### ISSUE TITLE
Row Reorder (drag & drop)

### ISSUE THREAD

**Issue by geemang2000** [tabalinas/jsgrid#1]
First off, very cool project. 

Are you planning to add drag / drop row re-ordering?

**Comment by tabalinas** [comment]
Thank you!

Yes, DnD is really significant functionality for grid.
I'm planning to implement it, however it's already possible now using $.fn.sortable, but it's more workaround.
Thank you for request.

**Comment by tabalinas** [comment]
I've created row reordering demo. You can find it on the demo page http://js-grid.com/demos/
It uses jQuery UI Sortable for rows reordering.

**Comment by tabalinas** [comment]
Decided not to implement this functionality as build-in since it's pretty simple to achieve it with jQuery ui sortable. Demos on the site cover this scenario.

**Comment by jmoleiro** [comment]
When i try to get the reordered rows using the .jsGrid("option", "data") method, i get the original data instead of the reordered. Any idea of what should i call after the $gridData.sortable execution to reflect the change on the data?
