### ISSUE TITLE
Prevent input field

### ISSUE THREAD

**Issue by teguh87** [tabalinas/jsgrid#100]
Hai..

Anyone no how to prevent any key input in input field such a letter or specialcaracter like space key, delete key, ect.

Best regards Teguh Santoso

**Comment by tabalinas** [comment]
This ticket should help https://github.com/tabalinas/jsgrid/issues/76 with handling event on the input inside grid field. 

To prevent different chars check out e.g. this SO answer http://stackoverflow.com/questions/3764821/best-way-to-restrict-a-text-field-to-numbers-only
