### ISSUE TITLE
How to load data on demand with paging ?

### ISSUE THREAD

**Issue by srganeshram** [tabalinas/jsgrid#1001]
Actually this is not an issue.

I want to know how to load data through ajax request based on the pages selected ?

Say for example
I have 1000 records in my database, I want to show only 10 at a time. When I click on the second page, it should load the next 10 records.

Hopes this understands. Please help me with example.

Thanks.

**Comment by srganeshram** [comment]
Any help ?

**Comment by heiovsky** [comment]
http://js-grid.com/demos/ - loading by page
ajax data loading -> google -> stackoverflow

**Comment by tabalinas** [comment]
@heiovsky, thanks for the lead!
