### ISSUE TITLE
Updating Perticular row Cell/column Value

### ISSUE THREAD

**Issue by vjkr14** [tabalinas/jsgrid#1002]
How to Set Cell value from an external method.

I want to set value of particular field say User, when I click on edit a popup is being displayed which searches users from database and returns selected value to particular row cell

I am stuck.. need urgent help.

**Comment by tabalinas** [comment]
You need to use `updateItem` method of the grid.
Checkout "Data Manipulation" demo http://js-grid.com/demos/ which uses external dialog to edit grid data.
