### ISSUE TITLE
jSGrid doesn't show correctly-fetched data

### ISSUE THREAD

**Issue by Racso** [tabalinas/jsgrid#1006]
Hi. Based on the examples, I'm trying to load some server-side data. It seems that the data is correctly fetched from the server, but it isn't being shown in the grid. Any help would be appreciated.

``` javascript
    $("#jsGrid").jsGrid({
        height: "70%",
        width: "100%",
        filtering: true,
        inserting: true,
        editing: true,
        sorting: true,
        paging: true,
        autoload: true,
        pageSize: 10,
        pageButtonCount: 5,
        deleteConfirm: "Do you really want to delete client?",
        controller: {
            loadData: function(filter) {
                return $.ajax({
                    type: "GET",
                    url: "Clientes.php",
                    data: item
                });
            },
            insertItem: function(item) {
                return $.ajax({
                    type: "POST",
                    url: "Clientes.php",
                    data: item
                });
            },
            updateItem: function(item) {
                return $.ajax({
                    type: "PUT",
                    url: "Clientes.php",
                    data: item
                });
            },
            deleteItem: function(item) {
                return $.ajax({
                    type: "DELETE",
                    url: "Clientes.php",
                    data: item
                });
            }
        },
        fields: [
            { name: "nombre", title: "nombre", type: "text", width: 150 },
            { name: "direccion", title: "direccion", type: "text", width: 150 },
            { name: "barrio", title: "barrio", type: "text", width: 200, filtering: false },
            { name: "administrador", title: "administrador", type: "text", width: 150 },
            { type: "control" }
        ]
    });
```

Data returned by Clientes.php is Content-Type:application/json:

`
[{"id":"91","nombre":"La Provincia","direccion":"Calle 1 # 2 - 3","barrio":"La Concordia","administrador":"Pepito P\u00e9rez"},{"id":"92","nombre":"BBQ","direccion":"Calle 123 # 232 - 3","barrio":"La Concordia","administrador":"Camilo Cristancho"},{"id":"93","nombre":"La Cechicher\u00eda","direccion":"carrera 1","barrio":"Cabecera","administrador":""}]
`

Result:

![grid](https://user-images.githubusercontent.com/26185386/35194532-213757e4-fe83-11e7-90a0-3ed472c7a84c.png)

**Comment by Racso** [comment]
I'm debugging the behaviour and this are my partial conclusions:

- The rows are there, just invisible.
- The `_refreshHeight` function seems to be hiding the cells. If I go to `_refreshSize` and disable the call to `_refreshHeight`, the cells appear. This probably means that the height isn't being calculated correctly.

**Comment by Racso** [comment]
Something I forgot to mention: I'm importing both `jsgrid.min.css` and `jsgrid-theme.min.css` as my only spritesheets.

**Comment by tabalinas** [comment]
Please checkout this answer https://github.com/tabalinas/jsgrid/issues/41#issuecomment-110103861

**Comment by Racso** [comment]
Sure, I saw it. The thing is that the table isn't showing even when using the CSS files you provide as default. Things should work out of the box. I suggest you to change those CSS files you provide as example.

**Comment by tabalinas** [comment]
As I answered here https://github.com/tabalinas/jsgrid/issues/41#issuecomment-110103861
The issue has nothing to do with jsgrid, this is how css height works. With correct css layout it works fine. If you'd like it to work for no layout, just specify fixed height. 
Getting started example uses fixed height and is going to work for any layout http://js-grid.com/getting-started/.
