### ISSUE TITLE
Nested JSGrid itemTemplate issue

### ISSUE THREAD

**Issue by bbhaskar07** [tabalinas/jsgrid#1007]
Hi I have a use case where i have a smaller grid inside another grid.
I am following the format in the below fiddle:
http://jsfiddle.net/tabalinas/w71odbyy/3/

However when the page loads i'm getting the following error:

HierarchyRequestError: Node cannot be inserted at the specified point in the hierarchy

```
 {name: "RESULTS", width: 100, itemTemplate: function( value, item){
   $grid =  $("div").attr("id", "jsGrid_catg0");
   $("#jsGrid_catg0").jsGrid({ 
     height: "auto",
     width: "90%",
     filtering: false,
     editing: false,
     data: item['RESULTS'],
     fields: [
        {name:"date", type:"text", width: 30},
        {name:"pass", type:"text", width: 30},
        {name:"fail", type:"text", width: 30},
     ]
    });

    return $grid
  }
```
If i comment out this field, every other column loads okay. Am I missing something here?

Thanks for this great tool!

**Comment by tabalinas** [comment]
Could you provide a jsfiddle reproducing the issue?

**Comment by bbhaskar07** [comment]
I figured out this issue, thanks for this great library!
