### ISSUE TITLE
http://js-grid.com/docs/#onitemupdated incorrect object name

### ISSUE THREAD

**Issue by willyann** [tabalinas/jsgrid#101]
sir:
i noticed that object name in 

```javascript
onItemUpdated
{
...
previuosItem
}
onItemUpdating
{
...
previuosItem
}
```

correct object name is "previousItem".

another issue is 
when  i try to update one row data but failed , then  i clicked "search" button not "x" button , wrong data will still keep on it. 
my config

```javascript
{
		    inserting: true,
		    filtering: true,
		    editing: true,
		    sorting: true,
	        autoload: true,
	        paging: true,
	        pageSize: 10,
	        pageButtonCount: 5
.....
}
```
thanks for your help

**Comment by tabalinas** [comment]
Thank you for the report. 
Docs is fixes. 
I've managed to reproduce the update issue.

**Comment by willyann** [comment]
wow! thank you sir.
