### ISSUE TITLE
how to add column names?

### ISSUE THREAD

**Issue by aicoutos** [tabalinas/jsgrid#1014]
how to add column names?

**Comment by heiovsky** [comment]
If reading is too hard for You, then You cant add column names

**Comment by aicoutos** [comment]
@heiovsky i need something like jqgrid http://www.ok-soft-gmbh.com/jqGrid/ColumnNamesAndTitelFromServer.htm

**Comment by aicoutos** [comment]
@heiovsky i'm reading the documentation but don't find anything about column names

**Comment by aicoutos** [comment]
@heiovsky i'm sorry. i'm wrote the code in PHP and don't see the fields part. thx.
![fields](http://imgur.com/uaoEzjMl.png)
