### ISSUE TITLE
Possible to use HTML entities inside "loadMessage" value?

### ISSUE THREAD

**Issue by UweKeim** [tabalinas/jsgrid#1016]
Inside [`loadMessage`](http://js-grid.com/docs/#loadmessage-default-please-wait), I want to use HTML entities like e.g. `&hellip;`.

Unfortunately, when doing so, the `&hellip;` is printed literally on my HTML page, instead of the expected `…`.

**My question:**

Is there any way to use HTML entites and have them rendered correctly?

**Comment by KarloX2** [comment]
You could try to encode this character using the \u code. E.g. "\u2026"

**Comment by UweKeim** [comment]
That does work, thanks a lot!
