### ISSUE TITLE
how to reload the jsgrid outside

### ISSUE THREAD

**Issue by parsonscp** [tabalinas/jsgrid#1019]
there are three controls in my page.  a tree ,jsgrid1,jsgrid2,when i click tree node then jsgrid1 load data ,click row of jsgrid1 then jsgrid2 load data. in general there are two relations : tree and jsgrid1.jsgrid1 and jsgrid2.i wanna konw when i click tree node how to reload the jsgrid2

**Comment by tabalinas** [comment]
If you'd like to reload data call `loadData` method on the grid `$("#grid").jsGrid("loadData");`.
