### ISSUE TITLE
How to make two grid - the master and detail

### ISSUE THREAD

**Issue by CrazyRedScorp** [tabalinas/jsgrid#102]
Sorry, my english isn't good. But! Thanks for this nice grid plugin.
Tell me please - how to make two grid the master and detail, in one page. I didn't find this in the documentation and in the demos.

**Comment by CrazyRedScorp** [comment]
I think, i can create a second div, with a new name. And in function "onclick" on the first table - send process for the filling of the secondary table. Right?

**Comment by tabalinas** [comment]
Thank you for the feedback!
Yes, it's good approach, pretty straightforward. Should work well.
