### ISSUE TITLE
Show empty grid on page load and then when on click of button load the records on the grid

### ISSUE THREAD

**Issue by Vikneshwarsmn** [tabalinas/jsgrid#1020]
Hi first of all thank you for this awesome pluggin. 

Im stuck a bit at a place. I have a page and in that page I have three tabs for Active, Pending and Deleted Users, each having a grid. Loading the data to the grid works like a charm. But for me what I want to do is, I want to load the data to the grid when ever that particular tab is clicked.

My default tab would be Active Users, so thats not a problem. But when I click on the tab "Pending Users" then only the grid should fetch the records from the server remotely and show them in the grid. Currently there are three ajax calls for each grid, even if i dont need them(most admins will look only at active users)

Is there something that can be done here?

**Comment by tabalinas** [comment]
Hi, thank you for the feedback.

The solution is to turn off autoload of grids with `autoload: false`, then load grid on `tabOpen` event with `loadData` method: http://js-grid.com/docs/#loaddatafilter-promise.

**Comment by leonardocastillo** [comment]
Hi, i use a loadData method, but i receive an error:  Uncaught TypeError: $(...).jsGrid is not a function

`   function actualizarGrid() {
                    $("#jsGrid").jsGrid("loadData");
            }`

Can help me ! Thanks.
