### ISSUE TITLE
I have a field no visible on the grid, how can I change the value data or have a default value? and filter this data?

### ISSUE THREAD

**Issue by barbaraws** [tabalinas/jsgrid#1022]
I have a field no visible on the grid, how can I change the value data or have a default value? and filter this data?

{ name: "id_agency", title: "Agency", type: "number", width: 3, visible: false },

Thank you

**Comment by tabalinas** [comment]
To change the value or set a default value use callbacks (http://js-grid.com/docs/#callbacks), like `onItemUpdating` and `onItemInserting`.
As for filtering, since it's up how you implement the implementation is also on your side. It can be an external field that you pass to filter in `loadData`.
