### ISSUE TITLE
Change value of filter-input before loadData

### ISSUE THREAD

**Issue by J-Setzer** [tabalinas/jsgrid#1023]
I'm new to this great project, thanks a lot for sharing!

**Question:**
How can I change the value of a filter-`input` before `loadData`?

I have a jsGrid with a `name`-field which can be filtered on server side. I'm using a **barcode scanner** which produces well defined strings, for example `xxx|1234|yyy|zzz`+`CRLF`. When placing the cursor into the `name`-input of the filter-row and scanning a barcode, strings like these are being written into the input field.

For server-side filtering I only need the numeric part `1234` of the incoming searchterm. I have already found out how to change the value of `filter.name` from `xxx|1234|yyy|zzz` to `1234` by defining the `filterValue`-function of the `name`-field. So this **can** be done before sending the request to the server using `loadData`.

But changing the value of `filter.name` does not affect the value of the input-field itself. The `input`-tag does not contain any `class` or `id`, so I cannot do something like `$('#id-of-the-input').val('1234')`. 

Can anyone help? Thanks in advance!
Jan

**Comment by KarloX2** [comment]
Maybe a more complex jquery selector expression could be used, something like e.g.

`$("#my-jsgrid .jsgrid-filter-row td:nth-child(3)>input")
`

to access the filter input of the 3rd column

**Comment by J-Setzer** [comment]
Good idea, @KarloX2, I will try.

**Comment by barbaraws** [comment]
You can use filtercss option of the [field config](http://js-grid.com/docs/#fields), then you call  $('.nameclass').val('1234')

**Comment by tabalinas** [comment]
@J-Setzer, hope @barbaraws or @KarloX2 suggestion worked. Please reopen if it's not the case.
