### ISSUE TITLE
onItemInserting not fire at first insert

### ISSUE THREAD

**Issue by devel0** [tabalinas/jsgrid#1028]
1. Bug Reports:
    A) onItemInserting fire
    B) onItemInserting called only for subsequent insert
    C)
![image](https://user-images.githubusercontent.com/13405008/35914186-af31cb88-0c02-11e8-8448-bc82687320d6.png)

**Comment by tabalinas** [comment]
The plus button above is just to toggle the insertion row, it shouldn't trigger the insert.
