### ISSUE TITLE
question (not really an issue)

### ISSUE THREAD

**Issue by edwardsmarkf** [tabalinas/jsgrid#1032]
hello - 

just when i thought that life could not possibly get any better, i find out about this totally awesome improvement:

```
<link type="text/css" rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jsgrid/1.5.3/jsgrid.min.css" />
<link type="text/css" rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jsgrid/1.5.3/jsgrid-theme.min.css" />
<link rel="stylesheet" type="text/css" href="demos.css" />
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jsgrid/1.5.3/jsgrid.min.js"></script>

```
proving once again that life does indeed just keep getting better and better!

my question, does the basic demo still really require this?

`<link rel="stylesheet" type="text/css" href="demos.css" />`

is there a cdnjs.cloudflare.substitiute for the demos.css?  could the basic example be changed to use a _cdnjs_ instead?

the more i use jsGrid the more **wonderful** it becomes, especially when i start seeing all the cool features in the documentation.

**Comment by tabalinas** [comment]
@edwardsmarkf, you don't really need `demos.css`. It's just for general styling of elements like  html/body/h1/h2/a/input. So I don't think there is a point in putting in on cdn.
