### ISSUE TITLE
Select current row, deselect others; change value cell, restore others.

### ISSUE THREAD

**Issue by CrazyRedScorp** [tabalinas/jsgrid#104]
I watched issue #38, It works. The style of the current row has changed.
Nice. But...
1. How to make the default style for the all other rows?
2. How to set the column "ColA" (in the current row, in rowClick function) new value of data, consisting of the other two columns (or calculate).
3. And restore the default value for the all other rows?
For example: http://jsfiddle.net/RedScorp/0m2n9Lkn/2/

Thank you.

**Comment by tabalinas** [comment]
1. remove the selected class for all rows before adding it to selected.

```javascript
        // remove class for all rows
        $("#jsgrid tr").removeClass("selected-row")
        
        // add class to highlight row
        $selectedRow.addClass("selected-row");
```

2 & 3. Use `updateItem` method http://js-grid.com/docs/#updateitemitemrowrownode-editeditem-promise
Calculated fields can be easily implemented with `itemTemplate`. Save current selected row to a variable and before updating new selected row, update old selected row.

**Comment by CrazyRedScorp** [comment]
Oh! It's so easy. Forgive me for inattentiveness. Thank you again.

**Comment by tabalinas** [comment]
It's ok. You are welcome!
