### ISSUE TITLE
input can insert,edit and display thousands separators 

### ISSUE THREAD

**Issue by santhoshdonthi** [tabalinas/jsgrid#1042]
Hi any one help me how to input text box can shows thousands separators in display , edit , insert in js grid 

ex: i am inserting text 100000000 i what to display 100,000,000 like this

**Comment by tabalinas** [comment]
Redefine `itemTemplate` and apply formatting. Look how to format numbers in google, see this answer  on SO for instance https://stackoverflow.com/a/14428340/1140893
