### ISSUE TITLE
Filtering problem

### ISSUE THREAD

**Issue by nelsonm24** [tabalinas/jsgrid#1053]
How can I filter my data with an array with numeric keys?
This is my example: http://jsfiddle.net/zzzfmpgt/269/

How is my loadData supposed to be?
Can anyone help? Thanks in advance!

**Comment by tabalinas** [comment]
Fields names indeed look weird (numbers instead of meaningful strings), but the idea is just the same as in the example: `filter["%%VAL%%"]` is going to be your filter value from the column.
