### ISSUE TITLE
Add record from database in batches (to already rendered JSGrid)

### ISSUE THREAD

**Issue by sharepointmike** [tabalinas/jsgrid#1056]
Hi Artem,

I really enjoy using JSGrid, thanks a lot for you effort.
I do have one question. I have a query which returns a lot of data. Even getting the data from the database takes too long. 

So now I first get the records from last year and build the grid. This is no problem at all. So the user can start working with the grid.

Meanwhile, I fire the second query to get the rest of the records.

Is there a way I can add the records to the grid without bordering the user?

Thanks a lot, Mike

**Comment by gdn11** [comment]
Hi Mike you can use pager may be to query less data. Changing page  start a new query

**Comment by sharepointmike** [comment]
Unfortunately, that does not solve my problem. The initial trip to the database takes to long. I think, even with paging, it gets all records. When I go to the next page. The same query runs again and again takes about more than a minute.

**Comment by gdn11** [comment]
You can load record by page by setting pageLoading to true and defining controller to query only needed records. Take a look [here](http://js-grid.com/docs/#controller).

**Comment by sharepointmike** [comment]
I must be doing something wrong. This is my code:
` $("#jsGrid").jsGrid({
        height: "auto",
        width: "100%",
        sorting: true,
        paging: true,
        autoload: true,
	pageLoading: true,
  	pageSize: 10,
		
	    controller: {
            loadData: function() {
                var d = $.Deferred();
                $.ajax({
                    url: "GetData.asp",
                    dataType: "json"
                }).done(function(response) {
                    d.resolve(response.data);
                });
                return d.promise();
            }
        },
 
        fields: [
            { name: "demo1", type: "text", title: "bla1" },
            { name: "demo2", type: "text", title: "bla2"}
        ],
    });
});`

GetData.asp returns a huge Json file. The time to generate te file is far too long. I tried your suggestions but not sure how to prevent the server from returning all records instead of a subset.

**Comment by heiovsky** [comment]
Answer this question:
- Did I send pageSize parameter to GetData.asp endpoint?

I will help you - you dont

    loadData: function(filter) {
                console.log(filter);  -> {pageSize:10,pageIndex:1} - you have to use this parameters in db query

                var d = $.Deferred();
                $.ajax({
                    url: "GetData.asp",
                    dataType: "json",
                    data:filter
                }).done(function(response) {
                    d.resolve(response);
                });
                return d.promise();
            }

**Comment by sharepointmike** [comment]
I use this to get my data:

```
set JSON = New JSONobject

Dim Orderlijst
Dim Orderlijst_cmd
Dim Orderlijst_numRows

Set Orderlijst_cmd = Server.CreateObject ("ADODB.Command")
Orderlijst_cmd.ActiveConnection = MM_FP_SQL_STRING
Orderlijst_cmd.CommandText = "{call dbo.sp_listdemo}

Set Orderlijst = Orderlijst_cmd.Execute

Response.ContentType = "application/json"

JSON.LoadRecordset Orderlijst

Response.Write(JSON.Write())

Response.End()
```
How do I adjust this to get the pagesize and pageindex parameters?

Sorry, I'm new in this area ;-)

**Comment by gdn11** [comment]
You must use a controller looking like this to send pagesize and pagenumber

`loadData: function(f) { 
   var skip = (f.pageIndex - 1) * f.pageSize;
   var d = $.Deferred(); 
   $.ajax({ 
      type: "GET",
      url: "GetData.asp",
      cache:false,
      dataType: "json",
      data:{
           start : skip,
           pagesize : f.pageSize,
           }}) .done(function(response) {
                      d.resolve({data:response.value,itemsCount:response["recordcount"]});})
               .fail(function(jqXHR, textStatus, errorThrown){
                      alert(jqXHR)};
   return d.promise();}`

on server side

you must request record to fill page so
 pagessize parameter give you records number and  start parameter position to start.

I don't know vb adodb object but i think you have to add your CommandText 

`CommandText +" top "+ Request["start"]+" limit "+ Request["pagesize"]`

**Comment by sharepointmike** [comment]
Thanks, I will sort this out!

**Comment by tabalinas** [comment]
The solution, as @gdn11 suggested, load data by pages. You are on the right track. The only thing to add here is you should return data from `loadData` in the following format: `{ data: [items], itemsCount: [total items count] }`
