### ISSUE TITLE
how to use font awesome with jsgrid for icons to keep consistent.

### ISSUE THREAD

**Issue by misschohoh** [tabalinas/jsgrid#1059]
I am trying to use the font awesome icon because the entire site I'm using is working off that. I can't seem to figure out how to incorporate font awesome as my icons instead of whatever jsgrid is using. 

It's really a shame they lumped the graphic into a global button used for everything that positions depending on the style. 

Anyways. I'd like to use the trash and edit icons from font awesome instead.

Does anyone have a really easy explanation of how to do this? 

I've seen a couple other questions but no one really explains exactly what to do.

Help please

**Comment by tabalinas** [comment]
This issue has a good example on how to do that https://github.com/tabalinas/jsgrid/issues/915
