### ISSUE TITLE
Cascading dropdwons 

### ISSUE THREAD

**Issue by umbundu** [tabalinas/jsgrid#106]
How are you? This is great work. I wonder if you support something like this in jTables.org:

This option is used to create cascaded dropdowns. If a combobox field depends on another combobox, jTable can automatically create cascaded dropdowns. See demo for usage.

Here, there is a sample usage of this option to provide Country/City cascade comboboxes?:

```javascript
CountryId: {
    title: 'Country',
    options: 'Demo/GetCountryOptions',
    list: false
},
CityId: {
    title: 'City',
    dependsOn: 'CountryId', //Cities depends on countries.
    options: function (data) {
        if (data.source == 'list') {
            //Return url of all cities for optimization. 
            return 'Demo/GetCityOptions?countryId=0';
        }
        //This code runs when user opens edit/create form or changes country combobox on an edit/create form.
        return 'Demo/GetCityOptions?countryId=' + data.dependedValues.CountryId;
    }
}
```

A field can be depended to more than one field. In this case, you can write fields seperated by comma as dependsOn: 'ContinentalId,CountryId' or as an array like dependsOn: ['ContinentalId', 'CountryId']

Thank you,
Everardo

**Comment by tabalinas** [comment]
In the following tickets you'll find samples, showing how to do it
https://github.com/tabalinas/jsgrid/issues/46
https://github.com/tabalinas/jsgrid/issues/71

**Comment by umbundu** [comment]
Thank you so much! I am taking your grid for a spin!

**Comment by tabalinas** [comment]
You are welcome!
