### ISSUE TITLE
jsGrid Need to dynamically set Validation on a field when another field option is selected.

### ISSUE THREAD

**Issue by jchooper12** [tabalinas/jsgrid#1066]
I have a jsGrid that has the following fields:

```js
fields: [
                    {
                        name: "StatusId",
                        type: "select",
                        title: "Status",
                        align: "center",
                        editing: true,
                        width: 100,
                        selectedIndex: "StatusId",
                        items: selectStatusData,
                        textField: "Name"
                    },
                    {
                        name: "InSuitStartDate",
                        type: "date",
                        title: "Start Date",
                        align: "center",
                        width: 80,
                        editing: true,
                        validate: {
                            validator: "required"
                        }
                    },
                    {
                        name: "InSuitEndDate",
                        type: "date",
                        title: "End Date",
                        align: "center",
                        width: 80,
                        editing: true,
                        validate: {
                            validator: "required"
                        }                                                
                    }
```

When ever I select a StatusId = Closed, I need to make sure the InSuitEndDate is required. If StatusId is not closed then InSuitEndDate should not be required.

I have invalidNotify implemented to display a message if required fields are not filled out but I am not sure how to toggle the required flag for InSuitEndDate. Any ideas?

**Comment by clratliff** [comment]
Did you ever find a solution. I'm facing the same requirement. If I find anything, I'll post back here.

**Comment by tabalinas** [comment]
The answer is to implement such a custom validation rule. `validate` supports custom function, where you can use current `item` to have validation depending on the data. Please checkout docs: http://js-grid.com/docs/#field-validation-config
Here is the source of the current `required` rule https://github.com/tabalinas/jsgrid/blob/master/src/jsgrid.validation.js#L76
