### ISSUE TITLE
How to filter data without a trip to the server?

### ISSUE THREAD

**Issue by sharepointmike** [tabalinas/jsgrid#1069]
Using a server call (Ajax Post call) a get a lot of records in my grid. 
This takes some time but it works fine.

Now I want to implement filtering. 
I now when I enter something in a filter box, the filter object gets populated and the LoadData gets called. I my case the LoadData does a request to the server to get the data (again), which take to much time. How can I prevent that and filter on the data I already have in my client?

**Comment by tabalinas** [comment]
You can combine client side and server side filtering. In `loadData` instead of calling server, data can be cached on client and filtered there.
