### ISSUE TITLE
File type column

### ISSUE THREAD

**Issue by fanturi** [tabalinas/jsgrid#107]
Hi,

Is it possible to have a file type column ?
In the table it could be just an image to allow users to download the file but in edition mode we should be able to add a file.

Is it already possible ?

Thanks.

**Comment by tabalinas** [comment]
Hi!

Yes, it's doable with custom field.

```js
// sample data
var data = [
    { Name: "John", Img: "http://placehold.it/250x250" },
    { Name: "Jimmy", Img: "http://placehold.it/250x250" },
    { Name: "Tom", Img: "http://placehold.it/250x250" },
    { Name: "Frank", Img: "http://placehold.it/250x250" },
    { Name: "Peter", Img: "http://placehold.it/250x250" }
];

// use FormData to upload files
controller: {
    ...,

    insertItem: function(insertingItem) {
        var formData = new FormData();
        formData.append("Name", insertingItem.Name);
        formData.append("Img[]", insertingItem.Img, insertingItem.Img.name);

        return $.ajax({
            method: "post",
            type: "POST",
            url: "/YourUrlToAddItemAndSaveImage",
            data: formData,
            contentType: false,
            processData: false
        });
    } 
},

fields: [
    // custom img file field
    {
        name: "Img",
        itemTemplate: function(val, item) {
            return $("<img>").attr("src", val).css({ height: 50, width: 50 });
        },
        insertTemplate: function() {
            var insertControl = this.insertControl = $("<input>").prop("type", "file");
            return insertControl;
        },
        insertValue: function() {
            return this.insertControl[0].files[0]; 
        },
        align: "center",
        width: 120
    },
    { type: "text", name: "Name" }
]
```

See the following fiddle:
http://jsfiddle.net/tabalinas/ccy9u7pa/16/

It shows how to create a custom field allowing to upload an image and a dialog for image full-size view.

**Comment by fanturi** [comment]
Hi,

Thanks for your response.
I would like to implement it with a dialog box for edition, could you help me ?

**Comment by tabalinas** [comment]
Sure, try to do it basing on the fiddle. It should be pretty similar to the inserting functionality. Fell free to ask if you have any questions.

**Comment by fanturi** [comment]
Hi,

I have a problem. My files are stored in a database.
So I have to get them with ajax.
How can I store them in the item object ?

Thanks for your help.

**Comment by tabalinas** [comment]
You could add an http handler (script) that will provide the file in a response. In this case you send only the link to the file in format `handler.php?file=<file_uid>` to the client side.

How to do it depends on your backend:

* for ASP.NET look at the answer http://stackoverflow.com/questions/1507572/streaming-databased-images-using-httphandler
* for php checkout this answer http://stackoverflow.com/questions/7793009/how-to-retrieve-images-from-mysql-database-and-display-in-an-html-tag

**Comment by fanturi** [comment]
hi,

It's ok to show the files, my problem is to upload the file in the database when the user want to add a new one.

In my saveClient function I have this extend :

```javascript
$.extend(template, {
  file_name: $("#file_name").val(),
  description: $("#description").val(),
  file_descr: $("#file_descr")[0].files[0],
  file_type: $("#file_descr")[0].files[0].type
});
```

And here the ajax call for the insert :

```javascript
$.ajax({
  url: "...",
  type: 'POST',
  dataType: 'json',
  data: {
    method: "insertTemplate",
    file_name: item.file_name,
    description: item.description,
    file_descr: item.file_descr,
    file_type: item.file_type
  },
  contentType: false,
  processData: false
}).done(function(response) {
  d.resolve(response[0]);
}).error(function(jqXHR, textStatus) {
  console.dir(jqXHR);
  console.log(textStatus);
});
```
I have this error message :

> No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://www.test.cc.cec' is therefore not allowed access. The response had HTTP status code 403.

Any ideas ?

thanks.

**Comment by fanturi** [comment]
ok I changed the code to use the formData like this in insertItem :

```javascript
var formData = new FormData();
						
formData.append("method", "insertTemplate");
formData.append("file_name", item.file_name);
formData.append("description", item.description);
formData.append("file_descr", item.file_descr);
formData.append("file_type", item.file_type);

$.ajax({
  url: "...",
  type: 'POST',
  dataType: 'json',
  data: formData,
  contentType: false,
  processData: false
}).done(function(response) {
  d.resolve(response[0]);
}).error(function(jqXHR, textStatus) {
  console.dir(jqXHR);
  console.log(textStatus);
});
```
Now I have a problem with the type of the file which is not recognized as a binary by the server but it's another problem and I will find the solution :)

Thanks for your help !

**Comment by fanturi** [comment]
I have another question.
Is it possible to prevent the rowClick event ?
I have a link in the table and when you click on it it opens the file.
But it opens also the dialog box to update the row.
I tried to put event.preventDefault() in the onClick function of the image but it doesn't work.

**Comment by tabalinas** [comment]
Yes, you need e.stopPropagation() in the link `click` event

**Comment by fanturi** [comment]
...
of course !

Thanks a lot ! everything's working now.
