### ISSUE TITLE
Looping through rows

### ISSUE THREAD

**Issue by saulmarg** [tabalinas/jsgrid#1075]
I need to validate data in the grid using Javascript.  I thought to use the data option of the grid to assign the results to an array, and then iterate through the array.  But it doesn't seem to assign the values in the jsgrid to the array.  My code is below.  I'd appreciate any assistance.

      function validateGrid() {
        //for each line, validate that start time is before end time
        var items = $("#jsgrid").jsGrid("option", "data");

        var arrayLength = items.length;
        for (var i = 0; i < arrayLength; i++) {
          alert(items[i]);
          //Do something
        }

      };

**Comment by mnanu** [comment]
I've tested your code and it worked.
Is your js-grid really named 'jsgrid'? maybe it's 'jsGrid' :smile: 
working example at: http://jsfiddle.net/hfct6gct/ (based on tabalinas fiddle)
see the output in browser console.

**Comment by saulmarg** [comment]
Please don't laugh, but that's exactly what the problem was!  

Doh!
