### ISSUE TITLE
Function to launch after refresh

### ISSUE THREAD

**Issue by fanturi** [tabalinas/jsgrid#108]
Hi,

It could be useful to be able to define a function to be launch after each refresh.
Will you implement it ?

Thanks.

**Comment by tabalinas** [comment]
There is a callback `onRefreshed`, see the docs http://js-grid.com/docs/#onrefreshed

**Comment by fanturi** [comment]
Thanks but have you an example how to use it ?
The documentation is poor for this part.
Is it possible to define a callback by default ?

**Comment by fanturi** [comment]
It's ok I found it.
You should clarify the documentation with some examples for noobies like me :)

**Comment by tabalinas** [comment]
Thanks for the suggestion!
