### ISSUE TITLE
how to get jsgrid column data

### ISSUE THREAD

**Issue by smcseah** [tabalinas/jsgrid#1086]
var data = $("#jsGrid").jsGrid("option", "data");
            console.log(data);

the output i get is 
(7) [{…}, {…}]
0
:
{String Found: "Random String 1", Replace Text: "Hello World!!", Id: 0}
1
:
{String Found: "Random String 2", Replace Text: "Good Morning", Id: 1}
 
how do I get the replace text and without the title

sorry for my bad english

**Comment by mnanu** [comment]
``data``
is a javascript array. Have a quick look over Arrays. Maybe you can start here: https://www.w3schools.com/js/js_arrays.asp

something like this might work (didn't try myself)
``console.log(data[0]['Replace Text'])``
should show ``Hello World!!``

**Comment by smcseah** [comment]
This is what I want

Thanks
