### ISSUE TITLE
Edit multiple items at once

### ISSUE THREAD

**Issue by andyjhall** [tabalinas/jsgrid#109]
Is it possible to put multiple (or all) items into 'Edit' mode at once?  Or alternately is it possible to have a key (such as tab) skip to the next item in the list? So I could edit item 1 <tab> item 2 <tab> etc.

**Comment by tabalinas** [comment]
No, only one row can be edited at a time.

Any row can be edited with `editItem`. This method accepts HTML element or jQuery element of the row `<tr>`. So you can implement logic handling keyboard keys `onkeypress` event.
