### ISSUE TITLE
How to define default options

### ISSUE THREAD

**Issue by fanturi** [tabalinas/jsgrid#11]
Hi,

I would like to define defaults option for all jsgrid I'm using on my website.
How can I do that ? Is it possible without change the options in jsgrid.js directly ?

Thanks for your work.

**Comment by tabalinas** [comment]
Hi, 

Yes, you can do it with following code

````javascript
$.extend(jsGrid.Grid.prototype, {
     // default options here
});
````

Gonna add special method for this.
Thank you for request.

**Comment by fanturi** [comment]
it's great.
is it possible to define default option for control column type too ?
since you have labels in options it's a good idea to allow a special method to define this option for translation.

thanks.

**Comment by tabalinas** [comment]
Yes, it's possible for fields in the similar way

````javascript
$.extend(jsGrid.fields.checkbox.prototype, {
     // default options here
});
````

You can define option of any other build-in field, just specify its name instead of `checkbox` (`text`, `textarea`, `number`, `select` or `control`).
I completely agree with you, this should be considered to make localization easier.

**Comment by buttflattery** [comment]
hi can you give any reference to the document where this is listed @tabalinas
