### ISSUE TITLE
row style on mouse over

### ISSUE THREAD

**Issue by vahidhiv** [tabalinas/jsgrid#110]
Hi, i want to add class to row when mouse enters that row (onmouseenter), and remove that class when mouse leaves (onmouseleave).
Is it possible? Do you have any function to control row style?
any help would be appreciated.

**Comment by tabalinas** [comment]
To be able to highlight row on hover provide an option `selecting=true`. To change the class attached to the hovered row specify the option `selectedRowClass: 'my-grid-row-selected-class-name'`.

**Comment by vahidhiv** [comment]
Thanks for your answer, i solved my problem sing a trick, i wanted just a column to hide the current element and show another, i did this by adding element in data provider (i use json as data) and hide the current element when row is selected. Anyway i appreciate your attention, thank you.

**Comment by tabalinas** [comment]
You are welcome!

**Comment by sandy3004** [comment]
any demo link for the same

**Comment by codelikeamexican** [comment]
Hopefully this helps :)
I changed the class that was pointing to the class selected row on the jsgrid.min.js file.
Instead of ".jsgrid-selected-row" I did changed to ".jsgrid-selected-row1"

on my stylesheet
```

.jsgrid-selected-row1 > .jsgrid-cell {
    border-color: #f5f5f5 !important;
    background-color: #f5f5f5 !important;
}

```

**Comment by codelikeamexican** [comment]
> any demo link for the same
Hopefully this helps :)
I changed the class that was pointing to the class selected row on the jsgrid.min.js file.
Instead of ".jsgrid-selected-row" I did changed to ".jsgrid-selected-row1"

on my stylesheet


```
.jsgrid-selected-row1 > .jsgrid-cell {
    border-color: #f5f5f5 !important;
    background-color: #f5f5f5 !important;
}
```
