### ISSUE TITLE
Custom field

### ISSUE THREAD

**Issue by ramin-rp** [tabalinas/jsgrid#111]
Hello,
Is it possible to have column with button element ?

**Comment by tabalinas** [comment]
Yes, just specify `itemTemplate` function in field [config](http://js-grid.com/docs/#fields). Or if you want a field to be used for several grids  define your custom field [see more here](http://js-grid.com/docs/#custom-field).

See the sample fiddle http://jsfiddle.net/tabalinas/nove9aww/
