### ISSUE TITLE
Symbol of "Enter" in the json data

### ISSUE THREAD

**Issue by CrazyRedScorp** [tabalinas/jsgrid#112]
Good day. And again, I am.
My grid receives data via json. But there are multi-line records, separated by "Enter". See the example <a href="http://jsfiddle.net/RedScorp/zk03do2o/2/">jsfiddle.net</a> in row with id = 8.
I think the problem is not in the grid. I think - in the processing JSON. But I do not know how to fix it. Tell me, how can I do? Thanks!

**Comment by CrazyRedScorp** [comment]
Excuse me. But, I found a solution - it is necessary to replace the character "enter" to "<br>". Example <a href="http://jsfiddle.net/RedScorp/zk03do2o/3/">jsfiddle.net>/a>.

**Comment by tabalinas** [comment]
Glad you worked it out.
