### ISSUE TITLE
[Help request] unable to show data in grid

### ISSUE THREAD

**Issue by iahmedani** [tabalinas/jsgrid#1126]
I'm trying to have information via controller, everything looks fine, i also can access data from ondataLoaded but stil not visible in grid.

here is my code:

promise to get info

`let myFirstPromise = new Promise((resolve, reject) => { 
    ipc.send('get');
    ipc.on('get',(e, result)=>{
            if(result.err){
        reject(result.err)
      } else {
        resolve(result.result)
      }
    })
  })`

`$("#jsGrid").jsGrid({
    height: "70%",
    width: "100%",
    filtering: true,
    inserting: true,
    editing: true,
    sorting: true,
    paging: true,
    autoload: true,
    pageSize: 10,
    pageButtonCount: 5,
    deleteConfirm: "Do you really want to delete client?",
    fields: [
        { name: "name", type: "text", width: 150 },
        { type: "control" }
    ],
    controller: {
        loadData: function(filter) {
          // ipc.send('data');          
          return myFirstPromise      
                      
        },
        insertItem: function(item) {
            return $.ajax({
                type: "POST",
                url: "/clients",
                data: item
            });
        },
        updateItem: function(item) {
            return $.ajax({
                type: "PUT",
                url: "/clients",
                data: item
            });
        },
        deleteItem: function(item) {
            return $.ajax({
                type: "DELETE",
                url: "/clients",
                data: item
            });
        }
    }, onDataLoaded: function(data) {
      console.log(data);
    }
});`

data logged in from onDataLoaded

`Object {data: Array(2), grid: d}`

Please help

**Comment by heiovsky** [comment]
Data object  should be {data:[],itemsCount:0}

**Comment by iahmedani** [comment]
@heiovsky  done but still issue persists

![image](https://user-images.githubusercontent.com/17918895/40554436-21e9d156-605f-11e8-84b4-ea139aa7a19e.png)

**Comment by heiovsky** [comment]
Put this on jsfiddle and i will take a look


pt., 25.05.2018, 18:04 użytkownik Imran Khan <notifications@github.com>
napisał:

**Comment by iahmedani** [comment]
@heiovsky  thanks for your support here it is.

https://jsfiddle.net/f5fd11xn/

**Comment by heiovsky** [comment]
https://jsfiddle.net/f5fd11xn/3/

**Comment by iahmedani** [comment]
@heiovsky  Many thanks dear, you are an angel for me :) it's working now

**Comment by iahmedani** [comment]
Thanks to @heiovsky , great support
