### ISSUE TITLE
Placing the jsGrid div inside another div does not work properly

### ISSUE THREAD

**Issue by ghooo** [tabalinas/jsgrid#113]
for example in `demos/basic.html` replace
```html
 <div id="jsGrid"></div>
```
with
```html
    <div>
        <div id="jsGrid"></div>
    </div>
```
The table will not appear.

I can make it work by making the parent div height be 100%
```html
    <div style="height:100%>
        <div id="jsGrid"></div>
    </div>
```

**Comment by tabalinas** [comment]
Checkout the answer for the issue https://github.com/tabalinas/jsgrid/issues/41

**Comment by ghooo** [comment]
Thanks a lot. (Y)

**Comment by tabalinas** [comment]
You are welcome!
