### ISSUE TITLE
Default sort order with pageLoading:true

### ISSUE THREAD

**Issue by ryanrozich** [tabalinas/jsgrid#115]
I have a jsgrid table which loads data from an AJAX request by setting pageLoading:true and autoLoad:true. I also have sortable:true and sorting works when I click on columns. There is a default sort order that I would like to implement so I don't need to make two roundtrips (1) to load the table and (2) to sort when clicking on the column header.  

Is there a way to set the default table sort field and sort order when the table first loads so that the filter object sent into the loadData function has the appropriate filter.sortField and filter.sortOrder?

**Comment by tabalinas** [comment]
You can set `autoload: false` in config, init the grid and then call `sort` method http://js-grid.com/docs/#sortsortconfigfield-order-promise
