### ISSUE TITLE
Methods for showing and hiding loadIndicator

### ISSUE THREAD

**Issue by ivanvastag** [tabalinas/jsgrid#116]
It would be very helpful to add a trigger method for showing and hiding loadIndicator. I couldn't manage to do it if it's already available.

**Comment by tabalinas** [comment]
There are methods for this, but it's not in api. These are `_showLoading()` and `_hideLoading()`. You can call them to solve the problem.
Could you share your case, to make it clear why you need it? So that maybe it's really worth to publish them.

**Comment by ivanvastag** [comment]
I have a request-response data manipulation. I'm waiting for response before actually inserting in table so in that case it would be useful for me to trigger showLoading and hide it when response arrives.

**Comment by tabalinas** [comment]
If data manipulation request is done within the controller, then loading indication should just work. Do you have loading outside the controller?

**Comment by ivanvastag** [comment]
I'm using websockets so I'm not sure if I'm able to do it within controller since controller methods are not blocking inserting as I understood. So I'm using onItemInserting, onItemUpdating to block inserting and set event listeners for response after which I trigger them and reinsert into table. Am I missing something?

**Comment by ivanvastag** [comment]
I've managed to call _showLoading() and _hideLoading() so that worked for me anyways. I can work with that if you don't feel like publishing it into API.

**Comment by tabalinas** [comment]
I think if you turn work with websockets in promise-way (e.g. http://stackoverflow.com/questions/25235784/javascript-angularjs-websocket-with-promises) then you can put it into the controller methods.

**Comment by ivanvastag** [comment]
Thank you for the response and link.

**Comment by wonsuc** [comment]
In my case if user click a hyperlink from a row, the detail data will be retrieved from server via ajax. During the networking I have to disable let user click another hyperlinks.
