### ISSUE TITLE
Key navigation

### ISSUE THREAD

**Issue by dav-m85** [tabalinas/jsgrid#117]
Is there a way of navigating the datagrid with shortcut keys, like in Gmail for example ?

Type i go up, j go down, x selects the current row, and so on...

**Comment by tabalinas** [comment]
This is really good point. Keyboard support is in a roadmap, but currently is not supported out-of-box. Now it should be done by developer manually: add tab-index to necessary elements and attach handlers for the particular keys.

**Comment by dav-m85** [comment]
OK, thanks for the quick answer :)
