### ISSUE TITLE
editTemplate: how to access the updated data?

### ISSUE THREAD

**Issue by RevealedFrom** [tabalinas/jsgrid#1186]
If I have an `editTemplate`, how does the updated data get passed back to jsGrid, or how do I access the updated values from `updateItem`?

For example, just for example, I have:

    fields: [
            { name: "name", type: "text", title: "Name", 
                    editTemplate: function(value, item) {
                                             return "<input type='textbox' value='value'>";
                                           }},
            { type: "control" }
            ]

What happens to the text I type in the textbox?

**Comment by flymikeG** [comment]
The function attached to editTemplate is executed while the item to be edited is being _rendered_. Once the item is rendered, and after you have updated the text box _and_ clicked the checkmark icon, the updated value will be available to your updateItem method of the grid controller.
