### ISSUE TITLE
Stay on same page when deleting an item

### ISSUE THREAD

**Issue by ivanvastag** [tabalinas/jsgrid#119]
My `loadData()` is returning promise and every time I delete an item it goes on page 1. 
I have `pageLoading: true` and I tried also tried `onItemDelete()` and `controller.itemDelete()` to call `grid.loadMethod()` with different `pageIndex` and `pageSize` values

Is that even posible?

**Comment by tabalinas** [comment]
This behavior is defined by load strategy of the grid. You can find how to implement your desired behavior in the docs http://js-grid.com/docs/#custom-loadstrategy.
