### ISSUE TITLE
Required field for edit/insert mode

### ISSUE THREAD

**Issue by fanturi** [tabalinas/jsgrid#12]
Hi,

Is it possible to add a new option for the fields: required.
Or maybe there is a way I didn't see ?

A simple possible behavior could be :

* Add a visual element to distinct required fields ('*' for example).
* Add a visual element for empty required fields (red border for example).
* Remove the red border if the user set a field.
* Until all required fields are set disabled the check mark icon or the plus sign icon.

With this solution you avoid a complex implementation with messages.

**Comment by tabalinas** [comment]
Yes, validation is an upcoming feature.

**Comment by tabalinas** [comment]
JFYI: The `Data Manipulation` demo on the demos page http://js-grid.com/demos/ now shows how to use jQuery Validation to validate the form.
