### ISSUE TITLE
How to get the grid instance or its data property from a validator?

### ISSUE THREAD

**Issue by emptyVoid** [tabalinas/jsgrid#1202]
I'd like to enforce uniqueness on values of a field/column, and afaict validator is provided only with the item it validates. Is there any way to get access to all items from a validator?

**Comment by bfayette** [comment]
You should custom validator and use param when you are defining your validators. You can put whatever you want 
see custom validation http://js-grid.com/docs/#validation
`{
    validator: string|function(value, item, param), // built-in validator name or custom validation function
    message: string|function,                       // validation message or a function(value, item) returning validation message
    param: any                                      // a plain object with parameters to be passed to validation function
}`

**Comment by emptyVoid** [comment]
Sorry, I don't understand how  ```param``` is supposed to provide the access to grid's items.

**Comment by bfayette** [comment]
Sorry it was not clear. Hope below will be more explicit.

In param you can add your grid id html component which will allows you to retrieve the grid from the global context. You can also pass the jquery grid object $('#yourGridId'). 

You could also override the grid callback method [onInit] which is called once to attach any contextual objects. You can then assign the grid object to your validator. I guest you could loop over grid fields, look for validator property and modify it as you want it

**Comment by emptyVoid** [comment]
Global variables is a no-go in my use case: I use multiple grids which are created by a factory, and I see no sane way to establish relation between grid and validator instances on the global scope.

**Comment by bfayette** [comment]
say you have defined your custom with a grid object which will be initialized on the init method
`jsGrid.validators.mycustomValidator = {
    grid : undefined
    message: "",
    validator: function(value, item) {
        this.grid.yourFunctionToCall()
    }
}`

and then later
`$("#grid").jsGrid({
    ...
    
    onInit: function(args) {
        var $this = this;
        gridInstance = args.grid;
        $.map($this.fields, function(fld, idx){
            //do whathever you want now with the field and the grid to modify the validator before it gets run
        });
    }
});`

Just an example but I think sky is your limit here. You get the data or you can access the grid configuration and so on

**Comment by emptyVoid** [comment]
Your solution is good to establish correspondent between validator and grid instances, though now I can't seem to find a way to differentiate between insert and edit operations, so that uniqueness validation won't prevent from editing an item.

**Comment by bfayette** [comment]
That's something different from your original question. But this usecase, you just have to access to data property of the grid instance. This is array of your plain js Object. You just have to verify if new (insertion) or else updating.

By the way, instead of using onInit or other callback methods to pass grid to your objects,  I find that someone can just define any property with a function which gives you access to parent context because the lib with call a method getOrApply which gives you access to the given context . 

**For instance instead of : **

`$("#grid").jsGrid({
   controller : {
      ---your controller methods;
    }
})
`
You could use
`$("#grid").jsGrid({
   controller : function(){
        var gridInstance= this;
        controller : {
             ---your controller methods;
         }
     }
})`

Please validate for other properties or sub-properties, I does work controller properties and the grid. But I did not verify if this would direct access of field within validators instances.

**Comment by emptyVoid** [comment]
> That's something different from your original question. But for this usecase, you can just access to data property of the grid instance. This is array of your plain js Objects. You just have to verify if not exists i.e new (insertion) or else update operation.

Right, sorry... I thought gaining access to the grid's instance would let me identify the item being edited. Though that's not the case with ```jsGrid``` since neither the item passed to validator nor any of the grid's properties reference the original item.

Anyways, thanks for the help!
