### ISSUE TITLE
How to Change "pageSize" by code?

### ISSUE THREAD

**Issue by FBoucher** [tabalinas/jsgrid#1215]
I'm trying to have a little dropdownlist with different values (10,50,100) and when the user select one I would change the pagesize.

```
<div id="jsgrid"></div><select id="pagelength">
    <option>10</option>
    <option>50</option>
    <option>180</option>
</select>
```

```
var selectedPagelength = 15;

 $("#pagelength").change(function () {
    onPageLenghtSelect($(this).val());
});

function onPageLenghtSelect(newLenght) {
    selectedPagelength = newLenght;
    $("#instancedata-grid").jsGrid("refresh");
}

$("#instancedata-grid").jsGrid({
                autoload: true,
                sorting: true,
                paging: true,
                pageSize: selectedPagelength,
                pageButtonCount: 5,
               ....
```
Nothing changes. I try "render" instead of refresh... same result.
If I recall my  $.getJSON it works, but then I when back to the server.... I don't need calling my api to get new data I just want to change the number of line displayed.

**Comment by bfayette** [comment]
Please review project doc regarding calling instance methods 
http://js-grid.com/docs/#methods

Basically you should use create an instance method as this
`$("#jsGrid").jsGrid({
     //your grid configuration or custom properties

    //your grid extension methods
    changePageSize : function(pageSize){     
       //you have access to all internal grid method
       var $this=this;
        $this.pageSize=pageSize;
      //Probably you will have to refresh the grid or other stuff
    }
})
`

And then call your new fleshmethod
var myPageSize= [get where everyou want]
 $("#grid").jsGrid("changePageSize", myPageSize);

That should work. I DO NOT TEST IT. 
THANKS

**Comment by FBoucher** [comment]
Fantastic, it works!

Here what I did:

```
    <span id="pageResizer" class="jsgrid-pager-page">
        <select id="pagelength">
            <option>15</option>
            <option>30</option>
            <option>60</option>
            <option>180</option>
        </select>
    </span>
    <div id="instancedata-grid"></div>

    <script type="text/javascript">
        function onPageLenghtSelect(newLenght) {
            selectedPagelength = newLenght;
            $("#instancedata-grid").jsGrid("changePageSize", selectedPagelength);
        }

        $("#instancedata-grid").jsGrid({
            autoload: true,
            sorting: true,
            paging: true,
            pageSize: selectedPagelength,
            pageButtonCount: 5,
            changePageSize: function (pageSize) {
                var $this = this;
                $this.pageSize = selectedPagelength;
                $this.refresh();
            },
            ...
        });

        $("#pageResizer").prependTo(".jsgrid-pager");
    </script>
```

**Comment by FBoucher** [comment]
Closing the answer from @bfayette answered my question.

**Comment by bfayette** [comment]
Glad it works for you. But you should use method parameter pageSize instead of the global variable selectedPagelength within.  
` changePageSize: function (pageSize) {
                var $this = this;
                $this.pageSize = pageSize;
                $this.refresh();
            },`

**Comment by FBoucher** [comment]
Yeah that's what I did. Bad copy paste.
and I used the pagerContainer: property instead of the jquery to get the dropdown inside the pager section.
