### ISSUE TITLE
how to get all JsGrid edited table data and send to server to process it.

### ISSUE THREAD

**Issue by sreekanth895** [tabalinas/jsgrid#122]
how to get all JsGrid edited table data and send to server to process it.

**Comment by tabalinas** [comment]
Could you be more specific? What exactly you try to accomplish? Basic samples available on the project page is not enough? http://js-grid.com/demos/

**Comment by sreekanth895** [comment]
Actually, i need to send all edited data of jsGrid table to server.to process/save in data base.

**Comment by tabalinas** [comment]
You can get all data from `data` option. Is it what you are looking for?

**Comment by RonakKosamia** [comment]
hi tablinas, 

can you help me with this issue.  m eding few rows in jsgrid, when i click on "submit" button , only those edited rows should get submitted on server.  i have more than 5000 records in a grid and i can not save all of them (will take a lot time). i just want to submit rows that edited by user.   any idea??

**Comment by tabalinas** [comment]
@RonakKosamia, not sure we should discuss it in this issue, but briefly in `updateItem` of controller set field e.g. `item.isEdited = true`. Once you submit data filter out only edited items. This should do the trick.

**Comment by ngordiz** [comment]
I have the same problem.  Using  var items = $("#jsGrid").jsGrid("option", "data" );  items contain data read from the database not changed data in the grid.

**Comment by tabalinas** [comment]
@ngordiz, not sure I understand, once you edit data they are updated in `data` option. So this should be actual items. Probably you have specific configuration or just your case is not clear to me.
If you will provide your code sample, please, open a separate issue.
