### ISSUE TITLE
jGrid inside tabs

### ISSUE THREAD

**Issue by danielgrom** [tabalinas/jsgrid#123]
I'm having a problem with misaligned content inside jsgrid when I put it inside jquery tabs, any ideas? The first one shows OK, but the others I have to sort the columns by clicking a header to fix it.

**Comment by tabalinas** [comment]
grid cannot calculate sized being placed in the hidden div. To fix this behavior call `refresh` method on tab open. Here is similar ticket for bootstrap tab: https://github.com/tabalinas/jsgrid/issues/49

**Comment by danielgrom** [comment]
thanks!

**Comment by tabalinas** [comment]
You are welcome!
