### ISSUE TITLE
Is there a way to control grid on column basis 

### ISSUE THREAD

**Issue by hasanjaved41** [tabalinas/jsgrid#1232]
Hi,
Is there a way to cancel editing for a particular column.
Means disable edit mode when click on a particular column.

**Comment by BrahamMounir** [comment]
Hi, 
   you can just set the editing option for the specific field :
   
  fields: [
        { name: "FieldName", title: "column designation", type: "text", editing: false },
or you can just omit the type
       { name: "FieldName", title: "column designation" },

hope it helps;

**Comment by hasanjaved41** [comment]
Thanks for your reply. I achieved this by using different approach, This also works.
