### ISSUE TITLE
Column with no width specified gets fixed to 100px

### ISSUE THREAD

**Issue by tplecko** [tabalinas/jsgrid#1236]
When I define grid columns, and specify width for all columns but one, the One column gets fixed to 100px which results in all columns width being calculated by browser (in regard to set value), thus all columns change width when window width changes.

Expected behavior is that all columns with width set become fixed width, and the one (or more) column(s) with no width value fill the remaining table space.

Can be reproduced with this code

        fields: [
            { name: "Name", type: "text", title: "Naziv"  },
            { name: "Mbs", type: "text", width: 24, title: "MBS"  },
            { name: "PB", type: "text", width: 23, title: "PB"  },
            { name: "OIB", type: "text", width: 34, title: "OIB"  },
            { name: "Country", type: "text", width: 35, title: "Država"  },
            { name: "City", type: "text", width: 35, title: "Grad"  },
            { name: "ActiveFrom", type: "text", width: 28, title: "Od"  },
            { name: "ActiveTo", type: "text", width: 28, title: "Do"  },
            { name: "Active", type: "checkbox", width:10, title: "A" }
        ],

Setting column width to "auto" or "*" results in it filling 90% of the table ,and the rest are shrunk to 10px, with css still showing original set values.

**Comment by tplecko** [comment]
At least one column width must be set to "auto", before trying to render the table. If no width is set, it defaults to 100px, thus breaking the desired appearance.
Documentation showed many defaults but this one.

Just my luck. I waste a hour on something so trivial, and when i decide to ask here, i find the solution and wish to delete the shame of this issue.

**Comment by djdance** [comment]
thanks :-)
single "auto" helps to fix another widths
