### ISSUE TITLE
The custom filter values provided in loadData([filter]) does not reflect in the searchboxes in the grid

### ISSUE THREAD

**Issue by StefH** [tabalinas/jsgrid#124]
When doing this custom search action:

```js
    // loadData with custom filter
    $("#grid").jsGrid("loadData", { Name: "John" }).done(function() {
       //
    });
```

The loaddata is executed correctly, but the search box for the **Name** column is *not* updated with the value "John".

How to get this working ?

**Comment by tabalinas** [comment]
Now it's not supported. We mentioning this functionality here https://github.com/tabalinas/jsgrid/issues/81
