### ISSUE TITLE
The fields "text" and "number" set default value in the filter when no value has been entered by the user

### ISSUE THREAD

**Issue by StefH** [tabalinas/jsgrid#125]
For the **jsgrid.field.text**, when the user does not search for this column, the filter still contains the default value ("" = empty string).

My proposal is to modify the filterValue function into:

``` js
filterValue: function() {
  return this.filterControl.val() !== "" ? this.filterControl.val() : undefined;
}
```

When do value is entered, this will return **undefined**.

Same as in the _CheckboxField_ code:

``` js
filterValue: function() {
    return this.filterControl.get(0).indeterminate ? undefined : this.filterControl.is(":checked");
},
```

Same for the **jsgrid.field.number**, the default value contains a integer 0 when the user does not search on this.

But if this change breaks the implementation, it's maybe better to add a property named **filterValueHasValue** like this:

``` js
filterValueHasValue: function() {
    return this.filterControl.val() !== "";
},
```

**Comment by tabalinas** [comment]
In checkbox we have this implementation, because we need third state, `true/false` is not enough. Empty filter field value can be easily handled just like `undefined`. Moreover, this is real input value, no magic involved. Why you think `undefined` is better than empty string?

**Comment by StefH** [comment]
In case of empty string, you can indeed discuss that this is fine, however for an integer, the default value would be 0, which does not differ from a real 0 value, if you want to search for for all products which are sold out (number-in-stock=0) for example.

So for integer values, returning 'undefined' would be the best option. And if you build it for checkbox and integers, maybe it's best to build the same logic for all types.

**Comment by tabalinas** [comment]
For number field, it sounds really reasonable.

**Comment by osamahq** [comment]
@tabalinas  I cant implement search for number field because I cant recognize if the user entered 0 or the number field is empty !!! thank you for your efforts

**Comment by tonisostrat** [comment]
As this `bug` is currently open you can/have to implement the proposed change in OP in your own code as a temporary work-around.
