### ISSUE TITLE
how to get itemcount in pagerRenderer

### ISSUE THREAD

**Issue by fangchenhui3** [tabalinas/jsgrid#1255]
I want to use itemCount in pagerRenderer,No itemCount in the parameter of pageRenderer.
I try to use it in this way ,But it seems no work!

the configuration is:
`pagerRenderer: jsGridPage,`

the function is:
```
function jsGridPage(data){
    var pageIndex = data.pageIndex;
    var pageCount = data.pageCount;
    return "<div>{itemCount}</div>";
}
```

Anyone can help?

**Comment by BrahamMounir** [comment]
Hi ;
A solution on the fly is to use onDataLoaded to get itemCount from the “data”
I did not test, but i made somthing similar and woks fine, for me,

 it hope it helps, 
 
```
pagerRenderer : function (args){ 
return "<div><span id="span_item_count">{itemCount}</span></div>";}

onDataLoaded: function (args) { 
$("#span_item_count ").html(args.data.length) }

```

**Comment by fangchenhui3** [comment]
> Hi ;
> A solution on the fly is to use onDataLoaded to get itemCount from the “data”
> I did not test, but i made somthing similar and woks fine, for me,
> 
> it hope it helps,
> 
> ```
> pagerRenderer : function (args){ 
> return "<div><span id="span_item_count">{itemCount}</span></div>";}
> 
> onDataLoaded: function (args) { 
> $("#span_item_count ").html(args.data.length) }
> ```

Thank you for your reply !
It works !
args.data.itemsCount

**Comment by fangchenhui3** [comment]
`onDataLoaded: function(args){
        args.data.itemsCount
}`
