### ISSUE TITLE
Add support for Logical Operators in the filter

### ISSUE THREAD

**Issue by StefH** [tabalinas/jsgrid#126]
Like
Equals = "eq"
Not Equals = "nq"
Less Than or Equal = "le"

and so on... like supported in odata: https://msdn.microsoft.com/en-us/library/hh169248%28v=nav.90%29.aspx

**Comment by tabalinas** [comment]
Filtering should be implemented by developer whether on the client in controller code or on the server with script code (maybe even mixed approach).

**Comment by StefH** [comment]
It would be nice if you could support something like is done in http://www.guriddo.net/demo/bootstrap/


![2015-10-29_21h15_59](https://cloud.githubusercontent.com/assets/249938/10830958/e5c3ef06-7e82-11e5-94ac-c5116fc3151c.png)

Some example prototype code in the **field.text** could be:
```js
filterTemplate: function() {
            if(!this.filtering)
                return "";

            var grid = this._grid,
            $result = this.filterControl = this._createFilterTextBox();
          // . . . 

            return $result;
        },

_createFilterTextBox: function() {
            var div = $("<div>");
            
            var menu = $("<div>").hide();
            menu.append("<ul><li>==</li><li>^</li><li>&lt;</li></ul>");
            
            var href = $("<a />", {
                name : "link",
                href : "#",
                text : "=="
            }).css("float", "left").click(function() {
                
                $(this).find("div").slideToggle("fast");
            });
            
            href.append(menu);
            var edit = $("<input>").attr("type", "text").css("float", "left");
            
            div.append(href).append(edit);
            
            return div;
        }
```

And the using this in the grid would be like:
```js
$("#jsGrid").jsGrid({
  fields: [
    { name: "Name", type: "text", filterOptions: ["==", "^", "&lt" ] },
  ]
});
```

Do you understand ?

**Comment by tabalinas** [comment]
Yes, I understand. This could be really good feature. For now I have few more necessary stuff to implement: like validation, keyboard support and others. This definitely something for future.

**Comment by StefH** [comment]
Which development environment do you use to develop this ?

**Comment by tabalinas** [comment]
You mean IDE?

**Comment by StefH** [comment]
Yes IDE

**Comment by tabalinas** [comment]
WebStorm
