### ISSUE TITLE
Filtering Select

### ISSUE THREAD

**Issue by bvasnake** [tabalinas/jsgrid#1261]
Hi,
how i can implement this technology http://jsfiddle.net/tabalinas/yef3xwh4/25/ using data bases

my code:
$(function () {

$.ajax({
		type: "GET",
		url: "ntd/index.php?type=" + type + ""
	})
	.done(function (ntd) {

		ntd.unshift({
			id: "0",
			name: "Все"
		});

		$.ajax({
				type: "GET",
				url: "sortament/index.php?type=" + type + ""
			})
			.done(function (sortament) {
				sortament.unshift({
					id: "0",
					name: "Все"
				});
				$.ajax({
						type: "GET",
						url: "marka/index.php?type=" + type + ""
					})
					.done(function (marka) {
						for (var i in marka) {
							var data = marka[i];

							$("#p1").append("<div class='check'><span class='checkbox-text'><span>" + data.name + "</span> </span><input id=m" + data.id + " value=" + data.name + " name=" + data.id + " type='checkbox'></div>");
						}
						marka.unshift({
							id: "0",
							name: "Все"
						});
						$("#jsGrid").jsGrid({

							height: "800",
							width: "95%",
							filtering: true,
							editing: false,
							sorting: true,
							paging: false,
							autoload: true,
							pageSize: 15,
							pageButtonCount: 5,
							deleteConfirm: "Do you really want to delete the client?",
							controller: {
								loadData: function (filter) {
									return $.ajax({
										type: "GET",
										url: "clients/index.php?type=" + type + "",
										data: filter
									});
								}
							},

							fields: [{
									name: "name",
									type: "text",
									title: "Наименование",
									editing: false,
									itemTemplate: function (value, item) {
										return $("<a>").attr("href", "prod_more.php?id=" + item.id + "").text(value);
									}
								}, {
									name: "id_sortament",
									type: "select",
									title: "Сортамент ",
									items: sortament,
									valueField: "id",
									textField: "name",
									width: 30,
									filtercss: "sortament-filter"
								}, {
									name: "id_marka",
									type: "select",
									title: "Марка ",
									items: marka,
									valueField: "id",
									textField: "name",
									width: 30,
									filtercss: "marka-filter",
									itemTemplate: function (markaID) {
										return $.grep(marka, function (item) {
											return item.id === markaID;
										})[0].NAME;
									}
								},
								{
									name: "id_ntd",
									type: "select",
									title: "НТД ",
									items: ntd,
									valueField: "id",
									textField: "name",
									width: 30,
									filtercss: "ntd-filter"
								},
								{
									name: "id",
									title: " ",
									align: "center",
									itemTemplate: function (value, item) {
										return $("<button>").text("Оформить")
											.on("click", function () {
												alert("Переход");
												return false;
											});
									}
								}
							]

						});
					});
			});
	});

**Comment by anhhai680** [comment]
Sorry, I don't know what is your matter ?
