### ISSUE TITLE
Data only loads in first jsGrid when there are multiple grids in one page

### ISSUE THREAD

**Issue by a6Bd2d962** [tabalinas/jsgrid#1277]
1. Bug Reports:
    A) Expected behavior
         - The data that matches the column names should load in each grid. The reason I'm using the load controller and not using the static "data" attribute is because in my real-world example, I need to load data from an intranet server
    B) Actual Behavior
        - Only the data for the first grid loads
    C) Steps to Reproduce
        - See fiddle
    
3. Help Request/Question:
    A) Clearly state your problem - see above
    B) Include your code - see fiddle

https://jsfiddle.net/5mtak7eo/6/

**Comment by rubend30** [comment]
In the fiddle you only define data1_global but in the second and third JS grid configuration you use data**2**_global.

**Comment by a6Bd2d962** [comment]
My mistake. It still doesn't work with that corrected though

https://jsfiddle.net/q4g8rphb/

**Comment by rubend30** [comment]
You forgot the 'controller' part in the second and third configuration.

```
controller: {
      loadData: function(filter) {
        var d = $.Deferred();
        d.resolve(data1_global);
        return d.promise();
      }
    }
```

And not 

```
loadData: function(filter) {
      var d = $.Deferred();
      d.resolve(data2_global);
      return d.promise();
    }
```

**Comment by a6Bd2d962** [comment]
That was the issue, you're correct. 
Thank you. I just needed someone else's eyes on this one. I couldn't see this one for some reason.
