### ISSUE TITLE
Add generic code to parse the filter object into a odata query url

### ISSUE THREAD

**Issue by StefH** [tabalinas/jsgrid#128]
The js-grid supports odata, which is very cool, however manually creating the odata Url is difficult.

Maybe this javascript library can be used : https://odatasamples.codeplex.com/documentation ?

**Comment by tabalinas** [comment]
Since composing urls is controller logic, which is implemented by developer, feel free to use any library or helper for this.

**Comment by StefH** [comment]
I am using breezejs (http://www.getbreezenow.com/) now, it works perfect in combination with js-grid

**Comment by tabalinas** [comment]
Glad to hear that! I personally love breezejs!
