### ISSUE TITLE
cancelEdit not working

### ISSUE THREAD

**Issue by RobGWarning** [tabalinas/jsgrid#1320]
Hi, I want to be able to cancel my update if the server is not accepting it.
this is part of my code in the controller:

updateItem: function (item) {
                $.ajax({
                    type: "post",
                    url: '/Mutations/mutations?handler=Update',
                    contentType: "application/json; charset=utf-8",
                    dataType: "json",
                    beforeSend: function (xhr) { xhr.setRequestHeader("X-XSRF-TOKEN", $('input:hidden[name="__RequestVerificationToken"]').val()); },
                    data: JSON.stringify({ MutId: item.mutId, Status: item.status })
                }).done(function (message) {
                    alert(message);
                    if (message !== 'Mutation status changed!') {
                        $('#jsgrid').jsGrid('cancelEdit');
                    }
                });
            },

The cancelEdit function gets called but the value in the grid is not reversed to its original value.
what is wrong?

**Comment by Ex0-Ghost** [comment]
hi , i think that
$('#jsgrid').jsGrid('cancelEdit');
is not what you think it is , this method cancels the editing view when you click edit on a row and reverse it to normal view ie. from input to text view.
"currently i think there is no way to do what you want to do", i was wrong , the controller waits for the promise if you return it ,and if it is rejected then it wont edit the item and you should notify the user and close the edit view manually:

**Comment by RobGWarning** [comment]
Hi @Ex0-Ghost I think you are right. it's already an very old issue and I don't know how I did resolve it. I believe I made an other server call to update the row.
