### ISSUE TITLE
Data loads, but cells are empty

### ISSUE THREAD

**Issue by wernerfletcher** [tabalinas/jsgrid#1323]
Hi,
I'm loading data into the table and I can see the rows and pages, but the cells are not displaying the data.
Here is my table setup: https://jsfiddle.net/jy3bd7fL/

Here is a response I get from my server (I made it shorter, there are 506):
`{
    "data": [
       {
            "amount": "USD 212.0",
            "description": "DR SALE XXXXXXXX 1376",
            "id": 97550541,
            "category": "Securities Trades",
            "transactionDate": "2020-02-14",
            "status": "UNPROCESSED"
        },
        {
            "amount": "USD 164.0",
            "description": "AMEX XXXXXXXX 1198",
            "id": 97550542,
            "category": "Other Income",
            "transactionDate": "2020-02-14",
            "status": "UNPROCESSED"
        },
        {
            "amount": "USD 510.0",
            "description": "VM CC XXXXXXXX 1490",
            "id": 97550543,
            "category": "Other Income",
            "transactionDate": "2020-02-14",
            "status": "UNPROCESSED"
        }
    ],
    "itemsCount": [506]
}`

This is what my table looks like after loading:
![image](https://user-images.githubusercontent.com/14299265/74684235-08c0ef80-51d4-11ea-9bf3-c60266c82e4f.png)

![image](https://user-images.githubusercontent.com/14299265/74684373-60f7f180-51d4-11ea-9b30-a17f2b4e0a62.png)

It's strange, it almost looks like the amount of rows are too many per page.  I'm not sure why that would be.
Your assistance is greatly appreciated.  Thank you very much.

**Comment by taurenshaman** [comment]
I got the same problem. Do you found any solution or alternative?

**Comment by wernerfletcher** [comment]
No, never found a solution unfortunately.  Moved on and used jQuery DataTables instead.
