### ISSUE TITLE
How to custom my pageloading option

### ISSUE THREAD

**Issue by LeoQuote** [tabalinas/jsgrid#134]
I have an API that provide data like this above :
```json
{
    "count": 1023
    "next": "https://api.example.org/accounts/?page=5",
    "previous": "https://api.example.org/accounts/?page=3",
    "results": [
       …
    ]
}
```
this API is paginated , so I set     pageLoading to true, expecting jsgrid could automatically load the other pages 
but what jsgird needed is that data should be in ``data`` instead of ``results``
https://github.com/tabalinas/jsgrid/blob/master/README.md#grid-controller

I ve look through the docs but found nothing about custom those stuff.

So I opened this issue.

**Comment by an2323** [comment]
If I understand your question, you need

```javascript
loadData: function(filter) {
    return $.get('your.api', filter).then(function(response) {

        var result = {
            data: response.results || [],
            itemsCount: response.count || 0
        }

        return result;

    })
}
```

**Comment by LeoQuote** [comment]
that works, thanks
2015年11月5日 下午8:37，"Andrey Kalashnikov" <notifications@github.com>写道：
