### ISSUE TITLE
Help Needed : Disable cell editing on some condition

### ISSUE THREAD

**Issue by GauravKatariya** [tabalinas/jsgrid#1344]
Hi All,
I have a scenario like
row1 -> editable , non-editable, editable
row2 -> non-editable , editable , editable

How can we achieve this. Disabling a particular cell edit based on some row value.

Your help will be highly appreciated.

**Comment by GauravKatariya** [comment]
Any update on this?

**Comment by Fergo** [comment]
I'm also curious about this. I need to prevent editing in a single cell on a single row.
