### ISSUE TITLE
rowRenderer strips any classes added to the returned <tr> wrapper element

### ISSUE THREAD

**Issue by bendrexl** [tabalinas/jsgrid#136]
I'm attempting to conditionally add a class to a table row, using the rowRenderer option.

I see the class added to the returned <tr> element, but after the row is rendered the classes are not present in the DOM.

```
rowRenderer: function (rowData) {
            var tr = $("<tr/>", { addClass: "myClass" });
            $.each(rowData, function(name, value){
                var td = $("<td/>", {
                    html: value
                }).appendTo(tr);
            });
            return tr;
        },
```

Inspecting var tr shows a valid jQuery object with myClass applied, but not in the rendered jsGrid on the page.

**Comment by tabalinas** [comment]
I cannot reproduce the issue. It works just fine in the following fiddle http://jsfiddle.net/tabalinas/yyt1v92k/
I guess the issue is somewhere in the outside code.
