### ISSUE TITLE
How to make inline edit with rowDoubleClick in JsGrid

### ISSUE THREAD

**Issue by aqrohadi** [tabalinas/jsgrid#1378]
//     rowDoubleClick: function(args) {
//       if(this.editing.item.rowClick) {
//              this.editItem($(args.event.target).closest(this, args));
//         }
//       },
  
//     rowDoubleClick: function (args) {
//         if(args.item.rowClick) {
//               jsGrid.Grid.prototype.editing.call(this, args);
//         }
//     },

This is script which I have created, but doesn't works. Could you help me to solve problem it.

Thank you!

**Comment by nandakumar-a** [comment]
try this easy one
```
rowClick:function(args)
{
//do something or leave it without removing the rowClick section
},
rowDoubleClick:function(args)
{
$("#jsGrid .jsgrid-edit-button").trigger("click");
}
```
Note: its is using Jquery please import jquery plugin before jsGrid.js

**Comment by aqrohadi** [comment]
Thanks for the response, @nandakumardtc 
the script code that you sent, it's works, but it's just that when I double-click on the free field and what happens is that the bottom field of the table is available to edit, are you any solution to the problem it ?
The point is from the your script, double-click it's works, but doesn't match what inline to edit. So the conclusion, every time me double-click on a certain field, which is open for editing it is always the bottom field. Look at the SS of the image below.

![image](https://user-images.githubusercontent.com/69478932/109804450-d7875600-7c54-11eb-9cb0-5c50d3580246.png)

**Comment by nandakumar-a** [comment]
yeah i got it @aqrohadi  try this one



```
var clients = [
        { "Name": "Otto Clay", "Birthday": "December, 17 2014" },
        { "Name": "Connor Johnston", "Birthday": "March, 5 2012" },
        { "Name": "Lacey Hess", "Birthday": "August, 2 2000" }
    ];
 
    $("#jsGrid").jsGrid({
        width: "600px",
        height: "400px",
 
        inserting: true,
        editing: true,
        sorting: true,
        paging: true,
 
        data: clients,
 
        fields: [
            { name: "Name", type: "text", width: 150, validate: "required" },
            { name: "Birthday", 
              type: "text",
              align: "right",
              width: 150
            },
          {
            type: "control"
          },
          
          ],
      rowClick:function(args)
      {
        
      },
      
    });
$("#jsGrid").on("dblclick","tr:not(.jsgrid-edit-row)",function(){
  $(this).find(".jsgrid-edit-button").trigger("click");
});
```

**Comment by aqrohadi** [comment]
Woww, rowDoubleClick it's works! Thank you so much @nandakumardtc !

**Comment by nandakumar-a** [comment]
Welcome, I am glad you got a solution @aqrohadi

**Comment by nandakumar-a** [comment]
There is another solution also i have attached [this](https://codepen.io/nandakumar-dtc/pen/rNWKbGN)

**Comment by aqrohadi** [comment]
better
