### ISSUE TITLE
Jsgrid Custom Phone number Field

### ISSUE THREAD

**Issue by AVitse** [tabalinas/jsgrid#1383]
Hi,

Regarding this example http://js-grid.com/docs/#custom-field 

how could i create phone number field like 00.00.00.00.00 format ?

Regards

Alex

**Comment by nandakumar-a** [comment]
@AVitse please refer this example for your clarification [this](https://codepen.io/nandakumar-dtc/pen/bGgbBoO)

**Comment by AVitse** [comment]
Hi,

Thank you it works very well.

How to get a mask for input based on this format? ( for add new row or edit row )

Best regards

**Comment by nandakumar-a** [comment]
sorry, I am unable to get you question, are asking to format the value on input tag like this 00,00,00,00,00 while editing?

**Comment by AVitse** [comment]
Yes, I want to format the value on input tag like this 00,00,00,00,00 while editing/ adding rows => Inputmask  (00,00,00,00,00)

**Comment by nandakumar-a** [comment]
@AVitse please refer this example for your clarification [this](https://codepen.io/nandakumar-dtc/pen/bGgbBoO)

**Comment by AVitse** [comment]
@nandakumardtc : it's work perfectly thanks you :+1:

**Comment by nandakumar-a** [comment]
@AVitse Am glad that the solution works for you and if you are ok with the given solution, please consider to close the issue.

 Thanks
