### ISSUE TITLE
Disabled fields which have options inserting and/or editing to false

### ISSUE THREAD

**Issue by fanturi** [tabalinas/jsgrid#14]
Hi,

It could be great if you could disabled fields which have option editing and/or inserting set to false.
Currently if you set this options to false the fields are not saved it's ok but you can still modify it on the screen. It's confusing.

**Comment by tabalinas** [comment]
The initial idea behind it was: if developer turns off editing (filtering or inserting) of the field, he has to redefine `editTemplate` (`filterTemplate` or `insertTemplate`). But it appears that this is not always convenient, so I agree, that It should be improved.
