### ISSUE TITLE
How to get <tr> row from data-item and vice versa?

### ISSUE THREAD

**Issue by mese79** [tabalinas/jsgrid#142]
Hi
Thanks for your great job!
I wonder how can i get grid row from data-item or date-item from a row?
In a loop over my data or grid rows i want to add a **css class** to the related ```<tr>``` based on value of a property of data-item. i mean something like conditional formatting.
I think it would be nice to have an event fired on every row added to the grid.

**Comment by tabalinas** [comment]
To set class to the row use the `rowClass` callback http://js-grid.com/docs/#rowclass

Get item by row:
```js
var item = $row.data("JSGridItem");
```

Get row by item:
```js
var $row = $jsGrid.jsGrid("_rowByItem", item);
```

Could you share your use cases, to know whether we need public API for this.

**Comment by mese79** [comment]
```rowClass``` did the job for me!
Thanks.

**Comment by Div703** [comment]
can u please elaborate ,how  can i use rowClass for row coloring

**Comment by tabalinas** [comment]
Just define css styles like following

```css
.my-row-custom-cls td {
    background: red;
}
```

**Comment by Div703** [comment]
Hi,,,thaxs fr de rply,,I gt de thing for row previously,but can u help me hw to clr a particular cell?

**Comment by tabalinas** [comment]
Please, open a separate issue clearly stating your question.
