### ISSUE TITLE
prevent data delete

### ISSUE THREAD

**Issue by mahendaraReddy** [tabalinas/jsgrid#143]
if i delete data from the grid its deleting data from the related Json object also how can i prevent default delete from json object.

**Comment by tabalinas** [comment]
If you remove item from grid, why you want prevent deletion? Or you want to prevent deletion in some cases? Clarify your use case, please. Provide a jsfiddle or code snippet if possible.

**Comment by tabalinas** [comment]
No answer for long time. Closing the issue.
