### ISSUE TITLE
onInsert, onEdit, onDelete events

### ISSUE THREAD

**Issue by velis74** [tabalinas/jsgrid#144]
I need custom event for CRUD buttons. In my particular case, for edit button.
Similar to existing onXXX-ing/-ed, but these would trigger directly in the event functions (_createEditButton).

I'm willing to do this myself, so would you consider accepting a pull request?

Edit: while implementing, I saw that onInsert is actually already supported through onOptionChanging...

**Comment by tabalinas** [comment]
Edit and Delete buttons are not parts of the grid. They defined on the level of `control` field. So whether we add these callbacks on the level of `control` field. Or maybe adding `onItemEditing` event for the grid is enough? Could you share your use cases?

**Comment by velis74** [comment]
My use case is that clicking the edit button should actually redirect to another page. Or display my custom dialog. As far as I tried the control, I could not achieve this via existing events.

**Comment by tabalinas** [comment]
Ok, then `onItemEditing` callback should be enough.
What's your current solution?

It could be
 - adding new field with edit button, that contains link, and hiding edit button from control field (`showEditButton: false`)
 - redefine `_createEditButton` of `control` field
 - redefining of `itemTemplate` of `control` field

**Comment by velis74** [comment]
My current solution is:

    editItem: function(item) {
        var $row = this._rowByItem(item);
        if($row.length) {
            var args = this._callEventHandler(this.onEdit, {
                row: $row,
                item: item,
            });
            if (args.handled !== true) {
                this._editRow($row);
            }
        }
    },

Seems I still need to learn about JS: I have no idea how to do #1 or #3 :)

**Comment by tabalinas** [comment]
It looks good.

Few points that I would do:
 - rename to `onItemEditing` (to be consistent and show precedence of callback)
 - instead of `args.handled` use opposite `args.cancel` to be consistent
 - put guard `if` instead of condition nesting (`if(!$row.length) return;`) 
 - add `onItemEditing: $.noop` to config
 - add unit test for the callback J

Created separate enhancement issue for the request with link to that one, so this can be closed.

**Comment by velis74** [comment]
OK, just a side question before I take a stab at it: do I also implement onItemInserting (for consistency), even though it can be achieved via onOptionChanging?

**Comment by tabalinas** [comment]
Maybe I'm missing something, but why onItemInserting is not enough? It looks like it lacks only onItemEditing, no?

**Comment by velis74** [comment]
Well, it seems we don't understand each other:
Current onItemxxx events trigger just before and just after the controller call. If you set result.cancel in onItem___ing, then the _controllerCall will return $.Deferred().reject().promise(); Not entirely sure what this does though, must check.

When researching this (to answer your question), I found that what I want can actually be done if I implement onItem___ing events, process them and just return .cancel = true

Let me verify this and get back to you. Seems my use case is already covered nicely :)

**Comment by velis74** [comment]
not. These events all trigger too late in the process (once the user had already entered the data). Perhaps only onItemDeleting would be usable in this way since it doesn't need any additional data entry in order to tell controller to delete the item, but then again - it also (optionally) fires the confirmation dialog...

Anyway, to answer your question: my current use case only requires event for editing, yes, but I will soon need to do the same for insert and delete as well. 

I find that doing anything to the control field would also require work on that special `add` button in the column headings row. The `add` button in the control field has no meaning in this concept, hence `onItemInsert`, `onItemUpdate`, `onItemDelete`. Sorry about this naming, but I thought a lot about how these events should be named and couldn't come up with anything "smart". The next possible alternative was `onItemInsertingUI`, `onItemDeletingUI` and `onItemUpdatingUI` emphasizing that these were events that fire before UI build?

I hope I explained this better now and thanks for listening.

**Comment by RevealedFrom** [comment]
For me, both `onItemInserting` and `onItemInserted` fire _after_ I click the + on the insert row. 

Am I interpreting it wrongly?  Does "on inserting" mean inserting into the `grid` or entering insert mode?  I am looking for an event that takes place upon entering insert mode so as to initialize some fields.

**Comment by tabalinas** [comment]
@RevealedFrom: `onItemInserting` happens before calling `insertItem` of the controller. So when actual inserting already happens. There is no event like `onItemEditing` for insertion. If you want to set some values to insert row you could do it in redefining `insertTemplate` of a particular item.

**Comment by RevealedFrom** [comment]
@tabalinas Thanks. Found my answer in #471 .
