### ISSUE TITLE
Insert and update decimal numbers

### ISSUE THREAD

**Issue by wichy5** [tabalinas/jsgrid#145]
Hi,
I have a column with a decimal number (price) and I only can use integer number. How can I do it???

Thank you

**Comment by tabalinas** [comment]
Checkout the following ticket https://github.com/tabalinas/jsgrid/issues/89

**Comment by wichy5** [comment]
I think that I didn't explain very well.
In my jsgrid I have one field with decimal number:
{ name: "Price", type: "number", width: 50,
            itemTemplate: function(value) {
                    return value.toFixed(2) + "€"; 
            }
}
when I insert new item or edit only save integer number, how can I fix it?
Thank you

**Comment by tabalinas** [comment]
Each field has `editValue` and `insertValue` functions to prepare value for insertion/editing http://js-grid.com/docs/#fields. I guess it's what you need. Or you can prepare value in controller methods.

**Comment by wichy5** [comment]
Thank you so much!!! :smile:

**Comment by tabalinas** [comment]
You are welcome!
