### ISSUE TITLE
EditItem Method

### ISSUE THREAD

**Issue by andyjhall** [tabalinas/jsgrid#148]
Can I pass a row number into the EditItem Method?

Thanks.

**Comment by tabalinas** [comment]
Could you bring more details about what you would like to do and for what purpose?

**Comment by andyjhall** [comment]
I was hoping to enable using the arrow keys to switch the selected item. I was thinking I could get the current row I'd and add 1 when the down arrow is pressed or minus when when the up button is pressed.

**Comment by tabalinas** [comment]
I see the following solution:
1) add some special class to each row with `rowClass` (e.g. `.grid-row`)
2) add keyboard handlers as in the following answer: http://stackoverflow.com/questions/11088674/shift-focus-with-arrow-keys-in-javascript
3) on enter key press call `editItem` with `document.activeElement`

You can also add some styling for focused row: `.grid-row:focus { background: skyblue; }`
