### ISSUE TITLE
Select field: is it possible to load data via ajax ?

### ISSUE THREAD

**Issue by fanturi** [tabalinas/jsgrid#15]
Hi,

Is it possible to load the data for a select column via ajax ?

I tried: items: { loadData: function() { ... } but it's not working.

Thanks.

**Comment by tabalinas** [comment]
Unfortunately, now it's not supported. `items` should be an array of items.

The possible workaround could be initializing grid on done of ajax request of select items like following:

````javascript
$.ajax({
    method: "get",
    url: "RetriveSelectItemsUrl"
}).done(function(items) {
    
    $("#jsgrid").jsGrid({
        // grid config
        fields: [
            { type: "select", items: items }
        ]
    });
    
});
````

**Comment by Oxicode** [comment]
+1

**Comment by aline-matos** [comment]
Yep, +1

**Comment by rigerta** [comment]
Hi, has anything changed on this? Meanwhile I tried the workaround but keeps throwing a "jsGrid is not a function" error. I am using jsGrid v1.5.3. Thanks by the way, this is a very nice and easy to use grid.
