### ISSUE TITLE
Flashing Table

### ISSUE THREAD

**Issue by Julian-B90** [tabalinas/jsgrid#150]
This was the first:
![flashing_tabel_01](https://cloud.githubusercontent.com/assets/4377396/11247335/f57df1e6-8e1b-11e5-9a0b-6409e93f8d28.png)

and shortly thereafter
![flashing_tabel_02](https://cloud.githubusercontent.com/assets/4377396/11247338/f8a47b6a-8e1b-11e5-8102-1c4e32aff319.png)

**Comment by tabalinas** [comment]
According to description I guess the following behavior: grid rendered in invisible area (hidden div), this may cause the issue with width. Then you do a resize (showing Chrome DevTools also fires resize) and grid refreshed. This behavior is defined by updateOnResize option http://js-grid.com/docs/#updateonresize-default-true

Correct me, if I'm wrong.

**Comment by Julian-B90** [comment]
Yes this is right.

**Comment by tabalinas** [comment]
Now this behavior is by design. 
Maybe you have an idea how to make it better?

**Comment by Julian-B90** [comment]
not realy. This Grid it was show in a tab with 3 tabs.

**Comment by Julian-B90** [comment]
okay now i have found the error. I don´t have use 
```javascript
var d = $.Deferred();
.........
success: function (data) {
   d.resolve(data.msg);
 },
........
return d.promise();
```

**Comment by tabalinas** [comment]
The behavior you described in the ticket is by design. If you spot another issue, please open another ticket. Thank you!
