### ISSUE TITLE
Odata not working

### ISSUE THREAD

**Issue by Craig30** [tabalinas/jsgrid#151]
Hi,

I cannot get my OData call working, here is my code(below).

I am calling an MVC action (which is what the URL points to) however the jsGrid just shows the loading symbol and nothing loads.

        $(function () {
            $("#jsGrid").jsGrid({
                height: "300px",
                width: "100%",

                inserting: true,
                filtering: true,
                editing: false,
                sorting: true,
                paging: true,
                autoload: true,
                pageloading:true,

                controller: {

                    loadData: function()  {
                        var d = $.Deferred();
                        $.ajax({
                            url: "http://localhost:50795/Orders/OrderModels/Index",
                            dataType: "json"
                        }).done(function (response) {
                            setTimeout(function () {
                                d.resolve(response.value);
                            }, 2000);
                        });
                        return d.promise();
                    }
                },

                fields: [
                    { name: "Customer", type: "text", width: 10 },
                    { type: "control" }
                ]
            });
        });

My MVC function that is handling the URL request above is as follows:
public IEnumerable<object> GetCustomerOrders()
{
            string[] Customer = { "d", "d", "F" };
            return Customer;
}

**Comment by tabalinas** [comment]
Do you see any error in the browser console? Try to put debugger into your done function to see whether you get there and if yes, then what is the response.

**Comment by tabalinas** [comment]
Also I noticed that you have `pageLoading: true`. In this case you should supply data to the grid in other format. You can find details in the docs http://js-grid.com/docs/#loaddatafilter-promisedataresult

**Comment by Craig30** [comment]
Hi,

I have now set pageLoading:false;

I am getting the following error from the Debugger:
Failed to invoke return value callback: SecurityError: The operation is insecure.

How can I resolve this?

Thanks.

**Comment by tabalinas** [comment]
The problem is [Same-origin policy](https://en.wikipedia.org/wiki/Same-origin_policy)
You cannot access data from another domain, unless client has special header specified in response from server.

See this SO question:
http://stackoverflow.com/questions/20442628/cors-jquery-ajax-request

Checkout this article to enable CORS in WebAPI:
http://www.asp.net/web-api/overview/security/enabling-cross-origin-requests-in-web-api

Or you can use jsonp, but it allows only reading https://learn.jquery.com/ajax/working-with-jsonp/

**Comment by Craig30** [comment]
Hi,

I did as specified in:
http://stackoverflow.com/questions/20442628/cors-jquery-ajax-request

I amended my code as described, however I get the same result. I used Fiddler to verify that JSON is being returned and it is.

Any advice?
Thanks.

**Comment by tabalinas** [comment]
Are you sure you specified it on the server side also? Which version of ODATA do you use? If it's ODATA v4 you should have something like WebAPI config

```csharp
public static class WebApiConfig
    {
        public static void Register(HttpConfiguration config)
        {
            // New code
            config.EnableCors();

            config.Routes.MapHttpRoute(
                name: "DefaultApi",
                routeTemplate: "api/{controller}/{id}",
                defaults: new { id = RouteParameter.Optional }
            );
        }
    }
```

Also in testing purposes you can install the following plugin to be able to request another domain with ajax https://chrome.google.com/webstore/detail/allow-control-allow-origi/nlfbmbojpeacfghkpbjhddihlkkiljbi?hl=en

**Comment by Craig30** [comment]
I am running it off my desktop as an MVC app, not Web API.

I also made changes to the ISS Express /config/applicationhost with:

        <httpProtocol>
            <customHeaders>
                <clear />
                <add name="X-Powered-By" value="ASP.NET" />
				   <add name="Access-Control-Allow-Origin" value="*" />
					<add name="Access-Control-Allow-Headers" value="Content-Type" />
            </customHeaders>
            <redirectHeaders>
                <clear />
            </redirectHeaders>
        </httpProtocol>

**Comment by tabalinas** [comment]
Have you tried the Chrome extension? Just to see if it works, when CORS issue is solved.

**Comment by Craig30** [comment]
Hi,

I have tried it - no luck. Is this a bug and if so can it be fixed please.

Thanks.

**Comment by tabalinas** [comment]
Have you tried to put a debugger into your `done` handler to see the response? Try to see the request in DevTools in the Network section to know whether it succeeded or not and what is the response (feel free to attach the screenshot of DevTools request details to this issue)
