### ISSUE TITLE
How to keep form data of row when inserting from header?

### ISSUE THREAD

**Issue by eddOrnelas** [tabalinas/jsgrid#153]
I want to keep the data or the form data entered when inserting a row, when i create or insert a new row, the table refresh and the form on the headers reset, so i need to know is there is something to keep it and not enter again the data after form validation

**Comment by tabalinas** [comment]
This behavior is defined in `control` field (not in the grid).
The easiest solution is just redefine `_createInsertButton` method of the field:

Currently it does the following:

```js
        _createInsertButton: function() {
            return this._createGridButton(this.insertButtonClass, this.insertButtonTooltip, function(grid) {
                grid.insertItem();
                grid.clearInsert();
            });
        },
```

Put the same function body, just w/o `clearInsert` call.
This should help.
