### ISSUE TITLE
Can I make each row a link to its own individual page?

### ISSUE THREAD

**Issue by flyinmryan** [tabalinas/jsgrid#156]
I have a data table that has been filled out via AJAX, but now I'm trying to link each row with a URL to that row event's own page.  I saw someone else asked about linking the edit icon with a URL and you advised to create a new field.  I'm going to have to do that myself in the next few days most likely, but for now I just need to know how the make the whole row an <a> tag basically.
Here is a fiddle with some of my code.  The JSON is the CSS area is an example of the data I'm getting from AJAX.  Thanks
http://jsfiddle.net/f5g1of7n/

**Comment by tabalinas** [comment]
Just define `rowClick` [callback](http://js-grid.com/docs/#rowclick) and put redirection logic there

```js
rowClick: function(args) {
    window.location = args.item.ItemUrl;
}
```

**Comment by flyinmryan** [comment]
Thank you!

**Comment by tabalinas** [comment]
You are welcome!
