### ISSUE TITLE
Value type returned in select fields edition and insertion

### ISSUE THREAD

**Issue by julmarci** [tabalinas/jsgrid#158]
Hello again Mr. Tabalinas.

I have select fields in my jsgrid which contains data referencing other persistence entities, so the data is an **integer** id (valueField) and a text name (textField). When inserting or editing, jsgrid always pass an object with a **text** id value to the insertItem and updateItem callbacks and the grid doesn't show the new/edited value until data is loaded again from the server (because I resolve with that same object)

Shouldn't jsgrid give an id (valueField) with the same type that the select field use? I think It'd be much better.

Thanks.

**Comment by tabalinas** [comment]
Actually, select field tries to predict the type of value (whether number or a string). And depending on the type turns a value to number or not. Not sure about your case and why it doesn't work for you, but you can force the type of value with `valueType='number'` in the field config.

**Comment by julmarci** [comment]
Oh, yes, that works. But I didn't find anything about valueType in the documentation.
My select options always containt a blank one, maybe that is why jsgrid doesn't predict the type right.

**Comment by tabalinas** [comment]
You are welcome! Ok, then maybe it really worth to publish it.
