### ISSUE TITLE
Internationalization(i18n) support

### ISSUE THREAD

**Issue by bboyz269** [tabalinas/jsgrid#159]
Hi, thank you for the great plugin!

 I've been searching for crud with inline editing/pagination/filter-ready for days. The big PLUS of jsGrid (beside that big green modeSwitchButton) is that IE8 compatible.
Back to the main point. As my project requires, I wonder if jsGrid is i18n-friendly? I took a look at the documentation but found none. Thank you again!

**Comment by bboyz269** [comment]
Hi, I just look at the documentation again and found some options for change text, tooltip. My question is that are those below sufficient? Please correct me if I'm missing anything. Thank again!

'''Javascript
// fields
searchModeButtonTooltip: "検索モード", // tooltip of switching filtering/inserting button in inserting mode
insertModeButtonTooltip: "新規モード", // tooltip of switching filtering/inserting button in filtering mode
editButtonTooltip: "編集",                      // tooltip of edit item button
deleteButtonTooltip: "削除",                  // tooltip of delete item button
searchButtonTooltip: "フィルター",                  // tooltip of search button
clearFilterButtonTooltip: "クリア",       // tooltip of clear filter button
insertButtonTooltip: "登録",                  // tooltip of insert button
updateButtonTooltip: "更新",                  // tooltip of update item button
cancelEditButtonTooltip: "編集戻す"         // tooltip of cancel editing button

// general options
noDataContent: "データが見つかりません。",
deleteConfirm: "削除しますよろしですか。",
pagerFormat: "頁: {first} {prev} {pages} {next} {last}    【 {pageIndex} ／ {pageCount} 】",
pagePrevText: "前",
pageNextText: "次",
pageFirstText: "最初",
pageLastText: "最後",
pageNavigatorNextText: "…",
pageNavigatorPrevText: "…",
loadMessage: "処理中…"
'''

**Comment by julmarci** [comment]
That's enough for me in Spanish provided your page code and content type are UTF8/UTF16 (what you need)

**Comment by tabalinas** [comment]
Thank you for the feedback!
I'm planning providing I18n support. Good to have it in requests, Thank you!

For now, all these labels seems enough.

**Comment by bboyz269** [comment]
Then I will go with those for now. Really looking forward to the i18n support! Thank you all

**Comment by tabalinas** [comment]
Let it be opened to track the progress.

**Comment by tabalinas** [comment]
The localization is now supported (but not released yet). 

@bboyz269, pull request with Japanese would be highly appreciated.
@julmarci, if you could do a pull request with Spanish, it would be really great.

Here you can find en example file for French https://github.com/tabalinas/jsgrid/blob/master/src/i18n/fr.js

Guys, thank you in advance!

**Comment by tabalinas** [comment]
Here is the English locale script https://gist.github.com/tabalinas/8162fac41ffe0a2bc81d

**Comment by bboyz269** [comment]
Hi, sorry for the late response. I've been caught up with works for months. I'm working on Japanese translation today but I get confused about the validation message.
```javascript
            minLength: { message: "Field value is too long" },
            maxLength: { message: "Field value is too short" },
            min: { message: "Field value is too large" },
            max: { message: "Field value is too small" }
```
Isn't it the opposite? When the field's length/value falls below min value, shouldn't it be showing "too short/small" instead of "long/large" and vice versa for max value?

**Comment by tabalinas** [comment]
Thank you for the feedback! This is really a crazy mistake 0_o
Fixed. Thanks again!
