### ISSUE TITLE
How to change the ajax request url to render another datas?

### ISSUE THREAD

**Issue by fakelbst** [tabalinas/jsgrid#16]
I don't know if can do this with the docs and examples, is there a way to do this?
Thanks very much!

**Comment by tabalinas** [comment]
Not sure, I got the problem. 
You can specify ajax url doing request to the server in controller methods
http://js-grid.com/docs/#grid-controller

Could you provide an example or more details about your case?

**Comment by fakelbst** [comment]
Thanks, this is the code 
```javascript
$("#xxx").jsGrid({
    width: "100%",
    paging: false,
    autoload: true,
    controller: {
        loadData: function() {
            var d = $.Deferred();
            $.ajax({
                url: "/a_list",
                dataType: "json"
            }).done(function(response) {
                d.resolve(response.data);
            });
            return d.promise();
        }
    },
    fields: [...]
});
```

After this grid loaded, I want change the ajax url to '/a_list?type=2', and render data to the same $('#xxx') element, is this possible?

**Comment by tabalinas** [comment]
Yes, it's possible, you can introduce `url` variable and change it on ajax `done`.
You can put this variable into the closure of self calling function like following:

````javascript
loadData: (function() {
	var url = "/a_list";
	
	return function() {
		var d = $.Deferred();
		$.ajax({
			url: url,
			dataType: "json"
		}).done(function(response) {
			url = "/a_list?type=2";
			d.resolve(response.data);
		});
		return d.promise();
	}
})()
````

Not sure, what you try to achieve, but want to be sure you aware that `loadData` accepts `pageSize` and `pageIndex` parameters if `pageLoading = true` 
See docs http://js-grid.com/docs/#loaddatafilter-promisedataresult

**Comment by fakelbst** [comment]
What I want to do is a filtering, different datas is loaded by different url, like '/a_list' and '/a_list?type=2', there is a select element in my page, and by different options, I want change the ajax url to get datas.

**Comment by tabalinas** [comment]
Ok, then define url outside the grid, change it on change event of your select, and call `loadData` method.

See following example (actual loading is not happen due to fake urls): http://jsfiddle.net/tabalinas/tjoag1ux/

```` javascript
App = {};

App.loadUrl = "/a_list";

$("#jsgrid").jsGrid({
    autoload: true,
    width: 200,
    controller: {
        loadData: function() {
            return $.ajax({
                type: "GET",
                url: App.loadUrl
            });
        }
    },
    fields: [
        { type: "text", name: "Name" }
    ]
});

$("#urlSelect").on("change", function(e) {
    App.loadUrl = $(e.target).val();
    $("#jsgrid").jsGrid("loadData");
});

````

**Comment by fakelbst** [comment]
Yes, this is exactly what I want. And thanks for this amazing grid plugin.

**Comment by tabalinas** [comment]
You are welcome!
Thank you for the feedback, I appreaciate it.
