### ISSUE TITLE
What is the correct way to change grid size?

### ISSUE THREAD

**Issue by velis74** [tabalinas/jsgrid#162]
I tried:

    $("#grid").jsGrid({height: 400});
    $("#grid").jsGrid("option", "height", 400);
    $("#grid").jsGrid("refresh");
    $("#grid").jsGrid("render");

In all combinations. Nothing seems to have the desired effect. I'm doing this in body.onresize event to adjust grid to available screen space.

**Comment by tabalinas** [comment]
Just settings fixed height can be done with 

```js
$("#grid").jsGrid("option", "height", 400);
```

No need to refresh or render. It works for me.
Moreover, you don't need to subscribe on resize, jsGrid already doing it http://js-grid.com/docs/#updateonresize-default-true

The problem, maybe is that you try to set the height in percents, then you maybe faced with something like this https://github.com/tabalinas/jsgrid/issues/41
