### ISSUE TITLE
My Add button didn't work. Help!

### ISSUE THREAD

**Issue by daengbukhary** [tabalinas/jsgrid#166]
Problem with add button. Can someone help me with it?

![add button](https://cloud.githubusercontent.com/assets/12839933/11720273/7dc7951e-9f99-11e5-8f79-868a678793cf.png)

**Comment by bboyz269** [comment]
Check if you have included [jquery ui](http://jqueryui.com/) in your page as $.fn.dialog is not defined.

**Comment by daengbukhary** [comment]
I have included the jquery by the way. But still, Uncaught TypeError: $(...).dialog is not a function..

<script src="public/js/jquery.js"></script>
<script src="public/js/jquery-ui.js"></script>
<link href="public/css/jquery-ui.css" rel="stylesheet" />

**Comment by daengbukhary** [comment]
my .dialog is okay now.. but showDetailsDialog is error..

![capture1](https://cloud.githubusercontent.com/assets/12839933/11742076/0dec3a3e-a038-11e5-8c69-a7f280fc76d7.PNG)
![capture2](https://cloud.githubusercontent.com/assets/12839933/11742077/0f1f5f26-a038-11e5-823d-b989b1c8735b.PNG)

**Comment by tabalinas** [comment]
I guess, you have not defined this function. Just read the error message.

**Comment by daengbukhary** [comment]
Actually, I am combining jsgrid PHP backend with your data manipulation. Do you have data manipulation for PHP though?

**Comment by tabalinas** [comment]
I guess, you have not defined this function. That's exactly what the error message says

**Comment by tabalinas** [comment]
No, it's two different things: demos are client-side, and backend samples are backend-side stuff. They can be used interchangeably.

**Comment by daengbukhary** [comment]
Thanks tabalinas.
