### ISSUE TITLE
How can I add function of keypress e=13 in the form?

### ISSUE THREAD

**Issue by daengbukhary** [tabalinas/jsgrid#167]
**** SAMPLE.JS ****
```js
fields: [
                { name: "year", title: "Year", width: 50, type: "text", tabindex: "3", class: "TabOnEnter"},
                { name: "code", title: "COA", type: "text", width: 70, tabindex: "1", class: "TabOnEnter"},
```
**** JS FUNCTION ****
```js
$(window).load(function () {
$(document).on("keypress", ".TabOnEnter" , function(e){
//Only do something when the user presses enter
if( e.keyCode ==  13 ) {
  var nextElement = $('[tabindex="' + (this.tabIndex  + 1) + '"]');
  console.log( this , nextElement );

  if (nextElement.length)
      nextElement.focus()
      else
        $('[tabindex="1"]').focus();
}
});
});
```

**Comment by bboyz269** [comment]
You should use "keydown" instead of "keypress". I don't remember the definition but "keypress" event should be used only for key that is printable on the screen.

**Comment by tabalinas** [comment]
I don't understand the question and how it's related to the js-grid.

**Comment by daengbukhary** [comment]
When I click switch to inserting button. I want the text field to have the function which after I input something on the field, I also can use "ENTER" to move to next tab/field. Is it clear?

**Comment by tabalinas** [comment]
Ok. So what is the issue that you experience?
Feel free to fork the fiddle https://jsfiddle.net/tabalinas/zzzfmpgt/ and demonstrate the issue.

**Comment by daengbukhary** [comment]
FYI, I'm using JSGrid for PHP Backend demo.
I have two functions that I want to put inside jsgrid using JavaScript.

1. I would like to add function which user can use enter (keypress=13) in insertTemplate instead of using "click" function / mouse. Example of function that I saw based from your jsgrid.js in filterTemplate:function() { part.

![capture](https://cloud.githubusercontent.com/assets/12839933/11831404/5f4f341c-a3e9-11e5-8e07-08473ac94a78.PNG)

2. Another function: 
For example, in this textfield below when I insert an input into COA's textfield, other fields such as year. description, debit/credit will display output which connected from the database.

![capture2](https://cloud.githubusercontent.com/assets/12839933/11831533/f6e51a26-a3e9-11e5-8e2f-a604ec67c6fb.PNG)

Glad if you can have an idea to help me solve it up. Thanks.
