### ISSUE TITLE
How to bind the change of the item when editing, inserting and filtering?

### ISSUE THREAD

**Issue by codingbunny** [tabalinas/jsgrid#169]
I have few select fields in my table. And I want them bind with other, which means the options of one select list is depend on the selection of other select list. So I made a new type based on the "select" type by changing the Template and _createSelect. I want to call _createSelect every time I modify the item but have no idea how to bind it. Thank you very much if you can help!

      editTemplate:  function(value,item) {
            if(!this.editing)
                return this.itemTemplate(value);
            var $result = this.editControl = this._createSelect(item.type);

           /*  How to bind?
            $().on("change",function(e) {
            	 $result = this.editControl = this._createSelect(item.type);
            });
           */

            return $result;
        },

    _createSelect: function(type) {
        	console.log("Create select:");
        	console.log(type);
            var $result = $("<select>"),
                valueField = this.valueField,
                textField = this.textField,
                selectedIndex = this.selectedIndex,
                boundField = this.boundField;

            $.each(this.items, function(index, item) {
                var value = valueField ? item[valueField] : index,
                    text = textField ? item[textField] : item,
                    bound = boundField ? item[boundField] : item;
//Only return options with same bound type

                if(bound==type){
                var $option = $("<option>")
                    .attr("value", value)
                    .text(text)
                    .appendTo($result);

                $option.prop("selected", (selectedIndex === index));
                }
            });

            return $result;
        }

**Comment by tabalinas** [comment]
Please, checkout the following issues:
https://github.com/tabalinas/jsgrid/issues/46
https://github.com/tabalinas/jsgrid/issues/71

**Comment by codingbunny** [comment]
Hi Tablinas,
Thank you for your answer. I tried your answer and it works well. But there still a problem, when I try to editing the row, when I click it, the value disappear. This happen to all my self defined fields. Could you help?
Before I click:
![before](https://cloud.githubusercontent.com/assets/16314757/11926600/0be584f4-a801-11e5-87cf-653dadbfbc28.png)
After I 
![after](https://cloud.githubusercontent.com/assets/16314757/11926607/18587bd8-a801-11e5-84f5-08843fdd6fe6.png)
click:

Thank you very much again!

**Comment by tabalinas** [comment]
Could you provide a fiddle (maybe modify one of fiddles from the tickets above) to demonstrate the issue?

**Comment by codingbunny** [comment]
Thank you for you reply. I added one column based on your previous fiddle. I am new for jQuery, the code may not good enough but it demonstrates my problem. 
http://jsfiddle.net/codingbunny/p39kteqh/2/

**Comment by codingbunny** [comment]
Hi Tabalinas,
Thank you for you reply. I added one column based on your previous fiddle. I am new for jQuery,the code is not good enough but it's all I can do. It demonstrates my problem. Thank you again!
http://jsfiddle.net/codingbunny/p39kteqh/3/

**Comment by tabalinas** [comment]
Looks like in the fiddle you've brought it works just fine. I don't see the issue

**Comment by codingbunny** [comment]
When you click the row to edit. The "Time" column value disappeared and it cannot be edited as well.

**Comment by codingbunny** [comment]
Sorry for bother you again, I have another question:
Assume there are column1 column2  and column3(C1 C2 C3),
selection of C3 is based on selection of C2 as the fiddle example. But it is also based on selection of C1, if C1 is true, C2 and C3 work normally, if C1 is false, then C3 have to be null or freezed. What I am thinking is every time C2 is on change, make a judgement on C1. But there is no way that I can get current selection of other column on insert or edit mode right? So do you have any advice on this? Thank you very much!

**Comment by codingbunny** [comment]
Hi,
The problem is I cannot edit the "Time" column. 
http://jsfiddle.net/codingbunny/p39kteqh/16/

**Comment by tabalinas** [comment]
Here is the fiddle with fixed editing: http://jsfiddle.net/tabalinas/p39kteqh/23/
Meanwhile the issues are not related to the original question (dependent selects). There were several quite strange issues: `eidtValue` instead of `editValue`, using val() for DOM element instead of jQuery element, wrong input index.

**Comment by codingbunny** [comment]
Thank you very much! And sorry for bother you with a silly spelling mistake.

**Comment by tabalinas** [comment]
You are welcome!

**Comment by codingbunny** [comment]
Sorry for bothering you again. This question is related to the original question and there is no silly bug. It is about one column depends on 2 columns.

I have 3 select columns, "type", "department" and "team". And "team" column based on both "type" and "department".
 When I choose "DEPT" in "type", the selections of "team" column should be empty, when I choose "TEAM" in "type", the "team"is based on "Department" as normal. This function works well as demonstrated. http://jsfiddle.net/codingbunny/p39kteqh/25/

My problem is(you can try editing in the existing row):
1. At the beginning the "type" is "TEAM", and the "department" is "Dept B", and the selections of "team" are "team B" and "team C", works well.
2. And then I change the "type" to "DEPT", the selection of "team" disappear as expect, works well.
3. And then I change the "type" back to "TEAM", and the selections of "team" become "team A", "team B" and "team C".
4. The "department" column remaining"Dept B" all the time. 

I want them to be "team B" and "team C" according to "department" column, but only when I change the selection of "department" and change it back I can get the ideal result, it is because I can't find a way to know the current selection of other columns.

 I hope I have explained clear, could you give some advice about how to get current selection of those column not on change, or any other advice? Thank you very much!

**Comment by tabalinas** [comment]
I see the issue. Actually, it works like this because in your `change` handler of `type` select you filter teams only by type not considering the department.

So you need also to filter by department:

```js
...
var typeTeam = $.grep(team_list, function(team) {
    // TODO: add here filtering by department
    return team.activity_type === selectedType;
});

teamField.items = typeTeam;
$(".team-insert").empty().append(teamField.insertTemplate());
...
```

**Comment by codingbunny** [comment]
Thank you for your reply.
I agree that I should filter by department, and the issue is I don't know how to know the current selection of department when I am changing type.

**Comment by tabalinas** [comment]
You can whether find the select by jQuery selector or just get it from `jsGrid.option("fields")[index].insertControl.val()`

**Comment by codingbunny** [comment]
Thank you for your help, problem solved! http://jsfiddle.net/p39kteqh/26/
I used 

         var selectedDepartment = $(".department-insert > select").val();
and this worked very well, thank you!
But actually, for

          var selectedDepartment = jsGrid.option("fields")[3].insertControl.val();

browser said "jsGrid.option() is not a function". And for

          var selectedDepartment = jsGrid.fields[3].insertControl.val();

browser said "cannot read insertControl of undefined."

**Comment by tabalinas** [comment]
jsGrid is the instance of grid, so it's equivalent to `$('#grid').jsGrid('option', 'fields')`

**Comment by bala29000** [comment]
Hi tabalinas,
I want to Edit multiple rows and save at once.. Save button is placed outside of grid...Do you have any sample for this ??
