### ISSUE TITLE
Filter custom field

### ISSUE THREAD

**Issue by dixso** [tabalinas/jsgrid#170]
Hi,
Why the select box does not appear in the filter?
http://jsfiddle.net/tabalinas/qg4et3ey/16/ (your code)
Thanks!

**Comment by tabalinas** [comment]
Hi, 

Because you have not defined `filterTemplate` for your custom field.
So looking at `insertTemplate` it can be something like the following:
```js
    filterTemplate: function() {
        var filterControl = this._filterControl = this._createSelect();
        
        setTimeout(function() {
            filterControl.multiselect({
                minWidth: 140
            }); 
        });
        
        return filterControl;
    },
```
