### ISSUE TITLE
Table content column alignment in bootstrap modal.

### ISSUE THREAD

**Issue by scottd6** [tabalinas/jsgrid#171]
Hi,

First of all, thanks for this plugin, easy to use and very effective. :0)

This isn't a bug however I have no idea where to get an answer or how to solve myself so...

I am including a table in bootstrap 3 modal and allow the column headers and filter columns line up great the columns for the detail rows do not.  With every column in the detail section of the table the offset becomes greater.

I have no doubt this is a simple css issue however I have no idea where to start.

Thanks for your help.

Scott.

**Comment by tabalinas** [comment]
Hi, thank you for the feedback.
It's hard to say not being able to see the issue.
Try to modify the following fiddle http://jsfiddle.net/tabalinas/zzzfmpgt/ to demonstrate the issue (you can prepare your own showcase to demon state the issue)

**Comment by tabalinas** [comment]
Close due to inactivity.

**Comment by scottd6** [comment]
Hi Artem,
Sorry for my late reply, to be honest I didn't expect to receive a response and hadn't checked this email account.  I updated the fiddle however it isn't working, for some reason I cannot get the showMyModal function to fire when I click the text.  Sorry not familiar with jsfiddle.  I have tried to add bootstrap references however these don't seem to be getting picked up and it is the bootstrap that I believe is causing the issue with formatting.JSGrid Basic - JSFiddle

|   |
|   |   |   |   |   |
| JSGrid Basic - JSFiddleTest your JavaScript, CSS, HTML or CoffeeScript online with JSFiddle code editor. |
|  |
| View on jsfiddle.net | Preview by Yahoo |
|  |
|   |


Thanks for you help.
Kind Regards,
Scott.

**Comment by tabalinas** [comment]
I see. But not having a demo to be able to reproduce the issue, I cannot help. If you have a web page with external access where I can see the issue, please, feel free to share it.

**Comment by scottd6** [comment]
Hi Artem,
I appreciate that, I will get back to you shortly.  Thanks again for your patience and assistance.
