### ISSUE TITLE
Is their a method to show/hide the insert row.

### ISSUE THREAD

**Issue by danielson317** [tabalinas/jsgrid#174]
I want the user to see just the current values unless they hit an "add new" button. Is it possible to show/hide the insert row?

**Comment by danielson317** [comment]
It appears this can be accomplish via the option method

     $('.name-charge_table').jsGrid('option', 'inserting', false);

**Comment by tabalinas** [comment]
Yes, you are right, it can be done changing this option.

**Comment by JeffMatthews2** [comment]
FYI, clearInsert method does not appear to work.  The alternative shown above works fine.

>$("#grid").jsGrid("clearInsert");

http://js-grid.com/docs/#clearinsert
