### ISSUE TITLE
Support for jQuery Validation

### ISSUE THREAD

**Issue by cigano** [tabalinas/jsgrid#176]
I really missed a functionality that can integrate jQuery Validation with Ajax events.

**Comment by tabalinas** [comment]
If grid will have build-in validation, is it fine?

I've played with jQuery Validation integration, but faced with few issues. In particular jQuery Validation requires a `<form>`, which in case of table is not applicable.

**Comment by cigano** [comment]
Okay for me. It doesn't need to be jQuery Validation. I just need to have a
way to provide an error message per field or per entire line.
