### ISSUE TITLE
How can i update single row ?

### ISSUE THREAD

**Issue by thoriyas** [tabalinas/jsgrid#180]
```js
updateItem: function(item) { 
 function(result, event){
if (event.status) {
 // Here i want to update row data with result data
} 
}
}
```

**Comment by tabalinas** [comment]
I didn't get the question. Could you provide more details and entire jsGrid config?

**Comment by thoriyas** [comment]
On update i'm calling my back-end method, I have some logic into the back-end there were rowdata are change on update and updated date return as a result. So here i want to update JS Grid row with updated row data.. result is my Updated RowData.

**Comment by tabalinas** [comment]
If I got your question correctly, the answer is in docs of `controller.updateItem` http://js-grid.com/docs/#updateitemitem-promiseupdateditem 
> Method should return updatedItem or jQuery promise that will be resolved with updatedItem. If no item is returned, updating item will be used as updated item.

So you need to resolve the promise with the updated item returned by server script like following:

```js
    updateItem: function(item) {
        var d = $.Deferred();
        $.ajax({
            url: "url.to.update.item",
            type: "POST",
            data: item
        }).done(function(updatedItem) {
            d.resolve(
        });
        return d.promise();
    }
```
