### ISSUE TITLE
Dynamic fields generation

### ISSUE THREAD

**Issue by kellerkind** [tabalinas/jsgrid#181]
Hi,
i am trying to get jsgrid to work with DRF (Django Rest Framework). The main goal is to create the fields in dynamic way. First basic text for testing and latter mapping the Django ORM models field format to an appropriate jsgrid one. Is there an existing function where I can put this magic in? The returning json from DRF may look like this: You see that also pagination and count of records is already there.

	{
	    "count": 2,
	    "next": null,
	    "previous": null,
	    "results": [
		{
		    "id": 1,
		    "name": "node01tp001",
		    "parent": "node01s001",
		    "uuid": "de264db2-fcf5-4e39-8325-6d9c06f68297",
		    "status": "planned",
		    "stage": "T",
		    "application": "",
		    "planning_comment": "",
		    "operational_comment": "",
		    "location": "",
		    "middleware": null,
		    "service_level": null,
		    "tshirt_size": null,
		    "business_service": null,
		    "ts_derivative": null
		},
		{
		    "id": 2,
		    "name": "node01s001",
		    "parent": null,
		    "uuid": "b66eaac4-8820-4bf7-b07a-69aa2877b794",
		    "status": "planned",
		    "stage": "T",
		    "application": "",
		    "planning_comment": "",
		    "operational_comment": "",
		    "location": "",
		    "middleware": null,
		    "service_level": null,
		    "tshirt_size": null,
		    "business_service": null,
		    "ts_derivative": null
		}
	    ]
	}

**Comment by tabalinas** [comment]
To generate fields on the fly you can do the following:

```js
// request fields metadata
$.ajax({ ... }).done(function(fieldsMetadata) {
    var fields = $.map(fieldsMetadata, function(fieldMetadata) {
         // turn fieldMetadata into jsGrid field description
         return { ... }
    });

    // init jsGrid
    $("#jsGrid").jsGrid({
        fields: fields,
        ...
    }) 
});
```

Is it what you asking about or I'm missing something?

**Comment by kellerkind** [comment]
Yes, will try that out, thanks!
