### ISSUE TITLE
mistyped paths in some demos

### ISSUE THREAD

**Issue by jmoreau-enquizit** [tabalinas/jsgrid#182]
The following links are mistyped (missing 'http:')
```
<link rel="stylesheet" href="//code.jquery.com/ui/1.11.2/themes/cupertino/jquery-ui.css">
<script src="//code.jquery.com/jquery-1.10.2.js"></script>
<script src="//code.jquery.com/ui/1.11.2/jquery-ui.js"></script>
```
in the custom-grid-field, data-manipulation and rows-reordering demos

**Comment by tabalinas** [comment]
No, it's valid url http://stackoverflow.com/questions/8951423/html-links-without-http-protocol

**Comment by jmoreau-enquizit** [comment]
OK.....I won't work when viewing it locally (which is what I was doing).

From that SO link:

If a web page is saved on a local disk and then opened from there, it has no protocol (just the file: pseudo-protocol), so URLs like //www.example.com won’t work; so here’s one reason for including the “http:” or “https:” part.

**Comment by tabalinas** [comment]
Agree, it makes sense.
