### ISSUE TITLE
Mutliple jsGrid implementions on the same page?

### ISSUE THREAD

**Issue by ViniH** [tabalinas/jsgrid#185]
Hello,

I've bee struggling with an issue whereby when I add more than one jsGrid into a page, only the most recently added jsGrid resizes properly when the parent container is resized.

I was wondering if jsGrid was designed to support more than one within a given DOM in the first instance, and if not, could this be looked at?

I can provide a jsfiddle example if absolutely necessary but I am hoping to avoid the need to write one, by having the above question answered first.

**Comment by tabalinas** [comment]
Hello, 

definitely multiple jsGrid should work fine on the same page. If you spotted an issue, please, provide more details. jsfiddle to be able to reproduce the issue would be perfect,
Thank you!

**Comment by tabalinas** [comment]
Any update on that?

**Comment by ViniH** [comment]
One of the problems was that pagerContainer for the external pager we identified using an id, which was not unique when more than one JSgrid object were being added to the DOM - I resolved this by using a different selector and removing the ID from the target container.  The other half of the issue was caused by failing to unsubscribe from events properly.  In both cases it was not JSgrid at fault.

**Comment by tabalinas** [comment]
Glad you figured it out. Thanks for the update!

**Comment by triadss** [comment]
one page have two grid but not working while loading one grid anther jsgrid header rows are automatically removed
