### ISSUE TITLE
Set sorting CSS returns incorrect field index when setting columns visible = false

### ISSUE THREAD

**Issue by mandarinsoda** [tabalinas/jsgrid#187]
I just noticed a minor bug playing around with dynamically hiding and showing columns.  If you hide a column at the beginning of a table, if sorting is enabled and one sorts a column after the column that was hidden, the correct field value is selected for sorting but jsgrid selected the wrong header field to highlight, as the fields array index doesn't take into account the hidden field in the following method:

```
_setSortingCss: function() {
            var fieldIndex = $.inArray(this._sortField, this.fields);

            this._headerRow.find("th").eq(fieldIndex)
                .addClass(this._sortOrder === SORT_ORDER_ASC ? this.sortAscClass : this.sortDescClass);
        }
```
Seems too minor for me to issue a pull request, but I could be wrong there.  Hope this is helpful.

Thanks!

**Comment by tabalinas** [comment]
Thank you for reporting this horrible bug!
