### ISSUE TITLE
I am unable to bind dropdown and grid on json post method in db.js

### ISSUE THREAD

**Issue by Itsathere** [tabalinas/jsgrid#188]
I am working in mvc4 and I am unable to bind dropdown and grid also.On grid bind through database through below method in db.js

```js
  $.get("/Merchandise/GetMerchandise",
   function (data) {
       debugger;
       db.clients = JSON.parse(JSON.stringify(data));
   }, "json");
```

 grid is not binding dynamic data and is showing "Please, wait..." till now after 20-30 minutes.

**Comment by geloh** [comment]
From the docs:
> $("#jsGrid").jsGrid({ 
        controller: {
            loadData: function() {
                var d = $.Deferred();
                $.ajax({
                    url: "/Merchandise/GetMerchandise",
                    dataType: "json"
                }).done(function(response) {
                    d.resolve(response.value);
                });
                return d.promise();
            }
        }
});

You need to be sure that your api is returning an array.

**Comment by Itsathere** [comment]
Now, I am able to bind grid like below method

loadData: function (filter) {
            return $.ajax({
                type: "GET",
                url: "/Merchandise/GetMerchandise",
                data: filter,
                dataType: "json"
            });
        },

and I have also bind the dropdownlist dynamically.Now, I am unable to bind datepicker and datefromat in respective column.

**Comment by geloh** [comment]
Hi. This sample code shows how you could get dynamic data from the server.
```
//loading data to display
function loadData() {
  var data = $.Deferred();
  $.ajax({
      url: "/your/api",
      dataType: "json",
      async: false
  }).done(function(response) {
  //do whatever you wanna do with response 
      data.resolve(response);
  });
  return data.promise();
}

var fields = [
      { name: "id", title: "Id", type: "text", width: 100 },
      { name: "name", title: "Name", type: "text", width: 200 }
    ];

$("#jsGrid").jsGrid({
  height: "90%",
  width: "100%",
  filtering: true,
  editing: true,
  sorting: true,
  paging: true,
  autoload: true,
  pageSize: 15,
  pageButtonCount: 5,
  deleteConfirm: "Do you really want to delete the client?",
  fields : fields,
  controller: {
      loadData: loadData
  },
});
```

**Comment by Itsathere** [comment]
I need dynamic implementation in db.js not inside view page. Please implement it in db.js and the set db.clients = [] value dynamically then I will able to do everything I need.

Thanks.

**Comment by tabalinas** [comment]
Just extract the code kindly provided by @geloh to `db.js`. You can implement other controller methods similarly. If you have a concrete issue or a question, feel free to ask.

**Comment by Itsathere** [comment]
I am unable to bind dropdownlist with database. Some times it's working some times not working.Can you explain me the reason

{ name: "Location", type: "select", items: db.Locations, valueField: "LocationID", textField: "Description", width: 200 },

in the above code snippet, I think **name** is the data-field of dropdownlist  **valueField** is value of dropdownlis and **textField** is text of dropdownlist. Am i right?.
