### ISSUE TITLE
Selecting the column (field) that must be sorted by default

### ISSUE THREAD

**Issue by djvnsk** [tabalinas/jsgrid#189]
Hi,
How to force the field that will be used to sort (from the time the page is loaded)? Example: by field "Address".
I use code like in Basic Scenario [demo](http://js-grid.com/demos/).

**Comment by geloh** [comment]
Hi. Supose you have a field named "address", for example.
```
$("#jsGrid").jsGrid("sort", "address");
```

**Comment by tabalinas** [comment]
Thank you @geloh, I think it's exactly what is needed.
