### ISSUE TITLE
Problem with jquery-ui dialog to add/modify

### ISSUE THREAD

**Issue by fanturi** [tabalinas/jsgrid#19]
Hi,

I need to have a modal window for editing/inserting data.
I used your example and adapt it with my needs (I need to validate data before the save).
I created a mix between the jquery website example and yours to use also the buttons options of the dialog for a better integration.
If I modify a line it's ok the first time but I have an error when I try to modify a line again after.
The problem is the item is null in updateItem. I don't understand why because the object is correct just before the call to updateItem.
Here the code, have you an idea ?

Thanks.

```javascript
var dialog = $( "#dialog-form" ).dialog({
    autoOpen: false,
    width: 850,
    modal: true,
    closeOnEscape: true,
    buttons: {
        Save: function() {
	     $("#categoryForm").submit();
         },
         Cancel: function() {
	     $(this).dialog("close");
	  }
        },
        close: function() {
	     dialog.find("form")[0].reset();
        }
});

var showDetailsDialog = function(dialogType, category) {
    $("#code_cat").val(category.code_cat);
    $("#descr_fra").val(category.descr_fra);
    $("#descr_eng").val(category.descr_eng);
    $("#descr_deu").val(category.descr_deu);
        
     dialog.find("form").submit(function() {
         if($("#categoryForm").valid()) {
	     event.preventDefault();
	     saveClient(category, dialogType === "Add");
	 }
     });

     dialog.dialog("option", "title", dialogType + " category").dialog("open");
 };

var saveClient = function(category, isNew) {
      $.extend(category, {
           code_cat: $("#code_cat").val(),
	   descr_fra: $("#descr_fra").val(),
	   descr_eng: $("#descr_eng").val(),
	   descr_deu: $("#descr_deu").val()
      });
      console.dir(category);
      $("#jsGrid").jsGrid(isNew ? "insertItem" : "updateItem", category);

       dialog.dialog("close");
};
```

**Comment by tabalinas** [comment]
The problem is that you attach submit handler on each dialog show. Thus when you change an item for the second time, the submit handler is fired twice. On third show three times and so forth.

See following working fiddle:
http://jsfiddle.net/tabalinas/kj6d6tw5/

**Comment by fanturi** [comment]
It's perfect !
You saved my day :)

Thanks a lot.

**Comment by tabalinas** [comment]
You are always welcome!
