### ISSUE TITLE
Sorting with Promise

### ISSUE THREAD

**Issue by ViniH** [tabalinas/jsgrid#192]
Would you be able to provide an example of how to enable/allow sorting when the data is supplied by a promise asynchronously?

At the moment with sorting enabled the column headers become click-able and the asc/desc indicator icon shows, but the rows are not sorted.

I would ideally like to be able to sort without having to go and re-get the data.

**Comment by christopher-worley** [comment]
If you are having issues with the loadData controller not sorting... I had to keep track of the last filter used in the search.  I also had to provide a starting sort when the user first comes to the page.  I append the filter to my search url.  Not sure if there is a better way.

		        controller: {
		            loadData: function(filter) {
		            	if (that.firstFilter) {
		            		that.firstFilter = false;
		            		filter = that.initFilter;
		            	}
		            	that.filter = filter;
		                return $.ajax({
		                	type: "GET",
		                	url: '/service/search',
		                	data: "filter=" + JSON.stringify(filter),
		                	dataType: "json"
		                });
		            }

**Comment by tabalinas** [comment]
Talking about original question: what is the issue with sorting? If you don't specify `pageLoading: true` sorting should work for async load just like for sync example.
For `pageLoading: true` all data should be sorted on the server, all jsGrid is doing - providing sort field and direction in parameters.
Could you provide more details about the issue?
