### ISSUE TITLE
Change the select field items depending on the grid rows

### ISSUE THREAD

**Issue by rdksgit** [tabalinas/jsgrid#193]
Hi

We are using js-grid for a project where we are adding new rows, the first field in the row is the list of users (dropdown coming through database) which we are getting through ajax and all works fine

What we need to do is when we create another row, we dont want the user already selected in the previous row to appear in the second row user dropdown, this is to avoid the error of the user trying to select the same user again

This code returns the users

```js
$.ajax({
        type: "GET",
        url: "/intranet/award/ajax_staff.php"
    }).done(function(userid) {
        userid.unshift({ id: "0", displayname:"Please select" });

 // We did something like this
 onDataLoaded: function(data){
                var response = data.data,
                    $sel = $('.jsgrid-insert-row').find('select');
                $.each(response,function(k, val){
                    var selector = 'option[value="'+val.userid+'"]';
                    if(val.userid!=0){
                        $sel.find(selector).remove();
                    }
                });
            }
```

The onDataLoaded works on the reload of the page and only shows list of users not in any of the rows but the moment we add another row the new row dropdown resets to the original list

Thanks
Sameer

**Comment by tabalinas** [comment]
What is about the following solution:
You have an array of employees that is shown in the select list (your `userid` array should be good).
This array is used to render a select.
Once you insert an item with the user, remove the item from this array (in your case `userid`). And the select will contain only necessary items.
Let me know if anything is not clear.
