### ISSUE TITLE
I want to Highlight the row after row selection.

### ISSUE THREAD

**Issue by himanshu0a** [tabalinas/jsgrid#194]
Right now the row gets highlighted on hovering but I also want the row to be highlighted with a different color after it has been selected.

Please suggest a solution to this.

**Comment by soul3lade** [comment]
Hello,

You can use the rowClick function to achieve the highlighting effect.  I've added a jsfiddle that @Tabalinas created showing how to highlight a row.

`rowClick: function(args) {
          var $row = this.rowByItem(args.item);
          $row.toggleClass("highlight");
        },`

http://jsfiddle.net/tabalinas/mba4mLh8/

**Comment by tabalinas** [comment]
@soul3lade, Thank you for the answer.
@himanshu0a, please let us know if this is what you were looking for.

**Comment by himanshu0a** [comment]
Yes this is the correct answer and this is exactly i was looking for.

Thanks @soul3lade

**Comment by blainerothrock** [comment]
The above solution did not work for me, I had to set the background color for each cell in the row:

```javascript
rowClick: function(args) {
  if ( selectedRow ) { selectedRow.children('.jsgrid-cell').css('background-color', ''); }
  var $row = this.rowByItem(args.item);
  $row.children('.jsgrid-cell').css('background-color','#F7B64B');
  selectedRow = $row;
},
```

**Comment by mansoor-omrani** [comment]
I changed @soul3lade 's fiddle a little bit (changed the CSS) to make it working (it seemed it was not working).

[http://jsfiddle.net/mba4mLh8/277/](http://jsfiddle.net/mba4mLh8/277/)
