### ISSUE TITLE
Select: Write "Name", not "ID" into DB

### ISSUE THREAD

**Issue by dipiana** [tabalinas/jsgrid#195]
Hi,

I try to write the "name" of one of the items into the database instead of the "ID". Therefore I tried to use `valueField: "Name"` but it does not work. Is it supposed to work that way?

```js
fields: [
                { name: "name", title: "Name", type: "text", width: 150 },
                { name: "age", title: "Age", type: "number", width: 50, filtering: false },
                { name: "address", title: "Address", type: "text", width: 200 },
                { name: "country_id", title: "Country", type: "select", width: 100, items: [
                    { Name: "", Id: 0 },
                    { Name: "United States", Id: 1 },
                    { Name: "Canada", Id: 2 },
                    { Name: "United Kingdom", Id: 3 }
                ],
                valueField: "Name",
                textField: "id"},
                { name: "married", type: "checkbox", title: "Is Married", sorting: false, filtering: false },
                { type: "control" }          
]
```

With these options, it only displays an empty selection list and does not write anything into my DB.

Thanks a lot!

**Comment by tabalinas** [comment]
The issue is `textField: "id"`with lowercase, while in the data you have `Id` as uppercase. But I think in your case you want textField also to be `Name`, right? Because in the code above what you'll see is just numbers (ids) instead of text.
