### ISSUE TITLE
How can i define decimal type ? 

### ISSUE THREAD

**Issue by thoriyas** [tabalinas/jsgrid#197]
I have used number type but it's would not allow me to save decimal values. for example i want to store 55.55 in some fields. how can i do this ?

**Comment by tabalinas** [comment]
You can define your own field like the following:

```js

    function FloatNumberField(config) {
        jsGrid.NumberField.call(this, config);
    }

    FloatNumberField.prototype = new NumberField({

        filterValue: function() {
            return parseFloat(this.filterControl.val());
        },

        insertValue: function() {
            return parseFloat(this.insertControl.val());
        },

        editValue: function() {
            return parseFloat(this.editControl.val());
        }
    });

    jsGrid.fields.floatNumber = FloatNumberField;

```

**Comment by C4Grey** [comment]
Just a little notice - a prototype of a FloatNumberField shold be jsGrid.NumberField since NumberField is hidden behind IIFE. Also text should be formatted to use a proper delimiter.

**Comment by snagareddy** [comment]
Hi,
Can i know where to add the code for getting decimal places in the field

**Comment by tabalinas** [comment]
If I get you right, you need to redefine `itemTemplate` something like following:

```js
    ...,
    itemTemplate: function(value) {
        return value.toFixed(2);
    }
```

Is it what are asking about?

**Comment by lodb** [comment]
When using the FloatNumberField code mentioned above, pressing enter while in a field still shows the message "Please enter a valid value. The two nearest valid ....." while saving (ie clicking the green V does work.. I've been looking at the code but couldn't find what I needed in jsgrid.field.number.js

Any help would be much appreciated!
