### ISSUE TITLE
How to create a filter programmatically

### ISSUE THREAD

**Issue by soongsta** [tabalinas/jsgrid#198]
Hi There

How do you create a filter programmatically? Is it by assigning the filter value like below?

" filter: {Married : true}, "

            $("#jsGrid").jsGrid({
                height: "80%",
                width: "100%",

                filtering: true,
                editing: true,
                sorting: true,
                paging: true,
                autoload: true,

                pageSize: 15,
                pageButtonCount: 5,
                
                data: clients,
                filter: {Married : true},
                
                fields: [
                    { name: "Name", type: "text", width: 150 },
                    { name: "Age", type: "number", width: 50 },
                    { name: "Address", type: "text", width: 200 },
                    { name: "Country", type: "select", items: countries, valueField: "Id", textField: "Name" },
                    { name: "Married", type: "checkbox", title: "Is Married", sorting: false },
                    { type: "control", modeSwitchButton: false, editButton: false }
                ]
            });

**Comment by tabalinas** [comment]
To filter the grid programmatically you can use `search` method: http://js-grid.com/docs/#searchfilter-promise
But if you wish to set filter values in the filter row controls, there is no built-in feature for that. You have to set the value your self with jQuery: `$(".my-filter input").val("My filter value")`.
