### ISSUE TITLE
Get filterValue on headerTemplate

### ISSUE THREAD

**Issue by fanturi** [tabalinas/jsgrid#20]
Hi,

It's me again :)

Is it possible to get the filterValue() of a given column in the headerTemplate function of control column ?

I use a dialog to insert/update item. I would like to initialize a value with the one in the filter if the user add a new item.
I'm able to get this value in the rowClick function, used for the update like this: 
```javascript
this.fields.filter(function(item) { return item.name === 'id_ref_comp_cat'; })[0].filterValue()
```

Is it possible to get this value in the headerTemplate ?

```javascript
headerTemplate: function() {
              return $("<button>").attr("type", "button").attr("title", "Add").addClass("jsgrid-button").addClass("jsgrid-mode-button").addClass("jsgrid-insert-mode-button")
                .on("click", function () {
                 console.dir(this.fields.filter(function(item) { return item.name === 'id_ref_comp_cat'; })[0].filterValue());
                  showDetailsDialog("Add", {});
                });
            }
```

Or maybe in the function showDetailsDialog directly ?

**Comment by tabalinas** [comment]
Hi!

For now you can do it from anywhere calling `_getFilter` method of the grid like this:

````javascript
$("#jsGrid").jsGrid("_getFilter")
```` 

Currently, this method is private, so I'll think about its publication. Looks like it could be really useful.
Thank you for feedback!

**Comment by fanturi** [comment]
perfect !
thanks.
