### ISSUE TITLE
Basic filters are not working

### ISSUE THREAD

**Issue by dhawkKD** [tabalinas/jsgrid#200]
Hi,

I have tried to use filters in js.grid, but seems its not working.
For filters, I have done 2 things filterable:true,
and controller:data,.

By setting above two properties I was able to get the filters in the Grid but when trying to filter data,
didn't got any success.
Please help.

**Comment by soul3lade** [comment]
Hello,

Filtering is done entirely on the server.  So when you pass along your filter to your back-end code, you will have to filter your results and then return them.  JsGrid will not do any filtering for you.

Im not sure what server side implementation you are using, but this page has a few examples of using jsGrid with them.

http://js-grid.com/samples/

**Comment by tabalinas** [comment]
Yes, actual data filtering should be done by developer on client side, server side or both.
Another issue could be that there is no option `filterable:true`, the grid has an option `filtering` http://js-grid.com/docs/#filtering-default-false.

**Comment by dhawkKD** [comment]
Actually I don’t want to do it on server side, and from the demo’s I thought its an inbuilt feature of Js grid. How can I achieve this on client side. Do you have any example of that.

Regards,
Kapil Dhawan

**Comment by Praveen-Charminar** [comment]
I also faced clientside filtering issue today, I got this solved by modifying code in below way. here gridData is passed from server for firsttime load in grid.

.jsGrid({
        height: "70%",
        width: "100%",
        filtering: true,
        editing: false,
        inserting: false,
        sorting: true,
        paging: true,
        autoload: true,
        pageSize: 15,
        pageButtonCount: 10,
        fields: [          
            { name: "Name", type: "text", width: 150 }            
        ],
        controller: {
            data:gridData,
            loadData: function (filter) {
                return $.grep(this.data, function (item) {
                    return (!filter.Name || item.Name.indexOf(filter.Name) >= 0);
                });
            },          
        }
    });

**Comment by dhawkKD** [comment]
Hi,

When I tried the solution provided by you, I found filter is undefined and getting error .

Regards,
Kapil

**Comment by kirankocherla** [comment]
Hi,

We get filter is undefined if data is not applied in controller data. Please check your code and apply data only on the controller data not in grid data.

Regards,
Praveen M

**Comment by dhawkKD** [comment]
Hi,

I have done exactly the same which is provided in the example, but still didn’t get any success. Can you share the basic code for this, that would be great help.

Regards,
Kapil Dhawan

**Comment by dhawkKD** [comment]
Thanks for the reply I am able to filter for a field. Just need to know how can I filter data on multiple fields together.

**Comment by tabalinas** [comment]
You are welcome!
Not sure what is the difference between filtering by single or multiple fields.
Just checkout backend sample projects, they already have this solved.

--
Best Regards,
Artem Tabalin
tabalinas@gmail.com

**Comment by dhawkKD** [comment]
Can you please share the link of backend sample projects.

**Comment by tabalinas** [comment]
Checkout here http://js-grid.com/samples/

**Comment by saikiran214333** [comment]
@dhawkKD @Praveen-Mudem @tabalinas  i am trying to filter.Grid is showing with the values but the filters are not working.. can any one tell the solutiion
$(function() {
		
	
				$("#jsGrid").jsGrid({
					height : "auto",
					width : "100%",
					filtering: true,
					sorting : true,
					paging : true,
					autoload : true,
					pageSize : 10,
					fields : [ {
						name : "patientId",
						type : "text",
						width : 150
					}, {
						name : "patientName",
						type : "text",
						width : 150
					}, {
						name : "genderId",
						type : "number",
						width : 150
					}, {
						name : "mobile",
						type : "number",
						width : 150
					}, {
						
					} ],
					controller : {
						loadData : function(filter) {
									return  $.ajax({
							        type: "GET",
							        url : "/Final/Reports",
							        data: "url"
						              return $.grep(this.data, function (item)-----> can you tell what is item. 
									  {
						                    return (!filter.patientId || item.patientId.indexOf(filter.Name) >= 0);
						                    return (!filter.patientName || item.patientName.indexOf(filter.Name) >= 0);
						                    return (!filter.genderId || item.genderId.indexOf(filter.Name) >= 0);
						                    return (!filter.mobile || item.mobile.indexOf(filter.Name) >= 0);
						                });
						            
							    
							  
							    }
					},
				}); 

			}); 
.

**Comment by drmargarido** [comment]
I changed the controller be allow search in any field of the table without hardcoding all of the fields.
``
$("#jsgrid").jsGrid({
        width: "100%",
        height: "400px",

        filtering: true,
        sorting: true,
        paging: true,

 	pageSize: 10,
        data: job_offers,
 
        fields: [
            { name: "Title", type: "text", width: 150 },
            { name: "District", type: "text", width: 100 },
            { name: "Creation Date", type: "text", width: 200 }
        ],
        controller: {
            data:job_offers,
            loadData: function (filter) {
                return $.grep(this.data, function (item) {
                    // Check if all the fields are empty
                    var all_empty = true;
                    for (var field in filter) {
                        if(filter[field]){
                            all_empty = false;
                        }
                    }

                    // If all the search fields are empty return all the rows
                    if(all_empty){
                        return true;
                    }

                    // If some search field has content check if it matches the table entries
                    for(var field in filter){
                        
                        // Ignore the search in empty fields
                        if(!filter[field]){
                            continue;
                        }

                        if(item[field].indexOf(filter[field]) >= 0){
                            return true;
                        }
                    }

                    return false;
                });
            },          
        }
    });

``

**Comment by drmargarido** [comment]
And here a solution with multiple field searching

```js
controller: {
            data:job_offers,
            loadData: function (filter) {
                return $.grep(this.data, function (item) {
                    // Check if all the fields are empty
                    var all_empty = true;
                    for (var field in filter) {
                        if(filter[field]){
                            all_empty = false;
                        }
                    }

                    // If all the search fields are empty return all the rows
                    if(all_empty){
                        return true;
                    }

                    var fields_to_search = [];
                    // Add fields to search in order to allow multiple fields searching
                    for(var field in filter){

                        // Ignore the search in empty fields
                        if(!filter[field]){
                            continue;
                        }

                        fields_to_search.push(field);
                    }

                    var matched = true;
                    // Check if all the fields match 
                    for(var i=0; i < fields_to_search.length; i++){
                        var field = fields_to_search[i];
                        if(!(item[field].indexOf(filter[field]) >= 0)){
                            matched = false;
                            break;
                        }
                    }

                    return matched;
                });
            },          
        }
```

**Comment by lovelivnlife** [comment]
Here's the solution used on http://js-grid.com/demos/ though you have to dig in the debug console to find it.
```javascript
    controller: {
        data:clients,
        loadData: function (filter) {
            return $.grep(this.data, function (item) {
                return (!filter.Name || item.Name.indexOf(filter.Name) > -1)
                && (!filter.Age || item.Age === filter.Age)
                && (!filter.Address || item.Address.indexOf(filter.Address) > -1)
                && (!filter.Country || item.Country === filter.Country)
                && (filter.Married === undefined || item.Married === filter.Married);
            });
        },
    }
```

**Comment by latuzu** [comment]
Javascript solution is:

controller: {
                data:data,
                loadData: function (filter) {
                    return $.grep(this.data, function (item) {
                        let flag = true;
                        for (key in filter) {
                            if (key != undefined) {
                                flag = flag && (!filter[key] || item[key].indexOf(filter[key]) >= 0);
                            }
                        }
                        return flag;
                    });
                },          
            },

**Comment by yjcho2252** [comment]
My solution for django version based on [demo code](https://github.com/tabalinas/jsgrid-django/blob/master/clients/templates/index.html) is:

```
                    loadData: function(filter) {
                        var d = $.Deferred();

                        $.ajax({
                            type: "GET",
                            url: "/clients/api",
                            data: filter
                        }).done(function(result) {
                            result = $.map(result, function(item) {
                                if (item.fields.name.indexOf(filter.name) > -1
                                    && item.fields.age.indexOf(filter.age) > -1
                                    && item.fields.address.indexOf(filter.address) > -1
                                ){
                                    x =  $.extend(item.fields, { id: item.pk });
                                    return x
                                }
                            });
                            d.resolve(result);
                        });

                        return d.promise();
                    },
```
