### ISSUE TITLE
Disable delete on condition & edit in disabled mode

### ISSUE THREAD

**Issue by anisiaalexandra** [tabalinas/jsgrid#201]
Hi,

I have been using the plugin for a few days now and it gives you a great way of using grids in a light way.
I have 2 question, for which I was not able to come up with answers myself so if you would be so kind to help me I would greatly appreciate it:
1. I need to hide the delete button on a row according to a value in the properties of the current row item. I tried to implement rowRenderer, but that is a bit to much customization, so I was wondering if there is any way to call the default rowRenderer and then, before returning the html just hide or dhow the delete according to the value?
2. Is  there a way of make a ranking field that would only display, or be enable only in display view, but with which I could do some javascript calls?

Thank you very much in advance.

Best regards,
Anisia Pop

**Comment by tabalinas** [comment]
Hi,

Thank you for the feedback!
1) instead of `rowRenderer` you can define `cellRenderer`.
If it's also too much customization, then you can redefine the `itemTemplate` of `control` field. Add some conditions on the item.
Here is built-in template:

```jsvascript
        itemTemplate: function(value, item) {
            var $result = $([]);

            if(this.editButton) {
                $result = $result.add(this._createEditButton(item));
            }

            if(this.deleteButton && /* your item conditions here */) {
                $result = $result.add(this._createDeleteButton(item));
            }

            return $result;
        },
```

2) didn't get the idea here. Please, provide more details or an example of the usecase.

**Comment by anisiaalexandra** [comment]
Hey,

Just wanted to thank you for your help. It solved both of the issues I had, because for the second I needed to return in the itemTemplate an html a button that would do something on button click, so got that working as well :). I just want to say one more time: really good plugin, very versatile, easy to customize and easy to integrate with other plugins. Thanks!

**Comment by tabalinas** [comment]
@anisiaalexandra, thank you for the update on results and so pleasing feedback. I really appreciate it.
