### ISSUE TITLE
Incorrect filter applied when multiple properties with dot notation used

### ISSUE THREAD

**Issue by dchekanov** [tabalinas/jsgrid#202]
When I set `filtering` to `true` globally and describe fields like this:

```javascript
fields: [
        { name: "properties.one", type: "text" },
        { name: "properties.two", type: "text" }
    ]
```

`controller.loadData` receives `{"properties":"value"}`.

Expected: `{"properties":{"one":"value", "two":"value"}}`.

Here is a jsfiddle: https://jsfiddle.net/keleran/LmLys8rz/

**Comment by tabalinas** [comment]
Thank you for the detailed and clear bug report!

**Comment by tabalinas** [comment]
Should be fixed with this https://github.com/tabalinas/jsgrid/issues/203

**Comment by dchekanov** [comment]
Works great, thanks!
