### ISSUE TITLE
Support Nested Json Data

### ISSUE THREAD

**Issue by phyllis0618** [tabalinas/jsgrid#203]
Hi,

I realize for the nested data like this
{name: "Address.city", type: "text"},

Read is fine, but when submit actually it does not write into db, and sorting, filtering are not work in this case.

BTW, if support the nested column for nested fields will be better, but that is more stretch.

Thanks

**Comment by tabalinas** [comment]
Nested fields should work for reading and for writing. If it doesn't work it's a bug. The issue is not clear. The thing is jsGrid doens't write data to db since it's client-side control. Would be great if you could provide an example (jsfiddle demonstrating the issue would be appreciated).
Thank you!

**Comment by phyllis0618** [comment]
Please see the example here:
http://jsfiddle.net/38mrv9tf/

I use the nested fields and the data table can read, but add, sort and filter do not work.

Thanks!

**Comment by pramodachary** [comment]
Jsgrid sorting is not working fine with nested data model...Please fix this bug ASAP.

**Comment by tabalinas** [comment]
@pramodachary, could you please open a separate issue for this and provide an example?

**Comment by carlosalzate74** [comment]
Hey

I am using v.1.5.2 and sort is not working when using dot notation, was it fixed on the newer version?

This is how my object looks like:

[  
  {
    "id": 24,
    "user_id": 1,
    "allowed": true,
    "plan": {
      "id": 1,
      "planName": "Christmas"
    }
  }
]



BTW, thanks for this great component

**Comment by stevehn** [comment]
Any idea on how I can reconfigure jsGrid to recognize this json format?
{"ROWCOUNT":1,"COLUMNS":["ID","USER_ID"],"DATA":{"ID":[3],"USER_ID":["user1"]}}

I don't want to make another webservice for jsGrid if I don't have to.

**Comment by tabalinas** [comment]
@stevehn, it's a subject for a separate issue. A short answer would be: no need in a separate service, you always can remap data to expected format in the `controller.loadData`.
