### ISSUE TITLE
set height after loading data

### ISSUE THREAD

**Issue by vahidhiv** [tabalinas/jsgrid#205]
Hi, I want to set height of table to 50% of its parent.
I tried it on creating table by setting 'height' attribute but it doesn't work.
I did this after loading data using jquery by this code:
`$("#portfolioJsgrid").jsGrid().height(xxx);`
first it got my set height but again resizes to first height.
How should I handle this???

**Comment by tabalinas** [comment]
Hi,
Please, checkout this issue https://github.com/tabalinas/jsgrid/issues/41

**Comment by vahidhiv** [comment]
It wasn't the solution i expected but solved my problem to some extent. Thank you for your attention.
