### ISSUE TITLE
ajax parameters

### ISSUE THREAD

**Issue by ShinDj** [tabalinas/jsgrid#208]
i want to call webmethod with parameters..but i cant..
is it possible?
```js
loadData: function(filter) {
return $.ajax({
type: "POST",
url: "info.aspx/GetList",
data: "{'Id':'abc', 'Name':'john'}",
dataType: "json"
});
}
```

**Comment by tabalinas** [comment]
Yes, it's possible. It's not even on jsGrid side. You just do an ajax request with jQuery. It doesn't matter do you have parameters or not.
You can try first to debug you request and be sure the url you are requesting is accessible.
