### ISSUE TITLE
Re: Loading jsGrid by calling Controller/WebService in MVC

### ISSUE THREAD

**Issue by skamal-IBP** [tabalinas/jsgrid#210]
HI,

Am really struggling to load the jsGrid using Controller service. Am not able to do it correctly. Can anyone pleas help em out.

I even tries the sample code in your demo but that too didn't work.

I get no data everytime I try suing below code.

Appreciate if anyone can help.

This is how am loading the jsGrid:
  
$(element).jsGrid({
       
       height: 300,
        
       width: "100%",

        filtering: true,
        sorting: true,
        paging: true,
        autoload: true,
        pageLoading: true,

        controller: {
            loadData: function (filter) {
                $.ajax({
                    type: "GET",
                    url: "../Common/GetData",
                    data: filter,
                    dataType: "JSON"
                });
            }
        },
        pageSize: 10,
        pageButtonCount: 5,
        pageIndex: 1,

        noDataContent: "No Record Found",
        loadIndication: true,
        loadIndicationDelay: 500,
        loadMessage: "Please, wait...",
        loadShading: true,

        fields: [
            { name: "Name", type: "textarea", width: 150 },
            { name: "Age", type: "number", width: 50 },
            { name: "Address", type: "text", width: 200 },
            { name: "Country", type: "select" },
             {
                 name: "", type: "text", width: 50, sorting: false, filtering: false,
                 itemTemplate: function (value) {
                     return '<div class="edit-container"><a class="edit-custom-field-link">Edit</a><div class="sort-icon-container"><div class="up-arrow-icon"></div><div class="down-arrow-icon"></div></div></div>';
                 }
             }
            //{ name: "Married", type: "checkbox", title: "Is Married", sorting: false }
            //,{ type: "control" }
        ]
    });

**Comment by tabalinas** [comment]
Have you found the solution? It was `return $.ajax(...)` as specified in the docs http://js-grid.com/docs/#grid-controller?

**Comment by skamal-IBP** [comment]
only $.ajax didn;t work, but following code did,

 controller: {
            loadData: function (filter) {
                var deferred = $.Deferred();

                $.ajax({
                    url: '../Common/GetData',
                    dataType: 'json',
                    type: "POST",
                    data: filter,
                    success: function (data) {
                        deferred.resolve(data);
                    }
                });
                return deferred.promise();
            }
        },

**Comment by tabalinas** [comment]
Returning $.ajax (means returning the deferred of ajax call) has in this case the same effect as creating own deferred and resolving it with request results. 
So it should work if you just return $.ajax.
