### ISSUE TITLE
Rows reordering not working after columns visibility changed with 'fieldOption' method.

### ISSUE THREAD

**Issue by SevaJmurov** [tabalinas/jsgrid#211]
Hi!
 I've used sortable from demo together with showing/hiding columns. And found that rows become inactive after .jsGrid('fieldOption','field_name','visible',true/false) called on any field/column.

**Comment by tabalinas** [comment]
Yes. This emo uses jquery sortable plugin. When field is shown or hidden the grid renders rows again. So the reordering won't work. The possible fix could be initializing sortable in `onRefreshed` callback. Then each time grid rows are rendered the sortable will be initialized. 
Maybe it really make sense to improve the demo. Thanks for the report.

**Comment by SevaJmurov** [comment]
Not at all.
Thanks for jsGrid.
Placing sortable in onRefreshed solves the issue.
