### ISSUE TITLE
Default value for filtering

### ISSUE THREAD

**Issue by kirilvit** [tabalinas/jsgrid#213]
Could you implement setting default value for filtering for some columns? I download data form server using Odata interface.

**Comment by tabalinas** [comment]
For now I'm not sure how to implement elegant solution to set values of filter or insert controls. The point is - you never know what's really rendered inside the `filterTemplate` or `insertTemplate` by dev. Thus there is no proper way to set the value of the filter or insert from jsGrid code.

What's about putting initial value on your side (not on the jsGrid side):

```js
// field config
{
    filterTemplate: function() {
        var $filterControl = jsGrid.fields.text.prototype.filterTemplate.call(this);
        return $filterControl.val("initial filter value");
    }
}
```

If you have better ideas regarding it, please, share.

**Comment by kirilvit** [comment]
I've implemented default filtering for checkbox field like this:
```javascript
loadData: function (filter) {
	if (defaultFilteringShouldBeApplied) {
		filter.IsDeleted = false;
		$('.jsgrid-filter-row input:checkbox').prop({
			indeterminate: false,
			readOnly: false,
			checked: false
		});
	    defaultFilteringShouldBeApplied = false;
	}
...
```
But your suggestion is better. Now I have:
```javascript
filterTemplate: function() {
    var $filterControl = jsGrid.fields.checkbox.prototype.filterTemplate.call(this);
	return $filterControl.prop({
		indeterminate: false,
		readOnly: false,
		checked: false
	});
}
```

Anyway, the best solution I see is to have a default filtering value in field options, and then pass it to `filterTemplate` function for customization: 
```javascript 
filterTemplate: function(defaultFilterValue) { .. } 
```

**Comment by tabalinas** [comment]
Regarding your suggestion:
if we do so, you need to redefine the `fitlerTemplate` anyway, right?
Then I don't see the point of passing the parameter, if you can put it right away since you already redefining the template.
The problem is to provide default value not making user to redefine `filterTemplate`.

**Comment by kirilvit** [comment]
No, I just wanted to say that defining and using default filter values would not be a problem for those people who use `fitlerTemplate` function to render own filter inputs.

For users who want to use default filter values it would looks like this:
```javascript
fields: [
		{ name: "Name", type: "text",  defaultFilterValue: "Test Name" },
...
```

**Comment by tabalinas** [comment]
Yes, I got what you are saying. The thing I don't understand why pass this detault filter value through the config, if you redefine field `filterTemplate` anyway? So you can easily define this default value there. Or am I missing something?

**Comment by kirilvit** [comment]
I don't want to touch filter templates in my project. I redefined `filterTemplate` only for one field to setup default filter value as you suggested. But I think that grid should have some settings for such common scenario. I can implement that logic and create a Pull request, if you agree with that.

**Comment by medley56** [comment]
Is it possible to do this and also populate the filter text boxes (jsgrid-cell)? I have a default filter working as @tabalinas suggested but it's sort of invisible to the user currently because it doesn't populate the filter row. I tried to manually set the value of the input element but I can't see a way to identify the jsgrid-cell elements.

**Comment by lafual** [comment]
Here is a solution. There header's checkbox is out of synch, but once the users starts clicking it, it corrects itself.

```

var loadCount = 0;
$("#myGrid").jsGrid({

onDataLoading: function(args) {
  if (loadCount++ < 1) {
    args.filter.myCheckboxField.active = true;
  }
},
```
