### ISSUE TITLE
Filtering grid from input value when i select field and click button?

### ISSUE THREAD

**Issue by pachecoder** [tabalinas/jsgrid#214]
Hi, i have a question, i need to filter my grid when i select the field and click button with the current value? This is my current JsFiddle: http://jsfiddle.net/pachecoder/j4sjj0jz/ 
I triying filtering to achieve but i'm really stuck . Sorry for the inconveniences, and thank you for this awesome plugin.

**Comment by tabalinas** [comment]
Hi,

The `search` method should do the trick.
On the search button handler call `search` method providing the filter:

```js
$("#search").click(function() { 
    $("#docstypes").jsGrid("search", {
        id: $("#searchData").val()
    });
});
```

Also you need to consider the filter in the `loadData` function:

```js
function loadData(filter) {
  var result = $.grep(docstypes, function(item) {
  	return !filter.id || filter.id == item.id;
  });;
  return result;
}
```

Here is the working fiddle http://jsfiddle.net/tabalinas/v8g2ryv9/
I didn't implement all the functionality, only the filtering by `Id`. But the principle should be clear.

**Comment by pachecoder** [comment]
Hi, I don't know what is happening, but i can't make this code work, in my JsFiddle, using your code kindly provided, works smooth, but when use the Ajax Request to render my data, my grid renders with "Not Found". 

```
function loadData(filter) {

  var data = $.Deferred();
  $.ajax({
      type: "GET",
      url: "/api/DocsTypes/",
      async: false
   }).done(function (response) {
      data.resolve(response);
  });
  var result = data.promise();

 var filterData = $.grep(result, function(item) {
    return (!filter.id || filter.id == item.id) && (!filter.Description || item.Description.indexOf(filter.Description) > -1);
  });

  return filter;
} 
```

My custom search button:

```
$("#search").click(function() {
  var field = $("#searchField").val();
  var value = $("#searchData").val();
  console.log(field);
  $("#docstypes").jsGrid("search", {
    field: value
  })
});
```

This is my controller:

controller: {
            loadData: loadData,
            //[...]
        },

Sorry for the incoveniences, thank you.

**Comment by tabalinas** [comment]
You should filter data in the `done` callback of the ajax, and then resolve deferred with filtered data.
