### ISSUE TITLE
mix client side filtering with loadData dynamically 

### ISSUE THREAD

**Issue by bluelinemango** [tabalinas/jsgrid#215]
hi! 
sry for open again this issue.
i've a problem with filtering in load data in Json way!
i dont know how to do it to work correctly.
plz help me ! i wanna get my data dynamically and set client-side filtering
here my part of code: 
```js
var db = {
loadData: function(filter) {
    return $.ajax({
        type: "POST",
        url: "/client/load-json-list",
        data: filter,
        dataType: "json"
    }).success(function(filter) {
        FormsSwitchery.init();
    })
},
```

**Comment by tabalinas** [comment]
Not sure I got the issue.
You want to filter data on the server side and then filter it on the client side also?

If I got you correctly then your pattern code will be like the following:

```js
loadData: function(filter) {
    var d = $.Deferred();

    // send request to the server and filter data there
    $.ajax({
        type: "POST",
        url: "/client/load-json-list",
        data: filter,
        dataType: "json"
    }).done(function(result) {
        result = $.grep(result, function(item) {
             // some client-side filtering
             return item.MyField === filter.MyField;
        });
        d.resolve(result);
    });

    return d.promise();
},
```

**Comment by bluelinemango** [comment]
> Not sure I got the issue.
You want to filter data on the server side and then filter it on the client side also?

If I got you correctly then your pattern code will be like the following:

no! exactly i wanna do vice versa. i wanna load my data from JSON and after that filter data in client side!
i did ur code but my problem is when i filter due to filtering call loadData function and loadData get data from server , i dont want to do this! 
i wanna load my data from server (JSON) and use filtering in client Side without load $.ajax again
tnx

**Comment by tabalinas** [comment]
The code pattern code I suggested is universal, and will work for any combination. If you don't need to filter data on server, it's not an issue, just return all the data from server and filter then in `done` callback.

Your case still not clear to me. You can provide a jsfiddle for your example to make it clear.
