### ISSUE TITLE
The data field width is not same as the column header width

### ISSUE THREAD

**Issue by jufei** [tabalinas/jsgrid#216]
Hi:
    I use jsgrid to show some data from database. To show multiple table, I used the jquery Tabs UI, each table show one table. I loaded the data with Ajax and prepare the fields defination in javascript.

   My question is: yes the data show well. But the field width is wrong, the column header width is not same as the data part width. Only I clicked some column header, the column header width will be same as data part width. 

   I used the jquery Tabs UI for the first time and I set width of the grid as below:
            width:1200,
            height:550,
            autowidth: true,
            shrinkToFit : false,
            fields: gridcolumns,

I set the width only because If I do not set it, it only show a 52pix width grid, I don't know why.
![jsgrid_issue](https://cloud.githubusercontent.com/assets/8425377/13564255/3d8136c0-e483-11e5-8ff8-c5f8645fe320.jpg)

Thanks in advance.

**Comment by geloh** [comment]
Hi. I think you should call the jsgrid refresh method when selecting the tab.

$( "#tabs" ).tabs({
  activate: function( event, ui ) {
  $('#jsgrid').jsGrid('refresh');
}
});

**Comment by tabalinas** [comment]
yes, this should help.
check out another similar issue https://github.com/tabalinas/jsgrid/issues/123

**Comment by jufei** [comment]
I have added the refresh method, it does not work.

**Comment by jufei** [comment]
It works. Thanks.
