### ISSUE TITLE
How can I adjust the width and height for the jsgrid when work with jquery UI tabs?

### ISSUE THREAD

**Issue by jufei** [tabalinas/jsgrid#218]
hi:
   I used several jsgrids with jquery UI tabs, I wish the grid to fullfill the area of tabs;

My tabs defination like this:
`<div id="tabs" style="overflow-x:auto; width:100%; height: 100%">
  <ul id='uls'>
    <li><a href="#database_grid">database</a></li>
    <li><a href="#painfo_grid">PA Info</a></li>
    <li><a href="#rfswitch_grid">General RF Switch</a></li>
    <li><a href="#rf_solution_grid">Special RF Switch Solution Defination</a></li>
    <li><a href="#spmode_grid">Special RF Config mode</a></li>
  </ul>

    <div id="database_grid"></div>
    <div id="painfo_grid"></div>
    <div id="rfswitch_grid"></div>
    <div id="rf_solution_grid"></div>
    <div id="spmode_grid"></div>
    </div>

`
and for the jsgrid, I used:
            autowidth: true,
            shrinkToFit : false,

but the width and height of the grid seems not fullfill the area, 
![jsgrid](https://cloud.githubusercontent.com/assets/8425377/13589513/59fa592c-e513-11e5-834c-5181b8e647a4.jpg)

Thanks in advance.

**Comment by tabalinas** [comment]
Where did you get these options?

**Comment by tabalinas** [comment]
You need to use `height` and `width` options of the grid. They accept all usual css values. Be aware that since this is just css, no miracle will happen, when you set height 100%, not caring about heights of parents.

**Comment by donnyv** [comment]
For anyone that comes across this. You set width and height like this.
jsGrid("option", "width","600px");
jsGrid("option", "height ","500px");
