### ISSUE TITLE
inline validation not working

### ISSUE THREAD

**Issue by sarita1234** [tabalinas/jsgrid#220]
{name : "service_name", title : "Service Name", type : "text", width : 70 ,align: "center", validate: { message: "Country should be specified", validator: function(value) { alert('hi');return value > 0; } }},

**Comment by tabalinas** [comment]
The config you put here is almost the same as we have in the demo `Validation` http://js-grid.com/demos/. And it's working there just fine.
So whether you provide more information (jsfiddle is also highly appreciated), or we can close the report as invalid.
