### ISSUE TITLE
Fill Select Filter DropDown List with items[] from an Ajax source with PageLoadingStrategy enabled

### ISSUE THREAD

**Issue by Firework83** [tabalinas/jsgrid#222]
Hi, 

I've a hard time to figure out how to fill out the filters of select fields from a external source (AJAX). I need to find a way to be filter results for options that are not necessary displayed in a page but be an option from another. I'm implemented successfully the PageLoadingStrategy along with the sorting done by the DB.

Actually, the examples show a static db.items[] list properties, but my db sources is async. I need to figure out a way to preload the select filter option list before loadData(). Also, I want the list to be loaded only once...

Your help is appreciated.

Thank you,

**Comment by tabalinas** [comment]
You can find how to do it in the jsgrid php sample project https://github.com/tabalinas/jsgrid-php/blob/master/public/js/sample.js
Basically, you request data for selects (use `$.when` if you need several selects with data from db) and on the `done` of ajax request initialize the grid.

**Comment by Firework83** [comment]
Thank you!

**Comment by BlackCentipede** [comment]
I have the same problem as him.

I just want to say, this isn't a solution, the select filter should be able to pull from JSON instead of wrapping the entire JS-Grid with AJAX callbacks. If you have 2 different JSON, you'll end up with AJAX callback that make another Ajax call with yet another Ajax Callback that finally initialize the Grid. It would certainly make JS-Grid a lot more usuable if we can return an ajax call to Select Items property.

**Comment by tabalinas** [comment]
Well having multiple selects with ajax results is not much different from having only one:

```js
var d1 = $.ajax({...});
var d2 = $.ajax({...});

$.when(d1, d2).done(function(result1, result2) {
   // initialize grid
});
```
At least you don't need to do a chain of ajax requests.

But I'll think about making it easier. 
Thank you for the feedback.

**Comment by Firework83** [comment]
Yes, it will be better to have an easier way as BlackCentipede suggets... 
Chaining breaks the load indicators since then...

**Comment by tabalinas** [comment]
@Firework83 I agree that having straightforward way to do it is better.
But could you provide more details about the issue: *"Chaining breaks the load indicators"*
First do we really need chaining? `$.when` should do the job, no?
And what exactly happens to load indicator?
