### ISSUE TITLE
Grouping with summery row

### ISSUE THREAD

**Issue by thoriyas** [tabalinas/jsgrid#223]
Does it support grouping ?

**Comment by tabalinas** [comment]
Grouping can be done with nested jsGrids. One main jsGrid with `rowRenderer` or a single column with `itemTemplate` that creates another jsGrid inside.

**Comment by tqmatheson** [comment]
Is there any available example code showing grouping that is achieved using either rowRenderer or itemTemplate?

**Comment by tabalinas** [comment]
Here is very basic example showing the approach http://jsfiddle.net/tabalinas/vc1wm99n/
