### ISSUE TITLE
I am unable to bind dropdownlist in jsgrid

### ISSUE THREAD

**Issue by Itsathere** [tabalinas/jsgrid#228]
I am unable to bind dropdownlist with database. Some times it's working some times not working.Can you explain me the reason

**{ name: "Location", type: "select", items: db.Locations, valueField: "LocationID", textField: "Description", width: 200 },**

in the above code snippet, I think **name is the data-field of dropdownlist**, **valueField is value of dropdownlis **and **textField is text of dropdownlist**. Am i right?.If so, why it's not working.Please explain and **one more thing can we edit on mouse over and update on mouse out in this grid**.

**Comment by CalvinMills** [comment]
are you loading db.locations through an ajax call ? if so your problem is that Ajax calls are asynchronous and as such the data has not been loaded before you try bind it to the drop down list

**Comment by Itsathere** [comment]
db.damages = [];
    db.clients = [];
    $.get("/Test/GetMerchant",
    function (data) {
        debugger;
        db.Locations = data.loc;
        db.damages = data.dam;
    }, "json");

above the code snippet inside db.js

**Comment by tabalinas** [comment]
Looks like @CalvinMills is right. You need to initizalize the grid right in the `done` handler of the ajax request:

```js

$.get("/Test/GetMerchant",
    function (data) {
        db.Locations = data.loc;
        db.damages = data.dam;

        // init grid here
    }, "json");
```

BTW: you can find an example in the js-grid sample project for php https://github.com/tabalinas/jsgrid-php/blob/master/public/js/sample.js
