### ISSUE TITLE
How to set value of Select2 using jquery ajax call

### ISSUE THREAD

**Issue by dhawkKD** [tabalinas/jsgrid#229]
Hi,

I am trying to set the value of my Select2 control on change event of some other control.
The results which needs to be set in Select 2 control is coming like [1,2] and for setting value I have tried below methods but nothing works.
1. $("#select2ID").select2('val', ["1", "2"]);
2. $("#select2ID").select2('val', [1, 2]);
3. $("#select2ID").select2(data,{id:1,text:"abc"},{id:2,text:"bcd"});

Help me in setting the multiple values for Select2 control on the change of any other control.

**Comment by tabalinas** [comment]
How this question is related to js-grid? Maybe you asked a question in the wrong project?

Regarding select2 you can maybe look at this answer on SO: http://stackoverflow.com/questions/19639951/how-do-i-change-selected-value-of-select2-dropdown-with-jqgrid
