### ISSUE TITLE
New row from empty grid

### ISSUE THREAD

**Issue by rcarickhoff** [tabalinas/jsgrid#232]
Clicking the green + to add a new row works great if I initially load the grid with data and there are rows to start.  If I start with no rows, how do I tell the grid about the schema of my data so it can insert the first row when the green + is clicked?  I am using the controller and tried returning a new object with null values for each property.  I just see the trashcan by itself in the middle of the row.   If I click the empty row, I see the green check and red x as if there is something there.  See attached screen shot.

![untitled](https://cloud.githubusercontent.com/assets/12790871/13800144/a7e50c38-eafc-11e5-9fc3-3a6884f2c15f.png)

**Comment by tabalinas** [comment]
It should not matter whether you loaded any data or not. Describe fields (columns) of the grid in the config. The grid should work just fine allowing you to add new data and afterwards you can access these items in `data` option like `$("#jsGrid").jsGrid("option", "data")`
