### ISSUE TITLE
How to click save button automatically after tab button or down arrow click from keyboard

### ISSUE THREAD

**Issue by Itsathere** [tabalinas/jsgrid#234]
I need to save data in editable jsgrid whenever, i will click on any of two button from keyboard which is **tab and down/up arrow**

**Comment by Itsathere** [comment]
I have tried [this](http://jsfiddle.net/QfCpC/1/) but it's not working.

**Comment by tabalinas** [comment]
I guess here is the answer to your question https://github.com/tabalinas/jsgrid/issues/117
