### ISSUE TITLE
Takes too much time to load data 

### ISSUE THREAD

**Issue by Itsathere** [tabalinas/jsgrid#236]
I have 100000+ data, when I bind 20000+ data it shows **server responded with a status of 500 (Internal Server Error)** after 5 minutes **but when data is under 1000 it binds the grid great**. I need it fast without any error.

**Comment by tabalinas** [comment]
I believe, that it's not grid that shows you an error and loads data too slow, it most probably ajax request. Anyway, usually if you work with such a huge amount of data you load data by pages. See `pageLoading` option http://js-grid.com/docs/#pageloading-default-false
