### ISSUE TITLE
Adding a button or link in row, when using rowClick: function

### ISSUE THREAD

**Issue by flyinmryan** [tabalinas/jsgrid#238]
Hello,

I am trying to add a button (or a link) to each one of my rows.  The problem is that I am using a rowClick function that redirects to a URL, and this overrides the button.  Can I disable the row click for certain columns?  I am trying to use jQuery to capture the button click event and only alert something, but it always redirects to the rowClick func, and doesn't execute the jQuery.

Here is the rowClick function.  It works well, but I want to disable it if the button or the row with the button was clicked.
`rowClick: function (args) {`
               `window.location = "/Reservations/Edit/" + args.item.resID;`
` },`

But I also have this jQuery, that doesn't get executed:
`$(".redeemBtn").on("click", function (event) {`
       ` event.preventDefault();`
       ` alert("something");`
`return false;`
` })`

I have tried the following HTML:
`<button class='redeemBtn'>REDEEM</button>`
`<a href='#' class='redeemBtn'>Redeem</a>`

I've looked through the documentation, but can't seem to find anywhere that answers this, if it's possible. 

Thank you for any advice you may have

**Comment by tabalinas** [comment]
I'm not sure why it happens.
See the following example, where the scenario described works fine: http://jsfiddle.net/tabalinas/x4Lnzda7/
If you won't find the issue, modify the fiddle to demonstrate the issue.

**Comment by flyinmryan** [comment]
That did it, I just had to modify the fiddle a little.  Thanks!
