### ISSUE TITLE
Insert data from external source

### ISSUE THREAD

**Issue by soongsta** [tabalinas/jsgrid#241]
Hi There

Is it possible to insert data into the grid using an external source?
I have created a sample here https://jsfiddle.net/soongsta/gyz2mfj1/6/

Cheers

**Comment by tabalinas** [comment]
Yes, what you can do is just define a simple controller:

```js
controller: {
  loadData: function() {
    return clients;
  }
}
```

Here is the updated fiddle: https://jsfiddle.net/tabalinas/psLeja63/
