### ISSUE TITLE
combo box

### ISSUE THREAD

**Issue by ElliotIrwin** [tabalinas/jsgrid#242]
Epic tool but would benefit from a combo box grid field option where you can start typing and it autocompletes by either searching an array of options or make an ajax request to an external server

**Comment by tabalinas** [comment]
Thank you for the feedback.
Not sure it best to build in such a field in the jsGrid directly. Maybe provide sample for custom fields that uses some popular comboboxes like [select2](https://select2.github.io/examples.html). Please, checkout this issue, I think it has a solution: https://github.com/tabalinas/jsgrid/issues/141
