### ISSUE TITLE
how to use date picker in search filters for search a date field?

### ISSUE THREAD

**Issue by pichlou** [tabalinas/jsgrid#244]

**Comment by tabalinas** [comment]
There is an example in the docs showing how to use a date field. It doesn't cover the `filterTemplate` but the idea is similar. You should define a `filterTemplate` that returns one or two datepickers (depending on your filtering use case - range of dates or a particular date) and a `filterValue` method which will return a seleted date or an array of two dates `[dateFrom, dateTo]` for two datepickers. Then you will be able to use these dates in your client-side or server-side (or even hybrid) filtering.
