### ISSUE TITLE
Need help to set maxsize

### ISSUE THREAD

**Issue by matt276** [tabalinas/jsgrid#246]
Hello

First of all many thanks for all this work !

I would like to set a maxsize property for a text field.
(ex : limit to 10 digit)
Is it possible ? Maybe i can use a custom field ?

Thanks for your help

**Comment by tabalinas** [comment]
You have several options:

1) redefine `_createTextBox` method to have the length limited for edit/insert/filter as following:

```js
{
    name: "MyField",
    type: "text",
    _createTextBox: function() {
        var $input = jsGrid.fields.text.prototype._createTextBox.call(this);
        return $input.attr("maxlength", 10);
    }
}
```

2) Redefine `insertTemplate` or `editTemplate` like in the option #1

3) Use built-in validation while it's limiting maybe too late, when value is already entered.

4) Inherit from existing `text` field and redefine templates or `_createTextBox` method, like described in the docs http://js-grid.com/docs/#custom-field

**Comment by matt276** [comment]
Hi

I used option 1, it is perfect for me.

Thanks for your support !

**Comment by tabalinas** [comment]
Nice!
