### ISSUE TITLE
Complex field which combine simple  fields together

### ISSUE THREAD

**Issue by nguyenth** [tabalinas/jsgrid#248]
In some situation, the grid need field combine many things, include select, textbox, datetimepicker for a filed. complex field will help you to do that situation.
![image](https://cloud.githubusercontent.com/assets/904663/14181271/7a2ccb6e-f790-11e5-8995-f4c084e513d3.png)

config with new field:
```js
 $("#jsGrid").jsGrid({
                    width: "100%",
                    height: "400px",
                    inserting: true,
                    editing: true,
                    selecting: true,
                    sorting: true,
                    paging: true,
                    autoload: true,
                    deleteConfirm: "Do you really want to delete the client?",
                    controller: {
                        loadData: getClient,
                        insertItem: insertClient,
                        updateItem: editClient,
                        deleteItem: delClient
                    },
                    fields: [
                        //{ name: "Name", type: "text", width: 150, validate: "required" },
                        {
                            name: "Name",
                            type: "complex",
                            binder: {
                                "First": { type: 'text' },
                                "Last": { type: 'text' }
                            },
                            title: "Card",
                            sorting: false
                        },
                        { name: "Age", type: "number", width: 50 },
                        { name: "Address", type: "text", width: 200 },
                        { name: "Country", type: "select2", items: countries, valueField: "Id", textField: "Name" },
                        { name: "Married", type: "checkbox", title: "Is Married", sorting: false },
                        {
                            name: "Card",
                            type: "complex",
                            displayLayout: "card",
                            filterValue: "Id",
                            binder: {
                                "Id": { type: 'text' },
                                "IssuePalce": { type: 'select', items: cities, valueField: "Id", textField: "Name" },
                            },
                            title: "Card",
                            sorting: true
                        },
                        { type: "control" }
                    ]
            });
```

**Comment by nguyenth** [comment]
(function (jsGrid, $, undefined) {

	var Field = jsGrid.Field;

	function ComplexField(config) {
		this.binder = {};
		this.controls = {};
		this.displayLayout = "";
		this.filterValue = "";
		this.editLayout = "";

		for (var prop in config.binder) {
			var childConfig = config.binder[prop];
			if (!childConfig)
				return;
			childConfig = $.extend(childConfig, { name: prop });
			var propType = childConfig.type || "text";
			this.controls[prop] = new jsGrid.fields[propType](childConfig);
		}

		Field.call(this, config);
	}

	ComplexField.prototype = new Field({

		autosearch: true,
		align: "left",
		css: "complex-field",
		sorter: function (obj1, obj2) {
			var defaultProp = this._getDedaultField();
			if (obj1[defaultProp] > obj2[defaultProp]) return -1;
			if (obj1[defaultProp] === obj2[defaultProp]) return 0;
			if (obj1[defaultProp] < obj2[defaultProp]) return 1;
		},
		itemTemplate: function (value, item) {
			var binder = this.binder,
				controls = this.controls,
				template = this.displayLayout,
				objRet = {};
			for (var prop in binder) {
				var control = controls[prop] || null;
				if (control) {
					objRet[prop] = control.itemTemplate(value[prop], value);
				}
			}
			return this._formatTemplate(objRet, template);
		},
		filterTemplate: function () {
			if (!this.filtering)
				return "";

			var grid = this._grid,
                $result = this.filterControl = this._getFilterControl().insertTemplate();
			if (this.autosearch) {
				$result.on("change", function (e) {
					grid.search();
				});
			}
			return $result;
		},
		insertTemplate: function () {
			if (!this.inserting)
				return "";
			return this.insertControl = this._createComplexInsertControl();
		},
		editTemplate: function (value) {
			if (!this.editing)
				return this.itemTemplate(value);
			var $result = this.editControl = this._createComplexEditControl(value);
			return $result;
		},
		filterValue: function () {
			return this.filterControl.filterValue();
		},
		insertValue: function () {
			var binder = this.binder,
				objVal = {};
			for (var prop in binder) {
				if (childControl = this._getControl(prop)) {
					objVal[prop] = childControl.insertValue();
				}
			}
			return objVal;
		},
		editValue: function () {
			var binder = this.binder,
				objVal = {};
			for (var prop in binder) {
				if (childControl = this._getControl(prop)) {
					objVal[prop] = childControl.editValue();
				}
			}
			return objVal;
		},
		_formatTemplate: function (objVal, template) {
			if (template.length == 0) {
				var arrs = [];
				for (var prop in objVal) {
					arrs.push(objVal[prop]);
				}
				return arrs.join("<br />");
			}
			var templateBody = $("#" + template).html();
			return $.tmpl(templateBody, objVal).prop("outerHTML");
		},
		_getDedaultField: function () {
			var filterProp = this.filterValue || ""
			binder = this.binder;
			if (filterProp.length == 0) {
				for (var prop in binder) {
					filterProp = prop;
					break;
				}
			}
			return filterProp;
		},
		_getFilterControl: function () {
			return this._getControl(this._getDedaultField());
		},
		_getControl: function (prop) {
			var controls = this.controls || {};
			return controls[prop];
		},
		_wrapEditTemplate: function (templateName) {
			var binder = this.binder;
			if (templateName.length == 0) {
				var template = $("<ul></ul>");
				for (var prop in binder) {
					var li = $("<li></li>");
					li.attr("jg", prop);
					template.append(li);
				}
				return template;
			}

			var templateBody = $("#" + templateName).html();
				model = {};
			for (var prop in binder) {
				model[prop] = prop;
			}
			return $.tmpl(templateBody, model);
		},
		_createComplexInsertControl: function () {
			var itemControl =  this._wrapEditTemplate(this.editLayout);
			var binder = this.binder,
				template = this.editLayout;
			for (var prop in binder) {
				if (childControl = this._getControl(prop)) {
					var placeholder = $("*[jg=" + prop + "]", itemControl).first();
					if (placeholder.length > 0) {
						placeholder.append(childControl.insertTemplate());
					}
				}
			}
			return itemControl;
		},
		_createComplexEditControl: function (value) {
			var itemControl = this._wrapEditTemplate(this.editLayout);
			var binder = this.binder,
				template = this.editLayout;
			for (var prop in binder) {
				if (childControl = this._getControl(prop)) {
					var placeholder = $("*[jg=" + prop + "]",itemControl).first();
					if (placeholder.length > 0) {
						placeholder.append(childControl.editTemplate(value[prop]));
					}
				}
			}
			return itemControl;
		}
	});

	jsGrid.fields.complex = jsGrid.ComplexField = ComplexField;

}(jsGrid, jQuery));

**Comment by tabalinas** [comment]
Not sure it's needed to be as a built-in now. Anyway, thank you for sharing your scenarios and suggestions.
