### ISSUE TITLE
getting data out of the grid

### ISSUE THREAD

**Issue by ashhorner** [tabalinas/jsgrid#250]
Hi,

sorry once again if this question is covered in the documentation or issues section, but I have been unable to find it.

Loading data in to the grid is fine, how do I get the data out?  

I have tried:

var products=$('#jsGrid').data;

...but it doesn't work.  

The reason I need this is because the grid is used to select items and edit various fields (e.g. quantity), so I need to extract the data.

Thanks,

Ashley

**Comment by tabalinas** [comment]
There is an option [`data`](http://js-grid.com/docs/#data) that allows to get/set items of the grid:

```js
var items = $("jsGrid").jsGrid("option", "data");
```
