### ISSUE TITLE
Cannot disable column headers and scrollbar

### ISSUE THREAD

**Issue by eliasuardi** [tabalinas/jsgrid#252]
Hello.
I've been trying to create a table without displaying the column headers.
I tried hiding the jsgrid-grid-header div but the table format gets messed up.
I've also tried hiding the scrollbar but couldn't find a solution.
Is there a way to solve this?

Thanks.

**Comment by tabalinas** [comment]
Hi,

you can hide header with `heading: false` [option](http://js-grid.com/docs/#heading-default-true)
to let the grid grow without scrollbar just remove `height` option.

**Comment by eliasuardi** [comment]
Heading: false works but removing the height parameter doesn't eliminate the scrollbar.

**Comment by tabalinas** [comment]
You can redefine with css the `overflow-y` property of the grid body.
