### ISSUE TITLE
LoadData does not work

### ISSUE THREAD

**Issue by Utach** [tabalinas/jsgrid#253]
Hi, I am new in jquery... I have been struggled to deal with loadData in jsgrid.... 
I am using Webform instead of MVC...

Here my code on aspx

```js
$("#jsGrid").jsGrid({
        height: "auto",
        width: "100%",
        sorting: true,
        paging: false,
        autoload: true,
        controller: {
            loadData: function (filter) {
                return $.ajax({
                    type: "GET",
                    contentType: "application/json; charset=utf-8",
                    url: "JsGridTesting.aspx/GetDataJSON",
                    dataType: "json"
                });
            }
        },
        fields: [
            { name: "Name", type: "text" },
            { name: "Description", type: "text", width: 150 }
        ]
    });
```

and here is my code on server side
```
<System.Web.Services.WebMethod()> _
   <ScriptMethod(ResponseFormat:=ResponseFormat.Json, UseHttpGet:=True)>
    Public Shared Function GetDataJSON() As String

        Dim obj1 As New Student() With {.Name = "Mick Jagger", .Description = "bar"}
        Dim obj2 As New Student() With {.Name = "Johnny Storm", .Description = "bar"}
        Dim obj3 As New Student() With {.Name = "Richard Hatch", .Description = "bar"}
        Dim obj4 As New Student() With {.Name = "Kelly Slater", .Description = "bar"}

        Dim objStudentList As New List(Of Student)() From {obj1, obj2, obj3, obj4}
        Dim objJSSerializer As New System.Web.Script.Serialization.JavaScriptSerializer()
        Dim strJSON = objJSSerializer.Serialize(objStudentList)

        Return strJSON
   End Function
```

I have checked that my GetDataJSON has return JSON data correctly but the grid cannot bind the data properly...... Please help me....

**Comment by geloh** [comment]
Hey! I think loadData expects a promise. Something similar to this should work.
```javascript
$("#jsGrid").jsGrid({
height: "auto",
width: "100%",
sorting: true,
paging: false,
autoload: true,
controller: {
loadData: function (filter) {
var data = $.Deferred();
$.ajax({
  type: "GET",
  contentType: "application/json; charset=utf-8",
  url: "JsGridTesting.aspx/GetDataJSON",
  dataType: "json"
}).done(function(response){
  data.resolve(response);
});
return data.promise();
}
},
fields: [
{ name: "Name", type: "text" },
{ name: "Description", type: "text", width: 150 }
]
});

```

**Comment by tabalinas** [comment]
In fact there should not be difference between returning $.ajax and returning a promise. But for debug purposes I would suggest you using @geloh's example. Put a `debugger;` in the `done` of ajax and ensure you get in it. Also ensure that `response` has valid format. As I remember (not sure though) the response have a field `value` (or something like that) when you use Page methods. In this case you indeed need to resolve promise with array of items.

**Comment by Utach** [comment]
Hi Geloh and Tabalinas, 
I use your examples, but it's still not work.... I put a debugger too, but nothing happen.. 
Could you please give more example of getting data from webservice, I want to see the server code returning json data. Please help

**Comment by tabalinas** [comment]
Ensure your ajax request works separately:

```js
$.ajax({
       type: "GET",
       contentType: "application/json",
       url: "JsGridTesting.aspx/GetDataJSON"
       }).done(function(response){
         console.log(response);
     });
```

Be sure that expected result is printed in the console.
Just in case: you need to open Chrome DevTools to see the console.

**Comment by Utach** [comment]
This is the result...
the "JsGridTesting.aspx/GetDataJSON" returns the correct object, right ?
But, on the grid, there is still no data... 

![untitled](https://cloud.githubusercontent.com/assets/18332882/14716120/c4a64d24-0815-11e6-9d7d-597445453000.png)

**Comment by tabalinas** [comment]
No, as you can see your response is not an array of objects, but an object with a field `d` where all data is just a string that you should parse. So in this case it should be at least `data.resolve(response.d)` or even `data.resolve(JSON.parse(response.d))`.

**Comment by Utach** [comment]
Woow, it perfectly works... you are great 
Many thanks @tabalinas

**Comment by tabalinas** [comment]
You are welcome!

**Comment by KarlaGonzalez** [comment]
It works for me too, thanks @tabalinas and @Utach !!

**Comment by vohoangnhut** [comment]
Wow. It's really helpful. thank @tabalinas

**Comment by JTC1701** [comment]
@tabalinas -- How should the JSON array be structured?  I have tried everything that has been suggested and still cannot get anything to display when using the loadData controller.

Here is my script:
loadData: function (filter) {
                        return $.ajax({
                            method: "GET",
                            url: "/api/sbom",
                            contentType: "application/json",
                            dataType: "json",
                            data: filter
                    }).done(function(response){
                        console.log(response);
                        });
                    },

And here is the result as it shows in the Console:
![image](https://cloud.githubusercontent.com/assets/24941073/21688289/3c7ee942-d33a-11e6-9281-8029d58d95d7.png)

**Comment by RevealedFrom** [comment]
I just wanted to make sure I get the syntax correct, so I hardcoded some data as follows:

      controller: {
         loadData: function(filter) { return [{"name": "abc", "description":"test"}]; },
         insertItem: $.noop, 
         updateItem: $.noop,
         deleteItem: $.noop
        },
 
The above doesn't work for me, although the exact same data when assigned to the `data` option works fine.

What have I done wrong?

**Comment by tabalinas** [comment]
@JTC1701, My guess is the grid loaded just fine, but it collapsed because of `height: "100%"`. Try to set fixed in pixels value to be sure.

**Comment by Venkatramanaryams** [comment]
hello sir tabalinas iam using jsgrid from last one week.please help about json object fetch into controller.Iam using JAVA so i used jsgrid like.grid.jsp file.Please help me

**Comment by Venkatramanaryams** [comment]
@Utach  can u send me that  jsgrid code

**Comment by Venkatramanaryams** [comment]
@tabalinas  and @Utach  hello sir tabalinas iam using jsgrid from last one week.please help about json object fetch into controller.Iam using JAVA so i used jsgrid like.grid.jsp file.Please help me

**Comment by NuclearSlug** [comment]
I encountered this identical problem when using ASP.NET WebForms.  After spending way too much time tinkering around with it, I discovered that if you're using a WebMethod in your ajax call instead of a generic handler, you will need to use `type: "post"` 

Here's my working solution to this:

```
        controller: {
            loadData: function (filter) {
                var data = $.Deferred();
                $.ajax({
                    type: "POST",
                    contentType: "application/json; charset=utf-8",
                    url: url,
                    dataType: "json"
                }).done(function (response) {
                    data.resolve(JSON.parse(response.d));
                });
                return data.promise();
            }
        },
```

**Comment by varathaa** [comment]
Hi, 
      I'm new to JS Grid.  I have ajax response with array of js objects.
I'm able to  make a promise successfully and return data.

But grid data  is not loading.

Please look in to this.

JS


  $("#jsGrid").jsGrid({       
        width: "100%",
        height: "auto",
        
        autoload: true,
        paging: true,
       controller: {
    	  loadData: function (filter) {
    		 var dfr = $.Deferred(); 
  			var hActionType ="F";
    			var hToken		= document.frmCapacityplan.hToken.value ;
    			var sUrl = url;
    			
      	    	 $.ajax({
      	    	 type: "GET",
      	         contentType: "application/json",
      	    	 url: sUrl+paramValue
             }).done(function (response) {
      	    		var responseData = {data:response};
      	    		console.log(responseData.data);
      	    		dfr.resolve(responseData.data);
                });
                return dfr.promise();
            }
         }, 
         
         fields: [
         	  
         	  { name: "ResourceID", width: 30 },
         	  { name: "Year", width: 30 },
         	  { name: "Month",width: 30 },
         	  { name: "ProjectId",width: 50 },
               { name: "Hours", width: 50 },
               { name: "Comments", width: 200 },                  
               { name: "ActiveFlag",width:20 }
           ] 
      
![ajax response](https://user-images.githubusercontent.com/43828042/46436479-e2a5c700-c726-11e8-8bbc-034e676b338f.png)

    });

});

**Comment by bmtsoykan** [comment]
@tabalinas  Hi,
I also faced similar issue with @JTC1701 .
In my console, the result array appered. But I couldn't display it. Could you please help me?
![Capture](https://user-images.githubusercontent.com/64690984/80865238-ac2c8700-8c90-11ea-8c6f-fe3084385d53.PNG)
