### ISSUE TITLE
Where to apply custom filter on pagination?

### ISSUE THREAD

**Issue by overflowz** [tabalinas/jsgrid#254]
Hello, I'm trying to apply new filter to a grid while doing pagination.
Situation is like this:
1) Modal dialog appears where are filter fields.
2) User fills these fields.
3) After clicking the search button which is also located at modal dialog form, I catch event and do the following:

```js
var onGridSearchFilterForm = function () {
    var formData = $('#gridSearchFilterForm').serialize();
    var grid = $('#itemsGrid').data('JSGrid');
    
    formData += ("&pageSize=" + grid.pageSize);
    formData += ("&pageIndex=" + grid.pageIndex);

    grid.search(formData).done(function (result) {
        if (result != null && result.success) {
            $('#gridSearchFilterModal').modal('hide');
        }
    });
};
```

But, of course I understand that this is just a 'temporary' filter. How can I apply this filter to grid so when user clicks {next page} it will display information provided by this filter?

Thanks!

**Comment by tabalinas** [comment]
Each time grid requests the data (including you open a page when `pageLoading: true`) the `controller.loadData` method is called with the `filter` as a parameter.

So you can provide your custom filter parameters just inside the `loadData` function as follows:

```js
  $("#jsGrid").jsGrid({
    ...,
    controller: {
      loadData: function(filter) {
         return $.ajax({
            data: {
               myOutOfGridFilterField: $("#externalField").val() // or get the value from anywhere else
               pageSize: filter.pageSize,
               pageIndex: filter.pageIndex,
               myField: filter.myField
            },
            ...
         });
      }
    }
  });
```
