### ISSUE TITLE
updateItem error

### ISSUE THREAD

**Issue by ashhorner** [tabalinas/jsgrid#257]
Hi,

I am trying to edit items in the grid and am using the code from Data Maniplation demo.  When I add an item to the grid then the code works fine, but when I try to update an item in the grid I get an error saying

"Uncaught TypeError: Cannot read property 'category' of undefined.".  I've checked and "item" is defined and "item.category" has a value.

The code is:
```
`       item=new Item(category, product, quantity, unit, price);          
        $('#jsGrid').jsGrid(isAdd=="true" ? "insertItem" : "updateItem", item);`

``` 

Thanks,

Ashley

**Comment by tabalinas** [comment]
The info provided is not enough to understand and help with the issue.
Maybe you could modify this fiddle http://jsfiddle.net/tabalinas/kj6d6tw5/ so we see the issue?

**Comment by ashhorner** [comment]
as always - thank you...I took elements of the code you shared and got things working.  If I'm honest, I don't know why it wasn't working as your technique for achieving certain elements is different to what I had done.

Ashley

**Comment by tabalinas** [comment]
You are welcome!
Glad you figured it out!
