### ISSUE TITLE
Filtering now working

### ISSUE THREAD

**Issue by zopyx** [tabalinas/jsgrid#258]
I've integrated jsgrid 1.4.1 into the Plone CMS with filtering enabled. However the filtering does not work (keypress events are possibly eaten or ignored somewhere, somehow)....how can I track this done.

See http://public.zopyx.com/filtering.mp4

**Comment by tabalinas** [comment]
Are you sure you've implemented actual data filtering on client or server side?

**Comment by zopyx** [comment]
This is my configuration:

```
            $('#table').jsGrid({
                width: "100%",
                height: "600px",
                autoload: true,
                sorting: true,
                paging: PAGING,
                filtering: true,
                controller: {
                    loadData: get_data
                },

                fields: [
                    { name: "title", title: "Name", type: "text", width: 200,  itemTemplate: title_renderer},
                    { name: "type", title: "Type", type: "text", width: 75, css: 'field-type'},
                    { name: "size", title: "Size", type: "text", width: 50, css: 'field-size', filtering: false},
                    { name: "modified", title: "Last modified", type: "text", css: 'field-modified', filtering: false },
                    { name: "st_mode_text", title: "Permissions", type: "text", sorting: false, size: 50 , filtering: false},
                    { name: "actions", type: "text", title: "Actions", sorting: false, itemTemplate: action_renderer, filtering: false}
                ]
            });

        });
```


The "basic scenario" demo does not show anything special that would be different from my code.
Is there anything missing in the documentation? Setting autosearch: true does not make a difference.

**Comment by zopyx** [comment]
I checked that the event handler for keypress works for the enter key. The grid.search()  gets called (however with 'filter' being undefined). From reading the docs: default filtering should work out of the box without custom filtering code, correct?

**Comment by tabalinas** [comment]
Nope, the data filtering logic is on the developer shoulders for the sake of flexibility and simplicity. Please see the following ticket: https://github.com/tabalinas/jsgrid/issues/32.
Maybe it should be stated clearer in the docs.

**Comment by dewelloper** [comment]
loadData: function (filter) {
                            criteria = filter;
                            var data = $.Deferred();
                            $.ajax({
                                type: "GET",
                                contentType: "application/json; charset=utf-8",
                                url: "/fapplications",
                                dataType: "json"
                                }).done(function(response){
                                    var res = [];
                                    if(criteria.Name !== "")
                                    {
                                        response.forEach(function(element) {
                                            if(element.Name.indexOf(criteria.Name) > -1){
                                                res.push(element);
                                                response = res;
                                            }
                                        }, this);
                                    }
                                    else res = response;
                                    if(criteria.Title !== "")
                                    {
                                        res= [];
                                        response.forEach(function(element) {
                                            if(element.Title.indexOf(criteria.Title) > -1)
                                                res.push(element);
                                        }, this);
                                    }
                                    else res = response;                                    

                                    data.resolve(res);
                                });
                            return data.promise();
                        },

**Comment by sharepointmike** [comment]
My Json result does not let me do "IndexOf". Any solution in my case?
