### ISSUE TITLE
The data boxes are misaligned

### ISSUE THREAD

**Issue by drevix** [tabalinas/jsgrid#261]
Good day,

When painting the Grid, the data shows misaligned What could be happening?

Thank you very much
![captura](https://cloud.githubusercontent.com/assets/9873689/14711064/8b7f00d6-079d-11e6-9f61-3eb3748f9875.PNG)

**Comment by tabalinas** [comment]
Try to call `$("#jsGrid").jsGrid("refresh")` to have column width refreshed.
One reason could be that you render the grid when its container is hidden.

**Comment by velis74** [comment]
I found that refresh didn't do the job, so I call `render` instead. It would be really nice if this could be moved into a function that ONLY refreshed the column dimensions.

**Comment by tabalinas** [comment]
No, in fact `refresh` method calls internal method `_refreshSizes` that does update widths. So it should help. If it doesn't work in your case, then there is something fishy in this concrete scenario.

**Comment by velis74** [comment]
Ah, OK, thanks for the info. I just started using the grid at the time, so I might have missed something.
