### ISSUE TITLE
Values not displayed in select on loading

### ISSUE THREAD

**Issue by viranianish** [tabalinas/jsgrid#262]
Hi, I have used jsGrid for my project and when I use the select type, the values of select are not displayed in the table but are available when we select the row for editing, and the filter also works. I don't know what the problem is.

Please help
![afterediting](https://cloud.githubusercontent.com/assets/13729917/14733190/d50340a0-087e-11e6-86fe-a7a0b5d13647.png)

![onloading](https://cloud.githubusercontent.com/assets/13729917/14733191/d5086bf2-087e-11e6-8233-f0a280362d7f.png)

**Comment by tabalinas** [comment]
Could you please provide your `select` field configuration?

**Comment by viranianish** [comment]
//initialize the db variable with filter settings and update and delete settings
var db = {
    loadData: function(filter) {
        return $.grep(this.items, function(item) {
            return (!filter.company_name || item.company_name.toUpperCase().indexOf(filter.company_name.toUpperCase()) > -1)
                && (!filter.sales_action || item.sales_action.indexOf(filter.sales_action) > -1)
                && (!filter.activity || item.activity.toUpperCase().indexOf(filter.activity.toUpperCase()) > -1)
                && (!filter.first_name || item.first_name.toUpperCase().indexOf(filter.first_name.toUpperCase()) > -1)
                && (!filter.last_name || item.last_name.toUpperCase().indexOf(filter.last_name.toUpperCase()) > -1)
                && (!filter.email_address || item.email_address.toUpperCase().indexOf(filter.email_address.toUpperCase()) > -1)
                && (!filter.website || item.website.toUpperCase().indexOf(filter.website.toUpperCase()) > -1)
                && (!filter.job_title || item.job_title.toUpperCase().indexOf(filter.job_title.toUpperCase()) > -1)
                && (!filter.business_phone || item.business_phone.toUpperCase().indexOf(filter.business_phone.toUpperCase()) > -1)
                && (!filter.home_phone || item.home_phone.toUpperCase().indexOf(filter.home_phone.toUpperCase()) > -1)
                && (!filter.mobile_phone || item.mobile_phone.toUpperCase().indexOf(filter.mobile_phone.toUpperCase()) > -1)
                && (!filter.fax_number || item.fax_number.toUpperCase().indexOf(filter.fax_number.toUpperCase()) > -1)
                && (!filter.address || item.address.toUpperCase().indexOf(filter.address.toUpperCase()) > -1)
                && (!filter.city_name || item.city_name.toUpperCase().indexOf(filter.city_name.toUpperCase()) > -1)
                && (!filter.state_name || item.state_name.toUpperCase().indexOf(filter.state_name.toUpperCase()) > -1)
                && (!filter.country_name || item.country_name.toUpperCase().indexOf(filter.country_name.toUpperCase()) > -1)
                && (!filter.postal_code || item.postal_code.toUpperCase().indexOf(filter.postal_code.toUpperCase()) > -1)
                && (!filter.memo || item.memo.toUpperCase().indexOf(filter.memo.toUpperCase()) > -1)
                && (!filter.login_username || item.login_username.toUpperCase().indexOf(filter.login_username.toUpperCase()) > -1)
                && (!filter.login_password || item.login_password.toUpperCase().indexOf(filter.login_password.toUpperCase()) > -1)
                && (filter.user_active === undefined || item.user_active === filter.user_active)
                && (!filter.agency_start_date || item.agency_start_date.toUpperCase().indexOf(filter.agency_start_date.toUpperCase()) > -1)
                && (!filter.agency_start_date || item.agency_start_date.toUpperCase().indexOf(filter.agency_start_date.toUpperCase()) > -1);
        });
    },
   
    updateItem: function(updatingUser) {
        //var updatingItem = $.parseJSON(updatingItem);        
        var userData = {"action":"updateUser","user_id":updatingUser['user_id'],"company_name":updatingUser['company_name'],"sales_action":updatingUser['sales_action'],"activity":updatingUser['activity'],"first_name":updatingUser['first_name'],"last_name":updatingUser['last_name'],"email_address":updatingUser['email_address'],"website":updatingUser['website'],"job_title":updatingUser['job_title'],"business_phone":updatingUser['business_phone'],"home_phone":updatingUser['home_phone'],"mobile_phone":updatingUser['mobile_phone'],"fax_number":updatingUser['fax_number'],"address":updatingUser['address'],"postal_code":updatingUser['postal_code'],"memo":updatingUser['memo'],"login_password":updatingUser['login_password']};        
        //make an ajax call to edit the specified row
        $.ajax({
            url: "Action/loadUsers.php",
            data: userData,
            type: "post",
            success: function(response){
                var response = $.parseJSON(response);                
                if(response[0] == 1){                    
                    alert("User updated succesfully!");                    
                    //return the new item if updation was succesful
                    return response[1];
                }                
                else if(response[0] == 0){                    
                    alert("User updation failed! Please try again later");                    
                    //return the old item if updation was succesful
//                    return response[1];
                }
            }
        });
    },

    deleteItem: function(deletingUser) {
        var itemIndex = $.inArray(deletingUser, this.items);
        //make an ajax call to delete the item
        var userData = {"action":"deleteUser","user_id":deletingUser['user_id']};
        $.ajax({
            url: "Action/loadUsers.php",
            data: userData,
            type: "post",
            success: function(response){
                if(response == 1){
                    //do nothing
                    //alert("User Deleted successfully!");
                    //this.items.splice(itemIndex, 1);                    
                }                
                else{                                       
                    alert("User Deletion Failed! Please try again later!");                   
                }
            }
        });        
    }

};

window.db = db;
var user = "";
if(window.location.href.indexOf("admin_manage_distributors.php")){
    user = "Distributors";
}
var userData = {action:"loadAllUsers",user:user};
//load the items from the db using ajax call
$.ajax({
    url: "Action/loadUsers.php",
    data: userData,
    type: "post",
    beforeSend: function()
    {
        ajaxindicatorstart('Loading.... Please wait..');
    },
    complete: function()
    {
        ajaxindicatorstop();
    },
    success: function(response){
        var data = [
            {Name:"",Id: 0},
            {Name:"Sales Office",Id: 1},
            {Name:"Agent",Id: 2},
            {Name:"Dealer",Id: 3}
        ];
        var sales_action_json = JSON.parse(JSON.stringify(data));
        db.items = $.parseJSON(response);                  
        $(function() {
            $("#jsGrid").jsGrid({
                height: "600",
                width: "100%",

                filtering: true,
                editing: true,
                sorting: true,
                paging: false,
                autoload: true,

                pageSize: 7,
                pageButtonCount: 5,
                
                deleteConfirm: "Do you really want to delete this user?",

                controller: db,

                fields: [               
                    {
                        headerTemplate: function() {
                            return $("<button>").attr("type", "button").text("Delete")
                                    .on("click", function () {
                                        deleteSelectedItems();
                                    });
                        },
                        itemTemplate: function(_, item) {
                            return $("<input>").attr("type", "checkbox")
                                    .on("change", function () {
                                        $(this).is(":checked") ? selectItem(item) : unselectItem(item);
                                    });
                        },
                        align: "center",
                        width: 100,
                        sorting: false
                    },
                    { name: "No", type: "number", width:50, editing: false },
                    { name: "company_name", type: "text", width:180, validate: "required"},
                    { name: "sales_action", type: "select", items: sales_action_json, valueField: "Id", textField: "Name", width: 200,valueType: "number" },
                    { name: "activity", type: "text", width: 180, validate: "required" },                                
                    { name: "first_name", type: "text", width: 180, validate: "required" },
                    { name: "last_name", type: "text", width: 180, validate: "required" },
                    { name: "email_address", type: "text", width: 180, validate: "required" },
                    { name: "website", type: "text", width: 180, validate: "required" },
                    { name: "job_title", type: "text", width: 100, validate: "required" },
                    { name: "business_phone", type: "text", width: 180, validate: "required" },
                    { name: "home_phone", type: "text", width: 180, validate: "required" },
                    { name: "mobile_phone", type: "text", width: 180, validate: "required" },
                    { name: "fax_number", type: "text", width: 180, validate: "required" },
                    { name: "address", type: "text", width: 250, validate: "required" },
                    { name: "country_name", type: "text", width: 200, editing:false },
                    { name: "state_name", type: "text", width: 200, editing:false },                    
                    { name: "city", type: "text", width: 200, validate: "required"},                    
                    { name: "postal_code", type: "text", width: 200, validate: "required" },
                    { name: "memo", type: "text", width: 300, validate: "required" },
                    { name: "login_username", type: "text", width: 200, editing: false },
                    { name: "login_password", type: "text", width: 200, validate: "required" },
                    { name: "user_active", type: "checkbox", width: 200, editing: true },
                    { name: "agency_start_date", type: "text", width: 200, validate: "required" },
                    { name: "agency_end_date", type: "text", width: 200, validate: "required" },
                    { type: "control",width:100 }
                ]
            });

            var selectedItems = [];
 
            var selectItem = function(item) {
                selectedItems.push(item);
            };

            var unselectItem = function(item) {
                selectedItems = $.grep(selectedItems, function(i) {
                    return i !== item;
                });
            };

            var deleteSelectedItems = function() {
                if(!selectedItems.length || !confirm("Are you sure you want to delete these items?"))
                    return;

                var $grid = $("#jsGrid");

                $.each(selectedItems, function(_, item) {
                    $grid.jsGrid("deleteItem", item);
                });

                selectedItems = [];
            };
        });
    }
});
function ajaxindicatorstart(text)
{
    //alert("Start");
    if (jQuery('body').find('#resultLoading').attr('id') != 'resultLoading') {
        //alert("if");
        jQuery('body').append('<div id="resultLoading" style="display:none"><div><img src="../images/ajax-loader.gif"><div>' + text + '</div></div><div class="bg"></div></div>');
    }

    jQuery('#resultLoading').css({
        'width': '100%',
        'height': '100%',
        'position': 'fixed',
        'z-index': '10000000',
        'top': '0',
        'left': '0',
        'right': '0',
        'bottom': '0',
        'margin': 'auto'
    });

    jQuery('#resultLoading .bg').css({
        'background': '#000000',
        'opacity': '0.7',
        'width': '100%',
        'height': '100%',
        'position': 'absolute',
        'top': '0'
    });

    jQuery('#resultLoading>div:first').css({
        'width': '250px',
        'height': '75px',
        'text-align': 'center',
        'position': 'fixed',
        'top': '0',
        'left': '0',
        'right': '0',
        'bottom': '0',
        'margin': 'auto',
        'font-size': '16px',
        'z-index': '10',
        'color': '#ffffff'

    });

    jQuery('#resultLoading .bg').height('100%');
    jQuery('#resultLoading').fadeIn(300);
    jQuery('body').css('cursor', 'wait');
}

function ajaxindicatorstop()
{
    jQuery('#resultLoading .bg').height('100%');
    jQuery('#resultLoading').fadeOut(300);
    jQuery('body').css('cursor', 'default');
}

**Comment by viranianish** [comment]
Sorry I pasted the whole file. Here's the code for conf..

$.ajax({
    url: "Action/loadUsers.php",
    data: userData,
    type: "post",
    beforeSend: function()
    {
        ajaxindicatorstart('Loading.... Please wait..');
    },
    complete: function()
    {
        ajaxindicatorstop();
    },
    success: function(response){
        var data = [
            {Name:"",Id: 0},
            {Name:"Sales Office",Id: 1},
            {Name:"Agent",Id: 2},
            {Name:"Dealer",Id: 3}
        ];
        db.sales_action_json = JSON.parse(JSON.stringify(data));
        db.items = $.parseJSON(response);                  
        $(function() {
            $("#jsGrid").jsGrid({
                height: "600",
                width: "100%",

                filtering: true,
                editing: true,
                sorting: true,
                paging: false,
                autoload: true,

                pageSize: 7,
                pageButtonCount: 5,
                
                deleteConfirm: "Do you really want to delete this user?",

                controller: db,

                fields: [               
                    {
                        headerTemplate: function() {
                            return $("<button>").attr("type", "button").text("Delete")
                                    .on("click", function () {
                                        deleteSelectedItems();
                                    });
                        },
                        itemTemplate: function(_, item) {
                            return $("<input>").attr("type", "checkbox")
                                    .on("change", function () {
                                        $(this).is(":checked") ? selectItem(item) : unselectItem(item);
                                    });
                        },
                        align: "center",
                        width: 100,
                        sorting: false
                    },
                    { name: "No", type: "number", width:50, editing: false },
                    { name: "company_name", type: "text", width:180, validate: "required"},
                    { name: "sales_action", type: "select", items: db.sales_action_json, valueField: "Id", textField: "Name", width: 200,valueType: "number" },
                    { name: "activity", type: "text", width: 180, validate: "required" },                                
                    { name: "first_name", type: "text", width: 180, validate: "required" },
                    { name: "last_name", type: "text", width: 180, validate: "required" },
                    { name: "email_address", type: "text", width: 180, validate: "required" },
                    { name: "website", type: "text", width: 180, validate: "required" },
                    { name: "job_title", type: "text", width: 100, validate: "required" },
                    { name: "business_phone", type: "text", width: 180, validate: "required" },
                    { name: "home_phone", type: "text", width: 180, validate: "required" },
                    { name: "mobile_phone", type: "text", width: 180, validate: "required" },
                    { name: "fax_number", type: "text", width: 180, validate: "required" },
                    { name: "address", type: "text", width: 250, validate: "required" },
                    { name: "country_name", type: "text", width: 200, editing:false },
                    { name: "state_name", type: "text", width: 200, editing:false },                    
                    { name: "city", type: "text", width: 200, validate: "required"},                    
                    { name: "postal_code", type: "text", width: 200, validate: "required" },
                    { name: "memo", type: "text", width: 300, validate: "required" },
                    { name: "login_username", type: "text", width: 200, editing: false },
                    { name: "login_password", type: "text", width: 200, validate: "required" },
                    { name: "user_active", type: "checkbox", width: 200, editing: true },
                    { name: "agency_start_date", type: "text", width: 200, validate: "required" },
                    { name: "agency_end_date", type: "text", width: 200, validate: "required" },
                    { type: "control",width:100 }
                ]
            });

            var selectedItems = [];
 
            var selectItem = function(item) {
                selectedItems.push(item);
            };

            var unselectItem = function(item) {
                selectedItems = $.grep(selectedItems, function(i) {
                    return i !== item;
                });
            };

            var deleteSelectedItems = function() {
                if(!selectedItems.length || !confirm("Are you sure you want to delete these items?"))
                    return;

                var $grid = $("#jsGrid");

                $.each(selectedItems, function(_, item) {
                    $grid.jsGrid("deleteItem", item);
                });

                selectedItems = [];
            };
        });
    }
});

**Comment by tabalinas** [comment]
Does it make sense to turn data into string and then parse it back to JSON?

`db.sales_action_json = JSON.parse(JSON.stringify(data));`

Apart from that, I guess that `sales_action` field is type of string (in the data coming from server in `response`). That's why items are empty.

**Comment by viranianish** [comment]
Yeah you are right, sales_action is displayed after changing type to int. Thanks a lot.

**Comment by tabalinas** [comment]
You are welcome!

**Comment by brianDHall** [comment]
We are also having the same issue of the value not displaying until the row is clicked.  
//Model
 public class ReimbursementMethodViewModel
    {
        public decimal TRAVEL_REIMBURSEMENT_METH_SEQ { get; set; }
        public string DESCRIPTION { get; set; }
    }
@model IList<ACBL.Crew.Travel.Web.Models.ReimbursementMethodViewModel>

 var methods = @Html.Raw(Json.Encode(@Model));

 var db = {
            loadData: function (filter) {
                var d = $.Deferred();
                $.ajax({
                    url: '@ViewBag.API_URL' + "TRAVEL_REIMBURSEMENT_TYPES",
                    type: "GET",
                    data : filter,
                    dataType: "json"
                }).done(function (response) {d.resolve(response.value);
                });
                return d.promise();


            }
};
 $(function (refreshgrid) {
            $("#jsGrid").jsGrid({
                inserting: true,
                editing: true,
                sorting: false,
                paging: true,
                autoload: true,
                width: "115%",
                height: "auto",
                controller: db,
                fields: [
                                { name: "TRAVEL_REIMBURSEMENT_TYPE_SEQ", title: "", type: "number", width: 30, editing: false, inserting: false },
                                { name: "DESCRIPTION", title: "Description", type: "text", width: 125, editing: true, inserting: true },
                                { name: "TRAVEL_REIMBURSEMENT_CODE", title: "ADP Code", type: "text", width: 30, editing: true, inserting: true },
                                { name: "methods", title: "Pay Method"
                                    , type: "select"
                                    , items:  methods
                                    , valueField: "TRAVEL_REIMBURSEMENT_METH_SEQ"
                                    , textField: "DESCRIPTION"
                                    , filterValue: function() { return this.items[this.filterControl.val()][this.textField];}
                                },
                                { type: "control", deleteButton: true, editButton: true, insertButton: true, editButtonTooltip: "Edit Amount" },
                               {
                                   itemTemplate: function (value,item) {
                                       var $result = jsGrid.fields.control.prototype.itemTemplate.apply(this, arguments);
                                       var $EditButton = $("<button>")
                                       .text("Edit More")
                                       .click(function(e){
                                           location.href = '@Url.Action("Details", "ReimbursementType")'  + '?' + "ptypeseq=" + item.TRAVEL_REIMBURSEMENT_TYPE_SEQ;
                                       });
                                       return $result.add($EditButton);
                                   }
                               }
                ]
            });
        });

**Comment by viranianish** [comment]
Hello @brianDHall, I see that your variable TRAVEL_REIMBURSEMENT_METH_SEQ is defined as decimal, change it to int and then try it..
May be it will solve the issue.

**Comment by brianDHall** [comment]
OK tried that no luck.
  public class ReimbursementMethodViewModel
    {
        public int TRAVEL_REIMBURSEMENT_METH_SEQ { get; set; }
        public string DESCRIPTION { get; set; }
    }

//controller
var methods = context.TRAVEL_REIMBURSEMENT_METHOD.Select(x =>
           new ReimbursementMethodViewModel
           {
               DESCRIPTION = x.DESCRIPTION,
               TRAVEL_REIMBURSEMENT_METH_SEQ = (int)x.TRAVEL_REIMBURSEMENT_METH_SEQ
           }).ToList()

**Comment by tabalinas** [comment]
@brianDHall, could you provide the resulting html with js rendered on the client?

**Comment by brianDHall** [comment]
<!DOCTYPE html>


<html>


<head>


<meta charset="utf-8" />


<meta name="viewport" content="width=device-width, initial-scale=1.0">


<title>Reimbursement types - My ASP.NET Application</title>


<link href="/ACBL.Crew.Travel.Web/Content/jquery-ui.css<http://localhost/ACBL.Crew.Travel.Web/Content/jquery-ui.css>" rel="stylesheet"/>


<link href="/ACBL.Crew.Travel.Web/Content/bootstrap.css<http://localhost/ACBL.Crew.Travel.Web/Content/bootstrap.css>" rel="stylesheet"/>


<link href="/ACBL.Crew.Travel.Web/Content/site.css<http://localhost/ACBL.Crew.Travel.Web/Content/site.css>" rel="stylesheet"/>


<link href="/ACBL.Crew.Travel.Web/Content/jsgrid-theme.css<http://localhost/ACBL.Crew.Travel.Web/Content/jsgrid-theme.css>" rel="stylesheet"/>


<link href="/ACBL.Crew.Travel.Web/Content/jsgrid.min.css<http://localhost/ACBL.Crew.Travel.Web/Content/jsgrid.min.css>" rel="stylesheet"/>


<link href="/ACBL.Crew.Travel.Web/Content/multi-select.css<http://localhost/ACBL.Crew.Travel.Web/Content/multi-select.css>" rel="stylesheet"/>



<script src="/ACBL.Crew.Travel.Web/Scripts/modernizr-2.6.2.js<http://localhost/ACBL.Crew.Travel.Web/Scripts/modernizr-2.6.2.js>"></script>




</head>


<body>


<div class="navbar navbar-inverse navbar-fixed-top">


<div class="container">


<div class="navbar-header">


<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">


<span class="icon-bar"></span>


<span class="icon-bar"></span>


<span class="icon-bar"></span>


</button>


<a class="navbar-brand" href="/ACBL.Crew.Travel.Web/PlanTravel<http://localhost/ACBL.Crew.Travel.Web/PlanTravel>">Crew Travel</a>


</div>


<div class="navbar-collapse collapse">


<ul class="nav navbar-nav">


<li><a href="/ACBL.Crew.Travel.Web/Travel<http://localhost/ACBL.Crew.Travel.Web/Travel>">Employees</a></li>


<li><a href="/ACBL.Crew.Travel.Web/<http://localhost/ACBL.Crew.Travel.Web/>">Travel Reimbursements</a></li>


<li><a href="/ACBL.Crew.Travel.Web/PlanTravel<http://localhost/ACBL.Crew.Travel.Web/PlanTravel>">Plan Travel</a></li>


<li><a href="/ACBL.Crew.Travel.Web/RiverPort<http://localhost/ACBL.Crew.Travel.Web/RiverPort>">River Ports</a></li>


</ul>


<ul class="nav navbar-nav navbar-right">


<li><a href="/ACBL.Crew.Travel.Web/Account/Register<http://localhost/ACBL.Crew.Travel.Web/Account/Register>" id="registerLink">Register</a></li>


<li><a href="/ACBL.Crew.Travel.Web/Account/Login<http://localhost/ACBL.Crew.Travel.Web/Account/Login>" id="loginLink">Log in</a></li>


</ul>



</div>


</div>


</div>


<div class="container body-content">



<h2>Reimbursement types</h2>


<!DOCTYPE html>



<link href="/ACBL.Crew.Travel.Web/Content/Site.css<http://localhost/ACBL.Crew.Travel.Web/Content/Site.css>" rel="stylesheet" />


<div id="jsGrid"></div>













<hr />


<footer>


<p>&copy; 2016 - American Commercial Barge Line</p>


</footer>


</div>



<script src="/ACBL.Crew.Travel.Web/Scripts/jquery-1.10.2.js<http://localhost/ACBL.Crew.Travel.Web/Scripts/jquery-1.10.2.js>"></script>


<script src="/ACBL.Crew.Travel.Web/Scripts/jquery-ui-1.11.4.js<http://localhost/ACBL.Crew.Travel.Web/Scripts/jquery-ui-1.11.4.js>"></script>


<script src="/ACBL.Crew.Travel.Web/Scripts/jquery.datetimepicker.js<http://localhost/ACBL.Crew.Travel.Web/Scripts/jquery.datetimepicker.js>"></script>


<script src="/ACBL.Crew.Travel.Web/Scripts/jsgrid.js<http://localhost/ACBL.Crew.Travel.Web/Scripts/jsgrid.js>"></script>


<script src="/ACBL.Crew.Travel.Web/Scripts/jsgrid.min.js<http://localhost/ACBL.Crew.Travel.Web/Scripts/jsgrid.min.js>"></script>


<script src="/ACBL.Crew.Travel.Web/Scripts/jquery.multi-select.js<http://localhost/ACBL.Crew.Travel.Web/Scripts/jquery.multi-select.js>"></script>



<script src="/ACBL.Crew.Travel.Web/Scripts/bootstrap.js<http://localhost/ACBL.Crew.Travel.Web/Scripts/bootstrap.js>"></script>


<script src="/ACBL.Crew.Travel.Web/Scripts/respond.js<http://localhost/ACBL.Crew.Travel.Web/Scripts/respond.js>"></script>




<script type="text/javascript">


var methods = [{"TRAVEL_REIMBURSEMENT_METH_SEQ":0,"DESCRIPTION":"Mileage Based Pay Amount"},{"TRAVEL_REIMBURSEMENT_METH_SEQ":1,"DESCRIPTION":"Fixed Pay Amount"},{"TRAVEL_REIMBURSEMENT_METH_SEQ":2,"DESCRIPTION":"Control Value"}];



var db = {


loadData: function (filter) {



var d = $.Deferred();


$.ajax({


url: 'http://localhost/CrewTravelApi/odata/' + "/TRAVEL_REIMBURSEMENT_TYPES",


type: "GET",


data : filter,


dataType: "json"


}).done(function (response) {


d.resolve(response.value);


});


return d.promise();




},


insertItem: function (item) {



return $.ajax({


url: 'http://localhost/CrewTravelApi/odata/' + "/TRAVEL_REIMBURSEMENT_TYPES",


type: "POST",


dataType: "json",


data: item


});



},


deleteItem: function (item) {



$.ajax({


type: "DELETE",


url: 'http://localhost/CrewTravelApi/odata/' + "TRAVEL_REIMBURSEMENT_TYPES(5)" + '?' + "ptypeseq=" + item.TRAVEL_REIMBURSEMENT_TYPE_SEQ,


dataType: "json"


});



},


updateItem: function (item) {




return $.ajax({


type: "PUT",


url: 'http://localhost/CrewTravelApi/odata/' + "TRAVEL_REIMBURSEMENT_TYPES(5)" ,


data: item,


dataType: "json"


});


}



};












$(function (refreshgrid) {


$("#jsGrid").jsGrid({



inserting: true,


editing: true,


sorting: false,


paging: true,


autoload: true,


width: "115%",


height: "auto",


controller: db,


fields: [


{ name: "TRAVEL_REIMBURSEMENT_TYPE_SEQ", title: "", type: "number", width: 30, editing: false, inserting: false },


{ name: "DESCRIPTION", title: "Description", type: "text", width: 125, editing: true, inserting: true },


{ name: "TRAVEL_REIMBURSEMENT_CODE", title: "ADP Code", type: "text", width: 30, editing: true, inserting: true },


{ name: "methods", title: "Pay Method"


, type: "select"


, items: methods


, valueField: "TRAVEL_REIMBURSEMENT_METH_SEQ"


, textField: "DESCRIPTION"


, filterValue: function() { return this.items[this.filterControl.val()][this.textField];}


},


{ type: "control", deleteButton: true, editButton: true, insertButton: true, editButtonTooltip: "Edit Amount" },


{


itemTemplate: function (value,item) {


var $result = jsGrid.fields.control.prototype.itemTemplate.apply(this, arguments);


var $EditButton = $("<button>")


.text("Edit More")


.click(function(e){


location.href = '/ACBL.Crew.Travel.Web/ReimbursementType/Details' + '?' + "ptypeseq=" + item.TRAVEL_REIMBURSEMENT_TYPE_SEQ;


});


return $result.add($EditButton);


}


}







]


});





});



</script>




</body>


</html>

**Comment by Wdio-v4reilly** [comment]
I confronted that issue and found an answer



https://stylesheets.space/questions/guide-on-altering-the-cursor-icon-during-an-ajax-operation-within-a-jquery-dialog
