### ISSUE TITLE
Passing ID with updateItem and deleteItem

### ISSUE THREAD

**Issue by w9nder** [tabalinas/jsgrid#264]
Hey,

I was taking my time going through every issue request, looking for some clarification..
Im kinda new to the Rest,Json,JS, Ajax Stuff but every day it is getting better, but i really need help as im not able to find anything to help me with my question.

So i wrote a API that has this stuff ( Its the beginning - only 1 table right now ):

- get /tech -> Get all data
- get /tech/id -> Get one Set of data
- post /tech -> Insert new data
- put /tech/:id -> edit data at ID
- delete /tech/:id -> delete data at ID

So, to update an item i need to pass the id for the row that is going to be edited. is there a easy way to pass the ID that is beeing edited to the URL provided in UpdateItem? 

Thanks in advance - i Hope you can help me.

**Comment by tabalinas** [comment]
Not sure which technology is more close to you, but there are plenty of examples for different backend technologies http://js-grid.com/samples/. These are sample applications showing how to create a REST service and use it with js-grid.
