### ISSUE TITLE
Body table with fix width 100px

### ISSUE THREAD

**Issue by tassamartz** [tabalinas/jsgrid#265]
Hello there,

i've been trying to use the js-grid libraray, i've worked with static and dynamic table, however in all cases, the first time the table is shown every time i see the following generated code for the body of the table 
<div class="jsgrid-grid-body"><table class="jsgrid-table" style="width: 100px;">
<tbody><tr class="jsgrid-row"><td class="jsgrid-align-center" style="width: 45%;">Aircraft</td><td class="jsgrid-align-center" style="width: 45%;"></td><td class="jsgrid-control-field jsgrid-align-center" style="width: 10%;"><input class="jsgrid-button jsgrid-edit-button" type="button" title="Edit"></td></tr><tr class="jsgrid-alt-row"><td class="jsgrid-align-center" style="width: 45%;">Basecamp</td><td class="jsgrid-align-center" style="width: 45%;"></td><td class="jsgrid-control-field jsgrid-align-center" style="width: 10%;"><input class="jsgrid-button jsgrid-edit-button" type="button" title="Edit"></td></tr></tbody></table></div> 

when you see the first line, the width is set to 100 px i don't know from where it comes, it seems from the js. The first div is the following <div id="jsGrid" class="jsgrid" style="position: relative; height: auto; width: 100%;"> so when i sort for instance my table the table is refreshed and the width of the body columns are aligned with those of the header. So my problem is why the first time the table is displayed the body column is not aligned with those of the header and are of width 100 px.

Thanks for your help!

**Comment by tabalinas** [comment]
I suspect the grid is rendered in an invisible container.
Feel free to provide a demo so we can say for sure.

**Comment by tassamartz** [comment]
Hi, 
thanks for your quick answer, yes you're right it's rendered in an invisible container, indeed a bootstrap tab, i have put the demo here https://jsfiddle.net/oskkter5/1/
If you move the jsGrid div into the first tab it's displayed correctly. So please advice how to avoid this behaviour, i really need to display it inside a tab ( i have a king of vertical menu and inside one of the options i have the jsgrid table.

Thks!

**Comment by tabalinas** [comment]
You need to call `refresh` method of the grid on tab opening. Please, see the following issue https://github.com/tabalinas/jsgrid/issues/49

**Comment by tassamartz** [comment]
Thanks very much for your help. Hope though this will be fixed in the future without any need for refresh if feasible.

The library is fantastic!

**Comment by tabalinas** [comment]
Glad that it worked. Thank for the feedback!
About fixing it out-of-box not sure it's feasible: the solution is to have kinda `resized` event on the div (which is not supported directly by browsers due to performance reasons, only hacky solutions available) or to refresh grid periodically with a timer (this is also shitty solution performance-wise).
