### ISSUE TITLE
When next update will be available?

### ISSUE THREAD

**Issue by overflowz** [tabalinas/jsgrid#267]
I wonder, when next update will be available? I see last updated time is few months ago or more. When can we get more features which were mentioned before here may we know? :-)

I must say, I just felt in-love with this project, it's so flexible and comfortable though!

Kind regards.

**Comment by tabalinas** [comment]
Thank you for your feedback, I appreciate it.
Currently, I'm working on the integration with Angular (repo: https://github.com/tabalinas/ng-jsgrid).
Then in May next minor version of js-grid will be available.
Thank you for your interest!

**Comment by overflowz** [comment]
Thanks to you for this awesome project! Keep going and good luck! :-)

**Comment by tabalinas** [comment]
Thank you!
