### ISSUE TITLE
Frozen column

### ISSUE THREAD

**Issue by adri21112** [tabalinas/jsgrid#269]
Hi!!
I am working with your grid and I need some frozen  columns when I use the overflow-x. Is it posible do this?
Thanks!!!

**Comment by tabalinas** [comment]
Hi! 
Frozen columns are not supported. The easiest way is to use two grids one next to the other. The first should not have horizontal scrolling, while the second will be scrollable.

**Comment by adri21112** [comment]
OK!!! Thanks!! I try it!

**Comment by michaelsogos** [comment]
There is a plan for frozen columns?

**Comment by tabalinas** [comment]
@michaelsogos, this issue has some insights https://github.com/tabalinas/jsgrid/issues/105

**Comment by saeedallahyari** [comment]
Hi.
Kindly. 
Thanks for providing simple & powerful grid.

Freezing columns provide good feeling user experience. Most of the time we used one grid in one page. 
According to #105 issue, when user put a grid in a page this code work correctly, but when use more than one grid, it didn't work correctly. In other word, the first one of all grids in the form work correctly in particular when applying freezing to all grids.

What is your idea?

Thanks.
