### ISSUE TITLE
Can I custom "select" with itemTemplate view?

### ISSUE THREAD

**Issue by ElioRiba** [tabalinas/jsgrid#271]
Hi Tabalinas,
 How can I custom the view a "select" group of item with my css, for example with different color or with glyphicon for each item?

This is my field now:

```js
                fields: [
                    { name: "StockNumber", type: "number", width: 50, align: "left", css: "customfamilyfont" },
                    { name: "Description", type: "text",
                    	itemTemplate: function(value, item) {
        					return $("<a>").attr("href", "single_item.php?descr="+value)
        					.attr("style", "customfamilyfont")
        					.text(value);
        					}, 
    						width: 200 },
                    { name: "Address", type: "text", width: 50, visible: false },
                    { name: "DataEntry", type: "text", width: 50, css: "customfamilyfont" },
                    { name: "Status", type: "select", width: 50, css: "customfamilyfont", items: 
                    	[
                    		{ Name: "In Stock", Id: "1"},
                    		{ Name: "Out Of Stock", Id: "2"},
                    		{ Name:"Pending", Id: "3"}
                    	],
                        valueField: "Id",
    					textField: "Name",
    					selectedIndex: 0
                    },
                    {
                        type: "control",
                        editButton: false,
                        deleteButton: false,
                        itemTemplate: function(value, item) {
    						return this._createGridButton("jsgrid-edit-button", "Click to Edit this row", function(grid) {
        						showDetailsDialog("Edit", item);
    						});
						},
                        headerTemplate: function() {
                            return $("<a>")
                            	.attr("class", "btn btn-success")
                            	.append("<i class='glyphicon glyphicon-plus icon-white'></i>")
                            	.append("<span> ADD</span>")
                                .on("click", function () {
                                    showDetailsDialog("Add", {});
                                });
                        }
                    }
                ]
```

**Comment by tabalinas** [comment]
What's about redefining `editTemplate` (or any other template):

```js
editTemplate: function(value, item) {
    var $select = jsGrid.fields.select.prototype.editTemplate.apply(this, arguments);
    // do whatever you wish with items and select itself
    return $select
}
```

**Comment by ElioRiba** [comment]
I'm sorry, but I don't understand how can I do.
Here in attached the field code I tried to fit but it doesn't work

`
{ name: "Status", type: "select", width: 50, css: "customfamilyfont", items: 
                    	[
                    		{ Name: "All", Id: ""},
                    		{ Name: "In Stock", Id: "1"},
                    		{ Name: "Out Of Stock", Id: "2"},
                    		{ Name:"Pending", Id: "3"}
                    	],
                        valueField: "Id",
    					textField: "Name",
    					selectedIndex: 0,
    					align: "center",
    					editTemplate: function(value, item) {
    						var $select = jsGrid.fields.select.prototype.editTemplate.apply(this, arguments);
    						// do whatever you wish with items and select itself
    						if (value == "1") {
    							$("span").attr("class", "label-success label label-default");
    						}
    						if (value == "2") {
    							$("span").attr("class", "label-default label label-danger");
    						}
    						return $select;
						}
                    }
`
Perhaps this code has not sense, but my goal will be display in select column for each row a special label which depends from the value loaded, for example:
if value loaded is "1" I'd like to create for that row a label success, for value "2" label danger, and other... as reported in the code above.
I wrote that code just to try to explain what I want to achive

**Comment by tabalinas** [comment]
Well, you have your `$select` jQuery object and you can do any modification at that point
see an example here: http://jsfiddle.net/tabalinas/9zukruyo/ (be aware styling of select options doesn't work on Mac).

**Comment by tabalinas** [comment]
Let me know if it's not what you meant.

**Comment by ElioRiba** [comment]
Thanks for your reply, but It was not that I've asked, sorry but it was my fault.
What I tried to explain is I have a table with "data manipulator" mode (just with popup dialog box), so when my table has been loaded in the "select" row there are fixed values like reported above (read from DB) and my request is customize every single data, for example: if I read "1" or "In Stock" value, I'd like to show this cell like the picture:

![screen shot 2016-05-05 at 09 53 26](https://cloud.githubusercontent.com/assets/18682722/15039760/44743f48-12a7-11e6-98be-507a2e0a0eb4.png)

obviously instead "success" label I'd like to put my read value.

My goal is get something like that:

![screen shot 2016-05-05 at 09 57 53](https://cloud.githubusercontent.com/assets/18682722/15039854/e361e114-12a7-11e6-9627-65b9deec93cc.png)

**Comment by tabalinas** [comment]
I'm still not sure where you want to put these badges. Just in the cell content, then redefine `itemTemplate` and return your `<span>`. If you want to put badges inside the select items, then probably you need custom field with a select control that supports this feature.

**Comment by ElioRiba** [comment]
I solve my problem from your suggestion, here is the field code:

`
{ name: "Status", type: "select", width: 50, itemTemplate: function(value, item) {
                    		// modespan store the kind of span color
                    		// textspan store the show text in each row
                    		var modespan = "";
                    		var textspan = "";
                    		if (value=="1") {
                    			modespan = "success";
                    			textspan = "In Stock";
                    		} else if (value=="2") {
                    			modespan = "danger";
                    			textspan = "Out Of Stock";
                    		} else if (value=="3"){
                    			modespan = "warning";
                    			textspan = "Pending";
                    		};
                    		return $("<span>").attr("class", "label label-"+modespan)
        					.attr("style", "customfamilyfont")
        					.text(textspan);
                    	},
                    	items: 
                    	[
                    		{ Name: "All", Id: ""},
                    		{ Name: "In Stock", Id: "1"},
                    		{ Name: "Out Of Stock", Id: "2"},
                    		{ Name:"Pending", Id: "3"}
                    	],
                        valueField: "Id",
    					textField: "Name",
    					selectedIndex: 0
                    },
`

and here is the show:

![screen shot 2016-05-05 at 18 21 00](https://cloud.githubusercontent.com/assets/18682722/15050929/29c3b1c8-12ee-11e6-8dff-6ea68cf461da.png)

I don't know whether my code is elegant, but works properly.
Thanks for your helping.

**Comment by tabalinas** [comment]
You are welcome! Glad that you figured it out!

**Comment by ElioRiba** [comment]
Thanks a lot again and don't worry, it will not the last time that I ask you helping :-)
I think your "framework" it is absolutely wonderful!!!
