### ISSUE TITLE
validation on previous value

### ISSUE THREAD

**Issue by mugsisme** [tabalinas/jsgrid#272]
Hi, I have a question about jsgrid.  I want to make a simple, dynamic grid.  The user will enter 3 values, start year, end year, and amount.  They could enter several rows like this, but I want to validate so each subsequent start year is at least one year later than the last end year entered.  How do I reference that value to validate against?  Thank you.

**Comment by tabalinas** [comment]
Validation function accepts the field value and the entire item. So you can do validation on the one of the fields. From what I understood here is the example code for your case:

```js
         $("#jsGrid").jsGrid({
                height: "70%",
                width: "100%",
                editing: true,
                autoload: true,
                controller: {
                    loadData: function() {
                        return [
                            { value1: 1, value2: 2 },
                            { value1: 10, value2: 20 }
                        ];
                    }
                },
                fields: [
                    { name: "value1", type: "number", width: 150 },
                    {
                        name: "value2",
                        type: "number",
                        width: 150,
                        validate: {
                            validator: function(value, item) {
                                return value > item.value1;
                            },
                            message: "Value2 should be greater than Value1"
                        }
                    },
                    { type: "control" }
                ]
            });
```

**Comment by mugsisme** [comment]
Hi, thanks so much for the help.  I cant seem to get it working correctly for my particular example, however.  I am attaching my code and a screen shot of the control on my page.  I have a couple of requirements, the first From Year value is always 1, and the max To Year value cant be greater than 121.  If the user adds a new row, the From Year has to be 1 year higher than the previous To Year value.  The To Year value can be the same as the From Year value on the same row, but cannot be lower.  Thanks!

<script>
        var clients = [
            { "From Year": 1, "To Year": 121, "Amount/Value": "$0" }
           
        ];
     
       
     
        $("#jsGrid").jsGrid({
            width: "80%",
            height: "150px",
     
            inserting: true,
            editing: true,
            sorting: true,
            paging: true,
            
            controller: {
                    loadData: function() {
                        return [
                            { value1: 1, value2: 2 },
                            { value1: 10, value2: 20 }
                        ];
                    }
                },
            
            
            deleteConfirm: "Do you really want to delete the row?",
     
            data: clients,
     
            fields: [
                { name: "From Year", type: "number", width: 40,         validate: {
            validator: "range",
            message: function(value, item) {
                return "Minimum year is 1 and maximum year is 121. Entered year is \"" + value + "\"  and is out of specified range.";
            },
            param: [1, 121],
            
            validator: function(value, item) {
                                return  value > item.value1;
                            },
                            message: "Value2 should be greater than Value1"
            
        } },
        
                { name: "To Year", type: "number", width: 40 },
                { name: "Amount/Value", type: "text", width: 60 },
                { type: "control" }
            ]
        });
    </script>
![screen shot 2016-05-04 at 8 29 48 am](https://cloud.githubusercontent.com/assets/11522098/15014182/80c6ed7c-11d2-11e6-8411-8e34476ed86e.png)

**Comment by mugsisme** [comment]
Thanks for the reply.  I want the grid to appear with one row initially, with the values and headers as shown in the image I attached.  While your code properly stops the “To Year” column from being less than the “From Year” column, I also need subsequent “From Year” entries to be 1 year more than the previous “To Year”  Actually I would like it to default to a value one greater than the previous To Year value and the new To Year value on adding a row should once again be 121.

For example, initially…
 1     121  $0

Lets say the user changes 121 to 50 and adds a row, the new row should default to 51 and 121.  If he then changes 121 to 75 and adds a row, it should default to 76  and 121.  I do not know how to accomplish getting the From Year to be one more than the previous To Year, and actually I don’t want the From Year to be editable by the user at all.



I also need to know if the whole grid can be disabled or hid when need be.

Thank you very much.

**Comment by tabalinas** [comment]
You can access grid data items in your validation function reading the option `data` of the grid. 

For the rest you've touched bunch of different topics here. Have you tried to implement all that? 
Not sure it makes sense to mix several all topics in a single request. I believe the initial question is answered. So if you have concrete questions open separate issues for them.

**Comment by mugsisme** [comment]
I appreciate your help. Your original answer checks value1 vs value2 of the same row, how do I check it validate value1 vs the previous value2?

Sent with Good Work (www.good.com)

On May 4, 2016 5:48 PM, Artem Tabalin <notifications@github.com> wrote:

You can access grid data items in your validation function reading the option data of the grid.

For the rest you've touched bunch of different topics here. Have you tried to implement all that?
Not sure it makes sense to mix several all topics in a single request. I believe the initial question is answered. So if you have concrete questions open separate issues for them.

-

**Comment by tabalinas** [comment]
Please, see my previous comment, I answered this question.

**Comment by tabalinas** [comment]
here is an example showing the principle (put your condition):
```js
validator: function(value, item) {
	var gridData = $("#jsGrid").jsGrid("option", "data");
	var lastItemValue2 = gridData[gridData.length - 1].value2;
    return value > item.value1 && value > lastItemValue2;
}
```
