### ISSUE TITLE
Body table with fix width 100px

### ISSUE THREAD

**Issue by pichlou** [tabalinas/jsgrid#273]
hi,i have a grid.
i pass options to it,and show table in bootstrap tab with click event,but table-body have 100px width! :(

    document.querySelector('a[data-target="#inbox"]').addEventListener('click', function () {
        $('#inboxGrid').mygrid({
            height: 'auto',
            width: '100%',
            paging: true,
            autoload: true,
            filtering: false,
            sorting: false,
            pageLoading: true,
            pageIndex: 1,
            pageSize: 12,
            selecting: true,
            pageButtonCount: 5,
            noDataContent: '....',
            loadIndication: true,
            loadIndicationDelay: 300,
            loadMessage: 'wait...',
            loadShading: true,
            LoadDataUrl: './inbox/q',
            fields: [
                {name: "inbox_msg_id", title: '', width: 50},
                {name: "inbox_msg_title", title: '', width: 50},
                {name: "inbox_msg_date_register", title: '', width: 50},
                {name: "name", title: '', width: 50}
            ]
        });

**Comment by tabalinas** [comment]
Have you seen this issue https://github.com/tabalinas/jsgrid/issues/265#issuecomment-216817771?

**Comment by pichlou** [comment]
yes,can i call _refreshSize method directly?
when call this method?

**Comment by pichlou** [comment]
yes,can i call _refreshSize method directly?
when call this method?

**Comment by pichlou** [comment]
thanks,its resolved,when i using "shown" instead of "click" event

**Comment by tabalinas** [comment]
glad that you figured it out.
regarding `_refreshSize` it's not the best idea to use it since it's a private method and can be renamed or changed in future (no guarantee for backward compatibility). Maybe it makes sense publish this method, to avoid rerendering all the grid data when calling `refresh`.
