### ISSUE TITLE
Is there a callback function executed when filtering?

### ISSUE THREAD

**Issue by fakelbst** [tabalinas/jsgrid#275]
Hello,
When I'm filtering and press `Enter`, which callback function can I look into? It seems not on the docs.
Thanks.

**Comment by tabalinas** [comment]
You are right, it's implemented on the level of the field, not on the grid level.
The easiest way I see to handle it is to redefine a little bit `filterTemplate` and add your own keypress handler:

```js
filterTemplate: function() {
	var $result = jsGrid.fields.text.prototype.filterTemplate.call(this);

	$result.on("keypress", function(e) {
	    if(e.which === 13) {
	        // do your handling here
	    }
	});

	return $result;
}
```
