### ISSUE TITLE
How I can add checkbox for multiple delete rows?

### ISSUE THREAD

**Issue by PashaShulga** [tabalinas/jsgrid#277]
I need select many rows use checkbox and remove them using the button

**Comment by tabalinas** [comment]
Is `Batch Delete` http://js-grid.com/demos/ demo is not what you are looking for?

**Comment by PashaShulga** [comment]
No, I need add in the table a column with checkbox and select many rows for removing, after select and press button the ajax send to the server array with data for removing from database. For example: [(col1.1, col1.2), (col2.1, col2.2)]. I just need know, how I can add checkbox with readOnly = False and add delete button.

**Comment by tabalinas** [comment]
Not sure how it's different from the demo

**Comment by PashaShulga** [comment]
So, how I can remove all (or 2, 3, 10) rows pressing one button?

**Comment by tabalinas** [comment]
You check 2, 3 or 10 items (that you want to delete) and press button Delete. Have you opened `Batch Delete` demo?

**Comment by PashaShulga** [comment]
Ooh, Sorry! I work 70 hours per week, this just my inattention.

**Comment by tabalinas** [comment]
Glad that you found it.

**Comment by PashaShulga** [comment]
I can use Batch Delete if parameter "editing: true" ?

**Comment by tabalinas** [comment]
Yes, why not?

**Comment by PashaShulga** [comment]
need double click for select, a first click - activate editing mode, second click - check mark

**Comment by tabalinas** [comment]
Add a `click` handler that will stop event from poping up

```
itemTemplate: function(_, item) {
    return $("<input>").attr("type", "checkbox")
            .on("click", function () {
                return false;
            })
            .on("change", function () {
                $(this).is(":checked") ? selectItem(item) : unselectItem(item);
            });
},
```

**Comment by drevix** [comment]
Hello,
I can change the confirmDeleting property after having created the JSGrid.

**Comment by drevix** [comment]
Hello,
Can I change the property confirmDeleting after having created the JSGrid? 
Excuse me, my English is bad.

**Comment by tabalinas** [comment]
@drevix: why are you commenting on this ticket? It seems irrelevant. If you have a question, open another a separate issue.

**Comment by priyanka335** [comment]
how to do bulk delete rows using checkbox
