### ISSUE TITLE
Copy grid data to clipboard.

### ISSUE THREAD

**Issue by overflowz** [tabalinas/jsgrid#281]
Hi, is there any way to copy only certain column's data to clipboard? (needed to paste it in excel later). Or if there's any 'hacks' to do that, could someone point me?

Regards!

**Comment by tabalinas** [comment]
Maybe look into [Clipboard API](https://developer.mozilla.org/en-US/docs/Web/API/ClipboardEvent), but it's definitely out of scope of jsgrid at least currently.
