### ISSUE TITLE
Add customize control

### ISSUE THREAD

**Issue by frankioh** [tabalinas/jsgrid#282]
There is a way to add a customize control inside of the controls column? I found in the documentation how do in the other colums, but for my project I need add it in that specific column:

![controls](https://cloud.githubusercontent.com/assets/8726569/15276964/a0cc3bde-1abc-11e6-8048-008eec353949.png)

Thanks in advance

**Comment by tabalinas** [comment]
Yes, you can customize control field as any other grid field, redefining `itemTemplate` or any other template. In fact, all fields are equal, their implementation is not coupled to the code of the grid itself.

**Comment by frankioh** [comment]
I tested and works!  BTW there is any wait to disable the edit mode with one click? I really like if I can enabled the edit mode until the user do click in my control.

Thanks

**Comment by tabalinas** [comment]
Sure, in fact, this implementation is just a default `rowClick` handler. So it's enough to put `$.noop` to this function to turn it off.
