### ISSUE TITLE
Showing filter text box when filed type is not given

### ISSUE THREAD

**Issue by chinthaka321** [tabalinas/jsgrid#284]
Hi Artem,
JS Grid is awesome !!. I'm using it for couple of project which I'm working on. Good job.

I have a one question. When I remove the type of the field filter input box of the grid get disappear. Do you know any reason for that?
What I want to archive is I want to select a row but row should not display text input box. It should appear like a label. But still I want to do the filtering using the header input box at the top.

**Comment by tabalinas** [comment]
Thank you for the feedback!

Yes, it happens because field w/o type doesn't have `filterTemplate` defined.
I believe all what have is just prevent field editing. Then leave field type as is, but redefine `editTemplate: function(value) { return value; }` and put field option `editing: false`.
