### ISSUE TITLE
OData JSON load 

### ISSUE THREAD

**Issue by backpt** [tabalinas/jsgrid#285]
Hello,

It's my first time using jsGrid, I'm a lot happy with the design and the implementation. I have read the documentation and saw the odata service demo, but I don't understand how the data is loaded. How can I build my JSON.

My project is to read a xml file that has the list of users and be able to load and edit that data in jsGrid.

Can you help me please?

Best regards,
Tiago Filipe

**Comment by tabalinas** [comment]
Please, checkout backend examples http://js-grid.com/samples/. Amount others there is an example with ASP.NET WebAPI.

**Comment by backpt** [comment]
Thank you very much!! :) I didn't see that tab 'BackEnds'
