### ISSUE TITLE
Custom Grid Field issue

### ISSUE THREAD

**Issue by ViniH** [tabalinas/jsgrid#287]
Hi again,

I'm now trying to implement an object picker in a grid field for editing purposes, however it is proving somewhat problematic.

I've followed the demo, however as always there is added complexity for me due to the grid being handled by a knockout binding... and I am struggling to figure out precisely how to do this.

The error I am having at the moment is **"grid.Field is not a constructor"**.

I've removed the contents of the loadData and updateItem method, as well as various other suibscription stuff which would only add confusion.

I suspect I'm trying to do this in the wrong place or some such, with most of the "issues" I've had in the past with jsGrid I've ended up figuring it out by examining the source code of jsgrid, but I am struggling with this one (perhaps because it's late on a Friday?).

Anyway the stripped out binding code is as follows:

```
	var defaultFieldListGridBinding =
		{
			init: function ( element, valueAccessor, allBindings, viewModel: ifwk.ViewModels.IObjectViewModel, bindingContext )
			{
				// Debug.
				var dataVM: idmg.ViewModels.IDefaultFieldListViewModel = valueAccessor();

				// Setup the basic configuration
				var jsGridOptions = {
					width: 400,
					editing: true,
					autoLoad: true,
					paging: false,
					pageLoading: true,
					noDataContent: "No Records",
				};

				// Add the grid.
				$( element )["jsGrid"]( jsGridOptions );

				// Get current grid object
				var grid = $( element ).data( "JSGrid" );

				/**
				* Custom grid field for using fieldlist object picker in jsgrid.
				*/
				var FieldList = function ( config )
				{
					grid.Field.call( this, config );
				};

				FieldList.prototype = new grid.Field( {

					itemTemplate: function ( value )
					{
						return new Date( value ).toDateString();
					},

					editTemplate: function ( value )
					{
						return this._editPicker = $( "<input>" ).datepicker().datepicker( "setDate", new Date( value ) );
					},

					editValue: function ()
					{
						return this._editPicker.datepicker( "getDate" ).toISOString();
					}
				});

				grid.fields.fieldList = FieldList;

				// Store in DOM for future use.
				ko.utils.domData.set( element, "jsGridOptions", jsGridOptions );
			},

			update: function ( element, valueAccessor, allBindings, viewModel: ifwk.ViewModels.IObjectViewModel, bindingContext )
			{
				var dataVM: idmg.ViewModels.IDefaultFieldListViewModel = valueAccessor();
				let jsGridOptions = ko.utils.domData.get( element, "jsGridOptions" );

				// If we have nothing to process just exit
				if( !dataVM ) return;

				$( element )["jsGrid"]( {

					fields: [
						{ name: "item", title: "Table", type: "text", width: 178, readOnly: true },
						{ name: "name", title: "Default FieldList", type: "fieldList", width: 178 },
						{
							type: "control",
							width: 41,
							modeSwitchButton: false,
							editButton: true,
							deleteButton: false
						}
					],

					controller:
					{
						loadData: function ( filter )
						{
						
						},

						updateItem: function ( item: idmg.Models.IDefaultFieldList )
						{
						
						},
					}

				});

				$( element )["jsGrid"]( "loadData" );
			}
		};

	ko.bindingHandlers.defaultFieldListGrid = defaultFieldListGridBinding;

**Comment by ViniH** [comment]
I've decided to use the global variable jsGrid as I cannot seem to find a way to tie this functionality to a single grid instance.  Therefore I will be careful in extending Field such that it doesn't break the multiple other implementations we have in the system.

**Comment by tabalinas** [comment]
Could you provide a working (non-working) example in jsfiddle or any other js sandbox, so it will be possible to see the issue?

**Comment by tabalinas** [comment]
It would be really good if you could provide your example, since ko adapter is also in a roadmap, so we could benefit from your efforts.

**Comment by tabalinas** [comment]
Closed due to inactivity.
