### ISSUE TITLE
Show Serial Numbers

### ISSUE THREAD

**Issue by BineshNarayanan** [tabalinas/jsgrid#288]
There is no option to show serial number column.

**Comment by tabalinas** [comment]
No sure what you mean by "serial number column", could you explain, please?

**Comment by BineshNarayanan** [comment]
Hi Artem,

Serial Number of the rows showed at the left most column as shown in the
attached snip.

[image: Inline image 2]

On Mon, May 23, 2016 at 8:08 AM, Artem Tabalin <notifications@github.com>
wrote:

> No sure what you mean by "serial number column", could you explain, please?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/tabalinas/jsgrid/issues/288#issuecomment-220865053>
>



-- 
BINESH

**Comment by tabalinas** [comment]
I'm not sure grid should provide any specifics for this functionality, you can easily implement it providing record number in the data item (not necessarily send this from the server, just map items in `loadData` function and add item index).
