### ISSUE TITLE
Link selectedindex of 2 select items

### ISSUE THREAD

**Issue by ErwinvanderZwart** [tabalinas/jsgrid#289]
Hi,

How can i link 2 cells on selectedindex?

If i change select 1 to selectedindex (4)
I want the select in the next cell also to change to same selectedindex (4)

BR,

Erwin van der Zwart

**Comment by tabalinas** [comment]
You can override `editTemplate` to attach `change` event handler. In this handler find another select and set current selected item.

**Comment by tabalinas** [comment]
Please see working demo http://jsfiddle.net/tabalinas/a8fy5wja/

**Comment by ErwinvanderZwart** [comment]
Hi,

This is exactly what i was trying to do, works great, i changed it to make it bidirectional between both
selects and that works now, i did't know how to get it but the css: is a nice identifier (;

Thanks for your help and offcource this very nice UI !

PS: Can we export the data of the total grid back to a json object after changes already? Or at least the row object date after change so i can update the original object used for the grid with the new data?

BR,

Erwin van der Zwart

**Comment by tabalinas** [comment]
You are welcome!
Of course, `controller.updateItem` method is called once you update an item there you should call update method on the server (http://js-grid.com/docs/#grid-controller)

**Comment by ErwinvanderZwart** [comment]
Hi,

Can i ask you a small question again?

I want to save the jsGrid current settings (including select box selected index) and store this (as JSON).

After the export i want to load this stored data again so all my previous settings are loaded again.

Is this possible?

BR,

Erwin van der Zwart
