### ISSUE TITLE
Column desconfigurated

### ISSUE THREAD

**Issue by chepapoa** [tabalinas/jsgrid#291]
Hi,

I got grid on my application and when i bring a grid with data, the grid shows columns desconfigurated. [See image](https://drive.google.com/open?id=0B9m26ABhel12M3hvdEUwYkdVeVU).

when i bring the grid empty and i insert a new item, the grid column configuration is ok. Grid column configuration i mean size of the columns.

**Comment by tabalinas** [comment]
It seems that gris is rendered in a hidden container. You need to call `refresh` method when container is shown (e.g. tab opened)

**Comment by tabalinas** [comment]
Please checkout this issue: https://github.com/tabalinas/jsgrid/issues/265

**Comment by chepapoa** [comment]
Thanks man. It works. :smiley:
