### ISSUE TITLE
Master / Child Grid - Get args from first row without having to click it

### ISSUE THREAD

**Issue by JeffMatthews2** [tabalinas/jsgrid#293]
Hi, I have a master jsGrid which loads a child jsGrid on the master's rowClick.  I also want to have the child grid load when the master grid is first loaded, without having to click on a row.  

RowClick sends "args" to its anonymous function.  I moved the code to build the child grid to a function GetChildGrid(args).  For master's rowClick(), this works fine because rowClick() has the args:

rowClick: function (args) {
            GetChildGrid(args);           
        }, 

How do I get the args for the first row of the master grid without clicking it?  If I can get them, then my child grid can be built from the first row of the master when it is first initialized.

Thanks.

**Comment by JeffMatthews2** [comment]
Update:

I made a small change in the rowClick of master as follows to pass only the args.item:

rowClick: function (args) {
            GetChildGrid(args.item);            
        },

So, here is the function which builds the childGrid:

 function GetChildGrid(myEvent)
    {
        var eventTime = booevent.DateTimeString; 
        var newButton = '<a class="btn btn-default" href="/Home/CheckIn?eventId=' + myEvent.Id + '&eventDate=' + eventTime + '">Check in »</a>';

        $("#CheckInButton").html(newButton);

        $.ajax({
            type: "GET",
            url: "/Event/GetRoster?eventId=" + myEvent.Id,
            dataType: "json",
            contentType: "application/json; charset=utf-8",
            success: function (response) {
                
                $("#EventPlayersGrid").jsGrid({
                    width: "100%",
                    inserting: false, .... etc.
   
Now, here is my call to GetChildGrid on document.ready:

GetChildGrid(1);

I have **no** idea why on earth this works.  I have changed it to GetChildGrid("Jeff"), and it works, too.  Basically, as long as I pass a parameter of any type other than null, it works.

**Comment by tabalinas** [comment]
You can handle this in `loadData` method of controller. Just take the first item and call creation of child grid.

**Comment by JeffMatthews2** [comment]
Thanks.  I see your point.  I am having trouble figuring out why my loadData is not firing.  Neither of the alerts are firing.  Here it is:

I have tried it with and without filter, and neither version will fire.

controller: {
            loadData: function (filter) { //filter) {
                alert("Hi");
                return $.ajax({
                    type: "GET",
                    url: "/Event/ReadEvents",
                    data: filter,
                    dataType: "json",
                    contentType: "application/json; charset=utf-8",
                    success: function (response) {
                        alert(response.First().DateTime);
                        alert("Hi");
                        GetRosterGrid(response.First());
                    }
                });
            },

**Comment by JeffMatthews2** [comment]
I have the load firing.  I just missed the simple rule that I have to call it on document ready.  I thought maybe it was called automatically.

Thank you!  Your grid is beautiful.  I am still debugging the load, but at least it's firing.

**Comment by tabalinas** [comment]
Thanks for the feedback! Let me know if you won't be able to make it work.
