### ISSUE TITLE
Custom Field editTemplate not working right after loadData() called.

### ISSUE THREAD

**Issue by JeffMatthews2** [tabalinas/jsgrid#294]
I have a custom field, which is DateTimeOffset.  When I perform insertItem(), the data is persisted as expected.  In order to cause sorting to include the new record, I call loadData() after the insertItem().  The data loads and displays correctly.

Example: I have dates as follows:

January 1, 2016
February 1, 2016

I insertItem(December 1, 2015)  <-- Note the date precedes the others.

So, after insertItem(), I loadData(), and the list is as expected:

December 1, 2015
January 1, 2016
February 1, 2016

Now, when I edit ANY item in the grid, the date in the customControl reverts to today's date when the edit commences.  For example, if I click on January 1, 2016, the custom datetimepicker is defaulting at May 25, 2016.  It defaults to this same value for all of the rows.  It makes me wonder about the "value" parameter in editTemplate.  So, I put an alert(value) to check it for a couple of dates, and here is what I got:

July 30, 2016: /Date(1469854920000)/
August 6, 2016:  /Date(1470461820000)/

So, the values being sent are different. Somehow, something is going wrong initializing the control for editing.

Here is the code:

```js
editTemplate: function (value) {
            return this._editPicker = //myDateTimePicker.datetimepicker("setDate", new Date(value));
            $("<input>").datetimepicker({
                dateFormat: "DD, MM d, yy - ",
                timeInput: true,
                timeFormat: "h:mm tt",
                timezone: -300,
                timezoneList: [
                    //{ value: -300, label: 'Eastern'},
                    { value: -300, label: 'Central' }
                    //{ value: -420, label: 'Mountain' },
                    //{ value: -480, label: 'Pacific' }
                ],
                showTimezone: true,
                showHour: false,
                showMinute: false
            }).datetimepicker("setDate", new Date(value));
        },
```

After I add an item with insertItem(), I reload the data, like so:

```js
insertItem: function (myEvent) {
                return $.ajax({
                    type: "POST",
                    url: "/Event/Create",
                    data: JSON.stringify(myEvent),
                    dataType: "json",
                    contentType: "application/json; charset=utf-8",
                    success: function (response) {                        
                        $("#RosterForTitle").html("Roster for " + response.DateTimeString);
                        $("#GameDatesGrid").jsGrid("loadData");
                    }
                })
            },

loadData: function(filter){ //filter) {
                return $.ajax({
                    type: "GET",
                    url: "/Event/ReadEvents",
                    data: filter,
                    dataType: "json",
                    contentType: "application/json; charset=utf-8",
                    success: function (response) {                        
                        
                    }
                });
            },
```

**Comment by tabalinas** [comment]
Could you provide a working (non-working) example (as link to public resource or in jsfiddle or in any other format)?

**Comment by JeffMatthews2** [comment]
I wish I could as to either of those, but I don't have a domain which hosts Windows, nor do I know how to use jsfiddle.   I am getting my skills up to speed with MVC, and your grid certainly seems integral to a good product.  I really like what it does!  So easily.

I don't think my problem is difficult at all, and I am almost 100% it's not a bug on your grid.  I am dealing with Json-type stuff, which I crudely understand.  I have just noticed where I think the problem is.  My re-load is getting a different response format than my initial load.  The data is the same, but the format is different.

Initial Load:

```
var events = @Html.Raw(JsonConvert.SerializeObject(Model));
```

The Model is:

```
@model List<Basketball.Models.Event>
```

It looks like this in the debugger:  

```
2016-06-04T14:00:00+00:00
```

On, re-load:

```
controller: {
            loadData: function () { //filter) {
                
                return $.ajax({
                    type: "GET",
                    url: "/Event/ReadEvents",
                    data: events, //filter,
                    dataType: "json",
                    contentType: "application/json; charset=utf-8",
                    success: function (response) {                        
                        
                        GetRosterGrid(response[0]);
                    }
                });
            },
```

And this is the response from the reload:

```
public JsonResult ReadEvents()
        {
            List<Event> events = Events.ReadEvents().OrderByDescending(e => e.DateTime).ToList();
            return Json(events, JsonRequestBehavior.AllowGet);            
        }
```

It looks like this in the debugger:

```
/Date(1465048800000)/
```

I need to make changes so that on re-load it gives me 2016-06-04T14:00:00+00:00, instead of  /Date(1465048800000)/.

I am just trying all sorts of things to see how to fix my re-load response.

**Comment by tabalinas** [comment]
I believe it's about json converter, checkout this article http://www.newtonsoft.com/json/help/html/datesinjson.htm

**Comment by JeffMatthews2** [comment]
Great link!  Fixed!

Thank you so much for your help and your grid!
