### ISSUE TITLE
Callback for SelectedRowChanged or similar

### ISSUE THREAD

**Issue by JeffMatthews2** [tabalinas/jsgrid#296]
RowClick() works well for loading a child grid's data based on master grid's key.  However, the rowClick() event is not fired when user clicks to edit a row in the master grid.  It is also not fired when user clicks + to insert a row in the master grid.  So, what I see is:

Scenario 1:
```
child's grid's data is based on master grid's row 1.  
user clicks to edit row 2 of master grid.
child grid's data is not updated since master's rowClick() is not fired.
```

Scenario 2:
```
child grid's data is based on master grid's row 1.  
user clicks + in master grid to add a blank row which then, receives input focus.
child grid's data is not updated (set to no data) since master's rowClick() is not fired.
```

If I could capture these events, it would make the syncing of child grid's data always be 100% current.  If these events can't be captured, then it's no big deal.  I was just wondering if this is possible, but I am not seeing anything in the documentation.

**Comment by JeffMatthews2** [comment]
Half way there.  OnItemEditing allows me to update the child grid.  I thought OnItemInserting would allow me to do so, too, but it doesn't fire at all.  I have an alert() in there, which never triggers.

**Comment by JeffMatthews2** [comment]
If there is not a way to do this, no worries.  Just close this issue.  It's a very minor point.

**Comment by tabalinas** [comment]
Not sure the issue is clear to me.
`onItemInserting` is not like `onItemEditing`, it's like `onItemUpdating`. It's fired when item insertion is started (just before `controller.insertItem` method call).
Again jsfiddle, showing the issue, could clarify your question. You could fork it from this one https://jsfiddle.net/tabalinas/kL291xp5/

**Comment by JeffMatthews2** [comment]
I appreciate it, but really it's so minor of a point.  It's not really something javascript code can demonstrate.  It's about adding a callback that isn't there.

Basically, when user presses (+) to show the insert row, there is no event to catch that.

Maybe it could be caught by using the insertValue's function of a custom field.  But seriously, it's no big deal.

**Comment by tabalinas** [comment]
In fact, `inserting` option value is changed to `true`. So you can handle this with `onOptionChanging` callback.
