### ISSUE TITLE
Restore selected item upon return to page

### ISSUE THREAD

**Issue by JeffMatthews2** [tabalinas/jsgrid#297]
Hi, Artem.

From your documentation:

>// edit row by jQueryElement
>$("#grid").jsGrid("editItem", $(".specific-row"));

I am wanting to pass selected row from CurrentView to AnotherView for some processing and then, from AnotherView's HttpPost to Controller, I want to redirect back to CurrentView by passing the same row from AnotherView to it. This way, the selected row doesn't jump back to the first row.  User stays on the row he selected before leaving to AnotherView.

The above editItem sounds like a way to do it.

I don't understand the $(".specific-row").  It appears like CSS class notation.  Can you explain how I use this to go directly to a specific row upon loading?

Thanks.

**Comment by JeffMatthews2** [comment]
Never mind.  I finally got it!

There's nothing like taking 50 lines of nasty hack that doesn't work and reducing it to 10 lines which do.  :-)

**Comment by tabalinas** [comment]
Nothing fancy, it shows that you can pass a jQuery element (or even DOMNode) to start editing row. It depends on the scenario how you want to get this row (specific with css selection or any other way).
