### ISSUE TITLE
jsGrid.sortStrategies doc example not working

### ISSUE THREAD

**Issue by bbj** [tabalinas/jsgrid#298]
Hi, in the online doc there is an example for sort strategy customization:

```js
jsGrid.sortStrategies.client = function(client1, client2) {
    return client1.Name.localeCompare(client2.Name) 
        || client1.Age - client2.Age;
};
```

I tried that and it appears that, when called the function params are not the clients, but the field themself, e.g. Name itself versus client object containing .Name; it is a known issue or is there something i did wrong?

**Comment by tabalinas** [comment]
You are right, this is the docs issue. Thank you for the feedback!
