### ISSUE TITLE
Get fields from json

### ISSUE THREAD

**Issue by markdhel** [tabalinas/jsgrid#3]
First of all, great plugin! I would like to ask if it's possible as well to get the fields and it's config from json? Thanks.

**Comment by tabalinas** [comment]
Thank you!
Could you provide more info about the case? 
What would you like to do with the source fields config?
You can save initial fields config before grid creation.

**Comment by markdhel** [comment]
Thanks Artem! What I mean is something like this, i have a json with the results and fields details. I would like to call the fields directly from the json. 
`{
	"results": [{
		"Name": "Otto Clay",
		"Age": 61,
		"Country": 6,
		"Address": "Ap #897-1459 Quam Avenue",
		"Married": false
	},
	{
		"Name": "Connor Johnston",
		"Age": 73,
		"Country": 7,
		"Address": "Ap #370-4647 Dis Av.",
		"Married": false
	},
	{
		"Name": "Lacey Hess",
		"Age": 29,
		"Country": 7,
		"Address": "Ap #365-8835 Integer St.",
		"Married": false
	}],
	"fields": [{
		"name": "Name",
		"type": "text"
	},
	{
		"name": "Age",
		"type": "number"
	},
	{
		"name": "Address",
		"type": "text"
	},
	{
		"name": "Married",
		"type": "checkbox",
		"title": "Is Married",
		"sorting": true
	},
	{
		"type": "control"
	}]
}`

I was able to make this work already i just created a new function to process the the json details and pass the needed details to `loadData` and `fields`. Thanks again!

**Comment by tabalinas** [comment]
I'm glad that you've worked this out. Thank you!
