### ISSUE TITLE
Can you give the working example link of page loading with huge amount of data from database in ASP.Net MVC

### ISSUE THREAD

**Issue by Itsathere** [tabalinas/jsgrid#300]
I have large amount of data in database and and if we fetch all data in json format it takes time to load grid or some time failed to load data.  I have got link [directloadingstrategy](http://js-grid.com/docs/#directloadingstrategy) but have confusion. So, please give me live demo link url with database to load huge amount of data.

I have date field and if i select any value from calendar then getting error 

> Uncaught TypeError: Cannot read property 'toISOString' of null

I have resolve date issue by below code snippet
```js
insertValue: function () {
                    if (this._insertPicker.datepicker("getDate") != null)
                        return this._insertPicker.datepicker("getDate").toISOString();
                    else
                        return this._insertPicker.datepicker("getDate");
                },
                editValue: function () {
                    if (this._insertPicker.datepicker("getDate") != null)
                        return this._insertPicker.datepicker("getDate").toISOString();
                    else
                        return this._insertPicker.datepicker("getDate");
                } 
```

one more thing can we change the date format in jsgrid and if i provide null value to date field it shows 

> Invalid Date

 .do you have solution for date. on null value it should say nothing.

Thanks.

**Comment by tabalinas** [comment]
It would be better to have two separate issues for unrelated questions, but I'll address both questions:

 - For large amount of data, you definitely should not use direct loading strategy, but load data by pages (`pageLoading: true`). You can find working example with Web API in this repo https://github.com/tabalinas/jsgrid-webapi. Note: you should modify it to pass page size and page index for server-side paging.

 - Regarding the date field: jsgrid doesn't have date field as built-in, there is just an example using jqueryUI datepicker in docs. To resolve your issues add specific handling of `null` value in `itemTemplate` (and other templates if necessary).

**Comment by Itsathere** [comment]
The link you have provided, I have already checked that before. After file download getting lots of error.Please give the exact file to implement the exact way of huge data loading.It's the last thing I am unable to implement inside js-grid.

Thanks.
