### ISSUE TITLE
Date format in jsgrid

### ISSUE THREAD

**Issue by Itsathere** [tabalinas/jsgrid#302]
I need date format MM/DD/YY in jsgrid.How to do it. I am trying to do it in Itemtemplate `itemTemplate: function (value) {
                    debugger;
                    if (value == "")
                        return "";
                    else
                        return new Date(value).toDateString();
                },`

but don't know the exact way.

I have resolved it by myself thanks.

**Comment by tabalinas** [comment]
I believe it's not about jsgrid, this is about working with dates in JavaScript. Checkout this SO answer http://stackoverflow.com/questions/3552461/how-to-format-a-javascript-date, I'm personaly prefer MomentJS.

**Comment by Itsathere** [comment]
I have resolve it. Thanks.
