### ISSUE TITLE
Callback for hover over a row

### ISSUE THREAD

**Issue by ekincaglar** [tabalinas/jsgrid#305]
Is there a callback event that is fired when a row is hovered over like onItemSelected (as selection practically means hover in jsGrid)?

**Comment by tabalinas** [comment]
There is no such a callback, but you can easily attach delegated event handler:

```js
$("#jsGrid").on({
    mouseenter: function(){
        var item = $(this).data("JSGridItem");
        console.log("mouseenter", item);
    },
    mouseleave: function(){
        var item = $(this).data("JSGridItem");
        console.log("mouseleave", item);
    }
}, "tr");
```

See example fiddle https://jsfiddle.net/tabalinas/9Lmt33uc/.
