### ISSUE TITLE
How to apply custom filters/search ?

### ISSUE THREAD

**Issue by ladvishal1985** [tabalinas/jsgrid#306]
Hi,
I am using JSGrid for one my requirement. I need to apply filters that are selected through checkboxes. For now I just trying put filter data using dummy filter value as below as shown the documentation:
$("#jsGrid").jsGrid("search", { id: 1 }).done(function() {
    	console.log("filtering completed");
});
This does not seem to work. Please let me know the correct way to have custom filter. 

Thanks
Vishal

**Comment by ladvishal1985** [comment]
I found the way to make the filter work from earlier discussions. My question is how should I invoke only loadData method to change the grid with the filtered data. This is how I am trying to achieve the filter.:
```javascript
    $('.filters input').on('change',function(e){
        $("#jsGrid").jsGrid("loadData").done(function() {
            var filter = { type: "Value" }
            var result = $.grep(subNodes, function(item, idx) {
            for (var key in filter) {
                  var value = filter[key];
                   if (value.length > 0) {if (item[key].indexOf(value) == -1)
                         return false;
                    }
              }
              return true;
         });
         return result;
        });
  })
```
The loadData method does not seem to work for me. Please let me know if this is the correct approach.

**Comment by ladvishal1985** [comment]
Closing this issue as I figured out what needs to be done. It works now. Thanks

**Comment by tabalinas** [comment]
Glad that you figured it out. Just in case checkout this question https://github.com/tabalinas/jsgrid/issues/258.

**Comment by dewelloper** [comment]
loadData: function (filter) {
                            criteria = filter;
                            var data = $.Deferred();
                            $.ajax({
                                type: "GET",
                                contentType: "application/json; charset=utf-8",
                                url: "/fapplications",
                                dataType: "json"
                                }).done(function(response){
                                    var res = [];
                                    if(criteria.Name !== "")
                                    {
                                        response.forEach(function(element) {
                                            if(element.Name.indexOf(criteria.Name) > -1){
                                                res.push(element);
                                                response = res;
                                            }
                                        }, this);
                                    }
                                    else res = response;
                                    if(criteria.Title !== "")
                                    {
                                        res= [];
                                        response.forEach(function(element) {
                                            if(element.Title.indexOf(criteria.Title) > -1)
                                                res.push(element);
                                        }, this);
                                    }
                                    else res = response;                                    

                                    data.resolve(res);
                                });
                            return data.promise();
                        },

**Comment by jabit** [comment]
Hi, that's works for me in all tables with different criteria/filters.
```
loadData: function(filter) {
                    criteria = filter;
                    var d = $.Deferred();
                    $.ajax({
                        url:        "{{ path('ListCustomers') }}",
                        dataType:   "json",
                    }).done(function(response) {
                        let res = [];
                        let keys;
                        let notFound = false;
                        let notFoundTemp = false;

                        responseData = response.data;
                        responseData.forEach(function(elementData) {
                            keys = Object.keys(elementData);
                            keys.forEach(function(elementKey) {
                                if(criteria[elementKey] != "" && criteria[elementKey] != null && criteria[elementKey] !== undefined){
                                    if(elementData[elementKey] != "" && elementData[elementKey] != null){
                                        if((typeof elementData[elementKey] != "number" && elementData[elementKey].indexOf(criteria[elementKey]) > -1) ||
                                            (typeof elementData[elementKey] != "string" && elementData[elementKey] == criteria[elementKey])){
                                            res.push(elementData);
                                            responseData = res;
                                            notFoundTemp = false;
                                        }else{
                                            notFoundTemp = true;
                                        }
                                    }
                                }
                                if(notFoundTemp){
                                    notFound = true;
                                }
                            }, this);
                        }, this);

                        if(res == "" && !notFound){
                            res = responseData;
                        }

                        d.resolve(res);
                    });
                    return d.promise();
                },
```
