### ISSUE TITLE
refreshing grid with 'auto' width shrinks by 2px

### ISSUE THREAD

**Issue by snemarch** [tabalinas/jsgrid#307]
When refreshing a grid with width set to 'auto', each refresh shrinks the grid width by 2 pixels. This happens regardless of whether the refresh happens because you manually send it a refresh event, re-order column sorting, or the toggle filter/add-new-row rows.

Demo [here](https://jsfiddle.net/stmo5mtf/), tested in Chrome 50 and Firefox 46.0.1, jQuery 1.12.4 + js-grid 1.4.1.

**Comment by tabalinas** [comment]
Hm... Interesting bug. Thank you for the report!

**Comment by AzeemQ1596** [comment]
Hey I think I also ran into the same issue. Doesn't make sense to me. Has this been fixed?
