### ISSUE TITLE
cannot update grid row with 'validate=required' and 'editing=false'

### ISSUE THREAD

**Issue by snemarch** [tabalinas/jsgrid#308]
I have a scenario where some fields are required when adding a new row to the table, but they must not be editable for existing rows. When using the combination of 'validate=required' and 'editing=false' the goal is *almost* achieved, but field validation fails for the 'editing=false' fields. Is this by design or a bug?

Demo [here](https://jsfiddle.net/stmo5mtf/).

**Comment by tabalinas** [comment]
The behavior looks unexpected. Thank you for the report!

**Comment by snemarch** [comment]
I'm currently looking into a solution for this issue.

I've been pondering a couple of different fixes. One was letting the 'required' validator test if the field has editing=false, but this would require giving the validators access to the field definition, as well as the grid (so it could check whether we're inserting/editing) - this would be a major kludge, so that idea was discarded.

Another idea was having **_validateItem()** skip checks if a field has editing=false, a 'required' validator, and we're in edit mode - but that would be a very specific hack, and given the several ways you can choose validators, the code would be ugly.

I believe the best solution is to include the editing=false fields in the edited item. I tried a couple of things, which resulted in errors because editing=false fields don't instantiate a Field object - they only have dumb DOM elements. I think I've found a decent solution, though: let **_getEditedItem()** do a deep object copy from the row's data object, then update fields with the edited versions.

The proposed solution (which can be seen [here](https://github.com/snemarch/jsgrid/tree/feature/edit-required-with-no-editing)) solves my use-case, and doesn't break any existing unit tests. It is kind of an API change, though, since the items now have the editing=false fields included. I think it's an OK solution, though, since the item already include all the (other) fields, not just the ones that have been modified during the edit.

I'm not sure how to write a clean unit test for this, and would like to hear your thoughts before attempting :)

**Comment by tabalinas** [comment]
Let me think about this a bit... 
Thank you for you contribution.
