### ISSUE TITLE
Textarea not working

### ISSUE THREAD

**Issue by jerto1** [tabalinas/jsgrid#31]
Hi,
It seems that the textarea type is not working. I opened the basic.html page, changed the Name field type from text to textarea and nothing is rendered, neither in filter, editing or inserting.
Can you check this issue please ?

**Comment by tabalinas** [comment]
Here is working fiddle created from basic demo where Name field is set to "textarea"
http://jsfiddle.net/tabalinas/z6ffzah5/

Could you provide more information how to reproduce the issue?
Maybe you can change this fiddle to show the problem.

**Comment by jerto1** [comment]
It works now. I add to delete jsgrid.field.textarea.js and upload it again. Maybe it was a bug during the initial  transfer. Anyway thank you for your interest in my problem and congratulations for this great project.

**Comment by tabalinas** [comment]
Thank you! Glad to hear that!
