### ISSUE TITLE
Refresh content

### ISSUE THREAD

**Issue by darklinki** [tabalinas/jsgrid#310]
Not sure if its a bug.

I try to reload the content on filtering. This works fine if I recall createGrid() after filtering. 

The problem is, I dont want to recreate the grid, I just want to update the content. While recreating, I loose the user filter input.

$("#grid").jsGrid("refresh"); seems to do nothing. 

Any workaround ?

**Comment by stephenlawuk** [comment]
Filtering should refresh your data automatically if you are using the controller load data part to do your filtering and you are returning the data via a jquery promise. You can see examples on http://js-grid.com/demos/

So below would have the data filtered by the results=40 and the success function is the filtered results coming back.
```
        controller: {
            loadData: function() {
                var deferred = $.Deferred();
 
                $.ajax({
                    url: 'http://api.randomuser.me/?results=40',
                    dataType: 'json',
                    success: function(data){
                        deferred.resolve(data.results);
                    }
                });
 
                return deferred.promise();
            }
        },
```

**Comment by darklinki** [comment]
Actually I dont want to use the prebuild controlers, cause my filtering request are kinda complicated with many mysql join statements. But I will try to insert my ajax request in the controller.

**Comment by darklinki** [comment]
Ok it worked, just had to change a small thing. 

 deferred.resolve(data.results); -> deferred.resolve(data);

Cause the object I´m retrieving is already the final result. 

Now I just jave to find out how to stop it getting called automaticly on pageopening.

**Comment by tabalinas** [comment]
Are you sure `autoload` config option is `false`? http://js-grid.com/docs/#autoload-default-false

**Comment by darklinki** [comment]
Ty set autoload to false, now its working.
