### ISSUE TITLE
case insensitive search

### ISSUE THREAD

**Issue by julmot** [tabalinas/jsgrid#312]
When searching for "connor" I expect "Connor Johnston" to be found:
![connor](https://cloud.githubusercontent.com/assets/8310677/15999558/dec61374-3146-11e6-9452-1d242e4334ca.png)
But what I get is:
![get](https://cloud.githubusercontent.com/assets/8310677/15999565/e93023fe-3146-11e6-8c45-2405c2f21ec3.png)
I may have missed something, but I didn't find any option in the documentation after searching for "case" and "sensitive". 
I furthermore expect a case insensitive search by default.

**Comment by tabalinas** [comment]
Please, checkout this issue https://github.com/tabalinas/jsgrid/issues/258.

**Comment by julmot** [comment]
@tabalinas Sorry, I don't have time to dig into this. I was looking for a simple sentence about this in the documentation. But this sentence helped me:

> Nope, the data filtering logic is on the developer shoulders for the sake of flexibility and simplicity.

Seems like jsgrid isn't what I am looking for.

**Comment by tabalinas** [comment]
Well, of course it depends on what you are looking for. But not sure why adding a `$.grep` in a single function on the client or filtering on the server-side is a game changer.
