### ISSUE TITLE
filter by search input on keypress

### ISSUE THREAD

**Issue by julmot** [tabalinas/jsgrid#313]
To improve usability and user experience it would be great to be able to see search results on keypress like on [DataTables](https://datatables.net/).

**Comment by tabalinas** [comment]
For now you can reach this redefining text field `filterTemplate` like the following:

```js
jsGrid.fields.text.prototype.filterTemplate = function() {
            var grid = this._grid;
            var $result = jsGrid.fields.text.prototype.filterTemplate.call(this);
            $result.on("keyup", function(e) {
                  // TODO: add proper condition and optionally throttling to avoid too much requests  
                  grid.search();
            });
            $result;
        },
```

For example you can use the following handling: http://jsfiddle.net/82sTJ/1/

**Comment by 7654098** [comment]
Hi, Tabalinas. Could you please advise, where this code has to be placed? Using this code, can I listen all keyup event in every filter fields in jsgrid?

**Comment by ferrarisebastian** [comment]
Hello, how ignore uppercase or lowercase ?
this function OK?

  $('.jsgrid-filter-row').find('input[type=text]').on("keyup", function (e) {
            $("#jsGrid").jsGrid("search");
        });

Thanks.

**Comment by dgriebel2014** [comment]
I'm running Angular, and therefore have access to $timeout, but this could be adjusted to accommodate non-angular apps.  If another key is pressed while there's a pending $timeout, that $timeout is cancelled and a new one is started.  I couldn't get keyup to fire when the filter input is completely cleared, but this seems to cover that as well.

```
// makes jsGrid apply filters after a 500 second debounce
$timeout(function () {
    $('#jsGrid :input').keydown(function () {
        var self = this;

        if (self.timeoutPromise)
            $timeout.cancel(self.timeoutPromise);

        if (self.value.length == 0)
            $('#jsGrid').jsGrid('loadData');

        self.timeoutPromise =
            $timeout(function () {
                $('#jsGrid').jsGrid('loadData');
            }, 500);
    });
});

```
