### ISSUE TITLE
pagerFormat

### ISSUE THREAD

**Issue by gatmeister** [tabalinas/jsgrid#315]
Hi all,

I have two external pagers (top and bottom) and I'm using a div to place it where I want like so. 
It all works fine (top and bottom)

Top pager: 
		pagerFormat: " {itemCount} results {prev} {pages} {next} "

I wanted the bottom pager to just show {prev} {pages} {next} without the {itemCount}
But I can't customize it as such when I manipulate it on onDataLoaded via a function

My question is: is jsGrid customizable as such?

**Comment by tabalinas** [comment]
Hi,

Since you have only single `pageFormat` by default both pagers will have the same format. What you could do is to change the one pager in `onRefreshed` callback (find the element with jQuery and just change its content).

**Comment by gatmeister** [comment]
Hmmmm. So onRefreshed do I initialize pagerContainer, pagerFormat again without the {itemCount} results? Cause changing the jsgrid-pager class without the results (and just the pager) is not working

**Comment by gatmeister** [comment]
One ugly hack:

onRefreshed: function(){
	   $('.pager').find('div.jsgrid-pager:not(.jsgrid-pager-page .jsgrid-pager-current-page)').css( "color", "transparent" );
	  }

or however you want the {itemCount} to be hidden

**Comment by tabalinas** [comment]
Yes, something like that. Glad that you figured it out.
Agree this is a big hacky, but the scenario is also pretty custom.
