### ISSUE TITLE
Hide expand/collapse row by click

### ISSUE THREAD

**Issue by eugeniotcs** [tabalinas/jsgrid#316]
It's possible expand/collapse column and use rowClick to show another data? (Like subGrid)

**Comment by tabalinas** [comment]
You can achieve this with custom `rowRenderer`. Please see this basic example http://jsfiddle.net/tabalinas/vc1wm99n/

**Comment by djdance** [comment]
hello, the example won't work now.
(this one is working though http://jsfiddle.net/9ftwLsmf )
