### ISSUE TITLE
sort data with date data type

### ISSUE THREAD

**Issue by Lobador** [tabalinas/jsgrid#319]
Hi,

I cannot sort data which has dateformat is DD/MM/YYYY

If possible, can you share an example about this?

Thanks in advance.

PS: I have created a new type which is called GridDate but it doesnt work properly. You can see my data type in below.

My Code:
```js
var GridDate = function (config) {
    jsGrid.Field.call(this, config);
};

GridDate.prototype = new jsGrid.Field({
    sorter: function (date1, date2) {
        return new moment(date1, 'DD/MM/YYYY').format('DD/MM/YYYY') - new moment(date2, 'DD/MM/YYYY').format('DD/MM/YYYY');
    },

    itemTemplate: function (value) {
        return new moment(value,'DD/MM/YYYY').format('DD/MM/YYYY');
    },


});

jsGrid.fields.GridDate = GridDate;
```

**Comment by tabalinas** [comment]
Find different sorting functions with moments here: http://jsfiddle.net/davidhooey/29dbLo1w/
