### ISSUE TITLE
Is there a way to set the content of a filter programmatically?

### ISSUE THREAD

**Issue by pineliu** [tabalinas/jsgrid#320]
I want to dynamically add some filter values and show them in the filter inputs. Is there a way that I can get a reference of the inputs so that I can set the values programmatically? Thank you very much!

**Comment by tabalinas** [comment]
Yes, you can like the following:

```js
var fields = $("#jsGrid").jsGrid("option", "fields");
var $filterControl = fields[indexOfTheField]._filterControl();
$filterControl.val("my filter value");
```

**Comment by pineliu** [comment]
Thanks a lot!
