### ISSUE TITLE
How to add context menu to the header?

### ISSUE THREAD

**Issue by pineliu** [tabalinas/jsgrid#321]
Is there a way that I can add the context menu to the header so that it uses a different menu compared to the table? Thank you very much!

**Comment by pineliu** [comment]
Find a walk-around: $("#gridID > .jsgrid-grid-header").contextmenu(function(e){console.log(e);return false;})

But if there is a built-in function to get the header reference, that will be preferable. Thank you!

**Comment by tabalinas** [comment]
Grid field has an option `headercss` which specifies the css class to be attached to the header cell.You can use it.
Anyway, doing it by row selector is also fine, you can redefine the grid option `headerRowClass: "my-context-menu  jsgrid-header-row"`, and then use your `my-context-menu` class to attach the handler.
