### ISSUE TITLE
data: visible: false, field doesn´t exist

### ISSUE THREAD

**Issue by darklinki** [tabalinas/jsgrid#322]
Hello,

thanks for your help in my previous question. This time I found a real issue :) 

If i set a field to visible false, it doesn´t show up in DOM.

{ name: "ArtikelID", type: "number", visible:false}

So it should be actually named "activated" instead of "visible". 

My problem is I´m trying to store data in the DOM. Any workaround idea ?  (width: 0, does not work :D )

**Comment by darklinki** [comment]
workaround:

```
{ name: "ArtikelID", type: "number", css:invisible }

invisible {
    display: "none";
}
```

**Comment by tabalinas** [comment]
Could you provide a jsfiddle showing the problem? 
You can fork this one https://jsfiddle.net/tabalinas/kL291xp5/

**Comment by darklinki** [comment]
https://jsfiddle.net/doomenik/fhzuqvmm/4/

The td doesn´t exist under the DOM.

**Comment by tabalinas** [comment]
The fiddle looks correct: grid has 3 columns as expected. What do you think is wrong about it?

**Comment by darklinki** [comment]
https://jsfiddle.net/doomenik/fhzuqvmm/6/

If the visible is set to false, there are correctly only 2 columns. But the problem is that the element is not just invisible, it is deleted.

Look under "Inspect element" and you wont find any td for that column.

**Comment by tabalinas** [comment]
Yes, `visible` in this case has nothing to do with css visibility. And what's wrong with this?

**Comment by darklinki** [comment]
I would like to store data in a field thats not visible. I also want to search/filter with the informations in this field. But bot wont work if the field just does not get created.

If you ask me, it shouldn´t delete the field, it should just hide it.

But anyway there is the workaround with css, its not that nice but It works.

**Comment by tabalinas** [comment]
The option with css is not a workaround, it's a way to make your scenario working.
Using particular grid implementation would be the wrong solution. You should not care about implementation. What if it will change one day... 
Technically a field is not visible in the grid, and it shouldn't matter how it's done. Again there is no correlation between css visibility.
