### ISSUE TITLE
Problems in render grid and show registers after insert

### ISSUE THREAD

**Issue by wagneranselmo** [tabalinas/jsgrid#324]
Hi, i need your help!
My grid not correctly render after show and after insert register.
Only render when clicked a header column for sort or other event...

Detail: I save all register at once, and not each insert!

**My code:**

```js
   $("#jsGrid").jsGrid({

            width: "100%",
            height: "85%",
            autoload: true,
            inserting: true,
            editing: true,
            sorting: true,
            paging: false,
            selecting: true,
            filtering: false,
                                   
            controller: {
                loadData: function(filter) {
                    return $.ajax({ 
                         type: "GET", 
                         url: "dataasync?t=listitensprices&id=" + dados.idTabela, 
                         data: filter, 
                         dataType: "json" 
                    }); 
                },
                
                insertItem: function(item) { 
                    
                    
                }, 

                updateItem: function(item) { 

                }, 

                deleteItem: function(item) { 
                 
                } 
                
            },

            fields: [
                { type: "control", width: 70 },
                { name: "intIdItemTabela", type: "number", width: 0, visible: false},
                { name: "intIdTabela", type: "number", width: 0, visible: false },
                { name: "strFomato", type: "select", items: formatos, title: "Formato", valueField: "valor", textField: "nome", width: 70, sorting: true, filtering: true },
                { name: "strCor", type: "select", items: cores, title: "Cor", valueField: "valor", textField: "nome", width: 70, sorting: true, filtering: true },
                { name: "strTipoPapel", type: "select", items: papel, title: "Papel", valueField: "valor", textField: "nome", width: 100, sorting: true, filtering: true },
                { name: "intTiragemDe", type: "number", title: "Tiragem de", sorting: false, width: 70, filtering: false },
                { name: "intTiragemAte", type: "number", title: "Tiragem até", sorting: false, width: 70, filtering: false  }
            ],

            rowClick : function(args) {

                return;
            },
            
            rowDoubleClick : function(args) {
                this.editItem(args.item);
            },
            
            onItemInserted : function() {
                
            }

        });
```
**Grid first render :**

![issues_jsgrid1](https://cloud.githubusercontent.com/assets/20070617/16240861/8121ed70-37c1-11e6-8491-427e2f54cd4a.png)

**Grid after click in header column sort:**
![issues_jsgrid2](https://cloud.githubusercontent.com/assets/20070617/16240952/ea41d112-37c1-11e6-9b37-08146f409efd.png)

**Grid after insert register**
![issues_jsgrid3](https://cloud.githubusercontent.com/assets/20070617/16240971/fd4f2926-37c1-11e6-9850-3ede0b5c68f1.png)

Tks for help!

**Comment by tabalinas** [comment]
I believe it happens due to `width: 100%`, but not sure why exactly. It could be influenced by the container styles.
Could you provide a jsfiddle to show the problem (fork this one https://jsfiddle.net/tabalinas/kL291xp5/)?

**Comment by wagneranselmo** [comment]
Ok tks... I'm going topost my code in jsfiddle. The problem of first image, has resolved with a sleep time after set data for grid (I use java for backend) and it worked!!!

But the problems after insert (image 3) continue... I need click, for example, on button plus in header line for render grid and show all data.

Tks .. i wait a possible solution!

Congratulations for jsGrid !!!

**Comment by mestrini** [comment]
Sorry for (sort of) hijacking the issue but I think I'm in a similar situation regarding the first rendering of the grid.
In my case the jsGrid lives in a jQuery UI tab which is hidden at start and the jsGrid core uses outerWidth() in _refreshWidth: function() (around line 875) to adjust the $bodyGrid width to the $headerGrid's. Problem is the outerWidth() shouldn't be used when elements are hidden as per jquery documentation.
_

> The value reported by .outerWidth() is not guaranteed to be accurate when the element or its parent is hidden. To get an accurate value, ensure the element is visible before using .outerWidth(). jQuery will attempt to temporarily show and then re-hide an element in order to measure its dimensions, but this is unreliable and (even when accurate) can significantly impact page performance. This show-and-rehide measurement feature may be removed in a future version of jQuery.

_ 
 
I noticed this because after sorting the columns via column header, the grid would render just fine with all the columns aligned with their headers and the height also adjusted to the containers height.

I edited the script to use offsetWidth which is exposed in the $headerGrid object and so far it has been working fine. I'll try to do the same with the height.

tx for the plugin.

**Comment by mestrini** [comment]
To avoid breaking the plugin's functionality by commenting instructions, and since I don't have time to go through all the source, I ended up by calling a `jsGrid("refresh") ` on tab activating which works fine since the grid is already visible.
tx

**Comment by tabalinas** [comment]
@mestrini: you are right, calling `refresh` when grid is rendered is a proper solution in this case.
