### ISSUE TITLE
how to set width for column to horizontal scroll when there are a lot of columns

### ISSUE THREAD

**Issue by amin750** [tabalinas/jsgrid#325]
i have a lot of column in grid and i want to horizontal scroll, but the header row and data row scroll together,how can i do it?

**Comment by tabalinas** [comment]
The horizontal twin scrolling of the header and body is done on purpose, not sure what exactly you don't like about it.

**Comment by amin750** [comment]
yes that's rightو i change overflow on the grid and it was cluttered
