### ISSUE TITLE
adding row numbers in the grid

### ISSUE THREAD

**Issue by gatmeister** [tabalinas/jsgrid#326]
I'm trying to add a row number for each row item. 
I can get the itemIndex using 

`$("#grid").jsGrid({
    rowClass: function(item, itemIndex){
                 }

})` 

I'm not sure how to put two and two together as I am creating the column for the row numbers under
fields: [], (i.e) 

`fields: [
       {name: "#", title: "#",
    	   itemTemplate: function(){
    		   //increment
    	   }
		},`

It increments fine going forward the pageIndex via a pager but when I go back to a previous pageIndex, it would still increment which is wrong.

How do I correctly add the row numbers? :)

**Comment by tabalinas** [comment]
I guess the easiest way would be just to map your data on the client adding a specific field (e.g. `index`) to the data themselves in `controller.loadData` function. And then bind this `index` field to the field of the grid.

**Comment by inalpolat** [comment]
Have a global variable ie rowNum :
    var rowNum = 0;
....
...

Then when initializing table add a field :

fields: [
                {
                    title: "#", type: "number", itemTemplate: function (value, item) {
                        rowNum += 1;
                        return rowNum;
                    }
                }, ......
            
Finally, reset this variable on each refresh (like sorting etc)
            onRefreshed: function (args) {
                rowNum = 0;

**Comment by sms71790** [comment]
may be 
    itemTemplate:function(value, item){
      return this._grid.data.indexOf(item) + 1;
    }
simple, not need var rowNum ...
