### ISSUE TITLE
Edit field in out of grid

### ISSUE THREAD

**Issue by amin750** [tabalinas/jsgrid#327]
how can i edit fields out of grid and then update it?

**Comment by tabalinas** [comment]
I didn't get the question. What do you exactly mean?

**Comment by amin750** [comment]
i have input fields out of grid and  inside a div element corresponding with grid field 
i want when click edit in row, the row item fill in the my input and when i change the values and then click button with name save update item in row and database.

note: now  return function  to rowClick for other use
thank you for helping me.

**Comment by tabalinas** [comment]
You could add a field with a button inside. On the click on the button you will fill your external fields with the data from the item. Then on the external button 'Save' click you just call `updateItem` method of the grid (http://js-grid.com/docs/#updateitemitemrowrownode-editeditem-promise).
