### ISSUE TITLE
Refresh grid after delete

### ISSUE THREAD

**Issue by negys** [tabalinas/jsgrid#328]
Hi. Pulling my hair out here. The grid does not refresh after calling the deleteItem controller method.
```js
           deleteItem: function(item) {
                var csrf_val = $('#anytime_booking_csrf').val();
                return $.ajax({
                    type: 'POST',
                    url: '/expense/remove/',
                    data: { id: item.id, anytime_booking_csrf: csrf_val },
                    dataType: 'json'
                });
            }
```
Should it refresh automatically?
I've also tried calling **jsGrid('removeItem', item)** but nothing happens.

Can you advise?

Thanks.

**Comment by negys** [comment]
I think it by abandoning deleteItem and using onitemDeleted instead.

onItemDeleted: function(args) {
            var item_id = parseInt(args.item.id, 10);
            var csrf_val = $('#anytime_booking_csrf').val();
            $.ajax({
                type: 'POST',
                url: '/expense/remove/',
                data: { id: item_id, anytime_booking_csrf: csrf_val },
                dataType: 'json'
            });
        },

**Comment by tabalinas** [comment]
`deleteItem` should be defined in the controller method. `onItemDeleted` is just a callback to handle event when an item is deleted. http://js-grid.com/docs/#controller
So it should be 

```js
controller: {
    ...,
    deleteItem: function(item) {
        // your ajax call here
    }
}
```
