### ISSUE TITLE
Disable "Delete" option

### ISSUE THREAD

**Issue by skygen007** [tabalinas/jsgrid#33]
Hi. Is there any way to disable "Delete" option ?

**Comment by tabalinas** [comment]
Not sure what you mean by "Delete" option, but if you talk about `control` field, you can hide delete button with following config option: 

```javascript 
{ type: "control", deleteButton: false }
```

Thus a user won't have ability to delete item from UI.

**Comment by rdksgit** [comment]
Hi tabalinas,
Is there a way to disable the delete option on a particular condition, i can do that for editing but the delete option is still active
check is coming through a ajax call and i want to disable the form when it is 1
if(check==1){
  $("#jsGridCommercial").jsGrid({
                editing: false,
                inserting: false
            });
}

Thanks
Sameer
