### ISSUE TITLE
Is it possible to config auto reload interval?

### ISSUE THREAD

**Issue by melson-jao** [tabalinas/jsgrid#331]
Hi, 

This is not a bug but asking for some help.
Everything is great. After I enable autoload is true, it is fine to autoload data periodically.
But I want to know is it possible to config the autoload interval, ex 30s or 1min?
I check the documents but no related config is found.
Any response is appreciated. Thanks.

**Comment by tabalinas** [comment]
Hi,

The option `autoload` tells to load data  right after grid rendering. It happens only once.
If you need to reload data periodically use `setTimeout` and call `loadData` method, then on `done` of the method schedule another reload with `setTimeout`, and so forth.

**Comment by melson-jao** [comment]
Appreciate for the quick and clear response.
Sorry for my mistake without checking the exact meaning of autoload.
Thanks again.

**Comment by tabalinas** [comment]
You are welcome!
