### ISSUE TITLE
Function of Cancel Button in Jsgrid

### ISSUE THREAD

**Issue by hoanglap3011** [tabalinas/jsgrid#332]
Hi, i don't know ask anywhere for my problem. so, hope you help me!

in function callback, example 
onItemInserting: function (args) {
// my content
},
i will check a few conditions and if don't satisfy, i wanto cancel insert. so, i need know function of cancel button.
can you help me?
thank you very much!

**Comment by tabalinas** [comment]
For canceling, please see Cancel item insetion in the docs: http://js-grid.com/docs/#oniteminserting
But you could also consider using the built-in validation.

**Comment by hoanglap3011** [comment]
1. In the case of the above I ask not to be clear and effective
I should have asked is worth in case the update not insert
but anyway thank you for your help, from which I learned how to handle similar
but there is one other problem.
for example, I use the command:
```
    onItemUpdating: function (args) {
        if (args.item.name === "") {
            args.cancel = true;
            alert ( "Specify the name of the item!");
        }
    }
```
of course, when I hit the update, I will receive the alert and that cell will not be updated, but the problem here is that data cells remain in a state of repair. I wanted to escape from the cell data correction status (as when I hit the cancel button)

in addition I have a few other problems, look forward to your help:
2. I'm having problems with the search box select.
examples like this
`<div id="div1"></div>
<div id="click">
    Click here to load again table
</div>

<script>
$(document).ready(function () {
	loadTable();
	$( "#click" ).click(function() {
        loadTable();
    });
});

function loadTable(){
	$.ajax({
		type: 'POST',
		url: url, // something
		data: params, // something
		dataType: 'json',
		async: false,
		success: function (data) {
			var obj = JSON.parse(data.value);
			db.clients = obj[0];
			db.countries = obj[1];
		},
	});
 
	//when I console.log in here then obtained db.clients and db.countries correctly

	$("#div1").jsGrid({
		height: "70%",
		width: "100%",
		filtering: true,
		editing: true,
		sorting: true,
		paging: true,
		autoload: true,
		inserting: true,
		controller: db,
		fields: [
            { name: "Name", type: "text", width: 150 },
            { name: "Age", type: "number", width: 50 },
			{ name: "Address", type: "text", width: 200 },
			{ name: "Country", type: "select", items: db.countries, valueField: "Id", textField: "Name" },
			{ name: "Married", type: "checkbox", title: "Is Married", sorting: false },
			{ type: "control" }
		],
	});
}
</script>
`
when I opened the first page ($ (document) .ready ...), everything is normal
but when I click on "Click here to load again table", select the search box disappears
I've tried setting async: false and async: true, but were unsuccessful. what should I do?

3.I build multiple tables in one display page. I will draw table t2 using the t1 rowclick function like this 
`<div id="div1"></div>
<div id="div2"></div>


<script>
$(document).ready(function () {
	loadTable1();
});

function loadTable1(){
	$("#div1").jsGrid({
		height: "70%",
		width: "100%",
		filtering: true,
		editing: true,
		sorting: true,
		paging: true,
		autoload: true,
		inserting: true,
		controller: db1,
		fields: [
            { name: "Name", type: "text", width: 150 },
            { name: "Age", type: "number", width: 50 },
			{ name: "Address", type: "text", width: 200 },
			{ name: "Country", type: "select", items: db1.countries, valueField: "Id", textField: "Name" },
			{ name: "Married", type: "checkbox", title: "Is Married", sorting: false },
			{ type: "control" }
		],
		rowClick: function (args) {
			var name = args.item['name'];
			loadTable2(name);
        },
	});
}

function loadTable2(name){
	db2.clients = someThingFunction(name); // ok
	$("#div1").jsGrid({
		height: "70%",
		width: "100%",
		filtering: true,
		editing: true,
		sorting: true,
		paging: true,
		autoload: true,
		inserting: true,
		controller: db2,
		fields: [
            { name: "Name", type: "text", width: 150 },
            { name: "Age", type: "number", width: 50 },
			{ name: "Address", type: "text", width: 200 },
			{ name: "Country", type: "select", items: db1.countries, valueField: "Id", textField: "Name" },
			{ name: "Married", type: "checkbox", title: "Is Married", sorting: false },
			{ type: "control" }
		],
	});
}
</script>
`
(depending on the row of t1 that I will load the corresponding data into tables t2)
the problem is when I'm on page 2 of t2 and I click on any row of data t1 which corresponds to that item only in one page, the page still displays t2 2 (a state memory format). so no data will be displayed on t2
How should I handle?

**Comment by tabalinas** [comment]
Please, open separate issues for 2nd and 3rd points.

**Comment by hoanglap3011** [comment]
thank you and first problem?

**Comment by tabalinas** [comment]
Gonna be also answered, as you see I reopened the ticket.

**Comment by tabalinas** [comment]
In this case just call method [`cancelEdit`](http://js-grid.com/docs/#canceledit)
