### ISSUE TITLE
reset sorting

### ISSUE THREAD

**Issue by AngeleMM** [tabalinas/jsgrid#333]
Hi.
I need to reset the table sorting, after sorting the table,  but I can't find any info about that, and in the documentation I can not find it too.
Can you please help me?

**Comment by tabalinas** [comment]
You could call `reset` method (but with sorting it will reset also the pager).
If you want to preserve paging you could go for a workaround and call a private method `_resetSorting` like this `$("#jsGrid").jsGrid("_resetSorting");`.
