### ISSUE TITLE
validation highlighting cell in wrong column if exists field with visibility 'false'

### ISSUE THREAD

**Issue by mestrini** [tabalinas/jsgrid#334]
I opted for using two fields of type "control", one at the left hand side of the grid and the other at the opposite end but, as mentioned in the title, when validation fires the wrong cell receives the css changes.

see picture please:
![validator1](https://cloud.githubusercontent.com/assets/8707565/16415160/ca026c28-3d33-11e6-98c6-3b616d539c30.png)

please note that issue happens even if using only one control on the left hand side

tx

**Comment by mestrini** [comment]
I think I've pinned the reason for this behaviour and it is the fact that I have a **hidden** field.
Once I remove it, the css highlighting works on the correct cell/column again.

Is there a way to overcome it or am I doing it wrong?

tx

**Comment by tabalinas** [comment]
Yes, thank you for the report.
This issue is fixed already https://github.com/tabalinas/jsgrid/issues/226
But pending to be released (it's gonna be very soon).
