### ISSUE TITLE
Problem when inserting with two check box

### ISSUE THREAD

**Issue by iamdatvt94** [tabalinas/jsgrid#336]
you can see my picture to see the my problem.
I wanna select value in combobox "Tên kế hoạch", and the value in combobox "Tên đơn vị" will load by my query in database.
How can i get acton when i click to select value in the combobox when i inserting?
![new bitmap image](https://cloud.githubusercontent.com/assets/18534522/16448107/eedddad2-3e19-11e6-97fa-0ace16b3b116.jpg)

**Comment by tabalinas** [comment]
Please, see the following issue with the similar problem https://github.com/tabalinas/jsgrid/issues/71
In this issue is mentioned a demo with the dependent selects in the inserting row: http://jsfiddle.net/tabalinas/n982uvx1/13/

**Comment by iamdatvt94** [comment]
Thanks for your answer. but It is the other problem with me. I wanna INSERT an item use many combobox. Your suggest is SEARCH an item?

**Comment by tabalinas** [comment]
Not sire I understand. In you example I see two comboboxes, just like the example I provided. And they should be bound, meaning values of one depending on another, again this is what my example is about.
