### ISSUE TITLE
"done is not a function" after render method

### ISSUE THREAD

**Issue by fanturi** [tabalinas/jsgrid#34]
Hi,

I have a problem with the render method.
When I want to execute something after that with a done method like your example I have this error message : Uncaught TypeError: $(...).jsGrid(...).done is not a function

Any ideas ?

Thanks.

**Comment by tabalinas** [comment]
Maybe you call method that doesn't return Promise?
Provide more details about what method you call.

Here is the  fiddle with `search` method that alerts on `done` of search.
http://jsfiddle.net/tabalinas/aa2Ljyfu/

```javascript
$("#search").click(function() {
    $("#jsGrid").jsGrid("search").done(function() {
        alert("search done!");
    });
});
```

You can modify the fiddle to show the issue.

**Comment by fanturi** [comment]
Arg ! forget about it I made a mistake with the name of the container...
sorry !

**Comment by tabalinas** [comment]
Glad you figured it out!
