### ISSUE TITLE
Call loadData from javascript to initialize data contents

### ISSUE THREAD

**Issue by baresw** [tabalinas/jsgrid#340]
Hello, 

We would like to be able to dynamically initialize the js grid table data from javascript by calling the loadData method.  We would like to be able to call loadData multiple times to refresh the database and have each call to loadData clear existing table data before filling the new entries.  We have tried several different approaches with try 3 being able to insert items singly, but unable to clear the table contents.

try 1: Initialize items whose attributes match the js grid's defined fields.  Bundle list and itemsCount 
before passing to loadData method.  This has no effect.  The table remains empty.
```js
var itemList = [ { "Name": "Jane", "Color": "blue" }, { "Name": "Mike", "Color": "red" } ];
// format data as suggested by documentation for loadData method.
var dataArg = { data: itemList, itemsCount: itemList.length };
$("#grid").jsGrid("loadData", dataArg);
```

try 2: Initialize items whose attributes match the js grid's defined fields.  Pass list directly to loadData.  This has no effect.  The table remains empty.
```js
var itemList = [ { "Name": "Jane", "Color": "blue" }, { "Name": "Mike", "Color": "red" } ];
$("#grid").jsGrid("loadData", itemList );
```

try 3: Call insertItem for each item.  This approach works to first fill the table, but subsequent applications of this approach continue appending to the existing table contents with no apparent way to clear the contents before inserting the next set of items.
```js
var itemList = [ { "Name": "Jane", "Color": "blue" }, { "Name": "Mike", "Color": "red" } ];
$("#jsGrid").jsGrid("insertItem", itemList[0]);
$("#jsGrid").jsGrid("insertItem", itemList[1]);
```

We tried calling methods destroy() and refresh() methods to clear the contents before making the insertItem calls, but neither of these methods are intended to clear only the data contents.

We defined the loadData method of our controller following the style of the examples.

```js
        loadData: function(filter) {
            return $.grep(this.clients, function(client) {
                return (!filter.Name || client.Name === filter.Name) &&
                           (!filter.Color || client.Color === filter.Color);
            });
        },
```

We also set the pageLoading true in $("#jsGrid").jsGrid({ ...	pageLoading: true,

Any suggestions would be appreciated.

thank you

**Comment by tabalinas** [comment]
Hello,

for the try1 and try2 (try3 is a hack):
`loadData` accepts not items, but filter plain js object. It calls `controller.loadData`.

```js
$("#grid").jsGrid({
  controller: {
    loadData: function(filter) {
      return { data: itemList, itemsCount: itemList.length };
    }
  }
});
```

So you can put client-side filtering directly to `loadData`. But more usual is to filter on the server and in `loadData` send ajax request to the server providing filter.
