### ISSUE TITLE
Multiple checkbox filtering (filter to more than one value per column)

### ISSUE THREAD

**Issue by CBuntrock** [tabalinas/jsgrid#343]
Hello everyone,

I need to filter a column in an excel-way allowing to show more than one value. Currently filtering only allows one value to filter on the grid. It should have checkboxes in the dropdown to allow selecting the values that should be shown (showing a distinct list of all values in the column). Similar to excel or other spreadsheets. Is this planned? If not, I would starting implementing this as I need it for an upcoming project.

Thanks!
Best,
Christian

**Comment by soul3lade** [comment]
Hello,

You could create your own custom field.  With that you could override the filterTemplate value and have it return what you are looking for.  As far as having a multi select dropdown, I have used the Chosen plugin with great success before, you could try implementing that.

http://js-grid.com/docs/#custom-field

https://harvesthq.github.io/chosen/

**Comment by CBuntrock** [comment]
Hi & thanks!
I think I don't need a custom field here because from my point of view all the default fields should be fine. I just need to be able to select multiple values per column to show at the same time when filtering. I am not sure if we are talking about the same thing here. I think about excel-like behavior.

Best,
Christian

**Comment by tabalinas** [comment]
Hi @CBuntrock, the way to go could be just redefine `filterTemplate` of existing fields (and `filterValue` to return filtering values). As for the multiselect control you can pick up chosen (as @soul3lade proposed) or select2, here is the good comparison https://www.sitepoint.com/jquery-select-box-components-chosen-vs-select2/

**Comment by KateK** [comment]
Hello!

I would like to make multiple filtering with select2. In this case I have a list of values in `filterValue`. Could you tell me how to handle with this?

Regards,
Kate

**Comment by HelloTweety** [comment]
> Hello everyone,
> 
> I need to filter a column in an excel-way allowing to show more than one value. Currently filtering only allows one value to filter on the grid. It should have checkboxes in the dropdown to allow selecting the values that should be shown (showing a distinct list of all values in the column). Similar to excel or other spreadsheets. Is this planned? If not, I would starting implementing this as I need it for an upcoming project.
> 
> Thanks!
> Best,
> Christian

**Comment by HelloTweety** [comment]
Hi, Did you find solution for this ?
If yes, Can you please paste the code for Loading filter data
Thank you
