### ISSUE TITLE
How to display the combo box to searching an item when I reload js-gird table?

### ISSUE THREAD

**Issue by iamdatvt94** [tabalinas/jsgrid#344]
Hi!
I have a problem with the js-grid table. I load the page the first time and it display sucessful with the combo box can search an item.
![new bitmap image](https://cloud.githubusercontent.com/assets/18534522/16674731/608714ec-44e5-11e6-882d-35ae65920164.jpg)
Then, i do something with the data and need to reload the table. And the combo box is disappear: 
![new bitmap image 2](https://cloud.githubusercontent.com/assets/18534522/16674753/9919589c-44e5-11e6-848c-cf9395d0b7a8.jpg)
If I press F5 to reload the page, it will display sucessful.
Can you help me?
Thanks so much!

**Comment by tabalinas** [comment]
Could you provide a jsfiddle showing the problem?

**Comment by tabalinas** [comment]
Close due to inactivity.
