### ISSUE TITLE
Passing array as property to custom field is passing the wrong data

### ISSUE THREAD

**Issue by xtrasimplicity** [tabalinas/jsgrid#345]
Hi,
I've written a custom field which requires that I pass an array of data as a property, which works fine (as long as there is only one column of that type).

However, I've noticed that if I create two columns with my custom field, and pass two separate arrays, both items are passed the **second** column's array.

An example demonstrating this can be found here (Take a look at the Console):
https://jsfiddle.net/xtrasimplicity/h1ewdday

Interestingly, passing strings in this way does not suffer from this issue.

I'll take a look tonight to see if I can come up with a patch for this, and will then submit a PR - but if anyone else has any comments as to whether this is intended, it would be greatly appreciated. :)

Thanks heaps!

**Comment by tabalinas** [comment]
Yes, the reason is `myArray` is in prototype, that's why it's single for all fields of this type. Just remove `myArray` from prototype definition and it will work as expected.

**Comment by xtrasimplicity** [comment]
Aha! Is this intended, or is it a limitation of Javascript's prototype concept? 

It seems a little odd that it works for strings, but not arrays. :)

Thanks heaps, though!

**Comment by tabalinas** [comment]
This is how JS prototypes work. In fact, it's not a limitation, just this kind of by design. As for string vs array difference, once you know how it works it also seems reasonable. String is a primitive while array is a reference type.
