### ISSUE TITLE
"fail" not working

### ISSUE THREAD

**Issue by dangerimp** [tabalinas/jsgrid#348]
I'm creating a controller and on purposefully having it fail to test to make sure that fail does what it should but it doesn't seem to.

Have you tested fail with jquery 3.0.0?

**Comment by tabalinas** [comment]
Yes, I've tested it with jQuery 3.0.0 and 3.1.0, and it seems to work fine.
Maybe it's something specific for your case. Could you provide an example (jsfiddle or in any other way)?

**Comment by tabalinas** [comment]
Close due to inactivity.
