### ISSUE TITLE
Focus and add trigger to row after insert

### ISSUE THREAD

**Issue by hoanglap3011** [tabalinas/jsgrid#349]
After i insert a row, a want to:
+ page show in that row's page (example, i in page 1 and and i add row, row in page 3 and screen must next to page 3)
+ focus (hightlight) that row
+ add trigger, example 'click', to that row
how can i do?
thank you!

**Comment by tabalinas** [comment]
1. To open a particular page use method `openPage`. The page you want to open you can define finding the index of the inserted item reading `data` option and get the index of the page according to the page size.
2. Define the class row with the option `rowClass` http://js-grid.com/docs/#rowclass. Add `isNew=true` property to the inserted item or just redefine `rowClass` so it will add this class by the index of the nwe item.
3. Just redefine `rowClick` http://js-grid.com/docs/#rowclick handler.

**Comment by hoanglap3011** [comment]
Can you tell me more for the question 1 by providing code?
i tried but not effective

**Comment by hoanglap3011** [comment]
oh. i my problem is sovled
total page can obtained by this code:             
`var pageCount = this._pagesCount();`
