### ISSUE TITLE
How should data in promise be formatted?

### ISSUE THREAD

**Issue by jhammer2** [tabalinas/jsgrid#35]
I am trying to use loadData with a promise. However, it does not load theater. I return 1 record for testing and the grid ends up showing 12 pages of blank data. Perhaps I am formatting the data incorrectly? The format that I am returning in the promise is:

{ data: [{"AccountName":"MyAccount","ContactNumber":"111-111-7890","AccountNumber":"123456789","UserName":"JaneDoe"}], itemsCount: [1] }

Is this not correct?

**Comment by tabalinas** [comment]
If you loading data by pages from server (`pageLoading: true`), then you should return data in format

```javascript
{
    data: [items],
    itemsCount: amountOfItems
}

// for your case
{
    data: [{"AccountName":"MyAccount","ContactNumber":"111-111-7890","AccountNumber":"123456789","UserName":"JaneDoe"}],
    itemsCount: 1 // without array
}
```

In most cases it's enough to load all data (usually it works faster for not huge amount of data). In this case just return the array of items.

See following fiddle with two examples http://jsfiddle.net/tabalinas/6690vqaz/

**Comment by jhammer2** [comment]
Thanks for the reply. I tried your suggestion, however it just keeps showing the please wait. When looking in the browser console I see the following error. I am also doing a console.logo on my promise data to see that it is formatted correctly. Any suggestions on how to resolve this?


{ data: [{"AccountName":"MySuperDuperAccount","ContactNumber":"123-456-7890","AccountNumber":"123456789","UserName":"RickyBobby","Password":"FightingChicken","DueDate":"2015-05-20","MonthlyPayment":"100.00"}], itemsCount: 1 }

jsgrid.core.js:492 TypeError: undefined is not an object (evaluating 'this.data.length')

**Comment by jhammer2** [comment]
what I am trying to do is an asynchronous call and returning the data in a promise.

**Comment by tabalinas** [comment]
Please, provide entire grid config. Maybe you could modify my fiddle to demonstrate the problem.

**Comment by jhammer2** [comment]
I have updated your fiddle. However, yo will not see the error due to the DB not existing, but you are able to see the controller code that I am using. Perhaps I am doing something incorrectly there? 


Thanks,
John

**Comment by tabalinas** [comment]
Send me the link to the updated fiddle than

**Comment by jhammer2** [comment]
Here is the link:

http://jsfiddle.net/6690vqaz/1/

**Comment by tabalinas** [comment]
The promise should be resolved an actual JS object, not a string representation

```javascript
feeds = '{ data: ['+feeds+'], itemsCount: '+len+' }';
def.resolve(feeds); // feeds is a string, but should be an object
```

Should be

``` javascript
feeds = {
    data: [items] // provide array, not a string here too
    itemsCount: len
};
def.resolve(feeds);
```

Hope it will help.

**Comment by jhammer2** [comment]
That is very helpful. I am now getting the screen to come up, however the cells are blank. When looking in the browser console I do the javascript object. can you tell if I am loading the object incorrectly? I am putting the array in, but perhaps the format is incorrect?


[Log] Object (roa.js, line 57)
data: Array[1]
0: "{"AccountName":"MySuperDuperAccount","ContactNumber":"123-456-7890"}"
length: 1
__proto__: Array[0]
itemsCount: 1
__proto__: Object


Here is the code that I used to create the object:

function getRecords() {
                                            var feeds = "";
                                            var def = $.Deferred();
                                            var db = window.openDatabase("Database", "1.0", "MyDB", 200000);

                                            db.transaction(function(tx) {
                                            var db = window.openDatabase("Database", "1.0", "MyDB", 200000);
                                           
					     tx.executeSql("SELECT AccountName,ContactNumber FROM BILL_TABLE", [], function(tx, results) {
                                                                    
                                                                    var len = results.rows.length;
                                                                    var feedarray = [];
                                                                    
                                                                    for (var i = 0; i <=len-1; i++) {
                                                                       
									var len = results.rows.length;
                                                                        var roaObj =results.rows.item(0);
                                                                        var jsonString=JSON.stringify(roaObj);
                                           
                                                                        feedarray.push(jsonString);
                                                                    }
									console.log(feedarray);
                
                                                                      feeds = {
                                                                                data: feedarray, // provide array, not a string here too
                                                                                itemsCount: len
                                                                        };
                                                                        console.log(feeds);
                                                                      def.resolve(feeds);
                                                                });
                                            });
                        		    return def.promise();
                			}



Thanks,
John

**Comment by tabalinas** [comment]
You are right, the format of objects in array is incorrect. You provide them as strings, but elements of `data` array should be also js objects. You can see the problem in console, where object is printed in quotes.

**Comment by jhammer2** [comment]
Thanks so much for your help. It is now working for me.

**Comment by tabalinas** [comment]
You are always welcome!
