### ISSUE TITLE
Adding Drop down to JS grid

### ISSUE THREAD

**Issue by SandySindhu** [tabalinas/jsgrid#351]
Hello Tabalinas,

I have a JS grid embedded n acsx page. Columns are added dynamically on run time.

I need to add drop down and lookup for first two columns in the grid.

Please assist.

Sandy

**Comment by Adondriel** [comment]
Have you checked the docs? 
http://js-grid.com/docs/#select
You have to give the field an object/attribute name to bind the value to, and an object/attribute name to bind the text to.

**Comment by SandySindhu** [comment]
Thanks for your response, yes I have checked.
I am adding columns like this - 
  columns.Add(new DataSourceColumn() { ColumnName = GridViewsUtils.NameColumn, Title = GridViewsUtils.NameColumnTitle });

Please assist how can I use that approach in this scenario.

**Comment by tabalinas** [comment]
It seems you mixed up jsgrid with some other component. Just checkout docs, it will be obvious.

**Comment by SandySindhu** [comment]
Sorry , it is a JS grid  and the columns are added on run time. Grid is used in a web part.

**Comment by Adondriel** [comment]
If you are using an ASP to json thing, make sure it is giving back the json in the right format. I notice you use "ColumnName = ___" which, if using a program that serializes that into json, it would turn it into `ColumnName: "___"` which would break the grid, because it looks for the property `name: "___"`

**Comment by SandySindhu** [comment]
Thanks for response, my grid is rendering correctly. I just need to change one of column type in a grid as a dropdown

**Comment by SandySindhu** [comment]
and how can I find the cell id in the row based on the value of other cell

for e.g. if in a row, marks columns >50 , then eligible cell in the row should be non editable

**Comment by Adondriel** [comment]
I don't think you're using your grid correctly... it sounds like your just using a default ASP GridView or something like that...

**Comment by SandySindhu** [comment]
It is JS Grid but not defined in html , it is all build on run time.

What more information you need to provide assistance

**Comment by tabalinas** [comment]
@SandySindhu, there is misunderstanding here: jsGrid (http://js-grid.com) doesn't have properties like `columns`, `DataSourceColumn`, and `ColumnName`. I guess you are talking about JSGrid mentioned here http://www.codeproject.com/Articles/813090/Master-detail-with-JSGrid, just so you know this is completely different component.

**Comment by SandySindhu** [comment]
I am referring to this - https://msdn.microsoft.com/en-us/library/office/ee539027(v=office.14).aspx
