### ISSUE TITLE
how i set range of date in filtering with using two date picker? (such as below img link)

### ISSUE THREAD

**Issue by pichlou** [tabalinas/jsgrid#352]
![mygrid](https://cloud.githubusercontent.com/assets/17822368/16767680/dfb580c8-4855-11e6-89d7-27e14b75febb.PNG)

**Comment by Adondriel** [comment]
depends on where you get your data. I am sure there is a way to filter between dates in javascript though, you would just have to filter your data before returning it to the grid.

**Comment by tabalinas** [comment]
Checkout the answer to the following issue https://github.com/tabalinas/jsgrid/issues/60

**Comment by pichlou** [comment]
Thanks,resolved :)
