### ISSUE TITLE
Integrating with Asp.net MVC

### ISSUE THREAD

**Issue by shefaliA** [tabalinas/jsgrid#354]
Hi,

I am trying to integrate grid with Asp.net MVC Controller. I am unable to pass data from controller to grid and bind it. Can you please provide some sample code.

Thanks

**Comment by shefaliA** [comment]
I added a drop down to add pageSize in UI. And on drop down change function using Jquery ,want to refresh grid with new pageSize . I am using itemCount to update PageSize in grid. Am I doing anything  #wrong?
$(".pagesize").change(function () {
                    console.log("getPageSize");
                    var pageSizeG = $('.pagesize :selected').val();
                    console.log(pageSizeG);
                    $("#jsGrid").jsGrid("itemCount", pageSizeG);                 
                });

**Comment by tabalinas** [comment]
You could set `pageSize` option:

```js
$("#jsGrid").jsGrid("option", "pageSize", pageSizeG);
```

I'm not sure where you get `itemCount` there is no such a method or option.

**Comment by shefaliA** [comment]
@tabalinas

Hi,
I am looking for help to integrate grid with Asp.net MVC. Can you guide me?

**Comment by tabalinas** [comment]
Checkout this sample project showing how to use jsGrid with ASP.NET https://github.com/tabalinas/jsgrid-webapi

**Comment by shefaliA** [comment]
I tried to use $("#jsGrid").jsGrid("option", "pageSize", pageSizeG); but the grid is not refreshing with the new selected page size.

**Comment by tabalinas** [comment]
Have you tried this scenario w/o integration with ASP.NET? To know if this is the issue of jsgrid, or a particular case.

**Comment by shefaliA** [comment]
Yes I did. I am able to get the selected page size in view. Does calling $("#jsGrid").jsGrid("option", "pageSize", pageSizeG); will refresh the grid?

**Comment by tabalinas** [comment]
Yes, it should refresh the grid.
Since you are asking, I'm not sure if you tried it yourself or not. If it's not refreshed, it's a bug. So if you experience this issue, please fork this jsfiddle https://jsfiddle.net/tabalinas/kL291xp5/ with the scenario reproducing the issue.

**Comment by shefaliA** [comment]
I have tried myself. Will fork it
