### ISSUE TITLE
Server validations

### ISSUE THREAD

**Issue by fredericoregateiro** [tabalinas/jsgrid#358]
How can we use this grid with server validations?

Thanks

**Comment by soul3lade** [comment]
Hello,

You would handle server side validation on the server side.  When you Insert/Edit/Delete a row you can use whatever backend system you are using to validate the results.  Then if there are issues you can send those back to the client.

Perhaps if I knew what backend system you were targeting I could give a better example on how to validate.

**Comment by fredericoregateiro** [comment]
Hello,
I'm using ASP.NET MVC

Thanks

**Comment by shefaliA** [comment]
I guess you can't leverage data annotations advantages with it.

**Comment by tabalinas** [comment]
Please checkout my answer to the similar question on SO http://stackoverflow.com/a/36291243/1140893.
