### ISSUE TITLE
Is there currently built in functionality to hide a column

### ISSUE THREAD

**Issue by jhammer2** [tabalinas/jsgrid#36]
Is there currently built in functionality to hide a column or does this need to be implemented with custom field? I am trying to have an item on the page, but not have it displayed to the user.

**Comment by tabalinas** [comment]
There is no option to hide a column. What if you just change `fields` option value excluding field to hide?

**Comment by tabalinas** [comment]
Have you tried changing `fields` option?

**Comment by jhammer2** [comment]
I was able to hide the column using CSS.

Thanks,
John

**Comment by tabalinas** [comment]
Glad you found the solution!
