### ISSUE TITLE
Returning Json Data from Asp.Net MVC

### ISSUE THREAD

**Issue by shefaliA** [tabalinas/jsgrid#360]
Hi,

I am facing issue loading data to the grid.Below is my code snippet -

---------------Controller-------------------
public class EmailTypeCodeController : BaseController
    {

 public ActionResult Get()
        {

           EModel vm = new EModel();

            vm.EventCommand = "List";

            vm.HandleRequest();

            return View("Index", Newtonsoft.Json.JsonConvert.SerializeObject(vm));
            
        }
}

---------------View (CSTML)--------------------
 $(function() {

        $("#jsGrid").jsGrid({
            height: "70%",
            width: "100%",
            filtering: true,
            editing: true,
            inserting: true,
            sorting: true,
            paging: true,
            autoload: true,
            pageSize: 15,
            pageButtonCount: 5,
            deleteConfirm: "Do you really want to delete the client?",
            controller: {
                loadData: function (filter) {
                    return $.ajax({
                        type: "GET",
                        url: "/EmailTypeCode/Get",
                        data: filter,
                        dataType: "json"
                    });
                }
            },
                fields: [
                    { name: "CodeID", type: "text", width: 50 },
                    { name: "CodeDescription", type: "text", width: 150 },
                    { name: "CodeStatus", type: "text", width: 50 },
                    { name: "PostingId", type: "text", width: 50 },
                     { name: "RecordCreateDate", type: "text", width: 50 },
                    { type: "control" }
                ]
            });
    });

Not sure whats the issue.Emodel is collection of objects which is serializing to JSon.Please suggest

**Comment by soul3lade** [comment]
Hello,

In your controller you are returning a View.  Instead try returning a Json object

`return Json(Netwonsoft.Json.JsonConvert.SerializeObject(vm), JsonRequestBehavior.AllowGet);`

I did not test this code, so there could be some issues but that is the basic concept.

**Comment by shefaliA** [comment]
View has many overloaded methods.The one I am using return a view along with Json. I also tried with below -
  public JsonResult Get()
        {
            EmailTypeCodeViewModel vm = new EmailTypeCodeViewModel();
            var jsonData = new
            {

                rows = (
          from emailType in vm.EmailTypeCodes.ToList()
          select new
          {
              codeID = emailType.CodeId,
              CodeDescription = emailType.CodeDescription,
              CodeStatus = emailType.CodeStatus,
              PostingID = emailType.PostingId,
              RecordCreatedDate = emailType.RecordCreateDate
          }    ).ToArray()
            };
                    return Json(jsonData, JsonRequestBehavior.AllowGet);
                }
jsonData is getting populated .I ahve 2 questions -

- Am  I binding jsonData collection with grid columns correctly?

- Am I calling the Ajax call correctly?

**Comment by tabalinas** [comment]
try to put a `debugger` in the `done` of your ajax handler to see what's coming from the server.

```js
return $.ajax({
                    type: "GET",
                    url: "/EmailTypeCode/Get",
                    data: filter,
                    dataType: "json"
                }).done(function(result) {
                    debugger;
                    console.log(result);
                });
```

Open the DevTools and verify what's coming from the server. I guess it's a data format issue.

BTW: Have you checked the sample js-grid project for ASP.NET? https://github.com/tabalinas/jsgrid-webapi

**Comment by Adondriel** [comment]
Also, if you are using ASP with MVC, you can litterally just return an object and it will automatically turn it into JSON for you. one of my controllers for example: 
```
        [HttpGet]
        [ActionName("getAllGAM")]
        public IList<GridAccountMonth> getAllGAM()
        {
            var allPAM = ProjectAccountingMonthService.GetMonthHour();
            IList<GridAccountMonth> allGAM = new List<GridAccountMonth>();
            foreach (ProjectAccountingMonth PAM in allPAM)
            {
                GridAccountMonth GAM = new GridAccountMonth();
                string strDate = PAM.ProjectMonth + "/01/" + PAM.ProjectYear;
                DateTime actualDate = DateTime.Parse(strDate);
                GAM.AccountingMonthID = PAM.AccountingMonthID;
                GAM.MonthHour = PAM.MonthHour;
                GAM.Date = actualDate;
                allGAM.Add(GAM);
            }
            return allGAM.OrderBy(x => x.Date).ToList();
        }
```

**Comment by shefaliA** [comment]
Thanks for responding

I tried to return the JSonResult from Controller and I am converting it to
Json but for some reason Ajax call is never made to controller.
When I hit the URL  "/EmailTypeCode/Get" directy from browser , I am
hitting the controller

Regards,
Shefali Agrawal
[773-666-3273]

**Comment by tabalinas** [comment]
Try to do your ajax call with jQuery but without jsGrid to be sure it's working.

**Comment by shefaliA** [comment]
I used Jquery Ajax call and its working

**Comment by tabalinas** [comment]
Ok, have you tried this https://github.com/tabalinas/jsgrid/issues/360#issuecomment-232819838?
Post the result printed to the console.

**Comment by Adondriel** [comment]
Also, check your route config, make sure you setup the route to be called like that.

**Comment by tabalinas** [comment]
Close due to inactivity.
