### ISSUE TITLE
Composite keys

### ISSUE THREAD

**Issue by fredericoregateiro** [tabalinas/jsgrid#361]
Hello,

Can i use composite keys for the objects, for example:
`
Customer: { Id, DeviceId, ..., CargoId, CargoDeviceId }
 Cargo: { Id, DeviceId, ... }
`
Where Id and DeviceId are the composite primary keys of the customer and cargo objects and CargoId, CargoDeviceId are FK's to the Cargo object.

The Cargo will be a select option.

Thanks,

**Comment by tabalinas** [comment]
Since jsgrid puts no restrictions on the  incoming data format, it doesn't care about primary keys at all. This means it can be simple or composite, it doesn't matter. Feel free to more details about the concerns you see regarding this scenario.
