### ISSUE TITLE
Doubles the record

### ISSUE THREAD

**Issue by drevix** [tabalinas/jsgrid#362]
Hi, I hope you are well.

I have the need to show a large volume of data in the grid .
To improve the loading time in the core.js file, add the code:
_get_data: function(data) {
	this.data = data;
}

After saving the data in function, I run the " refresh" the grid .
$("#jsGrid").jsGrid("refresh");

By doing this, at the time of generating a insertItem doubles the record.
 
 
![image](https://cloud.githubusercontent.com/assets/9873689/16879700/5beaf24a-4a77-11e6-857a-874b181418d0.png)

insertItem in  controller:
insertItem: function(insertingDato) {
        this.datos.push(insertingDato);
}

And in load-strategies in the finishInsert
finishInsert: function(insertedItem) {
       var grid = this._grid;
       grid.option("data").push(insertedItem);
       grid.refresh();
 }

What could I do to prevent duplicate records?

Thanks in advance

**Comment by drevix** [comment]
He added a line of code missing in _get_data

_get_data: function(data) {
this.data = data;

this._controller['datos'] = this.data;
}

**Comment by tabalinas** [comment]
Not sure I got the issue, but glad that you figured it out yourself.
