### ISSUE TITLE
How to know validate in insert mode or edit mode?

### ISSUE THREAD

**Issue by hoanglap3011** [tabalinas/jsgrid#363]
Hi,
i write a validator custom to check duplicate data. but it check both insert mode and edit mode
how do i know when it check insert mode and when it check edit mode?

**Comment by hoanglap3011** [comment]
anyone have idea?
i tried but no result !

**Comment by tabalinas** [comment]
In the `validator` function you got an item as a second parameter http://js-grid.com/docs/#field-validation-config. In your item I support you have some kind of `ID` field (to identify it in the persistent storage), so for new items it will be empty, as for existing one not. If you don't have ids, you can introduce some field like `isNew`.

**Comment by hoanglap3011** [comment]
thank you!

**Comment by hoanglap3011** [comment]
hi tabalinas,
i tried but not success
can you explain and example by code clearer?

**Comment by tabalinas** [comment]
It could look like the following:
```js
    validate: {
        validator: function(value, item) {
            if(item.ID) {
                // existing item
            } else {
                // new item
            }
        }
    }
```
