### ISSUE TITLE
v1.5.0 edit & delete button click issues

### ISSUE THREAD

**Issue by ozanh** [tabalinas/jsgrid#364]
Hello Tabalinas,
Thank you for the new version 1.5.0.
Unfortunately I had problems with v1.5.0. When I click on edit or delete buttons I get error and edit/delete functionality does not work if triggered from control buttons. Here is the [fiddle](https://jsfiddle.net/ozanhaci/fyota5L0/)
![jsgrid-error](https://cloud.githubusercontent.com/assets/16383613/16913190/76b0d6e0-4cf1-11e6-8893-b5ae515b08f5.PNG)

Note: calling `editItem` does not cause this error.

**Comment by tabalinas** [comment]
Thank you for the report! Going to fix is shortly and release a patch version

**Comment by tabalinas** [comment]
Release is published.

**Comment by ozanh** [comment]
Thank you for fast response and bug fixing.
