### ISSUE TITLE
itemTemplate weird behaviour on production environment

### ISSUE THREAD

**Issue by victorgaspar** [tabalinas/jsgrid#365]
Hi,

I'm using itemTemplate function and I'm getting a weird behaviour after data loading.
On the local environment, the 'value' variable of the anonymous function is undefined, and the 'item' variable contains the JSON object. So, the code below works.
On the production environment, the 'value' variable contains the JSON object, and the 'item' variable is undefined, therefore, the code below fails with error: "Uncaught TypeError: Cannot read property 'Id' of undefined"

Any idea why this could be happening?

Thanks!

`{ name: "Actions", width: "10%", align: "center", editing: false,
  itemTemplate: function(value, item) {
     return $("<div>").append("<a href='/editcontact/" + item.Id + "' onclick='return popup(this)'></a> ")
          .append("<a href='/deletecontact/" + item.Id + "' onclick='return popup(this)'></a> ");
  }
}`

Edit: I'm using version 1.4.1

**Comment by tabalinas** [comment]
What do you call `production environment`? I suppose the reason is that in prod environment you are loading latest version (1.5.0) and this cases the issue.

**Comment by victorgaspar** [comment]
The production environment is hosted in Openshift and I'm using Cloudflare as the CDN.

And you are right, the node package was not properly configured, and in production I was using 1.5.0, and in local environment I was using 1.4.1. Sorry, my mistake.

**Comment by victorgaspar** [comment]
I do not know what you changed in v1.5.1 but now variables item/value in itemTemplate functions works as in version 1.4.1.  :))

**Comment by tabalinas** [comment]
I've fixed it. https://github.com/tabalinas/jsgrid/issues/364 and release the patch version.
