### ISSUE TITLE
Displaying Editor Dialog

### ISSUE THREAD

**Issue by SSquared2000** [tabalinas/jsgrid#366]
I have been trying to display an Editor dialog as shown in the jsGrid web page 'Data Manipulation' Demo example.  Using that page as an example, I am never able to get any dialog displayed for editing.  I found a code example on Fiddle (http://jsfiddle.net/tabalinas/kj6d6tw5/) which helped me resolve the problem.

I added the div section:  `<div id="dialog-form" title="Details">` and now I see the dialog.  The Data Manipulation demo does not have this, and I have even looked over the page source to see if that section is there.  But somehow this code is working for the Demo web page.

Is there something I am missing regarding the Data Manipulation Demo page?  Or is the code example found on the Fiddle page the correct way to code this?

**Comment by tabalinas** [comment]
You can download the repo as a `zip`, all the demos are in the `demos` directory. https://github.com/tabalinas/jsgrid/blob/master/demos/data-manipulation.html
