### ISSUE TITLE
Max-height 

### ISSUE THREAD

**Issue by frankioh** [tabalinas/jsgrid#369]
There is a way to set a max-height? If I set a height after/before the load I got something like this:

![screen shot 2016-07-19 at 4 28 34 pm](https://cloud.githubusercontent.com/assets/8726569/16967295/ea528882-4dcd-11e6-9d5f-9c2600d7f5f9.png)

And looks very bad :( The idea is that when I have data, the grid only should be grown until the size I specified.

Thanks in advance.

**Comment by tabalinas** [comment]
Could you provide an example to demonstrate the issue and explain the desired behavior? You could fork this jsfiddle https://jsfiddle.net/tabalinas/kL291xp5/

**Comment by alexandre-janniaux** [comment]
Is it something like the following jsfiddle that you desire to get ?
https://jsfiddle.net/5zj21xph/3/

**Comment by tonisostrat** [comment]
add `max-height: [whatever]px` to `jsgrid-grid-body`

**Comment by tabalinas** [comment]
Thank you for the solution @tonisostrat. 
It does the trick.
