### ISSUE TITLE
Only first on every page is displayed.

### ISSUE THREAD

**Issue by aarangara** [tabalinas/jsgrid#37]
First of I am very much impressed by this plugin and it's very good.

I have been trying to use it for some data to be displayed on a simple web page for testing it.

This is my js configuration :+1: 
$(function() {

	$("#jsGrid").jsGrid({
		height : "100%",
		width : "100%",
		filtering : false,
		editing : true,
		sorting : true,
		paging : true,
		inserting : true,
		autoload : true,
		pageSize : 10,
		fields : [ {
			name : "userId",
			title: "User Id",
			type : "number",
			width : 50
		}, {
			name : "url",
			type : "text",
			title: "Url",
			width : 500
		}, {
			name : "enable",
			type: "checkbox", 
			title: "Is Enabled"
		}, {
			name : "timestamp",
			type : "text",
			title: "Last Updated On",
			width : 200
		}, {
			type : "control",
			editButton : true,
			deleteButton : true
		} ],

	//data :[{"userId":47,"url":"http://127.0.0.1:8080/MyProject/testservelte","enable":1,"timestamp":"Apr 10, 2015 1:39:52 PM"},{"userId":89,"url":"","enable":1,"timestamp":"Jan 20, 2015 12:00:50 PM"},{"userId":506,"url":"","enable":1,"timestamp":"Mar 2, 2015 5:14:33 PM"},{"userId":2348,"url":"","enable":1,"timestamp":"Jan 20, 2015 3:50:33 PM"},{"userId":2353,"url":"","enable":1,"timestamp":"Feb 13, 2015 4:18:00 PM"},{"userId":2448,"url":"","enable":1,"timestamp":"Feb 24, 2015 4:00:53 PM"},{"userId":2457,"url":"","enable":1,"timestamp":"Feb 26, 2015 3:51:28 PM"},{"userId":2468,"url":"","enable":1,"timestamp":"Feb 26, 2015 3:51:28 PM"},{"userId":2477,"url":"","enable":1,"timestamp":"Mar 16, 2015 7:11:44 PM"},{"userId":2479,"url":"","enable":1,"timestamp":"Mar 16, 2015 7:11:44 PM"},{"userId":2481,"url":"","enable":1,"timestamp":"Mar 24, 2015 3:30:04 PM"},{"userId":2508,"url":"","enable":1,"timestamp":"Apr 1, 2015 5:23:54 PM"},{"userId":2509,"url":"","enable":1,"timestamp":"Apr 2, 2015 10:01:13 AM"},{"userId":2521,"url":"","enable":1,"timestamp":"Apr 20, 2015 11:11:52 AM"},{"userId":2524,"url":"","enable":1,"timestamp":"Apr 9, 2015 4:57:40 PM"},{"userId":2527,"url":"","enable":1,"timestamp":"Apr 10, 2015 4:50:24 PM"},{"userId":2531,"url":"","enable":1,"timestamp":"Apr 14, 2015 4:58:17 PM"},{"userId":2535,"url":"","enable":1,"timestamp":"Apr 17, 2015 1:38:58 PM"},{"userId":2536,"url":"","enable":1,"timestamp":"Apr 20, 2015 4:17:47 PM"},{"userId":2537,"url":"","enable":1,"timestamp":"Apr 20, 2015 4:59:57 PM"},{"userId":2538,"url":"","enable":1,"timestamp":"Mar 16, 2015 7:11:44 PM"},{"userId":2545,"url":"","enable":1,"timestamp":"Apr 28, 2015 1:31:20 PM"},{"userId":2546,"url":"","enable":1,"timestamp":"Apr 20, 2015 4:59:57 PM"},{"userId":2559,"url":"","enable":1,"timestamp":"May 12, 2015 10:49:07 AM"},{"userId":2560,"url":"","enable":1,"timestamp":"May 12, 2015 10:49:07 AM"},{"userId":2561,"url":"","enable":1,"timestamp":"May 8, 2015 11:39:05 AM"},{"userId":2565,"url":"","enable":1,"timestamp":"May 8, 2015 11:39:05 AM"},{"userId":2566,"url":"","enable":1,"timestamp":"May 20, 2015 11:28:43 AM"},{"userId":2569,"url":"","enable":1,"timestamp":"May 22, 2015 11:24:55 AM"},{"userId":2577,"url":"","enable":1,"timestamp":"May 26, 2015 6:22:36 PM"},{"userId":2578,"url":"","enable":1,"timestamp":"May 27, 2015 1:28:08 PM"}],
		        
		controller : {
			loadData : function(filter) {
				filter["operation"] = "loadUrls";
				return $.ajax({
					type : "GET",
					url : "ruleenginehandler",
					data : filter,
					dataType : "json"
				});
			},

			insertItem : function(item) {
				item["operation"] = "insert";
				return $.ajax({
					type : "POST",
					url : "ruleenginehandler",
					data : item,
					dataType : "json"
				});
			},

			updateItem : function(item) {
				item["operation"] = "update";
				$.ajax({
					type : "POST",
					url : "ruleenginehandler",
					data : item,
					dataType : "json"
				}).done(function(data) {
					if (console && console.log) {
						console.log("Sample of data:", data);
					}
				}).fail(function(data) {
					if (console && console.log) {
						console.log("Failed", data);
					}
				});
			},

			deleteItem : function(item) {
				item["operation"] = "delete";
				return $.ajax({
					type : "POST",
					url : "ruleenginehandler",
					data : item,
					dataType : "json"
				});
			}
		}

	});

});

I have commented out "data" for loading information from my database.

It creates 4 page as there are 31 records, but it only displays first entry on each page  and not other entries.

When I provide data statically in "data", it renders everything correctly.

Please help me out in solving this.

**Comment by tabalinas** [comment]
Thank you for the feedback!
Your config looks well at first sight.

Try to change `loadData` method like following to be sure that ajax call returns the same data (see in console):

```javascript
loadData : function(filter) {
	var d = $.Deferred();

    filter["operation"] = "loadUrls";
    
    $.ajax({
        type : "GET",
        url : "ruleenginehandler",
        data : filter,
        dataType : "json"
    }).done(function(result) {
    	console.log(result);
    	d.resolve(result);
    });

    return d.promise();
},
```

**Comment by aarangara** [comment]
I tried what you suggested for load method. The console outputs the following :

[Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object]

I guess there are the objects that contain the data returned  by my serer side code.

Is there any issue with this?

I will explain what I have done in my server side code for returning json array : 

I have a pojo class which I convert to a json string using Gson. and then just return that same string as response. Is there something wrong I am doing in my server side code?

**Comment by fanturi** [comment]
Hi,

If you want to see what your object contains change: console.log(result) by console.dir(result).
If I checked correctly your code your object must have at least this fields: userId, url, enable and timestamp. If not adapt your server code.

**Comment by aarangara** [comment]
I tried using 

console.dir(result).

It gives me following : 

![grid-demo](https://cloud.githubusercontent.com/assets/2873128/7954738/eaaee8de-09ef-11e5-8bc6-2072d9e4747d.png)

It is having all required params as mentioned by you. I don't understand what am I missing though.

**Comment by fanturi** [comment]
I don't understand your part with the filter and your way to load data
Have you tried a more classic way to load your data ?
For example:

```javascript
$.ajax({
    url: "your/path",
    type: 'GET',
    dataType: 'json',
    data: {
        method: "your-method",
        userId_filter: filter.userId,
        url_filter: filter.url,
        enable_filter: filter.enable,
        timestamp_filter: filter.timestamp
    }
}).done(function(response) {
    d.resolve(response);
}).error(function(jqXHR) {
    d.reject(jqXHR.status);
});
						 
return d.promise();
```

**Comment by aarangara** [comment]
Yes, I tried this, but this is also not working for me. Only loads first row data on each page.

**Comment by fanturi** [comment]
I don't know why sorry.
Just to be sure have you check the others objects in your result.
In your screenshot we can see the first object only.

**Comment by aarangara** [comment]
Yes I checked each of 31 objects returned in my result and everything looks fine.

Please someone help me out with my problem, as I found this plug-in as the easiest for usage and understanding.

**Comment by fanturi** [comment]
the only difference I see between your result and your static data is with the field enable.
You are using true/false with ajax and 1/0 in the static data.
and personally I have some problems with field name like "enable" or common name like this.

sorry not to be able to help you, I hope @tabalinas can.

**Comment by aarangara** [comment]
I changed my server side code to return 0/1 instead of true/false, but still no luck.

**Comment by aarangara** [comment]
Finally my problem is resolved.

I kept the height as 100% in my config which is why the data was not getting displayed below the first row.

I really apologize for this as I don't have much experience with UI.

**Comment by tabalinas** [comment]
Glad that you figured this out!
