### ISSUE TITLE
How can i checked checkbox by clicking row in BatchDelete?

### ISSUE THREAD

**Issue by amin750** [tabalinas/jsgrid#370]
How can i use rowClick function to checked checkbox?

**Comment by tabalinas** [comment]
There are several ways to go.
For instance you could do the following:

```js
rowClick: function(args) {
    // find the checkbox in the clicked row and click on it
    $(args.event.target).closest("tr").find("input[type=checkbox]").click();
},
```

The only thing you should change `itemTemplate` a bit, to avoid infinite cycling you should call `e.stopPropagation` in checkbox click handler (to avoid click to popping up to the row again).

```js
itemTemplate: function(_, item) {
    return $("<input>").attr("type", "checkbox")
            .on("click", function (e) {
                $(this).is(":checked") ? selectItem(item) : unselectItem(item);
                e.stopPropagation();
            });
},
```

**Comment by seeker25** [comment]
For the first way 
         if (item.event.target.type == "checkbox")
                    return;
(this way when you select the checkbox which is part of the row, it wont double register the click)
