### ISSUE TITLE
SAVE the DATA . NEW DATA is not reflecting after refreshing the page.

### ISSUE THREAD

**Issue by animemis** [tabalinas/jsgrid#372]
Hi, The grid is the best than any other grid. 
I am using your example "data manipulation"
when I am saving the data after adding a new item and clicking on "Save". The data is reflecting in the last row. 
PROBLEM :  When I refresh the page , The data / row  inserted in the table is no more. 
Please show me how to save the data thus it should reflect even after refreshing the page.

I am sure , I am making some petty mistake. Please guide me..

**Comment by tabalinas** [comment]
Well, js-grid is a client-side control. This means, if you wish to have new items after page refresh, you need to save data in the persistent storage (database usually). For this purpose you implement `controller` methods: `loadData` will load data with ajax from the server, `insertItem` will save new item in database with ajax call. Here is the docs about controllers: http://js-grid.com/docs/#grid-controller.
You can also checkout sample projects for different backends available on github http://js-grid.com/samples/
