### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by tomcat4x** [tabalinas/jsgrid#378]
Hi,

by using jsGrid.locale('de'); i get the error: Error: unknown locale de. The same problem by using:
 jsGrid.locale('es'); 
 jsGrid.locale('pl');

Without setting a locale jsGrid is working without problems and die subdirectory i18n with the locales is present.

**Comment by tabalinas** [comment]
Have you added a link to the locale file? 
It's not included in the main script.

**Comment by tomcat4x** [comment]
Thats the solution.

Thanks a lot.
