### ISSUE TITLE
qplace

### ISSUE THREAD

**Issue by artinact** [tabalinas/jsgrid#38]
Couple of questions:
1. rowClick: how to call default event after processing the code in rowClick? 
2. how to find selected row? I have a "select" button outside of grid. Upon clicking on it I want  to know which row in the grid is currently selected.

Thanks,

**Comment by tabalinas** [comment]
1. What default `rowClick` does is just call `editItem` method if `editing` is `true`. So you can do the following:

```javascript
rowClick: function(args) {
    // your actions
    this.editItem(args.item);
}
```

2. Option `selecting` is actually means row highlight on mouse hover.
If you wish to select row e.g. on row click, you can save selected row in external variable:

```javascript
rowClick: function(args) {
    // save selected item
    selectedItem = args.item;

    // save selected row
    $selectedRow = $(args.event.target).closest("tr");
    
    // add class to highlight row
    $selectedRow.addClass("selected-row");
}
```

and styles for selected row

```css
    .selected-row > td {
        background: #c4e2ff;
        border-color: #c4e2ff;
    }
```

Hope it will help.

**Comment by CrazyRedScorp** [comment]
Sorry. It works. The style of the current row has changed. Nice.
But, how to make the default style for the all other rows?
