### ISSUE TITLE
Scroll to top when changing page

### ISSUE THREAD

**Issue by Ayaros1980** [tabalinas/jsgrid#382]
Hi, I have several jsGrids with pageLoading, and I would like to scroll to the top of the grid every time I change the page, now the scroll stays at its position and it is not very comfortable... Is there a way to do it?

**Comment by tabalinas** [comment]
There is `onPageChanged` callback (http://js-grid.com/docs/#onpagechanged), where you can put your scrolling logic:

```js
onPageChanged: function(args) {
    args.grid._body.scrollTop(0);
}
```

**Comment by Ayaros1980** [comment]
Perfect, thank you so much!

**Comment by tabalinas** [comment]
You are welcome!
