### ISSUE TITLE
I want onRowDouble Click behave as onRowClick

### ISSUE THREAD

**Issue by felveryepez** [tabalinas/jsgrid#383]
I am so newbie to all this...

I just want emulate the inline edit as when the editing:true property of the Grid is present but when you double click the row. 

I am using the one click for batch delete and want double click to edit each element inline as the normal behavior.

Is that possible?

Thanks.

**Comment by tabalinas** [comment]
Yes, just redefine both handlers.

The default implementation of `rowClick` is the following:

```
rowClick: function(args) {
    if(this.editing) {
        this.editItem($(args.event.target).closest("tr"));
    }
}
```

So you can put this implementation to `rowDoubleClick` and redefine `rowClick` in the grid config.

**Comment by felveryepez** [comment]
is not working Sir...

I have this...

`	$("#jsGrid").jsGrid({
		height: "auto",
		width: "100%",
		editing: false,
		paging: true,
		autoload: true,
		pageSize: 25,
		pageButtonCount: 5,
		deleteConfirm: false,
		rowDoubleClick: function(args) {
	        this.editItem($(args.event.target).closest("tr"));
		},
		
		/*	
		
		function(args) {
			showDetailsDialog("Edit", args.item)
		},
		*/

		controller: {
			loadData: function(filter) {
				return $.ajax({
					type: "GET",
					url: "timetrackers/",
					data: { filter: filter, ssoID : $_GET['ssoID'] },
					dataType: "json"
				});
			}
		},
		fields: [
			{
                headerTemplate: function() {
					return $('<button>').button({label: 'Delete', icons: {primary: 'ui-icon-circle-minus'}}).click(function (event) {
								deleteSelectedItems();
							});

                },
                itemTemplate: function(_, item) {
                    return $("<input>").attr("type", "checkbox")
                            .on("change", function () {
                                $(this).is(":checked") ? selectItem(item) : unselectItem(item);
                            });
                },
                align: "center",
                width: 50
            },
			{ name: "id", title: "ID", type: "number", align: "center", width: 30, inserting:false, editing: false, filtering: false },
			{ name: "pid", title: "Project Name", type: "select", align: "left", width: 150, items: projects, valueField: "pid", textField: "pname" },
			{ name: "tid", title: "Task Name", type: "select",align: "left", width: 150, items: tasks, valueField: "tid", textField: "tname" },
			{ name: "hours", title: "Hours", type: "text", align: "center", width: 30},
			{ name: "task_date", title: "Date", type: "myDateField", align: "center", width: 150 },
			{
				type: "control",
				editButton: true,
				deleteButton: false,
				headerTemplate: function() {
					return $('<button>').button({label: 'Add', icons: {primary: 'ui-icon-circle-plus'}}).click(function (event) {
								showDetailsDialog("Add", {});
							});
				}
			}

		]
	});`

**Comment by felveryepez** [comment]
I not working... this is my code...
`
	$("#jsGrid").jsGrid({
		height: "auto",
		width: "100%",
		editing: false,
		paging: true,
		autoload: true,
		pageSize: 25,
		pageButtonCount: 5,
		deleteConfirm: false,
		rowDoubleClick: function(args) {
	        this.editItem($(args.event.target).closest("tr"));
		},
		controller: {
			loadData: function(filter) {
				return $.ajax({
					type: "GET",
					url: "timetrackers/",
					data: { filter: filter, ssoID : $_GET['ssoID'] },
					dataType: "json"
				});
			}
		},
		fields: [
			{
                headerTemplate: function() {
					return $('<button>').button({label: 'Delete', icons: {primary: 'ui-icon-circle-minus'}}).click(function (event) {
								deleteSelectedItems();
							});

                },
                itemTemplate: function(_, item) {
                    return $("<input>").attr("type", "checkbox")
                            .on("change", function () {
                                $(this).is(":checked") ? selectItem(item) : unselectItem(item);
                            });
                },
                align: "center",
                width: 50
            },
			{ name: "id", title: "ID", type: "number", align: "center", width: 30, inserting:false, editing: false, filtering: false },
			{ name: "pid", title: "Project Name", type: "select", align: "left", width: 150, items: projects, valueField: "pid", textField: "pname" },
			{ name: "tid", title: "Task Name", type: "select",align: "left", width: 150, items: tasks, valueField: "tid", textField: "tname" },
			{ name: "hours", title: "Hours", type: "text", align: "center", width: 30},
			{ name: "task_date", title: "Date", type: "myDateField", align: "center", width: 150 },
			{
				type: "control",
				editButton: true,
				deleteButton: false,
				headerTemplate: function() {
					return $('<button>').button({label: 'Add', icons: {primary: 'ui-icon-circle-plus'}}).click(function (event) {
								showDetailsDialog("Add", {});
							});
				}
			}

		]
	});
`
