### ISSUE TITLE
How to put filter values in inputs

### ISSUE THREAD

**Issue by ozanh** [tabalinas/jsgrid#384]
Hello,
I use jsGrid 1.5.1 with `pageLoading=true`, `autoload=true` and with Grid Controllers. I load/update/insert/delete the data over ajax.
What I want to do is to save the last filter values entered by user to database (this is easy and can be handled on server side). Other thing is when page including jsGrid is refreshed or reopened, filter values should be in filter inputs and loadData should use the filter values at first load (this is not easy for me).
I know how to customize fields and introduce new field types so I can add default filter values to fields option and override filterTemplate to add default values to fields on server side and create a new load strategy to send default filter values to controller's loadData. This is hard and long way. Is not it good if `grid.search(filter)` or a new `grid.setFilter(filter)` method put the given values in filter inputs?

**Comment by tabalinas** [comment]
Yes, this is a really good suggestion. Thank you for the feedback!
In fact, this enhancement is already reported  (https://github.com/tabalinas/jsgrid/issues/81#issuecomment-130442869)
Currently, as a workaround you could set filter values manually with jQuery.
