### ISSUE TITLE
noDataContent cell class is missing

### ISSUE THREAD

**Issue by ozanh** [tabalinas/jsgrid#385]
Hello,
Following css code in **jsgrid.css** becomes useless because `noDataContent` `<td>` does not have `jsgrid-cell` class. I do not know whether it is intentional or not I just want to inform you.

    .jsgrid-nodata-row .jsgrid-cell {
        padding: .5em 0;
        text-align: center;
    }

**Comment by tabalinas** [comment]
Thank you for spotting and reporting the issue. This bug is introduced in 1.5 with styles improvements to prevent styles clashing issues for other tables inside jsgrid cells. That's why `jsgrid-cell` class was added, but for noDataRow it's missing.
