### ISSUE TITLE
select

### ISSUE THREAD

**Issue by ylahav** [tabalinas/jsgrid#386]
is it possible to define the 'select' option diffrently to each row.

example:
each row has 3 colos: 'table name', 'col name' and 'selected col'
The 'selected col' is depend on possible 'col' of a specific table... so, I want the following:

t1, col1-1 {col1-1, col1-2}
t1, col1-2 {col1-1, col1-2}
t2, col2-1 {col2-1, col2-2, col2-3, col2-4}
t2, col2-2 {col2-1, col2-2, col2-3, col2-4}
t2, col2-3 {col2-1, col2-2, col2-3, col2-4}
t2, col2-4 {col2-1, col2-2, col2-3, col2-4}

**Comment by tabalinas** [comment]
Redefine  options of select control in `editTemplate` of the field. There you can put a condition to define items depending on item type.

**Comment by ylahav** [comment]
I tried both itemTemplate and editTemplate....
the itemTemplate load only the latest "options" list and I want each row will have difreent options!
The 'editTemplate' is too late because if some of the rows (items) has value in this attribute, the attribute is not shown...

**Comment by ylahav** [comment]
I find a solution. I initial the 'select' option with all options.
On edit I am using only the allowed 'options'... and here I am using edittemplate

**Comment by tabalinas** [comment]
Yes, this is exactly what was meant. Glad that you figured it out.
