### ISSUE TITLE
Export table in .PDF or .CSV

### ISSUE THREAD

**Issue by ElioRiba** [tabalinas/jsgrid#388]
Hi,
 do you think should be possible to export a table to .pdf or .csv file?
Thanks

**Comment by tabalinas** [comment]
As a core functionality, I'm not sure it makes sense, because js-grid is a really lightweight control.
But this could be an additional utility script. 
There is already a registered suggestion: https://github.com/tabalinas/jsgrid/issues/59

**Comment by ElioRiba** [comment]
Thanks a lot.
