### ISSUE TITLE
Support Nested fields in Json Data

### ISSUE THREAD

**Issue by JoshZA** [tabalinas/jsgrid#39]
Could we please get support for something like:
```
            fields: [
                { name: "name", type: "text", title: 'Report Name' },
                { name: "client.name", type: "text", title: 'Client' },
            ]
```

Also in the documentation, it should be mentioned that ```name: "name"``` is case sensitive so ```name: "Name"``` won't work

**Comment by tabalinas** [comment]
Thank you valuable suggestion! Regarding case sensitiveness, I guess there is no need to tell about it in docs due to JavaScript case sensitiveness.

**Comment by tabalinas** [comment]
Implemented by https://github.com/tabalinas/jsgrid/pull/165
