### ISSUE TITLE
how can I make the sum ddi a numeric column in jsGrid?

### ISSUE THREAD

**Issue by eugeniotcs** [tabalinas/jsgrid#392]
Tabalinas Hello, how can I make the sum of a numeric column in jsGrid? For example, in custom-view demo,? (Jsgrid / demos / custom-view.html)
And show the result of the "Age" column in the last row?

**Comment by tabalinas** [comment]
I guess, this is the issue you are talking about https://github.com/tabalinas/jsgrid/issues/224
The suggestion to simplify this scenario is already added.
