### ISSUE TITLE
single select checkbox

### ISSUE THREAD

**Issue by saeedeh676** [tabalinas/jsgrid#394]
i need to change multiple select checkboxs to single select checkboxs.how i can do it?

**Comment by tabalinas** [comment]
I'm not sure I understand your question. What do you mean by "multiple select checkboxs" in jsgrid?

**Comment by saeedeh676** [comment]
i want to  select  only one checkbox in a group and   unchecked other checkbox on one checked

**Comment by tabalinas** [comment]
Are you talking about checkboxes in jsgrid rows?
If yes, then you can store a field in your data items `Checked` and use this field as checkbox field value, in the field click handler you change this `Checked` field for all items except selected and call `refresh` method of the grid. This should do the trick.

**Comment by saeedeh676** [comment]
thanks for your reply
