### ISSUE TITLE
updateItem and Errors from backend

### ISSUE THREAD

**Issue by wax100** [tabalinas/jsgrid#395]
Hello! I have a problem! 
here is the table 
http://mpodd.ru/spravochnik.html 
If I want to Update item and update email wax1001@rambler.ru to wax100@rambler.ru (But i cant have 2 similar emails and check it in backend) So, I want to cancel editing, show popup (I use swal) and don't hide editing inputs (the EDIT mode, to prevent lose data in inputs)

http://prntscr.com/c1qha9 

My JS is here :
http://mpodd.ru/assets/components/ajax/ajax.js 

Some code from it
```js
updateItem: function(item) {
                        var result = $.Deferred();
                    
                  $.ajax({
                        type: "POST",
                        dataType: "json",
                        url: 'assets/components/ajax/connector.php',
                        data: item
                    }).done(function(data) {
                    	if(data.success != true){
                           sweetAlert("Ошибка!", data.message, "error");
                          result.resolve(lastPrevItem);
                        }else{
                           result.resolve(data.data);
                        }
                        return result.promise();
                    })
```
But when I change **wax1001** to **wax100** I can see popup error, but in grid I see 2 emails "wax100@rambler.ru". Instead of return lastPrevItem. 
Can I make so, hant when I edit and have errors from server  - the grid row stay in EDIT mode, not in SHOW mode ?

**Comment by wax100** [comment]
Hmm , I think I do it these morning by myself)
In backend I add such code at error 
`$protocol = (isset($_SERVER['SERVER_PROTOCOL']) ? $_SERVER['SERVER_PROTOCOL'] : 'HTTP/1.0');
        $code = 400;
        header($protocol . ' ' . $code . ' ' . 'Error');`

and in frontend
return $.ajax({
                        type: "POST",
                        dataType: "json",
                        url: 'assets/components/ajax/connector.php',
                        data: sendd
                    }).done(function(data) {
                            return data;                           
                    }).error(function(response) {
                        sweetAlert("Ошибка!", response.responseJSON.message, "error");
                        return response.responseJSON.data;
                    })

**Comment by wax100** [comment]
Hello again ) I remade grid. 
Top grid is just to show and to filter items.
Bottom grid - I can edit items, but I cant! 
when i made 
`updateItem: function(item) {
console.log(item)
`
return me undefined! What is the problem? ... 
http://mpodd.ru/spravochnik.html?ismgr=1

**Comment by tabalinas** [comment]
I guess the issue, is that `updateItem` should be on the `controller` configuration, not in the grid. Currently, you redefined grid method instead of controller call.

**Comment by wax100** [comment]
Yes  , U are right. My mistake
