### ISSUE TITLE
Select row from javascript

### ISSUE THREAD

**Issue by VladislavBI** [tabalinas/jsgrid#397]
Hello how can i select row from outside js if i have full data, which is contained in this row (object with fields like id, name, etc)

**Comment by wax100** [comment]
Good question! I also want to know answear.
Artem, can U help us?

**Comment by tabalinas** [comment]
I'm not sure what you mean by "select row", but if you mean find a row, then you can use [`rowByItem`](http://js-grid.com/docs/#rowbyitemitem-jqueryelement).
If you don't have the item itself, you can find it by condition in items collection, which you can get from `data` option.

**Comment by wax100** [comment]
$('#grid').jsGrid('data') - return data-object?

**Comment by tabalinas** [comment]
No, this is the array of items currently loaded to the grid: `$('#grid').jsGrid('option', 'data')`
