### ISSUE TITLE
Add new item to top of grid

### ISSUE THREAD

**Issue by wax100** [tabalinas/jsgrid#398]
Hello Artem! 
Is there any option that  control where to add row - at the top or at the end od grid.

**Comment by tabalinas** [comment]
This behavior can be redefined with load strategy http://js-grid.com/docs/#load-strategies
In you case you need to redefine `finishInsert` so that it inserts data to the beginning of the array. 
Here is the current implementation:

```js
finishInsert: function(insertedItem) {
            var grid = this._grid;
            grid.option("data").push(insertedItem);
            grid.refresh();
        },
```

Use `unshift` instead of `push`.

**Comment by kunalkankariya** [comment]
> ```js
> finishInsert
> ```

@tabalinas This doesn't seem to work for me. Neither the loading strategy nor the config property works. Can you please do a quick jsFiddle for me please? Thanks.

**Comment by djdance** [comment]
it doesn't work for method "insertItem", use $("#grid").jsGrid("option", "data").unshift(item);
