### ISSUE TITLE
batch delete - deleting items from page 2 onwards processes only one

### ISSUE THREAD

**Issue by junnyman** [tabalinas/jsgrid#400]
Hi, about  "batch delete" in the demo, 
If you have turned on paging, batch delete would work properly on the first page,
But If you try to delete several items from second page onwards, a trigger set you back to page 1 and delete is applied only to the first item selected.

**Comment by junnyman** [comment]
Great Staff! Thanks for your reply!👍

**Comment by tabalinas** [comment]
Thank you for the report!
