### ISSUE TITLE
Include a status button that changes dynamically on click

### ISSUE THREAD

**Issue by claudiosw** [tabalinas/jsgrid#401]
Hi!

I'm trying to include a status button that changes dynamically on click. 
It is like a status task button that is created with status "to do" and when I click in the button the status is changed to "done".
I know how to do that with jQuery in a standard table. But when I included it in jsGrid, when I click in the button, it switches to the edit mode. Is there a way to avoid this in a column? (I already included editing: false, readOnly: true)

I also tried to include the button in the control column with this:
https://github.com/tabalinas/jsgrid/issues/172

But, when I click in the status button, it also enters the edit mode.

Is there a way that I can have this status button?

Thanks,

Claudio

**Comment by tabalinas** [comment]
Redefine `rowClick` callback, so that it does nothing, setting the config: `rowClick: $.noop`.
Or if you wish to preserve edit behavior `return false` from click handler on your button, so that event won't bubble to the row click form your button.

**Comment by claudiosw** [comment]
Problem solved! Thank you very much!

Tried to solve with your explanation but didn't solve but after searching for rowClick I found an example that you provided that solved my problem:
https://github.com/tabalinas/jsgrid/issues/96

**Comment by tabalinas** [comment]
Glad that you figured it out!

**Comment by VK-0102** [comment]
Can you let me know how you fixed by sample code snippet
