### ISSUE TITLE
Using jsGrid inside jQuery Tabs

### ISSUE THREAD

**Issue by SSquared2000** [tabalinas/jsgrid#403]
I am looking to consolidate multiple pages into a single page and use Tabs to switch between each different grid.  When I create two tabs and place one grid in each, the 2nd grid does not look correct.  The header titles are the correct width, but the row columns seem to have widths 1/2 of what they should be.  The result is, the row columns do not match up with their headers.  Is there something I can write to help prevent this issue?  Thank you for any help.

If I have both grids on the same page (not using jQuery Tabs) both grids look fine:
```
    <div id="jsGridSubInfo"></div>
    <div id="jsGridDataSet"></div>
```

But when I use tabs, I get the issue:
```
<script>$(function () { $("#tabs").tabs(); });</script>

<div id="tabs">
    <ul>
        <li><a href="#jsGridSubInfo">Subscriptions</a></li>
        <li><a href="#jsGridDataSet">Data Sets</a></li>
    </ul>

    <div id="jsGridSubInfo"></div>
    <div id="jsGridDataSet"></div>
</div>
```

**Comment by SSquared2000** [comment]
Ooops.  Nevermind.  I found the answer in this duplicate.  https://github.com/tabalinas/jsgrid/issues/216

**Comment by tabalinas** [comment]
Yes, exactly. Cool that you found it.
