### ISSUE TITLE
Cell Change  Event

### ISSUE THREAD

**Issue by Ankitmane1512** [tabalinas/jsgrid#404]
Is there any cell change Event in this grid ?

**Comment by tabalinas** [comment]
There is `onItemUpdating` and `onItemUpdated` callbacks which called before and after item update.
More about callbacks http://js-grid.com/docs/#callbacks.

**Comment by thilankascentic** [comment]
Hi @tabalinas 
I've implemented both onItemUpdating and onItemUpdated functions but those are not executing when changing a cell value,
In my grid, I dont have a separate column for update, i want to update other column's value when switching to cell, hence I need to get the value on cell click,

a little help please?
