### ISSUE TITLE
How to align rows in grid?

### ISSUE THREAD

**Issue by usmannoor** [tabalinas/jsgrid#405]
@tribis Hey there. I have a serious issue in aligning my rows. Whenever grid is load it squeezes the row and if I slightly change the size of browser then it surprisingly become correctly aligned I dont whats the issue behind this. Waiting for your help please as early as possible. I have attached screen shot and the piece of code which will clear you my issue.

**CODE:**

```
$("#userUpdation").jsGrid({
        height: "100%",
        width: "100%",
        filtering: false,
        inserting:false,
        editing: true,
        selecting: true,
        sorting: false,
        paging: true,
        autoload: true,
        pageSize: 10,
        pageButtonCount: 5,
        controller: {

            loadData: function (filter) {
                return $.ajax({
                    type: "GET",
                    url: "/updateUser",
                    data: filter,
                    success: function (result){
                              **$('#userUpdation').jsgrid('render');**
                    }
                });
            }
        }
    });
```

![jsgrid](https://cloud.githubusercontent.com/assets/8913993/17881250/58a1c4b4-691d-11e6-9892-fb43ea87c8d0.png)

**Comment by tabalinas** [comment]
Most probably you grid is rendered in an invisible container (e.g. in a hidden tab of a tab control).
Once you show this container call [`refresh`](http://js-grid.com/docs/#refresh) method.

**Comment by usmannoor** [comment]
Thanks it works on a sample project but still there's some issue in my actual code.

**Comment by tabalinas** [comment]
Could you provide an example to see the issue?

**Comment by usmannoor** [comment]
Yeah sure.

**Comment by usmannoor** [comment]
@tabalinas Thanks man it is working now. I had an invisible container and I was unaware of it now all things are clear. Thanks for your help.

**Comment by tabalinas** [comment]
Glad that you figured it out. You are welcome!
