### ISSUE TITLE
Rows Reordering Scenario has an issue

### ISSUE THREAD

**Issue by theeedannyd** [tabalinas/jsgrid#407]
Hi

It appears your demo is working but actually there are JS issues, I found this when it went to resave my reordered data back to my database, the actual data hadn't been reordered using the indexes..

Uncaught TypeError: Cannot read property '1' of null

Thanks

**Comment by tabalinas** [comment]
Hi,

Thank you for the report. Could you provide more detail on how to reproduce the issue?

**Comment by theeedannyd** [comment]
Hi,

Simply drag to reorder the list and it throws the error.

Thanks
