### ISSUE TITLE
How to clear grid rows

### ISSUE THREAD

**Issue by Ankitmane1512** [tabalinas/jsgrid#408]

**Comment by tabalinas** [comment]
Just put empty array to the `data` option of the grid.

**Comment by Ankitmane1512** [comment]
Autoload property of the grid is set to false.
How do I put empty array to data option, please give sample code.

**Comment by tabalinas** [comment]
Just use `option` method http://js-grid.com/docs/#optionoptionname-optionvalue to set `data` option to `[]`. But since `autoload:false` your grid should be empty on first load.

**Comment by Ankitmane1512** [comment]
Not understood from the documentation.
Please sample code or js-fiddler code for reference.

**Comment by tabalinas** [comment]
`$("#jsGrid").jsGrid("option", "data", [])`

**Comment by tabalinas** [comment]
`$("#jsGrid").jsGrid("option", "data", [])`

**Comment by Ankitmane1512** [comment]
Thank you.
