### ISSUE TITLE
jsgrid not showing results when being wrapped in a div tag

### ISSUE THREAD

**Issue by jhammer2** [tabalinas/jsgrid#41]
Is there a way to wrap the grid in a div without losing the data? I am trying to implement a slide out menu which would require wrapping everything in a div tag. However, when doing this the grid does not show any data.

**Comment by tabalinas** [comment]
Could you update this fiddle http://jsfiddle.net/tabalinas/z39qvxoc/ to demonstrate the problem?
It's not clear from the description.

**Comment by jhammer2** [comment]
The fiddle has been updated. The issue has to do with the height option. I was/am setting it based on a percentage. Which works fine when thejsgrid is not wrapped in a div. However, when it is set as percentage and you wrap a div tag around the grid, it will not show anything. You can see this in the updated fiddle:

http://jsfiddle.net/z39qvxoc/3/

The solution is to set the height based on px. Then everything works fine.

**Comment by tabalinas** [comment]
This is not an issue of jsGrid. This is how css height works. Read more about the problem here http://stackoverflow.com/questions/1622027/percentage-height-html-5-css

**Comment by jhammer2** [comment]
Thanks for the link. Good to know.

**Comment by tabalinas** [comment]
You are welcome!
