### ISSUE TITLE
How to add icon in text field

### ISSUE THREAD

**Issue by bfallar3** [tabalinas/jsgrid#410]
my grid enable insert, and I would like to ask how to customize the field to add an icon (e.g., search icon) when I clicked will pop-up a dialog (jquery dialog) and paste back the selected item to the text input.

**Comment by tabalinas** [comment]
You can redefine the content of the field with `itemTemplate` function. Return the content of the cell from it, obviously it can be anything. Checkout fields configuration http://js-grid.com/docs/#fields
