### ISSUE TITLE
pagerFormat can't set to center of page

### ISSUE THREAD

**Issue by KururuLABO** [tabalinas/jsgrid#411]
I've try to setting pagerFormat align all of page number to center of page but not working.

Setting
`pagerFormat: "<center> {pages} </center>",`

Result
`<div class="jsgrid-pager">
<center></center> 
<span class="jsgrid-pager-page">
<a href="javascript:void(0);">1</a>
</span>
<span class="jsgrid-pager-page jsgrid-pager-current-page">2</span>
<span class="jsgrid-pager-page"><a href="javascript:void(0);">3</a></span>  
</div>`

**Comment by tabalinas** [comment]
Try to add a css rule:

```css
.jsgrid-pager { text-align: cetner; }
```

**Comment by KururuLABO** [comment]
i tried to adding this css rule still not working.

**Comment by tabalinas** [comment]
I guess, it's just because you copied my code snipped with a typo: put `center` instead of `cetner`.

https://jsfiddle.net/tabalinas/cy8b8Lro/

**Comment by KururuLABO** [comment]
It's worked. I have to say thank and sorry. 
It's my bad. Didn't check code before reply this :+1:
