### ISSUE TITLE
loadData asp.net mvc controller not working

### ISSUE THREAD

**Issue by ferrarisebastian** [tabalinas/jsgrid#413]
Hello how are you? sorry for my English, I tell you I'm trying to lleba a grid using asp.net mvc, and I'm having incovenientes, I was watching the forum with errors, eg this: https://github.com/tabalinas/jsgrid/issues / 253 putting probe using: JSON.parse and gives me an error, you pass the print screen, thank you very much!
<img width="348" alt="1" src="https://cloud.githubusercontent.com/assets/8854368/17989121/4c60e334-6b01-11e6-9c1c-192bbe4fa626.PNG">
<img width="304" alt="2" src="https://cloud.githubusercontent.com/assets/8854368/17989122/4c61c880-6b01-11e6-9718-15a1730adb5e.PNG">
<img width="358" alt="3" src="https://cloud.githubusercontent.com/assets/8854368/17989123/4c630452-6b01-11e6-8afb-a68ef705de5e.PNG">
<img width="954" alt="4" src="https://cloud.githubusercontent.com/assets/8854368/17989124/4c6ff068-6b01-11e6-96f9-37a74649990c.PNG">

**Comment by tabalinas** [comment]
I guess, the issue with the response then, no?
Have you tries to `console.log(response)`?

**Comment by tabalinas** [comment]
Close due to inactivity.
