### ISSUE TITLE
Added field GET value problem

### ISSUE THREAD

**Issue by bux23** [tabalinas/jsgrid#414]
I have recently added a new select field to my grid. Every time I load the grid it doesn't load any results. Inspecting the requests I found that the value of this specific field is always passed as 0 while other filed values are passes empty are they are supposed to.
example url passed: clients/index.php?newfield=0&oldfield=&oldfield2=&oldfield3= 

I can't find the problem.

Any help appreciated

**Comment by tabalinas** [comment]
Sorry, the description doesn't make sense for me. Provide a demo to be able to see the issue (with jsfiddle or any other way), provide source code, screenshot at least. From description the issue is unclear.

**Comment by bux23** [comment]
I have sorted that out, I had a conflict between the value and the index of the select.
