### ISSUE TITLE
Get data from grid

### ISSUE THREAD

**Issue by Volandpro** [tabalinas/jsgrid#415]
I have made a simple grid with editable rows. How can I add a button, which will get data from my grid? (for example, save it in string varibale in JS). Thank you!

**Comment by tabalinas** [comment]
You can get data from the grid just reading the `data` option.

```js
var items = $("#grid").jsGrid("option", "data");
```

**Comment by Volandpro** [comment]
Thank you, it helped a lot) I have one more question - I have row with 2 columns, both with type 'select'. Is it possible to show in column2 items depending on the value of column1? For example, if column1 has value 'A', then I can put in column2 values 'C', 'D'. If column1 has value 'B', then I can put in column2 values 'E','F'. Is it possible?

**Comment by tabalinas** [comment]
Please, checkout the following issue https://github.com/tabalinas/jsgrid/issues/106
