### ISSUE TITLE
Conflit with PHP Curl Request

### ISSUE THREAD

**Issue by backpt** [tabalinas/jsgrid#417]
Hello,

I am having an issue with the loadData of jsGrid when php curl request reaches the connection timeout. With that problem the grids (I have 3 in the main page) crashes for about 2-3 minutes...

I have tried everything... Code in PHP to return response to JS and keep running the PHP Script, but nothing works. The grids only start loading again, when all the curls requests reach the connection timeout.

Right now it's the only problem with my web application and I need to finish that in about 1 week.

Anyone had that problem?

Here's my JS code:
```js
function polling() {
    var dataObject = {
        type: "Polling",
    };

    $.ajax({
        type: 'POST',
        url: "controllers/DatabaseController/",
        data: dataObject,
        success: function(response) {
            console.log(response);
        },
    });
}
```

Database Controller execute that:
```js
$url = "http://172.18.56.132:50000/displayMLProcessor";

        $input = "<displayMLRequest xmlns='http://www.peek.se/DisplayML/' version='1.12'
                          dateTime='2016-07-15T15:30:47'>
            <setDisplay template='Teste'>
                <textField region='Regiao'></textField>
            </setDisplay>
        </displayMLRequest>";

        $ch = curl_init(); 
        curl_setopt($ch, CURLOPT_URL, $url); //Set IP to communicate

        //Set POST XML Input
        curl_setopt( $ch, CURLOPT_POST, 1);
        curl_setopt($ch, CURLOPT_HTTPHEADER, array('Content-Type: text/xml'));
        curl_setopt($ch, CURLOPT_POSTFIELDS, $input);

        //Return response as string & TimeOuts
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
        curl_setopt($ch, CURLOPT_CONNECTTIMEOUT, 10);
        curl_setopt($ch, CURLOPT_TIMEOUT, 10);

        //Execute
        $output = curl_exec($ch); 

        //Importante para tratar os erros
        $httpCode = curl_getinfo($ch, CURLINFO_HTTP_CODE);

        curl_close($ch);

        if($httpCode == 200) {
            echo 0;
        } else {
            echo -1;
        }
```

What I need is to polling fuction run in backgroud, so the app keeps working normally and when I finished the polling(), I just need to refresh the main page with the new results.

Best regards

**Comment by tabalinas** [comment]
I'm not sure how js-grid relates to the problem. `loadData` should return a Promise that should be resolved with the data from the server. If you have client-side polling just on the update put data to the grid (setting `data` option for instance). Thus you will have grid with static content, and you will manage this content your self. In this case don't forget to disabled `autoload: false`.

**Comment by backpt** [comment]
But the results of the polling will only change one jsGrid. I have one grid that is not dependent of polling and the loadData code is that:
```
loadData: function () {
                return $.ajax({
                    type: "GET",
                    url: "controllers/PanelsController/"
					});
            }
```

The results of polling refresh one grid and some icons of page. But with the curl request waiting to reach the timeout just blocks the loadData of all grids. I can't understand why...

**Comment by backpt** [comment]
Sorry for all the messages. I have checked that if I try to do another AJAX Request after the polling as began, the web page only do the second ajax request after the php script is done. 

Can anyone help me pls?
