### ISSUE TITLE
jsGrid Edit cell content modification how to do ?

### ISSUE THREAD

**Issue by Tamizzz** [tabalinas/jsgrid#418]
Hi,

I am kinda new to jsGrid, so the issue is

1. I am creating a table with textarea , if i enter new line and save the table all the text seem to align in one  line and if i open to edit its in new line

Reason : it uses \n while html understands <br>

so can someone help me with a idea how to proceed.

My one approach was

1. While inserting data into db i converted "\n" to `"<br>"`
2. So while displaying it appears in new line
3. But while editing i dont wanna see  <br> so can inbuilt functions like editTemplate or editValue can help me ? If so can you please give me a example,

**Comment by tabalinas** [comment]
Don't convert data on inserting. Just redefine `itemTemplate` and replace your `\n` with `<br>` for the displayed info only. Thus in the DB and during editing you will have original data, while in the display you will also have valid html with proper text wrapping.

**Comment by Tamizzz** [comment]
Hi ,

Thank you for the help. But i still need help on how to use itemTemplate can u demonstrate it with Basic,html.

And another doubt is 

If i replace \n with < br > will i be still seeing <br> while editing the text in the text area ?

**Comment by tabalinas** [comment]
I'm not sure I understand your concerns. 
`itemTemplate` gets the value, so that you can do a replace just like you were doing for inserting. That's it, nothing else should be needed. For the `itemTemplate` signature check the documentation it's straightforward. Of course, if I understand your case correctly.
