### ISSUE TITLE
filter by search input on keyup, how ignore uppercase or lowercase ?

### ISSUE THREAD

**Issue by ferrarisebastian** [tabalinas/jsgrid#420]
Hello, how ignore uppercase or lowercase ?

$('.jsgrid-filter-row').find('input[type=text]').on("keyup", function (e) {
       // this.value
       $("#jsGrid").jsGrid("search");
});

Thanks.

**Comment by lnyuan** [comment]
Hi, were you able to solve this issue? I'm having the same problem :(

**Comment by tabalinas** [comment]
@lnyuan, if you are talking about filtering, then it's all up to your filtering code (usually it's in `controller.loadData` or even on the backend).

**Comment by lnyuan** [comment]
Hi I am trying to make the search case insensitive, and I have tried all the solutions that are found in issues, but it's still not working. Here is the code that I have right now, but I want it to be able to search regardless if user types in letters with uppercase or lowercase: 

`loadData: function(filter) {
                    var d = $.Deferred();
                    $.ajax({
                        type: "GET",
                        url: "/dashboard/data,
                        data: filter    
                    }).done(function(result) {
                        d.resolve($.map(result, function(item) {
                            return $.extend(item.fields, { id: item.pk });
                        }));
                    });
                    return d.promise();
                },`
I also have this segment of code that allows me to search while typing: 

`  //filter while searching
        var originalFilterTemplate = jsGrid.fields.text.prototype.filterTemplate;
        jsGrid.fields.text.prototype.filterTemplate = function() {
            var grid = this._grid;            
            var $result = originalFilterTemplate.call(this);
            $result.on("keyup", function(e) {
            grid.search();
            });
            return $result;
        };   `

**Comment by tabalinas** [comment]
@Inyuan, again the filtering defined in your own code. 
You can find an example of case-insensitive client-side filtering in this issue https://github.com/tabalinas/jsgrid/issues/960
