### ISSUE TITLE
multiple header bad aligned

### ISSUE THREAD

**Issue by valdes** [tabalinas/jsgrid#421]
I make a grid whith multiple header follow #24 and the insert new items row is always visible and the columns are not aligned with the other row in the grid, and how i add the insert button(green plus) to the miltirow header
![grid](https://cloud.githubusercontent.com/assets/1929148/18184372/1937518a-7099-11e6-8841-5e477b340285.png)

**Comment by tabalinas** [comment]
Since you use the custom header renderer, you have to take care of align yourself. 
As for the button you can also create it yourself, just add class `jsgrid-insert-mode-button` and a handler that will toggle `inserting` option.

**Comment by valdes** [comment]
hi tabalinas I looking for and not found how access the jsGrid scripting API to change `inserting` option and refresh the inserting row state

**Comment by tabalinas** [comment]
You can do it with the `option` method http://js-grid.com/docs/#optionoptionname-optionvalue
