### ISSUE TITLE
required validation wrong behavior

### ISSUE THREAD

**Issue by valdes** [tabalinas/jsgrid#422]
I have the following field definition 
```js
fields: [
            { name: "id", type: "text", width: 150, visible: false },
            { name: "request_id", type: "text", width: 150, visible: false },
            { name: "name", title:"Nombre", type: "text", width: 150, validate: "required" },
            { name: "last_name", title:"Apellidos", type: "text", width: 150, validate: "required" },
            { name: "position", title:"Cargo", type: "text", validate: "required" },
            { type: "control" }
        ]
``` 
and whe i try to adding items with validation errors i get the follow
![valid](https://cloud.githubusercontent.com/assets/1929148/18184711/a73fd91a-709a-11e6-866b-5edb3326e088.png)
in this example the field name and last_name are required and not are marked like that and the adding button change his icon for remove icon, but if you complete the required fields it work fine

**Comment by tabalinas** [comment]
Which version of js-grid are you using?

**Comment by valdes** [comment]
you are right, I using version 1.4.1, update to 1.5 a work fine

thank you
