### ISSUE TITLE
batch delete deletes items even if it is not selected

### ISSUE THREAD

**Issue by emekld** [tabalinas/jsgrid#423]
Hi, I am trying to use batch delete but whenever I select only one  item it also deletes the rest of the items. 
Here is the sample code that I am using
`$(function() {
	$("#jsGrid").jsGrid({
    height: "70%",
    width: "100%",
    filtering: true,
    editing: true,
    inserting: true,
	onItemUpdating: function (args){
		previousBank = args.previousItem;},
    sorting: true,
    autoload: true,
    rowClick: function(args) {},
    deleteConfirm: "Do you really want to delete this record?",
    controller: db,
    fields: [
   	 {
                headerTemplate: function() {
                    return $("<button>").attr("type", "button").text("Delete")
                            .on("click", function () {
                                deleteSelectedItems();
                            });
      			},
                itemTemplate: function(_, item) {
                 return   $("<input>").attr("type", "checkbox")
                            .prop("checked", $.inArray(item, selectedItems) > -1)
                            .on("change", function () {
                                if($(this).is(":checked")) {
                            selectedItems.push(item);
                        } else {
                            selectedItems = $.grep(selectedItems, function(i) {
                                 return i !== item;
                            });
                        }
                            });
                },
                align: "center",
                width: 50
        },
		{name: "countryName", title: "Country Name", type: "text", width: 150},
		{name: "cityCode", title: "City Code",type: "text", width: 50},
		{name: "currencyCode", title: "Currency",type: "text", width: 50},
		{name: "effectivityDate", title: "Effectivity Date",type: "date", myCustomProperty: "bar", width: 150},
		{name: "expiryDate", title: "Expiry Date",type: "date", myCustomProperty: "bar", width: 150},
		{name: "activeInd", title: "Active Index",type: "checkbox", title: "Active Index", sorting: false},
		{name: "rawCountryCode", title: "Raw Country Code",type: "text", width: 50},
		{name: "rawCityCode", title: "Raw City Code",type: "text", width: 50},
		{name: "patternName", title: "Calendar Pattern",type: "text", width: 150},
		{name: "lagDays", title: "Lag Days",type: "text", width: 50},
		{name: "lastUpdateTimestamp", title: "Last Update Gts",type: "text", width: 150},
		{name: "lastUpdateUser", title: "Last Update User",type: "text", width: 150},
		{ type: "control" }
	]
 });
 var selectedItems = [];
 
    var selectItem = function(item) {
        selectedItems.push(item);
    };
 
    var unselectItem = function(item) {
        selectedItems = $.grep(selectedItems, function(i) {
            return i !== item;
        });
    };
 
    var deleteSelectedItems = function() {
        if(!selectedItems.length || !confirm("Are you sure?"))
            return;
        deleteClientsFromDb(selectedItems);
 		
        var $grid = $("#jsGrid");
        $grid.jsGrid("option", "pageIndex", 1);
        $grid.jsGrid("loadData");
 
        selectedItems = [];
    };
 
    var deleteClientsFromDb = function(deletingBanks) {
        $.each(deletingBanks, function(_, item) {
        $("#jsgrid").jsGrid("deleteItem", item);
    });
    };
});`

**Comment by emekld** [comment]
We already found out the problem. It is not with the delete but with how we insert data it is not pushed in the db so when the load data is executed it did not include the added data

**Comment by tabalinas** [comment]
Glad that you figured it out.
