### ISSUE TITLE
(Possible) support for keys containing dots

### ISSUE THREAD

**Issue by tonisostrat** [tabalinas/jsgrid#424]
```javascript
$('#grid-container').jsGrid({
    //other stuff
    data: [
        {
            name: 'Foo',
            bar.count: 4
        }
    ],
    fields: [
        {
            title: 'Pretty name',
            type: 'text',
            name: 'name'
        },
        {
            title: 'Pretty bar count',
            type: 'number',
            name: 'bar.count'
        }
    ]
});
```
Currently the second column of the provided table is always empty because jsGrid cannot find `data[0].bar.count`, because it's "only" accessible through `data[0]['bar.count']`.

I understand if this can/is considered an edge case as dots in object properties do create confusion. I have implemented a workaround where I sanitize the keys by replacing all dots with underscores and it works just fine.

My question is: would it be worth it to consider an additional configuration item (i.e. `acceptDotNotation`) that, when enabled, changes the internal key lookup method to use escaped properties in brackets instead of plain ones like right now?

**Comment by tabalinas** [comment]
Indeed, interesting case. This is currently not supported. I'm not sure it's worth it to overcomplicate things. Let see if we have more requests like this.
For now you could easily map data on the client in `loadData` method, right?

**Comment by tonisostrat** [comment]
Yeah, like I said in the original post, I have implemented a workaround that handles this case.
