### ISSUE TITLE
 Disabled edit checkbox "IsDefault" if "IsDeleted" = true

### ISSUE THREAD

**Issue by ferrarisebastian** [tabalinas/jsgrid#425]
How get index  row ?

<img width="420" alt="capture" src="https://cloud.githubusercontent.com/assets/8854368/18284365/0a72acbc-7440-11e6-84e5-c791dc1f6f44.PNG">

**Comment by tabalinas** [comment]
`editTemplate` has an item itself as a second parameter, so you don't need index.
