### ISSUE TITLE
Replace validation browser alert() to custom function

### ISSUE THREAD

**Issue by 7654098** [tabalinas/jsgrid#427]
Hi, Artem.

Is it possible to replace validation browser alert() to custom function?

Regards!

**Comment by 7654098** [comment]
Done by editing source code.

**Comment by tabalinas** [comment]
No need to customize the source code. There is a special option to redefine `invalidNotify(args)`. See the docs http://js-grid.com/docs/#invalidnotify.

**Comment by 7654098** [comment]
Thank you!
