### ISSUE TITLE
Can i use pageFormat in pageRenderer function with a dropDown for change page size?

### ISSUE THREAD

**Issue by pichlou** [tabalinas/jsgrid#428]
pageFormat:  masterLang.page+": {first} {prev} {pages} {next} {last}    {pageIndex} "+masterLang.From +" {pageCount}    &nbsp;&nbsp;"+masterLang.count_all+": {itemCount}

this my pageFormat,i want to use a drop down with default selected pagesize option in pageRenderer.

**Comment by tabalinas** [comment]
You can call a private function on the grid instance `_createPagerByFormat()` inside the `pageRenderer`. This method returns a usual pager. So you can change any element you wish and of course append any dropdown to customize pager.
