### ISSUE TITLE
Soft Delete

### ISSUE THREAD

**Issue by screamingweasel** [tabalinas/jsgrid#429]
We are saving all of the changes to the grid and then submitting at once. We keep a status for each row and change it when adding or updating to make fewer database calls. My question is if we can "soft" delete a row by setting this status value, then filtering the row from display while keeping it in the actual grid data.

**Comment by tabalinas** [comment]
You could the following: in `deleteItem` set the field (for instance `isDeleted`) to `true` of the item and in `loadData` filter out this items. This should work.
