### ISSUE TITLE
After deleteItem()  stop loadData  or loadData current page

### ISSUE THREAD

**Issue by ROKAISAKKON** [tabalinas/jsgrid#43]
```javascript
deleteItem : function ( item ) {
     ..
     ..
     ..
     //code stop loadData  ??
     //code loadData  current page  Not loadData first page
}
```

After deleteitem it loadData  first page  every time T-T

**Comment by tabalinas** [comment]
The behavior of `deteleItem` depends on current loadStrategy. There are two build-in load strategies: DirectLoadingStrategy (for `pageLoading`=false) and PageLoadingStrategy (for `pageLoading`=true). 

It's not yet described in docs, but you can create custom load strategy and specify it with `loadStrategy` option.

In your case it's easier to redefine current `finishDelete`method of current strategy. 
 
Current implementation:

```javascript

// DirectLoadingStrategy
finishDelete: function(deletedItem, deletedItemIndex) {
    var grid = this._grid;
    grid.option("data").splice(deletedItemIndex, 1);
    grid.reset();
}

// PageLoadingStrategy
finishDelete: function(deletedItem, deletedItemIndex) {
    this._grid.search();
}

```

Thus direct loading removes item from `data` and calls `reset`, while page loading just calls `search` method.

You can redefine default behavior. For instance to prevent entire grid reset replace it with `refresh`:

```javascript
jsGrid.loadStrategies.DirectLoadingStrategy.prototype.finishDelete = function() {
    var grid = this._grid;
    grid.option("data").splice(deletedItemIndex, 1);
    grid.refresh();
}
```

Hope it will help.
