### ISSUE TITLE
Row index and number of rows displayed

### ISSUE THREAD

**Issue by bux23** [tabalinas/jsgrid#430]
Hello,

I was atrying to achieve two different option but unsucessfully.

1. trying to add a field that shows row index number (regardless of the sorting). tried to follow what said on issue [#326](https://github.com/tabalinas/jsgrid/issues/326) but it doesnt provide a full snippet and explanation.
Adding an index field to the data wont work as needed since entries (loaded from mysql in my case) could be deleted, and what I am looking for is a progressive index number of the entries displayed

2. Would like to add a dropdown to select the number of rows displayed per page

**Comment by tabalinas** [comment]
For the 1st: What is the problem with proposed in #326 solution? Have you tried to implement it?
For the 2nd: you have `pageSize` option - just set it once you change the dropdown value.

For future requests: please, don't mix two different questions in a single issue.

**Comment by bux23** [comment]
The solution in [#326](https://github.com/tabalinas/jsgrid/issues/326) is not well explained since the snippets are incomplete and their use is not explained: 
`$("#grid").jsGrid({
rowClass: function(item, itemIndex){
}
})` alone does nothing, and
`fields: [ {name: "#", title: "#", itemTemplate: function(){ //increment } },`
does not have the code which increments... only //increment

Any chance you could provide full code and  example so that I could understand and implement the feature?

**Comment by tabalinas** [comment]
You need to do literally what's written in the answer:

> map your data on the client adding a specific field (e.g. index) to the data themselves in controller.loadData function. And then bind this index field to the field of the grid.

```js
{
	... 

    controller: {
        loadData: function() {
        	var d = $.Deferred();

        	$.ajax({ ... }).done(function(result) {
        		d.resolve($.map(result, function(item, itemIndex) {
        			return $.extend(item, {
        				myIndexField: itemIndex + 1
        			})
        		}));
        	});

        	return d.promise();
        }
    },

    fields: [
    	...

    	{ name: "index", ... }
    ]
}
```

Code is not tested, just showing the principle.

**Comment by neo1afshin** [comment]
i use below code
$("#jsGrid").jsGrid({
            height: "auto",
            width: "100%",
            sorting: false,
            pageLoading: true,
            paging: false,
            autoload: true,
            controller: {
                loadData: function () {
                    var d = $.Deferred();
                    var searchParam = { FirstName: $("#firstName_textbox").val(), LastName: $("#lastName_textbox").val() };
                   return $.ajax({
                        type: "POST",
                        data: { "searchParam": searchParam, "currentPage": currentPage, "pageSize": pageSize },
                        contentType: "application/x-www-form-urlencoded; charset=UTF-8",
                        url: "/Users/GetUsers",
                        dataType: "json",
                        error: function (e, s) {
                            alert(s);
                        },
                    }).done(function (result) {
                        d.resolve($.map(result.data, function (item, itemIndex) {
                            return $.extend(item, { "Index": itemIndex + 1 });
                        }));
                        if (result.Result) {
                            $("#userdatapager_rowcount").html(result.itemsCount);
                            rowCount = result.itemsCount;
                            $("#userdatapager_currentpage").val(currentPage);
                            setTotalPages();
                        }
                    });
                }
            },
            selectable: true,
            rowClick: function (args) {
                var $row = this.rowByItem(args.item);
                var trow = $("tr.highlight");
                trow.removeClass("highlight");
                $row.addClass("highlight");
                selectedItem = args.item;
                RaiseCanExecuteCommands();
            },
            fields: [
                { name: "Index", title: "ردیف", type: "number", width: 30, align: "center", },
                { name: "UserID", title: "نام کاربری", type: "text", width: 70, align: "center", },
                { name: "FirstName", title: "نام", type: "text", width: 70, align: "center", },
                { name: "LastName", title: "نام خانوادگی", type: "text", width: 70, align: "center", },
                { name: "RoleName", title: "نقش", type: "number", width: 60, align: "center", },
                { name: "GroupID", title: "گروه بانک", type: "number", width: 30, align: "center", },
                { name: "IsActive", type: "isactivefield", title: "فعال", width: 20 },
            ]
        });
