### ISSUE TITLE
Nested grid titles with ajax call

### ISSUE THREAD

**Issue by arulmoli** [tabalinas/jsgrid#431]
Hi Artem:

You had created a nested grid as below. I wanted to have multiple column header in the parent grid and when we click on each row (using + sign is preferred), it should display 3 columns in the nested grid with values. I couldn't create that. Please help. 

My code is attached as well (but that makes an ajax call and i also attached the data returned by the ajax call and my grid output)

Your sample code:
basic example of nested grid:  http://jsfiddle.net/tabalinas/vc1wm99n/
---------------------------------------------------------------------------------------------------------------
 
Index.html code shown at the end of this document does the following:
Which actually makes an ajax call and using the response returned, the code
a)	Populates a main grid which has 4 columns: StatusId, ExecStartTime, Status, MachineName”.
b)	Populates a nested grid with 2 columns: Name and description.
Questions:
(1)	In the main grid, how do I display more than one column? How do I have + sign instead of a link for the row item and clicking on it should bring a nested grid.
(2)	Nested grid values are NOT aligned with the header – how do I do this?
```html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title></title>

    <link type="text/css" rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jsgrid/1.5.2/jsgrid.min.css" />
    <link type="text/css" rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jsgrid/1.5.2/jsgrid-theme.min.css" />

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jsgrid/1.5.2/jsgrid.min.js"></script>

    <script>
        $(document).ready(function () {
            $("button").click(function () {
                $.ajax({
                    url: "http://localhost:8080/api/executionreport/1", success: function (result) {
                        $("#div1").html(result);
                    }
                });
            });

            var reptsFullData = [];

            $(function () {

                // JS plugin is from (spell correction - http): htt://js-grid.com/demos/
                $("#jsGrid").jsGrid({
                    height: "auto",
                    width: "100%",

                    sorting: true,
                    paging: false,
                    autoload: true,

                    controller: {
                        loadData: function () {
                            var d = $.Deferred();

                            $.ajax({
                                //url: "http://services.odata.org/V3/(S(3mnweai3qldmghnzfshavfok))/OData/OData.svc/Products",
                                url: "http://localhost:8080/api/executionreport/1",
                                
                                dataType: "json"
                            }).done(function (response) {
                                

                                // TODO - Below code expects single object (as of the current web api)
                                // TODO - Later we might need to change web api to return list...and handle here as list.
                                /*
                                 var runtimeJson = JSON.parse(response.data);
                                 for (var i = 0; i < runtimeJson.length; i++) {
                                     repts.push(runtimeJson[i]);
                                     repts[i].ExecStopTime = $filter('getDiff')(runtimeJson[i].ExecStartTime, runtimeJson[i].ExecStopTime);
                                 }
                                 */

                                // Need to convert to JSON object. Then Push it in an array because the jsgrid expects "Array" kind of type such as: array[0..n]
                                var runtimeJson = JSON.parse(response);

                                // Need to push into array since the grid control expects array (rather than a big json type of response string).
                                reptsFullData.push(runtimeJson);

                                d.resolve(reptsFullData);
                            });

                            return d.promise();
                        }
                    },

                    fields: [
                        { name: "StatusId", type: "text" },
                        { name: "ExecStartTime", type: "textarea", width: 150 },
                        {
                            name: "Status", type: "text", width: 50, align: "center"
                        },
                        {
                            name: "MachineName", type: "text", width: 50
                        }
                    ],

                    rowRenderer: function (item) {
                        var $row = $("<tr>");
                        var $cell = $("<td>");

                        var $addressesGrid = $("<div>").addClass("nested-grid").hide();

                        $addressesGrid.jsGrid({
                            height: "auto",
                            width: "100%",
                            data: item.TestCasesStatus,             // selected row is "item" - not the object name. You have to give "item" alwaays.   
                            heading: true,                          // To display heading or not.
                            fields: [
                                { name: "Name", type: "text", width: 200, align: "center" },
                                { name: "Description", type: "text", width: 200, align: "center" }
                            ]
                        });

                        var $link = $("<a>").text(item.AutName)
                                                  .prop("href", "#")
                                                  .click(function () {
                                                      $addressesGrid.toggle();
                                                  });

                        $cell.append($link)
                          .append($addressesGrid);

                        return $row.append($cell);
                    },

                });

            });

        });
    </script>
</head>
<body>

    <div id="div1"><h2>Ajax Returned value goes here</h2></div>
    <button>Ajax call</button>

    <div id="jsGrid"></div>

</body>
</html>


<!--<!DOCTYPE html>

<html lang="en" xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta charset="utf-8" />
    <title></title>
</head>
<body>

    <script src="http://code.jquery.com/jquery-1.10.2.min.js"></script>

    <a href="Java Collections.html" class="button" id="javacollections" onclick="do_the_click('this.href');">Java Collections</a>

    <script>
        function do_the_click(url) {
            alert('inside this method do_the_click');
            $.ajax({
                async: false,
                url: url,
                contentType: "text/html",
                type: "GET",
                dataType: "text/html",
                success: function (data) {
                    alert('data');
                }
            });
        }
    </script>
</body>
</html>-->
```

**Comment by tabalinas** [comment]
As you can see, you have `rowRenderer` which creates `<tr>` and `<td>` for the grid. So you can create whatever is needed. Add several tds instead of a single in the example (for instance, the first will have a plus button which will expand the nested grid). To have proper header create also according `<th>` cells with `headerRowRenderer`.

**Comment by arulmoli** [comment]
Hi Artem: Thank you! Is there a way you could show me some sample quickly please in your basic example of nested grid: http://jsfiddle.net/tabalinas/vc1wm99n/ with 3 columns in the parent grid and 3 columns in the nested grid with column headers showing and values underneath please? Your help is very much appreciated. I tried. I am not able to get it right. Thanks a lot.

**Comment by tabalinas** [comment]
What was the issue when you tried to do it yourself?
Feel free to fork the fiddle, and show the issues, so it will be possible to fix them on the real example.

**Comment by arulmoli** [comment]
I tried the following in your fiddle. Please bear with me that i am sort of new to fiddle and not too good with javascript. In the following code, all i am trying to do is, add "Name", "Age" columns in the parent grid and nested grid to have "Address", "City" column. I could not solve two problems. Age - value does not show up in the parent grid. Nested grid when you click on the "Name" link, does NOT show "City column". Thanks a lot. Code is below that goes with your fiddle, not sure i will be able to save my changed below in there, perhaps i have to create a new fiddle?
http://jsfiddle.net/tabalinas/vc1wm99n/

var data = [
    {
        "Name": "Otto Clay",
        "Age": "25",
        "Addresses": [
        	{ Address: "Home Address", City: "City1" },
          { Address: "Work Address", City: "City1" },
          { Address: "Post Address", City: "City1" }
        ]
    },
    {
        "Name": "Connor Johnston",
        "Age":"26",
        "Addresses": [
        	{ Address: "Home Address", City: "City1" },
          { Address: "Work Address", City: "City1" },
          { Address: "Post Address", City: "City1" }
        ]
    }
];

$("#jsGrid").jsGrid({
        height: 300,
        width: "100%",
 
 				paging: true,
        autoload: true,
 
        pageSize: 2,
 
        controller: {
        	loadData: function() {
          	return data;
          }
        },
        
        fields: [
            	{ name: "Name", width: 200 },
              { name: "Age", width: 200 },
        ],
        
        rowRenderer: function(item) {
        	var $row = $("<tr>");
          var $cell = $("<td>");
          
          var $addressesGrid = $("<div>").addClass("nested-grid").hide();
          
          $addressesGrid.jsGrid({
          	width: 200,
            height: "auto",
            data: item.Addresses,
            heading: true,
            fields: [
            	{ name: "Address", width: 200 },
              { name: "City", width: 200 },
            ]
          });
          
          var $link = $("<a>").text(item.Name)
          							.prop("href", "#")
          							.click(function() {
                        	$addressesGrid.toggle();
                        });
          
          $cell.append($link)
          	.append($addressesGrid);
            
          return $row.append($cell);
        }
    });
