### ISSUE TITLE
how to get item while click a custom button cell

### ISSUE THREAD

**Issue by marwan118** [tabalinas/jsgrid#432]
i have two questions,but first of all, thank you very much to your work.
1.i need to know which row(or get the row item) where button lies in when i click that button 
2.is there a way to resize the column width by mouse dragging
thank you very much again.
![2016-09-10 14-17-12](https://cloud.githubusercontent.com/assets/14876021/18408404/8775d56c-7761-11e6-8945-fd62fd08f00b.png)

**Comment by tabalinas** [comment]
Thank you for the feedback!

1) In `itemTemplate` which will create a button, you have as a second parameter the item. So it should be in the closure of the button click handler. To get the row by item use the method http://js-grid.com/docs/#rowbyitemitem-jqueryelement

2) It's not supported currently. There is an issue for this enhancement https://github.com/tabalinas/jsgrid/issues/9

**Comment by marwan118** [comment]
thank you very much for the reply,that helps a lot.
but i myself figure another way to do this.
when i create that button in the itemTemplate  i  set the row element(something like an id) to the button class with prefix ,something like passButton_idxxxxxxxx,then i find all that kind of button ,and bind the click event handler to those button which infomation(id) contains in the button class attrib, and that is all i need right now.
i dont knwo if it is elegant or not , but it works.
by the way, there is  one more thing to do , i have to rebind all those event handler when onRefreshed event fired,otherwise the handler going down when something like deleting , sorting and something else cause the gird to refresh. which i dont know the reason ...

thank very much again.

**Comment by tabalinas** [comment]
The reason, is that grid items are rendered again on grid refresh. So new buttons don't have handlers anymore. That's why maybe better alternative would be bind handler directly in `itemTemplate`.

**Comment by marwan118** [comment]
yes, you are right.i did it in your way and thanks A lot bro👍🤓
