### ISSUE TITLE
can i select all rows in page with select_all button and checking checkbox in rows?

### ISSUE THREAD

**Issue by pichlou** [tabalinas/jsgrid#433]
i want to select some rows in grid with checkbox and also use  button to select all of loaded rows in current page,and do something such as ajax request for deleting selected rows.
is this possible?

**Comment by tabalinas** [comment]
Yes, it's possible (as almost anything J). First checkout `Batch Delete` demo scenario http://js-grid.com/demos/. 
And to add `Select All` functionality checkout for instance this fiddle http://jsfiddle.net/NogginBox/ScnQT/1/

**Comment by pichlou** [comment]
i cant use keyboard control such as "shift" or "ctr"l for multi selecting rows
