### ISSUE TITLE
does jsGrid allow sub columns?

### ISSUE THREAD

**Issue by VEDA95** [tabalinas/jsgrid#435]
I was looking through some of the documentation for the library and I had one question. Is it possible to create sub-columns for a heading column? Some of my data has sub-columns in it and I would like to display the sub columns along with their respective parent columns.

example: [http://imgur.com/a/UpWQb](url)

**Comment by tonisostrat** [comment]
Not out-of-the-box. There are a few ways you can achieve this, though.

You can leverage the **jsGrid** library functionality by overriding `[headerRowRenderer()](http://js-grid.com/docs/#headerrowrenderer-default-null)` but that would require you to render the whole header yourself.

You can also, after the table has been rendered and added to the DOM, use **JQuery** or the like to inject another `<tr>` into `.jsgrid-grid-header > .jsgrid-table` that has `<th>` elements with `colspan` attribute.

**Comment by tabalinas** [comment]
In addition to @tonisostrat checkout this issue https://github.com/tabalinas/jsgrid/issues/24
