### ISSUE TITLE
How to apply sorting after filtering

### ISSUE THREAD

**Issue by tipmaster** [tabalinas/jsgrid#436]
This may be a trivial issue that I haven't been able to solve; how can I apply sorting to my table right after a filtering has been performed. A quick code snippet would be immensely helpful. This is my current filtering code:

```js
loadData: function(filter) {
	            
	      		return $.grep(clients, function(client) {
	                return (!filter.language || client.language.indexOf(filter.language) > -1)
	                &&  (!filter.keyword || client.keyword.indexOf(filter.keyword) > -1)
	                });
	      	  
	        }, 
```

**Comment by tabalinas** [comment]
It depends on how you load data. You could turn of autoload (`autoload: false`), load data yourself, calling `loadData` method of the grid. This method returns a `Promise`, so on `done` of it call `sort` method of the grid.

```js
$("#grid").jsGrid("loadData").done(function() {
    $("#grid").jsGrid("sort", /* put sorting params here */);
});
```
