### ISSUE TITLE
Row Up/Down to Move and Save in Db

### ISSUE THREAD

**Issue by alpeshkasodariya** [tabalinas/jsgrid#438]
Hello,

We want to row up/down to move and also save in db.
We are referring Column reordering example but can't get solution.
Could you please help us for row move to store db ?

Any help would be appreciated .

Thanks

**Comment by tabalinas** [comment]
Do you have any particular question about the Row Reordering demo?
What's unclear exactly?

**Comment by alpeshkasodariya** [comment]
No,
We just referring below demo though with Rows Reordering.and trying and demo has not save in DB.But We are trying.
http://js-grid.com/demos/

please give me help or hint suggestion.So i can try it.

Thanks

**Comment by tabalinas** [comment]
If I got your question correctly, you need to call backend endpoint instead of `console.log` in the example, to save the order. Obviously, you need to have an `Order` field in the DB which you will set for items (you can send to backend either indices or item ids).
