### ISSUE TITLE
Grid stopped loading

### ISSUE THREAD

**Issue by bux23** [tabalinas/jsgrid#439]
My grid stopped loading data today and only diplays the not found div.

I havent changed anythins and my console shows not error.
My apache registry says:
mod_fcgid: stderr: PHP Notice: Undefined index: id in /data/vhosts/facileristrutturare.it/httpdocs/marketing/jsgrid/clients/index.php on line 13

The id filed obviously exists in my table. 
Any help appreciated

**Comment by tonisostrat** [comment]
If you're absolutely certain that there haven't been any code changes then the first thing I would think is to look at the actual dataset you're trying to push into the table. Maybe that has changed, maybe the items don't contain a proper **id** field anymore?

**Comment by tabalinas** [comment]
Try to find problems in you backend.
