### ISSUE TITLE
retrieving all rows

### ISSUE THREAD

**Issue by sergiofactvs** [tabalinas/jsgrid#44]
Hi, there is a method to retrieving all rows, including custom fields, from the jsgrid?

**Comment by tabalinas** [comment]
What do you mean by 'retrieving all rows`?

**Comment by sergiofactvs** [comment]
i mean, all data rows in the jsgrid, im looking for evaluate some custom fields like checkbox.
i know that can be done with js array filled in the custom field, but i wanna know if there other way.

Thx.

**Comment by tabalinas** [comment]
You can get all data items from `data` option

```javascript
var items = $("#jsGrid").jsGrid("option", "data"); 
```

Of course, if `pageLoading` is `true` you will got only data for the current page.
