### ISSUE TITLE
Cannot get items from grid when upgrading from jQuery 2.2.4 to 3.1.0

### ISSUE THREAD

**Issue by neriks** [tabalinas/jsgrid#440]
Hi,

Thanks for an excellent grid plugin! :-)

I recently upgraded jQuery from version 2.2.4 to 3.1.0. After the upgrade I cannot get items from the grid. The Grid('option', data) method simply returns an empty array!??

`var items = $('#grid').jsGrid('option', 'data');`

**Comment by tabalinas** [comment]
Are you sure it worked before the update?

**Comment by neriks** [comment]
Sorry , my mistake ... I've solved it! ;-) I assume that the items shouldn't be 'available' until loadData has completed ... But when using jQuery 2.2.4 the following code seem to work in my case!?

```
      controller: {
        loadData: function(filter) {
          var d = $.Deferred();
          $.ajax({
            type: 'GET',
            url: '/Home/UsersPage',
            data: {
              groupName: group
              pageSize: filter.pageSize,
              pageIndex: filter.pageIndex,
            },
            dataType: 'json',
          }).done(function(result) {
            d.resolve(result);

            ... ... ...
            var items = $("#grid").jsGrid("option", "data");
            ... ... ...

          }).fail(function() {
            d.reject();
          });
          return d.promise();
        },
      },

```
When I upgrade to jQuery 3.1.0 the code above stopped working. I moved Grid('option', data) method to the onDataLoaded event which solved the issue.

```
      onDataLoaded: function(args) {
         ... ... ...
          var items = $('#grid).jsGrid('option', 'data');
          ... ... ...
      }
```

**Comment by tabalinas** [comment]
There should not be difference between 2.4 and 3.1 in this case. Not sure, maybe it was synchronous, and now you made it asynchronous.
Anyway, glad that you figured it out.

BTW you can get `data` from args of the callback http://js-grid.com/docs/#ondataloaded
