### ISSUE TITLE
Unknown locale es

### ISSUE THREAD

**Issue by luisRojas29** [tabalinas/jsgrid#443]
Hello @tabalinas great plugin... give us in the company a lot of solutions... but I have faced a little issue, when loading the localization file, for es language... it gets me an Uncaught Error: unknow locale es.

Could you please help me solve this problem?
This is in my header...
```html
<link type="text/css" rel="stylesheet" href="<%= path%>/js/jsGrid/jsgrid.min.css" />
	<link type="text/css" rel="stylesheet" href="<%= path%>/js/jsGrid/jsgrid-theme.min.css" />
	<script type="text/javascript" src="<%= path%>/js/jsGrid/jsgrid.min.js"></script>
	<%  if( locale  != null && locale.toString().equals("es_MX") ) { %>
	<link type="text/css" rel="stylesheet" href="<%= path%>/js/jsGrid/i18n/jsgrid-es.js" />
	<% } %>
```

And then my js goes like:

```html
<script type="text/javascript">
 $(document).ready(function(){ 
	 jsGrid.locale("es");
	 $("#jsGrid").jsGrid({
</script>
...

```

**Comment by tabalinas** [comment]
Are you sure the locale file is linked? 
Since you have a condition for the `<link>`, maybe it's not `true`?

**Comment by luisRojas29** [comment]
Is it there, because I can see it using dev tools...

**Comment by tabalinas** [comment]
I guess then it's because you are linking js script as a cs stlysheet J
`<link type="text/css" rel="stylesheet"`

**Comment by luisRojas29** [comment]
.o. fool of me... didn't notice that detail... thanx a lot, works like a charm...
