### ISSUE TITLE
submit edited rows only to the server 

### ISSUE THREAD

**Issue by RonakKosamia** [tabalinas/jsgrid#445]
hi  @tabalinas , 

can you help me with this issue.  m editing few rows in jsgrid, when i click on "submit" button , only those edited rows should get submitted on server.  i have more than 5000 records in a grid and i can not save all of them (will take a lot time). i just want to submit rows that edited by user.

**Comment by tabalinas** [comment]
Hi,

In `updateItem` of controller mark item as edited, for instance `item.isEdited = true`. Once you submit data, filter out only edited items. 
This should do the trick.

**Comment by RonakKosamia** [comment]
can you tell me where ??? 

updateItem: function(item, editedItem) {
         if(arguments.length === 1) {
                editedItem = item;
            }

            var $row = item ? this.rowByItem(item) : this._editingRow;
            editedItem = editedItem || this._getValidatedEditedItem();

            if(!editedItem)
                return;

            return this._updateRow($row, editedItem);
        
        },

**Comment by tabalinas** [comment]
I'm not talking about the source code of jsgrid. You have to define it in the `controller.updateItem`. Checkout demos and docs on the project site http://js-grid.com/
