### ISSUE TITLE
Change table Style

### ISSUE THREAD

**Issue by am2222** [tabalinas/jsgrid#449]
Hi,
Is there any way to modify tables style?or any examples?thanks

**Comment by tabalinas** [comment]
There are two stylesheets for js-grid: core stylesheet defining layout, and theme stylesheet. You can modify styling redefining css rules. Class names are quite straightforward (see the source on cdn https://cdnjs.cloudflare.com/ajax/libs/jsgrid/1.5.2/jsgrid-theme.css)
