### ISSUE TITLE
Different location for Add button

### ISSUE THREAD

**Issue by jhammer2** [tabalinas/jsgrid#45]
Is there anything currently built in to allow the add button to be placed in a different location? It currently gets put on the page using the headerTemplate. I did not see anything in the documentation that generates anything for a footer.

**Comment by tabalinas** [comment]
Actually, add button can be anywhere. You can redefine any template of `control` or any other field (filterTemplate, insertTemplate, headerTemplate). Or you can just add this button outside the grid (above or below up to you).

All you need is to call grid API

to show/hide inserting row change `inserting` option: 

```javascript
$("#jsGrid").jsGrid("option", "inserting", isInserting);
```

to insert item with data filled in inserting row:

```javascript
$("#jsGrid").jsGrid("insertItem");
```
