### ISSUE TITLE
How to get error message from onError

### ISSUE THREAD

**Issue by am2222** [tabalinas/jsgrid#451]
Hi,
If I return an error respond from server for example this one
` return Response::json(['error' => 'Error msg'], 404); // Status code here`

The above code is a response using `Laravel`, anyway how can I get error message from `onError `Calback?
I don't know how to get it from args ,Is it even possible?
thanks

**Comment by tabalinas** [comment]
All arguments provided to fail handler by your ajax call will be as an array in `args` field as it's stated in the docs http://js-grid.com/docs/#onerror.

```js
onError: function(e) {
    console.log("Error message: " + e.args[0]);
}
```
