### ISSUE TITLE
how to write unique validator

### ISSUE THREAD

**Issue by samuelrobertson** [tabalinas/jsgrid#452]
Suppose you wanted a validator to validate unique row values in column. Very useful for many data entry scenarios (I ran into this at work) 

So I tried writing a unique validator. Its easy to write insert validator but hard to write edit validator because you need to know current row number when looping through grid data column (because that id is allowed to be there!). Can you suggest how to write the validation function? If you don't want to no problem because your js grid works great! I already have it working on insert new row.

Maybe you could even have a built-in validator called "unique"? That would be awesome!

**Comment by tabalinas** [comment]
To talk about uniqueness we should specify the field that should be unique. Validator for being unique by some `id` field, sounds a bit weird for me, since you usually don't specify the `id` when you insert an item (the same for edit). The uniqueness for a specific string field also seems quite rare, so I'm not sure about having this kind of built-in validator. Maybe I'm missing something here.

As for the custom validator, you basically should read items of the grid and check uniqueness. This should work.

**Comment by samuelrobertson** [comment]
I mean validating by the string field. I suppose its not too common. In the app I'm writing they can input codes into your grid which must be unique and they can also select from one of eight life insurance companies  and those must be unique too.

The reason its hard to write a custom validator on edit is because on insert you just check to see if the inserted value is already in the grid data. However, on edit, its already in there (imagine you just click on a row with the value and click save without changing it). So you can't simply loop through the data and look for that value. If the edit row index was passed into the validator callback, you could do it, since you would ignore the value if it was at that row index.

But anyway, my problem is solved. I do a quick Ajax server side check before the page even posts back and display the error message. The client just asked for it to be displayed as soon as they click the green check mark. (It is on add, but not on edit)

JsGrid was the best grid I found out there. DataTable Editor just didn't have the features I needed. Could jsGrid ever make it into the standard jquery ui widget library?

**Comment by tabalinas** [comment]
js-grid is based on jQuery, not jQuery UI. So there is no point to include it in jQuery UI.
