### ISSUE TITLE
Column width issue, data spilling into next column

### ISSUE THREAD

**Issue by hk298** [tabalinas/jsgrid#453]
Some people asked about flexible grids before. Resizing (#9) would be really nice. I currently have something like this:
![s1](https://cloud.githubusercontent.com/assets/15907767/19050135/4512c1cc-897b-11e6-9769-2eeece5eeaeb.png)
Obviously, some _lastdata_ strings are too long, and since they don't contain spaces, they are not broken into multiple lines. I could attempt to write a cell renderer that truncates the strings and adds an ellipsis. However, that makes sense only when the columns are re-sizable since otherwise the user won't be able to see the truncated part. For now I'm stuck with making the column large enough so that the data fits. Or are there other solutions? Tool tips maybe? This table is for viewing only, no editing. I could allow editing and have the backend do nothing, but this would be a bit awkward for the user.

**Comment by tabalinas** [comment]
Have you checked this one https://github.com/tabalinas/jsgrid/issues/450?
And yes, you could wrap cell content in a `<div title="/*put your field value here*/"><div>` so you will have tooltip for the content.

**Comment by hk298** [comment]
Neat! I'm using both now, `overflow: hidden` and the `div` you suggested. Still, adjustable columns would be really nice.

**Comment by tabalinas** [comment]
What do you mean by `adjustable columns`?

**Comment by hk298** [comment]
I meant resizable coloumns as mentioned in #9.

**Comment by drakans** [comment]
Hello tabalinas, I also really need to resize columns. do you have an workaround ? 
something like 
$( "#jsgrid-table tr th" ).resizable({
		      handles: 'e'
});
shouldn't work ?

Thanks by advance 
Steph

**Comment by tabalinas** [comment]
@drakans: frankly, I have not try it, but would be cool if you play with it and share results.
Could you +1 on the original feature request https://github.com/tabalinas/jsgrid/issues/9?
