### ISSUE TITLE
Filter ranges

### ISSUE THREAD

**Issue by hk298** [tabalinas/jsgrid#454]
Here's a crazy idea:
Strings can be filtered nicely with the `LIKE` comparison as shown in the examples. In the case of integer values and time stamps I would like to be able to filter by intervals, i.e. show what's >= x and <= y. Of course, I could use a filter string and define a simple syntax that the backend could parse. I could also have two text boxes outside the grid to enter the boundaries. However, it would be really cool if filter fields could be split into two:
![s2](https://cloud.githubusercontent.com/assets/15907767/19050972/ee4c3914-897e-11e6-9b9c-f74aed3b5d7e.png)

**Comment by tabalinas** [comment]
Yes, there is already a suggestion for that https://github.com/tabalinas/jsgrid/issues/29
