### ISSUE TITLE
Set item 'readOnly' based on another field value

### ISSUE THREAD

**Issue by kwyatt242** [tabalinas/jsgrid#458]
Hi - 
I have a field that I only want editable if another item value is false. Below is my attempt to make that work. 
```js
			fields: [{
				name: "userEmail",
				title: "Email",
				type: "text",
				width: 20,
				itemTemplate: function(value, item) {
					this.readOnly = item.notEditable;
                                        return value;
				}
			}]);
```
If I get false on item.notEditable the first time, all rows then set readOnly to false. I need each row individually set. 

I can't seem to find much information on 'itemTemplate' and how it functions..

Thanks for your help!
Kent

**Comment by tabalinas** [comment]
I think you need `editTemplate`. Just return  readonly control if item is non-editable, for instance:

```js
editTemplate: function(value, item) {
    var $result = jsGrid.fields.text.prototype.editTemplate.apply(this, argumets);
    $result.prop("readonly", item.notEditable);
    return $result;
}
```

**Comment by kwyatt242** [comment]
Thank you! That worked.

Sorry, I was hoping you could help me once more :( I am trying to make a
cell visually not editable in certain cases (which would mean it goes
yellow in edit mode while other cells are editable). This is why I
initially don't give it a type. I was hoping I could assign the type only
if it should act like a normal text cell that is editable.

I am sure I am doing something dumb because I can't seem to find much info
on 'editTemplate'. Thanks again!

 {
name: "userName",
title: "Name",
width: 175,
css: "gridTable",
align: "left",
editTemplate: function(value, item) {
if (item.Editable) {
var $result = jsGrid.fields.text.prototype.itemTemplate.apply(this,
arguments);
}
return $result;
}

**Comment by kwyatt242** [comment]
Or perhaps there is a better / simpler way to approach this? All I am
trying to avoid is the field that the user should not edit to appear in
yellow (no white box) as this seems confusing to them. See screenshot .
"System" should be in all yellow.
[image: Inline image 1]

**Comment by tabalinas** [comment]
Yes, you could do that.
I'm not sure if you want non editable items or particular field.
If you don't want to activate editing for some items, then redefine [rowClick](http://js-grid.com/docs/#rowclick) method, so you don't start editing if this is not editable item.

If you want to prevent editing of particular field, then instead of calling `itemTemplate` (if you don't do anything specific in it) just `return value` from `editTemplate`.

Hope this will help.
