### ISSUE TITLE
unable to load data from OData service response

### ISSUE THREAD

**Issue by kishorejv** [tabalinas/jsgrid#459]
FOllowing is my html code

<head>

    <link href="css/style.css" rel="stylesheet" type="text/css" />
    <script type="text/javascript" src="js/jquery-1.8.3.js"></script>
    <link type="text/css" rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jsgrid/1.5.2/jsgrid.min.css" />
    <link type="text/css" rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jsgrid/1.5.2/jsgrid-theme.min.css" />
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jsgrid/1.5.2/jsgrid.min.js"></script>

    <script src="js/url.js" type="text/javascript"></script>
    <script type="text/javascript" src="js/grid.locale-en.js"></script>
    <script type="text/javascript" src="js/jquery.jqGrid.min.js"></script>
    <link type="text/css" rel="stylesheet" href="css/ui.jqgrid.css" />
    <link type="text/css" rel="stylesheet" href="css/jquery-ui-1.8.21.custom.css" />

    <script>
    $(document).ready(function() {

      $("#project_list").jsGrid({
        height : "auto",
        width : "100%",
        sorting : true,
        paging : true,
        autoload : true,
        pageSize : 10,
        controller : {
          loadData : function() {
            var d = $.Deferred();

            return $.ajax({
              url : url + 'user/get_user_list',
              datatype : "xml",
              type : 'POST',
            }).done(function(result) {
          result = $.grep(result, function(item) {
            return item.ProjectName === filter.projectName;
          });
          d.resolve(result.value);
        });
        return d.promise();
      }
    },
    fields : [{
      title : "Project Name",
      name : "projectName",
      type : "text",
    }, {
      name : "projectDescription",
      type : "text",
      width : 150
    }, {
      name : "projectId",
      type : "number",
      width : 50,
      key : true,
      visible : false,
    }, {
      type : "control",
      editButton : true,
      modeSwitchButton : true,
      deleteButton : true,
      width : 35
     }],
       });
    });
    </script>
    </head>
    <body>
        <div class="panel-wrapper">
           
            <table id="project_list"></table>
       </div>

    </body>

Following is my xml response

    <projectList>
      <exceptionId>0</exceptionId>
      <id>0</id>
      <isException>false</isException>
      <offExptionid>0</offExptionid>
      <listException>false</listException>
      <listExceptionId>0</listExceptionId>
      <listSize>0</listSize>
      <nextPage>false</nextPage>
      <pageNumber>0</pageNumber>
      <projectBOs>
       <exceptionId>0</exceptionId>
       <id>0</id>
      <isException>false</isException>
       <offExptionid>0</offExptionid>
        <projectDescription></projectDescription>
       <projectId>5</projectId>
        <projectName>Bmw</projectName>
      </projectBOs>
      <projectBOs>
       <exceptionId>0</exceptionId>
       <id>0</id>
       <isException>false</isException>
       <offExptionid>0</offExptionid>
       <projectDescription>Toyota</projectDescription>
       <projectId>4</projectId>
        <projectName>Toyota global</projectName>
       </projectBOs>
      <projectBOs>
       <exceptionId>0</exceptionId>
        <id>0</id>
      <isException>false</isException>
    <offExptionid>0</offExptionid>
      <projectDescription>BMW Gloabal</projectDescription>
    <projectId>1</projectId>
    <projectName>BMW</projectName>
      </projectBOs>

**Comment by tabalinas** [comment]
The `loadData` method is incorrect: you should either return result of $.ajax call or Promise of your deferred (`return d.promise()`).
Moreover the issue lacks details about the problem you have. Just putting sources in the issues is not enough.

**Comment by kishorejv** [comment]
As u said my loaddata is incorrect i have tried returning either a promise or $.ajax, but still i am not able to load data into my jsgrid
 Its a clear cut issue as my question says i am not able to load the data after i make a service call, due to that i mentioned sources.
Hope i get an answer.  even i tried using json still problem persists

**Comment by tabalinas** [comment]
Have you opened the console and checked that your request is succeeded?
Put a `debugger` in your `done` function. Meaning just play with it to understand the issue.
If nothing will work, provide external access to the page, so it's possible to look at it.
