### ISSUE TITLE
Change filterTemplate fields any after selected item in filter ?

### ISSUE THREAD

**Issue by ROKAISAKKON** [tabalinas/jsgrid#46]
```javascript
fields :[
     {
        name           : "Test1",
        type           : "select",
        filterValue    : function () {
            //code ...
            //call function filterTemplate in fields name=Test2 ???

            return this.lotteryKey;
        }
    }
    , {
        name           : "Test2",
        type           : "select",
        filterTemplate : function () {
            this.filterControl = $('<select>');
            //code...
            return this.filterControl;
        },
        filterValue    : function () {
            return this.filterControl.val();
        }
    }
]
```

For pick provinces, cities and districts.

**Comment by tabalinas** [comment]
Don't get your question. What are you trying to achieve?

**Comment by ROKAISAKKON** [comment]
I am sorry. I am not good English.

update item in filter B after selected item in filter A

**Comment by tabalinas** [comment]
As I understand you try to accomplish something like this http://jsfiddle.net/tabalinas/n982uvx1/
Hope this example will help you.

**Comment by ROKAISAKKON** [comment]
it works. Thank you so much.

**Comment by tabalinas** [comment]
You are welcome!

**Comment by imuzahuzi** [comment]
> As I understand you try to accomplish something like this http://jsfiddle.net/tabalinas/n982uvx1/ Hope this example will help you.

How do I set selectedIndex?

The JS Grid interface loads and the Dropdown options load properly but when i select an option it is not updated in the JS Grid Table.
