### ISSUE TITLE
how to inserting option customize?

### ISSUE THREAD

**Issue by MingyuJeon** [tabalinas/jsgrid#462]
If inserting option value is true, then data can be edited or added.
I'd like to programmed like this, if want to change Province name and Code, should select Country name in `select` option. So, if Country name is not selected, Province name and Code in an inserting row should be deactivated.
However, If I set `type` to `select`, then its data isn't shown.
I have a no idea how to set options for it inserting row is select option and the column that show country name.

**My code is here.**
```javascript

{
    headerTemplate : "Country Name",
    name : "countryName",
    type: "select",
    items : JSON.stringify(temp.countryName),
    textField : "countryName",
    width : 100,
    align : "center",
}

```
<img width="1173" alt="2016-10-10 2 56 07" src="https://cloud.githubusercontent.com/assets/15281293/19227823/bc32f1e0-8ef9-11e6-8e72-02061728bf70.png">

**Comment by tabalinas** [comment]
`items` should be a valid js array (not sure why passing items as a string). 

Another thing: use option `title` instead of headerTemplate (the latter is for complex renderer usually).

**Comment by MingyuJeon** [comment]
I wanted to show a country list that I get from the server.

I'm not sure if my code is okay.

``` javascript
function provinceSetting() {
				$('#province-setting').jsGrid(
						{
							width : '100%',
							height : 'auto',

							autoload : true,
							confirmDeleting : false,
							paging : true,
							pageSize : 10,
							pageButtonCount : 5,
							inserting : true,
							editing : false,
							sorting : true,
							controller : {
								loadData : function(filter) {
									var def = $.Deferred();
									$.ajax({
										url : 'aws/api/v1/provinces',
										type : "GET",
										contentType : "application/json; charset=utf-8",
										dataType : "json"
									}).done(function(item) {
										def.resolve(item.result);
									});
									return def.promise();
								},
								
								deleteItem : function(deletingItem) {
									console.log(JSON.stringify(deletingItem.countryId));
									var item = JSON.stringify(deletingItem);
									console.log(item);
									console.log(item.countryId);
									$.ajax({
										url : 'http://aws/api/v1/countries'+'/'+JSON.stringify(deletingItem.countryId),
										type : "DELETE",
										contentType : "application/json; charset=utf-8",
										dataType : "json",
										data : JSON.stringify(item),
										complete : function(){
											console.log(deletingItem.countryId);
										}
									}).done(function(item) {
										alert('');
										console.log(item);
										selectedItems = [];
										var $grid = $("#country-setting");
										$grid.jsGrid("loadData");
									});
								},

```

**Comment by tabalinas** [comment]
I don't understand the issue from the description: what is `item` in this case? You should provide valid set of possible items in the `items` option (check in the docs http://js-grid.com/docs/#select).
Also check grid sample projects http://js-grid.com/samples/.

Anther issue: `deleteItem` method should also return a promise of the ajax, in other case you could have the following issue: the item will be removed from the grid, while a deletion request failed.

> if I want to deactivate inserting option?
Have you tried `inserting` option (http://js-grid.com/docs/#inserting-default-false)?

For future: it's better not to mix different questions in a single GitHub issue.

**Comment by MingyuJeon** [comment]
I'm not sure if I understand what you're saying.
You mean, To mix text type and select type is not good in one field?
I wanted to do like this cause if someone want add province or state, should input country first.
So, unless those select option value is decided, another inserting option with text type should be deactivated. 

<img width="584" alt="2016-10-11 9 09 51" src="https://cloud.githubusercontent.com/assets/15281293/19254845/0645ac3e-8f93-11e6-86c8-a7e714bb0b84.png">

and another issue you said is fixed.
I deleted `Deffered()` cause it occurs error which is `.Deffered() is not defined`
Well... I don't know why it works but now it's okay :)

**Comment by tabalinas** [comment]
At this point I really advise you to look at the sample project which already has solution for your question, as I understand it (see grid initialization https://github.com/tabalinas/jsgrid-php). For the rest, I can only repeat single-issue rule: don't put several questions in a single issue.
