### ISSUE TITLE
how to customize 1 button refresh grid, outside grid ,and 1 toolbar search outside grid

### ISSUE THREAD

**Issue by mautrung09** [tabalinas/jsgrid#465]
how to customize 1 button refresh grid,
outside grid
,and 1 toolbar search outside grid

**Comment by tabalinas** [comment]
Since toolbar and a button are outside of the grid, they can be customized in any way, and it's not related to the grid itself. Of course it depends on what is meant by customizing. In general the issue lacks information about the problem with customization.
