### ISSUE TITLE
Can you provide an example for jsgrid filed pattern example. 

### ISSUE THREAD

**Issue by sri596** [tabalinas/jsgrid#469]
Please find my field rules.
- Field length < 10 &
- Field should starts with "AA" pattern.

Thanks
Srinivas

**Comment by tonisostrat** [comment]
This is simple regex, has nothing to do with this library.

`^A{2}.{0,7}$`

**Comment by sri596** [comment]
Can we write like this?

{ title: "PART NUMBER", name: "partNumber", type: "text", align: "center", 
	validate: { message: "Length of PART NUMBER should be < 10 characters & should starts with AA.", validator: "rangeLength", param: [0, 10], pattern: "^A{2}" }
},

**Comment by tonisostrat** [comment]
Did you even look at the docs?

[Working example](https://jsfiddle.net/fh0vsL9r/1/)

**Comment by sri596** [comment]
Thanks.
pattern example is not available in docs. Please add it. it will be useful for most of the users.

**Comment by tabalinas** [comment]
@sri596, it's listed in the docs http://js-grid.com/docs/#built-in-validators
