### ISSUE TITLE
How to insert new item in starting/Top of the grid.

### ISSUE THREAD

**Issue by sri596** [tabalinas/jsgrid#470]
Hi.
I have  20 items in my grid. my page count is 15.
So page1 contains 15 & page2 contains 5.

If I insert new row, it is adding as last row of a grid. So here user need to go to last page to verify/view the inserted data. Is there anyway to insert as 1st row of grid? So that we can avoid page switching.

Please help.

Thanks.

**Comment by tabalinas** [comment]
You can do providing a custom load strategy (http://js-grid.com/docs/#custom-loadstrategy).
In your case you have to redefine `finishInsert` (not `finishDelete` as in the example).
