### ISSUE TITLE
How to insert new row with default values

### ISSUE THREAD

**Issue by sri596** [tabalinas/jsgrid#471]
My jsgrid contains 3 fields.
Name, Age, Country.

If I click on Switch to Insert mode (+ Symbol). It is showing 3 empty text box fields. Please find below snapshot
![image](https://cloud.githubusercontent.com/assets/22791045/19308180/f43a19a8-909b-11e6-9d7a-c565c744dc4e.png)

For my requirement default country value is "USA". If i click on Switch to Insert mode it should show as per below snapshot.

![image](https://cloud.githubusercontent.com/assets/22791045/19308235/3aa93f72-909c-11e6-9b7c-3430fbcc0245.png)

On inserting new row, grid should set country value as USA. If required user can edit & insert the row.

Please help.

**Comment by tonisostrat** [comment]
You can specify the `selectedIndex` parameter when you insert a `select` type field, refer to the [documentation](http://js-grid.com/docs/#select).

**Comment by tonisostrat** [comment]
You need to override the `insertTemplate()` function for that field and do something like this:

```
insertTemplate: function() {
    var input = this.__proto__.insertTemplate.call(this);

    input.val('USA')

    return input;
}
```

**Comment by sri596** [comment]
Hi. Thanks for your response. I am beginner. Can you please provide some more details?
Please find my field details below.

fields:[
{ title: "Name", name: 'name', type: "text", align: "center", validate: "required"},
{ title: "Age", name: 'age', type: "Number", align: "center", validate: "required"},
{ title: "Country", name: 'country', type: "text", align: "center", validate: "required"},
]
For 3rd field i.e. Country field i need default value as USA.

Please help.

**Comment by tonisostrat** [comment]
[Working example](https://jsfiddle.net/rL3xye1q/)

**Comment by tabalinas** [comment]
@tonisostrat, thank you for the great answers!
