### ISSUE TITLE
Unable to perform search

### ISSUE THREAD

**Issue by kishorejv** [tabalinas/jsgrid#477]
Is there anything we must write externally to perform search on a column.  from demos i understand that no code is written , please help me out.
I have filtering:true, so that i have search boxes on each col , when i enter text and hit on enter button of keyboard or search icon nothing happens but it calls a REST-ful service which i have written to get data for grid

Am i doing wrong? some where

**Comment by tonisostrat** [comment]
```javascript
controller: {
  loadData: function(filter) {
    /*
      you need to extract the value from `filter` object and pass it to your REST call in the supported format.
    */

    // rest of your REST call code
  }
}
```

**Comment by kishorejv** [comment]
Tried the following approach , it didnot work ( am i doing it correct ? )   

                    controller : {
						    loadData : function(filter) {

							var d = $.Deferred();

							$.ajax({
								url : "myurl",
								 
								dataType : "json",
								type : 'POST',
							}).done(function(response) {
			                                       
                                               // client-side filtering
                                      
                                                 result = $.grep(response, function(item) {
                                                  return item.Name === filter.Name;
								 
							 });
							 

								d.resolve({
									data : response.project

								});

 


							});
							return d.promise();
 
 },
 
						},

**Comment by tabalinas** [comment]
Your code looks incorrect: the response is filtered into some `result` variable (global?), while you are resolving deferred with `response.project`.

**Comment by kishorejv** [comment]
yes , in above case result variable is global . i removed it and tried below coding still problem exit. if i am still wrong could you please help me with coding .

      .done(function(response) {

     // client-side filtering
			 $.grep(response, function(project) {
				
   	       return project.Name === filter.Name;
 								 
							 });
								d.resolve({
									data : response.project 
	
								});



							});
							return d.promise();

**Comment by kishorejv** [comment]
@tonisostrat  i am trying to do client side filtering . can u help me out?
As per tabalin suggestion i tried following code but using this i am not able to load data when i resolve deferred using result.

    .done(function(response) {
    var result = $.grep(response, function(project) {
        return project.Name === filter.Name;
    });

    d.resolve(result);
    });

But when i try to print result it gives me an empty array..
