### ISSUE TITLE
Can I set a new attribute like data-[name] to each row?

### ISSUE THREAD

**Issue by messala** [tabalinas/jsgrid#479]
First of all, sorry if this is not the right place for my question and I'm really sorry for my english.

I've set up a js-grid from a json. My json have 4 properties: id, name, code and an irrelevant boolean, but I created the grid with only 2 columns: code and name.

Set up and build the table is ok, but now I would like to set an attribute "data-cid" in each row (tr element) with the value from my json id property to be able to retrieve it from a hover event.

I tried to skip it writing a span element inside the cell value manually:
`arr.push( { "code": tCode, "Name": '<span class="class1" data-cid="'+tId+'">'+tName+'</span>' } );`

And this is the jQuery to react to the hover event:
`    $(".class1").hover(function(e) {`
`	alert();`
`    });`

Everything seems to work, there's no javascript exception and the span element is being added to DOM properly, but the execution do not achieves the alert line.

If I simply write a copy of one of these span to document like this, the alert works:
`document.write('<span class="class1" data-cid="123">name</span>');`

It seems to be a really simple task, but I'm new with js-grid and I couldn't figure it out by myself through the reference.

**Comment by messala** [comment]
I tried to write a span element inside the cell value manually:

`arr.push( { "code": tCode, "Name": '<span class="class1" data-cid="'+tId+'">'+tName+'</span>' } );`

And this is the jQuery to react to the hover event:

`    $(".class1").hover(function(e) {`
`	alert();`
`    });`

Everything seems to work, there's no javascript exception and the span element is being added to DOM properly, but the execution do not achieves the alert line.

If I simply write a copy of one of these span to document like this:

`document.write('<span class="class1" data-cid="123">name</span>');`

The alert works. =/

**Comment by tonisostrat** [comment]
```javascript
$('[selector'].jsGrid({
  //all of your other configuration

  rowRenderer: function(item, rowIndex) {
    var $row = $('<tr>');

    $row.data('cid', item.id);

    this._renderCells($row, item);

    return $row;
  }
});
```

**Comment by messala** [comment]
I don't understand one thing: the tr default class name is "jsgrid-row" and the following command do nothing:
`	$(".jsgrid-row").hover(function(e) {`
`		alert();`
`	});`

Does the js-grid overrides the behavior of event listener for its elements?

Where can I find the reference for this property "_attachRowHover"? I didn't find nothing... =S
