### ISSUE TITLE
Backslash for old ie causing problems with cleancss

### ISSUE THREAD

**Issue by nishp1** [tabalinas/jsgrid#48]
Running cleancss against `theme.css`
```
.jsgrid-load-panel {
    padding-top: 1.5em \ ;
}
.jsgrid-load-panel:before {
    display: none \ ;
}
```

gets converted into (note removed `;` at the end of each block)
```.jsgrid-load-panel{padding-top:1.5em \}.jsgrid-load-panel:before{display:none \}```

What browsers does `\` target? Is `\9` the intended hack?

**Comment by nishp1** [comment]
Changing `\` to `\9` does fix the problem.

**Comment by tabalinas** [comment]
Thanks for the report and fix!

**Comment by nishp1** [comment]
:+1:
