### ISSUE TITLE
Edit a specific column for all rows

### ISSUE THREAD

**Issue by harveyteofilo** [tabalinas/jsgrid#480]
Hello,
Is there a way to edit a specific column for all the rows in my grid?
It's like trying to do what the editItem(item|$row|rowNode) method does, but, for all the rows. Thanks.

**Comment by tonisostrat** [comment]
No, nothing out-of-the-box. You need to write your own function that takes the new value, loops through all the grid items and updates them.

**Comment by harveyteofilo** [comment]
Okay, thanks.
