### ISSUE TITLE
 Use ajax to return data and itemCount in loadData function

### ISSUE THREAD

**Issue by ryanjayson** [tabalinas/jsgrid#482]
Is it possible to use ajax call to return data and itemCount in loadData function?

I tried this code below,it's working, but the thing is I don't want to use the async:false option. I don't what to wait for the return to interact to the page, is there any solution for this?

  ```
loadData: function (filter) {
         model = {
                page: 1,
                orderBy: "LastName",
                reverse: false,
                itemCount: 20,
                filters: null
            };            
          var _customer = $.ajax({
                type: 'GET',
                url: '@Url.Action("GetCustomers")',
                dataType: 'json',
                async: false,
                data: model
            });


            return {
                data: _customer.items,
                itemsCount: _customer.itemCount
            };
        },
```
on my controller, I return this structure

            return new {
              ItemCount = cModelView.Count(), // returns the items count
              Items = cModelView // returns the items
            };

**Comment by tonisostrat** [comment]
There's a whole demo page [here](http://js-grid.com/demos/) concerning async data loading. See **OData Service**.

**Comment by tabalinas** [comment]
Yes, this is the basic scenario of jsgrid.
Here is a code snippet based on demo referenced by @tonisostrat:

```js
loadData: function() {
    var d = $.Deferred();

    $.ajax({ /* your config here */ }).done(function(response) {
        d.resolve({
            data: response.items,
            itemsCount: response.itemCount
       });
    });

    return d.promise();
}
```
