### ISSUE TITLE
disable field validation when editing 

### ISSUE THREAD

**Issue by amin750** [tabalinas/jsgrid#483]
how can i disable field validation when editing field is false?

my code:
`validate: {
                    message: "error message",
                    validator: function (value) {
                        return value >= 0 && value != "";
                    }
                }`

**Comment by tabalinas** [comment]
What is the use case for having validation for non-editable field?

**Comment by tonisostrat** [comment]
@tabalinas I think he wants to disable field validation on editing. 

> field is false

probably means

> field is invalid

**Comment by amin750** [comment]
@tonisostrat  yes,exactly
> I think he wants to disable field validation only on editing.

**Comment by tabalinas** [comment]
Then checkout this issue https://github.com/tabalinas/jsgrid/issues/363

**Comment by amin750** [comment]
@tabalinas  the issue #363 not resolve my problem

**Comment by tabalinas** [comment]
@amin750: yes, this could be possible workaround. 
But if #363 won't help, then not sure I understand the issue: it's should be the same in the validation function depending on editing/inserting you either check value or just return `true` if there is no need to validate.

**Comment by amin750** [comment]
thank you for solution, my problem resolved
