### ISSUE TITLE
custom button in control column

### ISSUE THREAD

**Issue by fredericoregateiro** [tabalinas/jsgrid#485]
I'm using this code to create a new button on the control column:
```csharp
{
    type: 'control',
    itemTemplate: function () {
        var $result = jsGrid.fields.control.prototype.itemTemplate.apply(this, arguments);
        var $myButton = $('<button class="btn-clean mdi mdi-playlist-plus" title="Adicionar" onclick="AddLine()">');
        return $result.add($myButton);
    }
}
```
What is the best way to pass the item of the current row to the button click event handler?

Thanks,
Frederico

**Comment by tonisostrat** [comment]
If you care to look at the [source code](https://github.com/tabalinas/jsgrid/blob/master/src/jsgrid.field.js#L26) or even the [documentation](http://js-grid.com/docs/#fields) you would see that `itemTemplate()` already accepts the item itself as one of it's arguments.

You can refactor your code:

```javascript
{
  type: 'control',
  itemTemplate: function(value, item) {
    //your stuff
  }
```

**Comment by fredericoregateiro** [comment]
Thanks for the reply,
My question was the best way to get the item passed to the button click event handler, not in the itemTemplate.
The item i can also get from the arguments property.

This question is just my lack of knowledge in javascript, that i'm starting to learn.
Thanks

**Comment by tonisostrat** [comment]
That's exactly the reason why `item` is important in `itemTemplate()`. Proper design mandates that you create the button and assign a click handler to it right there instead of referencing some global function somewhere.

```javascript
itemTemplate: function(value, item) {
  var $customButton = $('<button>').on('click', function() {
    //do something relevant with item here
  };
}
```

**Comment by fredericoregateiro** [comment]
Thanks,
It's working perfectly
The variable scope IN JAVASCRIPT is something that i'm still trying to master.
