### ISSUE TITLE
Leave editing but update row

### ISSUE THREAD

**Issue by theeedannyd** [tabalinas/jsgrid#486]
Hi, it might be me but i cant find the mechanism or callback that triggers the cancel of updating row when I click off from it. I want to enable the row which is in editing state to update when I click off from it. That is, click off from the grid entirely or onto the next row. I tried making a method which updates the currently ineditmode row from the onediting method of another row click, but it seems that even though the onediting row callback is fired that that row is actually in editing state so the updateItem method updates this newly selected row. Please help! Many thanks and many thanks for the tool, it really is the best I have worked with. Danny

**Comment by theeedannyd** [comment]
worked it out, used on row click and updated if the new row didnt equal the last. Cheers

**Comment by tabalinas** [comment]
Glad that you figured it out!

**Comment by sukothap** [comment]
@theeedannyd I'm trying to do a similar thing in my application, but I can't seem to make it work when clicking out of the grid, (could get it working when clicking on a new row) such as on a Save button. Any help is appreciated.

**Comment by tabalinas** [comment]
@sukothap, subscribe on click event on `document`. In the handler check if the `event.target` outside of the grid call `updateItem` method of the grid.
