### ISSUE TITLE
Apply filter while typing in the filtering box

### ISSUE THREAD

**Issue by hongyiqin** [tabalinas/jsgrid#487]
Hi, I've spent some time reading through the online docs but didn't find a way to apply filter while the user is typing in the filtering box. I think currently loadData is only triggered when an Enter key is pressed.

Is it possible to force filtering at every key stroke? 

Thanks.

**Comment by tonisostrat** [comment]
It's possible if you add a keychange handler to the input boxes.

**Comment by tabalinas** [comment]
For the sample of how to do it checkout the following issue https://github.com/tabalinas/jsgrid/issues/313

**Comment by hongyiqin** [comment]
Hi @tabalinas ,thanks for the prompt reply.

The code snippet from issue #313 doesn't work for me, typing in the filter box doesn't seem to do anything.

Is it possible to have a small working example on jsfiddle.net.

Thanks.

**Comment by hongyiqin** [comment]
Hi @tabalinas , here's an example: http://jsfiddle.net/sdbadjye/1/  I added your code in the end but it doesn't do dynamically filtering yet. Thanks.

**Comment by tabalinas** [comment]
There are several issue in your and my code (it was not tested, it just showed the main principle).

Issues:
 - `jsGrid` is a root namespace, not a jQuery adapter
 - the `filterTemplate` should be redefined before the grid initialization, so new function will be taken into account
 - we need to save original `filterTemplate` before redefining it, so we can call it afterwards
 - at the end it lacks a `return` statement

Here is the working fiddle: http://jsfiddle.net/xk402uhg/

**Comment by hongyiqin** [comment]
Thanks @tabalinas , much appreciated

**Comment by Jasvinder15s** [comment]
Hi, @tabalinas and @hongyiqin can we have this functionality of filtering while typing in the filter for the number field too. I have spent some time trying this but that doesn't work. 

Is it possible to have non-case sensitive search for the text field?
