### ISSUE TITLE
Filtering on Custom fields

### ISSUE THREAD

**Issue by vissini** [tabalinas/jsgrid#488]
Hi,

Congratulations by the JsGrid. This is so good. Help me a lot in my projects.

But this time I can't find a answer for my problem.

How can I filtering an Custom field.
I created a Brazilian money field, that works very well, but I can't filtering by this field (not appear the input field).
![image](https://cloud.githubusercontent.com/assets/5443537/19598966/8bd4d4b0-977c-11e6-922a-8abd2633dde0.png)

Let me know if have some possibility to do this.

Many thanks

**Comment by tonisostrat** [comment]
You need to implement both `filterTemplate()` and `filterValue()` for that functionality.
