### ISSUE TITLE
Set custom property

### ISSUE THREAD

**Issue by AlexPerotti** [tabalinas/jsgrid#489]
I wasn't able to find a way to pass a custom property into jsGrid object.
An option such as customProperties: {} could be very useful

**Comment by tonisostrat** [comment]
This is Javascript.. you can add any abritrary property to the configuration object.

```javascript
$('[selector]').jsGrid({
  fields: [
    //your fields
  ],
  controller: {
    //your controller
  },
  customProperty: 'this is',
  customFunction: function() {
    return 'really easy'
  }
});
```
