### ISSUE TITLE
table is compressed

### ISSUE THREAD

**Issue by Julian-B90** [tabalinas/jsgrid#49]
I use the bootstap Tab component and in the first call of the site i get what is shown in the thumbnail below.
When i reload the page the table works fine.

![error](https://cloud.githubusercontent.com/assets/4377396/8249973/bf38c314-166f-11e5-99e9-146b9230c5ec.JPG)

**Comment by tabalinas** [comment]
If rendered in invisible area grid cannot calculate sizes correctly, and the refresh is required.

Refresh the grid on tab opening:

```javascript
$('a[data-toggle="tab"]').on('shown.bs.tab', function (e) {
  $("#jsGrid").jsGrid("refresh");
});
```

If the tab is opened by default, just trigger event on ready:

```javascript
$('a[data-toggle="tab"]:first').trigger("shown.bs.tab");
```

**Comment by Julian-B90** [comment]
Thanks this are working fine. :-D

**Comment by tabalinas** [comment]
You are welcome!

**Comment by frank-liu** [comment]
thanks tabalinas , you are so great. Also thanks Julian-B90 to write your problem. I ran into the same issue.

thank you two.
