### ISSUE TITLE
update single row and push back to db.

### ISSUE THREAD

**Issue by dauris** [tabalinas/jsgrid#490]
I am sure you have answered this already but I'm having problem trying to figure out how to get it back up. If a little direction can be given it would be great. I've pulled down the data perfectly but upon editing the field I can't figure out how to get it back up there.

**Comment by tonisostrat** [comment]
You need to have the `updateItem()` method of controller do something.

**Comment by tabalinas** [comment]
As @tonisostrat mentioned you need to define `updateItem` in the `controller`. 
Here is an example https://github.com/tabalinas/jsgrid-php/blob/master/public/js/sample.js (this is the  sample project [js-grid + php](https://github.com/tabalinas/jsgrid-php)).
