### ISSUE TITLE
Dynamic data on pagination, it's possible?

### ISSUE THREAD

**Issue by reypm** [tabalinas/jsgrid#495]
I am looking for a good jQuery Grid plugin and I believe this one is awesome. Before I start using it I would like to know if there is any way to get data dynamic. What I mean? Most of the datagrid I've found load all the data on a single query and then process it through JS/jQuery and with too many data this is insane. So I am looking for one that makes possible to load data as soon as I move in pagination by making a request to the server for get the data. Also I am using PHP is there any example around?

**Comment by tabalinas** [comment]
As I understand you are talking about loading data by pages - yes this is basic scenario for js-grid, checkout this option http://js-grid.com/docs/#pageloading-default-false.
There are sample projects for js-grid http://js-grid.com/samples/ (php among them).
