### ISSUE TITLE
Add/remove columns, it's possible?

### ISSUE THREAD

**Issue by reypm** [tabalinas/jsgrid#496]
Is there any chance to add support for add/remove columns? What I mean let's said I have a default set of columns for render when grid load, something like:

```
{
    defaultCols: {
        'col1',
        'col2',
        'col3',
    }
}
```

But I have a `col4` and `col5` that I would like to shown also. The data is coming so I will available values for those ones as well.

It's possible then to toggle it's visibility dynamically?

**Comment by tabalinas** [comment]
Every field has an option `visible` (see fields config http://js-grid.com/docs/#fields). So you can define several hidden fields.
There is a method [fieldOption](http://js-grid.com/docs/#fieldoptionfieldnamefieldindex-optionname-optionvalue) to change the value of the field option.
