### ISSUE TITLE
I would like to have an animation on deleteItem like fade

### ISSUE THREAD

**Issue by Julian-B90** [tabalinas/jsgrid#50]

**Comment by Julian-B90** [comment]
maybe i can made it with onItemDeleting?

**Comment by tabalinas** [comment]
The problem currently is a behavior of the grid on item deleting. It refreshes the grid.
Here I explained how it works and how it maybe changed.

Thus, it's doable now with a little tricky workaround:

```javascript
jsGrid.loadStrategies.DirectLoadingStrategy.prototype.finishDelete = function(deletedItem, deletedItemIndex) {
    var grid = this._grid;
    grid.option("data").splice(deletedItemIndex, 1);
    var $row = grid._rowByItem(deletedItem);
    $row.fadeOut({
        done: function() {
            $row.remove();
        }
    });
};
```

See working fiddle: http://jsfiddle.net/tabalinas/z6ffzah5/

**Comment by tabalinas** [comment]
Decided not to implement for the moment. For now the workaround above can be used.

**Comment by refeele** [comment]
I need to achieve this but the workaround is not working (2015 issue I know...)
