### ISSUE TITLE
Reset page # of grid on search/filter

### ISSUE THREAD

**Issue by ralawar7** [tabalinas/jsgrid#500]
I have an issue where I will be on a page besides 1 - let's say page 8. Then after I filter out a column, a search is performed and the results are retrieved, but then I am placed on page 8 instead of 1.

Is there a way to reset the page number back to 1 after searching/filtering? I tried using openPage but that causes two searches to go out to my data service on every filter (the openPage itself seems to add an additional call to the data service).

**Comment by tabalinas** [comment]
When you are searching the paging should reset.

**Comment by ralawar7** [comment]
Sorry, I meant I'm doing a loadData to filter like this:

`$(gridID).jsGrid("loadData", filterValues);`

Tried adding it to the filterValues, but it gets the current page number in the loadData parameters instead.

**Comment by tabalinas** [comment]
So use `search` method instead.
