### ISSUE TITLE
rowDoubleClick

### ISSUE THREAD

**Issue by azisn11s** [tabalinas/jsgrid#501]
I tried to use rowDoubleClick for getting an item in grid, but when trying it for twice or more, the item show for all item that I've tried before. CMIW

**Comment by tabalinas** [comment]
Not sure the issue is clear. Need more details to understand the problem. 
The config is necessary to be able to help with the issue. A jsfiddle or any other example would be even better.

**Comment by tabalinas** [comment]
Close due to inactivity.

**Comment by azisn11s** [comment]
Sorry for replying too late.

in case:
_rowDoubleClick: function (arg) {
console.log(arg);
}_

and when we tries for multiple click, so we get more than one object containing in the arg variable.

My question : what should I do to choose last **arg.item** when tried for more than one click in any row of records grid?
Thx

**Comment by tabalinas** [comment]
I've just tested the `console.log` for `rowDoubleClick` and it works just fine. Each time `arg` contains only one item. So it's not clear what and how you are trying to choose. You have a double click handler, so the last fired callback will contain the last clicked item.

**Comment by aqrohadi** [comment]
How to make an inline edit by rowDoubleclick with jsGrid.
While my script doesn't work.

rowDoubleClick: function(args) {
      if(this.editing.item.rowDoubleClick) {
             this.editItem($(args.event.target).closest(this, args));
        }
      },

and

rowDoubleClick: function (args) {
        if(args.item.rowDoubleClick) {
              jsGrid.Grid.prototype.editing.call(this, args);
        }
    },

Please Help Me.

**Comment by aqrohadi** [comment]
How to make an inline edit by rowDoubleclick with jsGrid.
While my script doesn't work.

rowDoubleClick: function(args) {
      if(this.editing.item.rowDoubleClick) {
             this.editItem($(args.event.target).closest(this, args));
        }
      },

and

rowDoubleClick: function (args) {
        if(args.item.rowDoubleClick) {
              jsGrid.Grid.prototype.editing.call(this, args);
        }
    },

Please Help Me.

**Comment by aqrohadi** [comment]
How to make an inline edit by rowDoubleclick with jsGrid.
While my script doesn't work.

rowDoubleClick: function(args) {
      if(this.editing.item.rowDoubleClick) {
             this.editItem($(args.event.target).closest(this, args));
        }
      },

and

rowDoubleClick: function (args) {
        if(args.item.rowDoubleClick) {
              jsGrid.Grid.prototype.editing.call(this, args);
        }
    },

Please Help Me.
