### ISSUE TITLE
Update row on field (not row) blur

### ISSUE THREAD

**Issue by mybarker** [tabalinas/jsgrid#502]
Is there anything built in to jsgrid to update the row when the user navigates out of a field? I've managed to update when a different row is selected but not when a different field within the same row is clicked.

I've looked through the docs, demos and issues here and can't seem to find an example. Can anyone help me get started, please? Thanks.

**Comment by tabalinas** [comment]
Handle `blur` event on the field control and call `updateItem`.

**Comment by mybarker** [comment]
Thanks for your reply. I added the following to my custom field:

onblur: function (item) {
    console.log("onblur called");
    updateItem(item);
    }

But it is never called. I tried adding it to the jsgrid source in one of the built in fields and it also isn't called. This is because the onblur isn't added to the input tag. Is there another way to do this?

**Comment by mybarker** [comment]
I also tried adding it in the field configuration like so:
```
fields: [
    { name: "foo", type: "number", title: "bar", onblur: updateItem(item) }
]
```
But it doesn't work and errors, saying "item not defined".

Thanks.

**Comment by tabalinas** [comment]
jsGrid `field` doesn't have `onblur` event. You have to redefine the `editTemplate` and attach the event handler.
