### ISSUE TITLE
Filter fields get cleared when changing visibility

### ISSUE THREAD

**Issue by hk298** [tabalinas/jsgrid#503]
Can you please have a look at this: http://jsfiddle.net/3fp7tzgp/2/
When you enter something into the filter field and press the "return" key, the filter is set and the value remains visible in the filter field. This is the normal behaviour. Now uncomment line 13 to change the visibility of one column, enter a value into the filter field and hit "enter" again. Now the filter field is cleared even though the filter is actually set. It doesn't matter which field's visibility you change or whether you turn visibility on or off.

**Comment by tabalinas** [comment]
Changing the visibility of a field causes grid rendering. Rendered filtering row resets inputs values. This is a problem. There is a suggestion a a few related issues, e.g. https://github.com/tabalinas/jsgrid/issues/384

Thank you for the report.
