### ISSUE TITLE
Item passed to validation funtion only contains editable fields

### ISSUE THREAD

**Issue by AlexPerotti** [tabalinas/jsgrid#504]
I have a validation scenario where I must validate a field based on a value contained in a hidden column.

Unfortunatly the "item" object passed to validator only contains fields which are visibile and editable.

How can I fix that behaviour?

**Comment by tabalinas** [comment]
jsGrid allows to redefine validation component with `validation` option.
So you could derive your validation component from standard one, e.g.


```js
// Define your validation component
function MyValidation(config) {
    jsGrid.Validation.call(this, config);
}

MyValidation.prototype = new jsGrid.Validation();

MyValidation.prototype.validate = function(args) {
    var errors = [];

    $.each(this._normalizeRules(args.rules), function(_, rule) {
        // args.row is a reference to the row, from which you can get item args.row.data('JSGridItem')
        // pass item as a 4th param or if you have custom validators just pass args inside
        if(rule.validator(args.value, args.item, rule.param))
            return;

        var errorMessage = $.isFunction(rule.message) ? rule.message(args.value, args.item) : rule.message;
        errors.push(errorMessage);
    });

    return errors;   
};


// Use it in js-grid config
{
    validation: function(config) {
        return new MyValidation(config);
    }
}

```

Original `validate` source https://github.com/tabalinas/jsgrid/blob/master/src/jsgrid.validation.js#L13

**Comment by AlexPerotti** [comment]
Thank you for the quick answer.

I followed your example but the call args.row.data('JSGridItem') is undefined, while args.row holds a correct reference to the row.

`

 
    function CustomValidation(config) {
        jsGrid.Validation.call(this, config);
    }

    CustomValidation.prototype = new jsGrid.Validation();

    CustomValidation.prototype.validate = function (args) {
        var errors = [];

        $.each(this._normalizeRules(args.rules), function(_, rule) {
            // args.row is a reference to the row, from which you can get item args.row.data('JSGridItem')
            // pass item as a 4th param or if you have custom validators just pass args inside
            if (rule.validator(args.value, args.item, rule.param, args.row.data('JSGridItem')))//, args.row.data('JSGridItem')
                return;

            var errorMessage = $.isFunction(rule.message) ? rule.message(args.value, args.item) : rule.message;
            errors.push(errorMessage);
        });

        return errors;   
    };

    jsGrid.CustomValidation = CustomValidation;



```
//in the grid configuration

validation: function(config) {
                    return new jsGrid.CustomValidation(config);
                }
```

**Comment by AlexPerotti** [comment]
That made it! ty very much. I post the full working code just in case someone else need this

The validator

```
(function (jsGrid, $, undefined) {
    
    function CustomValidation(config) {

        console.log(config);
        jsGrid.Validation.call(this, config);
    }

    CustomValidation.prototype = new jsGrid.Validation();

    CustomValidation.prototype.validate = function (args) {
        var errors = [];
        var currentRowData = this.Grid.jsGrid("option", "data")[args.itemIndex]
        
        $.each(this._normalizeRules(args.rules), function(_, rule) {
            if (rule.validator(args.value, args.item, rule.param, currentRowData))
                return;
            var errorMessage = $.isFunction(rule.message) ? rule.message(args.value, args.item) : rule.message;
            errors.push(errorMessage);
        });

        return errors;   
    };

    jsGrid.CustomValidation = CustomValidation;

}(jsGrid, jQuery));
```

In the grid config:

```
validation: function (config) {
                    if (config === undefined)
                        config = {};

                    config.Grid = $("#gridId");
                   
                    return new jsGrid.CustomValidation(config);
                },
```

**Comment by tabalinas** [comment]
You are welcome!

More generic version would be to pass the instance of the grid:

```js
validation: function (config) {
                    config = config || {};
                    config.grid = this;
                    return new jsGrid.CustomValidation(config);
                },
```

And then get current item like:

```js
var currentRowData = this.grid.option("data")[args.itemIndex];
```

**Comment by AlexPerotti** [comment]
in my initialization scope "this" is a something different (I'm inside a jQuery-ui widget), I need a direct reference to the grid. Or you have a better idea to make this generic?
```
$.widget('PM.ProductAttributes', {

        _create: function () {
            $("#myGrid").jsGrid(
            {
               //options omitted
                controller: {
                    loadData: function (filter) {
                       //function
                    },

                    updateItem: function (item) {
                        //function
                    }
                },
            
                validation: function (config) {
                    if (config === undefined)
                        config = {};

                     //here this refers to widget instance!
                    config.Grid = $("#myGrid");
                   
                    return new jsGrid.CustomValidation(config);
                }
               //......


               
            });

           
        }, 
```

**Comment by tabalinas** [comment]
Are you sure about `this` in your sample? Have you checked your assumption?
Here `this` will be the context in which `validation` function will be called, and it will be called by the grid, so the context will be the grid instance.
