### ISSUE TITLE
Display column based on the value

### ISSUE THREAD

**Issue by sunilbhagavath** [tabalinas/jsgrid#506]
Hi,
    Is it possible to build a column dynamically.
For example if suppose the are 10 columns and all are empty. So display first 5 column and if and only after these 5 column are filled display the remaining 5 columns and hide the previous 5 columns. Please need urgent help in these. Thanks in advance

**Comment by tabalinas** [comment]
Yes, building columns dynamically is a basic js-grid scenario. Do you have any specific issue with implementation?

**Comment by sunilbhagavath** [comment]
Ya i just started using JSGRID. If its not much trouble can you tell how to build columns dynamically

**Comment by sunilbhagavath** [comment]
Ya i just started using JSGRID. If its not much trouble can you tell how to build columns dynamically and to add access control in each column. Like Only certain user can edit certain column in the grid

**Comment by tabalinas** [comment]
Checkout demos and sample projects. Feel free to ask any concrete questions if you have problems implementing your scenario.
