### ISSUE TITLE
I have problems loading the grid

### ISSUE THREAD

**Issue by hmykol20** [tabalinas/jsgrid#51]
Hi , I'm new to the grids and jsGrid thought was very good but I'm having problems when trying to load my data using ajax , I hope you can help me for one of my classes at the university

**Comment by tabalinas** [comment]
Could you provide more details about the issue?
Maybe you could modify this fiddle to demonstrate the problem http://jsfiddle.net/tabalinas/zzzfmpgt/

**Comment by hmykol20** [comment]
you can check please?


2015-06-30 22:35 GMT-06:00 Artem Tabalin <notifications@github.com>:

> Could you provide more details about the issue?
> Maybe you could modify this fiddle to demonstrate the problem
> http://jsfiddle.net/tabalinas/zzzfmpgt/
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tabalinas/jsgrid/issues/51#issuecomment-117432316>.
>



-- 
*Michael Herrera*
Designs | Programming | Creativity
Founder of Herreras Aplicaciones
Phone: (+505) 86026663
Email: mherrera@herreraaplicaciones.com
Website: www.herreraaplicaciones.com <http://herreraaplicaciones.com>

 <http://fastsolutionsonline.net>

**Comment by tabalinas** [comment]
Sure, give me the link to updated fiddle, please.

**Comment by hmykol20** [comment]
ok

2015-06-30 22:58 GMT-06:00 Artem Tabalin <notifications@github.com>:

> Sure, give me the link to updated fiddle, please.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tabalinas/jsgrid/issues/51#issuecomment-117433877>.
>



-- 
*Michael Herrera*
Designs | Programming | Creativity
Founder of Herreras Aplicaciones
Phone: (+505) 86026663
Email: mherrera@herreraaplicaciones.com
Website: www.herreraaplicaciones.com <http://herreraaplicaciones.com>

 <http://fastsolutionsonline.net>

**Comment by hmykol20** [comment]
http://jsfiddle.net/zzzfmpgt/2/

2015-06-30 22:58 GMT-06:00 Michael Herrera <hmykol20@gmail.com>:

> ok
>
> 2015-06-30 22:58 GMT-06:00 Artem Tabalin <notifications@github.com>:
>
>> Sure, give me the link to updated fiddle, please.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/tabalinas/jsgrid/issues/51#issuecomment-117433877>.
>>
>
>
>
> --
> *Michael Herrera*
> Designs | Programming | Creativity
> Founder of Herreras Aplicaciones
> Phone: (+505) 86026663
> Email: mherrera@herreraaplicaciones.com
> Website: www.herreraaplicaciones.com <http://herreraaplicaciones.com>
>
>  <http://fastsolutionsonline.net>
>



-- 
*Michael Herrera*
Designs | Programming | Creativity
Founder of Herreras Aplicaciones
Phone: (+505) 86026663
Email: mherrera@herreraaplicaciones.com
Website: www.herreraaplicaciones.com <http://herreraaplicaciones.com>

 <http://fastsolutionsonline.net>

**Comment by hmykol20** [comment]
My main problem is that I try to fill the grid from a php file and the
plugin does not show errors but also fills me with the grid... if you
could help me with an example using ajax or something similar will
greatly appreciate it


2015-06-30 23:11 GMT-06:00 Michael Herrera <hmykol20@gmail.com>:

> http://jsfiddle.net/zzzfmpgt/2/
>
> 2015-06-30 22:58 GMT-06:00 Michael Herrera <hmykol20@gmail.com>:
>
>> ok
>>
>> 2015-06-30 22:58 GMT-06:00 Artem Tabalin <notifications@github.com>:
>>
>>> Sure, give me the link to updated fiddle, please.
>>>
>>> —
>>> Reply to this email directly or view it on GitHub
>>> <https://github.com/tabalinas/jsgrid/issues/51#issuecomment-117433877>.
>>>
>>
>>
>>
>> --
>> *Michael Herrera*
>> Designs | Programming | Creativity
>> Founder of Herreras Aplicaciones
>> Phone: (+505) 86026663
>> Email: mherrera@herreraaplicaciones.com
>> Website: www.herreraaplicaciones.com <http://herreraaplicaciones.com>
>>
>>  <http://fastsolutionsonline.net>
>>
>
>
>
> --
> *Michael Herrera*
> Designs | Programming | Creativity
> Founder of Herreras Aplicaciones
> Phone: (+505) 86026663
> Email: mherrera@herreraaplicaciones.com
> Website: www.herreraaplicaciones.com <http://herreraaplicaciones.com>
>
>  <http://fastsolutionsonline.net>
>



-- 
*Michael Herrera*
Designs | Programming | Creativity
Founder of Herreras Aplicaciones
Phone: (+505) 86026663
Email: mherrera@herreraaplicaciones.com
Website: www.herreraaplicaciones.com <http://herreraaplicaciones.com>

 <http://fastsolutionsonline.net>

**Comment by hmykol20** [comment]
I confess that I love the plugin you have done so have tried all day
to make it work that gives me everything I need and even more than an
hour ago came to my head contact you to see if you could help me


2015-06-30 23:44 GMT-06:00 Michael Herrera <hmykol20@gmail.com>:

> My main problem is that I try to fill the grid from a php file and the plugin does not show errors but also fills me with the grid... if you could help me with an example using ajax or something similar will greatly appreciate it
>
>
> 2015-06-30 23:11 GMT-06:00 Michael Herrera <hmykol20@gmail.com>:
>
>> http://jsfiddle.net/zzzfmpgt/2/
>>
>> 2015-06-30 22:58 GMT-06:00 Michael Herrera <hmykol20@gmail.com>:
>>
>>> ok
>>>
>>> 2015-06-30 22:58 GMT-06:00 Artem Tabalin <notifications@github.com>:
>>>
>>>> Sure, give me the link to updated fiddle, please.
>>>>
>>>> —
>>>> Reply to this email directly or view it on GitHub
>>>> <https://github.com/tabalinas/jsgrid/issues/51#issuecomment-117433877>.
>>>>
>>>
>>>
>>>
>>> --
>>> *Michael Herrera*
>>> Designs | Programming | Creativity
>>> Founder of Herreras Aplicaciones
>>> Phone: (+505) 86026663
>>> Email: mherrera@herreraaplicaciones.com
>>> Website: www.herreraaplicaciones.com <http://herreraaplicaciones.com>
>>>
>>>  <http://fastsolutionsonline.net>
>>>
>>
>>
>>
>> --
>> *Michael Herrera*
>> Designs | Programming | Creativity
>> Founder of Herreras Aplicaciones
>> Phone: (+505) 86026663
>> Email: mherrera@herreraaplicaciones.com
>> Website: www.herreraaplicaciones.com <http://herreraaplicaciones.com>
>>
>>  <http://fastsolutionsonline.net>
>>
>
>
>
> --
> *Michael Herrera*
> Designs | Programming | Creativity
> Founder of Herreras Aplicaciones
> Phone: (+505) 86026663
> Email: mherrera@herreraaplicaciones.com
> Website: www.herreraaplicaciones.com <http://herreraaplicaciones.com>
>
>  <http://fastsolutionsonline.net>
>



-- 
*Michael Herrera*
Designs | Programming | Creativity
Founder of Herreras Aplicaciones
Phone: (+505) 86026663
Email: mherrera@herreraaplicaciones.com
Website: www.herreraaplicaciones.com <http://herreraaplicaciones.com>

 <http://fastsolutionsonline.net>

**Comment by hmykol20** [comment]
Hello friend

**Comment by tabalinas** [comment]
What you have to do is create php script that gives JSON in response. Look at this answer for more details http://stackoverflow.com/questions/21959312/creating-a-rest-api-using-php
And define jsGrid controller like following (of course you need to change urls):

```javascript
controller: {
    loadData: function(filter) {
        return $.ajax({
            type: "GET",
            url: "/clients",
            data: filter
        });
    },
    insertItem: function(item) {
        return $.ajax({
            type: "POST",
            url: "/clients",
            data: item
        });
    },
    updateItem: function(item) {
        return $.ajax({
            type: "PUT",
            url: "/clients/" + item.id,
            data: item
        });
    },
    deleteItem: function(item) {
        return $.ajax({
            type: "DELETE",
            url: "/clients/" + item.id
        });
    }
},
```

I'm currently preparing sample projects how to use jsGrid with different back-ends. There are already available samples for ASP.NET WebAPI (https://github.com/tabalinas/jsgrid-webapi), Ruby on Rail (https://github.com/tabalinas/jsgrid-rails/), and Django (https://github.com/tabalinas/jsgrid-django). ExpressJS, PHP and Java are upcoming.

**Comment by hmykol20** [comment]
I try but the filtering not working

**Comment by tabalinas** [comment]
The filtering should be done by developer himself. Whether on the client or on the server. In case of server your php script should get filtering params from request and filter data sending in response filtered data. Of course you can do it on the client-side, just filter data like following.

```javascript
controller: {
    loadData: function(filter) {
        var d = $.Deferred();
        $.ajax({
            type: "GET",
            url: "/clients"
        }).done(function(data) {
            var result = $.grep(data, function(item) {
                return filter.Field || client.Field === filter.Field;
            });
            d.resolve(result);
        });
        return d.promise();
    },


```

**Comment by hmykol20** [comment]
Ok friend  thanks so much...

**Comment by tabalinas** [comment]
Welcome!
