### ISSUE TITLE
Can you set the selected row class (jsgrid-selected-row) per table? And how to define a tooltip for rowclick?

### ISSUE THREAD

**Issue by christiansyl** [tabalinas/jsgrid#511]
Two questions:

1- I got some tables that are only used for display and I would like to have the selected-row not highlighted and the mouse pointer not showing a hand. But I don't want to change the jsgrid-selected-row class as I have other tables that are using the rowClick feature.
2- Is it possible to define a tooltip for rolling over a row?

Thanks and BTW congrats for the amazing work!

c.

**Comment by tabalinas** [comment]
1. what's about settings `selecting: false` for these grids, so that selection will be disabled?

2. you can add `title` attribute to a cell, or to the `<tr>`. You can do it defining `rowRenderer` function and calling `this._renderCells($myTrElement, item);` to render content cells.

**Comment by christiansyl** [comment]
perfect! thanks for the response!
