### ISSUE TITLE
jsgrid and chosen

### ISSUE THREAD

**Issue by ahmed610** [tabalinas/jsgrid#512]
hi,

I want to use chosen jquery plugin in jsgrid. hoever I'm getting an issue. the chosen plug in cut-of and does not show as the standard <select> tag. to get the full list of chosen I have to use the header scroll bar for insert action which doesnt look nice for the end user.

any help?

**Comment by tabalinas** [comment]
Have you checked out this ticket https://github.com/tabalinas/jsgrid/issues/87?

**Comment by ahmed610** [comment]
hi,

thank you for your prompt response.

I tried the above solution with no success

when I insert any <select> plugin (like chosen or any other plugin that has the capability to display search box) the drop down menu of the plugin tries to fit in the cell without expanding into other cells like the normal behavior of the select field type

**Comment by ahmed610** [comment]
the problem is similar to this
http://stackoverflow.com/questions/31699775/responsive-table-with-chosen-chosen-drop-got-cut-off-behind-table

however I dont know how to change the overflow element in the css file in js-grid

**Comment by tabalinas** [comment]
@ahmed610, could you provide an example with jsfiddle or at a least a screenshot to see the issue?

**Comment by ahmed610** [comment]
the problem is similar to this link
http://stackoverflow.com/questions/31699775/responsive-table-with-chosen-chosen-drop-got-cut-off-behind-table

**Comment by ahmed610** [comment]
![image](https://cloud.githubusercontent.com/assets/23277376/20086896/06b4b93c-a585-11e6-85cd-014df065cc5c.png)


![image](https://cloud.githubusercontent.com/assets/23277376/20086903/1657d4c8-a585-11e6-88e1-3b88aac90898.png)

as noticed I have to scroll to see the items in the drop down list

**Comment by DreamingVisions** [comment]
Honestly I ran into this same problem and instead used select2 plugin instead
https://select2.github.io/

It ended up being a great decision as I ended up liking it better anyways.

**Comment by ahmed610** [comment]
it is working with select2

thanks

**Comment by tabalinas** [comment]
@ahmed610: regarding the `chosen`, probably some comments from this issue https://github.com/harvesthq/chosen/issues/86 could help.

**Comment by DreamingVisions** [comment]
Yeah i spent a ton of time on this about a month ago and it was really much easier solution to use select2 plugin. And I honestly ended up liking the plugin even more than chosen. It has to do with how it handles the "dropdown" ul and overflow:hidden. Select2 handles the "dropdown" differently, completely bypassing the issue.
