### ISSUE TITLE
Filter Odata

### ISSUE THREAD

**Issue by maxdiable** [tabalinas/jsgrid#513]
hi,
the js-grid show my records, from odata web api, but filter not working.
this is my code:
`        $("#jsGrid").jsGrid({
            height: "auto",
            width: "100%",

            filtering: true,
            editing: false,
            sorting: true,
            paging: true,
            autoload: true,
            pageloading: true,

            pageSize: 2,
            pageButtonCount: 5,

            controller: {
                loadData: function () {
                    var d = $.Deferred();

                    $.ajax({
                        url: "http://localhost:64841/odata/OperatoriOdata",
                        dataType: "json"
                    }).done(function (response) {
                        d.resolve(response.value);
                    });

                    return d.promise();
                }
            },

            fields: [
                { name: "name", type: "text" },
                { type: "control" }
            ]
        });`

any help ?
br
Max

**Comment by tonisostrat** [comment]
Well, you need to define `loadData(filter)` instead of `loadData()` and then.. do something with the `filter` object. Check out the [docs](http://js-grid.com/docs/#loaddatafilter-promisedataresult).

**Comment by maxdiable** [comment]
very nice :)
sorry.. but it's possible create a custom filter ??
br
Max

**Comment by tonisostrat** [comment]
What do you mean by a "custom filter"?

**Comment by maxdiable** [comment]
example:
it's possible add in head column a range box for date o number ?
br
Max

**Comment by tonisostrat** [comment]
Each field (i.e. column) has a method called `filterTemplate()` that you can implement to create any kind of filter input box/control.

**Comment by maxdiable** [comment]
Good :)
Very nice
