### ISSUE TITLE
filtering is not working with static data

### ISSUE THREAD

**Issue by hazarartuner** [tabalinas/jsgrid#515]

**Comment by hazarartuner** [comment]
Here is my settings when I load jsgrid:

{
   "height":"500px",
   "width":"100%",
   "filtering":true,
   "editing":true,
   "sorting":true,
   "paging":true,
   "autoload":true,
   "pageSize":15,
   "pageButtonCount":5,
   "data":[
      {
         "Detail":"",
         "AgentName":"OPEN MEDYA"
      },
      {
         "Detail":"",
         "AgentName":"SPEED"
      },
      {
         "Detail":"",
         "AgentName":"TEZEL"
      },
      {
         "Detail":"<a id=\"a_79281\" href=\"javascript:getThisBidChild(79281, 79368);\"><span id=\"i_79281\" class=\"glyphicon glyphicon-plus-sign\"></span></a>",
         "AgentName":"MEC"
      },
      {
         "Detail":"<a id=\"a_79279\" href=\"javascript:getThisBidChild(79279, 79367);\"><span id=\"i_79279\" class=\"glyphicon glyphicon-plus-sign\"></span></a>",
         "AgentName":"MEC"
      }
   ],
   "fields":[
      {
         "sorting":false,
         "width":"auto",
         "css":"field-header",
         "name":"Detail",
         "title":"Detay",
         "type":"text"
      },
      {
         "sorting":false,
         "width":"auto",
         "css":"field-header",
         "name":"AgentName",
         "title":"Ajans",
         "type":"text"
      }
   ]
}

**Comment by tabalinas** [comment]
Please checkout the following issue https://github.com/tabalinas/jsgrid/issues/258
