### ISSUE TITLE
Date Filter not working in js-grid with data coming from service in JSON Object

### ISSUE THREAD

**Issue by RoshniUpadhyaya** [tabalinas/jsgrid#516]
I am trying to implement the js-grid using ODATA and data is coming from service in JSON object and I am able to display date in 'dd-MM-YYYY' format but i am not able to apply filter in that format.

I have tried to solve this problem with the following link but it didn't work : http://jsfiddle.net/tabalinas/doaw2zgs/

Please suggest me the solution.

**Comment by tonisostrat** [comment]
How can anyone suggest a solution when you haven't even shown us what you have so far?

**Comment by RoshniUpadhyaya** [comment]
Here is the JS Grid Code.
function CallDCJSGrid(createDCUrl, poId) {
    var dcdate;
    var DateField = function (config) {
        jsGrid.Field.call(this, config);
    };
    poId = poId || 0;

    //Customization of Date field 
    DateField.prototype = new jsGrid.Field({
        sorter: function (date1, date2) {
            return new Date(date1) - new Date(date2);
        },
        itemTemplate: function (value) {
            var curr_date = new Date(parseInt(value.substr(6))).getDate();
            var curr_month = new Date(parseInt(value.substr(6))).getMonth() + 1;
            var curr_year = new Date(parseInt(value.substr(6))).getFullYear();
            dcdate = (curr_month + "/" + curr_date + "/" + curr_year);
            return (curr_month + "/" + curr_date + "/" + curr_year)
        },
        filterTemplate: function () {

            var now = new Date();
            this._fromPicker = $("<input id='frmDate'>").datepicker({ defaultDate: now.setFullYear(now.getFullYear() - 1) });
            this._toPicker = $("<input id='toDate'>").datepicker({ defaultDate: now.setFullYear(now.getFullYear() + 1) });
            return $("<div>").append(this._fromPicker).append(this._toPicker);
        },
        filterValue: function () {
            var fromDate = $('#frmDate').val();
            var toDate = $('#toDate').val();
            return {
                from: fromDate,
                to: toDate
            };
        }
    });
    //Assinging the custom datefields to grid date column
    jsGrid.fields.date = DateField;

    //Loading the grid for with all challans.
    $("#DCJSGrid").jsGrid({
        width: "100%",
        height: "auto",
        sorting: true,
        filtering: true,
        paging: true,
        autoload: true,
        pageSize: 20,
        pageButtonCount: 5,
        align: "center",

        controller: {
            loadData: function (filter) {

                // Below code is used to decide the data parameter of Ajax to get the DC list based on poId value
                var filterData = "";
                if (poId > 0) {
                    filterData = {
                        "poId": poId
                    };
                } else {
                    filterData = filter;
                }

                var d = $.Deferred();
                $.ajax({
                    url: "/VendorDC/GetVendorDCData",
                    type: "GET",
                    contentType: "application/json",
                    data: filterData,
                    dataType: "json",
                }).done(function (response) {
                    response = $.grep(response, function (item) {
                        return (!filter.pPONumber.toString() || (item.pPONumber == null ? "" : item.pPONumber).toLowerCase().indexOf(filter.pPONumber.toLowerCase().toString()) > -1)
                            && (!filter.DCNO.toString() || (item.DCNO == null ? "" : item.DCNO).toLowerCase().indexOf(filter.DCNO.toLowerCase().toString()) > -1)
                            && (!filter.VendorCode || (item.VendorCode == null ? "" : item.VendorCode).toLowerCase().indexOf(filter.VendorCode.toLowerCase()) > -1)
                            && (!filter.pVendorName || (item.VendorCode == null ? "" : item.pVendorName).toLowerCase().indexOf(filter.pVendorName.toLowerCase()) > -1)
                            && (!filter.DCDate.from || new Date(dcdate) >= filter.DCDate.from)
               && (!filter.DCDate.to || new Date(dcdate) <= filter.DCDate.to)
                         && (!filter.UploadDocument || item.UploadDocument.indexOf(filter.UploadDocument) > -1)
                    });
                    d.resolve(response);
                });
                return d.promise();
            }
        },
        fields: [{
            name: "DCNO", type: "text", width: 10, title: "D.C. Number", align: "center"
        },
          { name: "DCDate", type: "date", width: 18, align: "center" },
        { name: "pPONumber", type: "text", width: 19, align: "center", title: "P.O. Number" },
        {
            name: "VendorCode", type: "text", width: 17, title: "Vendor Code", align: "center", visible: false,

        },
        {
            name: "pVendorName", type: "text", width: 45, title: "Vendor Name", visible: false,
        },
        {
            name: "UploadDocument", type: "text", width: 4, sorting: false, title: "Document", align: "center",
            filtering: false, itemTemplate: function (value, item) {
                if (item.UploadDocument != null && item.UploadDocument != "") {
                    return $('<a>').attr("href", item.UploadDocument).attr("download", "download").attr("alt", "Download").attr("title", "Download").append('<img src="/Content/img/download.png" alt="document" />').append('</a>');
                }
            }
        },
        {
            type: "control", width: 2, editButton: false, deleteButton: false,
            headerTemplate: function () {
                return $("<img>").attr("src", "/Content/Img/Add.png").attr("id", "imgCreateDC").attr("alt", "Create DC").attr("title", "Create DC").css({ "cursor": "pointer" })
                        .on("click", function () {
                            window.location.href = createDCUrl;
                        });
            }
        }]

    });
}

**Comment by AlexPerotti** [comment]
The issue is related to ,net way of serializing dates.

There are a lot of different solution to handle this

1) manual parse the value
2) use a library like moment.js
3) format the date server side as string.

here an example to manually parse the date which returns a Date object

`           if (value == null || value == "")
                return null;
            var pattern = /Date\(([^)]+)\)/;
            var results = pattern.exec(value);
            return new Date(parseFloat(results[1]));
            `


here an example with moment.js which returns a moment object

`return moment(value);`

**Comment by tabalinas** [comment]
Yes, JSON doesn't specify any particular format for dates.
So pick up one of the solutions proposed by @AlexPerotti. 
A few SO links that might be useful:
dates in JSON: http://stackoverflow.com/questions/10286204/the-right-json-date-format
.NET date to js date: http://stackoverflow.com/questions/206384/how-do-i-format-a-microsoft-json-date, 
http://stackoverflow.com/questions/1016847/converting-net-datetime-to-json

**Comment by RoshniUpadhyaya** [comment]
Thanks for the solution ..It works..I have tried using moment.js

**Comment by RoshniUpadhyaya** [comment]
I have problem filtering date using moment.js "DD/MM/YYYY" format. Filter applies only on the Day. Month & Year are not getting filter. Please suggest me the solution. It works well with "MM/DD/YYYY" 

Below is the js-grid code
function CallDCJSGrid(params) {
    var dcdate;
    var filterFlag;
    var DateField = function (config) {
        jsGrid.Field.call(this, config);
    };

    params.poId = params.poId || 0;
    //Below code is to check poId & set filtering to true if poId is found 0 otherwise set filtering to false
    if (params.poId == 0) {
        filterFlag = true;
    }
    else {
        filterFlag = false;
    }

    //Customization of Date field 
    DateField.prototype = new jsGrid.Field({
        itemTemplate: function (value) {
            if (value != null) {
                var dcdateFormat = moment(value).format("DD/MM/YYYY");
                return dcdateFormat;
            }
        },
        filterTemplate: function () {
            var now = new Date();
            this._fromPicker = $("<input id='frmDate' placeholder='From Date'>").datepicker({ dateFormat: "dd/mm/yy", maxDate: new Date(), defaultDate: now.setFullYear(now.getFullYear() - 1) });
            this._toPicker = $("<input id='toDate' placeholder='To Date'>").datepicker({ dateFormat: "dd/mm/yy", maxDate: new Date(), defaultDate: now.setFullYear(now.getFullYear() + 1) });
            return $("<div>").append(this._fromPicker).append(this._toPicker);
        },
        filterValue: function () {
            var fromDate = $('#frmDate').val();
            var toDate = $('#toDate').val();
            return {
                from: fromDate,
                to: toDate
            };
        }
    });

    //Assigning the custom datefields to grid date column
    jsGrid.fields.date = DateField;

    //Loading the grid for with all delivery challans.
    $("#DCJSGrid").jsGrid({
        width: "100%",
        height: "auto",
        sorting: true,
        filtering: filterFlag,
        paging: true,
        autoload: true,
        pageSize: params.pageSize,
        pageButtonCount: params.pageButtonCount,
        pagerContainer: "#DCJSGridPager",
        pagerFormat: "No of Records: {itemCount} | Pages: {first} {prev} {pages} {next} {last}    {pageIndex} of {pageCount}",
        pagePrevText: "Prev",
        pageNextText: "Next",
        pageFirstText: "First",
        pageLastText: "Last",
        pageNavigatorNextText: "...",
        pageNavigatorPrevText: "...",
        align: "center",
        controller: {
            loadData: function (filter) {
                // Below code is used to decide the data parameter of Ajax to get the DC list based on poId value
                var filterData = "";
                if (params.poId > 0) {
                    filterData = {
                        "poId": params.poId
                    };
                } else {
                    filterData = filter;
                }

                var d = $.Deferred();
                $.ajax({
                    url: params.GetDCDataUrl,
                    type: "GET",
                    contentType: "application/json",
                    data: filterData,
                    dataType: "json"
                }).done(function (response) {
                    response = $.grep(response, function (item) {
                        dcdate = moment(item.DCDate).format("DD/MM/YYYY");
                        if (filterFlag) {
                            // Applying filter
                            return (!filter.pPONumber || (item.pPONumber == null ? "" : item.pPONumber).toLowerCase().indexOf(filter.pPONumber.toLowerCase()) > -1)
                                && (!filter.DCNO || (item.DCNO == null ? "" : item.DCNO).toLowerCase().indexOf(filter.DCNO.toLowerCase()) > -1)
                                && (!filter.VendorCode || (item.VendorCode == null ? "" : item.VendorCode).toLowerCase().indexOf(filter.VendorCode.toLowerCase()) > -1)
                                && (!filter.pVendorName || (item.VendorCode == null ? "" : item.pVendorName).toLowerCase().indexOf(filter.pVendorName.toLowerCase()) > -1)
                                && (!filter.DCDate.from || dcdate >= filter.DCDate.from)
                                && (!filter.DCDate.to || dcdate <= filter.DCDate.to)
                                && (!filter.UploadDocument || item.UploadDocument.indexOf(filter.UploadDocument) > -1)
                        }
                        else {
                            return (!filter.pPONumber || (item.pPONumber == null ? "" : item.pPONumber).toLowerCase().indexOf(filter.pPONumber.toLowerCase()) > -1)
                                && (!filter.DCNO || (item.DCNO == null ? "" : item.DCNO).toLowerCase().indexOf(filter.DCNO.toLowerCase()) > -1)
                                && (!filter.VendorCode || (item.VendorCode == null ? "" : item.VendorCode).toLowerCase().indexOf(filter.VendorCode.toLowerCase()) > -1)
                                && (!filter.pVendorName || (item.VendorCode == null ? "" : item.pVendorName).toLowerCase().indexOf(filter.pVendorName.toLowerCase()) > -1)
                                && (!filter.UploadDocument || item.UploadDocument.indexOf(filter.UploadDocument) > -1)
                        }
                    });
                    d.resolve(response);
                }).fail(function (jqXHR, textStatus) {
                    var err = "Error " + " " + textStatus;
                    if (jqXHR.responseText && jqXHR.responseText[0] == "{")
                        err = JSON.parse(jqXHR.responseText).Message;
                    console.log(err);
                });
                return d.promise();
            }
        },
        fields: [
        { name: "DCNO", type: "text", width: 10, title: "D.C. Number", align: "center" },
        { name: "DCDate", type: "date", width: 19, align: "center" },
        { name: "pPONumber", type: "text", width: 19, align: "center", title: "P.O. Number" },
        { name: "VendorCode", type: "text", width: 17, title: "Vendor Code", align: "center", visible: false },
        { name: "pVendorName", type: "text", width: 45, title: "Vendor Name", visible: false },
        {
            name: "UploadDocument", type: "text", width: 4, sorting: false, title: "Document", align: "center",
            filtering: false, itemTemplate: function (value, item) {
                if (item.UploadDocument != null && item.UploadDocument != "") {
                    return $('<a>').attr("href", item.UploadDocument).attr("download", "download").attr("alt", "Download").attr("title", "Download").append('<img src="/Content/img/download.png" class="je-grid-icons" alt="document" />').append('</a>');
                }
            }
        },
        {
            type: "control", width: 2, modeSwitchButton: false, editButton: false, deleteButton: false,
            headerTemplate: function () {
                return $("<img>").attr("src", "/Content/Img/Add.png").attr("id", "imgCreateDC").attr("alt", "Create DC").attr("title", "Create DC").css({ "cursor": "pointer" })
                    .on("click", function () {
                        window.location.href = params.CreateDCUrl.replace("POID", params.poId);
                    });
            }
        }]
    });
}

**Comment by tabalinas** [comment]
@RoshniUpadhyaya, I'm not sure your issue is related to the original one. Please open another one if the problem is still actual.

**Comment by Head-Strong** [comment]
I have created custom sorter for date time sorting and it is working fine : 
// Always Register JSGrid.Js First
jsGrid.sortStrategies.datetime = function (date1, date2) {
    var result = parseDate(date1) - parseDate(date2)
    return result;
};

function parseDate(input) {
    var parts = input.match(/(\d+)/g);
    // new Date(year, month [, date [, hours[, minutes[, seconds[, ms]]]]])
    // months are 0-based
    var mdate = new Date(parts[2], parts[0] - 1, parts[1], parts[3], parts[4], parts[5]);
    return mdate;
}

**Comment by rohitoza147** [comment]
this is my php file:

<?php

$con=mysqli_connect('localhost', 'root', '','account');
 $sql = "select pname,amount from cash_voucher";

$res = mysqli_query($con,$sql) or die(mysqli_error($con));
$num = mysqli_num_rows($res);

$json = array();
if($num > 0)
{
    while ($obj = mysqli_fetch_object($res))
    {
        $json[] = $obj;
    }
}
echo  json_encode($json);


?>

and this is my  controller 
! function(document, window, $) {
    "use strict";
    var Site = window.Site;
    $(document).ready(function($) {
            
        }), jsGrid.setDefaults({
            tableClass: "jsgrid-table table table-striped table-hover"
        }), jsGrid.setDefaults("number", {
            _createTextBox: function() {
                return $("<input>").attr("type", "number","name", "pname").attr("class", "form-control input-sm")
            }
        }), jsGrid.setDefaults("text", {
            _createTextBox: function() {
                return $("<input>").attr("type", "text","name","amount").attr("class", "form-control input-sm")
            }
        }),
        jsGrid.setDefaults("control", {
            _createGridButton: function(cls, tooltip, clickHandler) {
                var grid = this._grid;
                return $("<button>").addClass(this.buttonClass).addClass(cls).attr({
                    type: "button",
                    title: tooltip
                }).on("click", function(e) {
                    clickHandler(grid, e)
                })
            }
        }),		
        function() {
            $("#basicgrid").jsGrid({
                height: "500px",
                width: "100%",
                filtering: !0,
                editing: !0,
                sorting: !0,
                paging: !0,
                autoload: !0,
				stringResult: true,
                pageSize: 15,
                pageButtonCount: 5,
                //deleteConfirm: "Do you really want to delete the client?",
                controller: db,
                fields: [{
                    name: "pname",
                    type: "number",
                    width: 10
                }, {
                    name: "amount",
                    type: "number",
                    width: 70
                }, {
                    type: "control"
                }]
            })
      
       
        }()
}(document, window, jQuery);

data show but can not filltter..
plaz help me
