### ISSUE TITLE
change grunt to rollup?

### ISSUE THREAD

**Issue by nuintun** [tabalinas/jsgrid#517]
I think you can change the build tool to [rollup.js](http://rollupjs.org).
Because the source [jsgrid.core.js](https://github.com/tabalinas/jsgrid/blob/master/src/jsgrid.core.js) is too large now, so not suitable for reading and maintenance.

I use rollup.js build [QRCode.js](https://github.com/nuintun/qrcode/blob/dev/src-dev/lib/QRCode.js) to [qrcode.encode.dev.js](https://github.com/nuintun/qrcode/blob/dev/dist/qrcode.encode.dev.js) and it looks great~

**Comment by tabalinas** [comment]
Thank you for the suggestion, but I'm not sure using rollup itself will change anything.
The problem of big `jsgrid.core.js` can be solved by extracting some part in a separate module, but this module can be easily built with existing grunt task.
