### ISSUE TITLE
field "title" is not apprearing for Custom Columns/Controls

### ISSUE THREAD

**Issue by vsaji** [tabalinas/jsgrid#519]
I have an additional column with the following setup. But the title is not appearing. Is that I have to  override headerTemplate when I use custom controls? 
```
{
			title : "De/activate Client",
			type : "control",
			editButton: false,
			width:80,
            deleteButton: false,
            editing : false,
			itemTemplate : myItemTemplate,
		}
```

```
headerTemplate: function() {
	            return "De/activate Client";
	        }
```

**Comment by tonisostrat** [comment]
The `control` column is special that way. Yes, for that type of column you need to override `headerTemplate()`.
