### ISSUE TITLE
how to make this.items can't update in updateItem

### ISSUE THREAD

**Issue by vanthinh91** [tabalinas/jsgrid#52]
i want to make this.items can't update in updateItem or after some event?
Thank!

**Comment by tabalinas** [comment]
Could you provide more info about the problem? Maybe you can change the http://jsfiddle.net/tabalinas/zzzfmpgt/ to demonstrate the problem?

**Comment by vanthinh91** [comment]
in function updateitem: 
http://jsfiddle.net/zzzfmpgt/3/

**Comment by tabalinas** [comment]
Save previous item in `onItemUpdating` callback. Then when validation is failed return this item from `updateItem` method.

Something like this:

        onItemUpdating: function(args) {
            previousItem = args.previousItem;
        },
    
        controller: {
            loadData: function(filter) {
                ...
            },
    
            updateItem: function(updatingItem) { 
                if(true){ // your validation condition here
                    alert("stop update this.clients");
                    return previousItem;
                }
                
                // ajax call to update here
            },
        },


See fiddle: http://jsfiddle.net/tabalinas/zzzfmpgt/4/

**Comment by vanthinh91** [comment]
thank!
But when filtering then this "" exists
http://i.imgur.com/tYNGcVs.png

**Comment by tabalinas** [comment]
If you return `previousItem` it should be fine. If it's not, please, modify the fiddle to demonstrate the problem http://jsfiddle.net/tabalinas/zzzfmpgt/4/

**Comment by vanthinh91** [comment]
change "Otto Clay" to null, where filtering all you see in "Otto Clay" is null
http://jsfiddle.net/tabalinas/zzzfmpgt/6/

**Comment by tabalinas** [comment]
The link gives 404.
