### ISSUE TITLE
How to insert rows dynamically (Websocket.Onmessage())

### ISSUE THREAD

**Issue by vsaji** [tabalinas/jsgrid#520]
Hi Team -

Can you please publish a sample code which demonstrates the dynamic insertion of row in the grid. I have a web socket listener in my program that receive json text. I would like add them on the top of the grid as and when a message receive.  The old entries should get pushed down.

Please help.

**Comment by tabalinas** [comment]
Have you tried to implement this?
If yes, then feel free to share your partial results (as a fiddle or probably a page with public access), so it will be possible to advise.
Also feel free to ask if you have any particular question.

**Comment by vsaji** [comment]
Sorry If my question has confused you. What I was intended to ask you was, how do I insert rows on the top position of the grid when a messages (some json row) received through some event. All the examples currently available on the net is demonstrating data loading during the page loading and not when a particular event happens.

**Comment by tabalinas** [comment]
You can control data of the grid yourself. Having an array and a grid with static data (using `data` option instead of controller). Then once you got data, update `data` option of the grid and call `refresh` method.
