### ISSUE TITLE
Nested jsgrid

### ISSUE THREAD

**Issue by matdrapeau** [tabalinas/jsgrid#521]
Hello,
I am wondering if it is possible to have a grid which has rows that contains a grid in one of their field?

**Comment by matdrapeau** [comment]
I came up with that example... but the behavior of the nested grid is weird...
http://jsfiddle.net/jngjk9o3/1/

**Comment by matdrapeau** [comment]
Closing the gap to make this work... but the inserts and edits are not working as expected. Also the spaces of the column of the nested grids is not large enough.
http://jsfiddle.net/jngjk9o3/2/
Any help would be appreciated

**Comment by tabalinas** [comment]
Do you mean inserts and edits of the nested grid?
Then first you need to prevent row click from bubbling to external grid, redefining `rowClick` of the nested grid as follows:

```js
rowClick: function(args) {
    if(this.editing) {
        this.editItem($(args.event.target).closest("tr"));
        args.event.stopPropagation();
    }
}
```

Another thing to realize is that with current approach uses static data, so once the external grid is refreshed for any reason, the edits of nested grid will be lost.

**Comment by matdrapeau** [comment]
You are right, the data of nested grids is lost when refreshed... is there any way to fix this?

Also, the `rowClick` blocks the inline edits:
http://jsfiddle.net/jngjk9o3/3/

Would it be smarter to adapt `insertRowRenderer` instead?

thanks

**Comment by tabalinas** [comment]
I'm not sure what you meant by "blocks the inline edits", but if you are talking about exceptions fired when you click rows of nested grid, then you could fix then with a "shield click handler", preventing click propagation (see here http://jsfiddle.net/tabalinas/w71odbyy/3/).

As is updates work. It all depends on what you want to achieve. Current example seems to work fine.

**Comment by matdrapeau** [comment]
@tabalinas In your given example, when I am trying to edit a nested grid, there isn't input boxes shown in order to put text inside.

**Comment by tabalinas** [comment]
It's because you have not define the `type` property for most of fields.

**Comment by ngordiz** [comment]
JsGrid - update a row based on the input change of another row.
Hi,
I am trying to reflect the input entered into one row, in another row of the GRID.  In the updateItem function, I update the current row that was just modified.    Then I get all the items in the grid, start a $.each loop.  When I find the proper row, I change the values of the columns in that row.  But I can't make the screen to reflect the new values.
Can you help me please.  Thanks
