### ISSUE TITLE
disable other field after select the option (apply only for its row)

### ISSUE THREAD

**Issue by FalinCh** [tabalinas/jsgrid#526]
Hiii.....
I have option <select> in my field, and I also have checkbox.
i want to ask is there any option after i select the option value in that row, it automatically disabled the checkbox of the same row?

Thanks

**Comment by ahmed610** [comment]
use insertRowRenderer and editRowRenderer to have better control on the elements and its events

**Comment by tabalinas** [comment]
@FalinCh, there is no built-in option for this case, but you can attach a handler to this select field so that it changes checkbox state.
Here is how to redefine the template and attach a change handler

editTemplate: function() {
    var $result = jsGrid.fields.text.prototype.editTemplate.call(this);
    $result.on("change", function() {
        // change state of the checkbox
    });
    return $result;
}

**Comment by GauravKatariya** [comment]
What do we have to specify in onChange method for disabling editing for some cells
