### ISSUE TITLE
ItemUpdate results in empty row

### ISSUE THREAD

**Issue by jdcalus** [tabalinas/jsgrid#527]
I am using the controller to loadData without any problems. The JSON that is used to populate the Grid  looks like the following:

```js
[{"doc_type":"Wordtag","_rev":"2-a16c3da837baf8d2d18e1ddf7ba5d2e6","_id":"0c89c9a4bd1a0f9fcac6a842a11f1cdb","Original":"Bro","Replacement":"Bra"},{"doc_type":"Wordtag","_rev":"1-b1dafdbc3f12b8621eef4b197f16a42d","_id":"5d4ee80b422818b62b2f6e68e81ee5e2","Original":"Ed","Replacement":"Edward"},{"doc_type":"Wordtag","_rev":"1-c18737acd3de00edfc1795f7220a96b0","_id":"955b3354f0a519ff8c22fe60820a83b7","Original":"Jess","Replacement":"Jeff"},{"doc_type":"Wordtag","_rev":"9-09f77fe0c82bfcce5b128a7053a21ed2","_id":"c46984a9d8244ac0e5bd673a43a77475","Original":"RX","Replacement":"Prescription"},{"doc_type":"Wordtag","_rev":"1-dd8bdf37afb557a75814fb29b4be2f87","_id":"c46984a9d8244ac0e5bd673a43a77803","Original":"No.","Replacement":"Number"},{"doc_type":"Wordtag","_rev":"1-e628318117cb43a55f0199179cd3ba1e","_id":"c46984a9d8244ac0e5bd673a43a78498","Original":"NO.","Replacement":"Number"},{"doc_type":"Wordtag","_rev":"3-bc79387a2032d984dbdf9ebedb7ecf37","_id":"fcfe3f06b7534a23d9e7cc9b14625068","Original":"Lis","Replacement":"Lisa"}]
```

My Fields looks like the following:

```js
fields: [
            { name: "Original", type: "text", key: true, width: 150, validate: "required" },
            { name: "Replacement", type: "text", width: 150 },
            { type: "control" }
        ]
```
The basis purpose of the grid is to allow someone to identify the original word and the word that is needed as a replacement.

The data is ultimately stored in a couchDB, which is where the _rev value and the _id values are managed.

So here is where I believe the problem exists. When I update one of the rows, the updateItem function gets call and I make an aJax request to my server. The Grid passes the entire json, as expected, and i update the couchDB with the new value for "Replacement". But couchDB changes the value of _ID. So when I send the new JSON back to the Grid it doesn't know where to update the row. I am assuming jsGrid is using _ID as the key for each row.

Is there a way to replace a row with a new value? My guess would be to keep a copy of the original json and replace with the new one. Currently the row that is updated blanks out after the call to the server to udpate.

Below is my updateItem function

```js
 updateItem: function(item) {
                var d = $.Deferred();
 
                $.ajax({
                    url: "http://localhost:5000/updateWord",
                    type: "PUT",
                    dataType: "json",
                    data: item,
                    success: function (data) {
                    	d.resolve(data);
                	},
                	error: function(e) {
                   	 alert("error: " + e.responseText);
                	}
                });
 
                return d.promise();
            },
```

Any help is appreciated.

**Comment by tabalinas** [comment]
js-grid should work as you expect, if I got the description right. The only thing to be sure is that the updated item is returned by backend and the `data` variable has expected value.

**Comment by tabalinas** [comment]
Close due to inactivity.
