### ISSUE TITLE
Columns with count down timer

### ISSUE THREAD

**Issue by vsaji** [tabalinas/jsgrid#528]
I am dynamically inserting rows into a grid as below (data receives via web socket event). 
```js
function onMessage(data){
	var grid = $("#jsGrid");
	var gridData = grid.jsGrid("option", "data");
	gridData.unshift(data);
	grid.jsGrid("refresh");
}
```
One of my column contains an integer value ex: 120, I want to implement an independent countdown control in each row which start counting-down the value to 0 from the original value as soon as the row is inserted. 

**Background**
This is essentially indicates time in seconds. The grid contains rows that indicates tokens obtained and its expiry seconds. Once the token is expired (count down to 0), the row should automatically removed from the grid. As you can see below, I have a control placed in the last column to terminate the token forcefully as well which is working fine. 

![image](https://cloud.githubusercontent.com/assets/691574/20747931/fad16ec2-b726-11e6-8725-fba53cc36883.png)

Can you please help in giving some advice on how I can implement this.

**Comment by tabalinas** [comment]
In the `itemTemplate` of your field set a timer, so that it does countdown and removes the row once it has 0. Here is an example code:

```js
// assume there is a 'timeout' field in the item

itemTemplate: (function() {
	var timers = {};

	return function(value, item) {
		
		var scheduleTimer = function() {
			clearTimeout(timers[item.id]);
			timers[item.id] = setTimeout(function() {
				if(item.timeout <= 1) {
					$("#jsGrid").jsGrid("deleteItem", item);
				}

				if(item.timeout > 1) {
					$result.text(--item.timeout);
					scheduleTimer();
				}
			}, 1000);
		}

		var $result = $("<div>");
		$result.text(item.timeout);

		scheduleTimer();

		return $result;
	};
})()

```

Here is the fiddle: ihttps://jsfiddle.net/tabalinas/t4035j08/

**Comment by vsaji** [comment]
Thanks a lot friend. It worked like gem. :+1:
