### ISSUE TITLE
Need to hide/show filter when pressing button using jquery

### ISSUE THREAD

**Issue by Image3D** [tabalinas/jsgrid#529]
I need to hide / show filter when pressing a button using jQuery.

Tried to use $("#jsGrid").jsGrid("fieldOption", "Filtering", false) but it did not work.

Can you help ?

**Comment by Image3D** [comment]
Solved. attribute must be "filtering" and not "Filtering"

This is the correct working code:

 $("#jsGrid").jsGrid("option", "filtering", false);

**Comment by tabalinas** [comment]
Glad that figured it out.
