### ISSUE TITLE
Checkboxes Value

### ISSUE THREAD

**Issue by fdourado** [tabalinas/jsgrid#531]
Hi, i'm trying to set value to each checkbox.

How can i do that?? I want click at checkbox all for loading everything 

Here is my code:

 headerTemplate: function () {
                                    return $("<input>").attr("type", "checkbox")
                                            .on("click", function () {

                                          //here i need find all checkboxes checked and send array with all values to my method.
                                                var checkboxes = (this).closest('#dvCheckBoxListControl').find(':checkbox');

                                                if ($(this).is(':checked')) {

                                                    checkboxes.prop('checked', true);
                                                    PushPinRepresentante(null, checkboxes);

                                                } else {
                                                    checkboxes.prop('checked', false);
                                                }
                                               
                                            }); 

Thanks

**Comment by tabalinas** [comment]
Did you find the solution yourself? 
Could you share it in comments?

**Comment by fdourado** [comment]
Sure,

You have to set value at itemTemplate something like:

 itemTemplate: function (_, item) {
                                   
                                    return $("<input>").attr("type", "checkbox")
                                            .prop("checked", false, $.inArray(item, result) > -1)
                                            .val(item.VALUE)
                                            .on("change", function () {

                                                var checkboxes = $(this).closest('#dvCheckBoxListControl').find(':checkbox');

                                                    PushPinRepresentante(checkboxes);
                                           
                                               
                                            });
                                }
Where the item is my array has value i want to set
