### ISSUE TITLE
create input / textbox conditionally

### ISSUE THREAD

**Issue by danisupr4** [tabalinas/jsgrid#532]
Hi, I have looked at source code,

```js
_createEditRow: function(item) {
				if($.isFunction(this.editRowRenderer)) {
					return $(this.renderTemplate(field.editRowRenderer, field, { item: item, itemIndex: this._itemIndex(item) }));
				}
				var $result = $("<tr>").addClass(this.editRowClass);

				console.log('item.myColumn: '+item.myColumn);
				this._eachField(function(field) {
					var fieldValue = this._getItemFieldValue(item, field);
					this._prepareCell("<td>", field, "editcss")
					.append(this.renderTemplate(field.editTemplate || "", field, { value: fieldValue, item: item }))
					.appendTo($result);
				});

				return $result;
			},
```

I have put `console.log` of `item.myColumn`, and have successfully echoed, then I want to make conditional task whether to generate textbox or not, depends on value of `item.myColumn`.
For example, if myColumn=1 then generate textbox, else, not generate.

How to solve that? thank you very much :)

**Comment by tabalinas** [comment]
I would not go to source, but just redefine `editTemplate` of the field.
For instance:

```js
editTemplate: function(value, item) {
    var $result = jsGrid.fields.text.prototype.editTemplate.apply(this, arguments);
    return item.myColumn ? $result : value;
}
```

Here it's assumed that you are using `text` field. If `myColumn` is falsy it renders just the value of the field instead of editing control.

**Comment by danisupr4** [comment]
Yes, agree, I mean that too, never modify the source, just override a function into my jsGrid, config.
I use your code, then it works perfectly, thank you :)
