### ISSUE TITLE
Add new button grid

### ISSUE THREAD

**Issue by fdourado** [tabalinas/jsgrid#533]
Someone can help me for add new button to grid??

**Comment by danisupr4** [comment]
inside any of your fields, put something like this

```
itemTemplate: function(value, item) {
    var $result = jsGrid.fields.control.prototype.itemTemplate.apply(this, arguments);
    var $customButton = $("<button>")
        .text('BUTTON')
        .click(function(e) {
            alert("....." + item.yourColumnValue);
            e.stopPropagation();
        });
    return $result.add($customButton);
}
```

**Comment by fdourado** [comment]
where i add style? or icon as background-image??

**Comment by tabalinas** [comment]
@fdourado: since in this example `$customButton` and be literally anything, you can do whatever you wish. For instance just `addClass("my-custom-button")` and then add your styles for `.my-custom-button` class.

**Comment by fdourado** [comment]
Sure, i already did

Thanks
