### ISSUE TITLE
Rows re-ordering don't save

### ISSUE THREAD

**Issue by Grey911** [tabalinas/jsgrid#535]
Good afternoon!
I use the sorting lines like this - [http://js-grid.com/demos/](http://js-grid.com/demos/) and everything works fine.
But when I'm trying to get JSON -

>  var result_json = JSON.stringify ($("#grid") jsGrid ( "option", "data"));

order of the data does not change the order of rows remains the same. What am I missing?

**Comment by tabalinas** [comment]
Could you provide a jsfiddle (for instance forking this one https://jsfiddle.net/tabalinas/cy8b8Lro/) or just a page with public access demonstrating the problem?

**Comment by Grey911** [comment]
https://jsfiddle.net/j44o1hnx/2/
After row reordering "Get values" button return same data as at start.

**Comment by tabalinas** [comment]
Now it's clear. I thought you are talking about sorting of the table (not rows reordering).
Well, reordering doesn't influence on the order of actual items.
If you wish items to be reordered too, you need to handle it.
See demo http://js-grid.com/demos/ Rows reordering for an example.
In the handler just set `items` back to `data` option of the grid.
