### ISSUE TITLE
ComboBox filter grid and cutom button error

### ISSUE THREAD

**Issue by fdourado** [tabalinas/jsgrid#537]
Hi, jsgrid is very amazing but i'm get some problems for display combobox for filter jsgrid and to render custom button here is my code:

```js
var array = new Array();
   ob = {
            loadData: function (filter) {
                return $.grep(this.clients, function (client) {
                    return (!filter.strNome || client.strNome.indexOf(filter.strNome) > -1)
                        && (!filter.strStatus || client.strStatus === filter.strStatus)
                });
            },
        }
        ob.clients = [{strCodigo:21313, strNome: "Jack", strStatus: 7, dblLong: "12322" }];
      

        ob.strStatus = [
        { Name: "", Id: 0 },
        { Name: "Adm Vendas", Id: 6 },
        { Name: "Bloqueado", Id: 7 },
        { Name: "Não Visitados", Id: 1 }
        ];


  $("#dvClientes").jsGrid({
            height: "70%",
            width: "50%",
            filtering: true,
            autoload: true,
            controller: ob,

 fields: [
                { name: "strCodigo", title: "Codigo", type: "text", width: 10, filtering: false, align: "center" },
                { name: "strNome", title: "Nome", type: "text", width: 30 },
                { name: "strStatus", title: "Status", type: "select", items: ob.strStatus, valueField: "Id", textField: "Name", width: 10 },
 {
                   headerTemplate: "Localizar",
                   itemTemplate: function (value, item) {
                       var $result = jsGrid.fields.control.prototype.itemTemplate.apply(this, arguments);
                       var $customButton = $("<button>").val(item.dblLong)
                           .addClass("btnLocalizar")

                           .click(function (e) {
                               alert("....." + item.dblLong);
                               e.stopPropagation();
                           });
                       return $result.add($customButton);
                   },
                   align: "center"
               }
            ]
        });
```

The combobox don't show for select to filter but textbox for filter by name works.
The CustomButton show error :
 `Uncaught TypeError: Cannot read property 'prototype' of undefined jquery-1.10.min.js:`

**Comment by tabalinas** [comment]
Since `select` field is redefined the same field should be used as a base implementation of `itemTemplate`:
```js
var $result = jsGrid.fields.select.prototype.itemTemplate.apply(this, arguments);
```

Not sure this is the only problem though.

**Comment by fdourado** [comment]
i figure out this error but found another
 to solve this error, i just put reference: <script src="~/Scripts/jsgrid/fields/jsgrid.field.select.js"></script>

my select field don't show textfield at grid, 

ob.countries = [
        { Name: "", Id: 0 },
        { Name: "Adm Vendas", Id: 6 },
        { Name: "Bloqueado", Id: 7 },
        { Name: "Não Visitados", Id: 1 },
        { Name: "Positivado", Id: 4 },
        { Name: "Reagendado", Id: 5 },
        { Name: "Semana", Id: 2 },
        { Name: "Visita Futura", Id: 3 }
        ];
        ob.clients = [
            { Name: "", Id: 0 },
        ];
  for (var i = 0; i < result.length; i++) {
            ob.clients[i] = { strNome: result[i].strNome, strCodigo: result[i].strCodigo,  strStatus: result[i].strStatus };
        }

    $("#dvClientes").jsGrid({
           
            width: "50%",
            filtering: true,
            autoload: true,
            controller: ob,
   fields: [
                { name: "strCodigo", title: "Codigo", type: "text", width: 10, filtering: false, align: "center" },
                { name: "strNome", title: "Nome", type: "text", filtering: false, width: 35 },
                { name: "strStatus", title: "Status", type: "select", items: ob.countries, valueField: "Id", textField: "Name", width: 15 }
]

**Comment by fdourado** [comment]
i found it, my field strStatus: result[i].strStatus was string, so i parseInt and works!!

Thanks!
