### ISSUE TITLE
Enhancement of interacting with server side for data pagination with ajax.

### ISSUE THREAD

**Issue by adual** [tabalinas/jsgrid#538]
User will prefer interacting with server side for pagination data but not whole data one time API calling.
When calling ajax, request parameters or post body should contain current page number, page size, search criteria etc for server side subsequent pagination querying.

**Comment by highfield** [comment]
It seems to me that the parameters are as you say.
I'm using a custom controller as described in: http://js-grid.com/docs/#loaddatafilter-promisedataresult

**Comment by adual** [comment]
@higfield Can you please share me your code? It will help me a lot, thanks.

**Comment by highfield** [comment]
Sure, but you should wait until Monday because I have it at work.

**Comment by tabalinas** [comment]
@adual, turn on `pageLoading: true` then grid will load data by pages.
Please take a look at this issue: https://github.com/tabalinas/jsgrid/issues/84

**Comment by adual** [comment]
@tabalinas Got it, thanks for your help.

**Comment by chavi289** [comment]
@tabalinas I cannot see the pageIndex getting passed correctly to my API call. I have initialized pageIndex as 0 and it remains 0 on every page change. Please help.
