### ISSUE TITLE
How to preset the sorting parameters on creation?

### ISSUE THREAD

**Issue by highfield** [tabalinas/jsgrid#539]
Either I didn't understand how to do, or it seems that's not possible to set the field/order parameters straight in the configuration, so that the very first load will send to the server the proper query.
My grid config is something like that:
```
        var config = {
            filtering: true,
            editing: false,
            sorting: true,
            paging: true,
            pageLoading: true,
            pageSize: 15,
            autoload: true,
            controller: dc,
            fields: [
                { name: "name", type: "text", width: 200 },
                { name: "value", type: "text", width: 150, filtering: false, sorting: false },
                ...
            ],
            ...
        };

```
Thanks in advance.

**Comment by tabalinas** [comment]
Try to turn off `autoload: false` and right after creation call `sort` method of the grid. 
If you have loading by page (`pageLoading: true`) then sorting will trigger loading automatically. If it's not the case, just call `loadData` after sorting.

**Comment by highfield** [comment]
Well, I've just created a test app, and your suggestion seems working fine. However, I must face the official app which is more complex, and I need some time (I think tomorrow will be possible).

https://github.com/highfield/jsGridDemo

I will leave you a feedback as soon as possible, so that you can close this issue.

Thank you very much for your effort.

**Comment by tabalinas** [comment]
Seems we figured it out.
