### ISSUE TITLE
JsGrid - Change the font in a one or more grids

### ISSUE THREAD

**Issue by ngordiz** [tabalinas/jsgrid#541]
Is there anyway I could change the font of some of the jsgrid-cell to bold.  
Thanks in advance for your help.

**Comment by tabalinas** [comment]
Sure, the way to do it depends on your use case.
If you want to make all cells of a particular column to be bold: define `css: "my-custom-class"` property of the field and then define styles in your stylesheet.
If you want only particular cells to be bold (depending on value or another item field): redefine `itemTemplate` and add your css class by condition:

```js
itemTemplate: function(value, item) { 
    return $("<div>").addClass(item.myFieldToMarkAsBold ? "my-custom-bold-class" : "").text(value);
}
```

**Comment by ngordiz** [comment]
Thanks for your response.
