### ISSUE TITLE
Horizontal scrollbar issue

### ISSUE THREAD

**Issue by iskitsas** [tabalinas/jsgrid#542]
Even on official demo pages I can see a horizontal scrollbar all the time

I have seen it in both Chrome and Firefox
js-grid version: 1.5.2
Ubuntu 16.04
Dell xps 13 9350 QHD - 3200x1800

Screenshots
![js-grid-1 5 2-sh_issue_firefox](https://cloud.githubusercontent.com/assets/1267871/21098772/717bdcce-c073-11e6-88fd-9df5ced140fd.png)
![jsgrid-1 5 2_sh_issue_chrome](https://cloud.githubusercontent.com/assets/1267871/21098773/71826ad0-c073-11e6-975e-9286fd3de317.png)

**Comment by tabalinas** [comment]
@iskitsas, could you please test it with v1.5.3 (current version).
Because on my Mac I cannot reproduce the issue.

**Comment by iskitsas** [comment]
Seems ok now
![js-grid-1 5 3-fixed](https://cloud.githubusercontent.com/assets/1267871/21246491/d4932e32-c331-11e6-80a3-6b35c19690e2.png)

**Comment by tabalinas** [comment]
@iskitsas, perfect, thank you!
