### ISSUE TITLE
How to extend filter object with custom value

### ISSUE THREAD

**Issue by rwoszczyk** [tabalinas/jsgrid#544]
I have additional checkbox in control column:

```js
type: "control",
            width: 80,
            itemTemplate: function() {

              if (arguments[1].IsDeleted === true) {
                return $('<span class="grid-control-label">').text("deteled");
              } else {
                return jsGrid.fields.control.prototype.itemTemplate.apply(this, arguments);
              }
            },
            filterTemplate: function() {

              var $result = jsGrid.fields.control.prototype.filterTemplate.apply(this, arguments);
              var $myButton = $("<label for='jsgrid_deleted_chbx' class='grid-filter-label' style='display: inline-block;'>" +
                "<input type='checkbox' id='jsgrid_deleted_chbx' name='IsDeleted' value='value'>" +
                "show deleted" +
                "</label>");

              $myButton.find('input')
                .change(function() {
                  $("#jsGrid").jsGrid("loadData");
                });

              return $result.add($myButton);

            }
```

It works fine while loading data, but when I trying get filter object : $("#jsGrid").jsGrid("getFilter"); then the boolean value of IsDeleted is not included.

What I am doing wrong ? Should I do it in another way ?

**Comment by tabalinas** [comment]
Do you have a field for `IsDeleted` in the grid?
In fact `getFilter` method returns only fields existing in the grid and having `filtering: true` (it's `true` by default).

**Comment by rwoszczyk** [comment]
I am guessing that I should have such field for IsDeleted (I can make them invisible since I don't need to display this column), but my question now is; 
How can I change filter value for this column / field IsDeteled from outside this column ?

**Comment by tabalinas** [comment]
Not sure I follow your use case. Before you were talking about `IsDelete` being absent from `getFilter` result. Now you are talking about changing `IsDelete` from outside.
What do you mean by 'outside'? Do you want to have this value in the `loadData(filter)`?
Please clarify your use case.

**Comment by rwoszczyk** [comment]
Yes, I will try clarify my use case.

I would like to have additional value in data model of row (IsDeleted field), but I dont need any additional column do display this (I am going to display value "IsDeleted"  in control column, instead of Edit/remove icons, since there is no sense to display edit and/or delete icons for deleted records).

Now, I would like to filter by IsDeleted field value as well like by any other columns filters. Unfortunately there is no IsDeleted value in object filter:

var filter = $("#grid").jsGrid("getFilter");

I would to change the IsDeleted field value (true/false) in filter object, by checkcbox situated also in header of control column (egzample in my first post).

How can I achive this ?

**Comment by tabalinas** [comment]
Ok, it's much more clear now, thanks.
So, in your case, you should not care about `getFilter`.
You have `loadData` of your controller, so you can just get filter value in this method. 
How you will do that depends on the implementation. So you can either just find it with jQuery selector, or create it and save to the field instance (in your `filterTemplate` add something like `this._isDeleteCheckbox = $("<input>").attr("type", "checkbox") ...`), so you will be able to read this value from the grid field.

```
loadData: function(filter) {
   filter.IsDeleted = $("#my-filter-checkbox").is(":checked");

   // filter is used here
}

**Comment by rwoszczyk** [comment]
OK, but my need is still unresolved.
I particulary call getFilter object, since I need filter values to send request without paging, to obtain all results and make the export to excel file.

**Comment by tabalinas** [comment]
Yes, but why you cannot add `IsDelete` to your filter before sending request?
It will be similar to my example with the only difference that you will call `getFilter` to get filter value.
