### ISSUE TITLE
Dynamically add an item to a select control

### ISSUE THREAD

**Issue by buknotoy** [tabalinas/jsgrid#545]
Hi, is there a way to dynamically add an option to a select control in the grid?

![image](https://cloud.githubusercontent.com/assets/22160322/21170768/29d3f8f6-c213-11e6-8c2c-131683e4e1f6.png)

I'm trying to add an entry to the 'Product Template' dropdown on the grid above.  The default options are being loaded correctly.  There is however a link on the same page that adds a new item and I would want that new item to be added to the list of options as well.

Thanks in advance.

**Comment by tabalinas** [comment]
Yes, just redefine `insertTemplate` (or `editTemplate`) to add new options. The similar value as it's done here for default value (https://github.com/tabalinas/jsgrid/issues/471).
But probably easier would be to add what you want to `items` for grid `select` in advance (with ajax call, and initialize grid on done...).
