### ISSUE TITLE
Is it possible to submit a row by hitting ENTER?

### ISSUE THREAD

**Issue by onebree** [tabalinas/jsgrid#546]
If I have an insert or edit row, I would like to submit that row by pressing ENTER while in any of the fields within that row. Basically, submit the row without physically clicking the check mark (or plus sign, if it's and insert row)

I am using js grid version 1.5.2

**Comment by tabalinas** [comment]
Yes, you can do that adding a handling the `Enter` key press.
Look at this comment https://github.com/tabalinas/jsgrid/issues/243#issuecomment-205171378

**Comment by onebree** [comment]
Thanks for the help, @tabalinas. This ended up being my code, and it worked:

```js
function insert_on_enter(field) {
  field.on("keydown", function(e) {
    if(e.keyCode === 13) {
      $("#payments_grid").jsGrid("insertItem");
      $("#payments_grid").jsGrid("clearInsert");
      return false;
    }
  });
}

function update_on_enter(field) {
  field.on("keydown", function(e) {
    if(e.keyCode === 13) {
      $("#payments_grid").jsGrid("updateItem");
      return false;
    }
  });
}
```

```js
insertTemplate: function(value) { 
  this.insertControl = $("<input>");
  insert_on_enter(this.insertControl);
  return this.insertControl;
},
editTemplate: function(value) { 
  this.editControl = $("<input>").val(value);
  update_on_enter(this.editControl);
  return this.editControl;
}
```

**Comment by tabalinas** [comment]
You are welcome! 
Thank you for posting the final result.

**Comment by carlosalzate74** [comment]
@onebree @tabalinas 

Great job!

Would you please provide a jsFiddle or an example, not sure where to place those functions.

Thank you

**Comment by MahdiMahzuni** [comment]
> @onebree @tabalinas
> 
> Great job!
> 
> Would you please provide a jsFiddle or an example, not sure where to place those functions.
> 
> Thank you

Your Field Object Can have editTemplate and addTemplate functions .
```
{ name: "quantity", type: "number", width: 50, editing:true, 
        editTemplate: function(value) {...},insertTemplate:function(.......
      }
```
