### ISSUE TITLE
jsgrid - Do not display the value of a column if it does not change

### ISSUE THREAD

**Issue by ngordiz** [tabalinas/jsgrid#547]
Is it possible not to display the value of one or more columns if the value does not change?

Thanks in advance for your help.

**Comment by tabalinas** [comment]
What do you mean by `change`? Is it a particular event?

**Comment by ngordiz** [comment]
I mean if the value remains the same and you don’t want to show the value in every row, until it changes again.

Thanks

**Comment by tabalinas** [comment]
@ngordiz, could you provide an example?

**Comment by ngordiz** [comment]
Manager name

Employee first name

Employee last name

Hours worked

status

John Doe

Tom

Adams

40

APPROVED

John Doe

Tim

Allan

45

Not Approved

John Doe

Nancy

Kim

40

Approved

Phil Sandy

Rose

Smith

37

approved


I would like not to display the second and the third John Doe, since it is the same as the first line.


Thanks, Nahid

**Comment by tabalinas** [comment]
I guess representation in the comment is not what you expected, right?
Would you mind to format it properly or put a screenshot to show expected result.

From what I undersrand you need to define a special `itemTemplate`, tracking the current value and previous value. It returns either a new value (when it's changed) or an empty string, if it's the same.

**Comment by ngordiz** [comment]
Thanks.  Sorry for the bad display.  I got it.

**Comment by tabalinas** [comment]
You are welcome!
