### ISSUE TITLE
[Question] What is the Licence 

### ISSUE THREAD

**Issue by crazypigs** [tabalinas/jsgrid#549]
I am working on a project and would like to know if this library has a MIT licence. Can I use this software without infringing on any copyright laws. We are going to need to use,edit the source and it will be kept private on our part to be sold as a complete product.

Many thanks,

Crazypigs

 #question

**Comment by tabalinas** [comment]
This is MIT (https://github.com/tabalinas/jsgrid/blob/master/LICENSE)
No worries. Feel free to modify and use it J
