### ISSUE TITLE
insertItem problem

### ISSUE THREAD

**Issue by tbellembois** [tabalinas/jsgrid#550]
Hello,

I have a problem with the `insertItem` function.
Here is my code:
```javascript
        var teams= [
            { "Name": "ATLAS" },
            { "Name": "ALICE" },
        ]; 
        var grid = $("#jsGrid").jsGrid({
            //...SOME PARAMS HERE...
            data: teams,
     
            fields: [
                { name: "Name", type: "text", width: 150, validate: "required" },
                { type: "control" }
            ],

            insertItem: function (item) {
                var d = $.Deferred();
                
                $.ajax({
                  method: "POST",
                  url: "/admin/team/insert/",
                  data: item,
                  dataType: "json",
                }).done(function( data ) {
                    console.log( "done:" + JSON.stringify(data) );
                    d.resolve(data);
                }).fail(function( msg ) {
                    console.log( "fail" + msg );
                    d.reject();
                });
                
                return d.promise();
            }
        });
```

The data returned from my server is `{"Name":"foo"}`.
But the new row is never inserted.
My jquery is `jquery-3.1.1.min.js`. I have tried with `jquery-1.11.3.min.js` without success.
I have tried to hard code `d.resolve({ "Name": "foo" })`.

I may have misunderstood how the function work.
Where is my mistake ? Thanks.
Regards,
Thomas

**Comment by tabalinas** [comment]
You need to define `insertItem` method in the `controller` option http://js-grid.com/docs/#controller.

**Comment by tbellembois** [comment]
Oups ! Yes, much better ! :) It works like a charm. Thanks.

**Comment by tabalinas** [comment]
You are welcome!

**Comment by kjindal** [comment]
I have a question: Why are you using d.resolve and reject functions? Thanks!

**Comment by tabalinas** [comment]
@kjindal, in case of `resolve` the insertion will be completed and item will be added to the grid. In case of `reject` insertion will be canceled.

**Comment by arnvidhr** [comment]
In case of rejection, I still see added newly rows...
