### ISSUE TITLE
Is it possible to generate fields[] section from JSON?

### ISSUE THREAD

**Issue by pavel1992** [tabalinas/jsgrid#552]
In my project i want to generate full table from json array received by ajax. 

Is it possible to get fields section with it? 
I mean i have json like
```
[
  {
    "id": "number",
    "name": "text",
    "price": "number"
  }
]
```
I want to try to parse it with   `$.each(response, function (index, value)) `
in fields section to get something like 
```
fields:[
{name: "id", type:"number"}
{name: "name", type:"text"}
{name:"price", type:"number"}
]
```

Is it right way, or i missed some methods for it in   documentation?

**Comment by tabalinas** [comment]
Yes, this seems to be the good way to do it. 
Get the response, iterate over item fields and create fields array, then create grid.

**Comment by pavel1992** [comment]
Now i have new problem:
i v got array: `["name: "price", type:"number"", "name: "name", type:"text"", "name: "id", type:"number""]` 
and a json string: `[{"price":"$10","name":"New Item 0","id":10},{"price":"$11","name":"New Item 1","id":11},{"price":"$12","name":"New Item 2","id":12}]` .
I m trying 2 initialize table with code like
```
  $("#jsGrid").jsGrid({
            width: "100%",
            height: "400px",

            inserting: true,
            editing: true,
            sorting: true,
            paging: true,
            controller:
                {
                    loaddata: JSON.stringify(mydata)
                },
            fields: myheader
        });
```
and i see empty field. Can u tell me, what i m doing wrong?
And before u asking about JSON.stringify, i debug output it, it s right way to get string, not an [Object Object Object]

**Comment by pavel1992** [comment]
Okay, i solved it. Right way to generate fields section was
```
function parseHeader(headerFromAjax)
    {   var parsedHeader = new Array();
        $.each(headerFromAjax[0], function (index, value) {
                var o = new Object();
                o.name = index;
                o.type = value;

               parsedHeader.push(o);

        });


        return parsedHeader;
    }
```

**Comment by tabalinas** [comment]
I'm not sure I followed your example, but there are several issues:
 - `loaddata` should be `loadData`
 - `loadData` should be a function returning data: `loadData: function() { return items; }
 - returned items should be a valid JS array, not a string representation of a JSON.
