### ISSUE TITLE
New and Updated Items Are Not Showing in the Grid

### ISSUE THREAD

**Issue by 19peaches** [tabalinas/jsgrid#553]
Hello.

I really love this plugin a lot, but I'm having trouble getting the grid to reload with added or updated items. It looks like the item exists because the row remains, but there aren't any values in the row.

During the edit:

![edit](https://cloud.githubusercontent.com/assets/1456472/21278814/7bc81e66-c39a-11e6-8a41-0973afaa7b20.png)

And after I save, it does get updated on my back end, but the grid info disappears:

![after-save](https://cloud.githubusercontent.com/assets/1456472/21278839/97bc1ad2-c39a-11e6-8e94-86dd75b9674f.png)

Any ideas? Have you seen this behavior before? It was working till I added the toastr plugin, but I removed it and now I'm getting these blank rows.

I'd appreciate any help.

**Comment by tabalinas** [comment]
Could you share your grid config?

**Comment by 19peaches** [comment]
Ah ... yes ... I did change that to return a success or error message. My whole config is pretty enormous so I'll just put the updateItem method:

```
updateItem: function(item) {
    var url = "{{ route('cards.update', ['id' => ':id']) }}";
    var url = url.replace(':id', item.id);

    return $.ajax({
        headers: {'X-CSRF-TOKEN': $('meta[name="token"]').attr('content')},
        type: 'POST',
        url: url,
        data: item,
        success: function(json) {
            if (json['type'] == 'success') {
                toastr.success(json['message'], json['title']);
            } else {
                toastr.error(json['message'], json['title']);
            }
        }
    });
},
```

How can I return a message from my controller without throwing off the grid? Can I return the item and the message in the same object and just utilize the message parts I need? Or is there a way to get the grid to ignore the returned message and just update as it does without it?

Thanks for your help.

-V

**Comment by 19peaches** [comment]
Ok nevermind man, I got it sorted. I just stored the item and returned it in the success method of the ajax command.

Thanks a lot.

**Comment by 19peaches** [comment]
Ok, I spoke too soon.

It works for updateItem but not for insertItem.

My insertItem code looks like so:

```
insertItem: function(item) {
    $item = item;

    $.ajax({
        headers: {'X-CSRF-TOKEN': $('meta[name="token"]').attr('content')},
        type: 'POST',
        url: "{{ route('cards.store') }}",
        data: item,
        success: function(json) {
            if (json['type'] == 'success') {
                toastr.success(json['message'], json['title']);

                return $item;
                
            } else {
                toastr.error(json['message'], json['title']);
            }
        }
    });
}
```

Thanks.

**Comment by tabalinas** [comment]
Have you tried to return the inserted item from `insertItem`?
You are talking about `insertItem`, does this mean that `updateItem` now works as expected?

**Comment by tabalinas** [comment]
No answer, closing for now.
