### ISSUE TITLE
Auto grow / auto resize text area

### ISSUE THREAD

**Issue by Tamizzz** [tabalinas/jsgrid#554]
Hi,

I am currently stuck auto resizable ( text area height is as big as the content inside ) textarea, checked for solutions and all of them suggest in adding external class to text area.

How do i add external class to textarea, since there is provision for css in fields attribute is there any provision for class in fields attribute ? or Do you have any alternate solution ?

**Comment by tabalinas** [comment]
You can assign a class to the field with `css` property and then style your textarea depending on this class. No need to set class on the textarea itself (while it's also possible redefining field templates)
