### ISSUE TITLE
Text from select field is not showing when custom cellRenderer is set.

### ISSUE THREAD

**Issue by Ranentil** [tabalinas/jsgrid#557]
Hi,
When custom cell rendering is set for text field, then select field column is displayed as id value. 
Can I somehow display textField from SelectFiled?

http://jsfiddle.net/x20wc9me/

**Comment by tabalinas** [comment]
With `cellRenderer` it's you who decide what to show in the cell.
First, it should be provided for the field that you want to customize.

Here is corrected example: http://jsfiddle.net/vxp549aw/

While I'm not sure why you need `cellRenderer` in this case.
