### ISSUE TITLE
How to call loadData from button event click ?

### ISSUE THREAD

**Issue by vohoangnhut** [tabalinas/jsgrid#558]
Hi Host.
Sorry for my bad english.
Im trying to call controller.loadData of the grid from outside the grid render.
Example : I set autoload equal false and I wanna call loadData of grid when i click a Button after grid created.
I dont how to do it. Can you help me

**Comment by vohoangnhut** [comment]
I resolved my question.

I turned off autoload
`//Auto load data
autoload: false,`

- Created a function, call loadData again 
`var objSearch = {};
function loadData(param) {
    objSearch.param1 = param;
    objSearch.param2 = "param2";
    $("#jsGrid").jsGrid("loadData");
};`

- Passing this param into loadData in controller
` controller: {

            loadData: function (filter) {
                var d = $.Deferred();
                filter.condition = objSearch;
                $.ajax({
                    type: 'GET',
                    url: "/Mail/getData",
                    dataType: "json",
                    data: filter,
                    success: function (data) {
                        d.resolve(data);
                    },
                    error: function(e) {
                        alert("error: " + e.responseText);
                    }
                });

                return d.promise();
              },`

anyway. I hope this can help some newbie suck as me.

**Comment by tabalinas** [comment]
Glad that you figured it out.
