### ISSUE TITLE
On update fail how to prevent from clearing input values?

### ISSUE THREAD

**Issue by deepak-trimantra** [tabalinas/jsgrid#559]
Hi,
I refer #475 for inserting and it works fine. But i am not able to do the same in case of update.
I don't want to clear values when update fails. Can you give me any solution for this?

**Comment by tabalinas** [comment]
What if you won't resolve promise on failure? Have you tried to reject?
I'm not 100% sure I understand what you are trying to achieve.
Anyway, jsfiddle or any other example demonstrating the problem would be helpful.

**Comment by deepak-trimantra** [comment]
Hi, Thanks for reply

i try it on jsfiddle

http://jsfiddle.net/zptyjnxh/28/

if you see in insert when you set flag = 1 and add something insert boxes gets clear.
if you set flag = 0 the insert boxes will hold their values.

I am using this for inserting items in the database, idea here is to stop inserting if there is error / wrong data, instead of clearing form i did this so user will not loose data and make changes and again try to insert. This works fine as i wanted.

But for updating i am not able to achieve this, in both the cases update boxes closes. Can you tell me how to reject promise? the solution you are saying.

ISSUE is If user tries to update any row and if value is wrong or duplicate instead of clearing edit boxes and closing edit mode hold the values. 

Tell me if you still not get the issue.

**Comment by tabalinas** [comment]
As I mentioned, you need to reject the deferred instead of resolving it `d.reject()`.

About `args.cancel = true`; it makes sense to do it only in `-ing` callbacks (`onItemUpdating` etc), because in `-ed` callbacks it's too late the action has been done already.
