### ISSUE TITLE
Clarify documentation on pattern validator

### ISSUE THREAD

**Issue by onebree** [tabalinas/jsgrid#560]
Right now, the documentation for using the `"pattern"` validator is:

> **pattern** - the field value should match the defined pattern (the pattern should be provided as a string regexp in `param` field of validation config)

I think this statement can be clarified to explain that a regexp literal could be passed as well.

Looking at the source code, if a string is provided, it is used in a `RegExp` instance. Otherwise, `param` is not altered (remains a literal) and is tested directly against the value.

https://github.com/tabalinas/jsgrid/blob/master/src/jsgrid.validation.js#L101-L109

```js
pattern: {
  message: "Field value is not matching the defined pattern",
  validator: function(value, _, param) {
    if(typeof param === "string") {
      param = new RegExp("^(?:" + param + ")$");
    }
    return param.test(value);
  }
}
```

**Comment by tabalinas** [comment]
Indeed! Thank you for spotting!
Don't you mind to make a PR with the correction?

**Comment by onebree** [comment]
Not at all! I'll get one submitted today.

**Comment by onebree** [comment]
@tabalinas I saw that there is also a gh-pages branch for this repo. Where should I add my changes to for the docs? In the README in master, or somewhere in gh-pages?

**Comment by tabalinas** [comment]
@onebree, README on `master`.

**Comment by hbarbosa437** [comment]
Hi

I would like to turn a field editable based on other grid field which is a checkbox. How can I do taht
