### ISSUE TITLE
responsive

### ISSUE THREAD

**Issue by fdourado** [tabalinas/jsgrid#563]
Hi, 
I want to know if its possible to do responsive, css

i tryed with % but its wrong

 fields: [
                { name: "strCodigo", title: "Codigo", type: "text", width: 5, filtering: false, align: "center" },
                { name: "strNome", title: "Nome", type: "text", filtering: false, width: 45% },
                { name: "strStatus", title: "Status", type: "select", items: ob.countries, valueField: "Id", textField: "Name", width: 23% }

Thanks

**Comment by tabalinas** [comment]
`45%` is incorrect value in JavaScript. Have you tried to provide these values correctly in quotes (`"45%"`)?

**Comment by tabalinas** [comment]
See working example https://jsfiddle.net/tabalinas/v6ww51ez/
