### ISSUE TITLE
On click of edit button show dilog details 

### ISSUE THREAD

**Issue by kishorejv** [tabalinas/jsgrid#566]
Hi ,
I am able to get modal pop up jquery's on clik of a row . similarly i would like to open same dilog on clik of edit icon . How can i acheive that .

**Comment by tabalinas** [comment]
Redefine `control` field.
You could define your custom field, redefine click handler on the existing edit button, or just add your edit button (turn off standard one with `editButton: false` so you will have only one):

```js
itemTemplate: function(value, item) {
	var $result = $([]);

	var $originalTemplate = jsGrid.fields.control.prototype.itemTemplate(value, item);

	var $myEditButton = this._createGridButton(this.editButtonClass, this.editButtonTooltip, function(grid, e) {
	    // show dialog here
	    e.stopPropagation();
	});

	return $result.add($myEditButton).add($originalTemplate);
}
```
