### ISSUE TITLE
Grid Columns overlapping when inside other div

### ISSUE THREAD

**Issue by navar45000** [tabalinas/jsgrid#567]
Here's an example of when using jsgrid inside a drop down menu.  The problem is that when you have lots of columns of data,  the grid is getting compressed together rather than overflow into the area accessible by the horizontal scroll bar.
![grid-issue](https://cloud.githubusercontent.com/assets/11891371/21510194/871693ca-cc45-11e6-808c-f4f2bd063252.png)

**Comment by tabalinas** [comment]
What do you have in `width` option of the grid and what is in you `fields` width configuration?
Could it be the case that grid is rendered in the hidden controller? If  it's the case, then calling `refresh` method of the grid should fix it.

**Comment by navar45000** [comment]
The problem is with the default setting of using table-layout: fixed on .jsgrid-table class.   I will edit the class to fix the problem. It seems that if you have columns going off the viewable portion of the div the table-layout: fixed makes matters worse.
![table-layout-fixed](https://cloud.githubusercontent.com/assets/11891371/21531871/3e2f5a00-cd00-11e6-971b-eccabd1bcff9.png)
![table-layout-fixed-normal](https://cloud.githubusercontent.com/assets/11891371/21531872/3e3fe924-cd00-11e6-865e-5dc93380f79a.png)

**Comment by navar45000** [comment]
One of the things that is helping to align things is to use jquery to set min-width which css is respecting.  the regular css width seems like it's being ignored.

**Comment by tabalinas** [comment]
`table-layout: fixed` ensures column width to be set defined by the width of the first row cells.
Probably it's possible that width of columns are too small. That's why it would make sense to see the config of the grid.

**Comment by tabalinas** [comment]
@navar45000, could you share your grid config? Or probably your app is available online?

**Comment by tabalinas** [comment]
No feedback is given. Closing the issue.
