### ISSUE TITLE
How to export jsGrid Data in Excel or CSV file.

### ISSUE THREAD

**Issue by jackryu** [tabalinas/jsgrid#568]
How to export jsGrid Data in Excel or CSV file.

**Comment by navar45000** [comment]
The way I did it is to use something like alasql which allows json to excel export.   Then you need to use the data option on the jsgrid to get the json data.

**Comment by tabalinas** [comment]
@navar45000, thank you for the answer.

You can also checkout the following issue https://github.com/tabalinas/jsgrid/issues/59.
It also provides a few solutions.
