### ISSUE TITLE
Hi, some help.

### ISSUE THREAD

**Issue by MarcelVe** [tabalinas/jsgrid#57]
Hi, this grid is great.
But i need to use this grid with RedBeanPHP to show data.
Can you help on how to return the data from RedBeanPHP to fill grid?
Sorry, my english is not so good.
Thank you.

**Comment by tabalinas** [comment]
Hi, 

I guess this http://www.redbeanphp.com/manual3_0/rest_server is the best way. Just provide your data as json to jsGrid.

**Comment by tabalinas** [comment]
Be more specific if need any further assistance.
