### ISSUE TITLE
range date

### ISSUE THREAD

**Issue by nmorich** [tabalinas/jsgrid#575]
if i use this http://jsfiddle.net/tabalinas/doaw2zgs/ work great but the field with end date not display.
How add 1 day to end date of range?

Thanks

**Comment by tabalinas** [comment]
This has nothing to do with js-grid. This is about data filtering logic (defined in `db`).
You can add one day (as in this example http://jsfiddle.net/tLob70hd/), or just provide dates w/o time in grid data.
