### ISSUE TITLE
Change label/text column on dropdown selection in JsGrid

### ISSUE THREAD

**Issue by priyarathi** [tabalinas/jsgrid#577]
Hello,

How do I change label/text value on dropdown change?

In edit template on dropdown change, I am calling ajax method to get the label value.
On ajax success, I need to assign the json value to another column of label type in jsgrid.

I have tried below ways with no luck :(

```js
perDiemField.val(json);
perDiemField.text = json;
perDiemField.textSelect = json;
perDiemField.value = json;
```

Please help!

Thanks!

**Comment by tabalinas** [comment]
What is `perDiemField` variable in your case?
Would be great if you could provide a jsfiddle or any other example of you use case (forking this one for instance: https://jsfiddle.net/tabalinas/v6ww51ez/)

**Comment by tabalinas** [comment]
No answer, closing
