### ISSUE TITLE
Is there a property on columns to make them automatically size to the size of their respective header? 

### ISSUE THREAD

**Issue by runithome** [tabalinas/jsgrid#58]
Is there an "auto" property on the column width as opposed to using a fixed width? I am trying to create columns which are the same size of the headers. The header row does automatically size the columns, but the rows of data seem to require fixed widths.

**Comment by tabalinas** [comment]
No, there is no such property for field (column) width. The reason is that header and body tables are separated, so to sync their width we need to specify it. 

Anyway, you can specify the width according to header width, and it will work. Also you can specify field width in percents.

**Comment by runithome** [comment]
Ok. Matching the header and field widths using percentages should do the trick.
Thanks very much.

**Comment by tabalinas** [comment]
You are welcome!
