### ISSUE TITLE
row edit based on conditions

### ISSUE THREAD

**Issue by koni1225** [tabalinas/jsgrid#580]
Hi Tabalinas,

Hope u r doing well.

i had a small situation, i need to edit row based on the condition 

for example : if id is equals to 1 i need to edit that row other no need to edit.

can you give me some example.

Thanks in advance.

**Comment by tabalinas** [comment]
Use `rowClick` handler.
The default implementation is the following:

```js
        rowClick: function(args) {
            if(this.editing) {
                this.editItem($(args.event.target).closest("tr"));
            }
        },
```

Update the condition so that it's not editing for particular items. (you will have an item in `args.itam`).

**Comment by koni1225** [comment]
Hi Tabalinas,

Hope u r doing well.

Thanks for u r reply the example u r given is working perfectly.

but the edit icon is enabled how to disable the edit icon

Thanks in advance.

**Comment by tabalinas** [comment]
If you are using `control` field then set `editButton: false` in the field config.
