### ISSUE TITLE
conditional show/hide control column in jsgrid

### ISSUE THREAD

**Issue by priyarathi** [tabalinas/jsgrid#583]
Any idea on how do I show/hide control column based on model property?

**Comment by priyarathi** [comment]
I found the solution. I added a property Name  : "Control" to my control column and then added below on my model property check to hide the column:
 $("#itineraryJsGrid").jsGrid("fieldOption", "Control", "visible", false);

**Comment by tabalinas** [comment]
Glad that you found the solution. 
Note: it's not necessary to specify the field name, you can reference the field by the index
See `fieldOption` docs for me info http://js-grid.com/docs/#fieldoptionfieldnamefieldindex-optionname-optionvalue.
