### ISSUE TITLE
Custom filter row with {less than; equals; greater than} options.

### ISSUE THREAD

**Issue by pavel1992** [tabalinas/jsgrid#585]
Is there any possible way to create/define custom filter row for client side filtering?

As i see, filter-row is an object with {column name:filter value} structure. 
So, can i somehow add some selector for working with number type fields, or i should filter data some other way and then refresh jsgrid with my filtered data?

**Comment by tabalinas** [comment]
You can define the filtering cell content redefining `filterTemplate`, and `filterValue` function should return filter value. The filter value can be complex, for instance a plain object of any structure.
If you would provide more info about your use case it would be easier to advise.

**Comment by pavel1992** [comment]
I want a custom filter fields, which depends on column type. For example, for text column it will be deafult, for number column it should have an input and a selector with >, =, < options. I modified my client-side filter function from ` function applyFilter(data, header){}`

to ` function applyFilter(data, filter, header)`, so now i know type of a column when filtering. But i don't understand, how to put more then 1 insert into single filter field.
Sorry if it's obvious question, i m pretty new in JavaScript.

**Comment by tabalinas** [comment]
I'm not sure the issues is clear. What is `applyFilter` function and where do you use it?
Could you provide an example demonstrating the issue or at least the source code of your case?

**Comment by tabalinas** [comment]
No answer, closing
