### ISSUE TITLE
Dropdown not Coming in Edit Template

### ISSUE THREAD

**Issue by dhawkKD** [tabalinas/jsgrid#586]
Hi,

I am using JS-Grid for inline update , grid has 5 columns four are of text type and 1 is Select type.
When I am clicking on the row, edit row comes, but with the text box only not with the select control.

After using Developers tool I can see the drop down in the source, but somehow it is not appearing on the page.

Thanks.
![select issue](https://cloud.githubusercontent.com/assets/17156312/21928654/1267072e-d9b2-11e6-88f5-745593c072bb.PNG)
![image](https://cloud.githubusercontent.com/assets/17156312/21928684/34cde6ca-d9b2-11e6-8efe-494feb38e75f.png)

**Comment by tabalinas** [comment]
This is really weird, do you use any specific css that could just hide your select?
Why other text fields don't look like usual inputs?

Would be much easier to help if you could provide an example (in jsfiddle, just a page with public access, or any other way).

**Comment by tabalinas** [comment]
No answer, closing.
