### ISSUE TITLE
How to get the on change event for First Row (Add Row)

### ISSUE THREAD

**Issue by DasariNitesh** [tabalinas/jsgrid#587]
Hi,
I created the jsGrid with the userId(combo selection),UserName and Agency(combo selection).

Te first row is used to create the data and remaining rows just display only  ..
the screen shot is attached below.
the code used is:

```js
grid =$("#jsGrid").jsGrid({
    height: "70%",
    width: "70%",
    
      editing: true,
      inserting: true,
      sorting: true,
      paging: true,
      autoload: true,
    
    controller: {
	loadData: function(filter) {
        return $.grep(userToTAS, function(user) {
		
		
		//var searchString = $.trim($("#search").val());
		var searchString =filter.search;	
            return (!searchString || user.UserId.indexOf(searchString) > -1)
			        || (!searchString || user.UserName.indexOf(searchString) > -1)
		            || (!searchString || user.TA.indexOf(searchString)> -1);
        });
    },
	
    
    insertItem: function(item) {
	   alert(item.UserId);
	   for (i = 0; i < item.TA.length; i++) { 
			alert(item.TA[i]);
			//$("#jsGrid").jsGrid("clearInsert");
	}
       // this.userToTAS.push(item);
	   
	    var d = $.Deferred();
		setTimeout(function () {			
			grid.insertFailed = true;
			
			d.resolve();
		},2);
		return d.promise();
    },
    
    deleteItem: function(item) {
        var index = $.inArray(item, userToTAS);
        userToTAS.splice(index, 1);
    }
    
},
    
    fields: [
	    
					
        { name: "UserId", type: "select",width: 150, align: "center" , items: users,valueField: "Id", textField: "Name"},
        { name: "UserName", type: "text", inserting: false },
        { name: "TA", type: "multiselect", width: 100, align: "center", items: transitAgencies, textField: "TAName" },
        { type: "control",  modeSwitchButton: false,editButton: false }
    ]
});
```

question is how to get the on change of userId combo select box.?
please find the attached full source code file

```html
<img width="960" alt="ui screen shot" src="https://cloud.githubusercontent.com/assets/25143385/21970781/b32c2572-db6f-11e6-93fb-cbd206b56d13.png">
```

**Comment by DasariNitesh** [comment]
Hi All,

I am able to get the on change event of userId combo box using the following code:

  { name: "UserId", type: "select",width: 150, align: "center" , items: users,valueField: "Id", textField: "Name",
		
			insertTemplate: function() {	              			
	                var $insertControl = jsGrid.fields.select.prototype.insertTemplate.call(this);
	                $insertControl.on("change", function() {
					    var selectedUserId = $(this).val();					  
						var selectedUser = $.grep(users, function(user) {
	                        return user.Id === selectedUserId;
	                    });						
						if (selectedUser.length == 1) {								
							var userNameWithId = selectedUser[0].Name;	
							var userName = userNameWithId.split(':')[1];
							$(".userName-insert").empty().append(userName);
						}							
					});
					return $insertControl;
					}
		},this 

If any one wants to see the complete example please check  the following attached example:

**Comment by tabalinas** [comment]
Thanks for sharing the solution.
Looks like mentioned attachment is not available.
