### ISSUE TITLE
Control Column in table

### ISSUE THREAD

**Issue by atomixstar** [tabalinas/jsgrid#588]
Hi, I really need to know if is possible to control the columns inside the table, add, edit and delete.

I checked documents but is new to me and I need it very urgently if knows someone.

**Comment by tabalinas** [comment]
By `controlling columns` you mean add/change/delete columns of the grid on the fly?
Yes, you can change `fields` option using `option` method (http://js-grid.com/docs/#optionoptionname-optionvalue) to the new collection of fields.
Or just change an a particular field option with http://js-grid.com/docs/#fieldoptionfieldnamefieldindex-optionname-optionvalue

**Comment by atomixstar** [comment]
Exactly, can please provide a sample code for that ?

I just need the jsgrid to allow users build their own table and after click submit to add the html code generated intro a database.

**Comment by tabalinas** [comment]
Examples for both mentioned grid api methods are available in the docs (see my previous method).
