### ISSUE TITLE
populating JQuery example

### ISSUE THREAD

**Issue by dataSQL** [tabalinas/jsgrid#594]
http://js-grid.com/getting-started/

Hello, I followed your wonderful example but the grid did not populate, please any suggestions?
[https://www.useloom.com/share/6dccfae0de3211e6a08e17679c6c16a7](url)

**Comment by tabalinas** [comment]
Do you link jQuery to the page? It should be added before jsgrid, since jQuery is required.

Also noticed that you have two links to js-grid scripts. There should be single link to js-grid.

**Comment by dataSQL** [comment]
Thank you, shall have a chance to view in 2 hours, am not at my IDE computer right now.  Thank you for the reply.

Jon
