### ISSUE TITLE
How do I do a Master Detail grid?

### ISSUE THREAD

**Issue by meatballcoder** [tabalinas/jsgrid#595]
Since the versions may be new, I thought I'd ask in 2017.

If I want a master/detail view or a way to populate one grid from another, do I use this:

https://github.com/tabalinas/jsgrid/issues/316

https://github.com/tabalinas/jsgrid/issues/102

I only ask so that I don't reinvent the wheel.  Thanks.

**Comment by tabalinas** [comment]
Yes, it's still the same. You can use these issues as examples.

**Comment by tecnicoc** [comment]
It's possible edit detail table. Is there an example?
