### ISSUE TITLE
Detect "insert button click", "cancel insert", and "cancel edit"

### ISSUE THREAD

**Issue by alexcoroza** [tabalinas/jsgrid#596]
What Im planning is to reveal a hidden field when inserting or editing and then hide it again whenever the user saves it or cancels it, but it seems I cant find find these events in the documentation >> callbacks

**Comment by tabalinas** [comment]
You can redefine templates of the control field and attach your handlers.

**Comment by NewBo1234** [comment]
Could you please show what that might look like?

**Comment by tabalinas** [comment]
In the `control` field definition override necessary template and add click handler with custom code.

```js
{
    type: "control",
    itemTemplate: function(_, item) {
        var $result = jsGrid.fields.control.prototype.itemTemplate.apply(this, arguments);

        // add click handler to edit button (goes first)
        $result.eq(0).click(function() {
            console.log("edit", item);
        });

        return $result;
    }
}

```
