### ISSUE TITLE
PHP options in JSGrid Select

### ISSUE THREAD

**Issue by mistaq** [tabalinas/jsgrid#598]
I want to use a PHP array as the options in a JS Grid select, something like this:

```html
        <script>
            var clients = [
            ];

            var countries = <?php $options_array ?>;

            $("#jsGrid").jsGrid({
                width: "100%",
                height: "400px",

                inserting: true,
                editing: true,
                sorting: true,
                paging: true,

                data: clients,

                fields: [
                    { name: "Name", type: "text", width: 150, validate: "required" },
                    { name: "Age", type: "number", width: 50 },
                    { name: "Address", type: "text", width: 200 },
                    { name: "Country", type: "select", items: countries, valueField: "Id", textField: "Name" },
                    { name: "Married", type: "checkbox", title: "Is Married", sorting: false },
                    { type: "control" }
                ]
            });
        </script>
```
However, when I attempt to do that, the entire JSGrid does not load.  This is using CakePHP 3.

**Comment by tabalinas** [comment]
Are you sure rendered JS is valid? Have you checked the source of the html page rendered in the browser?

**Comment by mistaq** [comment]
Yes. The variable is empty, it shows countries = ;

I've also tried json_encode, and while that does load them in the source code like this: var countries = `{"1":"Australia","2":"United States"};`
the JSGrid still doesn't load. 

I'm thinking it might be to do with the array not having valueField or textField. If we don't issue a value/text field, would it just normally load the entire line of each array?

**Comment by tabalinas** [comment]
`countries` should an array. Please checkout docs http://js-grid.com/docs/#select
Also you can check the exception you have in DevTools of the browser.

**Comment by mistaq** [comment]
Okay I got it working, turns out I had put quotation marks around the items for the select.

**Comment by tabalinas** [comment]
Glad that you figured it out!
