### ISSUE TITLE
updateItem: trigger call only when the row content is changed

### ISSUE THREAD

**Issue by georges49** [tabalinas/jsgrid#599]
Hello tabalinas,
I'm using your grid in my web app and it is really great.

I have a question related to editing.

```js
rowClick: function(args) {
            
var $row = $(args.event.target).closest("tr");
var $cell = $(args.event.target).closest(".jsgrid-cell");
cellIndex = $($row.find("td")).index($cell);
if(this._editingRow) {
   this.updateItem();
}
if (this.editing){
       this.editItem($row);
}
},
```

I am using the code above to trigger a call to the backend when I click outside the row that was in edit mode.

However this code triggers a call even if I do not change any value in the row. 

Is there a way to trigger the call only when at least one cell value has changed?

Thanks.

**Comment by tabalinas** [comment]
You can call `updateItem` in any case, but do the check in `controller.updateItem`. In `onItemUpdating` you can access the original updating item (`args.previousItem`) and changed item (`args.item`). Knowing if item has been changed or not you can either send ajax request or just ignore the change.

**Comment by georges49** [comment]
Thanks a lot. This is exactly what I was looking for.

**Comment by tabalinas** [comment]
You are welcome!
