### ISSUE TITLE
Field with Action Menu without Editing set to true

### ISSUE THREAD

**Issue by iTabALot** [tabalinas/jsgrid#602]
Hi, 
Is it possible to add a dropdown menu to a field either as a custom-field or text rendered from cellRenderer? I have gone over the docs but the 'select' type field only works when the jsGrid is in editing mode...possible to avoid that so that a user can select an action from a list. List can contain anything from jumping to another page on my website etc.

Never mind - I have figured it out.

**Comment by tabalinas** [comment]
As I understand, you have to redefine `itemTemplate` to render the `select` component.

Anyway, glad that you figured it out! What have you done finally?
