### ISSUE TITLE
OnClick Modal for text input

### ISSUE THREAD

**Issue by mistaq** [tabalinas/jsgrid#605]
I'd like to add an onclick modal for my Resources text input, as a simple dropdown select would have far too many things to choose from, and with a modal, I'd be able to better use a list with a search filter for selection.

On JSGrid's documents however, there's no notes on how to set up such a thing.

**Comment by tabalinas** [comment]
This kind of functionality is not supported out-of-box. You need to implement it.
Have you already tried?
Please be more specific about the issues you faced.

**Comment by tabalinas** [comment]
No answer, closing
