### ISSUE TITLE
Bootstrap popover on hover

### ISSUE THREAD

**Issue by ravetroll** [tabalinas/jsgrid#606]
I have a grid which has data like an email inbox.  I want the user to be able to hover over a message item in the grid and for a Popover to be displayed on hovering over that line.

I can already access the data i need using this:

```
$("#jsGridInbox").on({
            mouseenter: function () {
                var item = $(this).data("JSGridItem");
                console.log("mouseenter", item);
            },
            mouseleave: function () {
                var item = $(this).data("JSGridItem");
                console.log("mouseleave", item);
            }
        }, "tr");
```

a hover triggered popover can be defined as:

`<a id="popoverData" class="btn" href="#" data-content="Popover with data-trigger" rel="popover" data-placement="bottom" data-original-title="Title" data-trigger="hover">Popover with data-trigger</a>`

I would like to get the popover to have its `data-content` and `data-original-title` populated from fields in the grid.   I want the popover to be based to the line in the grid that is being hovered on.  Could someone point me in the right direction for getting this done?

**Comment by ravetroll** [comment]
Ok, I have answered my own question so I will put the answer here for everyone elses benefit.

The solution lies in customising the rowRenderer.

```
rowRenderer: function(item) {
            var $row = $('<tr>');            

            this._renderCells($row, item);
            
            $row.attr("id", "popover");
            
            $row.attr("data-content", item.Address);
            
            $row.attr("title", item.Name);
            
            return $row;
                },
```

The following javascript will trigger the popover for each row you hover over

`$("tr[id=popover]").popover({placement:"top",trigger:"hover"});`

Here is the fiddle forked from one of @tabalinas 's ones

http://jsfiddle.net/a4xw24h1/

**Comment by ravetroll** [comment]
This works with the supplied static dataset but if I try to extra a dataset from an API then it doesn't work correctly

I think the problem is that there are missing event listeners attached to the tr's (table rows).  Any ideas how I can get those event listeners added after my controller loadData ajax call has returned the data?

**Comment by tabalinas** [comment]
Try to attached your mouse handler (`mouseenter` etc.) in `onRefreshed` callback. Thus handlers will be attached right after row rendering.

**Comment by ravetroll** [comment]
Well done!


`onRefreshed: function () {  $("tr[id=popover]").popover({ placement: "top", trigger: "hover" });}`

**Comment by njelic** [comment]
Hey ravetroll and tabalinas,

Your post help me a lot to solve my problem. But one question for you. I used rowRenderer to select row and to put a class and id in them. Hover works perfect but I need hover effect just when they hover the Address column. Do you have any ideas how can I do that?

**Comment by ravetroll** [comment]
Hi @njelic 

You need to make the popover only respond to the td surrounding the address:

You can do this with row renderer:  See JSFiddle:  http://jsfiddle.net/39sgrd1b/

**Comment by njelic** [comment]
Thank you @ravetroll
