### ISSUE TITLE
Alignment width of cell

### ISSUE THREAD

**Issue by leeyuentuen** [tabalinas/jsgrid#607]
The alignment of the table header is not the same alignment as the table content.
the issue is because the header and content are in different table-tag.

![selection_005](https://cloud.githubusercontent.com/assets/1487966/22422736/41cc9576-e6ee-11e6-9864-e6b975b799c9.png)

**Comment by ravetroll** [comment]
I call a function 

```
renderMyGrid() {

            $("#jsGridMyGrid").jsGrid("render");
        }
```

to fix that.

**Comment by tabalinas** [comment]
Most probably the grid is rendered in a hidden container.

Call `refresh` method to fix the rendering (`$("#jsGridMyGrid").jsGrid("refresh");`). `render` also helps but it's heavier and also triggers data loading if `autobind: true`.

Two separate tables used by design to be able to scroll content of the grid separately.

**Comment by leeyuentuen** [comment]
The problem is not fully solved,
when the email address is longer than, it will resize the other tables after them as you see on the screenshot before.
i'm using the following code:

    ```
$("#jsGrid").jsGrid({

        editing: false,
        sorting: false,
        paging: true,
        width: "100%",
        data: contacts,
        heading: true,

        fields: [
            {name: "function", type: "text", width: "100", title: gtFunction},
            {name: "function_group", type: "select", width: "100", title: gtFunctionGroup, items: functionGroups, textField: "name"},
            {name: "salutation", type: "text", width: "100", title: gtSalutation},
            {name: "surname", type: "text", width: "100", title: gtSurname},
            {name: "name", type: "text", width: "100", validate: "required", title: gtName},
            {name: "phone", type: "text", width: "100", title: gtPhone},
            {name: "email", type: "text", width: "200", title: gtEmail},
            {name: "language", type: "text", width: "50", title: gtLanguage},
            {name: "is_billing", type: "checkbox", width: "20", title: "B", sorting: false},
            {name: "is_commercial", type: "checkbox", width: "20", title: "C", sorting: false},
            {name: "is_technical", type: "checkbox", width: "20", title: "T", sorting: false},
            }
        ]
    });
    renderMyGrid();
```

**Comment by tabalinas** [comment]
@leeyuentuen, please, see if this can help https://github.com/tabalinas/jsgrid/issues/450?

**Comment by leeyuentuen** [comment]
with overflow,
![selection_008](https://cloud.githubusercontent.com/assets/1487966/22472184/25260352-e7d5-11e6-82b6-785187e3ed62.png)

with overflow and word-wrapping
![selection_009](https://cloud.githubusercontent.com/assets/1487966/22472214/3d11fde0-e7d5-11e6-9fdc-9e9f7fbe307c.png)

but still the column doesn't match the same like the header

**Comment by mchl0208** [comment]
@tabalinas I'm getting the same issue when columns are more than 10 ... I really don't know if depends on cells content or columns count. :/
