### ISSUE TITLE
Acces items from fields

### ISSUE THREAD

**Issue by jabiertxof** [tabalinas/jsgrid#608]
Hi there is a posibility to access the items row data on field creation, without using itemTemplate. Only want have the item data accesible like in the name to allow compact definitions of fields and move custom widgets away the data for reuse?

Thanks in advance, Jabier.

**Comment by jabiertxof** [comment]
I finaly fix it by this way:
In custom field create a code  like:
```javascript
xField.prototype = new jsGrid.Field({
autosearch: false,  
url : 'no_url_yet',  
itemTemplateImpl: function(value, item) {},  
itemTemplate: function(value, item) {  
        this.itemTemplateImpl(value, item);  
        return '<a href="'+ this.url+'">Go to other row data stored url</a>';  
    }
}
```
And in the Field definition put:
```javascript
fields: [{ name: "link",
    type: "xfield",
    itemTemplateImpl: function(value, item) {
        this.url = item.url;
    }
]
```

**Comment by tabalinas** [comment]
Glad that you figured it out! Thanks for sharing your solution.

**Comment by jabiertxof** [comment]
You are welcome. Thanks for this cool grid.
