### ISSUE TITLE
New to jsGrid.  Need crud events.

### ISSUE THREAD

**Issue by NewBo1234** [tabalinas/jsgrid#609]
Good afternoon,

I am very new to jsGrid and jQuery in general.  I was trying to figure out how to use the insertItem, updateItem and deleteItem (which appear to be the functions called when the events are fired?).  However, in the "demos", it appears to look for an un-findable db.js file.  

1) Could this please be added in some form or fashion?  It would be very helpful when figuring out how the code works to have all of the files available or at least referenced.

2) Is there a working CRUD example that just does alerts or something?  Right now, I cannot even tell that the events are firing at all.  My database doesn't update, obviously, but my table doesn't update either.  I have the editing and inserting set to true, which puts in the icons to handle the edit (the pencil), the delete (the trashcan), and then at the top a green plus sign (adding).  The only icon that does anything is the trashcan, which deletes it, but the event is whisked away somewhere and all I can do is add a confirmation message.

```js
$("#jsGrid").jsGrid({
     inserting: true,
     editing: true,
     sorting: true,
     paging: true,

     deleteConfirm: function(item) {
           return "You sure?";
     },

     data: formdata,
     
     fields: [ ....... {type: "control", width: 50}]
})
```

My code is basic right now.  The fields show up.  I can (outside of the grid) set up buttons to add and take away rows.  However, I want to use the pencil, the plus and so on--the defaults are wonderful for what I need which is a completely editable table.

How do I add the code to capture the image clicks?  When I click on the pencil, I can edit the row, and then I can click on the green checkbox (again, using the defaults) and nothing happens.

I regret that I'm such a beginner and am having difficulty with such basic things.

Regards.

**Comment by tabalinas** [comment]
The `db.js` is in the repo https://github.com/tabalinas/jsgrid/blob/master/demos/db.js
Feel free to checkout the sources, you will find all the demos source code in `/demos/` directory.

There are samples for different backends available on the website http://js-grid.com/samples/

The question about image click is not clear to me.

**Comment by NewBo1234** [comment]
Good morning,

Thanks for the direct link.

I was having issues that rows were not updating or deleting or anything.  So I was wondering if there was an event that needed to be used to get the jsGrid to update.  Apparently I had a typo or something.  

Now I can update the jsGrid but I need to send an update to the database when someone inserts a row (or deletes a row or updates a row).  So is there an event that I can use to handle that?

Thanks.

**Comment by tabalinas** [comment]
Usually, it needs to send an ajax request to update data. This should be done in the `controller`. Read more in docs http://js-grid.com/docs/#grid-controller
