### ISSUE TITLE
Create a default filter working on static data (provided array)

### ISSUE THREAD

**Issue by maurorulli** [tabalinas/jsgrid#61]
When specified an array for data option (static data) and enabling the filtering feauture should results on a working filter on the data array provided.

**Comment by tabalinas** [comment]
Actual filtering is always done by developer. Option `data` is usually used for static data. So for your case just define grid controller like following:

```javascript
controller: {
    loadData: function(filter) {
        return $.grep(data, function(item) {
            return item.Field === filter.Field // put your conditions here
        }
    }
}
```

**Comment by maurorulli** [comment]
Thanks, it works perfectly with:

controller: {
     loadData: function(filter) {
            return $.grep(myData, function(item) {

             if (filter.Field1.length > 0 && item.Field1
.toLowerCase().search(filter.Field1.toLowerCase()) == -1) return false;
             if (filter.Field2.length > 0 && item.Field2
.toLowerCase().search(filter.Field2.toLowerCase()) == -1) return false;
                       ........
             if (filter.FieldN.length > 0 && item.FieldN
.toLowerCase().search(filter.FieldN.toLowerCase()) == -1) return false;

             return true;
            });
        }
    }

Thanks a lot for the immediate reply,

Mauro Rulli.



Il giorno lun 13 lug 2015 alle ore 15:47 Artem Tabalin <
notifications@github.com> ha scritto:

**Comment by tabalinas** [comment]
You are welcome!

**Comment by maurorulli** [comment]
Excuse me Artem Tabalin,

I'm trying the select field.

I changed:
{ name: "Field1", type: "text", title: "Cl. Mer." },
to:
{ name: "Field1", type: "select", items:["", "FB", "FC"], title: "Cl. Mer."
},

The grid header changed as expected, but the values in the coumun grid
disappeared. Do I need a custom renderer?
Thanks in advance for your patience.

Il giorno lun 13 lug 2015 alle ore 16:50 Artem Tabalin <
notifications@github.com> ha scritto:

**Comment by tabalinas** [comment]
Here is the docs about select field http://js-grid.com/docs/#select
> If valueField is not defined, then the item index is used instead.

Thus, in your case Field1 should have values like 0, 1 or 2.
If you wish to use strings as values provide items as plain objects { value: "", text: "" } and define valueField: "value" and textField: "text".

**Comment by maurorulli** [comment]
It works perfectly, I missed that info in docs.
Thanks.

Il giorno lun 13 lug 2015 alle ore 19:28 Artem Tabalin <
notifications@github.com> ha scritto:
