### ISSUE TITLE
Need to be in document ready?

### ISSUE THREAD

**Issue by NewBo1234** [tabalinas/jsgrid#611]
Just a quick question from a newbie.

I have the jsGrid command in the plain script node, but it doesn't render unless put it in the `$(document).ready(function() {...} );` stuff.

```html
<script>
     //.... here doesn't work

     $(document).ready(function() {
           //.....here it works
     });
</script>
```

Is this supposed to work in the `<script></script>` tags or only in the document ready?

Thank you.

**Comment by tabalinas** [comment]
I guess, it doesn't work without `$(document).ready` because you linked the script to js-grid after the grid creation. Put js-grid script link before the initialization code, this should help.

**Comment by NewBo1234** [comment]
I'm sorry.  I am a very new beginner to this and don't understand.  Are you talking about putting the code below the created <div id="jsGrid"> ?  This is a Thymeleaf rendered page on a separate computer, so I do appreciate explicit examples.

**Comment by NewBo1234** [comment]
OK....  I fiddled with it, and it appears to work when the script tags are after the div tags.  Is this what you mean?
