### ISSUE TITLE
Question:  Need to update last row in grid after ajax update call

### ISSUE THREAD

**Issue by NewBo1234** [tabalinas/jsgrid#613]
Good morning,

Love jsGrid.  It's awesome.

I have a grid that I'm doing basic CRUD on, but the supporting table has an autonumber column.  I obviously need those values, but I cannot (with accuracy) get them until I've done the update.  Unfortunately, this means that I send an insert with everything but the autonumber filled in, I get the autonumber back.  So, I end up with entries without a value filled in.

How can I update that new row with the returned value?  Right now it's just blank.
Winona

**Comment by tabalinas** [comment]
The inserting ajax call should return inserted item in the response (with id field specified).
Return from `controller.insertItem` a promise which will be resolved with this new item. If nothing is returned from `controller.insertItem` then grid renders a row for initial item, but if inserted item is returned then according row will be rendered instead.
