### ISSUE TITLE
How do I navigate to a new page on clicking the respective row, using "rowClick" function

### ISSUE THREAD

**Issue by sdarshanam** [tabalinas/jsgrid#616]
I have a grid that populates one set of data, on clicking any of the row, want to navigate to a new page that uses the row item details and shows more information, how can this be possible ?

**Comment by ravetroll** [comment]
something like this:

```
rowClick: function (args) {
                        selectedItem = args.item;
                        window.location = "/mycontroller/myAction?Id=" + selectedItem.Id;
                    },
```

**Comment by tabalinas** [comment]
@ravetroll, thank you for the answer!
