### ISSUE TITLE
Make Filtering Not Case-Sensitive

### ISSUE THREAD

**Issue by robmoore77** [tabalinas/jsgrid#62]

**Comment by tabalinas** [comment]
All filtering should be done by developer either on client or server side (or both). See following answer https://github.com/tabalinas/jsgrid/issues/61

**Comment by robmoore77** [comment]
Thank you! - issue #61 was very helpful.

**Comment by tabalinas** [comment]
You are always welcome!

**Comment by mahendaraReddy** [comment]
Hi tabalinas 
    for case in-sensitive search i written like this.      
 loadData: function(filter) {    	
	    return $.grep(this.items, function(items) {					       
            return (items.customername.toLowerCase().indexOf(filter.customername.toLowerCase()) > -1);
		 });
       },

 is there any effects with this code.

**Comment by tabalinas** [comment]
Hi mahendaraReddy,

What do you mean by "any effects"? 
Does your solution work fine?

**Comment by mahendaraReddy** [comment]
yes its working fine but if any field is empty filter not working, even if it is case sensitive.

**Comment by tabalinas** [comment]
Looks like not a big problem, just consider empty filter value in the $.grep

```js
loadData: function(filter) {       
	return $.grep(this.items, function(items) {                        
	    return !filter.customername || 
                (items.customername.toLowerCase().indexOf(filter.customername.toLowerCase()) > -1);
	});
},
```
