### ISSUE TITLE
Dynamic population of Jsgrid fields

### ISSUE THREAD

**Issue by jcmurdock2** [tabalinas/jsgrid#625]
I would to create new fields that come from a json file. The only way I can find to make fields is to hardcode them in like the demos: 

```js
 fields: [
            { name: "Account", width: 150, align: "center" },
            { name: "Name", type: "text" },
            { name: "RegisterDate", type: "myDateField", width: 100, align: "center" },
            { type: "control", editButton: false, modeSwitchButton: false }
        ]  
.....
```

Could I set fields to a var or an object that contains the field i want?  Any guidance would be great.

Jqgrid has this funtionality: [http://stackoverflow.com/questions/3867459/dynamic-population-of-jqgrid-colmodel-and-data](url)

**Comment by richraid21** [comment]
Yes, you can assign fields to any object. Just make sure it has the minimum required properties.

**Comment by jcmurdock2** [comment]
@richraid21  could you show me an example?

**Comment by kdydesign** [comment]
Yes, you can create a new field module by referring to jsgrid.field and jsgrid.field.text.

An example of creating an sample(jsgrid.field.sample.js) module ..
```javascript
(function (jsGrid, $, undefined) {
   var Field = jsgrid.Field;

   //your constructor
   function [Constructor](grid, config) {
      Field.call(this, config)
      ...
   }

   //module prototype
   [ModuleName].prototype = new Field({
      _sampleFunction: function() {
            ...
      }
      ...
   });

   jsGrid.field.[ModuleName] = [Constructor];
}(jsGrid, jQuery));
```

**Comment by tabalinas** [comment]
@jcmurdock2, I'm not sure what kind of example you are requesting, it all depends on the use case.
From the description it sounds like it needs to define an array for fields and push items in it based on the data coming from the server. Then you initiate the grid proving this array in the config field `fields: yourFieldsArray`.
