### ISSUE TITLE
[QUESTION] How to set field property to another field

### ISSUE THREAD

**Issue by Entrio** [tabalinas/jsgrid#626]
Hi, how would I go about setting my custom property in custom field type to another field or data from the controller?

**Comment by tabalinas** [comment]
Not sure the use case is clear.
You can always set a field property with [fieldOption](http://js-grid.com/docs/#fieldoptionfieldnamefieldindex-optionname-optionvalue) method even for custom properties. 

If this is not what you are looking for, please, provide more details about the use case,

**Comment by Entrio** [comment]
Hi, thanks for your reply.

Here I set the fields

fields:     [
                {name: "id", title: "ID", type: "number", width: 20},
                {name: "agentTransactionId", title: "ID Агента", type: "number"},
                {name: "agent", title: "Агент", type: "number"},
                {name: "amount", title: "Сумма", type: "balance", transactionType: "isTopup"},
                {name: "agentTransactionTime", title: "Дата", type: "date"}
            ]

I have a custom field "balance" which has customer property transactionType. I need to set this property to value which is called "isTopup" and is passed along with other values.

Thank you

**Comment by tabalinas** [comment]
The field configuration is for entire column, not for a particular row. So you can set this property in the configuration like above or with `fieldOption` method afterwards. Normally custom configuration property of a field would be then used by templates (like `itemTemplate`).
What is the intent of this `transactionType` property?
If I understand the description correctly, trying to set a field property for each data item doesn't make sense in the way it works.

**Comment by Entrio** [comment]
I am displaying transaction type, it can either be balance topup or balance removal. If it is removal, I need to display a "-" before the sum, otherwise display "+"

**Comment by tabalinas** [comment]
Ok, seems like you can handle it with `itemTemplate`:

```js
itemTemplate: function(value, item) {
    // render value depending on item.isTopup or any other property
    return (item.isTopup ? "+" : "-") + value;
}
```

**Comment by Entrio** [comment]
Thank you so much, that did the trick!

**Comment by tabalinas** [comment]
You are welcome!

**Comment by FardinAhsan** [comment]
@tabalinas Thank you so much. You given trick is working fine.
