### ISSUE TITLE
which event method we have to use to filter the data when page loaded first time

### ISSUE THREAD

**Issue by vijaymagentone** [tabalinas/jsgrid#627]
i have static content data array.my grid has filtering enabled and created my custom filtering method.that is working fine.But when grid loaded first time it should not show the all data.it has to filter data with custom condition and return data to grid .this has to happen when page is loading first time

**Comment by tabalinas** [comment]
define this logic in the `controller.loadData` method. Once `autobind: true`, the `loadData` will be called and returns expected data.
