### ISSUE TITLE
can i use two arrays in data

### ISSUE THREAD

**Issue by vijaymagentone** [tabalinas/jsgrid#628]
i have static  json array called clients.so if we put data:clients in jsgrid syntax it renders the table.when the page loaded first time i have to display some filtered content of that static json array.that's is what i have to achieve in my js grid.please help if you have any idea.i have created filtering function on searching.it's working.but that filtering should be called when page loading first time

**Comment by richraid21** [comment]
Please provide more information

**Comment by vijaymagentone** [comment]
i have given description please check once

**Comment by tabalinas** [comment]
@vijaymagentone, there is no point in filing the same issue twice.
https://github.com/tabalinas/jsgrid/issues/627
