### ISSUE TITLE
Contents of columns alternate between left and right align

### ISSUE THREAD

**Issue by baresw** [tabalinas/jsgrid#629]
The JSGrid contents display so that the contents of each column alternates between left and right align.

For example, there are two columns A and B.  Column A contains integers.  Column B contains strings.

A.......B
1.......apple                (first row exhibits left align)
.......2........grape         (second row exhibits right align).
This pattern repeats for all other rows.  
Both integer and string column contents show this same issue.

I tried initializing the grid using all possible align options of "left", "right", "center", and ""
$(document).ready(function() {
  $("#IdJsGridScriptEditor").jsGrid({
	width: "100%",
        align: "left",

Any suggestions would be appreciated.  thanks, Will.

**Comment by richraid21** [comment]
align is a field property, not a JsGrid object property. I'm unable to reproduce your issue. Could you take a look [here](https://codepen.io/richraid21/pen/PWxabe) and see if you could recreate it?

**Comment by baresw** [comment]
Thank you for the clarification on using the align property.  The columns correctly displayed after I updated the file jsGrid/css/theme.css to the version included in the current distribution.
