### ISSUE TITLE
Set visibility of multiple columns at once

### ISSUE THREAD

**Issue by Azkel** [tabalinas/jsgrid#632]
Hi, 

I'm trying to hide/show multiple columns at once,  but after every column visibility change,  grids gets rendered,  which makes performance an issue for me. 

Is there some way to update multiple columns at once, or stop grid from rerendering until the end of setting visibility for all columns?

**Comment by Azkel** [comment]
Figured it out by myself - note for people having this same kind of issue in a future.

Each call to fieldOption calls a method to once again render a grid, so the easiest way was to change each field as wanted by getting it by `jsGrid.fields`, and after setting each column as wanted calling `$('#jsGrid').jsGrid("render")`. Thanks to that grid is rendered only once, but with all desired columns visible.

**Comment by tabalinas** [comment]
Glad that you figured it out!
Thanks for sharing the solution!
