### ISSUE TITLE
Need to add type dynamically into the jsgrid column after ajax sucess in ADD case

### ISSUE THREAD

**Issue by dhawkKD** [tabalinas/jsgrid#633]
![image](https://cloud.githubusercontent.com/assets/17156312/22926346/38bfd5ac-f2d2-11e6-9721-63e77e00ae1a.png)

By referring upper image ...in the add if "Asset#" is ok than i need to make other fields(country,status etc.) as editable.
(means read only get removed and become editable)

In my case ,firstly i removed the type from each column except "Asset#" from the Jsgrid,than when we enter a value in "Asset#" and click on "+" sign than it go into the server side code.From there it return true and false,if true than i need to make other fields like country ,status etc as editable.

I need help that how we make it editable in this case.

**Comment by tabalinas** [comment]
Readonly is not per row property, but for the entire row, and it's not possible to define a field readonly for some row and non-readonly for others. But if you are talking about adding only single row, then you can always change the type of the field with [fieldOption](http://js-grid.com/docs/#fieldoptionfieldnamefieldindex-optionname-optionvalue) method.

**Comment by richraid21** [comment]
A better usability method would be to create a modal/model form that the user fills in which validates the Asset#, then allows you to add the other fields like Status, ClientID etc. Once you have all that, you can use the JSGrid API to add the row with data dynamically.

Doing it this way ensures that you know any row in the grid is valid and you don't need to change read-only properties on the fly.
