### ISSUE TITLE
Allow add new row with enter keypress

### ISSUE THREAD

**Issue by hubdotcom** [tabalinas/jsgrid#637]
Make it more seamless, something like

```
$(".jsgrid-table").on("keyup", ".jsgrid-insert-row input", function(e) {
    if (e.which == 13) {
        $('.jsgrid-insert-button').click();
    }
});
```

**Comment by tabalinas** [comment]
Thank you for the suggestion, but I'm not sure about doing it out-of-box. This kind of behavior usually depends on requirements. In the end, as you said, it can be quite easily implemented on top.
