### ISSUE TITLE
Add new entries to top of table instead of bottom

### ISSUE THREAD

**Issue by hubdotcom** [tabalinas/jsgrid#638]
The user cannot see the entry has been added once there are several items. Adding to the top would be a better experience. At least a feature switch could be added to do this.

addTop: true

**Comment by hubdotcom** [comment]
ref: https://github.com/tabalinas/jsgrid/issues/398

**Comment by tabalinas** [comment]
Thank you for the suggestion

**Comment by richraid21** [comment]
This configuration option might be better as a string parameter:     

`insertedRowLocation: "bottom"|"top"`     

This would allow more freedom in the future for different placement options, rather than limiting the user to a binary choice.

**Comment by tabalinas** [comment]
@richraid21, yes, good proposal.

**Comment by richraid21** [comment]
[Something like this would probably work](https://github.com/richraid21/jsgrid/blob/add-new-row-placement-config/src/jsgrid.load-strategies.js#L56). I didn't write tests or anything yet, just playing around with it. [Row placement defaults to the bottom but can be configured to insert at the top](https://github.com/richraid21/jsgrid/blob/add-new-row-placement-config/src/jsgrid.core.js#L1128).

**Comment by kunalkankariya** [comment]
@richraid21 This doesn't seem to work when using the jsgrid CDN
