### ISSUE TITLE
Sorting, dates, itemTemplate

### ISSUE THREAD

**Issue by Junglefish** [tabalinas/jsgrid#641]
Hi

I’m using data from a JSON feed to populate a grid.
The date fields come back in this format: “December, 17 2014 00:00:00”
If I feed that date string into one of the grid fields like below the column is sortable:

fields: [
    { name: "VOTE_VOTEDATE", title: "Date1", type: "date"},
    . . .
]

However, I want to format the date so instead I convert the field to an itemTemplate, like this:

fields: [
    { 
    	itemTemplate: function(value, item) {
    		dtDate = new Date(item.VOTE_VOTEDATE);
    		return $.format.date(dtDate, "dd MMMM yyyy");
    	} 
    	, title: "Date3"
    	, type: "date"
    }
    . . .
]

Now the date is nicely formatted but the column is no longer sortable.

How do I get the second version to sort?

**Comment by richraid21** [comment]
Just a note, JsGrid doesn't have a built in field type of "date", so you may want to implement that if you expect to be working with dates. 

However, you can add a sorter function directly to the field definition: 
`fields[
{
name: "myDate",
title: "Birthday",
type: "text",
sorter: function(d1, d2) {
                var date1 = new Date(d1).getTime();
                var date2 = new Date(d2).getTime();
                return (date1>date2)-(date1<date2);
              }
}
]`     

Please see [this codepen](https://codepen.io/richraid21/pen/EZqZQM) for a working example.

**Comment by Junglefish** [comment]
Hi RichRaid

Thanks for the help. My final field therefore looks like this, and it now sorts correctly:

{ 
	name: "VOTE_VOTEDATE", 
  	title: "Date", 
  	type: "text",
  	align: "right",
  	itemTemplate: function(value, item) { 
    	dtDate = new Date(item.VOTE_VOTEDATE);
    	return $.format.date(dtDate, "dd MMMM yyyy");
  	},
 	sorter: function(d1, d2) {
    	var date1 = new Date(d1).getTime();
    	var date2 = new Date(d2).getTime();
    	return (date1>date2)-(date1<date2);
  	}
}, 

Just one more small problem. By adding the 'align' property, the content now aligns right, which is cool. However, the column header now aligns in the center (previously it was on the left). How do I get it to also align on the right?

**Comment by richraid21** [comment]
@Junglefish That actually seems like intended behavior from a code standpoint. [The theme.css](https://github.com/tabalinas/jsgrid/blob/master/css/theme.css#L32) ensures that the headers of the table always remains centered. Maybe @tabalinas could explain if this is intentional or or not? 

As a quick fix, you could custom css to the field for the header: 
```
{
      headercss: "force-right",
}
```
then use a rule to force it:
```
tr.jsgrid-header-row th.force-right {
  text-align: right;
}
```

**Comment by Junglefish** [comment]
Hi RichRaid

That's a perfect solution, and also helps me to understand a bit more the way jsGrid can be configured.

Thanks again.

**Comment by tabalinas** [comment]
@richraid21, yes centered headers is the default js-grid theme, but it doesn't mean that it cannot be changed. This is css rules that can be overridden according to particular UI design requirements.
