### ISSUE TITLE
row number in grid

### ISSUE THREAD

**Issue by mohammdr** [tabalinas/jsgrid#643]
Hi expert
How can I add row number to JS-Grid just like jqgrid?
in one of my projects I need this functionality.
thanks.

**Comment by xuanxoo** [comment]
You just have to indicate the field type to number: type: "number"

**Comment by mohammdr** [comment]
Hi xuanxoo
I mean index row; not type of number. like this image : https://i.stack.imgur.com/05beP.png

**Comment by maurorulli** [comment]
RowRenderer has a RowIndex param. You could try to use it as row-num.

**Comment by xuanxoo** [comment]
yep, you can try something like this :  
rowRenderer: function (item, itemIndex) {
                return $("<tr>").append("<td>").append(itemIndex);
}

**Comment by tabalinas** [comment]
@mohammdr, please, checkout the following issue https://github.com/tabalinas/jsgrid/issues/430.

**Comment by inalpolat** [comment]
Have a global variable ie rowNum :
    var rowNum = 0;
....
...

Then when initializing table add a field :

fields: [
                {
                    title: "#", type: "number", itemTemplate: function (value, item) {
                        rowNum += 1;
                        return rowNum;
                    }
                }, ......
            
Finally, reset this variable on each refresh (like sorting etc)
            onRefreshed: function (args) {
                rowNum = 0;
