### ISSUE TITLE
How can I get the row value before editing in js-GRID

### ISSUE THREAD

**Issue by Theriodis** [tabalinas/jsgrid#644]
In js-GRID I want during editing a row(editTemplate):

1.To get the initial value of this row and.
2.To get the edited value. 

The specific js-GRID column is a text field.

But I can't get the **initial** value. Only the edited.

This i my code:

					```
					editTemplate: function() {
						
					//Access the current text field
					var variableGroupEditResult = jsGrid.fields.text.prototype.editTemplate.call(this);
					
					//alert(variableGroupEditResult.val());
					
					//When the value of this textfield is changed pass it to the Process Variables grid
					variableGroupEditResult.on("change", function() {
					
					//Get the value of this text field
					var selectedEditValue = variableGroupEditResult.val();
					
					//alert(selectedEditValue);

					});
					
					return variableGroupEditResult;
					},
```

**Comment by maurorulli** [comment]
Not sure if can help, but onItemUpdating callback provides the previousItem too.

**Comment by Theriodis** [comment]
I didn't find the solution so far.  @tabalinas  Any idea please?

**Comment by maurorulli** [comment]
RowRenderer has a RowIndex param. You could try to use it as row-num.

**Comment by Theriodis** [comment]
Yes Yes Yes @maurorulli !! 

onItemUpdating  worked!

1) I added the code:
onItemUpdating: function(args) { previousValue = args.previousValue;
						 }
2)And apart from that I passed the previousValue to my editTemplate and it is done.
