### ISSUE TITLE
rowRenderer always cause error

### ISSUE THREAD

**Issue by xuanxoo** [tabalinas/jsgrid#645]
When I delcare the rowRenderer event on a jsgrid it causes this error and grid is not loading
![jsgriderror](https://cloud.githubusercontent.com/assets/13761014/23211225/53cb6764-f901-11e6-97fd-b0fd8fdf9812.PNG)
.

**Comment by maurorulli** [comment]
From the Documentation:
The function should return markup as a string, jQueryElement or DomNode representing table row TR

**Comment by xuanxoo** [comment]
thanks @maurorulli  ¿what about cellRenderer? It is not causing error but never is launched.
