### ISSUE TITLE
how to check which mouse button is click on RowClicked event   of grid view  row ,by default you can click only with left button of mouse 

### ISSUE THREAD

**Issue by yogesh2591** [tabalinas/jsgrid#647]
On rowClick event only fire on mouse left Click.How To check Other Click

```
rowClick: function (args) {
                    var event = args.event;
                    switch (event.which)
                    {
                        case 1:
                            alert('Left Mouse button pressed.');
                            break;
                        case 2:
                            alert('Middle Mouse button pressed.');
                            break;
                        case 3:
                            alert('Right Mouse button pressed.');
                            break;
                        default:
                            alert('You have a strange Mouse!');
                    }

                    }
```

**Comment by richraid21** [comment]
Please provide more information.

**Comment by tabalinas** [comment]
@yogesh2591, `args.event` provides access to the native browser click event. The problem is `click` event is not fired on right mouse click. You most probably need `contextmenu` event or just check mouse button on `mousedown` event (this SO question might be useful http://stackoverflow.com/questions/2405771/is-right-click-a-javascript-event)

**Comment by yogesh2591** [comment]
thanks @tabalinas

**Comment by yogesh2591** [comment]
@tabalinas i tried every thing but it didn't work.the context menu can be clicked out side the grid but on jsgrid-row and it not worked

**Comment by maurorulli** [comment]
Can you provide a jsFiddle sample?

**Comment by yogesh2591** [comment]
I figured out what to do:
**Changing code in jsgrid.js From this**
`        .on("click", $.proxy(function (e) {
          this.rowClick({
          item: item,
          itemIndex: itemIndex,
          event: e
          });
          }, this))`


**To**
```
 .on("mousedown", $.proxy(function (e) {
                    this.rowClick({
                        item: item,
                        itemIndex: itemIndex,
                        event: e
                    });
                }, this));

```
now i got every click of mouse
