### ISSUE TITLE
Deleting option missing

### ISSUE THREAD

**Issue by maurorulli** [tabalinas/jsgrid#649]
I've **inserting** option to allow inserting rows. I've **editing** option to allow editing rows. But I miss a **deleting** option to allow or not deleting rows. I need it for an "only-edit" grid, how can I disable/hide the trash icon?

I just noticed that setting **editing** to false doesn't hide the edit icon as I expected.

**Comment by Theriodis** [comment]
We have 2 problems which looks similar @maurorulli . I can't find a  function similar to insertTemplate and editTemplate for deleting rows.

**Comment by tabalinas** [comment]
@maurorulli, edit and delete icons defined by `control` field. They has nothing to do with the grid itself. And `control` field has `editButton` and `deleteButton` (http://js-grid.com/docs/#control) which allow to hide buttons if needed.

@Theriodis, do you mean `deleteTemplate`? Not sure I can imagine how it would look like.

**Comment by Theriodis** [comment]
@tabalinas  exactly! I mean `deleteTemplate`. Does is exist?  For example when I delete a row I want to keep the previous value of this field (like in my already implemented insertTemplate and editTemplate) and perform some checks(Please check my issue #650 ). How will I do it inside my main.js file? With which function or event or anything?

Thanks
