### ISSUE TITLE
Saving edits

### ISSUE THREAD

**Issue by andyjhall** [tabalinas/jsgrid#65]
Is there a way to have edits saved if you click to edit another item? or if you press enter within the edit box?

**Comment by tabalinas** [comment]
Well, currently there is no such a functionality out-of-box. 
But you can achieve it redefining `editItem` method, something like the following:

```javascript
var baseEditItem = jsGrid.prototype.editItem;

jsGrid.prototype.editItem = function() {
    if(this._editingRow) {
	this.updateItem();
    }
    baseEditItem.apply(this, arguments);
};
```

**Comment by andyjhall** [comment]
This just seems to return 'Unable to get property 'editItem' of undefined or null reference', no previous experience of overriding methods so not sure exactly how to use this code. Any help appreciated.

**Comment by tabalinas** [comment]
Sorry, made a mistake in code. Corrected the sample above.
See working fiddle http://jsfiddle.net/tabalinas/rkxbgzrx/

**Comment by andyjhall** [comment]
That makes much more sense, thanks!
