### ISSUE TITLE
Filtering on readOnly columns

### ISSUE THREAD

**Issue by vcaraulean** [tabalinas/jsgrid#652]
We're displaying many columns but only few of them should be editable.

As suggested in #91, we're not setting the "type" and column is marked as "readOnly". But this is also disabling filtering by those columns.

Is there a way to make readOnly columns filter-able? I'm looking into messing with `filterRowRenderer` but may be there's an easier approach?

**Comment by richraid21** [comment]
You are not getting a filter box because the default Field implementation's filterTemplate method doesn't return anything. 

I would strongly suggest you create a custom field type for your needs. This would cover both of your requirements: editTemplate should be the same as itemTemplate, for read only behavior, but you can create a filterTemplate that does what you want.

**Comment by vcaraulean** [comment]
Thanks, @richraid21 for suggestion. Ended up with a custom column. Not the prettiest way (you have to do it for all your column types) but it works.

But will really appreciate an easier way to filter on read-only columns.

**Comment by richraid21** [comment]
@vcaraulean you might be able to overwrite the default field filter Template instead. I haven't looked into it.

**Comment by tabalinas** [comment]
@vcaraulean, have you tried to set `editing: false` for you read only field? I guess, this is exactly what you expect.

@richraid21, not sure I understand what you mean by "fields should be able to be marked as read only individually, rather than the whole grid though", like readonly per row?

**Comment by J-Setzer** [comment]
I was facing the same problem, and as @tabalinas has written a while ago:
Setting the field's `editing: false` and `readOnly: true` disabled editing and re-enabled filtering . 
Perfect, thanks!

**Comment by djdance** [comment]
Tested correction: set only field's **editing: false**,  no need to set readOnly, and of course not readOnly:true
