### ISSUE TITLE
how to insert row dynamically on control Click

### ISSUE THREAD

**Issue by yogesh2591** [tabalinas/jsgrid#654]
here is my grid view (**Please see Attach Image for reference**), i want to insert row on Click of Green square (**1st Column(it is a control column)**)of selected row .the new row should be inserted below clicked row, where should i write the insertion code.   
![new bitmap image](https://cloud.githubusercontent.com/assets/16665704/23328689/4a3f551c-fb4e-11e6-8063-790c4e801aa4.png)

**Comment by richraid21** [comment]
This is not a trivial matter.

The insertRow creation happens inside of the _createHeader function and is rendered but hidden on the grid view. You would have to override the _createHeader function to remove the insertRow, then somehow bootstrap the insertRow creation inside of your click event.

**Comment by tabalinas** [comment]
@richraid21, I guess `insertItem` method should do the trick. The only tricky part is appending below current item, here the best choise, I guess, is to reload loading strategy `finishInsert`.
