### ISSUE TITLE
Data-attributes to row

### ISSUE THREAD

**Issue by xdefrag** [tabalinas/jsgrid#656]
Is there any possibility to set data-attributes to row?

I have:
````
<tr class="jsgrid-row jsgrid-selected-row">
````
And i need something like:
````
<tr class="jsgrid-row jsgrid-selected-row" data-id="1" data-type="contact">
````

**Comment by richraid21** [comment]
No, that is not available in the library right now. 

You will need to provide a custom rowRenderer function for the grid object.

**Comment by xdefrag** [comment]
@richraid21 you save my day! Thank you.

**Comment by tabalinas** [comment]
One way to do it is described in this issue https://github.com/tabalinas/jsgrid/issues/479
