### ISSUE TITLE
Multiple dynamic filters "select"

### ISSUE THREAD

**Issue by rmsalazar** [tabalinas/jsgrid#659]
Hello

**after all, Thank you for given us such a great tool**

I have a grid with some data, this data have 4 specific values in each row, example:

> id: "name1", desc: "description", family: "aa", line: "aaa1", platform: "aaa1a001", group: "aaa1a001g001"

_(This is not json, its just an example of my data)_

what i need to do is this:

1. family,line, platform and group must be a select filter
2. line is a child of family, platform is a direct child of line, and group is a direct child of platform.
3. when i select one family, the filter of line must change  and display only lines with the selected family, and the same with platform and group, when i select line, only platform and group must change, and this must have the selected family and line, and when i change platform, only group must update with the selected family, line and platform...
4. when i said "update", i mean the content of the select of each filter and the data itself

i already try this(modifyin the select element directly of each filter), but when i select a different family, the filter object doesnt clean the line, platform and group filter (i put a message on the loadData option)
And i cant fine a "clearfiltercolumn" option or something.

**i hope you understand me, and ill appreciate your time.**

**Comment by tabalinas** [comment]
Have you checked the following issue https://github.com/tabalinas/jsgrid/issues/106?

**Comment by rmsalazar** [comment]
**thank you!**

that was what i need.

**Comment by tabalinas** [comment]
you are welcome!

**Comment by rmsalazar** [comment]
Hey, guess what, your example ( http://jsfiddle.net/tabalinas/n982uvx1/ ) is not working correctly, and I actually recreate your example in my project but i face the same issue, when the loadData function triggers, the filter json doesnt have the actual filters dynamicaly created.

for example:

with 3 select, i change the first filter (for example continent, i select America), then i change the second filter (for example countries, i select Peru) then i select Lima, the JSon filter is like this:

`{ filter1:"", Filter2:"", Continent:"America", Country:"Peru", City:"Lima" }`

now, if I change the filter Continent, my filters country and city, dinamically change and moves to the empty option (default option), but if y console log the filter JSon when the loadData functions triggers, the object look like this:

`{ filter1:"", Filter2:"", Continent:"Asia", Country:"Peru", City:"Lima" }`

instead of:

`{ filter1:"", Filter2:"", Continent:"Asia", Country:"", City:"" }`

I've seen this issue first with my custom "on change" event made with JQuery, and now even with the filtertemplate option that you suggest me.

**The real problem is that the thing that fires the filter function, doesnt have the current filters, and i dont know why**
