### ISSUE TITLE
Time picker in jsgrid

### ISSUE THREAD

**Issue by priyarathi** [tabalinas/jsgrid#660]
Hi,

Do we have any example with time picker column in JS Grid?

My requirement is I need two separate columns in jsGrid - One for date field and one for time picker. I could get the date using myDateField. Having trouble with time field.

Thanks,
Priya

**Comment by richraid21** [comment]
You could create a custom field type that uses the new HTML5 input type of datetime-local and split the result in your logic. Other than that, you will need to use some type of UI library or UI element.

**Comment by tabalinas** [comment]
In this example you can find bootstrap datetimepicker https://jsfiddle.net/ytv8prjo/
You could use something similar, or probably it supports time only mode, so you could have a separate column for it.

The original issue https://github.com/tabalinas/jsgrid/issues/571

**Comment by priyarathi** [comment]
Thank you so much for the solution richraid21 and tabalinas.

**Comment by GJeeva** [comment]
hi
i want date column and time is separate column in same grid 
how to separate in datetime picker

**Comment by alexisc67** [comment]
Hi, in the example in jsfiddle you need to change insertDate to insertValue otherwisw Insert doesn't work. It should look like:

        insertValue: function () {
            var insertValue = this._insertPicker.data('DateTimePicker').date();
            if (typeof insertValue !== 'undefined' && insertValue !== null) {
                return insertValue.format('L');
            } else {
                return null;
            }
        },

**Comment by priyarathi** [comment]
I added MyTimeField like below and used it in timepicker column in jsgrid. Hope this helps!





var MyTimeField = function (config) {
                jsGrid.Field.call(this, config);
            };

            MyTimeField.prototype = new jsGrid.Field({
                sorter: function (date1, date2) {
                    return new Date(date1) - new Date(date2);
                },

                itemTemplate: function (value) {
                    if (value === null) {
                        return '';
                    } else {
                        return value;
                    }
                },

                insertTemplate: function (value) {
                    return this._insertPicker = $("<input>").datetimepicker({
                        format: 'LT'
                    }).attr("title", "Time");
                },

                editTemplate: function (value) {
                    this._editPicker = $('<input>').datetimepicker({
                        format: 'LT'
                    });

                    if (typeof(value) !== 'undefined' && value !== null) {
                        this._editPicker.data('DateTimePicker').date(value);
                    }
                    this._editPicker.attr("title", "Time");
                    return this._editPicker;
                },

                insertValue: function () {
                    var insertValue = this._insertPicker.data('DateTimePicker').date();
                    if (typeof insertValue !== 'undefined' && insertValue !== null) {
                        return insertValue.format('LT');
                    } else {
                        return null;
                    }
                },

                editValue: function () {
                    var editValue = this._editPicker.data('DateTimePicker').date();
                    if (typeof editValue !== 'undefined' && editValue !== null) {
                        return editValue.format('LT');
                    } else {
                        return null;
                    }
                }
            });

            jsGrid.fields.myTimeField = MyTimeField;

And my column looks like below. Ignore the business rule in validator- 

 {
                        name: "StartTime",
                        title: "Start Time",
                        type: "myTimeField",
                        width: 50,
                        css: 'row-segment',
                        validate: {
                            message: function (value, item) {
                                var isValidEntry = true;

                                if (value == '')
                                    isValidEntry = false;
                                else {
                                    var startDate = currentSegmentType == model.MotorPoolSegmentTypes.MultiDay ? new Date(item.StartDate) : getRequestStartDate();
                                    var startDateText = currentSegmentType == model.MotorPoolSegmentTypes.MultiDay ? item.StartDate : getRequestStartDateText();
                                    var test = new Date(startDateText + ' ' + value);
                                    var today = new Date().setHours(0, 0, 0, 0);
                                    if (isNaN(test))
                                        isValidEntry = false;
                                    else if (startDate.setHours(0, 0, 0, 0) == today) {
                                        if (lastTripType == model.EmergencyTripTypeId && test >= new Date())
                                            return "Start Time cannot be in the future.";
                                        else if (lastTripType != model.EmergencyTripTypeId && test <= new Date())
                                            return "Start Time cannot be in the past.";
                                    } 
                                }

                                return !isValidEntry ? "Start Time is required" : null;
                            },
                            validator: function (value, item) {
                                if (value == '')
                                    return false;
                                else {
                                    var startDate = currentSegmentType == model.MotorPoolSegmentTypes.MultiDay ? new Date(item.StartDate) : getRequestStartDate();
                                    var startDateText = currentSegmentType == model.MotorPoolSegmentTypes.MultiDay ? item.StartDate : getRequestStartDateText();
                                    var test = new Date(startDateText + ' ' + value);
                                    var today = new Date().setHours(0, 0, 0, 0);
                                    if (isNaN(test))
                                        return false;
                                    else if (startDate.setHours(0, 0, 0, 0) == today) {
                                        if (lastTripType == model.EmergencyTripTypeId)
                                            return test <= new Date();
                                        else
                                            return test >= new Date();

                                    } else
                                        return true;
                                }
                            }
                        }
                        }
