### ISSUE TITLE
AJAX callback and connecting to CakePHP controller

### ISSUE THREAD

**Issue by mistaq** [tabalinas/jsgrid#665]
In my [previous issue](https://github.com/tabalinas/jsgrid/issues/651), I noted that I was unable to get any of the AJAX callbacks working. This is despite the controller in my script coming straight out of the jsGrid documentation, and only changed to fit with my URLs.

Table wise, I have two tables:

* Resources, which contains the function called `manageinstrument`, which is where the jsGrid is.
* Instruments, which contains functions `index` `add`, `edit`, `delete`, and which is where I want the AJAX callbacks to direct to.

My grid controller, which is part of the jsGrid script, and in the `manageinstrument` View:

```
controller: {
                loadData: function (filter) {
                    $.ajax({
                        type: "GET",
                        url: "localhost/project/instrument/",
                        data: filter
                    });
                },
                insertItem: function (item) {
                    $.ajax({
                        type: "POST",
                        url: "localhost/project/instrument/",
                        data: item
                    });
                },
                updateItem: function (item) {
                    $.ajax({
                        type: "PUT",
                        url: "localhost/project/instrument/",
                        data: item
                    });
                },
                deleteItem: function (item) {
                    $.ajax({
                        type: "DELETE",
                        url: "localhost/project/instrument/",
                        data: item
                    });
                }
            },
```

This is one of my CakePHP Instrument controller functions: the add function (what I want to be called via AJAX when I do an insertItem):

```
public function add()
    {

        $instrument = $this->Instruments->newEntity();
        if ($this->request->is(['post', 'ajax'])) {
            $instrument = $this->Instruments->patchEntity($instrument, $this->request->data);
            if ($this->Instruments->save($instrument)) {
                $this->Flash->success(__('The instrument has been saved.'));

                return $this->redirect(['action' => 'index']);
            } else {
                $this->Flash->error(__('The instrument could not be saved. Please, try again.'));
            }
        }
        $resources = $this->Instruments->Resources->find('all')->toArray();
        $this->set(compact('instrument', 'resources'));
        $this->set('_serialize', ['instrument']);
    }
```

I've already tried to change the URL in the jsGrid controller's insertItem function to match my PHP controller function's name, while also adding datatype: "JSON" as follows:

```
insertItem: function (item) {
                    $.ajax({
                        type: "POST",
                        url: "localhost/project/instrument/add",
                        data: item
                        datatype: "JSON"
                    });
                },
```

I've also tried an approach I used for a modal that used an AJAX callback:

```
insertItem: function (item) {
                    $.ajax("localhost/project/instrument/add.json"{
                        data: item
                    });
                },
```

In all 3 methods, while the jsGrid saves the row of data being inputted, the AJAX callback fails. I did an inspect and checked the source code and the URLs definitely point to the correct Views and I also get no errors in Console. JSON and XML are already implemented, and so I'm just at a loss as to why I can't pass the data to the PHP controller, which would then contact the MySQL database. I know this is affecting all of the AJAX callbacks, as I have one data entry already in the Instruments Controller and that isn't being loaded, and if I Edit a data entry on jsGrid, still nothing changes in the database.

Sorry if it appears like I'm spamming the jsGrid Github - I wasn't sure if I should post this as a comment in the previous issue, or post it as a new issue, given that the previous issue's title related to blank spaces in the jsGrid when adding/editing, which I have since fixed.

**Comment by Oxicode** [comment]
+1

**Comment by richraid21** [comment]
Maybe I'm missing something, but you're not calling any of the callbacks provided by `.ajax`. You need `.success`, `.error` or `.complete` chained to your Ajax call.

**Comment by mistaq** [comment]
@richraid21 Do you mean like this?

```
insertItem: function (item) {
                                        $.ajax({
                                            type: "POST",
                                            url: "localpath/project/instrument/",
                                            data: item,
                                            success: function(data){
                                                successmessage: "Data successfully inserted."
                                            },
                                            error: function(data){
                                                errormessage: "Data could not be inserted."
                                            },
                                            complete: function(data){
                                                completemessage: "Ajax callback completed."
                                            }
                                        });
                                    }
```
After running this, I get nothing in response, so I don't think I'm doing it correctly. `data` in each of the callback function is said to be unused - I thought it would use the data parameter `data: item`.

**Comment by mistaq** [comment]
It seems that using $.post caused the issue of getting http://localhost/project/instrument/manageinstrument/[object%20Object] Failed to load resource: the server responded with a status of 404 (Not Found), however while I've fixed that, I'm still yet to be able to save data to MySQL (that tells me the PHP function isn't actually being called).

**Comment by mistaq** [comment]
Fixed! Well at least InsertItem is fixed. Made a really stupid mistake when I Cake Baked and only rebaked the model, rather than the whole thing (so it was not up to date with the database).

**Comment by tabalinas** [comment]
Glad that you figured it out!
