### ISSUE TITLE
how to use custom filter for grid view??

### ISSUE THREAD

**Issue by yogesh2591** [tabalinas/jsgrid#667]
![new bitmap image](https://cloud.githubusercontent.com/assets/16665704/23748031/ecbb7922-04e7-11e7-8846-0bb8578153cc.png)

here is my grid view i use Custom input for filtering row , i use server side filtering by calling method using ajax and retrieving filter rows . the Problem is my grid view data update after every 15 seconds and filter get cancel. how to save current filter in loadData function

**Comment by maurorulli** [comment]
How do you update your grid view?

**Comment by yogesh2591** [comment]
using loadData and ajax 

```
controller: {
                    loadData: function (filter) {
                        var d = $.Deferred();

                        $.ajax({
                            type: "POST",
                            url: "Default.aspx/get_details",
                            data: "{}",
                            contentType: "application/json; charset=utf-8",
                            dataType: "json"
                        }).done(function (response) {
                            console.log("loaded agian");
                            d.resolve(JSON.parse(response.d));
                        });

                        return d.promise();
                    }
                }
```

and then using ajax call

`setInterval(function () { $("#jsGrid").jsGrid("loadData"); }, 50000);`

**Comment by tabalinas** [comment]
Is your filter coming outside of the grid? Then you can just extend `filter` object with additional filtering parameters in `loadData` function.

**Comment by yogesh2591** [comment]
@tabalinas can you provide sample??

**Comment by yogesh2591** [comment]
@tabalinas can i get help

**Comment by tabalinas** [comment]
By extending I mean usual object extend, so the your `loadData` will look like:

```js
loadData: function (filter) {
    $.extend(filter, {
        myParameter1: "myParameter1Value",
        ...
    });

    // your usual loadData code
}
```

**Comment by yogesh2591** [comment]
@tabalinas  thank you
