### ISSUE TITLE
Grid customization to hide additional information

### ISSUE THREAD

**Issue by bradybray** [tabalinas/jsgrid#668]
Hello;

I have a grid but its a bit too wide for the screen on which it is being displayed. My idea is to hide some of the columns that contain relevant information in another dialog. Perhaps a sort of drop down or popup that will display itself when clicked and show this additional information. Does jsGrid have functionality to support this? Or is there an easier way?

~Braden.

**Comment by tabalinas** [comment]
Each field has an option `visible`. So you can set this options depending on values selected in the dialog.
As for the dialog use any widget available out there (or create your own if you wish). Once changes in the dialog submitted set `visible` option for each field with `fieldOption` method of the grid.
