### ISSUE TITLE
Converting string to integer

### ISSUE THREAD

**Issue by mistaq** [tabalinas/jsgrid#669]
I would like to use insertTemplate to insert an integer into a field, to be used as a foreign key input. However, the foreign key attribute in my table uses Integer, but insertTemplate returns a string.

Example:

Before the `$("#jsGrid").jsGrid({`, I define `id`.

`var id = "<?php echo $id?>";` $id is an id being passed to the View itself. For this example, let's use the integer 5.

In my fields, I have field resource_id as follows:

```
{name: "resource_id", type: "number", width: 150, visible: false,
       insertTemplate: function() {
              var input = this.__proto__.insertTemplate.call(this);
              input.val(parseInt(id))
              return input;
       }
}
```

Thus whenever I add a new row to the jsGrid, `resource_id` is set to string value = 5. However because of the mismatch in data types (string vs. int), it can't be saved. I know of the parseInt JavaScript function, but I'm unsure as to where it should go, be it the controller where the AJAX occurs, inside insertTemplate, or in the field itself.

**Comment by maurorulli** [comment]
`var id = "<?php echo $id?>";`

What happens if you remove the double quotes?

**Comment by tabalinas** [comment]
Are you sure you need this `resource_id` in the grid?
I would suggest adding it before sending to the server inside `controller.insertItem`.
Let me know if it works.

**Comment by tabalinas** [comment]
No answer. Closing.

**Comment by mistaq** [comment]
Sorry for not responding; my users ended up wanting a different system that no longer required the use of jsGrid.
