### ISSUE TITLE
Custom Field Type: Colorpicker

### ISSUE THREAD

**Issue by Cocotus** [tabalinas/jsgrid#67]
Hi,
I spend this sunday checking out datagrid solution and I have to say its exactly the thing I will use in my webproject. I played around trying to display/load my data and it works great, thank you! I have one question: I tried to build up a color/colorpicker-type column using your example here: http://js-grid.com/docs/#custom-field but I can't get it work :(  . The goal ist to display color values (i.e. "black", hex strings like #FF2E3785 for user in that column. Is this possible, or any example I can look at?

**Comment by tabalinas** [comment]
Hi,

Thank you for the feedback!
What color picker widget do you use?

**Comment by tabalinas** [comment]
Here is the sample with the [spectrum](https://github.com/bgrins/spectrum): colorpicker. http://jsfiddle.net/tabalinas/8thcpey4/

It's a little tricky since spectrum don't allow to initialize widget on detached element (that's why we need these setTimeouts).

```javascript
var ColorField = function(config) {
    jsGrid.Field.call(this, config);
};

ColorField.prototype = new jsGrid.Field({
    
    itemTemplate: function(value) {
        return $("<div>").css({
            display: "inline-block",
            background: value,
            width: "50px",
            height: "20px"
        });
    },
    
    insertTemplate: function(value) {
        var insertPicker = this._insertPicker = $("<input>").attr("type", "color");
        setTimeout(function() {
            insertPicker.spectrum({
                color: "#fff"
            });
        });
        
        return insertPicker;
    },
    
    editTemplate: function(value) {
        var editPicker = this._editPicker = $("<input>").attr("type", "color");
        setTimeout(function() {
            editPicker.spectrum({
                color: value
            });
        });
        
        return editPicker;
    },
    
    insertValue: function() {
        return this._insertPicker.spectrum("get").toHexString();
    },
    
    editValue: function() {
        return this._editPicker.spectrum("get").toHexString();
    }
    
});

jsGrid.fields.color = ColorField;

```

**Comment by Cocotus** [comment]
Good sir,
I would like to bestow upon you the title of "hero of the Internet" for your last post, as that is simply awesome! :+1:  
Yes Im using spectrum and yes your example looks exactly the way I need it. It works really well and all is perfect except for one minor thing I noticed:

![colorpicker](https://cloud.githubusercontent.com/assets/2303272/8916233/77560c74-34aa-11e5-893b-1d0832903f2a.jpg)

I know that your code works as intended and I will need to look at spectrum gui/options on how to disable that "Choose" button or better how to make it save the color like your button does. But I don't think its complicated will look at it now - Thank you and keep up the great work!

**Comment by tabalinas** [comment]
Thank you! J
The scenario you're talking about is doable: handle choose button click calling `updateItem` grid method directly. Provide the item with changed color as parameters.
But, I guess it may look confusing: user chosen a color and clicks `Cancel` edit, but color saved anyway. Don't you think so?
