### ISSUE TITLE
loadData not working

### ISSUE THREAD

**Issue by nptravi** [tabalinas/jsgrid#671]
I am new to Jquery or jsgrid. I tried to use this plugin. When I use static data with data:[{objects}] I get the grid. But when I try to get data from loadData, No data comes to grid.

Below is my code, please guide me what I am missing.

$("#jsGrid").jsGrid(
	{
		width:"85%",
		height: "70%",
		
		paging: false,
		sorting: false,
		
		autoload: true,
		loadData: function()
		{
			
			return [{"empname":"Vijayan","empno":"E002128"}];
		},
		
		fields:
		[
		{name: "empname", type: "text", width: "150"},
		{name: "empno", type: "text",width:"100"}
		]
	});

Thanks.

**Comment by richraid21** [comment]
`loadData` needs to be within the controller object; it is not a root JsGrid property. 
```
controller: {
       loadData: function(){
                     return //data
       }
}
```

**Comment by nptravi** [comment]
Bingo! It works. Thanks a lot.

**Comment by jaguarxii** [comment]
For some reason I was wrting "autoLoad" instead of "autoload", this make the whole difference between working and not working.
