### ISSUE TITLE
First row of the dataset turn off sort

### ISSUE THREAD

**Issue by rammi987** [tabalinas/jsgrid#676]
Hello,

i have a question of i can do this with your plugin i have this list as below:

id, name, prisindex
1 , hans, 10, 
2 , lars  , 13,
3 , tokil , 14,
4 , bo    , 9

Then i sort prisindex, but i want alwas id 1 to be at the top.

id, name, prisindex - decs
1 , hans, 10, 
4 , bo    , 9
2 , lars  , 13,
3 , tokil , 14,

id, name, prisindex - asc
1 , hans, 10, 
3 , tokil , 14,
2 , lars  , 13,
4 , bo    , 9

This i need for you can sort in all users, but you own accoount need to be at the top at alwasy for compare your own user the top with the sort users below.

**Comment by richraid21** [comment]
I don't think I would recommend this approach. Why don't you display the current account information above the grid? It creates visual separation, results in better usability and would be easier to implement than what you suggest.

**Comment by maurorulli** [comment]
you have to implement your custom sorting strategy.

Check the [DOC](http://js-grid.com/docs/#custom-sorting-strategy)

**Comment by tabalinas** [comment]
@rammi987, yes, this is possible. As @maurorulli advised you need to implement your custom sorting strategy.
