### ISSUE TITLE
Use Arrows up and Down for selectine one row.

### ISSUE THREAD

**Issue by guilhermehrcosta** [tabalinas/jsgrid#677]
How use arrows up and down for selecting one row. I am using an editable field.

http://pastebin.com/zYymX990

**Comment by tabalinas** [comment]
Just as in your example, you have to handle up and down arrows click event. On this event do required actions depending on what you mean by `selecting one row`. Notion of js-grid for selection is just highlighting. So this could be a specific class that you add for styling, or anything else. Also you could track the selected row and start editing it on `Enter` key press for instance.
