### ISSUE TITLE
How can I get insertModeButton, editButton, deleteButton Click Event?

### ISSUE THREAD

**Issue by anne214000** [tabalinas/jsgrid#678]
Couple of questions:

1. How can I get insertModeButton, editButton, deleteButton Click Evnet?
I want to do some actions on insertModeButton, editButton, deleteButton click, not on insertItem, updateItem, deleteItem.  But I can't find Button Click Evnet.
2. How can I let jsgrid Disable?
Thanks a lot

**Comment by maurorulli** [comment]
1. onItemInserting, onItemUpdating, onItemDeleting are fired before the action are done, you can do some actions here.

2. What do you mean by "let jsgrid Disable"?

**Comment by anne214000** [comment]
1. But I want to do some actions when insertModeButton click(when grid inserting row appeared), before I inserting new item, how can I do that?
2. I mean can't touch jsgrid element , maybe I can disable jsgrid's div?
Thanks

**Comment by tabalinas** [comment]
1. If you want to attach handlers to particular buttons of `control` field you have to redefine particular template and attach your handlers. Or just define your own buttons.

```js
{
    type: "control",
    headerTemplate: function() {
        var $result = jsGrid.fields.control.prototype.headerTemplate.call(this);
        $result.on("click", function() { /* your handler */ };
        return $result;
    }
}
```

2. You can checkout this SO answer http://stackoverflow.com/questions/639815/how-to-disable-all-div-content
