### ISSUE TITLE
HOW WE  USE JS GRID IN DYNAMIC JAVA PROJECT IN ECLIPSE

### ISSUE THREAD

**Issue by Venkatramanaryams** [tabalinas/jsgrid#681]
I AM NOT GETTING HOW WE USE JS GRID IN ECLIPSE FOR CREATING A DYNAMIC WEB APPLICATION 
CAN ANYONE PLEASE HEL ME

**Comment by richraid21** [comment]
Please provide more information and format your post accordingly, thanks.

**Comment by tabalinas** [comment]
This issue description is inappropriate. Almost no information. The question is very vague.
Another issue "yelling" with CAPS.

**Comment by Venkatramanaryams** [comment]
<%@ page language="java" contentType="text/html; charset=ISO-8859-1"
	pageEncoding="ISO-8859-1"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1">
<title>jQuery</title>
<link type="text/css" rel="stylesheet"
	href="https://cdnjs.cloudflare.com/ajax/libs/jsgrid/1.5.3/jsgrid.min.css" />
<link type="text/css" rel="stylesheet"
	href="https://cdnjs.cloudflare.com/ajax/libs/jsgrid/1.5.3/jsgrid-theme.min.css" />
<script type="text/javascript"
	src="http://code.jquery.com/jquery-1.9.1.min.js"></script>
<script type="text/javascript"
	src="https://cdnjs.cloudflare.com/ajax/libs/jsgrid/1.5.3/jsgrid.min.js"></script>
<script type="text/javascript"
	src="https://cdnjs.cloudflare.com/ajax/libs/jsgrid/1.5.3/jsgrid.min.css"></script>
<script type="text/javascript"
	src="https://cdnjs.cloudflare.com/ajax/libs/jsgrid/1.5.3/jsgrid.js"></script>
<script type="text/javascript"
	src="https://cdnjs.cloudflare.com/ajax/libs/jsgrid/1.5.3/jsgrid.css"></script>
<script type="text/javascript"
	src="https://cdnjs.cloudflare.com/ajax/libs/jsgrid/1.5.3/jsgrid-theme.min.css"></script>
<script type="text/javascript"
	src="https://cdnjs.cloudflare.com/ajax/libs/jsgrid/1.5.3/jsgrid-theme.css"></script>
<script>
	$(document).ready(function() {
		alert("JS grid Functionality #Welcomes U");
	});
</script>
<script>
	$(document).ready(function() {
		$("#somebutton").click(function() {
			servletCall();
		});

	});
	function servletCall() {
		alert("------servlet call---------");
		var FromDate = document.getElementById("t1").value;
		var ToDate = document.getElementById("t2").value;
		$.post("Reports?value=" + FromDate + "&value2=" + ToDate)	}
</script>
</head>
<body>
	<h1>Canceled Service Report</h1>

	From Date
	<input type="text"  id="t1" name="t1">
	<br> To Date
	<input type="text" id="t2" name="t1">
	<br>
	<button id="somebutton">press here</button>
	<div id="somediv"></div>
	<div id="jsGrid"></div>
<script>

	 $("#jsGrid").jsGrid({
		 width: "100%",
	        height: "400px",
	 
	            inserting: true,
	            filtering: true,
	           
	            sorting: true,
	            paging: true,
	            autoload: true,
	            pageSize: 10,
	            controller: {
	                loadData: function (filter) {
	                    return $.ajax({
	                        type: "POST",
	                        url: "/Reports/",
	                        data: filter
	                       
	                    });
	                }
	            },

        fields : [
		       						{name : "patientId",type : "text",width : 150},
	        						{	name : "patientName",type : "text",width : 150}, 
	        						{	name : "genderId",	type : "text",width : 150},
	        						{	name : "mobile",	type : "number",width : 150},
	        						{type : "control"}
	        					 ]
	        	
	        });
		

 </script>
</body>
</html>

**Comment by Venkatramanaryams** [comment]
This is my responce.........from java

[{"patientId":"TP16000002","patientName":"Sagarh","genderId":"1001","mobile":"9853538795"},{"patientId":"TP16000003","patientName":"Sudhir","genderId":"1001","mobile":"9700255639"},{"patientId":"TP16000004","patientName":"Sunidhi","genderId":"1002","mobile":"9853658963"},{"patientId":"TP16000005","patientName":"Sada","genderId":"1001","mobile":"9856321456"},{"patientId":"TP16000006","patientName":"CHARNOCK","genderId":"1001","mobile":"5555555555"}]

**Comment by Venkatramanaryams** [comment]
Tell me how cani load int my grid
