### ISSUE TITLE
editTemplate

### ISSUE THREAD

**Issue by ahmed610** [tabalinas/jsgrid#682]
could you please tell me what I'm doing wrong here:

```js
{  name: "next_f", type: "text", width: 20, title:"next",
    editTemplate: function(value, item) {
        var $input = jsGrid.fields.text.prototype._createTextBox.call(this);
        return $input.attr('style',  'width:50px').attr('value',value);
    }
},
```

when I use the abovethe updateItem is not working

**Comment by richraid21** [comment]
If all you want to do is set the width, you should provide an `editcss: "my-input"` to the field properties then style it like
```
td.my-input>input{
width: 50px;
}
```

**Comment by ahmed610** [comment]
thank you for your answer it worked with me 

however I have added !important to force the style

td.my-input>input{
width: 50px !important;
}

but why updateItem is not working when i use editTemplate>

**Comment by tabalinas** [comment]
@ahmed610, this is because if you redefine `editTemplate` like this, you need to redefine also `editValue`, since grid doesn't know about this `input`.

Or you could jsut redefine the field differently, so that you don't need to redefine `editValue` at all:

```js
    editTemplate: function(value, item) {
        var $result = jsGrid.fields.text.prototype.editTemplate.call(this, value, item);
        $result.attr('style',  'width:50px');
        return $result;
    }
```
