### ISSUE TITLE
Paging resets to #1 after deleteItem

### ISSUE THREAD

**Issue by Peter-With-A-P** [tabalinas/jsgrid#683]
Hi, I'm not sure if this is intended, but I'm finding that if I delete a row on the last page I get kicked back to page 1. It also happens on this jsfiddle (http://jsfiddle.net/tabalinas/zeLnh4qs/) which leads me to think it's intended behaviour rather than me getting something wrong.

It'd be really nice to stay on the page I'm on, so that the next record can easily be deleted too. Any advice?

(Many thanks for awesome tool by the way)

**Comment by richraid21** [comment]
Returning to the beginning is the default behavior of the delete. 

This is mentioned [here](http://js-grid.com/docs/#custom-loadstrategy), for your future documentation needs. Also mentioned is a method of creating a new finishDelete strategy to simple refresh the grid on delete. 

I have implemented the documentation suggestion in a fork of your original fiddle, located [here](http://jsfiddle.net/wo8k2502/). Note both the custom strategy defined at the top of the Javascript, and the configuration of the JsGrid object at the bottom.

**Comment by tabalinas** [comment]
@richraid21, your answer is just great!

**Comment by Peter-With-A-P** [comment]
Thank you so much.
