### ISSUE TITLE
readOnly text field cannot be modified by script

### ISSUE THREAD

**Issue by RevealedFrom** [tabalinas/jsgrid#684]
I have a field as follows:

`{ name: "UpdatedBy", type: "text", "Updated By", readOnly: true }`

and I want to fill it with the id of the user updating it:

`onItemUpdating: function(args) {
args.item.UpdatedBy = "xxxx";
}`

I put a breakpoint and find that, on subsequent hits after the first, the variable `args.item.UpdatedBy` contains my value I updated at the first `onItemUpdating` event.  However, the grid does not show this value.

Is this by design?  Can readOnly fields be modified by script?

**Comment by richraid21** [comment]
onItemUpdating is simply a callback that values the item by value. 

In order to modify the data in the grid, you need to go about doing it a different way:
```
onItemUpdating: function(args){
          var grid = args.grid
          grid.data[args.itemIndex].LastModified = new Date()
          grid.refresh()
        },
```

See a working example [here](https://codepen.io/anon/pen/rypOPb)

**Comment by RevealedFrom** [comment]
Beautiful!  Thanks.

Another question: `onItemUpdating` fires when the editing is done, ie green tick is clicked. Is there an event that fires upon entering into edit mode?

**Comment by richraid21** [comment]
@RevealedFrom `onItemEditing` should work
