### ISSUE TITLE
Proposal: Issue Template

### ISSUE THREAD

**Issue by richraid21** [tabalinas/jsgrid#685]
Github [provides a way for repos to specify a template](https://github.com/blog/2111-issue-and-pull-request-templates) for issues. I think this might be a good way to standardize the way things get reported. 

I propose some form of the following:
```
<!--- 
Please attempt to fit your report into 1 of 3 categories and include the following information:
1. Bug Reports:
    A) Expected Behavior
    B) Actual Behavior
    C) Steps to Reproduce
2. Feature Request:
    A) Desired Feature
    B) Justification for Addition
3. Help Request/Question:
    A) Clearly state your problem
    B) Include your code
    C) If Applicable, attach a JSFiddle or CodePen
-->

<!--- Begin Report Below This Line -->

```

The comments would not be rendered in the posted issue, but would be visible when reporting a new issue. Just an idea!

**Comment by tabalinas** [comment]
Great idea! Perfectly makes sense!
Thank you for the suggestion!
