### ISSUE TITLE
Guidance needed : Live client side search , insert and delete reloading grid

### ISSUE THREAD

**Issue by SouvikRay123** [tabalinas/jsgrid#687]
Hi ,
I am using the ASP.Net Web API demo .
Need some help with the following :-
1) I was trying to make the search live by using the code :
 $(".jsgrid-cell > input").on("keyup", function (e) {
 // can't figure out what to write here so that the search happens
});
2) I wanted to know if there was a way to perform client-side searching instead of hitting the server everytime a search is performed .
3) And after going to a different page , if I delete an item , the grid navigates to the 1st page , whereas incase of edit , the grid edits the row and remains on the current page .

Thanks

**Comment by SouvikRay123** [comment]
Ok , I have solved the insert and delete ones .

**Comment by richraid21** [comment]
1. You need to either trigger loadData or search, depending on if you want paging to be reset. Consult the [search method docs](http://js-grid.com/docs/#searchfilter-promise).     

2. I don't think searching the local dataset is supported. I could be wrong though. @tabalinas 

3. Check out #683 for a solution to the delete problem you're having

**Comment by SouvikRay123** [comment]
Ok thanks , will check them out . 
Also , say I have the following models -->
Parent { 
int parentId ;
list<child> children ;
}

Child{
int childId ;
}

Now , I will show the parent in the main page and I want to show the children along with editing text boxes for the parent when the user clicks on edit . On saving the parent , the changes in the child will also be saved . Any ideas on how to do this ?

**Comment by tabalinas** [comment]
Addressing the second question:

> I wanted to know if there was a way to perform client-side searching instead of hitting the server everytime a search is performed .

This can be easily implemented: load data before grid initialization and in `controller.loadData` implement client-side filtering on the loaded data.

As for your additional question, I think it's too much for a single issue. Please, open another issue for this specific question.
