### ISSUE TITLE
Bootstrap accordion refresh issue

### ISSUE THREAD

**Issue by bluenose1970** [tabalinas/jsgrid#688]
Hi

I have an issue with a jsGrid embedded within a Bootstrap accordion.

On the first click of the accordion the grid is shown but the refresh is visible, grid snaps into place after a few seconds. Is there any way to hide the initial refresh so the grid doesn't snap into place and is just shown?

Example:
https://jsfiddle.net/v6ww51ez/3/

Screenshot on the initial click of the accordion.
![1](https://cloud.githubusercontent.com/assets/25171000/24206109/3d3b1196-0f15-11e7-9b88-bfb8a4c73f1f.png)

Screenshot after the grid has refreshed
![2](https://cloud.githubusercontent.com/assets/25171000/24206143/4d2f11d8-0f15-11e7-929d-7d28b75bfa74.png)

Thanks.

**Comment by richraid21** [comment]
[You could set](https://jsfiddle.net/y2uu3wwp/) its `visibility: hidden;` property by default, then make it visible after the grid refresh. That's more of a hack really. I'm not too familiar with how bootstrap accordians work.

**Comment by bluenose1970** [comment]
Thanks for the response.

Setting the visibility to hidden did work, see updated example:

https://jsfiddle.net/v6ww51ez/4/

Unfortunately though this only works if 1 grid is present, see extended example with 2 tabs (each tab has a grid).

https://jsfiddle.net/v6ww51ez/6/

Now the tabs have stop working (don't collapse). I've tried detecting which tab is clicked and updating accordingly but this doesn't work. Any help is appreciated as I don't think it's far off from working!

Thanks again.

**Comment by tabalinas** [comment]
@bluenose1970, this doesn't work due to example bugs: `if` conditions assign instead of checking and ids should go w/o `#`.

Here is the fixed version:
https://jsfiddle.net/v6ww51ez/7/

**Comment by bluenose1970** [comment]
Terrific! Thanks for the fix, think I've been looking at the issue for too long!

Also, great grid btw!
