### ISSUE TITLE
jsGrid is not function

### ISSUE THREAD

**Issue by mahendaraReddy** [tabalinas/jsgrid#69]
after rediretion to one page to another page then try to add content go grid its showing grid is not a function, but if i add content without redirecting its working fine.

**Comment by tabalinas** [comment]
Could you provide some code or jsfiddle to show the issue?

**Comment by mahendaraReddy** [comment]
$(function() {

	     $("#jsaddgrid").jsGrid({
	         height: "70%",
	         width: "100%",
	         filtering: true,
	         editing: true,
	         sorting: true,
	         paging: true,
	         autoload: true,
	         pageSize: 15,
	         onOptionChanged:function(a){
	          },
	         onOptionChanging:function(aa){
	         },
	                
	         onItemUpdating: function(a) {
	        	 },
	        	 onOptionChanging:function(){
	        	 },
	         deleteConfirm: "Do you really want to delete the Product?",
	         controller: db,
	         fields: [
	                  { title: "Product Name", name: "productName", type:"text",editing: false, width: 100 },
	                  { title: "Product ID", filtering: false,name: "productid", type: "text", width: 100, editing: false, },
	                  { title: "total", filtering: false,name: "quantity", type: "number",range:1,  width: 50,editing:true, },
{ title: "total", filtering: false,name: "quantity", type: "number",range:1,  width: 50,editing:true, },


            { type: "control" }
	              ]
	     
	     });	  

			 (function() {
						    var db = {
						         loadData: function(filter) {
						        	
						        	console.log(filter);
						            return $.grep(this.items, function(items) {
						            	console.log(items);
						                var v= (!filter.productName || items.productName.indexOf(filter.productName) > -1);
						             	console.log(v);
						             	return v;
						            });
						        },

						        insertItem: function(insertingItem) {
						            this.items.push(insertingItem);
						        },

						        updateItem: function(updatingItem) {
						        	console.log(JSON.stringify(updatingItem));
						        },

					       deleteItem: function(deletingItem) {
		                 	$.post('../../orderControler/deleteOrder/'+deletingItem.customerid,function(obj) {});
						        	console.log(deletingItem.customerid);
						    }}
						    window.OrderSave = OrderSave;
						    OrderSave.items = [
						    ];
						}()); 

  var Orderd =   {
       				 "productName":"mahenda",
       				 "productid":"124",
       				 "total":"100",
       				 "quantity":'1',
       				 
       				 };



	    	   $("#jsaddgrid").jsGrid("insertItem",Orderd ).done(function(){
  			       db.push(Orderd);
	    		   console.log(JSON.stringify(Orderd));
  			});

**Comment by mahendaraReddy** [comment]
and how to limit number field to positive numbers only, there is no option i found,

**Comment by tabalinas** [comment]
Your code looks correct. What do you mean by redirect? If this is redirect to another server resource, then you need to be sure that jsGrid javascript are loaded when you apply jsGrid plugin. If you defined the links to scripts with `defer` or `async`, it's possible that DOMContentReady event will be fired before script is loaded.

**Comment by tabalinas** [comment]
Regarding number field value limitations, it's better to open a separate ticket (as an enhancement). Something like provide `min` & `max` options for number field. Also the validation (an upcoming feature) will help too.

Currently, you can define your custom field. Something like `positiveNumber`:

```javascript
    var NumberField = jsGrid.NumberField;

    function PositiveNumberField(config) {
        NumberField.call(this, config);
    }

    PositiveNumberField.prototype = new NumberField({
        min: 0,

        _createTextBox: function() {
            return $("<input>").attr({
                 type: "number",
                 min: this.min
            });
        }
    });

    jsGrid.fields.positiveNumber = jsGrid.PositiveNumberField = PositiveNumberField;

    // applying it
    { name: "Value", type: "positiveNumber", min: 100 }
```

**Comment by mahendaraReddy** [comment]
Thank u very much for info.
