### ISSUE TITLE
Customize select field labels

### ISSUE THREAD

**Issue by krystianx** [tabalinas/jsgrid#693]
Hi, i have problem to customize select field, i cannot override itemTemplate function in my grid, it doesn't execute even i return simple string

my field:

            {
                itemTemplate: function(value, item){
                    return item.cardNumber + ' ' + item.lastName;
                },
                name: 'anglerId',
                title: /*[[#{results.angler}]]*/'',
                type: "select",
                items: anglers,
                valueField: "id",
                textField: "cardNumber",
                selectedIndex: 0,
                width: 100
            }

please help how can i solve this.

**Comment by tabalinas** [comment]
It looks correct. Probably there is a bug somewhere in the code not shown in the snippet.
Show the issue with jsfiddle or on any other public demo page.
Also check DevTools console for the errors.
