### ISSUE TITLE
How can I know the field name which in validator?

### ISSUE THREAD

**Issue by anne214000** [tabalinas/jsgrid#694]
I have a custom validation for many field :

```
    jsGrid.validators.number = {
        message: "@Localizer["numberValidators"]",
        validator: function (value, item) {
            return /^(-?\d+)(\.\d+)?$/.test(value);
        }
    };
```
the "item" is valid Row, but I want to know which field into this validation now.
thanks.

**Comment by tabalinas** [comment]
The field info is not provided in the arguments. 
Since you know which validator you set to the field, you could define specific validators for particular fields, so that you know for which field this validator is used.
