### ISSUE TITLE
Support Assigning ID Attribute To Headers, Filters

### ISSUE THREAD

**Issue by tparikka** [tabalinas/jsgrid#695]
I'm an SDET testing using Selenium to test web application that uses jsgrid and I am wondering if it is currently possible, or possible to support in the future, assigning an ID attribute to filter controls and headers in jsgrid? Right now I'm using Xpath lookups to get the table headers and input controls but best practice is to use IDs whenever possible, as it's faster and a much more reliable lookup method overall. Thank you for your help!

**Comment by richraid21** [comment]
IDs would mean that multiple grids could not be used on the page. Unless IDs are auto generated on the fly, which would mean that JsGrid kept some type of central state. I don't see this happening, sorry.

**Comment by tparikka** [comment]
What if an ID was assigned to the grid as a whole and then IDs for UI controls were dynamically assigned like %GridName%_%header1% or %GridName%_%filter1%, etc?

**Comment by tabalinas** [comment]
As @richraid21 stated, using IDs for a component would make it more difficult to reuse it.
If ids are needed, they should be generated with outside code. It can be done in `onRefreshed` callback for instance, just iterating over headers and filters setting required ids.
