### ISSUE TITLE
Datepicker overflow issue on IOS

### ISSUE THREAD

**Issue by blchatel** [tabalinas/jsgrid#696]
Hi

Following this issue #86, and applying 
```js
.jsgrid` {
    overflow: visible;
}
```
I solved the described issue on all browser except Iphones/Ipads one...where the datepicker stay hidden...

Any Idea to solve it?

Thanks

**Comment by tabalinas** [comment]
Could you provide a jsfiddle or something showing the problem, so it's possible to see the issue and play with it?

**Comment by blchatel** [comment]
Impossible today to reproduce the bug on JSFiddle. Maybe a conflict with other js/css files in my main project. 
I keep trying tomorrow and come up with news

**Comment by tabalinas** [comment]
No reply. Closing
