### ISSUE TITLE
Insert, Update, and Delete from custom buttons outside jsrid

### ISSUE THREAD

**Issue by kvigor** [tabalinas/jsgrid#697]
I have a custom toolbar I've created, however it looks like there's not an API that exposes insert, update, and delete, outside of the jsGrid. 

// Desired Behavior:
function InsertBlankRow()
{
    var mygrid = $("#myGrid").jsGrid()
    mygrid.AddBlankRow(); // Or something similar
}

**Comment by richraid21** [comment]
`editItem`, `deleteItem` and `insertItem` will do what you want

**Comment by kvigor** [comment]
Thanks just tried this moments ago and it works: 
`$("#myGrid").jsGrid("insertItem");` // This inserted a blank row

**Comment by bradybray** [comment]
Is it possible to populate that blank row with data from the table?

**Comment by richraid21** [comment]
@bradybray Yes. You can provide an `item` object.

**Comment by bradybray** [comment]
I'm not sure what you mean.

**Comment by richraid21** [comment]
@bradybray  `insertItem` function can [be provided](http://js-grid.com/docs/#insertitemitem-promise) a row Object to specify the data to add, instead of a blank row.

**Comment by bradybray** [comment]
@richraid21 Ok; that seems simple enough. 

But my particular problem is I have this button control I've created. I want to register for the event it gets click and get the row in which it is currently stored whether by primary key or such. Once I have that information then I can call the `insertItem` function simply enough. How do I get from click the button to calling `insertItem`?

'var MySaveField = function(config) {
	jsGrid.Field.call(this, config);
};

MySaveField.prototype = new jsGrid.Field({
	css: 'save-field',
	align: "center",

	insertTemplate: function(value) {
		return this._insertButton = $("<input type=button value=Save-As id=SaveRuleAs>")
	},

	editTemplate: function(value) {
		return this._editButton = $("<input type=button value=Save-As id=SaveRuleAs>")
	},

});

jsGrid.fields.SaveAs = MySaveField;


$(function() {
	$( '#SaveRuleAs' ).click(function() {
		alert("registered for click event")
	});
});`

**Comment by tabalinas** [comment]
@bradybray: you can find the row like the following `$(e.target).closest("tr")`. Here `e` is a click event coming as a first argument to the `click` handler.
