### ISSUE TITLE
Separate Time and Date Picker 

### ISSUE THREAD

**Issue by GJeeva** [tabalinas/jsgrid#698]
Hi

hi
i want date column and time  column in same grid
how to separate in datetime picker 
Like

Program |     Date       |     Time      |     Modifed By
 CCCC     |  24/4/2017 |    7:15 PM   |      Admin

AS Like that

Thanks & Regards
Jeeva

**Comment by richraid21** [comment]
You will need to create custom field types using the HTML5 form inputs of `type='date'` and `type='time'`. [Browser support is _ok_](http://caniuse.com/#search=time)

**Comment by GJeeva** [comment]
Here i used as
  fields: [ 
            { name: "Program", title: "Program", type: "text" },
            { name: "EventDate", title: "Date", type: "date",  width: 10 },
            { name: "EventTime", title: "Time", type: "time", width: 10, value:"18:00" }, (also tried span )

here, is need any changes ? following code

  editTemplate: function (value) {
            return this._editPicker = $("<input>").datepicker().datepicker("setDate", new Date(value));
        },
        insertValue: function () {
            return this._insertPicker.datepicker("getDate").toISOString();
        },
        editValue: function () {
            return this._editPicker.datepicker("getDate").toISOString();
        },
        filterValue: function () {
            return {
                from: this._fromPicker.datepicker("getDate"),
                to: this._toPicker.datepicker("getDate")
            };

**Comment by GJeeva** [comment]
Here i used as
  fields: [ 
            { name: "Program", title: "Program", type: "text" },
            { name: "EventDate", title: "Date", type: "date",  width: 10 },
            { name: "EventTime", title: "Time", type: "time", width: 10, value:"18:00" }, (also tried span )

here, is need any changes ? following code

  editTemplate: function (value) {
            return this._editPicker = $("<input>").datepicker().datepicker("setDate", new Date(value));
        },
        insertValue: function () {
            return this._insertPicker.datepicker("getDate").toISOString();
        },
        editValue: function () {
            return this._editPicker.datepicker("getDate").toISOString();
        },
        filterValue: function () {
            return {
                from: this._fromPicker.datepicker("getDate"),
                to: this._toPicker.datepicker("getDate")
            };

**Comment by tabalinas** [comment]
@GJeeva, we can help with concrete questions, not just examining your code, not being sure about goal.
If the issue is still actual, please ask more specific question about faced issues.
