### ISSUE TITLE
controller updateItem question

### ISSUE THREAD

**Issue by choldi** [tabalinas/jsgrid#70]
Hello,
I want to defer the updateItem but I don't know how to handle when an error occurs.

Here's my code:

PHP Function:
```php
    public function ajaxUpdateDispositivo()
    {
        $this->render = false;
        $id = intval( $this->f3->get('GET.Id'));
        $dispositivo = $this->f3->get('GET.nombre');
        $query=DispositivoQuery::create()->findOneById($id);
        $query->setNombre("$dispositivo");
        $query->save();
        if ($err) 
            return false;
        else {
            $result = [];
            $var["id"] = $id;
            $var["nombre"] = $dispositivo;
            $result[] = $var;
            return json_encode($result);
        }
    }
```

javascript function:

```javascript
            updateItem: function(updatingItem)
            {
                var d = $.Deferred();
                $.ajax({
                    type: "GET",
                    url: "../../dispositivo/ajaxUpdateDispositivo",
                    data: updatingItem
                }).success (function(response) {
                    //response gives me ""
                    d.resolve(response);
                
                }).error (function(xhr, ajaxOptions, thrownError) {
                    //here, restore old row value
                    //previousItem doesn't exist in this point
                    d.resolve();
                });

                return d.promise();
            }
        }
```

How can I get the previous value?

Thanks in advance,
Jordi

**Comment by choldi** [comment]
I've just corrected the success part:
In the controller, I changed the return part:

            $var['Id'] = $id;
            $var['nombre'] = $dispositivo;
            echo json_encode($var);

And in the success part in the updateItem

                $.ajax({
                    type: "GET",
                    url: "../../dispositivo/ajaxUpdateDispositivo",
                    data: updatingItem
                }).success (function(response) {
                    d.resolve($.parseJSON(response));

Still working in the error part.

**Comment by choldi** [comment]
Rendering the grid on fail does the trick

                $.ajax({
                    type: "GET",
                    url: "../../dispositivo/ajaxUpdateDispositivo",
                    data: updatingItem
                }).success (function(response) {
                    d.resolve($.parseJSON(response));
                }).error (function(xhr, ajaxOptions, thrownError) {
                    d.resolve();
                    $("#dispositivo").jsGrid("render");

But I don't know if it is the right way to do it.

**Comment by tabalinas** [comment]
As mentioned in the ticket https://github.com/tabalinas/jsgrid/issues/52 you can use `onItemUpdating ` callback to save previous item.

```javascript
$("#jsGrid").jsGrid({
    onItemUpdating: function(args) {
        previousItem = args.previousItem;
    },

    controller: {
        ...

        updateItem: function(updatingItem) { 
                var d = $.Deferred();
                $.ajax({
                    type: "GET",
                    url: "../../dispositivo/ajaxUpdateDispositivo",
                    data: updatingItem
                }).done(function(response) {
                    d.resolve(response);
                }).fail(function() {
                    d.resolve(previousItem);
                });

                return d.promise();
        },
    },
    ...
}
```

Note that you can use `onError` callback to handle ajax fails.

Am I right, that your ajax request doesn't work now and you always got into fail? Or you just try to handle possible exceptions?

**Comment by choldi** [comment]
Ok, That works. Thanks for your help.
Update works right, I'm just trying to handle possible exceptions, as you said.
