### ISSUE TITLE
How can I set row style by the "rowClass: function(item, itemIndex)"

### ISSUE THREAD

**Issue by Kujoo25** [tabalinas/jsgrid#700]
Hello,
How can I set row style by the rowClass function?
I try set class in css file and then return name in function, but this isn't working.
Can you help me?
Thanks

**Comment by richraid21** [comment]
Please provide an example of your code in [JsFiddle](https://jsfiddle.net/) or [Codepen](https://codepen.io/).

**Comment by tabalinas** [comment]
@Kujoo25, the way you described it, it should just work.
Reopen the issue and come with specifics or an example, as **richraid21** requested, so we can see the problem.
