### ISSUE TITLE
How to export jsGrid Data in Excel

### ISSUE THREAD

**Issue by vikasrai0807** [tabalinas/jsgrid#704]
How to export jsGrid Data in Excel

**Comment by richraid21** [comment]
You cannot directly export to Excel. I currently have a pull request, #703 that would add CSV output functionality. This can be imported to excel.

**Comment by tabalinas** [comment]
We can consider as a duplicate of https://github.com/tabalinas/jsgrid/issues/59

**Comment by vijayvictory1** [comment]
pls give me one example , jsGrid to Excel export
