### ISSUE TITLE
Settings itemTemplate values via ajax timing issue

### ISSUE THREAD

**Issue by kvigor** [tabalinas/jsgrid#705]
I have the following itemTemplate, the problem is at the time my call returns the incorrect icon is returned and set in the UI, is there a way to rebind to the itemTemplate?  Any suggestions... I'm not an ajax expert.  The only way this works is using async: false but there is a bad ui side effect.

```js
itemTemplate: function (_, item) {
                    var isComments;
                    var yesComments = $("<i class='comments icon' style='color: green;'></i>");
                    var noComments = $("<i class='comments icon' style='color: red;'></i>");

                    var isComments = $.ajax({
                        //async: false,
                        type: 'GET',
                        contentType: "application/json; charset=utf-8",
                        url: getRequestBaseUrl() + "HasComments?RequestID=" + item.RequestID,
                        dataType: "json"
                    }).done(function (data) {
                        if (data) {
                            return yesComments;
                        }
                        else {
                            return noComments;
                        }
                    });
                    return isComments.responseText === "true" ? yesComments : noComments;
                  
                }
```

**Comment by richraid21** [comment]
itemTemplate needs to return HTML markup.

**Comment by kvigor** [comment]
itemTemplate is a function to create cell content. It should return markup as string, DomNode or jQueryElement.  

I am returning a jQuery element.

**Comment by tabalinas** [comment]
The point is all necessary data to render the grid should be returned by `loadData` method.
So if you need so data, just return them with all the data on `loadData` call.
`itemTemplate` doesn't support deferred rendering. Your example won't work w/o `async: false`, which is indeed deprecated and provides bad UX.
