### ISSUE TITLE
Attempting to loadData for grid2 from rowClick event of grid1

### ISSUE THREAD

**Issue by kvigor** [tabalinas/jsgrid#707]
The second grid not populated: it just say Please, wait...  my data is actually an array of objects:
e.g. data = [Object, Object, Object ,Object]
```
$("#myGrid").jsGrid({
rowClick: function (args) {

            if (checkBoxField.checked === false) {
                checkBoxField.checked = true;
                populateEquipmentGrid(args); // populate other jsGrid
                // store selected item to array
                selectedItems.push(args.item);
            }
}
});

function populateEquipmentGrid(args) {
        // Populate the Equipment List    
        var id = args.item.RequestID;
            
        $("#myOtherGrid").jsGrid("loadData",
             $.ajax({
                 type: 'GET',
                 contentType: "application/json; charset=utf-8",
                 url: getEquipmentBaseUrl() + "GetDataByID?RequestID=" + id,
                 dataType: "json"      
             })
        );
    }
```

**Comment by kvigor** [comment]
This is also resolved the issue was NOT with jsgrid it was with my code.  If you get a Please, wait... when loading data, there most likely another js error somewhere on the page.

**Comment by tabalinas** [comment]
`loadData` is a method of jsGrid.
In the child grid config for option `controller.loadData` should be provided a function that will return the ajax call results.
The row click handler should call `loadData` method of the grid, so it will reload.
