### ISSUE TITLE
JsGrid - update a row based on the input change of another row.

### ISSUE THREAD

**Issue by ngordiz** [tabalinas/jsgrid#709]
Hi,
 I am trying to reflect the input entered into one row, in another row of the GRID. In the updateItem function, I update the current row that was just modified. Then I get all the items in the grid, start a $.each loop. When I find the proper row, I change the values of the columns in that row. But I can't make the screen to reflect the new values.

**Comment by maurorulli** [comment]
Try to invoke the [refresh](http://js-grid.com/docs/#refresh) method after that.

**Comment by ngordiz** [comment]
Thanks for your help, it works.
