### ISSUE TITLE
Who to make entire jsgrid readonly or disabled

### ISSUE THREAD

**Issue by kvigor** [tabalinas/jsgrid#712]
Is there a recommended way to make the entire jsgrid readonly?  Doing the following the filter row is enabled: 
```
$("#myGrid").prop('disabled', true);
$("#myGrid").children().prop('disable', true);
$(".jsgrid-filter-row").prop('disable', true);
```

**Comment by tanhargithub** [comment]
Hi Kvigor,

I think instead of disabling the grid, you should create and initialize another grid without the functionalities that you want to restrict for Read Only user group.

**Comment by tabalinas** [comment]
Turn off editing and inserting (`editing: false`, `inserting: false`), and hide delete button for control field (`deleteButton: false`).

**Comment by priyarathi** [comment]
How can I turn editing/inserting off after grid is originally initialized with editing/inserting as true?

**Comment by tabalinas** [comment]
@priyarathi, have you tried to set options `editing` and `inserting` to `false`?
`$("#grid").jsGrid("option", "editing", false)`.

**Comment by priyarathi** [comment]
Hi, I tried that but it didn't work. So I achieved it by - 
$("#lodgingJsGrid").jsGrid("fieldOption", "Control", "visible", false);
& then added args.cancel = true; in onItemInserting, onItemEditing & onItemUpdating events.

Thanks!
