### ISSUE TITLE
Set value for hidden column

### ISSUE THREAD

**Issue by kooltest** [tabalinas/jsgrid#713]
How to assign a value to a column when changing to another column

**Comment by tabalinas** [comment]
The issue is unclear. Please provide more details about what you are trying to achieve and what is not working.

**Comment by kooltest** [comment]
I want to assign a amount column after input the quantity column and the unit price column.(sorry my english is bad.)

**Comment by tabalinas** [comment]
For `amount` column define `itemTemplate` returning the computed value. Once you will save edits, the item will be re-rendered and amount will be shown. 

Not sure why you mentioned "hidden column" in the title of the issue.
