### ISSUE TITLE
I can't hide scrollbars

### ISSUE THREAD

**Issue by dotkebi** [tabalinas/jsgrid#714]
hello.

I want to disable scrollbar. So I fixed jsgrid.css like this.
```
.jsgrid-grid-header {
    overflow: auto;
    -webkit-user-select: none;
    -khtml-user-select: none;
    -moz-user-select: none;
    -ms-user-select: none;
    -o-user-select: none;
    user-select: none;
}

.jsgrid-grid-body {
    overflow: auto;
    -webkit-overflow-scrolling: touch;
}
```

![image](https://cloud.githubusercontent.com/assets/8197507/24647377/9e7a2e7a-195a-11e7-80f5-df24213c0601.png)

but that scrollbar still appear.

And I think that height of JSGrid is too long. try to set jQuery height like this

```
<div class="card" id="grid-holder">
  <div class="card-header">
    <strong>header</strong>
  </div>
  <div class="card-block" id="jsGrid"></div>
  <div class="card-footer">
    ...
  </div>
</div>
```

```
var height = window.screen.height * 0.6;
$('#grid-holder').height(height);
```

I try to change height of `#grid-holder` or `#jsGrid`, but it seems not to work correctly.

How can I fit jsGrid and disable scrollbars?

**Comment by tabalinas** [comment]
About scrollbars checkout the following issue https://github.com/tabalinas/jsgrid/issues/179

Regarding height: once you set grid height to `100%` it's up to your layout css to make it display properly. See this issue https://github.com/tabalinas/jsgrid/issues/41 for more details.
