### ISSUE TITLE
dyanamically data is fetched through Js-grid,but filtering is not working?

### ISSUE THREAD

**Issue by saikiran214333** [tabalinas/jsgrid#715]
MY Jsp code for js Grid
```js
$(function() {

			$.ajax({
				type : "GET",
				url : "/Final/Reports?value=2016-03-03&value2=2017-03-03"
			}).done(function() {

				$("#jsGrid").jsGrid({
					height : "auto",
					width : "100%",			
					filtering: true,
				       sorting : true,
					paging : true,
					autoload : true,
					pageSize : 3,
					controller : {
						loadData : function(filter) {
							return $.ajax({
								type : "GET",
								url : "/Final/Reports?value=2016-03-03&value2=2017-03-03",
								data : filter
							});
						},
					},
					fields : [ {
						name : "patientId",
						type : "text",
						width : 150
					}, {
						name : "patientName",
						type : "text",
						width : 150
					}, {
						name : "genderId",
						type : "number",
						width : 150
					}, {
						name : "mobile",
						type : "number",
						width : 150
					}, {
						type : "control"
					} ]
				});

			});
		});
```
can any help us?
any help would be greatly appreciated

**Comment by Venkatramanaryams** [comment]
I have also  that same problem,filtering is not working..
your help would be greatly appreciated
Thanks in advance

**Comment by maurorulli** [comment]
@saikiran214333 Do you have managed the object filter in your Servlet (or other server side component)?

@Venkatramanaryams complete your opened issue providing further information please.

**Comment by saikiran214333** [comment]
no @maurorulli  actully i am new to js grid and i fetched the data using servlet and it is shown in the grid.
but i dont know how filter the data.
can u help me out.

**Comment by Venkatramanaryams** [comment]
k @maurorulli

**Comment by maurorulli** [comment]
@saikiran214333 you are loading data two times. First in your external ajax call, and than inside the loadData definition. You have to chose one (the loadData definition is strongly raccomended).
The loadData uses the filter param to define the criteria search. 
Check the [DOC](http://js-grid.com/docs/#loaddatafilter-promisedataresult).

**Comment by saikiran214333** [comment]
As u said @maurorulli  i removed the ajax call to one time and i replaced a filter. as u see below
<script>
		$(function() {
		
			var filter = $("#grid").jsGrid("getFilter");
				$("#jsGrid").jsGrid({
					height : "auto",
					width : "100%",
					filtering: true,
					sorting : true,
					paging : true,
					autoload : true,
					pageSize : 10,
					controller : {
						loadData : function() {
							return $.ajax({
								type : "GET",
								url : "/Final/Reports?value=2016-03-03&value2=2017-03-03",
								data : filter
							});
						
						},
					},
					fields : [ {
						name : "patientId",
						type : "text",
						width : 150
					}, {
						name : "patientName",
						type : "text",
						width : 150
					}, {
						name : "genderId",
						type : "number",
						width : 150
					}, {
						name : "mobile",
						type : "number",
						width : 150
					}, {
						
					} ]
				});

			});
	</script>
am not geting throgh the doc site. can u please help me out..... with sample code..
thanks in advance.

**Comment by maurorulli** [comment]
Please format the code. Help us to help you.

**Comment by saikiran214333** [comment]
$(function() {
		
	
				$("#jsGrid").jsGrid({
					height : "auto",
					width : "100%",
					filtering: true,
					sorting : true,
					paging : true,
					autoload : true,
					pageSize : 10,
					fields : [ {
						name : "patientId",
						type : "text",
						width : 150
					}, {
						name : "patientName",
						type : "text",
						width : 150
					}, {
						name : "genderId",
						type : "number",
						width : 150
					}, {
						name : "mobile",
						type : "number",
						width : 150
					}, {
						
					} ],
					controller : {
					loadData : function(filter) {
						return $.ajax({
							type : "GET",
							url : "/Final/Reports",
							data :filter
						});
					
					},
				},
				});

			});

**Comment by maurorulli** [comment]
And what's the problem with this code? Which behavior?

Your Reports servlet get called? Does it recive the data parameter?

**Comment by saikiran214333** [comment]
yes @maurorulli  data is came to the GRID table.But Filtering is not working.

**Comment by maurorulli** [comment]
What is the "data" parameter's value in your servlet?

**Comment by saikiran214333** [comment]
@maurorulli  STRING IS THE PARAMETER.
public class Reports extends HttpServlet {
	String jstring = null;
public void doGet(HttpServletRequest request, HttpServletResponse response)
			throws ServletException, IOException {
		PrintWriter out = response.getWriter();

		String s1 = request.getParameter("value");

		String s2 = request.getParameter("value2");

		try {
			List<Patient> pList = new ArrayList<Patient>();

			Class.forName("");
			Connection con = DriverManager
					.getConnection(
							"XYZ",
							"USERNAME", "PASSWORD");
			Statement st = con.createStatement();

			String query = "QUERY";
			System.out.println("MY QUERY=" + query);

			ResultSet rs = st.executeQuery(query);
			Patient patient = null;
			Gson gson = new Gson();
			if (rs != null) {
				while (rs.next()) {
					patient = new Patient();
					patient.setPatientId(rs.getString("COLUMN NAME"));
					patient.setPatientName(rs.getString("COLUMN NAME"));
					patient.setGenderId(rs.getString("COLUMN NAME"));
					patient.setMobile(rs.getString("COLUMN NAME"));
					pList.add(patient);

				}
				jstring = gson.toJson(pList);
				response.setContentType("application/json");
				response.setCharacterEncoding("UTF-8");
				response.getWriter().write(jstring); ------->THIS IS THE REPSONSE.
				System.out.println(jstring); 
			} else {
				System.out.println("Result:" + rs);
			}

		} catch (Exception e2) {
			e2.printStackTrace();
		}

		finally {
			out.close();
		}

	}
}
DATA IS COMING LYK THIS--- [{"patientId":"1234","patientName":"XYZ","genderId":"02","mobile":"1234567894"}]

**Comment by Venkatramanaryams** [comment]
Hello @maurorulli  I also have same  problem ,please tell the suggestion for us.
Thanks in Advance

**Comment by maurorulli** [comment]
In your servlet you MUST handle the filter input parameter. The ajax request pass to your servlet all parameters needed to filter the query. You have to use these parameters to create dinamically your SQL.

**Comment by saikiran214333** [comment]
sorry i cannot get you.How can handle the filter input parameter.
can you explain me in detail @maurorulli

**Comment by maurorulli** [comment]
try this in your servlet:

`System.out.println("The pageSize param is: " + pageSize);`

What is your output?

**Comment by saikiran214333** [comment]
![capture](https://cloud.githubusercontent.com/assets/26632523/24736891/740b3964-1aa8-11e7-8fcf-bab548211ebb.PNG)
we can't write like that.we have to declare that variable(pageSize) in java or import from any package.

**Comment by saikiran214333** [comment]
@tabalinas @maurorulli We want client side filtering.

**Comment by maurorulli** [comment]
Sorry, my fault.

`System.out.println( "The pageSize param is: " + request.getParameter("pageSize") );`

**Comment by saikiran214333** [comment]
@maurorulli this is we got

12:34:37,634 INFO  [STDOUT] The pageSize param is: null

**Comment by maurorulli** [comment]
And what about:

`System.out.println(` "The data param is: " + request.getParameter("data") );

**Comment by saikiran214333** [comment]
@maurorulli 
12:38:23,907 INFO  [STDOUT] The data param is: null

**Comment by maurorulli** [comment]
inside your loadData function insert:

`alert(filetr);`
or
`console.log(filter);`

before the ajax call. What's your output?

**Comment by saikiran214333** [comment]
we got alert @maurorulli 
![capture1](https://cloud.githubusercontent.com/assets/26632523/24742275/44edc696-1ac7-11e7-9aef-60cbd7eea9e0.PNG)
![capture3](https://cloud.githubusercontent.com/assets/26632523/24742276/44f7e8ec-1ac7-11e7-845c-ca4161844088.PNG)

**Comment by maurorulli** [comment]
`alert(filter);`
without quotes

**Comment by saikiran214333** [comment]
@maurorulli 
![capture4](https://cloud.githubusercontent.com/assets/26632523/24742515/34b38166-1ac8-11e7-83af-efc2c64af4a4.PNG)
![capture5](https://cloud.githubusercontent.com/assets/26632523/24742516/34b6416c-1ac8-11e7-921c-5d9575260c0f.PNG)

**Comment by maurorulli** [comment]
please inspect and show us the contet of that item with your browser tools.

**Comment by saikiran214333** [comment]
which item @maurorulli

**Comment by saikiran214333** [comment]
when we are inspect the page we got the below @maurorulli 
![capture7](https://cloud.githubusercontent.com/assets/26632523/24742953/fec1138c-1ac9-11e7-8622-e973a0b3389c.PNG)

**Comment by Venkatramanaryams** [comment]
Is this Useful? @


![capture](https://cloud.githubusercontent.com/assets/26459147/24743096/90b032a0-1aca-11e7-87c5-c3e3da3baba2.JPG)

**Comment by maurorulli** [comment]
you both are working on the same project?

@saikiran214333 I wolud like to see the content of the object filter. Put a breakpoint on the alert(filter) line and inspect its content.
@Venkatramanaryams Nothing of useful.

**Comment by Venkatramanaryams** [comment]
yes we are working on same project @maurorulli

**Comment by saikiran214333** [comment]
sorry actually we are using jsp to display the js GRid.How can we add break to that.
@maurorulli 
AND Yes we are working on same project

**Comment by maurorulli** [comment]
in your browser's console (hit F12 to open hit) you can debug you javascript

**Comment by saikiran214333** [comment]
This is wat we get when break point is set. @maurorulli 
![capture](https://cloud.githubusercontent.com/assets/26632523/24749301/30a677f0-1ae0-11e7-9cc6-c90482223714.PNG)

**Comment by maurorulli** [comment]
Nice. As you can see on the right you can explode the filter var. I have to see it.

**Comment by saikiran214333** [comment]
@maurorulli 
![capture8](https://cloud.githubusercontent.com/assets/26632523/24752037/c63c491c-1ae9-11e7-916d-67340b3820d7.PNG)

**Comment by maurorulli** [comment]
Ok. Now come back to your servlet. You should get that request parameters. Try this code in your servlet:

```
System.out.println("patientId: " + patientId);
System.out.println("patinetName: " + patinetName);
System.out.println("genderId: " + genderId);
System.out.println("mobile: " + mobile);
```

Try to check the output when you try the filter too.

**Comment by saikiran214333** [comment]
![capture](https://cloud.githubusercontent.com/assets/26632523/24752852/5c06dc16-1aed-11e7-8fda-98dee0bfc233.PNG)

![capture1](https://cloud.githubusercontent.com/assets/26632523/24752856/61e899f8-1aed-11e7-8485-4afbf67a07ee.PNG)
 the out put when i try to filter is going to servlet again and exceting the query
@maurorulli

**Comment by maurorulli** [comment]
Pls, check the spell. pa**tine**tName should be patientName.
Anyway, we are arriving to the spot.
You have to model you SQL dynamically. Something like:

```
String patientId = request.getParameter("patientId");
String patientName = request.getParameter("patientName");
String genderId = request.getParameter("genderId");
String mobile = request.getParameter("mobile);

String SQL = "SELECT * FROM myTable ";
<check if at least one input paramter is not empty. If so:>
SQL += " WHERE (patientId="+patientId+
" OR patientName LIKE %"+patientName+"% "+
" OR genderId = "+genderId +
" OR mobile LIKE %"+mobile+"%";
```
Would be a best practice to change Statement into PreparedStatement (google it to learn it).

**Comment by saikiran214333** [comment]
public class Patient {
private String patientId;
private String patientName;
private String genderId;
private String mobile;
public String getPatientId() {
	return patientId;
}
public void setPatientId(String patientId) {
	this.patientId = patientId;
}
public String getPatientName() {
	return patientName;
}
public void setPatientName(String patientName) {
	this.patientName = patientName;
}
public String getGenderId() {
	return genderId;
}
public void setGenderId(String genderId) {
	this.genderId = genderId;
}
public String getMobile() {
	return mobile;
}
public void setMobile(String mobile) {
	this.mobile = mobile;
}

}

THEN,
we create a objects in servlet 
List<Patient> pList = new ArrayList<Patient>();
we are calling that patient class from servlet @maurorulli

**Comment by maurorulli** [comment]
this is the bean you use for output. But you have at first use those 4 input parameters to filter the records in your query.

**Comment by saikiran214333** [comment]
hello @maurorulli Actually we are not passing any parameters from front end....we have a table in our database we want to fetch the data from that database and showing in grid. so for we take ajavascript file and written the js grid code using controller we are calling our servlet  like this
controller : {
					loadData : function(filter) {
					
						return $.ajax({
							type : "GET",
							url : "/Final/Reports",---------this my servlet
							data:filter
						});

then  we fetched the data like this
![capt](https://cloud.githubusercontent.com/assets/26632523/24755067/6f347024-1af6-11e7-8366-019850839e9d.PNG)
=
=
My problem here is filters are not working 
please tell me the solution for this
Actually i thought that  you did not understood my problem thats why requesting again..
THANK YOU SO MUCH

**Comment by Venkatramanaryams** [comment]
hello @maurorulli 
i saw this code in this git hub
https://github.com/tabalinas/jsgrid/issues/200
we have also same problem
 i tried like that but  did not get result...
we are like what @saikiran214333  mentioned in the last comment
please tell me the proper solution for my problem
 sorry for irritating you
Thanks in advance

**Comment by maurorulli** [comment]
What I'm trying to say is that you HAVE to build your own FILTERING mechanism. JsGrid has not an out-of-the-box filtering. It has a mask to input the filter values, but you have to use it in your server side to filter data.
You can also provide a client-side filtering (mentioned in the @Venkatramanaryams link), but the server side filtering is the the best choice (lower consumption of traffic data).

So, when filtering is enabled, JsGrid call your servlet passing it data insetring in the filter mask. In your servlet you have to use this strings to filter data in your query. The filterd ResultSet come back to JsGrid that refresh the data in the grid.

**Comment by Venkatramanaryams** [comment]
Good Morning @maurorulli  i can change the query but my problem is not that. I put a search boxes below the column name you can saw in above comments. i want working of that search boxes(Filtering is there). like in basic scenario search boxes below http://js-grid.com/demos/ i want to filter or search  the data after attaching to the grid table

**Comment by maurorulli** [comment]
The sample you refer uses a clinet-side filtering. If you inspect the source code of that page, in the db.js script, you'll find the following snippet:

```
        loadData: function(filter) {
            return $.grep(this.clients, function(client) {
                return (!filter.Name || client.Name.indexOf(filter.Name) > -1)
                    && (!filter.Age || client.Age === filter.Age)
                    && (!filter.Address || client.Address.indexOf(filter.Address) > -1)
                    && (!filter.Country || client.Country === filter.Country)
                    && (filter.Married === undefined || client.Married === filter.Married);
            });
        },
```
note: client and clients are the same of your patients.

**Comment by saikiran214333** [comment]
Yes @maurorulli  we write like this but search box filters are not working            
                              controller: {
						loadData: function(filter) {
						    var d = $.Deferred();
                                                      // send request to the server and filter data there
						return $.ajax({
						        type: "GET",
						        url: "/Final/Reports",
						        data: filter,
						      //  dataType: "json"
						    }).done(function(result) {
						        result = $.grep(result, function(item) {
						             // some client-side filtering below
						                  return (!filter.patientId || item.patientId.indexOf(filter.patientId) > -1);
						                   return (!filter.patientName || item.patientName.indexOf(filter.patientName) > -1);
						                    return (!filter.genderId || item.genderId.indexOf(filter.genderId) > -1);
						                     return (!filter.mobile || item.mobile.indexOf(filter.mobile) > -1);
						        });
						        d.resolve(result);
						    });

						    return d.promise();
						},

**Comment by maurorulli** [comment]
loadData is called automatically from jsGrid when you use his filtering system.
If you have your own search box (and search button), try something like:

```
$(yourSearchButton).click(function(){
   $("#grid").jsGrid("loadData", { 
         patientName: yourSearchBox.val(),
         patientId: yourSearchBox.val(),
         .....
      })
   );
});
```
In this manner you'll call manually the loadData method. Refer to [DOC](http://js-grid.com/docs/#loaddatafilter-promise)

**Comment by saikiran214333** [comment]
hello  @maurorulli actually we put the "filtering :true" in our js grid code.So we got that seacrh boxes now we  want working of that search boxes for dyanamic data which is coming from controller(calling from servlet URL:"").

**Comment by saikiran214333** [comment]
@maurorulli  we are waitng for  your reply.

**Comment by maurorulli** [comment]
Sorry, I didn't understood your last question. Has worked fine the previous solution?

**Comment by tabalinas** [comment]
@saikiran214333, @Venkatramanaryams,
As @maurorulli mentioned js-grid doesn't provide data filtering out-of-box, it should be implemented.

In your case (as you described it) the client-side filtering should be used, so you can load data once and then just filter them on the client, something like:

```js

// fetch data for the grid once at the beginning
$.ajax({ ... }).done(function(data) {

    $("#jsGrid").jsGrid({
        ...,

        controller: {
            loadData:  function(filter) {
                return $.grep(data, function(item) {
	            // client-side filtering below (be sure conditions are correct)
	            return (!filter.patientId || item.patientId.indexOf(filter.patientId) > -1) 
	            	&& (!filter.patientName || item.patientName.indexOf(filter.patientName) > -1)
	                && (!filter.genderId || item.genderId.indexOf(filter.genderId) > -1)
	                && (!filter.mobile || item.mobile.indexOf(filter.mobile) > -1);
	        });
            }
        }

    });

})

**Comment by saikiran214333** [comment]
Thanks you @tabalinas @maurorulli @Venkatramanaryams  we got  it.... #thanksAlot
