### ISSUE TITLE
only Header make at center align not the datarow

### ISSUE THREAD

**Issue by PrasadDDharmadhikari** [tabalinas/jsgrid#718]
I want to make Header text in center aligned. how can i do.when i apply align center then datarow also align center but i want only header align.

**Comment by tabalinas** [comment]
`<th>` usually centered by default in browsers (https://jsfiddle.net/tabalinas/0c2gt41s/)
So headers are always centered.
Anyway, if you wish to change styling for header redefine it for `jsgrid-header-cell` class.

**Comment by PrasadDDharmadhikari** [comment]
I use IE browser.it show left align. thanks for reply.it resolved..

**Comment by tabalinas** [comment]
@PrasadDDharmadhikari, ah, good to know about IE!
You are welcome!
