### ISSUE TITLE
multiple select box

### ISSUE THREAD

**Issue by akshata-dasar** [tabalinas/jsgrid#72]
Is it possible to have multiple select box??

**Comment by tabalinas** [comment]
Do you mean several select field? Or several selects in a single field?
To the first question the answer is yes. To the second: you need to create custom field.

**Comment by akshata-dasar** [comment]
several selects in a single field is what i meant... so i can include the jquery multiselect plugin and create custom field??

**Comment by tabalinas** [comment]
Exactly! How to create custom field check out http://js-grid.com/docs/#custom-field

**Comment by akshata-dasar** [comment]
Ok thank you.

**Comment by tabalinas** [comment]
You are welcome!

**Comment by akshata-dasar** [comment]
Hi,

i am not able integarte the custom field for this multiselect plugin.

http://www.erichynds.com/examples/jquery-ui-multiselect-widget/demos/

Could you please help me out with this.

**Comment by tabalinas** [comment]
Here is how you can do it

```javascript
var MultiselectField = function(config) {
    jsGrid.Field.call(this, config);
};

MultiselectField.prototype = new jsGrid.Field({
    
    items: [],
    textField: "",
    
    itemTemplate: function(value) {
        return $.makeArray(value).join(", ");
    },
    
    _createSelect: function(selected) {
        var textField = this.textField;
        var $result = $("<select>").prop("multiple", true);
        
        $.each(this.items, function(_, item) {
            var value = item[textField];
            var $opt = $("<option>").text(value);
            
            if($.inArray(value, selected) > -1) {
                $opt.attr("selected", "selected");
            }
            
            $result.append($opt);
        });
        
        return $result;
    },
    
    insertTemplate: function() {
        var insertControl = this._insertControl = this._createSelect();
        
        setTimeout(function() {
            insertControl.multiselect(); 
        });
        
        return insertControl;
    },
    
    editTemplate: function(value) {
        var editControl = this._editControl = this._createSelect(value);
        
        setTimeout(function() {
            editControl.multiselect();
        });
        
        return editControl;
    },
    
    insertValue: function() {
        return this._insertControl.find("option:selected").map(function() {    
            return this.selected ? $(this).text() : null;
        });
    },
    
    editValue: function() {
        return this._editControl.find("option:selected").map(function() {    
            return this.selected ? $(this).text() : null;
        });
    }
    
});

// using it
var countries = [
    { name: "USA" },
    { name: "Canada" },
    { name: "France" },
    { name: "UK" },
    { name: "Russia" }
];

{ name: "Country", type: "multiselect", width: 100, align: "center", items: countries, textField: "name" }
```

See the working fiddle http://jsfiddle.net/tabalinas/qg4et3ey/16/

**Comment by akshata-dasar** [comment]
Hey, thank you so much it worked with a little modifications.

Thanks,
Akshata

**Comment by tabalinas** [comment]
You are welcome!

**Comment by KaperOzobuco** [comment]
Hello everyone :)
Consultation, it may be that this no longer walk the multi select?

**Comment by tabalinas** [comment]
@KaperOzobuco, not sure I understand what you mean

**Comment by KaperOzobuco** [comment]
I'm trying to implement multi select and I can not do it then I appear me  :(

if you press on the link http://jsfiddle.net/tabalinas/qg4et3ey/16/
really no longer works

**Comment by KaperOzobuco** [comment]
thanks for everything  :))

**Comment by KaperOzobuco** [comment]
this very good grid

**Comment by tabalinas** [comment]
Thank you for the feedback, if you would open browser console, it will see that it's multiselect site that is not responding. Try to find the new location of the multiselect widget (side control, not related to js-grid) and update links, then it should work.

**Comment by KaperOzobuco** [comment]
thanks, when I open the console I find an error in "insertControl.multiselect ();"

in the part of ".multiselect ()" the only difference I made with their example was in items: [], change it by items: [{name: "USA"},
     {Name: "Canada"},
     {Name: "France"},
     {Name: "UK"},
     {Name: "Russia"}]

and end of all
jsGrid.fields.multiselect = jsGrid.MultiselectField = MultiselectField;

once this this me just begun to "work" (with this error and does nothing) without doing any of this simply does nothing: S

**Comment by tabalinas** [comment]
Please fork the fiddle and correct links to multiselect, so we can see the error.

**Comment by KaperOzobuco** [comment]
`(function(jsGrid, $, undefined) {

    var MultiselectField = function(config) {
    jsGrid.Field.call(this, config);
};

MultiselectField.prototype = new jsGrid.Field({

    items: [],
    textField: "",

    itemTemplate: function(value) {
        return $.makeArray(value).join(", ");
    },

    _createSelect: function(selected) {
        var textField = this.textField;
        var $result = $("<select>").prop("multiple", true);

        $.each(this.items, function(_, item) {
            var value = item[textField];
            var $opt = $("<option>").text(value);

            if($.inArray(value, selected) > -1) {
                $opt.attr("selected", "selected");
            }

            $result.append($opt);
        });

        return $result;
    },

    insertTemplate: function() {
        var insertControl = this._insertControl = this._createSelect();

        setTimeout(function() {
            insertControl.multiselect(); 
        });

        return insertControl;
    },

    editTemplate: function(value) {
        var editControl = this._editControl = this._createSelect(value);

        setTimeout(function() {
            editControl.multiselect();
        });

        return editControl;
    },

    insertValue: function() {
        return this._insertControl.find("option:selected").map(function() {    
            return this.selected ? $(this).text() : null;
        });
    },

    editValue: function() {
        return this._editControl.find("option:selected").map(function() {    
            return this.selected ? $(this).text() : null;
        });
    }

});

    jsGrid.fields.multiselect = jsGrid.MultiselectField = MultiselectField;

}(jsGrid, jQuery));
`
This code is embedded in a file in "jqgrid.field.multiselect.js"

and the html I put this

`<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>jsGrid - Validation</title>
    <link rel="stylesheet" type="text/css" href="demos.css" />
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:300,600,400' rel='stylesheet' type='text/css'>

    <link rel="stylesheet" type="text/css" href="../css/jsgrid.css" />
    <link rel="stylesheet" type="text/css" href="../css/theme.css" />

    <script src="../external/jquery/jquery-1.8.3.js"></script>
    <script src="db.js"></script>

    <script src="../src/jsgrid.core.js"></script>
    <script src="../src/jsgrid.load-indicator.js"></script>
    <script src="../src/jsgrid.load-strategies.js"></script>
    <script src="../src/jsgrid.sort-strategies.js"></script>
    <script src="../src/jsgrid.validation.js"></script>
    <script src="../src/jsgrid.field.js"></script>
    <script src="../src/fields/jsgrid.field.text.js"></script>
    <script src="../src/fields/jsgrid.field.number.js"></script>
    <script src="../src/fields/jsgrid.field.multiselect.js"></script>
    <script src="../src/fields/jsgrid.field.checkbox.js"></script>
    <script src="../src/fields/jsgrid.field.control.js"></script>
</head>
<body>
    <h1>Validation</h1>
    <div id="jsGrid"></div>

    <script>
        $(function() {

            $("#jsGrid").jsGrid({
                height: "70%",
                width: "100%",
                filtering: true,
                editing: true,
                inserting: true,
                sorting: true,
                paging: true,
                autoload: true,
                pageSize: 15,
                pageButtonCount: 5,
                deleteConfirm: "Do you really want to delete the client?",
                controller: db,
                fields: [
                    { name: "Name", type: "text", width: 150, validate: "required" },
                    { name: "Age", type: "number", width: 50, validate: { validator: "range", param: [18,80] } },
                    { name: "Address", type: "text", width: 200, validate: { validator: "rangeLength", param: [10, 250] } },
                    { name: "Country", type: "multiselect", items: db.countries, valueField: "Id", textField: "Name",
                        validate: { message: "Country should be specified", validator: function(value) { return value > 0; } } },
                    { name: "Married", type: "checkbox", title: "Is Married", sorting: false },
                    { type: "control" }
                ]
            });

        });
    </script>
</body>
</html>
`

**Comment by tabalinas** [comment]
In your fiddle the links to multiselect are still broken. To make it work you need to provide working links (`External Resources` section on the left side).

**Comment by h-patel** [comment]
Hi i have implemented the multi select but 1 problem my data(country is comming comma separated not array.) is coming as below:
`db.users = [
    {
        "Account": "A758A693-0302-03D1-AE53-EEFE22855556",
        "Name": "Carson Kelley",
        "Country": "USA,Canada"
    },
    {
        "Account": "D89FF524-1233-0CE7-C9E1-56EFF017A321",
        "Name": "Prescott Griffin",
        "Country": "UK"
    },
    {
        "Account": "06FAAD9A-5114-08F6-D60C-961B2528B4F0",
        "Name": "Amir Saunders",
        "Country": ""
    },
    {
        "Account": "EED7653D-7DD9-A722-64A8-36A55ECDBE77",
        "Name": "Derek Thornton",
        "Country": ""
    },
    {
        "Account": "2A2E6D40-FEBD-C643-A751-9AB4CAF1E2F6",
        "Name": "Fletcher Romero",
        "Country": ""
    },
    {
        "Account": "3978F8FA-DFF0-DA0E-0A5D-EB9D281A3286",
        "Name": "Thaddeus Stein",
        "Country": ""
    },
    {
        "Account": "658DBF5A-176E-569A-9273-74FB5F69FA42",
        "Name": "Nash Knapp",
        "Country": ""
    }
];`
So what is happening try to edit the pre selected value is not selecting.
Please let me know what changes need to do

**Comment by gaurav1990-dev** [comment]
How to create multiple select dropdown in single column in js grid. I want this for date as user can select either year or month and year or whole date. Please help me how to achieve this. Thank you

**Comment by vishu3875** [comment]
I need to implement multiple selection in the drop down. The above jsfiddle link is not working. Can someone help on it?
