### ISSUE TITLE
How do I capture the filter column and filter value in the controller

### ISSUE THREAD

**Issue by wzhao6898** [tabalinas/jsgrid#721]
Hi there,

I'm trying to get the server side filtering to work, our server side script takes parameters: table_name, index, size, sort_column_name, sort_column_order, filter_column_name, filter_column_value. How can I capture the filter parameters from JsGrid in the controller, so I can pass them to the server side script?
Thanks,

David

    `$("#jsGrid").jsGrid({
        height: "auto",
        width: "100%",
 
        filtering: true,
        sorting: true,
        paging: true,
        pageLoading: true,
        autoload: true,
        pageSize: 25,
        clearFilterButton: true,
        controller: {
            loadData: function(filter) {
                var d = $.Deferred();
 				var sortField = '';
 				if (typeof filter.sortField !== 'undefined') {
	 				sortField = filter.sortField;
 				}
 				var sortOrder = true;
 				if (typeof filter.sortOrder !== 'undefined') {
 					if (filter.sortOrder === 'desc') {
 						sortOrder = false;
 					}
 				}
				$.ajax({
				url: 'myURL',
				type: 'POST',
				data: JSON.stringify({
                                        method:"getStore",
					params:[
                                         TABLE_NAME,
                                         filter.pageIndex,
					 filter.pageSize,
					 sortField,
					 sortOrder,
                                         FILTER_COLUMN, //where can I get this
                                         FILTER_VALUE // and this one?
                                 ]}),
				contentType: "application/json; charset=utf-8",
				dataType   : "json",
				success    : function(){
				}}).done(function(response) {
                	d.resolve({ data: response.result.items, itemsCount: 200 });
                });
				
                return d.promise();
            }`

**Comment by tabalinas** [comment]
All filter fields coming within `filter` parameter of the `loadData`.
