### ISSUE TITLE
Working of Filters with Dynamic Data on Js grid?

### ISSUE THREAD

**Issue by Venkat147** [tabalinas/jsgrid#722]
Iam using  Jsgrid  and  calling one servlet fetched the data into grid table but filters on working i got filters with "filtering :true" but those are not working. how can i do? Please help me friends..
This is my js grid code
@tabalinas  i used your cod as you said in https://github.com/tabalinas/jsgrid/issues/215
please tell me how can i get

		$(function() {
				$("#jsGrid").jsGrid({
					height : "auto",
					width : "100%",
					filtering: true,
					sorting : true,
					paging : true,
					autoload : true,
					pageSize : 10,
					fields : [ {name : "patientId",type : "text",width : 150},
								 {name : "patientName",type : "text",width : 150},
								  {name : "genderId",type : "number",width : 150},
								   {name : "mobile",type : "number",width : 150	},
								    {	} ],
					
                                        controller: {
						loadData: function(filter) {
						    var d = $.Deferred();

						    // send request to the server and filter data there
						return $.ajax({
						        type: "GET",
						        url: "/Final/Reports",
						        data: filter,
						        dataType: "json"
						    }).done(function(result) {
							    alert(result);
						        result = $.grep(result, function(item) {
						        	 // some client-side filtering below
					        	 return item.patientId === filter.patientId
						        	&& item.patientName === filter.patientName
						        	&& item.genderId === filter.genderId
						        	&& item.mobile === filter.mobile;

						        });
						        d.resolve(result);
						    });

						    return d.promise();
						},
					}
	            }); 
 		});
	
	</script>

**Comment by Venkat147** [comment]
@tabalinas  I used this 
<link type="text/css" rel="stylesheet"
	href="https://cdnjs.cloudflare.com/ajax/libs/jsgrid/1.5.3/jsgrid.min.css" />
<link type="text/css" rel="stylesheet"
	href="https://cdnjs.cloudflare.com/ajax/libs/jsgrid/1.5.3/jsgrid-theme.min.css" />
<script type="text/javascript"
	src="http://code.jquery.com/jquery-1.9.1.min.js"></script>
<script type="text/javascript"
	src="https://cdnjs.cloudflare.com/ajax/libs/jsgrid/1.5.3/jsgrid.min.js"></script>
<script type="text/javascript"
	src="https://cdnjs.cloudflare.com/ajax/libs/jsgrid/1.5.3/jsgrid.min.css"></script>
<script type="text/javascript"
	src="https://cdnjs.cloudflare.com/ajax/libs/jsgrid/1.5.3/jsgrid.js"></script>
<script type="text/javascript"
	src="https://cdnjs.cloudflare.com/ajax/libs/jsgrid/1.5.3/jsgrid.css"></script>
<script type="text/javascript"
	src="https://cdnjs.cloudflare.com/ajax/libs/jsgrid/1.5.3/jsgrid-theme.min.css"></script>
<script type="text/javascript"
	src="https://cdnjs.cloudflare.com/ajax/libs/jsgrid/1.5.3/jsgrid-theme.css"></script>

**Comment by Venkat147** [comment]
PLease Tell me anyOne

**Comment by Venkat147** [comment]
Iam getting error like this
![capture](https://cloud.githubusercontent.com/assets/26997773/24790279/0b3faafe-1b94-11e7-809d-5da14ccbcd1f.JPG)

**Comment by tabalinas** [comment]
It looks like a duplicate, see my answer here https://github.com/tabalinas/jsgrid/issues/715#issuecomment-292755637
