### ISSUE TITLE
Js grid Inserting And Updataing on Dynamic Data

### ISSUE THREAD

**Issue by Venkatramanaryams** [tabalinas/jsgrid#726]
Hello @tabalinas, @maurorulli  I got the Filtering with the Help of  you.(in the issue https://github.com/tabalinas/jsgrid/issues/715) Now  I want  Insrteng and Updating . I tried like this http://zetcode.com/articles/jsgridservlet/     but servlet is not called Please Help Guys..

My Code

  <body>
	<div id="jsGrid"></div>
	<script>

	 $(function() {
        $.ajax({  type: "GET",
       url: "/Final/Reports",
        }).done(function(data) {

                $("#jsGrid").jsGrid({
         	height : "auto",
		width : "100%",
		inserting:true,
		filtering: true,
		sorting : true,
		paging : true,
		autoload : true,
		pageSize : 10,
		fields : [ {
			name : "patientId",
			type : "text",
			width : 150
		}, {
			name : "patientName",
			type : "text",
			width : 150
		}, {
			name : "genderId",
			type : "number",
			width : 150
		}, {
			name : "mobile",
			type : "number",
			width : 150
		}, { type:"control"	} ],

        controller: {
            loadData:  function(filter) {
                return $.grep(data, function(item) {
	            // client-side filtering below (be sure conditions are correct)
	            return (!filter.patientId || item.patientId.indexOf(filter.patientId) > -1) 
	            	&& (!filter.patientName || item.patientName.indexOf(filter.patientName) > -1)
	                && (!filter.genderId || item.genderId.indexOf(filter.genderId) > -1)
	                && (!filter.mobile || item.mobile.indexOf(filter.mobile) > -1);
	        });
            },
    insertItem: function (item) {
        alert("entering");
        return $.ajax({
            type: "POST",
            url: "/Final/Reports",
            data: item
                             });
                           }
                        }
                     });
                 });
            });
	 </script>

Please Tell me my Mistake
 Thanks in Advance

**Comment by saikiran214333** [comment]
Hello @tabalinas  @maurorulli thanku in advance. With the help of you guys we both( @Venkatramanaryams  ) achieved filtering successfully. Now we are working on the inserting data to the data base and editing.Can you guys correct  the code please.Please guide us.
Thanks U

**Comment by Venkatramanaryams** [comment]
Please any one help us

**Comment by saikiran214333** [comment]
Please @tabalinas  help us..

**Comment by maurorulli** [comment]
@saikiran214333 @Venkatramanaryams 
Guys I tried from the beginning to help you in the right direction. But I guess you have some basic issues.
I cannot do your work.

I said you that you should use server side filtering. You need server side filtering if you want server side feautures (insterting / updating). In my opinion you should restart your project and learning missing concepts.

**Comment by Venkatramanaryams** [comment]
Hello @maurorulli  Thanks for your Response.Actually We want Only Client side Filtering and We got that, i can do server side Filtering with Changing my SQL Query.I want to Develop the project like   http://zetcode.com/articles/jsgridservlet/ But not the same way What he did.  I have my own Database which Contains a lot of Data.I want to Show that Data in Grid Format with Enabling Filtering ,  Inserting And Updating. I completed Filtering. Now I want Inserting and Updtaing,  for that i reffered this http://zetcode.com/articles/jsgridservlet/ But Servlet did not called for that Post method.
Please Help with your Suggestion
Hope you can Help me 
Thanks in Advance

**Comment by saikiran214333** [comment]
@maurorulli  @tabalinas  Thats wat we want actually @Venkatramanaryams said.Please help guys.

Thanks in advance.

**Comment by maurorulli** [comment]
Let us see your servlet

**Comment by Venkatramanaryams** [comment]
my servlet


        public class Reports extends HttpServlet {
           String jstring = null;
                  public void doGet(HttpServletRequest request, HttpServletResponse response)
                             throws ServletException, IOException {
                      PrintWriter out = response.getWriter();
                 try {
                    List pList = new ArrayList();
                      Class.forName("com.informix.jdbc.IfxDriver");
                             Connection con = DriverManager
                                        .getConnection(
                               "databaseconnection",
                             "user name", "password");
                               Statement st = con.createStatement();
                 String query = "select * from temporary_patient_tbl";
					System.out.println("MY QUERY=" + query);
					ResultSet rs = st.executeQuery(query);
				Patient patient = null;
					Gson gson = new Gson();
									if (rs != null) {
				while (rs.next()) {
					patient = new Patient();
					patient.setPatientId(rs.getString("temp_patient_id"));
					patient.setPatientName(rs.getString("temp_patient_name"));
					patient.setGenderId(rs.getString("temp_gender_id"));
					patient.setMobile(rs.getString("temp_mobile"));
					pList.add(patient);
                                      }
			jstring = gson.toJson(pList);
			response.setContentType("application/json");
			response.setCharacterEncoding("UTF-8");
			response.getWriter().write(jstring);
			System.out.println(jstring);
		} else {
			System.out.println("Result:" + rs);
		}

	} catch (Exception e2) {
		e2.printStackTrace();
	}

	finally {
		out.close();
	}
    }
            public void doPost(HttpServletRequest request, HttpServletResponse response)
        throws ServletException {

        String patientId = request.getParameter("patientId");
          String patientName = request.getParameter("patientName");
          String genderId = request.getParameter("genderId");
         String mobile = request.getParameter("mobile");
         Connection con = null;
     PreparedStatement pst = null;

    try {
                          con = DriverManager.getConnection("databaseconnection",
						"useraname", "password");
                pst = con.prepareStatement("INSERT INTO CARS(temp_patient_id, 
       temp_patient_name,temp_gender_id,temp_mobile) "
                + "VALUES(?, ?,?,?)");
        pst.setString(1, patientId);
        pst.setString(2, patientName);
        pst.setString(3, genderId);
        pst.setString(4, mobile);
        pst.executeUpdate();
        System.out.println("Data Added");

             } catch (SQLException ex) {
              } finally {
              try {
            if (pst != null) {
                pst.close();
            }
            if (con != null) {
                con.close();
            }

        } catch (SQLException ex) {
            
            
        }
    }
}

**Comment by maurorulli** [comment]
Does the "entering" alert appear?

**Comment by Venkatramanaryams** [comment]
it is working

**Comment by maurorulli** [comment]
I can't see any issues. Check your javascript console or your server console for any error.

**Comment by Venkatramanaryams** [comment]
But data does not stored in Database and Servlet did not called

**Comment by Venkatramanaryams** [comment]
Is this correct Way https://github.com/tabalinas/jsgrid/issues/475

**Comment by maurorulli** [comment]
Are you sure your servlet didn't called and javascript errors doesn't appeare in browser's console?

**Comment by Venkatramanaryams** [comment]
yes

**Comment by maurorulli** [comment]
There's no reason to not be called. Sorry I can't help you.

**Comment by Venkatramanaryams** [comment]
I am new toJs grid and java Script Thats why  iam not understaning. Once see this issue
https://github.com/tabalinas/jsgrid/issues/475
https://github.com/tabalinas/jsgrid/issues/190
If you understand Tell me How to do

**Comment by saikiran214333** [comment]
@tabalinas  please help us.

**Comment by saikiran214333** [comment]
@maurorulli @tabalinas  We got inserting the values dyanamically to data base now we want to implement the  deletion and updation can you guys guide us. We written code for the deleting and updating but row values didn't get through servlet.How can i get that row values of js grid table into servlet.Please help us.
THANKS IN ADVANCE.

**Comment by maurorulli** [comment]
@saikiran214333 @Venkatramanaryams 
Does everything work fine now? Just for curiosity, what was the issue?

**Comment by saikiran214333** [comment]
@maurorulli  got it with out any errors. #projectcompleted #715 #thanksfrur cooperation
