### ISSUE TITLE
get filter value

### ISSUE THREAD

**Issue by nmorich** [tabalinas/jsgrid#729]
how get filter value on edit or delete? below my code

$.ajax({
        type: "POST",
        url: "./preventivi.php",
        data: "arch=" + arch + "&submit=mostrapreventivi",
        dataType: "json",
        success: function (msg) {
            var db = {
                loadData: function (filter) {
                    return $.grep(this.clients, function (client) {
                        return (!filter.numero || client.numero.indexOf(filter.numero) > -1)
                                && (!filter.rev || client.rev.indexOf(filter.rev) > -1)
                                && (!filter.datait || client.datait.indexOf(filter.datait) > -1)
                                && (!filter.daticliente.toLowerCase() || client.daticliente.toLowerCase().indexOf(filter.daticliente.toLowerCase()) > -1)
                                && (!filter.titolo.toLowerCase() || client.titolo.toLowerCase().indexOf(filter.titolo.toLowerCase()) > -1)
                                && (!filter.tempi_consegna.toLowerCase() || client.tempi_consegna.toLowerCase().indexOf(filter.tempi_consegna.toLowerCase()) > -1)
                                && (!filter.pagamento.toLowerCase() || client.pagamento.toLowerCase().indexOf(filter.pagamento.toLowerCase()) > -1)
                                && (!filter.totaleprev || client.totaleprev.indexOf(filter.totaleprev) > -1)
                                && (!filter.totalescontatoprev || client.totalescontatoprev.indexOf(filter.totalescontatoprev) > -1)
                                && (!filter.stato || client.stato.indexOf(filter.stato) > -1);
                    });
                }
            };

            window.db = db;

            db.clients = msg.dati;
            jsGrid.locale("it");
            var campi = [
                {name: "numero", type: "text", title: "<b>Num.</b>", css: "customRow", width: "30"},
                {name: "rev", type: "text", title: "<b>Rev.</b>", css: "customRow", width: "30"},
                {name: "datait", type: "text", title: "<b>Data</b>", css: "customRow", width: "40"},
                {name: "daticliente", type: "text", title: "<b>Cliente</b>", css: "customRow"},
                {name: "titolo", type: "text", title: "<b>Titolo</b>", css: "customRow"},
                {name: "tempi_consegna", type: "text", title: "<b>Tempi di consegna</b>", css: "customRow"},
                {name: "pagamento", type: "text", title: "<b>Pagamento</b>", css: "customRow"},
                {name: "totaleprev", type: "text", title: "<b>Totale</b>", css: "customRow", width: "60"},
                {name: "totalescontatoprev", type: "text", title: "<b>Totale scontato</b>", css: "customRow", width: "60"},
                {name: "stato", type: "select", items: [
                        {name: "Seleziona stato", Id: ""},
                        {name: "Da inviare", Id: "0"},
                        {name: "Inviato", Id: "1"},
                        {name: "Confermato", Id: "2"},
                        {name: "Da risentire", Id: "3"},
                        {name: "Fatturato", Id: "4"},
                        {name: "Archiviato", Id: "5"},
                    ], title: "<b>Stato</b>", valueField: "Id", textField: "name", css: "customRow", width: "60"},
                {type: "control", itemTemplate: function (value, item) {
                        var $result = jsGrid.fields.control.prototype.itemTemplate.apply(this, arguments);
                        var $myButton = $("<i style=\"margin-left: 5px; color: #2E65A1;\"class=\"fa fa-files-o fa-lg\" aria-hidden=\"true\"></i>")
                                .click(function (e) {
                                    copyPrev(item.id);
                                    e.stopPropagation();
                                });
                        var $myButton2 = $("<i style=\"margin-left: 5px; color: #ff0000;\"class=\"fa fa-file-pdf-o fa-lg\" aria-hidden=\"true\"></i>")
                                .click(function (e) {
                                    var idd = item.id;
                                    window.open('./pdf/preventivo.php?idprev=' + idd + '', '_blank');
                                    e.stopPropagation();
                                });
                        return $result.add($myButton).add($myButton2);
                    }}
            ];

            $("#jsGrid").jsGrid({
                width: "100%",
                height: "580px",
                filtering: true,
                editing: true,
                sorting: true,
                paging: true,
                autoload: true,
                pageSize: 10,
                pageButtonCount: 5,
                controller: db,
                deleteConfirm: "Stai per cancellare, sei sicuro?",
                noDataContent: "Nessun record trovato",
                fields: campi,
                // cancella item
                onItemDeleting: function (args) {
                    var idd = args.item.id;
                    $.ajax({
                        type: "POST",
                        url: "./preventivi.php",
                        data: "id=" + idd + "&submit=delete",
                        dataType: "json",
                        success: function () {
                        }
                    });
                },
                // edita item
                onItemEditing: function (args) {
                    args.cancel = true;
                    var ide = args.item.id;
                    aggiorna(ide);
                }
            });            
        }

    });
    $('.showcont').html("<div id=\"jsGrid\"></div>");

**Comment by maurorulli** [comment]
What's exactly your problem? (anche in italiano se preferisci ;) )

**Comment by nmorich** [comment]
Intanto complimenti per l'italiano.
      Ho risolto, dovevo riuscire a recuperare i filtri e reimpostarli
      dopo le varie operazioni.
      
      ho creato le variabili per i filtri, es.
      var filtro = { azienda: "valorefiltro" };
      
      applicato ai campi:
      var campi = [
                          {name: "azienda", type: "text", title:
      "<b>Azienda</b>", css: "customRow", filterTemplate:
      createTextFilterTemplate("azienda", filtro)},
                          {name: "piva", type: "text", title:
      "<b>P.Iva</b>", css: "customRow"},
                          {name: "codicefiscale", type: "text", title:
      "<b>C.F.</b>", css: "customRow"},
                          {name: "email", type: "text", title:
      "<b>E-mail</b>", css: "customRow"},
                          {name: "telefono", type: "text", title:
      "<b>Telefono</b>", css: "customRow"},
                          {name: "cellulare", type: "text", title:
      "<b>Cellulare</b>", css: "customRow"},
                          {name: "metodo", type: "text", title:
      "<b>Pagamento</b>", css: "customRow"},
                          {type: "control"}
                      ];
      
      questa la funzione createTextFilterTemplate:
      
      function createTextFilterTemplate(propertyName, initialFilter) {
          return function () {
              /*DEFAULT*/
              if (!this.filtering)
                  return "";
      
              var grid = this._grid,
                      $result = this.filterControl =
      this._createTextBox();
      
              if (this.autosearch) {
                  $result.on("keypress",
                          function (e) {
                              if (e.which === 13) {
                                  grid.search();
                                  e.preventDefault();
                              }
                          });
              }
              /* END DEFAULT*/
              var gridFilter = initialFilter;
              if (gridFilter && gridFilter[propertyName]) {
                  $result.val(gridFilter[propertyName]);
              }
              return $result;
          }
      }
      
      Grazie comunque
      
      
      Il 11/04/2017 11:33, Mauro Rulli ha scritto:
    
    
      What's exactly your problem? (anche in italiano se preferisci
        ;) )
      —
        You are receiving this because you authored the thread.
        Reply to this email directly, view
          it on GitHub, or mute
          the thread.
      
        
          
          
        
        
      
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/tabalinas/jsgrid","title":"tabalinas/jsgrid","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/tabalinas/jsgrid"}},"updates":{"snippets":[{"icon":"PERSON","message":"@maurorulli in #729: What's exactly your problem? (anche in italiano se preferisci ;) )"}],"action":{"name":"View Issue","url":"https://github.com/tabalinas/jsgrid/issues/729#issuecomment-293204025"}}}
    
    
    
    -- 
...Coltiva Linux che tanto Windows si pianta da solo...

**Comment by maurorulli** [comment]
Good! You can close the issue then.
