### ISSUE TITLE
Visibility of fields - edit and insert

### ISSUE THREAD

**Issue by djjohnjosephuk** [tabalinas/jsgrid#731]
Hi,

I'm having trouble with dynamically showing fields when an item is selected for edit.
I have the column initially hidden by default, using `visible: false` and then within the `onEditing `method I attempt to set the visible flag to true using the `fieldOption `method so a value can be set.

However this seems to interfere with the edit functions as it then no longer converts the row to edit mode.

Is there something I am missing or is this sort of behaviour not supported?

**Comment by richraid21** [comment]
Could you provide an example of your code?

**Comment by djjohnjosephuk** [comment]
Sure, minimal example:

`
$("#jsGrid").jsGrid({
        // ...
        onItemEditing: function(args) {
            $('#jsGrid').jsGrid('fieldOption', 'MyColumn', 'visible', 'true');
            // ... the above line prevents fields converting to edit mode
        },
        fields: [
            { 'title' : 'MyColumn', visible: false } 
        ]
});
`

**Comment by maurorulli** [comment]
[JsFiddle](https://jsfiddle.net/dfk2knpe/)

**Comment by richraid21** [comment]
@maurorulli Thanks for that

@djjohnjosephuk Calling `fieldOption` results in the grid re-rendering itself. This triggers the a `clear` and a `refresh`, both of which cancel any current edit rows. This behavior is baked-in pretty deep.

**Comment by tabalinas** [comment]
Yes, as @richraid21 described, grid re-renders on field option changes. Hidden fields for instance are not rendered, so to show them it requires to re-render the grid.

You can define a `rowClick`, thus that `editItem` is called after showing new field:

```js
      rowClick: function(args) {
	 var item = $(args.event.target).closest("tr").data("JSGridItem");
      	 $('#jsGrid').jsGrid('fieldOption', 'MyColumn', 'visible', 'true');
         this.editItem(item);
      },
```

https://jsfiddle.net/owcxwahm/2/
