### ISSUE TITLE
Width of column works but editing textbox is still small

### ISSUE THREAD

**Issue by andyp05** [tabalinas/jsgrid#732]
Grid displays fine until I hit the edit control. The resulting textbox or textarea is less than half the width of the column. I am new to jsGrid, so am I missing something simple? The functionality works. Just the display is not working. 

```
fields: [
    { name: "Status", type: "text", width: 30, editing: true },
    { name: "Notes", type: "textarea", width: 250, editing: true }
]
```

Thanks in advance for any help.

**Comment by richraid21** [comment]
This shouldn't be happening. Could you please post an example of your code replicating the problem using Jsfiddle or CodePen?

**Comment by andyp05** [comment]
Strange...When I pulled the json api results into a variable and assigned to data in the controller in jsfiddle, it works as expected. In both cases, I load the following files.
```
<script src="https://code.jquery.com/jquery-3.2.1.min.js" integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4=" crossorigin="anonymous"></script>
<link type="text/css" rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jsgrid/1.5.3/jsgrid.min.css" />
<link type="text/css" rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jsgrid/1.5.3/jsgrid-theme.min.css" />
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jsgrid/1.5.3/jsgrid.min.js"></script>
```
It does not work the same in my django app.

![image](https://cloud.githubusercontent.com/assets/14006401/25018354/0f37a484-2055-11e7-9643-33b6b2be5dfc.png)

**Comment by andyp05** [comment]
Found it. Had another css file loading that conflicted with jsgrid. it set max-width: 280px;

Thanks
