### ISSUE TITLE
Can I save as "column name" a name which includes empty space character?

### ISSUE THREAD

**Issue by Theriodis** [tabalinas/jsgrid#733]
In the Basic Scenario js-GRID demo there are two files: basic.html and db.js

I want to set as displayed column name a name which includes empty space character, for example : "Column Name" instead of "Name".

To do so, is there any way:

A) I can set in basic.html:

```
fields: [
                    { name: "Column Name", type: "text", width: 150 },
                    { name: "Age", type: "number", width: 50 },
                    { name: "Address", type: "text", width: 200 },
                    { name: "Country", type: "select", items: db.countries, valueField: "Id", textField: "Name" },
                    { name: "Married", type: "checkbox", title: "Is Married", sorting: false },
                    { type: "control" }
                ]
```
B) I can set in db.js :

```
   db.clients = [
        {
            "Column Name": "Otto Clay",
            "Age": 61,
            "Country": 6,
            "Address": "Ap #897-1459 Quam Avenue",
            "Married": false
        } 
   ];
```

And C) at the same time to make filtering work? How should I change filtering of column Name in the  below code of db.js to make filtering work for the column with my new Name  being "Column Name"? : 

```
        loadData: function(filter) {
            return $.grep(this.clients, function(client) {
                return (!filter.Name || client.Name.indexOf(filter.Name) > -1)
                    && (!filter.Age || client.Age === filter.Age)
                    && (!filter.Address || client.Address.indexOf(filter.Address) > -1)
                    && (!filter.Country || client.Country === filter.Country)
                    && (filter.Married === undefined || client.Married === filter.Married);
            });
        },
```

Thank you in advance

**Comment by Theriodis** [comment]
@maurorulli and @tabalinas  you have helped me lots of times in problems of mine and I thank you very much for doing so.

Do you have any idea how should I solve this problem?

**Comment by maurorulli** [comment]
@Theriodis just set the title properties:

```
fields: [
{ name: "varName", title: "Column Name with blank spaces", type: "text", width: 150 },
...
]
```

**Comment by Theriodis** [comment]
@maurorulli  this way I will save in my client the varName and I don't want it.
I want not only to save in my client for example:    db.clients = [  "Column Name" : "A Test Value", ........ ],

but also to  set the loadData function for filtering of the field "Column Name" and I don't know how to change the loadData function.

i have tried  `&& (!filter[ "Column Name"]|| client[ "Column Name"].indexOf(filter[ "Column Name"]) > -1)`

but filtering misbehaves.

**Comment by maurorulli** [comment]
filter["Column Name with blank spaces"] should work (be careful to use double quotes)

**Comment by Theriodis** [comment]
So you do mean that && (!filter[ "Column Name with blank spaces"]|| client[ "Column Name with blank spaces"].indexOf(filter[ "Column Name with blank spaces"]) > -1) is a proper statement for a simple text field and it should work. Right?

The same practice should I follow for a selectbox, e.x. && (!filter["Column Name with blank spaces"] || client.Country === filter["Column Name with blank spaces"]) ?? Is there any differentiation between different js-GRID fields?

**Comment by maurorulli** [comment]
- Yes.

- Show us the case.

**Comment by Theriodis** [comment]
I observed that this code: `(!filter[ "Column Name with blank spaces"]|| client[ "Column Name with blank spaces"].indexOf(filter[ "Column Name with blank spaces"]) > -1)` works great for text, number and checkbox  except for select field in my code.

Take a look at this code which is for this js-GRID that has as last column a selectbox :

![test](https://cloud.githubusercontent.com/assets/15203809/25233341/328a9ddc-25e7-11e7-905f-1f4d0d111fd1.png)

With the following code when I create a new line, I close the js-GRID and I reopen it this line does not exist.

  ```
                  { name: "Display Name", validate: { message: "Field Display Name is required", validator: function(message) { return message; } }, align: "center", type: "text", width: 40 },
                    { name: "Rule Expression", validate: { message: "Field Rule Expression is required", validator: function(message) { return message; } }, align: "center", type: "text", width: 70 },
					{ name: "Error Description", validate: { message: "Field Error Description is required", validator: function(message) { return message; } }, align: "center", type: "text", width: 70 },
					{ name: "Applies to", validate: { message: "Field Applies to is required", validator: function(value) { return value != ""; } }, align: "center", type: "select", items: rules.applies_to, valueField: "Name", textField: "Name", width: 65 },
```

The database of my js-GRID is the following: 

```
(function() {
	
	var total_rule_ids = 1;

    var rules = {

        loadData: function(filter) {
            return $.grep(this.clients, function(client) {
                return (!filter.ID || client.ID.indexOf(filter.ID) > -1)
					&& (!filter.Name || client.Name.indexOf(filter.Name) > -1)
                    && (!filter["Display Name"] || client["Display Name"].indexOf(filter["Display Name"]) > -1)
					&& (!filter["Rule Expression"] || client["Rule Expression"].indexOf(filter["Rule Expression"]) > -1)
					&& (!filter["Error Description"] || client["Error Description"].indexOf(filter["Error Description"]) > -1)
					&& (!filter["Applies to"] || client["Applies to"] === filter["Applies to"]);
            });
        },
		
		

        insertItem: function(insertingClient) {
			insertingClient.ID = total_rule_ids;
            this.clients.push(insertingClient);
			$("#RulesJson").html(JSON.stringify(this.clients));
			total_rule_ids++;
        },

        updateItem: function(updatingClient) { 
			$("#RulesJson").html(JSON.stringify(this.clients));
		},
		
			
        deleteItem: function(deletingClient) {
            var clientIndex = $.inArray(deletingClient, this.clients);
            this.clients.splice(clientIndex, 1);
			$("#RulesJson").html(JSON.stringify(this.clients));
        }

    };
	
	
	rules.applies_to =  [
        { Name: "All", Id: 0 },
        { Name: "PROCESS_1 v1.0", Id: 1 },
        { Name: "PROCESS_1 v2.0", Id: 2 },
        { Name: "MORTGAGE_LOANS v1.0", Id: 3 }
    ];
	
    rules.clients = [];

	window.rules = rules;
	
   
	
}());
```
If I change the last line of loadData to something different, for example : 

      ```
  loadData: function(filter) {
            return $.grep(this.clients, function(client) {
                return (!filter.ID || client.ID.indexOf(filter.ID) > -1)
					&& (!filter.Name || client.Name.indexOf(filter.Name) > -1)
                    && (!filter["Display Name"] || client["Display Name"].indexOf(filter["Display Name"]) > -1)
					&& (!filter["Rule Expression"] || client["Rule Expression"].indexOf(filter["Rule Expression"]) > -1)
					&& (!filter["Error Description"] || client["Error Description"].indexOf(filter["Error Description"]) > -1)
					&& (!filter.Applies_To || client.Applies_To === filter.Applies_To);
            });
        },
```

then js-grid works great for both inserting and filtering except for the select.

How should I define the select in the database to make filtering work also for selectbox?

**Comment by maurorulli** [comment]
{ name: "Applies to", validate: { message: "Field Applies to is required", validator: function(value) { return value != ""; } }, align: "center", type: "select", items: rules.applies_to, valueField: "Name", textField: "Name", width: 65 }

I guess there's an error. "valueField" shoud be "Id", so the value of Applies_To will be a number (the Id).

**Comment by Theriodis** [comment]
Yes but this way I will save in my client lines of the following format:

```
{
			"ID": 1,
			"Name": "asdas",
			"Display Name": "dasd",
			"Rule Expression": "asdas",
			"Error Description": "dasda",
			"Applies to": 1
		}
```

I want to save in my client the format for example :  `"Applies to": "Select_Option_4"`

If I define the valueField as Name and I give a different name instead of "Applies to" which is a single word, e.x.  "Test" filtering works great. But can I give the name of 2 words with blank between them, as "Applies to"?

**Comment by Theriodis** [comment]
OK I set "valueField" as "Id" and I fixed my problem according to this procedure. 

Thank you  @maurorulli and @tabalinas  very much for your prompt response.
