### ISSUE TITLE
Sorting with itemTemplate of checkbox, delete the statement of checkbox

### ISSUE THREAD

**Issue by rammi987** [tabalinas/jsgrid#734]
Hello, 
i have some trobule, i have an input field as check box like this: 
```js
{
                    name: 'comparegrafh',
                    title: ' ',
                    width: 25,
                    sorting: false,
                    itemTemplate: (value, item ) => {
                        console.log(value)
                        console.log(item)
                        return $('<input>').attr('type', 'checkbox').attr('data-comparegraph-farmid', item.FarmerId);
                    }
                }
```

but then i sorting in the diffent other fields it delete the statement of the input, so i check meaby the first 2 rows and sorting in the name the checkbox i now reset to no be check anymore?

**Comment by rammi987** [comment]
https://fiddle.jshell.net/gruxdxc5/ 
Small picse the of my code there show the bug i mean

**Comment by rammi987** [comment]
@maurorulli??? @richraid21

**Comment by richraid21** [comment]
You're attempting to save state without any of the required properties for a custom field. Have a look [here](http://js-grid.com/docs/#custom-field), specifically for the `editValue` function. 

Furthermore, The default functionality of the grid is to only modify the underlying data when the grid is set to editing mode. If you want to keep track of selected records without using the `editing` portion of the grid, you will need to write your own custom control and logic.

**Comment by rammi987** [comment]
But do you se my fiddle i you custom fields becouse i need the data-attr that the standart checkbox field not support that or?

But if i have a custom field and have editValue will it save the statement or i am out off boundris agian?

Right now i have solved it by merrory chach a array of the inputs. But want to hear have delimit i am off the code en the fiddle

**Comment by tabalinas** [comment]
As @richraid21 mentioned, you have to maintain checkbox states. Once you sort rows they are rendered again and checkbox state is lost. 

See the following fiddle showing a possible solution with maintaining the state:
https://fiddle.jshell.net/tabalinas/vgh8421c/
