### ISSUE TITLE
send data to server to filter query with ajax

### ISSUE THREAD

**Issue by vahidhiv** [tabalinas/jsgrid#74]
Hi. This is what i have:
controller: {
	                loadData: function(filter) {
	                	
	                    return $.ajax({
	                        type: "GET",
	                        url: "js/grid_get_all_products.jsp",
	                        data: filter,
	                        dataType: "json"
	                    });
	                }
	            },
but i want to send a parameter and get it in the mentioned page and set my query using it. How can i do it? 
Thanks in advance.

**Comment by choldi** [comment]
You can try 
``` javascript
controller: {
loadData: function(filter) {
                     data=filter;
                     data['parameter']="value of the parameter";
                    return $.ajax({
                        type: "GET",
                        url: "js/grid_get_all_products.jsp",
                        data: filter,
                        dataType: "json"
                    });
                }
            },

```

and in your backend you will receive the filter values and the new parameter.

Hope it helps

**Comment by vahidhiv** [comment]
Thank you very much. You helped a lot.
And thanks for this lightweight plugin.
