### ISSUE TITLE
Columns of data at minimum size when loading for the first time

### ISSUE THREAD

**Issue by lhuacacolqui** [tabalinas/jsgrid#740]
![image](https://cloud.githubusercontent.com/assets/27408200/25115882/c8cbb850-23ce-11e7-8a23-c092b679dd0c.png)
Hi experts...
I have a problem with loading the table for the first time.
When I click on the order, it normalizes. Someone might have had the same problem I could use a lot of help

After the click.

![image](https://cloud.githubusercontent.com/assets/27408200/25115967/58182340-23cf-11e7-83b6-3fd5d5368157.png)

**Comment by tabalinas** [comment]
Most probably your grid is rendered in a hidden container. 
Please checkout the following issue: https://github.com/tabalinas/jsgrid/issues/265.
