### ISSUE TITLE
inserting commas in a sortable number column

### ISSUE THREAD

**Issue by bunkabox** [tabalinas/jsgrid#741]
Hi,
I have a sortable column with costs in $dollars, but when I have commas in the string, the sorting doesn't work. Is it something to do with the itemTemplate attribute? This is what I have so far for that field: 
`itemTemplate: function(value) {
                        return "$" + value; }`

How can I sort this column with commas?
Thank you for your time!

**Comment by tabalinas** [comment]
What do you mean "sorting doesn't work"? It's sorted incorrectly as strings?
Then define sorting strategy that will provide the sorting you expect.
Put it into `sorter` option of the field, or define a custom strategy if you need it multiple times http://js-grid.com/docs/#custom-sorting-strategy.
