### ISSUE TITLE
Scroll Bar fail ? 

### ISSUE THREAD

**Issue by Drainman** [tabalinas/jsgrid#744]
Hi ! And thank's for this great tool :+1:  !

I'm not shure if this is the right place to write (Sorry).
I try to make a grid with all day of one month but fields exceed size of the <div> use by the grid.
Usually a horizontal scroll bar appear automatically ? 
Cause it don't work for me :/

Other question, as you can see in my code I don't know if i have to use dowload files here on Github (Master) or 1-5-3 version ....
In the two case grid appear but scroll bar no..

# In my **head**

```
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.0/jquery.min.js"></script>
<link type="text/css" rel="stylesheet" href="files/script/jsgrid-1.5.3/jsgrid.min.css" />
<link type="text/css" rel="stylesheet" href="files/script/jsgrid-1.5.3/jsgrid-theme.min.css" />
```

**or ?** 
```
<link type="text/css" rel="stylesheet" href="files/script/jsgrid-master/css/jsgrid.css" />
<link type="text/css" rel="stylesheet" href="files/script/jsgrid-master/css/theme.css" />
```

`<script type="text/javascript" src="files/script/jsgrid-1.5.3/jsgrid.min.js"></script>`
**or ?**
`<script type="text/javascript" src="files/script/jsgrid-master/dist/jsgrid.js"></script>`

# My div : 
`<div id="jsGrid" style="margin:50px;"></div>`

# My script :

```
//build grid
			$("#jsGrid").jsGrid({
			width: "80%",
			height: "500px",
			inserting: true,
			editing: true,
			sorting: true,
			paging: true,
			fields: [
			{ name: "Name", type: "text", width: 150, validate: "required"},
			{name : "L-1", type: "manday", width: 90},
			{name : "Ma-2", type: "manday", width: 90},
			{name : "Me-3", type: "manday", width: 90},
			{name : "J-4", type: "manday", width: 90},
			{name : "V-5", type: "manday", width: 90},
			.
			. //All days
			.
			{ type: "control" , width : 10 }]});
```

PS : Excuse my english (I'm French ^^ )

**Comment by tabalinas** [comment]
Yes, horizontal bar should appear automatically. Please provide a page with public access to show the problem (jsfiddle or any other way).

As for scripts checkout the Getting Started section of the project website http://js-grid.com/getting-started/

**Comment by Drainman** [comment]
Thank's for the help ! 
Here the link : https://jsfiddle.net/rhwxue73/
Hope you can help me ^^ It's for an important project !

**Comment by tabalinas** [comment]
Once you have data in the grid it works https://jsfiddle.net/c6wtLmc0/
Do you want your empty table header to be scrollable?

**Comment by Drainman** [comment]
Oh thank's ! :D 
And yeah, if it's possible I want a scrollbar in my empty table !

**Comment by tabalinas** [comment]
Opened another issue for the bug.

**Comment by robertsLando** [comment]
In order to fix this I have edited main jsgrid css where webkit scrollbars are hidden with a specific css rule, search and remove all `webkit-scrollbar` rules and set `overflow-x: scroll` on `.jsgrid-grid-header` and `.jsgrid-grid-body`
