### ISSUE TITLE
SCSS / CSS mixin for different browsers?

### ISSUE THREAD

**Issue by KarlaGonzalez** [tabalinas/jsgrid#745]
Hi everyone,

I´m having a hard time figuring out how to implement this step by step little manual about styling on sass (in this case only focusing on IE, but actually I would like to include other basic browsers): https://makandracards.com/makandra/1113-different-css-for-ie-using-sass

Could someone recommend some material so I can use different css for specific browsers? Doesn´t have to be this solution. 

Thanks!

**Comment by tabalinas** [comment]
How is this related to jsgrid?
