### ISSUE TITLE
General Factory Function for jsGrid

### ISSUE THREAD

**Issue by bradybray** [tabalinas/jsgrid#746]
Hello;

I am working to incorporate jsGrid in a manner more consistent with DRY principles. Would anyone have some pointers for creating a sort of factory function to create a jsGrid instance much like one would create a new object with arguments being the data source and various configurations? The idea is to make an easily reusable grid component I could populate with data when need be and when passed the data from an ajax query. Then once the object is created it can be rendered to the screen.

It wouldn't be right for you to do my homework for me. I simply ask for pointers and tips or even some resources I could browse to find my way to this solution.

Thank you for jsGrid and cheers;

Braden.

**Comment by tabalinas** [comment]
The intent is a bit unclear.
How is creating of jsgrid instance violates DRY principle?

**Comment by bradybray** [comment]
Sorry for the confusion;

I am managing multiple grid instances in the same page and need a way to update them with data from different sources. The structure of the data is the same but a user may want to view a different table. All the data is stored in a database which is accessed using AJAX. I wrote the backend code myself using a combination of django and django-rest to setup an API for accessing the data. 

Is this anymore clear? I guess I put the cart before the horse. ;)

Braden.

**Comment by tabalinas** [comment]
@bradybray, thanks for the context.
Could you just declare a function wrapping creation of js-grid passing necessary parameters?

**Comment by bradybray** [comment]
@tabalinas no problem
I could declare a function. Is it possible to pass variables to jQuery objects? For example;
`$var = 'attributeID'
function($var, $ajaxQueryResponse) {
  $($var).jsGrid(...) {
    ...
  }
};`

Furthermore would one also be able to pass in an Ajax query/response? You'll notice I slipped that in as a parameter to the function wrapper for jsGrid. What would something like this look like if possible AND to have this occur on button or some sort of click handling event?

Braden.

**Comment by tabalinas** [comment]
> I could declare a function. Is it possible to pass variables to jQuery objects? 
I'm not sure what you mean. You can always have parameters in your factory function and use them (they will be available due to closure).

Try to implement it (using jsfiddle for instance), and once you have a concrete problem or a question it's going to be easy to answer.
