### ISSUE TITLE
Grouping Options

### ISSUE THREAD

**Issue by TartanLeGrand** [tabalinas/jsgrid#748]
Hi, I want to group data. Example: 
![image](https://cloud.githubusercontent.com/assets/25587164/25328075/bdc26208-28d6-11e7-931f-837e20b693c2.png)

The data is group by resource_id and I want this:

![image](https://cloud.githubusercontent.com/assets/25587164/25328645/fdd3aa6c-28d8-11e7-8f18-08d9da306d79.png)

Thanks for Helping !

**Comment by tabalinas** [comment]
Data grouping should be done prior to display in `controller.loadData` or on the server.
As for group rendering in the grid checkout the following issue: https://github.com/tabalinas/jsgrid/issues/223
