### ISSUE TITLE
How to find Row and Highlight particular Row in JsGrid using data value.

### ISSUE THREAD

**Issue by yogesh2591** [tabalinas/jsgrid#749]
i have a grid with 200 rows . i want to implement a find functionality ,where user input a value on for any one column (unique value in column ). then the row which has a value will be highlighted( Changing row Css class ) and grid will scroll to middle to display row , if it is  row below screen. I don't want to use filter functionality.

**Comment by tabalinas** [comment]
Sounds like a good use case.
I see it like this: find you item in the `data` array. Then get the row using `rowByItem` and scroll to this row (checkout this SO issue http://stackoverflow.com/a/4801674/1140893).

**Comment by djdance** [comment]
it works, but what if grid has pages?
