### ISSUE TITLE
get selected text in filter object not the value of a select box

### ISSUE THREAD

**Issue by akshata-dasar** [tabalinas/jsgrid#75]
How do i get the selected text(NOT VALUE) of a select box from filter object passed from the controller on loadData?

controller: {
                loadData: function(filter) {
                    return $.ajax({
                        type: "GET",
                        url: "clients/",
                        data: filter
                    });
                }

**Comment by tabalinas** [comment]
Each field has `filterValue` function that returns value of filter from field. You can redefine buildin behavior for your field to return not the value but item text.

**Comment by tabalinas** [comment]
Something like following:

```javascript
filterValue: function() { 
    return this.items[this.filterControl.val()][this.textField];
}
```

See the fiddle http://jsfiddle.net/tabalinas/Lcfy7htp/
