### ISSUE TITLE
JsGrid only sorts top two rows

### ISSUE THREAD

**Issue by theeedannyd** [tabalinas/jsgrid#750]
Hi,

I have noticed the grid in my case only sorts the top tow rows. I thought it had been my code to make expanding columns on click but I have removed that code and it still does this..

Any ideas?
Many thanks in advance.

$("#jobs-grid").jsGrid({
        width: "100%",
        height: "74.5vh",
        sorting: true,
        paging: true,
        data: contactRequests,
        fields: listingConfig,
        noDataContent: "<div id='no-data-message'><h2>Please use the search tools above to<br /> find what you are looking for.</h2><img src='img/search-icon.jpg' /></div>",

        rowClass: function (item, itemIndex) {

            var rowClass = "";

            $.each(selectedServiceConfig.IssueGroups, function (index, issue) {

                if(item.IssuePriority <= issue.MaxIssuePriority && item.IssuePriority >= issue.MinIssuePriority)
                    rowClass = issue.Name;

            });

            return rowClass;

        },
        rowClick: function (args) {

            //var $target = $(args.event.target);
            //if ($target.closest(".btn-Edit").length) {
            //    EditContactRequest(args.item.Id);
            //}
            //else if ($target.closest(".btn-Sched").length) {
            //    ToggleScheduledComms($target);
            //}
            //else if ($target.closest(".btn-Backfill").length) {
            //    ToggleBackfillSummary($target);
            //}
            //else if ($target.closest(".btn-Hist").length) {
            //    ToggleCommsHistory($target);
            //}
            //else if ($target.closest(".btn-Del").length) {
            //    ToggleDelete($target);
            //}
            //else ($target.closest(".resizable-grid-column").length)
            //{
            //    // handle cell click
            //    var cell = $target.closest(".resizable-grid-column");

            //    if (cell.attr("class") != null)
            //        {
            //    var columnClass = cell.attr("class").split(' ');
            //    var id = columnClass[1];

            //    $(".resizable-grid-column").removeClass("expand");
            //    $("." + id).addClass("expand"); //calculate width
            //    }
            //}

        },
        onInit: function (args) {

            //setTimeout(function () {
            //    $(".jsgrid-header-cell.resizable-grid-column")
            //    .on("click",
            //    function () {

            //        var columnClass = $(this).attr("class").split(' ');
            //        var id = columnClass[1];

            //        if (!$(this).hasClass("expand"))
            //        {
            //            $(".resizable-grid-column").removeClass("expand");
            //            $("." + id).addClass("expand"); //calculate width
            //        }
            //        else
            //        {
            //            $(".jsgrid-cell." + id).addClass("expanded"); //calculate width
            //        }

            //    });
            //}, 500);

        }
    });

**Comment by tabalinas** [comment]
Provide an example to reproduce the issue, it could be a jsfiddle or any other resource with public access.

**Comment by tabalinas** [comment]
No answer.

**Comment by theeedannyd** [comment]
Hi Sorry, I went on holiday, it is going to be hard to give you the files / access because its all a bit restricted. I will try to get back to you shortly. Many thanks
