### ISSUE TITLE
Inserting text into grid field disappears upon clicking edit control

### ISSUE THREAD

**Issue by andyp05** [tabalinas/jsgrid#752]
I am allowing a user to highlight text in a document displayed above the grid and populate the textbox in the grid. I am using the mouseup event in jquery to find the cell and put the text in the box. This works fine. But, when the user clicks the edit control for the row, a blank textarea appears. The text in the row is not copied to the textarea control. 

```js
<script>
    $("#article").on('mouseup', function() {
        var selectedText = getSelectionText();
        var grid = $("#jsGrid").data();
        if (selectedRowNotes == null) {
            alert("NO Grid Row Is SELECTED");
            return;
        }
        if (selectedRowNotes) {
            selectedRowNotes.textContent = selectedRowNotes.textContent + "\n" + selectedText;
        } else {
            selectedRowNotes.textContent = selectedText;
        }
    }); 
</script>
```

In the grid:

```js
        onItemEditing: function(args) {
            selectedRowNotes = args.row[0].cells[6];
        },
        rowClick: function (args) {
            selectedRowNotes = args.event.currentTarget.cells[6];
        }
```

If I cancel the edit, the text reappears. I don't want update the data using ajax since the user may elect to cancel the edit.

Thanks in advance for any suggestions.

**Comment by tabalinas** [comment]
Could you reproduce the issue forking the jsfiddle https://jsfiddle.net/tabalinas/v6ww51ez/ (or any other way)? I'd like to be sure about the intent, and it would be easier to give more specific advice.

**Comment by andyp05** [comment]
If you take a look at https://jsfiddle.net/gp9sLnam/4/ it demonstrates the issue,
1. Click on any grid row.
2. Click text at top and the clicked on row's text will change to 'abc'
3. Click the edit control for the row and the 'abc' is lost.
Thanks

**Comment by tabalinas** [comment]
You changed the cell of the table, it has nothing to do with the item. You have to change the data item.
See fixed fiddle https://jsfiddle.net/97xyhrxc/1/

**Comment by andyp05** [comment]
Thank you very much. Can't believe I missed that.

**Comment by tabalinas** [comment]
You are always welcome!
