### ISSUE TITLE
Edit control moves along with horizontal bar

### ISSUE THREAD

**Issue by hiepphan** [tabalinas/jsgrid#753]
I'm having an issue like this:
My grid has so many columns and it shows horizontal bar in it. When I move that bar when I add or edit a row, I'd like those edit controls (save/remove icons) moves along with the bar. Could someone help me on it?
Thanks!

**Comment by tabalinas** [comment]
You could put this control field on the left and implement a solution similar to describe in this issue https://github.com/tabalinas/jsgrid/issues/105.

**Comment by hiepphan** [comment]
Thanks, @tabalinas, I used double control with the first one has position absolute.
