### ISSUE TITLE
Could I set state editing to all row

### ISSUE THREAD

**Issue by khoinguyen1312** [tabalinas/jsgrid#757]
I need to set state "editing" to all row instead of click on each row to edit. Could I do that.

In my project, there will be a button, if user click on that button, all row in table will set to edting state for edit. Then user will click on "Save button" or "Cancel button".

Thank you.

**Comment by richraid21** [comment]
JsGrid keeps track of the currently editing row for some operations. You could go around the default behavior but their may be some unintended consequences to doing this. You may be better off coming up with a better UX or workflow. Making everything editing would enlarge the grid. Just my 2 cents.
