### ISSUE TITLE
Static data and filtering

### ISSUE THREAD

**Issue by andymacourek** [tabalinas/jsgrid#759]
I downloaded the sample and I can use the grid just fine with static data and sort and such. Filtering controls shows up, but no filtering is actually applied.

**Comment by fredo1950** [comment]
Try to define the rules of filters in a variable.
For example:
`var db = {
                    loadData: function(filter) {
                        return $.grep(data, function (group) {      
                            return (filter.courseId === undefined || group.courseId === filter.courseId)
                            && (!filter.endDate || group.endDate.indexOf(filter.endDate) > -1);
                        });
                    }
                }`
Then add the variable as the value of the controller attribute when initializing jsGrid.
**controller: db**

`$("#jsGrid").jsGrid({
                    height: "600px",
                    width: "100%",
                    filtering: true,
                    editing: true,
                    inserting: true,
                    sorting: true,
                    paging: true,
                    autoload: true,
                    pageSize: 15,
                    pageButtonCount: 5,
                    data: data,
                    controller: db
}`

**Comment by andymacourek** [comment]
That did it!  Thanks!

**Comment by JonilsonC** [comment]
Se você veio em busca de uma solução na qual apenas 1 linha é selecionada e que também desseleciona a mesma linha, aqui está a solução:

If you came looking for a solution in which only 1 line is selected and which also deselects the same line, here is the solution:
`selectedVal = null;

rowClick: function (args) {

             selectedVal = args.item;

             let $row = this.rowByItem(args.item);

             if ($row.hasClass("highlight") === false) {
                 //Deseleciona todas as linhas
                 for (let i = 0; i < this.data.length; i++) {
                     this.rowByIndex(i).removeClass("highlight");
                 }
                 $row.toggleClass("highlight");

             } else {
                 selectedVal = null;
                 $row.toggleClass("highlight");

             }
             console.log(selectedVal);
         }`
