### ISSUE TITLE
Keypress event on text box(Inside Grid)

### ISSUE THREAD

**Issue by akshata-dasar** [tabalinas/jsgrid#76]
where should i write the function for keypress event of an text box inside a grid?? i wrote it in sample.js but it is not working.. Can anyone help with this issue?

**Comment by akshata-dasar** [comment]
Its done! Thank you.

**Comment by mahendaraReddy** [comment]
Hi akshata-dasar,

can u plz tellme how did u do that keypress event of an text box.

**Comment by akshata-dasar** [comment]
Hi Following is the code snippet,

fields: [
	{ name: "attr", title: "address", type: "text", width: 100, insertcss:"attr-insert",
	insertTemplate: function() 
	{
		var valField=this._grid.fields[4]; //the column where we want to see the result
		var $insertControl = jsGrid.fields.text.prototype.insertTemplate.call(this);
	        $insertControl.on("keypress", function() {
			//your code goes here
		});
		return $insertControl;
		}
	}
}]

**Comment by GutoMartins019** [comment]
Hi guys, i tried to implement this function to get the key enter press on editing a text field on the grid row, but is not working. Can you guys help me? How i have to do?

Thanks for your amazing tool, nice work!

**Comment by tabalinas** [comment]
GutoMartins019, It works for you now, right?

**Comment by GutoMartins019** [comment]
Yes, it works! I improved the validation method. Thanks for your amazing job.

**Comment by sripathi123** [comment]
hi GutoMartins019,

can u plz tell me how to achive this keypree event.

**Comment by GutoMartins019** [comment]
hi sripathi123

Yes, i got this event when the user press enter after editing a field.

To do this, i built a edit template with this validation of keypress.

The code below show how i did:

				editTemplate: function(value) {
				var valField=this._grid.fields[3]; //the column where we want to see the result
				var grid = this._grid;
				var $editControl = jsGrid.fields.text.prototype.editTemplate.call(this);
				$editControl.on("keypress", function(e) {
					if ( e.which === 13 ) {
						if(Validation function){
							do something;
						}else{
							grid.updateItem();
							e.preventDefault();
							e.stopPropagation();
						}
					}
				});
				$editControl.val(value);
				return $editControl;
				}

this template is on field declaration of the grid.

Hope i can help you.
