### ISSUE TITLE
jsgrid inline edit by row double click

### ISSUE THREAD

**Issue by TingOng** [tabalinas/jsgrid#761]
Is it possible to inline edit by row double click?

**Comment by tabalinas** [comment]
what exactly you mean by `inline edit`?

**Comment by TingOng** [comment]
I fixed it...thanks for your reply..:)

**Comment by tburd** [comment]
How did you fix it?
I would like to do the same.

Thank you!

**Comment by aqrohadi** [comment]
I have the same problem. Can you help me, to solve inline edit with rowDoubleClick for JsGrid. Thank you!
