### ISSUE TITLE
loading/altering data

### ISSUE THREAD

**Issue by edwardsmarkf** [tabalinas/jsgrid#763]
Hello - totally AWESOME grid tool...   thank you so much for creating it.

i am very new to jsgrid and am attempting to combine js-grid with deepstream to create a dynamic grid.

So, the data might look like this:

- program loads initially with no data:     
**[]**

- a moment later, deepstream provides us the initial data:         
**[ {name: 'Jack', address: '123 here street'}]** 

- three seconds later deepstream makes a change:    
**[ {name: 'Jack', address: '123 THERE street'}]** 

- two seconds later, deepstream changes the data yet again:
**[ {name: 'Jack', address: '123 here street'},{name: 'Jill', address: '789 Elm st'} ]** 

i tried using the following every time the data changes:

> 		$("#jsGrid").jsGrid('refresh');
> 		$("#jsGrid").jsGrid('reload');
> 		$("#jsGrid").jsGrid('reset');
> 		$("#jsGrid").jsGrid('destroy');

destroy blanks out the grid, but i cannot seem to determine how to force jsGrid to "reload"

here is the initial code used to create the grid (cut/paste from examples)

 ```
         $("#jsGrid").jsGrid({
                height: "70%",
                width: "100%",
		controller: {
			insertItem: function(insertRow) {
			    console.log('inserting: ', insertRow);
			},

			updateItem: function(updateRow) { 
				console.log(updateRow);
			},

			deleteItem: function(deleteRow) {
			    console.log('deleting: ' , deleteRow);
			}
		},
		data: sequelizeTable,
                filtering: true,
                editing: true,
                inserting: true,
                sorting: true,
                paging: true,
                autoload: false,
                pageSize: 15,
                pageButtonCount: 5,
                deleteConfirm: "Do you really want to delete?",
                fields: [
                    { name: "sequelizeName", type: "text", width: 150 },
                    { name: "Id", type: "number", width: 50, editing: false },
                    { name: "sequelizeAddress", type: "text", width: 200 },
                    { type: "control" }
                ]
            });

        });


this is probably a very simple question.  thank you for any help and assistance.

EDIT - i read unkind comments by [xopyx](https://github.com/tabalinas/jsgrid/issues/32) -- please don't 
let these comments discourage you.  i have tried many different grid products, and js-grid is the best
 of all of them.  your work is very much appreciated.

```

**Comment by edwardsmarkf** [comment]
SCRATCH QUESTION PLEASE - it would appear that `$("#grid").jsGrid("refresh");` and `$("#jsGrid").jsGrid("refresh");` do different things.  This is a classic example of what happens when one stares at code for too long.

**Comment by tabalinas** [comment]
@edwardsmarkf, so you finally figured it out, right?

The difference between `$("#grid").jsGrid("refresh");` and `$("#jsGrid").jsGrid("refresh")` depends on the id of your grid (use first if it's `id="grid"` and second if it's `id="jsGrid"`) J

PS Thank you for the feedback!

**Comment by edwardsmarkf** [comment]
yeah, pretty silly of me.....  ;-)   and thanks for not giving me the "Stack-Overflow" treatment and downvoting the question.

**Comment by edwardsmarkf** [comment]
NOTE: 

it appears that trying to recreate the table does not seem to work once the grid is displayed, 

`jsgridTable = [{'name': 'only name', 'address':'only address'}];   // no! this wont work.`

this will do the same thing without deleting/recreating the array:
```
jsgridTable.splice(0, jsgridTable.length );	// empty array *WITHOUT* deleting it!
jsgridTable.push({'name': 'only name', 'address':'only address'} );   // yes!
jQuery("#jsGrid").jsGrid("refresh");
```
this is probably obvious, but thought i should mention it.

**Comment by tabalinas** [comment]
I'm not sure I understand the question.
Could you provide a jsfiddle or another public demo to show the problem?

**Comment by tabalinas** [comment]
No answer.

**Comment by pato89** [comment]
Hi my problem is not grid update after the insert a new register in database..!! Help me Please.!!!
