### ISSUE TITLE
Custom position of empty row for data adition

### ISSUE THREAD

**Issue by fymous** [tabalinas/jsgrid#766]
I have a scenario like jsGrid Validation demo.But I have 2 headers in the table and each with a Add control field.First header is at the top of table while second header is at the middle and respective data below each header.
When I click on the Add button of the second header, an empty row for data edition is populated at the top of the table below header 1.Can I add that empty row after second header.

Table:
Header 1 (+Add Button)
    Row1
    Row2
...
Header 2 (+Add Button)
<<on click of this add button i want to populate the empty row for data edition here,Now its getting added below Header 1>>
    Row1
    Row2
..

**Comment by tabalinas** [comment]
Not sure I understand the scenario. Do you have two headers in the same grid?
Or this is two separate grids but influencing on each other?
Having a jsfiddle or another public resource demonstrating the problem would make it much easier to help.

**Comment by tabalinas** [comment]
No answer.
