### ISSUE TITLE
Dynamic select data type?

### ISSUE THREAD

**Issue by epicfaace** [tabalinas/jsgrid#768]
I have a question. Using jsgrid, you can provide some data for a select field as follows:

```
{
    name: "Country",
    type: "select"
    items: [
         { Name: "", Id: 0 },
         { Name: "United States", Id: 1 },
         { Name: "Canada", Id: 2 },
         { Name: "United Kingdom", Id: 3 }
    ],
    valueField: "Id",
    textField: "Name"
}
```

However, is there a way to change this "items" attribute AFTER a grid has been initialized? For example, if some of the values on this dropdown depend on _other_ values elsewhere in the grid, how would one implement that?

**Comment by tabalinas** [comment]
Please, look at this fiddle showing how to implement dependent select fields http://jsfiddle.net/tabalinas/n982uvx1/
It shows the basic idea.
