### ISSUE TITLE
how to update cell value

### ISSUE THREAD

**Issue by tanvan81** [tabalinas/jsgrid#771]
Hey, I have 3 column in gird, 

ex: column A, column B, column C

column C =  column A * column B

I want to update value in Column C, by call updateitem, but error

Uncaught RangeError: Maximum call stack size exceeded

How can I set cell value when Update Item

Tks

**Comment by maurorulli** [comment]
can you provide a JsFiddle?

**Comment by tanvan81** [comment]
sorry for late

Here my link

https://jsfiddle.net/kirknino/1bf8zp6z/43/

tks

2017-05-10 15:20 GMT+07:00 Mauro Rulli <notifications@github.com>:

**Comment by shunty-gh** [comment]
From my very limited experience with jsGrid I would think what you're after is an itemTemplate for your Total column. Something roughly like:

    { 
      name: "Total", 
      type: "number", 
      width: 50, 
      title: "Total",
      editing: false,
      inserting: false,
      itemTemplate: function(value, item) {
          // Probably want to add rounding and error checking on this and maybe even some nice formatting
          return item.Quantity * item.Price * (1 + item.VAT / 100);
      }
    }

This, however, seems to conflict with the fact that you are allowing the user to enter and store (in the array) the total value even though you say you want it to be calculated. So maybe you need an extra field definition like CalcTotal with the above settings, using the editing and inserting properties appropriately.

I suppose that if you wanted to update an internal stored total value you could also use the onItemInserted and/or onItemUpdated callbacks on the grid too. Something like:

      // other grid options...
      // pageButtonCount: 5,
      // ... blah blah
      onItemUpdated: function(args) {
        args.item.Total = args.item.Quantity * args.item.Price * (1 + args.item.VAT /100);
      }

Don't know how you'd get that to update on the grid though - but then you shouldn't be showing it anyway.

Like I said, I'm new to this. But I like it so far.

**Comment by tabalinas** [comment]
@tanvan81, for fields with calculated values, as @shunty-gh proposed, define `itemTemplate` and don't specify `type` property, so it's going to be readonly (https://jsfiddle.net/yg3d12yL/)
