### ISSUE TITLE
Paging on grid inside of a modal

### ISSUE THREAD

**Issue by ktrimmer** [tabalinas/jsgrid#777]
Help please
**The setup** - I have a jsGrid that contains a checkbox. When in Edit Mode and the Checkbox is checked, it opens a bootstrap modal which also contains a jsGrid. The modal jsgrid contains a button  that when click returns the value back the launching jsGrid setting a value of a different field. 

This works beautifully except ...

**The problem** - If I turn paging or filtering on for the jsGrid that is displayed on the Modal. When I navigate to any page that is not page 1 and you click the  Button, the Click function defined in the Edit Template does not fire. 

**My fear** - I fear that I am handling the opening and closing of the Modal incorrectly. 
I've created a JSFiddle that recreates my issue. 
[https://jsfiddle.net/g33kydad/076jxvg0/](url)

Any help overcoming this issue would be greatly appreciated.

**Comment by fredericoregateiro** [comment]
The link to the jsfiddle is wrong: 404

**Comment by tabalinas** [comment]
Please open a new issue with fixed jsfiddle link, if this issue still actual.
