### ISSUE TITLE
Hi, I want to highlight a row a different color after double clicking.

### ISSUE THREAD

**Issue by scottd6** [tabalinas/jsgrid#778]
I have tried  this in the rowDoubleClick event which was an example on this site but it didn't work.  I check the jsFiddle and it didn't work for me there either.

```js
var $myRow = $("#idGridVfSubList").jsGrid("rowByItem",(args.item));
$myRow.toggleClass("rowSelected");
```

Any help would be appreciated.

Thanks,

Scott.

**Comment by scottd6** [comment]
Update:
It is changing the CSS as the correct RGB is showing by alerting:
alert($myRow.css("background-color"));
however it is not taking effect visually.

**Comment by tabalinas** [comment]
Then this is not a jsGrid issue. This is css issue.
I believe you set background for the `tr` like `tr. rowSelected { background: ... }`. Try to set it for `td` like `tr.rowSelected td { background: ... }`.
