### ISSUE TITLE
Get grid array 'data', change the array and refresh the grid

### ISSUE THREAD

**Issue by kyajiv** [tabalinas/jsgrid#779]
We need to make one api request as per the user input and show the results in multiple different grids. User can change the search criteria and we need to refresh the grid as per user input. Is there a way to get the current' data' array or just change the data array and refresh the grid once user click on search button. Right now we are initializing the grid instead of just refreshing the existing grids with new data array,

**Comment by tabalinas** [comment]
Sound like you should set `data` option of the grid `$(".jsGrid").jsGrid("option", "data", [data_items])`.
