### ISSUE TITLE
WYSIWYG editor

### ISSUE THREAD

**Issue by matdrapeau** [tabalinas/jsgrid#780]
Wondering if any of you had success trying to integrate a WYSIWYG editor with a jsGrid textarea field (or any other type)?
It appears there is no callback to trigger right after the rendering of a cell (in edits and inserts), that way we could call some WYSIWYG editor with the appropriate selector.

Like here:
http://jsfiddle.net/1k3cvyyp/3/
The insert seems to work, the edits are not since they are created after loading... How can we call again the tinymce.init after the textarea input to be displayed?

thanks

**Comment by tabalinas** [comment]
Because tinymce cannot be initialized on detached node we have to initialize it once the textarea is attached:

```js
          editTemplate: function(value, item) {
              var $result =  jsGrid.fields.textarea.prototype.editTemplate.apply(this, arguments);
              
              setTimeout(function() {
	          		tinymce.EditorManager.execCommand('mceAddEditor', true, $result.get(0));
              });
              
              return $result;
          }
```

The tricky part is disposing, since we need to remove tinymce instance:

```js
    cancelEdit: function() {
		    if(!this._editingRow)
          	return;
                
        tinymce.remove(this._editingRow.find("textarea").get(0));
        
    		jsGrid.Grid.prototype.cancelEdit.call(this);  
    }
```

Here is a working example http://jsfiddle.net/krg9rmch/

**Comment by ndpawan** [comment]
Well... I doubt about.. How do you know the id of textarea?

I saw this link and copy to my code and try...
The error comes up "Cannot read property 'getContent' of null"

The worked example in

http://jsfiddle.net/krg9rmch/

`        	insertValue: function() {
            	return tinyMCE.get('note_template').getContent();
        	},
        	editValue: function() {
            	return tinyMCE.get('note_template').getContent();
        	}
`
how do you define id of the textarea as "note_template"?

Thanks
