### ISSUE TITLE
Canceling delete enables edit row

### ISSUE THREAD

**Issue by SouvikRay123** [tabalinas/jsgrid#782]
Hi guys ,

I have changed the rowRenderer and included the following lines :

```js
            var grid = this;
            var $editButton = $("<a>").append($("<i class='fa fa-pencil-square-o'>")).append($("<span>Edit</span>"));
            var $deleteButton = $("<a>").append($("<i class='fa fa-trash-o'>")).append($("<span>Delete</span>"));

            $editButton.on("click", function () {
                grid.editItem(item);
            });

            $deleteButton.on("click", function () {
                grid.deleteItem(item);
            });
```

Editing works but if I cancel the delete operation from the javascript popup , the row changes to editing mode . Where should I make a change to fix this ?

**Comment by SouvikRay123** [comment]
Ok , I don't know why this happened , but I added the following in the jsgrid list of options ( I had a requirement to disable editing on clicking the row ) --
        rowClick: function (args) { return; },

and now on clicking cancel , it doesnot enable edit mode .

**Comment by tabalinas** [comment]
Default row click behavior is start editing. When delete button is clicked click event bubbles and fires row click. To avoid this call `stopPropagation` on the event or just `return false`:

$deleteButton.on("click", function (e) {
    grid.deleteItem(item);
    e.stopPropagation();
});
