### ISSUE TITLE
Issue Retrieving Data From jsGrid

### ISSUE THREAD

**Issue by hllau9** [tabalinas/jsgrid#784]
I am not able to retrieve the grid data using the following, any advice?
var data = $('#grid').jsGrid('option', 'data');

but it works for fields.
var data = $('#grid').jsGrid('option', 'fields');

Many thanks.

**Comment by tabalinas** [comment]
Your code snippet is correct.
Probably the reason is you are reading data when grid is empty (not yet loaded).
Please provide a jsfiddle or any other public resource to be able to reproduce the issue.

**Comment by tabalinas** [comment]
No answer.
