### ISSUE TITLE
Override edit button function

### ISSUE THREAD

**Issue by amin750** [tabalinas/jsgrid#785]
how to override default edit function in jsgrid?

**Comment by tabalinas** [comment]
Description lacks any details. What do you mean by "edit function"?  How would you like to override it?

**Comment by amin750** [comment]
**i have button out of jsgrid with name Edit**
![capture2](https://cloud.githubusercontent.com/assets/19873094/26573661/dd230764-4533-11e7-93de-5fa74662995f.JPG)
**when i checked checkbox on grid i want to get data of row for edit**
![capture1](https://cloud.githubusercontent.com/assets/19873094/26573662/dd25b96e-4533-11e7-9b3c-35a03e239eb7.JPG)

## how to do this?

**Comment by tabalinas** [comment]
Checkout `Data Manipulation` demo on the [demo page](http://js-grid.com/demos/).
