### ISSUE TITLE
Conditionally apply "selecting" flag to control which rows are highlighted on mouseover

### ISSUE THREAD

**Issue by vanak** [tabalinas/jsgrid#787]
A) I want to use the select flag conditionally: http://js-grid.com/docs/#selecting-default-true

When the row/field data meets a certain condition, the row should be selectable - otherwise, it's read only.

B) 

I have removed edit/delete buttons from control on certain condition, and I control action from rowClick based on a condition, but I am looking to add conditionally apply the "selecting" flag to control the highlight on mouseover.

```js
$("#test").jsGrid({
        width: "75%",
        height: "800px",
 
        inserting: true,
        editing: true,
        sorting: true,
        paging: true,
		confirmDeleting: true,
		deleteConfirm: "Confirmation?",

        data: testData,
        rowClick: function(args) {
        	if (args.item.user === username) {
                // do something
        	}
        },
        fields: [
		    { name: "ID", type: "number", width: 10 },
            { name: "User", type: "text", width: 50 },
            { type: "control",
                itemTemplate: function(value, item) {
                var out = $([]);

                if(item["User"] === USER.name) {
                    out = out.add(this._createEditButton(item));
                    out = out.add(this._createDeleteButton(item));
                }
                return out;
                }
            }
        ]
});
```

**Comment by tabalinas** [comment]
I think the easiest would be to redefine css for the row for your specific css class. This class should be attached in `rowClass` method (http://js-grid.com/docs/#rowclass) with your specific condition.
