### ISSUE TITLE
How to add custom field with autocomplete text?

### ISSUE THREAD

**Issue by hershe** [tabalinas/jsgrid#788]
I want to add an insert field in the grid with text type and with autocomplete feature.
Please help!

**Comment by SinghKing88** [comment]
Hi Use this beow in grid its Grid Column. you can put inside Fields[]. change the input type to which ever control you like.

{
                name: "AutoComplete",
                itemTemplate: function (_, item) 
               { 
                return $("<InputType>").autocomplete({
                                     source: function (request, response) {
                          $.ajax({
                                     url: url + request.term,
                                    type: 'GET',
                                   dataType: "json",
                           success: function (data) {
                          response(data);
                          },
                   error: function (data) {
                         alert(data.statusText);
                }
            });
        },
    });
                },
                align: "center", width: 120, sorting: false
            },

**Comment by tabalinas** [comment]
@hershe, add a custom field using `autocomplete` widget https://jqueryui.com/autocomplete/ (of course there are a lot of alternatives out there).
Here is how you can define a custom field http://js-grid.com/docs/#custom-field
Feel free to ask concrete questions if anything is unclear about implementation.

**Comment by hahmed1987** [comment]
Hi, from above links I can't understand how to handle id and text together in jsGrid for jquery ui autocomplete.
Currently it is showing either value of the selected item. But if I given text in value and id in id column of list then it is showing value text and not handling id of the selected value. 
kindly help me.

**Comment by caldera500** [comment]
Hi tabalinas,

This is a great script. Thank You!!
I am able to implement autocomplete on insert and edit like this:

var tags = ["tag1", "tag2", "tag3"];

MyDescriptionField.prototype = new jsGrid.Field({

insertTemplate: function(value) {
      return this._editPicker = $("<input>").autocomplete({source : tags});
        },
editTemplate: function(value) {
      return this._editPicker = $("<input>").autocomplete({source : tags});
        },
...........

I have 2 questions:
1.) How do I capture the value for insert and edit? The code below is not working. I would think that all I want to do is get the values that were added to the input fields by autocomplete.

insertValue: function(){
  return this._insertPicker = $("<input>").val();
 },

It seems, if I don't define 'insertValue' & 'editValue' it is not working and the above code is not correct either. 

2.)How do I add the custom field to the search bar. The custom field demo only shows the insert bar but not the search fields.

Thanks again for the great script!!

**Comment by julekwiatrak** [comment]
Hi caldera500,

I can try helping with 2): 

Try adding 

filterTemplate: function(value) {
return this._editPicker = $("").autocomplete({source : tags});
},
filterValue: function(value) {
return this._editPicker = $("").autocomplete({source : tags});
},

and adding **filtering=true** as a parameter to jsGrid like here:

$("#jsGrid").jsGrid({
        height: 300,
        width: "100%",
 
        autoload: true,
        inserting: true,
        editing: true,
        filtering: true,

Hope this helps.

**Comment by caldera500** [comment]
Hi julekwiatrak,
Thanks for the tip. I ended up using:

`filterTemplate: function(value) {
        return this._filterAuto = $("<input>").val(value);
    },
		filterValue : function() {
			return this._filterAuto.val();
		},
`  for the template (without autocomplete) 

and 

`insertTemplate: function(value) {
      return this._insertAuto = $("<input>").autocomplete({
		source : function(req, res){
			$.ajax({
			  url: '/getdescription',
			 dataType : 'json',
			data: {
			  term: req.term
			},
			success: function(data){							
			var result = [];
			data.forEach(function(d){
			result.push(d.pDescription);
			});
			res(result);
			}
		});
	},
	minLength: 2,
	});
        },
	insertValue: function() {
         return this._insertAuto.val();
		},`
for the insert function with autocomplete
