### ISSUE TITLE
Customize select dropdown to have a search box

### ISSUE THREAD

**Issue by umav-123** [tabalinas/jsgrid#789]
Category : Help Request/Question:

Hi Tabalinas,

During insert of a new item, I want to show a search box in the select dropdown as there may be many values. I tried to customize the default select and use the bootstrap-select for live search (using selectpicker class). My modified code is like this

```js
    insertTemplate: function(value, item) {
	var $select = jsGrid.fields.select.prototype.insertTemplate.call(this);
	$select.addClass('selectpicker');
	$select.attr("data-live-search", "true");
	/*$select.selectpicker({
	liveSearch: true
	});	*/		             		
	$select.selectpicker('refresh');
	$select.selectpicker('render');
	
	return $select;
}			
```
    
But nothing gets rendered for this field. Could you let me know how to achieve this
Thanks in advance
Uma

**Comment by tabalinas** [comment]
Could you reproduce the issue in jsfiddle (forking this one for instance http://jsfiddle.net/a4xw24h1/)?

Just a guess, sometimes widgets cannot be initialized on detached DOM Nodes, so it makes sense to postpone initialization like:

```js
insertTemplate: function(value, item) {
	var $select = jsGrid.fields.select.prototype.insertTemplate.call(this);
	$select.addClass('selectpicker');
	$select.attr("data-live-search", "true");
	
	setTimeout(function() {
		$select.selectpicker({
			liveSearch: true
		});		             		
		$select.selectpicker('refresh');
		$select.selectpicker('render');
	});
	
	return $select;
}
```

**Comment by umav-123** [comment]
Thank you so much. When I click on "+" , in the insert row it does display the bootstrap select picker now.  Please see the updated jsfiddle.  ( [http://jsfiddle.net/Uma_V/pt7t7ut4/]  )

But still there is one issue wrt display. The dropdown is not overflowing on the table below, but rendered within the top insert panel.. So its not properly visible. How to make it look like in the default select.

Again, thanks for a great js library

Regards,
Uma

**Comment by tabalinas** [comment]
You have to render the select to the html body.
This line fixes the problem

```js
$select.attr("data-container", "body");
```

http://jsfiddle.net/ugkpsmjd/

**Comment by umav-123** [comment]
Hi Tabalinas,
Thank you so much. That fixed the issue. Really appreciate your putting efforts to provide resolutions

**Comment by tabalinas** [comment]
@umav-123, you are welcome!
