### ISSUE TITLE
Dynamic columns and rows based on itemtemplate

### ISSUE THREAD

**Issue by gradexpert** [tabalinas/jsgrid#792]
3. Help Request/Question:
    A) Clearly state your problem
    B) Include your code
    C) If Applicable, attach a JSFiddle or CodePen
    
-->

Hi there i am binding data to js-grid but i need to dynamically tell the grid that i need to bind x no. of columns and then dynamically assign values and header to the same...can i do something like below?

**View**
```
@model Models.StudentAssessmentViewModel

...

<script type="text/javascript">
          var values = @Html.Raw(Json.Encode(@Model.students));
          var mdetails = @Html.Raw(Json.Encode(@Model.mapDetails));
         var results = @Html.Raw(Json.Encode(@Model.results));
     
 
`$("#mapsDiv").jsGrid({
                height: "auto",
                width: "100%",

                sorting: true,
                paging: false,
                autoload: true,
                data: values,
                
                fields: [
                    { name: "firstname", type: "text" },
                    { name: "surname", type: "text" },
                    {
                        name: "birthdate", type: "text"
                    },
                    {
                        name: "classname", type: "text"
                    },
                    foreach(var i in mdetails)
                     { 
                        name: i.headername, type: "text",

                        itemTemplate: function(value, item) {
                            //find the result value for this student and this mdetail then bind with the value
                        }
                    }
                ]
            });`

          ...
</script>

My MVC View is bound to a **Model** as follows 
```
public class StudentAssessmentViewModel
{
        public StudentAssessmentViewModel() { }
        public List<ShortStudent> students { get; set; }
        public List<ShortResult> results { get; set; }
        public List<MapDetail> mapDetails { get; set; }
}
```

**Comment by tabalinas** [comment]
Yes, you can do that, but use proper JavaScript syntax. No foreach in the object initialization, but build fields array before constructing the grid and just pass this fields array to the grid config.

**Comment by vyasrohit1983** [comment]
I am also looking for some way where I can bind the column name dynamically in JSGrid, so what I need is as below:
PortFolio   Col1   Col2   Col3    Col4    col5    Col6
SomeText  1       0         0          1         0        1
SomeText  1       0         0          1         0        1
SomeText  1       0         0          1         0        1

So first column is of type text and column name Col1 to Col 6 will be dynamic that I can get from some service call and they all are of checkbox type, please give some direction how can i bind column name dynamically ?

**Comment by vyasrohit1983** [comment]
Can you please provide sample code for this, to bind the columns name dynamically, I have list of columns in list.
Desired Output is attacehd, 1st col is fixed rest of the cols are dynamic
![DynamicCol](https://user-images.githubusercontent.com/65226984/95950584-74fefc00-0e12-11eb-8a82-49cb13c63b9b.jpg)
