### ISSUE TITLE
Populating Values into Insert Row from Existing Grid

### ISSUE THREAD

**Issue by bojansoldan** [tabalinas/jsgrid#794]
This may be a completely novice question, but I have a situation where I need to frequently enter similar types of data in the grid control.  Often the only difference between rows is a single field.  I'm looking for a way to click a row or initiate some type of action to have the data replicated into the insert row. 

Any help or guidance on how to do this would be greatly appreciated.

Also, thanks a million for this awesome grid control, it's been wonderful to use so far!

**Comment by richraid21** [comment]
You currently cannot pass default data into the insert row function, so you would have to set the values external of the JsGrid library.    

You could add a parameter to the internal `_insert` function but it might be more trouble than its worth

**Comment by tabalinas** [comment]
@bojansoldan, did you manage to find a solution finally?
Have you tried to follow @richraid21's advices?

**Comment by topo79** [comment]
@richraid21 @tabalinas I am looking for kinda the same here I guess #936 please help me sort this out and the light at the end of the tunnel LOL. TY (BTW this is awesome so far!!)
