### ISSUE TITLE
Sort not working for nested arrays

### ISSUE THREAD

**Issue by carlosalzate74** [tabalinas/jsgrid#795]
Hey

I am using version 1.5.2 and sort is not working when using dot notation, was it fixed on the newer version?

This is how my object looks like:

[
{
"id": 24,
"user_id": 1,
"allowed": true,
"plan": {
"id": 1,
"planName": "Christmas"
}
}
]

BTW, thanks for this great component

**Comment by richraid21** [comment]
Could you post your sorting code please? Preferably in a Jsfiddle or Codepen?

**Comment by carlosalzate74** [comment]
Sure, thanks for answering.
[https://jsfiddle.net/stratsu/yja938gg/32/](url)

There you can sort by User Id, Allowed but Plan

**Comment by richraid21** [comment]
@carlosalzate74 I looked into your problem for a bit, and it is actually more complicated than I anticipated. My original thinking was that you could create a custom sort strategy, but I don't think nested objects are being passed through the system correctly; I will look further when I have time. 

@tabalinas Could we mark this as Help Wanted/Enhancement?

**Comment by carlosalzate74** [comment]
Thanks for looking at it

**Comment by tabalinas** [comment]
@richraid21, thanks for looking into it, based on jsfiddle appears to be a bug (added label).

@carlosalzate74, thanks for the report!

**Comment by carlosalzate74** [comment]
Hello guys,
Do you have any updates in this one?

Thanks

**Comment by uniquejava** [comment]
I found it's because the nested property value is not properly got in jsGrid `_sortData` function.

```js
_sortData: function() {
    var sortFactor = this._sortFactor(),
        sortField = this._sortField;

    if(sortField) {
        this.data.sort(function(item1, item2) {
            // item1[sortField.name] has problem for nested property
            return sortFactor * sortField.sortingFunc(item1[sortField.name], item2[sortField.name]);
        });
    }
},
```
I put the following code before using jsGrid, and this issue resolved.
```js
jsGrid.Grid.prototype._sortData = function () {
  var self = this,
    sortFactor = this._sortFactor(),
    sortField = this._sortField;

  if (sortField) {
    this.data.sort(function (item1, item2) {

      var value1 = self._getItemFieldValue(item1, sortField);
      var value2 = self._getItemFieldValue(item2, sortField);
      return sortFactor * sortField.sortingFunc(value1, value2);
    });
  }
};
```

**Comment by carlosalzate74** [comment]
Yes, it is working, I appreciate it. This is the updated version of my [JSFiddle](https://jsfiddle.net/yja938gg/37/)

Thanks @uniquejava

**Comment by wlya** [comment]
@tabalinas I found that the latest release doesn't include this patch"https://cdnjs.cloudflare.com/ajax/libs/jsgrid/1.5.3/jsgrid.min.css", please check it out.
