### ISSUE TITLE
insert row at first in list

### ISSUE THREAD

**Issue by santosh-vishwakarma** [tabalinas/jsgrid#796]
when i am inserting new row it by default go at the last of the list of row.
Please help me to add new inserted row at first position on the list

**Comment by natxocc** [comment]
On grid config write this:

insertRowLocation: "top"

**Comment by tabalinas** [comment]
@santosh-vishwakarma, please checkout this issue https://github.com/tabalinas/jsgrid/issues/398.

**Comment by kunalkankariya** [comment]
This doesn't seem to work @natxocc
