### ISSUE TITLE
Is it possible to select various rows to cpy to clipboard?

### ISSUE THREAD

**Issue by natxocc** [tabalinas/jsgrid#797]
I need to select multiple rows (with Control Key or other option)
Is is possible to do?
Thanks.

**Comment by tabalinas** [comment]
It depends on what you mean by "select a row".
You could use `Batch Delete` demo (http://js-grid.com/demos/ - demo page) as a reference implementation. It uses checkboxes to select rows. In your case you could use `rowClick` instead of checkboxes and verify that `Ctrl` key is pressed.
