### ISSUE TITLE
 need help  

### ISSUE THREAD

**Issue by minalkArmstrong** [tabalinas/jsgrid#798]
if possible please  attach a jsfiddle

I want to display 3 4 line of description of product in description column but i want to  set fix height to each row and due to fix height all data will not be shown so it should be display on tooltip on cell hover. at end of description three dot will be shown to notify continue description.
i waiting for your reply ...
I want to add css like below example:
<table><tr><td><label tooltip='Slot Nut M8-Manufactured Part-Mild Steel-Flat-Length 20mm-Width 20mm-Thickness 6mm-0.016kg/pcs	'>Slot Nut M8-Manufactured Part-Mild Steel-Flat-Length 20mm-Width 20mm-Thickness...<label></td></tr><table>

**Comment by richraid21** [comment]
Tooltips are based on the `title` attribute of the element. You could create a custom item template and apply the value of the cell to the `title` attribute. You could then use one of the several available `ellipse` CSS properties to achieve the truncated display.

**Comment by tabalinas** [comment]
@richraid21, thanks for the proposed solution!
