### ISSUE TITLE
Grid header closing edit row

### ISSUE THREAD

**Issue by SouvikRay123** [tabalinas/jsgrid#799]
Hi guys ,

When I click on a row to edit it and then click on a column header to sort that column , the edit row is gone . I have tried using jquery as 

```js
$(".jsgrid .jsgrid-header-row .jsgrid-header-cell").click(function (e) {
            alert("Header clicked");
            $(".jsgrid-button.jsgrid-update-button").click();
});  
```

but it doesnot work .

So , my requirement is that when a user is in edit mode and he does something like filter or search or page change , it should show a javascript alert and ask him if he wants to save or not . If he clicks yes , it will save the item and then sort , else it will perform the function like search or sort etc. When I used inspect element of chrome , I saw that on clicking the column header , the edit-row is deleted and then the alert is shown . So , the update-button doesnot exist at that time . What should I do to fulfill the requirement ?

**Comment by tabalinas** [comment]
Try to redefine `cancelEdit` method to have something like:

```js
cancelEdit: function() {
    if(!this._editingRow)
        return;

    if(window.confirm("Save changes?")) {
    	this.updateItem();
    } else {
    	jsGrid.Grid.prototype.cancelEdit.call(this);
    }
}
```
