### ISSUE TITLE
header above scrollbar and border-right property

### ISSUE THREAD

**Issue by mg1075** [tabalinas/jsgrid#8]
In Chrome, the right border is not displaying on a scrollable grid.

![image](https://cloud.githubusercontent.com/assets/2031435/6761194/855dd622-cf1e-11e4-8e83-26f0cd0629ee.png)

Here's the code in question.

![image](https://cloud.githubusercontent.com/assets/2031435/6761204/a73e1478-cf1e-11e4-9aa1-7856c3814d55.png)

And here's how it looks after modifying inline and external css in chrome dev tools. 

![image](https://cloud.githubusercontent.com/assets/2031435/6761235/f0089dcc-cf1e-11e4-9738-962fa5ac35cf.png)

![image](https://cloud.githubusercontent.com/assets/2031435/6761224/d920ae60-cf1e-11e4-8879-6fb530531d16.png)

**Comment by tabalinas** [comment]
It appeared that the issue caused by iframe used for demo showcases. The control is self doesn't have this issue. Thank you for pointing this out.
