### ISSUE TITLE
S.NO number 

### ISSUE THREAD

**Issue by mahendaraReddy** [tabalinas/jsgrid#80]
hi tabalinas,

how can i enable a serial number field, that should be auto increment while inserting, and if i delete any row that can be auto adjust according to serial number.

thanks in advance.

**Comment by tabalinas** [comment]
I guess you'd better define this field not in the grid but in data item. Set this field accordingly on controller `insertItem` and `deleteItem` methods. In `jsGrid` use standard field (without type) and it will just render the value of your autoincrement field as text.

**Comment by mahendaraReddy** [comment]
hi 
while inserting i can manually insert S.NO using a auto increment variable, but if i delete any row i loose the sequence in case i have 5 records in grid then i delete 3rd row then  S.NO sequence become 1 2 4 5.

**Comment by tabalinas** [comment]
I see. In the itemTemplate you have access to item (but not index). To get index you could call `$.inArray(item, $grid.jsGrid("option", "data"))` and return it from `itemTemplate`.
But I guess, the easier way to provide the index in data. If you retrieving data from database you could add a field with serial number with something like e.g. ROW_NUMBER in MS SQL. If it's a local array then add a field with item index. It would the easier.

**Comment by mahendaraReddy** [comment]
Hi tabalinas
for case in-sensitive search i written like this.

loadData: function(filter) {

return $.grep(this.items, function(items) {

return (items.customername.toLowerCase().indexOf(filter.customername.toLowerCase()) > -1);
});
},

is there any effects with this code.
