### ISSUE TITLE
How to change field type based on the name of another field.

### ISSUE THREAD

**Issue by bmaljai** [tabalinas/jsgrid#801]
I have a question about configuring the jsgrid.

I have two fields:
{ name: "sField", type: "text"},
{ name: "sValue", type: x}

I want the field type of sValue to change depending on the sField value on a given row.

so if data:
[
{"sField":"id", "sValue":1234},
{"sField":"name","sValue":"abcdef"}
]

then I would want the row that has an sField of "ID" to have type: "number"
but for sField of "name", I would want a type: "text".
I'd like to use this for select, and some custom fields as well.

**Comment by tabalinas** [comment]
`type` config property takes place for entire grid column. 
To combine several fields, you have to define custom field combining two fields and rendering a control depending on another field value.
