### ISSUE TITLE
Request: Column spans

### ISSUE THREAD

**Issue by bradybray** [tabalinas/jsgrid#803]
Does jsGrid have the ability to create a column span for similar column sets?

**Comment by tabalinas** [comment]
Not sure what you mean by "column span for similar column sets". Could you provide more info and/or a screenshot?

**Comment by bradybray** [comment]
https://www.w3schools.com/tags/tryit.asp?filename=tryhtml_td_colspan

Would I want to look in to custom renderer?

**Comment by tabalinas** [comment]
Yes, custom `rowRenderer` should do the trick.

**Comment by bradybray** [comment]
@tabalinas I have a concern. Lets say I create a custom renderer using rowRender. I create a simple table say... `<table><th>blah...</th><tr><td>data...</td></tr></table> and append this to the data grid. Will the table header be rendered onto each row of data? What I mean is will each row have its own header? I only need a single header for this particular task. 

If this is true then does the rowRenderer not support the functions I need? And if that is also true what other options do I have to customize a tables headers?


Thank you for your help;

Braden.

**Comment by tabalinas** [comment]
With `rowRederer` you will render a `<tr>` with cells inside (not yet another table). 
Regarding header it's up to you: you can keep it, or if you need colspan or any fancy logic, go for `headerRowRenderer`.

**Comment by bradybray** [comment]
@tabalinas So by using the custom renderers do I lose the common controls used to edit, delete rules?

**Comment by tabalinas** [comment]
@bradybray, nothing prevents you from calling `itemTemplate` method of the `control` field in your custom rowRenderer.
