### ISSUE TITLE
Sorting Version Numbers

### ISSUE THREAD

**Issue by mgyatso** [tabalinas/jsgrid#805]
Via the 'controller' and its 'loadData' function I am populating a grid with Product Names and their Version Numbers from a database. Some Version Numbers are basic (ex: 2, 11) and some use semantic versioning where the numbers contain decimals (1.2, 11.0.3, 12.0).

Added to the grid with:

```
{
     title: "Version",
     name: "product_version",
     type: "text",
     align: "left",
     width: "10%"
},
```

Do you happen the have a solution that enables me to sort ASC or DESC on these numbers?

**Comment by tabalinas** [comment]
Define custom sorter. The sorter implementation is up to you. You could look at this one for instance https://stackoverflow.com/questions/6832596/how-to-compare-software-version-number-using-js-only-number
