### ISSUE TITLE
How to load json object

### ISSUE THREAD

**Issue by zerozerofat** [tabalinas/jsgrid#807]
1、server return json object as below ,jsgrid how to parse the data.
{"code":0,"res":null,"id":null,"msg":null,
"data":[
{"id":1,"descName":"计算机网络","descCode":"PRO2017050800004"},
{"id":3,"descName":"测绘","descCode":"PRO2017053100039"},
{"id":4,"descName":"工商管理","descCode":"PRO2017060400041"},
{"id":5,"descName":"计算机程序设计","descCode":"PRO2017061500044"}
]}

**Comment by tabalinas** [comment]
You don't need to parse it. In `loadData` method fetch data and resolve retuned promise  with `result.data`, something like:

```js
loadData: function() {
    return $.ajax(/* ajax request config */).then(function(result) {
        return result.data;
    });
}
```
