### ISSUE TITLE
Update pagination realtime with SignalR

### ISSUE THREAD

**Issue by ragerory** [tabalinas/jsgrid#808]
Hi,

We are using SignalR to update our screen from database events. When we get an update or an insert, signalR is notified, and it updates the data that jsGrid is using and all is well.

When SignalR is done updating the dataset, we call:

$("#jsGrid").jsGrid("loadData");

And the grid renders the changes.

However, something we just noticed when doing more inserts, is the pagination doesn't update. 

Scenario: 
1. We have page sizes of 20, and are currently showing 4 pages. 
2. The last page has 17 records displayed. 
3. We do 4 inserts into the database, so loadData is called 4 times. 
4. We see the first 3 inserts get added in real time, but do not see the 4th. 
5. The page count still shows 4 pages. 
6. When we refresh the browser, that is when we see the 5th page with the last item. 

Is there something special we need to do to have the pagination updated as well? I thought that loadData would have done that, but I guess it doesn't actually rerender the grid. 

For what it's worth, the way it currently works is what we want (the user isn't taken off of the current page and the screen doesn't refresh). We just want the pagination to update in real time also.

Thanks in advance.

**Comment by tabalinas** [comment]
It also depends on the paging strategy you use.
If you don't use loading by pages (`pageLoading: false`) then `loadData` at the end sets option `data`, which calls `refresh`. `refresh` calls `_refreshPager` (https://github.com/tabalinas/jsgrid/blob/master/src/jsgrid.core.js#L788) which should update the paging. So in theory it should just work.

Could you provide an example or somehow demonstrate the problem?

**Comment by ragerory** [comment]
So, we are setting up the grid like this...
`$("#smGrid").jsGrid({
    width: "100%",
  /*  height: "700px", */
    filtering: false,
    inserting: false,
    editing: false,
    sorting: true,
    autoload: true,
    controller: smController,
    rownumbers: true,
    rowClick: function () { },
    paging: true,
    pageSize: 17,

   // set fields...

});`

Then when we get and update or an insert, signalR will do this...

`$(function() {
    var recordManagement = $.connection.recordManagementHub;

    // Functions that the hub or observer can call to broadcast messages.
    RecordManagement.client.receiveUpdates = function(result) {
        var resultObject = JSON.parse(result);
        var updatedRecord = resultObject.RecordManagement.UpdatedRecord;
        var objIndex = findWithAttr(srmData, "SerialNumber", updatedRecord.SerialNumber, "CycleID", updatedRecord.CycleID);

        if (objIndex > -1) {
            srmData[objIndex] = updatedRecord;
        } else {
            srmData.unshift(updatedRecord);
        }

        $("#smGrid").jsGrid("loadData");
    };

    // Start the connection.
    $.connection.hub.start();
});`

If I have no records, the grid has no paging controls, which is expected. When I run 18 inserts, I see each row get added but still no paging controls. I hit F5, and the page controls then show with the 18th record on the second page. I was hoping that when I hit the 18th insert, it would then also show paging controls.

**Comment by tabalinas** [comment]
Looking at sources, I don't see why it could work incorrectly.

Since I don't have a chance to debug try to call `refresh` method on the grid (directly calling it in DevTools or add a temp button for it) to be sure paging updates when you invoke it.

If it updates correctly, then probably you redefined some grid internal the way that `refresh` is not called when grid data has been changed (https://github.com/tabalinas/jsgrid/blob/master/src/jsgrid.core.js#L337).

If it doesn't then there is something fishy with the `refresh` method itself (https://github.com/tabalinas/jsgrid/blob/master/src/jsgrid.core.js#L556).
