### ISSUE TITLE
how get value of input.

### ISSUE THREAD

**Issue by lhuacacolqui** [tabalinas/jsgrid#809]
![image](https://user-images.githubusercontent.com/27408200/27346321-67c93076-55b2-11e7-91d1-deb77537c958.png)

After

![image](https://user-images.githubusercontent.com/27408200/27346354-8a324e68-55b2-11e7-92b0-1dab98f7c699.png)

**Comment by tabalinas** [comment]
You should define `insertValue` for your grid field. Have you followed the custom field sample in the docs http://js-grid.com/docs/#custom-field?

**Comment by lhuacacolqui** [comment]
Yes, but I can not change the date format dd.mm.yyyy
this is the code:
![image](https://user-images.githubusercontent.com/27408200/27515380-97d79a92-5967-11e7-8b8d-c4422bc5bd9e.png)

**Comment by tabalinas** [comment]
I guess then this question is more about datepicker. 
This is the answer probably https://stackoverflow.com/questions/1328025/jquery-ui-datepicker-change-date-format?
