### ISSUE TITLE
Pagination not restricting table view to browser window

### ISSUE THREAD

**Issue by philCryoport** [tabalinas/jsgrid#810]
Bug Reports:
    A) Expected Behavior
With pagination set to true, expect display of table to fit within browser window, including header row, pagination row, etc.

    B) Actual Behavior
Chromium 57 and Firefox 54 on Windows 10 both display a table that takes several page-scrolls to view the entire "page" of data.  I have a UHD 4K display (3820 x 2160).  Whether my browser window fills my entire 4K screen or I've sized my browser window to only be 1/2 the height of my screen (the equivalent of 1920x1080), the "page" of data fills a height of the equivalent of something like 3820x6480.

    C) Steps to Reproduce

1. Download really large row-quantity data set (I'm receiving ~15,000 rows). 
1. Call jsGrid with the following settings:
```
$("#dataTable").jsGrid({
                paging: true,
                data: data,
                fields: fieldList
            });
```

**Comment by tabalinas** [comment]
The height of the grid depends on the css styles layouting your page. You can define `height` property of the grid in percents or pixels. So it's up to your css and `height` property to define the height of the grid.
For loading big amount of data the good practice would be using `pageLoading: true`, to load data by pages.
