### ISSUE TITLE
Create autocomplete field on "row level"

### ISSUE THREAD

**Issue by hurtonypeter** [tabalinas/jsgrid#811]
Hi, 

I'd like to create an autocomplete field, that can search in the database and if you select an item, that fills up the whole line. For example I have a Person class

```js
class Person {
   Id: number;
   Name: string;
   Age: number;
   ...etc.
}
```

We could add persons to a list with a grid. Basically, as an user you could create new persons by entering new name (and other values), but if you type in a name that already exists in the database, you can select that from the autocomplete dropdown list. This would fill up the remaining input fields and make them disabled.

I got here so far:
```js
insertTemplate: function () {
	if (!this.inserting)
		return "";

	var $el = this.insertControl = this._createTextBox();

	var config = $.extend({
		minLength: 3
	}, this.autocompleteConfig);

	$el.autocomplete(config)
		.autocomplete("instance")._renderItem = function (ul, item) {
			return $("<li>")
				.append("<a>" + item.value + "</a>")
				.appendTo(ul);
		};

	return this.insertControl;
}
```
When you initialize the fields of the grid:

```js
[
	{
		name: "Id",
		css: "hidden"
	},
	{
		name: "Name",
		title: "Name",
		type: "autocomplete",
		autocompleteConfig: {
			source: '/Ajanlatkero/KozbeszerzesiEljarasInditasa/SzervezetAutocomplete',
			select: function (event, ui) {
				// the ui variable has all the information to fill out the fields
                                // TODO: fill out the editor row, make the fields disabled
			}
		}

	},
	{
		name: "Age",
		title: "Age",
		type: "number"
	},
	...etc
]
```

The problem is: how can I access to the other editor fields?

**Comment by tabalinas** [comment]
Each editor saves the reference to the editing control (just like it's done in your example with `this.insertControl`). You can access fields of the grid reading `fields` option, something like:
 `$("#jsGrid").jsGrid("option", "fields")[0].insertControl.val()`
