### ISSUE TITLE
Question: Concat string for the textField in a column with type "select"

### ISSUE THREAD

**Issue by NewBo1234** [tabalinas/jsgrid#812]
3. Help Request/Question

I have a JsGrid that displays several columns of type "select" and they work fine.  However, I have one select that I need to concat several fields for the textField display only.  

My database table separates the pieces for indexing and searching purposes into 3 columns.  I'd like to display the three columns like this in the textField:

"col1 - col2 - col3"

Could you please let me know how to do this?

Thank you.

**Comment by tabalinas** [comment]
The second parameter of the field's `itemTemplate(value, item)` is the item. 
You can access all item fields and display whatever needed in a single field.
