### ISSUE TITLE
Sorting not working with ajax call for loadData

### ISSUE THREAD

**Issue by lmcadory** [tabalinas/jsgrid#813]
I need some help understanding loadData. I'm pulling in data via an ajax call. I have no problem loading the data into the grid. I'm having issues sorting the data.

My ajax call looks like:
 
```javascript
$.ajax({
    url: loadUrl, //variable because the url changes
    type: 'GET',
    dataType: 'json',
  }).done(function (response) {
    var startIndex = (filter.pageIndex -1) * filter.pageSize;
    d.resolve({
       data: response.slice(startIndex, startIndex + filter.pageSize),
       itemsCount: response.legnth
   });
})
```
I can see what's happening. The url for the GET response is being called when I click the header, the filter parameter is updated to include sortField and sortOrder, also the response is returned from the backend unsorted. Am I supposed to handle filtering inside the done call? I assumed sorting happened auto-magically in the client. If I have to handle sorting when the response comes back how would I handle custom sorts?

**Comment by lmcadory** [comment]
Nevermind. I read the documentation closer and see since I have pageLoading set to true grid.loadData is called. So the server needs to handle sorting.

**Comment by tabalinas** [comment]
Glad that you figured it out.
