### ISSUE TITLE
loadData argument cannot filter a column named "pageIndex"

### ISSUE THREAD

**Issue by davehayes** [tabalinas/jsgrid#818]
I believe this is a bug report, but it comes from looking at your documentation and I haven't actually seen this happen. 

What if you are using a custom controller function for loadData(), you are paging, and you have a column named 'pageIndex', 'pageSize', 'sortField', or 'sortOrder' and you want to filter on it? If I read your documentation correctly, you cannot ever filter on these fields. :)

**Comment by tabalinas** [comment]
Yes, this is correct. It doesn't mean you cannot use this naming on the server-side. But you will have to remap it on client-side to avoid names clashing.

**Comment by davehayes** [comment]
Isn't this easily fixable by declaring a new parameter 'filterObject' (or whatever) and using that to filter fields?

**Comment by tabalinas** [comment]
It can be done, but this will be a Breaking Change.
