### ISSUE TITLE
Rows grouping possible?

### ISSUE THREAD

**Issue by shamil177** [tabalinas/jsgrid#819]
Hi there!
Great component, but I have one quick question: Is it possible to group rows like in the following example [here](http://khan4019.github.io/tree-grid-directive/test/treeGrid.html)?

Regards,
Shamil

**Comment by shamil177** [comment]
Figured it out. Thanks!

**Comment by topo79** [comment]
@shamil177  How can you please provide some code. TY

**Comment by shamil177** [comment]
Hi topo79,

I've used this as to start with: https://github.com/tabalinas/jsgrid/issues/223 

Cheers,
Shamil
