### ISSUE TITLE
Adding and removing fields 

### ISSUE THREAD

**Issue by AlbertServen** [tabalinas/jsgrid#82]
Is there a way to remove and add fields in the header without refreshing the grid (calling `loadData`)?

Thanks.

**Comment by tabalinas** [comment]
By 'fields' you mean rows? If yes, then the answer is yes. You need to redefine loadStrategy (it's not documented yet, docs will be added soon). 
See following tickets https://github.com/tabalinas/jsgrid/issues/43, https://github.com/tabalinas/jsgrid/issues/50, https://github.com/tabalinas/jsgrid/issues/54

**Comment by AlbertServen** [comment]
No, I mean columns, to show and hide without making a post call. Sorry if I explained it wrong.

**Comment by tabalinas** [comment]
Oh, I see now. Then try the following: call `render` method and turn off `autoload`. In this case you should call `loadData` yourself.

**Comment by AlbertServen** [comment]
This is what I'm doing and it seems to work:
```javascript
grid.jsGrid('option', 'autoload', false);
grid.jsGrid('option', 'fields', fieldsToShow);
grid.jsGrid('refresh');
```
Thank you for the help.

**Comment by tabalinas** [comment]
You are welcome! Glad that it helped. 
Note: you can set `autoload: false` in the grid config or even set it as the default option for all the grids on the page.
