### ISSUE TITLE
Select box not showing value when inserted

### ISSUE THREAD

**Issue by StealthRT** [tabalinas/jsgrid#821]
Hey there @tabalinas I am having an issue with the select type when inserting item into the table.

Below is a **GIF animation** showing me adding the data to the table (and that it **doesnt show the 5 dropdown values** when rendered) but **does** show the **normal "text" boxes** if they have data (seen in the animation as "**blah blah**").
![20170629_113639](https://user-images.githubusercontent.com/1037844/27696781-85c27974-5cc0-11e7-82a8-714fda5679f9.gif)

The json I am passing the **dropdown box items** that I select the values for **SM Type** looks like this:
`[
    {
      "id": 1,
      "name": "SW"
    },
    {
      "id": 2,
      "name": "HW"
    }
]`

And my **Fields** value for that example is:
![screen shot 06-29-17 at 11 52 am](https://user-images.githubusercontent.com/1037844/27697342-edecd98a-5cc1-11e7-97f9-fb495b3aa1f6.PNG)

I've tried to add the properties value of **"valueType", "text"** as it's coming in as a **Int** but even adding that does not work when inserting it into the table.

It only shows once I **click on the row** to **edit it** and **click on the green check mark**. After that it shows the dropdown values as it should.

My overall javascript code to start the jsGrid is this (**NOTE**: I have not changed the 'filter' section of the code as I am not at that point yet):
```js
//Set up jsgrid
            var db = {
                loadData: function (filter) {
                    return $.grep(this.clients, function (client) {
                        return (!filter.Name || client.Name.indexOf(filter.Name) > -1)
                            && (!filter.Age || client.Age === filter.Age)
                            && (!filter.Address || client.Address.indexOf(filter.Address) > -1)
                            && (!filter.Country || client.Country === filter.Country)
                            && (filter.Married === undefined || client.Married === filter.Married);
                    });
                },
                insertItem: function (insertingClient) {
                    console.log('insertItem');
                    this.clients.push(insertingClient);
                },
                updateItem: function (updatingClient) {
                    console.log('updateItem');
                },
                deleteItem: function (deletingClient) {
                    console.log('deleteItem');
                    var clientIndex = $.inArray(deletingClient, this.clients);
                    this.clients.splice(clientIndex, 1);
                }
            };

            window.db = db;

            $(document).ready(function ($) {
                $("#jsGrid").jsGrid({
                    height: "500px",
                    width: "100%",
                    onItemDeleted: function (args) {
                        //console.log('onItemDeleted', args);
                    },
                    onItemUpdated: function (args) {
                        //console.log('onItemUpdated', args);
                    },
                    onItemInserted: function (args) {
                        //console.log('onItemUpdated', args);
                        //console.log('onItemUpdated', args.item);

                        $.each(args.item, function (index, value) {
                            console.log('index: ' + index + ' value: ' + value);
                        });
                                                
                        $.ajax({
                            type: 'POST',
                            url: 'saveInsert',
                            cache: false,
                            dataType: 'json',
                            data: {
                                bomdata: args.item
                            },
                            success: function (response) {
                                //$("#jsGrid").jsGrid("updateItem");
                            },
                            error: function (response) {
                                console.log(response);
                            }
                        });
                    },
                    onInit: function (args) {
                        //console.log('onItemUpdated', args)
                    },
                    onDataLoaded: function (args) {
                        //console.log('onDataLoaded', args)
                    },
                    editValue: function () {
                        //console.log('editValue')
                    },
                    paging: true,
                    autoload: true,
                    pageIndex: 1,
                    pageSize: 20,
                    confirmDeleting: false,
                    pageButtonCount: 5,
                    pagerFormat: "Pages {pageIndex} of {pageCount} : {pages}",
                    pagerContainer: "#externalPager",
                    noDataContent: "Nothing to display...",
                    loadShading: true,
                    inserting: true,
                    editing: true,
                    sorting: true,
                    paging: true,
                    filtering: false,
                    fields: response.Fields
                });
            });
```

Can you provide me some code that will allow me to **programmatically click** on the **inserted row** and **click the check mark** so that it will show up?

**Comment by tabalinas** [comment]
Are you sure a data item that you are adding on "Add Item" button has a field with the same name as your `select` field and its value has integer datatype?

**Comment by kelmore5** [comment]
Hey @tabalinas, I was going to post this in a question, but saw this already opened. I'm going to wait to see what @StealthRT responds with, but I had another question.

I see that if cell data in the grid doesn't exactly match the select value, it won't display the value, but why is that? Is there a way for the column to display the value regardless if it's in the select or not?

Thanks! Best of luck to StealthRT

**Comment by StealthRT** [comment]
This is how i am currently getting it to display all the select results.
`onItemInserted: function (args) {
                        //Hacky way of making the dropdown values show without user needing to edit it first
                        $("input[title='Edit']").each(function (index, el) {
                            $.when($(el).triggerHandler('click')).done(function () {
                                $("input[title='Update']").trigger('click');
                            });
                        });
                    },`
