### ISSUE TITLE
UpdateItem not called with readonly field

### ISSUE THREAD

**Issue by myoustal** [tabalinas/jsgrid#825]
I am new to the grid, I noticed the Controller updateItem function is not called when updating a grid row with a readonly field. The readonly field is created as follows:
{ name: "Firm",           type: "text",  width: 100, validate: "required",
 editTemplate: function(value, item) {
                  return value; }
}
Failure is in jsGrid.min.js editValue: function() line 1357. Function fails with editControl undefined. This does not happen when no readonly fields exist in row. Any feedback appreciated.

**Comment by tabalinas** [comment]
The property `readonly` doesn't mean you can eliminate editing control itself. This means this control will be in readonly state (the control, but not the cell). If you want to turn off editing for a cell, set `editing: false`. Of just don't use `type: "text"` (don't specify any type and you will get text cell).

**Comment by myoustal** [comment]
ok, got it! Thanks for your quick reply.
