### ISSUE TITLE
jsGrid to open to a tree control?

### ISSUE THREAD

**Issue by NewBo1234** [tabalinas/jsgrid#826]
3.) Help request

Good afternoon,

I was wondering if anyone had tried to attach a tree object to a field in the jsgrid?  My ideal would be to click on the field and have a tree object drop down like it does with the example Date grid.

Just wondering if anyone else had done it.

Thanks.

**Comment by tabalinas** [comment]
Looks like nobody tried it yet. You could be the first one who tried it. It could be built with http://travistidwell.com/jquery.treeselect.js/ for instance.
