### ISSUE TITLE
Safari jsGrid Height

### ISSUE THREAD

**Issue by leonardolb560** [tabalinas/jsgrid#827]
Issue with grid running in safari or mobile devices

Issue: jsGrid with height 100% does not render correctly in safari or any mobile OS. It keeps with height 20px
 
You can see that in the pic above. I have 8 pages of data but grid height does not respect 100%. It works fine in google Chrome

![image](https://user-images.githubusercontent.com/20689140/27846334-e1bfbafc-610c-11e7-9682-d47f1c4aca00.png)

**Comment by tabalinas** [comment]
All what `height: "100%"` does is it sets css height of the container to 100%. If it's displayed incorrectly, it should be solved with css of the particular page using the grid. 
Answer to a similar problem: https://github.com/tabalinas/jsgrid/issues/41#issuecomment-110103861
