### ISSUE TITLE
Event triggered before the insert row is displayed?

### ISSUE THREAD

**Issue by NewBo1234** [tabalinas/jsgrid#828]
Help/Question

Is there an event triggered or something for before the insert row is displayed?  The onItemInserting and onItemInserted are triggered by the green plus, rather than when the insert row is displayed.

Thanks!

**Comment by tabalinas** [comment]
`onItemInserting` and `onItemInserted` has nothing to do with "the green plus". They called before and after `controller.insertItem` call, which is triggered by `insertItem` method of the grid.
Insert row is shown when `inserting` option of the grid is set to `true`. Each time it happens `onOptionChanging` callback is triggered before http://js-grid.com/docs/#onoptionchanging.
