### ISSUE TITLE
grid controls for custom render

### ISSUE THREAD

**Issue by bradybray** [tabalinas/jsgrid#829]
Hi Guys;

First let me thank @tabalinas and @richraid21 for all their help. I'm really grateful you guys have been there to answer my questions about this project. :)

I recently implemented the custom render. And it looks great. However, I lost all the controls provided by the default theme and layout. This includes items like sorting... and the like. Even edit and delete buttons. 

How may I get those back?

Braden.

**Comment by tabalinas** [comment]
Do you have a jsfiddle or any other public resource demonstrating the issue?
