### ISSUE TITLE
problem with update

### ISSUE THREAD

**Issue by acercandroc** [tabalinas/jsgrid#83]
Good evening, I adapted my way, for what I needed, I am using database updating using double click, the problem that I have is that only updated once, when wanting to update another row, throwing error does not take the form data, "TypeError Error: updatingClient is null" thanks for the help.

**Comment by tabalinas** [comment]
Could you provide your code? Or a jsfiddle to demonsrate the problem?

**Comment by acercandroc** [comment]
Good night, of course.
I implemented all in MVC pattern, the problem is that updates and deletes
well, but finally I try to add a record this is taken as if to remove,
always take the previous selection, if I want to eliminate, eliminate, but
often want to add send to remove, if refresh the page and add a record and
then want to remove, do not, but sent to save
thanks.




Alejandro Corredor Parra
*Analista-Desarrollador*
313 340 94 42

2015-08-09 1:37 GMT-05:00 Artem Tabalin <notifications@github.com>:

> Could you provide your code? Or a jsfiddle to demonsrate the problem?
>
> —
> Reply to this email directly or view it on GitHub.
>

-- 
 



*Declinación de Responsabilidades:* Los servicios de MISENA son soportados 
tecnológicamente por © Google y ofrecidos por el Servicio Nacional de 
Aprendizaje – SENA de manera gratuita a los aprendices e instructores de 
programas de formación titulada, las opiniones que contenga este mensaje 
son exclusivas de su autor y no representan la opinión del Servicio 
Nacional de Aprendizaje o de sus autoridades. El receptor deberá verificar 
posibles virus informáticos que tenga el correo o cualquier anexo, razón 
por la cual el SENA no es responsable de los daños causados por cualquier 
virus transmitido en este correo electrónico.

Los contenidos, textos, imágenes, archivos enviados en este mensaje son 
responsabilidad exclusiva del remitente y no reflejan ni comprometen de 
ninguna manera a la institución. No se autoriza el uso de esta herramienta 
para el intercambio de correos masivos, cadenas o spam, ni de mensajes 
ofensivos, de carácter político, sexual o religioso, con fines de lucro, 
con propósitos delictivos o cualquier otro mensaje que se considere 
indebido o que vaya en contra de la Ley.

-- phpMyAdmin SQL Dump
-- version 4.2.11
-- http://www.phpmyadmin.net
--
-- Servidor: 127.0.0.1
-- Tiempo de generación: 10-08-2015 a las 06:51:11
-- Versión del servidor: 5.6.21
-- Versión de PHP: 5.6.3

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

--
-- Base de datos: `jsgrid`
--

-- --------------------------------------------------------

--
-- Estructura de tabla para la tabla `perfil`
--

CREATE TABLE IF NOT EXISTS `perfil` (
`id` int(11) NOT NULL,
  `nombrePerfil` varchar(45) COLLATE utf8_spanish_ci NOT NULL
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8 COLLATE=utf8_spanish_ci;

--
-- Volcado de datos para la tabla `perfil`
--

INSERT INTO `perfil` (`id`, `nombrePerfil`) VALUES
(1, 'administrador'),
(2, 'usuario');

-- --------------------------------------------------------

--
-- Estructura de tabla para la tabla `usuarios`
--

CREATE TABLE IF NOT EXISTS `usuarios` (
`id_usuario` int(100) NOT NULL,
  `nombres` varchar(100) NOT NULL,
  `apellidos` varchar(100) NOT NULL,
  `documento` varchar(45) NOT NULL,
  `usuario` varchar(100) DEFAULT NULL,
  `contrasena` varchar(100) DEFAULT NULL,
  `edad` varchar(100) NOT NULL,
  `perfil` int(11) NOT NULL
) ENGINE=InnoDB AUTO_INCREMENT=185 DEFAULT CHARSET=utf8;

--
-- Volcado de datos para la tabla `usuarios`
--

INSERT INTO `usuarios` (`id_usuario`, `nombres`, `apellidos`, `documento`, `usuario`, `contrasena`, `edad`, `perfil`) VALUES
(184, 'fdsdfg', 'sdf', '345345', NULL, NULL, '44', 1);

--
-- Índices para tablas volcadas
--

--
-- Indices de la tabla `perfil`
--
ALTER TABLE `perfil`
 ADD PRIMARY KEY (`id`);

--
-- Indices de la tabla `usuarios`
--
ALTER TABLE `usuarios`
 ADD PRIMARY KEY (`id_usuario`), ADD KEY `idPerfil_idx` (`perfil`);

--
-- AUTO_INCREMENT de las tablas volcadas
--

--
-- AUTO_INCREMENT de la tabla `perfil`
--
ALTER TABLE `perfil`
MODIFY `id` int(11) NOT NULL AUTO_INCREMENT,AUTO_INCREMENT=3;
--
-- AUTO_INCREMENT de la tabla `usuarios`
--
ALTER TABLE `usuarios`
MODIFY `id_usuario` int(100) NOT NULL AUTO_INCREMENT,AUTO_INCREMENT=185;
--
-- Restricciones para tablas volcadas
--

--
-- Filtros para la tabla `usuarios`
--
ALTER TABLE `usuarios`
ADD CONSTRAINT `idPerfil` FOREIGN KEY (`perfil`) REFERENCES `perfil` (`id`) ON DELETE CASCADE ON UPDATE CASCADE;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;

**Comment by acercandroc** [comment]
window.onload=function(){
      cargaSelect();
     cargaDatos();
    
    };
    function cargaSelect(){
         var parametros = {opcion: 11};
    $.post(
            "Controlador/controladorCarga.php",
            parametros, selectPerfil,
            "json"
            ); 
    }

    function selectPerfil(datos){
        console.log("llega select");
        console.log(datos);
        if(datos !== null){
            
            var i, option, select;
            
            select = document.getElementById("perfil");
            
            for(i=0 ; i<datos.length ; i++){
                option = document.createElement("option");
                option.value = datos[i].id;
                option.textContent = datos[i].nombrePerfil;
                select.appendChild(option);
            }
            
        }
        
    }
function cargaDatos(){
    
        var parametros = {opcion: 7};
    $.post(
            "Controlador/controladorCarga.php",
            parametros, personas,
            "json"
            );

}    


    function personas(datos) {
            console.log("llega grid");
        console.log(datos);
    var db = {
        loadData: function (filter) {
            return $.grep(datos, function (client) {

                return(!filter.id_usuario || client.id_usuario === filter.id_usuario) &&
                        (!filter.apellidos || client.apellidos === filter.apellidos)
                        && (!filter.documento || client.documento === filter.documento)
                        && (!filter.edad || client.edad === filter.edad)
                        && (!filter.nombres || client.nombres === filter.nombres)
                        && (!filter.perfil || client.perfil === filter.perfil);
            });
        },
        insertItem: function (insertingClient) {
            console.log(insertingClient);

            console.log("llega insertar");
            var parametros = {
                opcion: 8,
                nombres: insertingClient.Nombres,
                apellidos: insertingClient.Apellidos,
                documento: insertingClient.Documento,
                edad: insertingClient.Edad,
                perfil: insertingClient.Perfil
            };
            $.post(
                    "Controlador/controladorCarga.php",
                    parametros,  cargaDatos
                    );
        },
        updateItem: function (updatingClient) {
            console.log(updatingClient.id);

            console.log("llega actualizar");
            var parametros = {
                opcion: 9,
                id: updatingClient.id,
                nombres: updatingClient.Nombres,
                apellidos: updatingClient.Apellidos,
                documento: updatingClient.Documento,
                edad: updatingClient.Edad,
                perfil: updatingClient.Perfil
            };
            $.post(
                    "Controlador/controladorCarga.php",
                    parametros, cargaDatos
                    );
        },
        deleteItem: function (deletingClient) {
            console.log(deletingClient);
// borrar, toma los dats desde la misma consulta, no desde el formulario
            console.log("llega eliminar");
            var parametros = {
                opcion: 10,
                id: deletingClient.id_usuario
            };
            $.post(
                    "Controlador/controladorCarga.php",
                    parametros, cargaDatos
                    );
            
            console.log(parametros);
        }

    };
    // toma el id del div q desea cargar el grid
            $("#jsGrid").jsGrid({
                height: "100%",
                width: "100%",
                filtering: true,
                editing: false,
                sorting: true,
                autoload: true,
                paging: true,
                pageSize: 15,
                pageButtonCount: 5,
                updateOnResize: true,
                noDataContent:  "No se encuentra",
                deleteConfirm: function(item) {
                    return "el esuario \"" + item.nombres + "\" será eliminado. Está seguro?";
                },
                rowDoubleClick: function(args) {
                    showDetailsDialog("Edit", args.item);
                },
                controller: db,
                fields: [{
                    headerTemplate: function() {
                            return $("<button>").attr("type", "button").text("Delete")
                                    .on("click", function () {
                                        deleteSelectedItems();
                                    });
                        }
                    ,
                        itemTemplate: function(_, item) {
                            return $("<input>").attr("type", "checkbox")
                                    .on("change", function () {
                                        $(this).is(":checked") ? selectItem(item) : unselectItem(item);
                                    });
                        },
                        align: "center",
                        width: 50
                    
                    },
                    { title: "Apellidos", name: "apellidos",type: "text", width:'auto' },
                    { title: "Documento", name: "documento", type: "text", width:'auto' },
                    { title: "Edad", name: "edad", type: "text", width:'auto'},
                    { title: "Nombres", name: "nombres", type: "text", width:'auto'},
                    { title: "Perfil", name: "perfil", type: "text", width:'auto' },
                    {
                        type: "control",
                        modeSwitchButton: false,
                        editButton: false,
                        headerTemplate: function() {
                            // a oprimir add , abre el popup con el formulario
                            return $("<button>").attr("type", "button").text("Add")
                                .on("click", function () {
                                    showDetailsDialog("Add", {});
                                });
                        }
                    }
                ]
                
            });

// dispara el dialog con el formulario dentro
            $("#detailsDialog").dialog({
                autoOpen: false,
                width: 400,
                close: function() {
                    // toma los datos q vienen dentro del form en el dialog
                    // y valida q no vaya vacio
                    $("#detailsForm").validate().resetForm();
                    $("#detailsForm").find(".error").removeClass("error");
                }
            });

            $("#detailsForm").validate({
                rules: {
                    nombres: "required",
                    apellidos: "required",
                    documento: "required",
                    edad: "required",
                    perfil: "required"
                },
                messages: {
                    nombres: "Please enter name",
                    apellidos: "Please enter valid age",
                    documento: "Please enter address (more than 10 chars)",
                    edad: "Please enter your age",
                    perfil: "Please enter your rol"
                },
                submitHandler: function() {
                    formSubmitHandler();
                }
            });

            var formSubmitHandler = $.noop;

            var showDetailsDialog = function(dialogType, client) {
                
                $("#id").val(client.id_usuario);
                $("#apellidos").val(client.apellidos);
                $("#documento").val(client.documento);
                $("#edad").val(client.edad);
                $("#nombres").val(client.nombres);
                $("#perfil").val(client.perfil);

                formSubmitHandler = function() {
                    saveClient(client, dialogType === "Add");
                };

                $("#detailsDialog").dialog("option", "title", dialogType + " Client")
                    .dialog("open");
            };

            var saveClient = function(client, isNew) {
                $.extend(client, {
                    id: $("#id").val(),
                    Nombres: $("#nombres").val(),
                    Apellidos: $("#apellidos").val(),
                    Documento: $("#documento").val(),
                    Edad: $("#edad").val(),
                    Perfil: $("#perfil").val()
                });
                $("#jsGrid").jsGrid(isNew ? "insertItem" : "updateItem" , client);

                $("#detailsDialog").dialog("close");
            };
            
            ///////borrar masivo con checkbox ?
                  var selectedItems = [];

            var selectItem = function(item) {
                selectedItems.push(item);
            };

            var unselectItem = function(item) {
                selectedItems = $.grep(selectedItems, function(i) {
                    return i !== item;
                });
            };

            var deleteSelectedItems = function() {
                if(!selectedItems.length || !confirm("Are you sure?"))
                    return;

                var $grid = $("#jsGrid");

                $.each(selectedItems, function(_, item) {
                    $grid.jsGrid("deleteItem", item);
                });

                selectedItems = [];
            };
          ///////borrar masivo con checkbox ?
    }

**Comment by tabalinas** [comment]
Grid controller `updateItem`, `insertItem`, and `deleteItem` methods should return jQuery.Promise for the async requests. In your case you should add `return` before `$.post` methods.

**Comment by acercandroc** [comment]
well ?
 insertItem: function (insertingClient) {

            var parametros = {
                opcion: 8,
                nombres: insertingClient.Nombres,
                apellidos: insertingClient.Apellidos,
                documento: insertingClient.Documento,
                edad: insertingClient.Edad,
                perfil: insertingClient.Perfil
            };
            return;
            $.post( "Controlador/controladorCarga.php", parametros,  cargaDatos );
        }

**Comment by tabalinas** [comment]
Nope, you should return the result of `$.post` (it returns promise). In you code you return before sending the request.

**Comment by acercandroc** [comment]
sorry, i don't understand
well?
? así 
insertItem: function (insertingClient) {

        Parámetros var = {
            opcion: 8,
            Nombres: insertingClient.Nombres,
            Apellidos: insertingClient.Apellidos,
            Documento: insertingClient.Documento,
            Edad: insertingClient.Edad,
            Perfil: insertingClient.Perfil
        };
      
        var result = $ .post ("Controlador / controladorCarga.php", parametros, cargaDatos);
return result;
    }

**Comment by tabalinas** [comment]
Yes, it's ok. Do you still have problem with your case after this change?

**Comment by acercandroc** [comment]
the problem remains the same :(

**Comment by tabalinas** [comment]
Try to modify the fiddle to demonstrate the problem http://jsfiddle.net/tabalinas/zzzfmpgt/
To emulate async post requests you can use setTimeout (or just do it all synchronously).

**Comment by acercandroc** [comment]
the problem is not the requests, the problem is that the order update, delete and update should not go where

**Comment by acercandroc** [comment]
that otherwise could submit? otherwise than as formSubmitHandler

**Comment by tabalinas** [comment]
Frankly, don't get what you mean. The problem you faced is not clear, that's why I need a fiddle to see the problem.

**Comment by acercandroc** [comment]
I had to leave the add button. to update I use clicking on the field, so as not make me conflict between options, was the only way, but now I have another concern, is there any way that you enable update by double clicking on the cell and not a single click?

**Comment by acercandroc** [comment]
it is very unstable. he is set to do certain action and unconfigures or otherwise....

**Comment by tabalinas** [comment]
Regarding editing on double click, yes it's doable. 

You can attach the default `rowClick` handler to `rowDoubleClick` like following:

```javascript
rowClick: $.noop,
rowDoubleClick: jsGrid.Grid.prototype.rowClick,
```

Regarding. other concern I still not able to get what you mean. You need any help, provide an example to see the issue.
