### ISSUE TITLE
How to access a custom field in custom field type

### ISSUE THREAD

**Issue by NewBo1234** [tabalinas/jsgrid#830]
Hey,

I'm not sure if this is a bug or what, but I have a custom field type with a custom field.  The documentation shows that it can be added.  The documentation shows that it can be edited from the page.  But whenever I try to use the value, it says that the variable is not initialized.  I can see how "foo" is in the custom Date field, but there's no following line showing where it is used or how to access it.

Could someone please help me out?
Thanks.

**Comment by NewBo1234** [comment]
Applicable code is found at http://js-grid.com/docs/#custom-field 

Where is "foo" being used?  I can't seem to get a hold of a custom field's value.

**Comment by tabalinas** [comment]
Sorry, if this example confused you. The value `"foo"` is NOT used anywhere. It's just to show that you can define any custom property with any desired value, which can be used at some point if needed (not in this case).

**Comment by NewBo1234** [comment]
Please re-open this question.

When I have a custom field and attempt to access it in the editTemplate and insertTemplate, I get the error that the field is never defined and is null.  Could you please put in a small thing--a console.log or something--that can show how to access this?

**Comment by NewBo1234** [comment]
My example code:

.... boiler plate code eliminated

MyField.prototype = new jsGrid.Field({
     items: ["1", "2", "3"],
     insertTemplate: function(value) {
         alert(items);
     }
});
......

I get a ReferenceError: items is not defined.

**Comment by tabalinas** [comment]
Hm... How `items` could be found? Is it a global variable?
If you are trying to reference `items` from the field object it should be `this.items`, and it has nothing to do with jsGrid, this is JavaScript basics.
