### ISSUE TITLE
Help Request/Question: help with deleteItem

### ISSUE THREAD

**Issue by parisid** [tabalinas/jsgrid#832]
hello, i have a simple issue, i need to insert and delete from external button data in the grid.

first i use:

       	$("#jsGrid").jsGrid("insertItem", { "ID": "A"});

after, with other button i try:

       	$("#jsGrid").jsGrid("deleteItem", { "ID": "A"});

but nothing happens.
I dont'have any error in console, but seems that i "search" the row in a wrong way.

Can anyone help me?, thanks in advance.

**Comment by tabalinas** [comment]
Checkout the docs for `deleteItem` (http://js-grid.com/docs/#deleteitemitemrowrownode-promise).
You can delete rows knowing jQueryElement reference, DonNode reference, or item reference.
You can always find item reading `data` option of the grid and just finding element by ID.
