### ISSUE TITLE
cellRenderer - How do I know which column in the item I am rendering?

### ISSUE THREAD

**Issue by gorch74** [tabalinas/jsgrid#838]
I have a custom rendering function, and I would like to render the cell differently depending on what column it is that I am rendering.  Is there anyway to do this?

```js
function formatCell(value, item){  
    if (if (item[columnName + "_suffix"].value > 0){     
      return $("td>").append(value + '*');  
    }    

    return $("<td>").append(value);
}

```

So in this mock example I want to check columnName + suffix and see if it has a value greater than 0.  If so I would add an asterix

`data {ColA: 100, colA_suffix: 10, ColB: 100, colB_suffix: 0, }`

so in this case ColA would render as 100* and ColB would just render as 100

Hope this makes sense

**Comment by tabalinas** [comment]
`cellRenderer` is unique for each column. It assumes that you know in which column you are putting this renderer. If it's universal for all columns use curing for the renderer putting column name in the closure.
