### ISSUE TITLE
The column (field) that must be sorted by default when data loads into grid.

### ISSUE THREAD

**Issue by saru19** [tabalinas/jsgrid#839]
Hi,
How to force the field that will be used to sort (from the time the page is loaded)? Example: by field "Address".
I use code like in Basic Scenario demo.

https://github.com/tabalinas/jsgrid/issues/189

I have the same issue what is described above. I used the suggested solution , so that sorting is happening by default when the grid id loading. But the problem is when i click on search icon or clear filter icon(without giving any text to search or giving text) again the sort order is missing.
My requirement is data should be in sorting order even if we click on search or clearfilter icon.

**Comment by heiovsky** [comment]
Hi,
Just redefine loadData function.
This is raw function copied from jsgrid source and '$("#jsGrid").jsGrid("sort", "Age");'  is added which does the trick

    $("#jsGrid").jsGrid({
        height: 300,
        width: "100%",
        filtering: true,
        sorting: true,
        paging: true,
        autoload: true, 
        pageSize: 6,
        pageButtonCount: 5, 
        controller: db, 			
        fields: [
            { name: "Name", type: "textarea", width: 150 },
            { name: "Age", type: "number", width: 50 },
            { name: "Address", type: "text", width: 200 },            
            // problematic field: if you uncomment the following field definition,
            // you'll see that no records will be displayed in the grid.
            
            { name: "Country", type: "select", items: db.countries, valueField: "Id", textField: "Name" },
            
            { name: "Married", type: "checkbox", title: "Is Married", sorting: false }
        ]
    ,  

     loadData: function (filter) {
            filter = filter || (this.filtering ? this.getFilter() : {});

            $.extend(filter, this._loadStrategy.loadParams(), this._sortingParams());

            var args = this._callEventHandler(this.onDataLoading, {
                filter: filter
            });
 
            return this._controllerCall("loadData", filter, args.cancel, function (loadedData) {
                if (!loadedData)
                    return;

                this._loadStrategy.finishLoad(loadedData);

                this._callEventHandler(this.onDataLoaded, {
                    data: loadedData
                   
                });
                  $("#jsGrid").jsGrid("sort", "Age");
            });
        }

    });

**Comment by saru19** [comment]
Hi heiovsky,
Thank you very much for giving the solution. It is working exactly as per my requirement.
