### ISSUE TITLE
How do the paging on the server?

### ISSUE THREAD

**Issue by robertomellocampos** [tabalinas/jsgrid#84]
How do the paging on the server?
There is this option?

**Comment by tabalinas** [comment]
There is an option `pageLoading` http://js-grid.com/docs/#pageloading-default-false
Set it to `true` and controller method `loadData(filter)` will accept `pageIndex` and `pageSize`. You should pass these params to the server script. Returning result should have format `{ data: [array of items on the current page], itemsCount: totalAmountOfItems]}`
