### ISSUE TITLE
Question: Conditional initial field css

### ISSUE THREAD

**Issue by heiovsky** [tabalinas/jsgrid#840]
Hi,
I have a question. where I have to put some code to make field css conditional, what I mean?

'field css' depended on 'field name'

Example:
```css
.class_1{ color:red; }
```

fields: id, name, lastName, creationDate

And now i want fields [id,creationDate] to have 'class_1' css 

I know I can achieve this in fields definition, but I want to make it global.

so where to put
```js
if(name==='id' || name==='creationDate')
{
css="class_1";
}
```

:)

**Comment by heiovsky** [comment]
Solved.
 
By adding filed ' staticFields: [] ' in grid prototype

         Grid.prototype = {
             staticFields: ['id'],
             ...

then edit function

                _eachField: function (callBack) {
                    var self = this;
                    $.each(this.fields, function (index, field) {
                     
                        for (i = 0; i < self.staticFields.length; i++) {
                            if (field.name === self.staticFields[i]) {
                                field.css = 'jsgrid-cell-static';
                                break;
                            }
                        }
                        
                        if (field.visible) {
                            callBack.call(self, field, index);
                        }
                    });
                },

and just redefining 'staticFields'

                   $("#jsGrid").jsGrid({
                        staticFields: ['id', 'creationDate'],
                        width: "100%",
                         ...

**Comment by tabalinas** [comment]
Glad that you figured it out!
