### ISSUE TITLE
Scrolling by jsGrid DIV cuts off headers

### ISSUE THREAD

**Issue by StealthRT** [tabalinas/jsgrid#841]
Seems as though when i place **Overflow-x: scroll** into this:
`<div id="jsGrid_Pending" style="overflow-x: scroll; box-shadow: rgba(0, 0, 0, 0.55) 0px 5px 6px -4px; border-radius: 4px; border: 1px solid rgb(204, 204, 204); position: relative;" class="jsgrid">`

It cuts off the headers whereever the width of the table is:
![tableheadcutoff](https://user-images.githubusercontent.com/1037844/28186818-7d390284-67ea-11e7-8686-28cdfbf7e0f6.gif)

So i'm not really sure how to correct that. However, when I add this css:
```
.jsgrid-grid-header,
.jsgrid-grid-body {
        overflow: auto !important;
}
```
It DOES show all the header names but also shows another scrollbar under the headers:
![doublescroll](https://user-images.githubusercontent.com/1037844/28187024-30b521a8-67eb-11e7-8bca-a3498a3375a0.gif)

How can I hide the scrollbar UNDER the headers but still have the outter scrollbar in order to move left and right without the header being cut off?

**Comment by tabalinas** [comment]
Why do you redefine `overflow-x` in the first place?
It should be scrollable out-of-box.

**Comment by StealthRT** [comment]
Not sure. Thats just what i have to work with.

**Comment by tabalinas** [comment]
Try to remove this override.
