### ISSUE TITLE
Search by ALL columns with external search box

### ISSUE THREAD

**Issue by StealthRT** [tabalinas/jsgrid#844]
How can I add the ability to search **ALL** current viewable columns with an external search box? Just like I can define a **pagerContainer** I would like to equally do that with a search box like this example:
![filter](https://user-images.githubusercontent.com/1037844/28214819-c2ab191c-6879-11e7-9386-972b27e28647.png)

**Comment by tabalinas** [comment]
There is a `search` method of the grid (http://js-grid.com/docs/#searchfilter-promise) Use it for searching. 
In fact, `control` field does nothing but calling `search` method of the grid.
