### ISSUE TITLE
SubGrid with Row under normal Row onClick

### ISSUE THREAD

**Issue by floei** [tabalinas/jsgrid#845]
Hi, I Try to create a Table with some rows and columns. on click on a row, it should expand and show some SubRows. I therefore created a row.click() function. But when clicking on the row it appends the new content at the end of the rows not under my current row. How do I do this? here is some code example:

[this is a working example in jsfiddle](https://jsfiddle.net/fL033h9d/)

```
rowRenderer: function(item) {
            var row = $("<tr>");

            var addressesGrid = $('<tr>').addClass('nested-grid').hide();
            addressesGrid.jsGrid({
                width: "100%",
                height: "auto",
                data: data,
                heading: false,
                fields: col
            })
            items= Object.keys(item)
           items.forEach(function(key){
               if(key!=items[items.length-1]) {
                   var cell = $("<td>").addClass("jsgrid-cell").append(item[key])
                   row.append(cell)
               }
            })
            row.click(function () {
                addressesGrid.toggle();
            })
            row.append(addressesGrid);


            return row
        }
```

**Comment by tabalinas** [comment]
Please checkout this answer on StackOverflow: https://stackoverflow.com/a/45393085/1140893

**Comment by amin750** [comment]
I want a subgrid like the picture below, which is the arrow in the left column and open when click it
![capture](https://user-images.githubusercontent.com/19873094/31336934-fc439002-ad05-11e7-8146-0bc25017db57.JPG)

**Comment by amin750** [comment]
I want a subgrid like the picture below, which is the arrow in the left column and open subgrid when click it
![capture](https://user-images.githubusercontent.com/19873094/31338348-b0eb7f24-ad0b-11e7-84d8-1482ac499a3e.JPG)

**Comment by krovein** [comment]
> I want a subgrid like the picture below, which is the arrow in the left column and open subgrid when click it
> ![capture](https://user-images.githubusercontent.com/19873094/31338348-b0eb7f24-ad0b-11e7-84d8-1482ac499a3e.JPG)

Hi bro,
have you handled this problem? can u help me, please?

**Comment by amin750** [comment]
> > I want a subgrid like the picture below, which is the arrow in the left column and open subgrid when click it
> > ![capture](https://user-images.githubusercontent.com/19873094/31338348-b0eb7f24-ad0b-11e7-84d8-1482ac499a3e.JPG)
> 
> Hi bro,
> have you handled this problem? can u help me, please?

add rowRenderer() function like below to your grid

rowRenderer: function (item) {
            var row = $("<tr>");
            var addressesGrid = $("<td colspan='9'>").hide();
            addressesGrid.jsGrid({
                width: "100%",
                height: "auto",
                data: item.somedata,
                fields: [
                    { name: "field1", type: "text", title: "some text", width: 50 },
					{ name: "field2", type: "text", title: "some text", width: 60 },
					{ name: "field3", type: "text", title: "some text", width: 70 },
                ]
            });
            var cell1 = $("<td>").addClass("jsgrid-cell").text(item.somedata.somefield1).css({ "width": "50px" });
            var cell2 = $("<td>").addClass("jsgrid-cell").text(item.somedata.somefield2).css({ "width": "50px" });
            var cell3 = $("<td>").addClass("jsgrid-cell").text(item.somedata.somefield3).css({ "width": "250px" });

            row.append(cell1).append(cell2).append(cell3);

            row.click(function () {
                addressesGrid.toggle();
            });

            return row.add(addressesGrid);
        }

**Comment by amin750** [comment]
> > I want a subgrid like the picture below, which is the arrow in the left column and open subgrid when click it
> > ![capture](https://user-images.githubusercontent.com/19873094/31338348-b0eb7f24-ad0b-11e7-84d8-1482ac499a3e.JPG)
> 
> Hi bro,
> have you handled this problem? can u help me, please?

add rowRenderer() function like below to your grid

`        rowRenderer: function (item) {
            var row = $("<tr>");
            var addressesGrid = $("<td colspan='9'>").hide();
            addressesGrid.jsGrid({
                width: "100%",
                height: "auto",
                data: item.somedata,
                fields: [
                    { name: "field1", type: "text", title: "some text", width: 50 },
					{ name: "field2", type: "text", title: "some text", width: 60 },
					{ name: "field3", type: "text", title: "some text", width: 70 },
                ]
            });
            var cell1 = $("<td>").addClass("jsgrid-cell").text(item.somedata.somefield1).css({ "width": "50px" });
            var cell2 = $("<td>").addClass("jsgrid-cell").text(item.somedata.somefield2).css({ "width": "50px" });
            var cell3 = $("<td>").addClass("jsgrid-cell").text(item.somedata.somefield3).css({ "width": "250px" });

            row.append(cell1).append(cell2).append(cell3);

            row.click(function () {
                addressesGrid.toggle();
            });

            return row.add(addressesGrid);
        }`

**Comment by preety2** [comment]
@krovein did u get any solution??
@tabalinas I want to do same
