### ISSUE TITLE
Custom field uses items array and each column overwrites the array

### ISSUE THREAD

**Issue by NewBo1234** [tabalinas/jsgrid#846]
Good morning,

I am attempting to set up a tree custom field (at the time it seemed easier than trying to filter 3 different columns).  
```js
var MyTreeField2 = function(config) {
   jsGrid.Field.call(this, config);
}

MyTreefield2.prototype = new jsGrid.Field({
   idField: "id",
   textField: "textField",
   items: ["a"],
   groupByFields: ["d"],

   ...... (other boilerplate stuff)
   
   insertTemplate: function(value) {
      var myItems = this.items;
      
      console.log("my items are now: ");
      console.log(myItems);
      
      return getTreeDiv(idField, textField, myItems, groupBy, value);
   }

   ..... rest of the boilerplate
});
```

I have 2 columns trying to use these custom types.  I appear to be getting the correct, different arrays to fill these two columns.  But, the second instance of the MyTreeField2 overwrites the first instance's items.

Could you please help me?

Thank you,
Winona Whitener

**Comment by NewBo1234** [comment]
Good morning,

I think that I got it figured out.

So, based on my answer, the example code for custom fields and having custom properties for those fields may need to be updated.

Here's my code:

`
var MyTreeField = function(config) {
   // This allows for properties to be set and have them exclusive to a given column.  So, if this tree is  
   // database driven (like mine), then putting the custom fields up here allows them to not be over-
   // written between multiple columns using the custom fields.
   this.idField = "";
   this.textField = "";
   this.items = [];
   this.groupByFields = [];
   
   jsGrid.Field.call(this, config);
}

MyTreeField.prototype = new jsGrid.Field({
    // Putting a custom property here will work, but it will not necessarily be unique across the columns
    // So putting a property here may get overwritten if it is an object.  A reference like a string or number
    // will stay unique.  So, something like tooltip text would go here or a default selection number or
    // similar information.
    tooltipText = "",
    hintText = "",
    // for the documentation sake, let's assume that there is a collection of colors that mean something
    // across a number of columns, such as a color collection that colorCollection[0] = green, 
    // colorCollection[1] = yellow, colorCollection[2] = red that show status
    colorCollection = [],

   itemTemplate: function(value) {
        var myColor;
       if (value < 0) {
              myColor = this.colorCollection[2];
       }
       else if (value > 0 && value < 5) {
               myColor = this.colorCollection[1];
        }
        else {
               myColor = this.colorCollection[0];
        }
         
        // This is how we can access even the items with the 'this' pattern.
        // So this would be if we want our display to have a span with a background of myColor
        // and then we're using our specific items to get the display value.
        return "<span style='background:" + myColor + "'>" + this.items[value] + "</span>";
   },
   
   ..... skipping other boilerplate and details.    
});

jsGrid.fields.myTreeField = MyTreeField;
`

I hope that this example is clear enough that the documentation can be updated.  Or, even better, I'd like to have more feedback on whether or not there are better ways.

Thanks,
Winona Whitener

**Comment by NewBo1234** [comment]
Actually, this is probably just a WIP.  Apparently changing those values and having those values held between functions is a lot harder.

Any ideas?

**Comment by tabalinas** [comment]
I'm not sure I understand the original problem.
Second field items shouldn't overwrite items of the first field. 
Could it be an issue with the implementation?
Do you have a jsfiddle to show the problem?

**Comment by tabalinas** [comment]
No answer.
