### ISSUE TITLE
Loading indicator is not coming some times for service calls like sorting ,search e.t.c using jsgrid

### ISSUE THREAD

**Issue by vinod-yerramreddy** [tabalinas/jsgrid#849]
Loading indicator is not coming some times for service calls like sorting ,search e.t.c using jsgrid

1. Bug Reports:
    A) Should load an indicator
    B) load indicator not working some times when doing sorting and searching server side.
    C) Search or sort at server  side

**Comment by tabalinas** [comment]
Do you have a public resource (jsfiddle or any other) to demonstrate the problem?
At least grid configuration is needed to understand the problem.
