### ISSUE TITLE
How to use rowRenderer property to change background colour of a specific row while in jsGrid?

### ISSUE THREAD

**Issue by gitayanhub** [tabalinas/jsgrid#850]

**Comment by heiovsky** [comment]
https://jsfiddle.net/koja0mqp/29/

**Comment by gitayanhub** [comment]
I used another solution which seemed easy to me.
used rowClass to attach my custom class, and in custom class I have provided td css background color property as important. and the result was as expected.
`
js
rowClass : function(item,itemIndex){
if(item.pass==='true'){
return "notPass";
}
}
css:
.notPass td{
background-color: red !important;
}
`

**Comment by heiovsky** [comment]
Ye, it's better, forgot about this.

**Comment by gitayanhub** [comment]
closing the issue, as I found out a way to do it. thanks heiovsky for your reply!
