### ISSUE TITLE
best way to show column data that is returned during AJAX call after Insert

### ISSUE THREAD

**Issue by Hunter85** [tabalinas/jsgrid#852]
Currently I have a grid with three columns(ID, State, Date).  ID column inserting value is false as its a primary key in the database.  When I insert I use ajax call in insertItem which returns new ID.  The problem I am having is that the new row is already added to the grid without the ID before I return the ID from ajax call.  I am trying to find out the best way to update the grid and the grid data.  sorry couldnt get fiddle working correctly with my code.  Please help thanks

**Comment by heiovsky** [comment]
Hi,
just return whole object {ID,state,Date} not only ID and let jsGrid do the magic

**Comment by Hunter85** [comment]
Worked PERFECT! Thank you for the help.
