### ISSUE TITLE
how to get the grid data?

### ISSUE THREAD

**Issue by ufoqhmdt** [tabalinas/jsgrid#854]
If i want to get the grid data . May  i use $('id').jsgrid().getData() to get the whole current data? I can't find the document about this .

**Comment by ufoqhmdt** [comment]
if there is not provide this method, I just only do it through custom function like this：

`
$('.jsgrid-table tr.jsgrid-row,tr.jsgrid-alt-row').each(function(index, item) {
	console.log(index, $(item).text());
});
`

**Comment by heiovsky** [comment]
var data = $('#grid').jsGrid('data');

**Comment by tabalinas** [comment]
You can data from `data` option (http://js-grid.com/docs/#data):
```js
var data = $("#grid").jsGrid("option", "data");
```
