### ISSUE TITLE
HELP: Use the feature of export which is not been released yet

### ISSUE THREAD

**Issue by ansioncai** [tabalinas/jsgrid#855]
Help 

I want to use the feature of export which is not been released yet.

How can I build the latest from master(as I see that it has been committed to master) and use it in my project.

**Comment by tabalinas** [comment]
1. Fetch repo
2. ensure that nodejs is installed
3. run `npm install`
4. run `grunt default`

The result will be in the `dist` directory

**Comment by djdance** [comment]
could someone share resulting js? I have no Node.js. Thanks
