### ISSUE TITLE
problem with grid call

### ISSUE THREAD

**Issue by g14nluk4** [tabalinas/jsgrid#857]
i've a dinamyc grid in my project where when i select 1 option it call my grid , well this works but not always , i mean i don't know why but sometimes it doesn't work and send me this error:

![image](https://user-images.githubusercontent.com/24521821/28723564-65da70d6-73b7-11e7-932d-71d0f0242060.png)

**Comment by heiovsky** [comment]
Hi,
Show your code with jsGrid config or reproduce this scenario on JSFiddle

**Comment by tabalinas** [comment]
Looks like jsGrid script is not loaded. 
It could be the case that this script is loading asynchronously, so it's not guaranteed that it present when jsGrid is initialized.

**Comment by g14nluk4** [comment]
i solved the problem( i think) , in my project there is  a button on my grid , wich call a  modal with content from another page(jsp) , i don't know why but if i change the call  $(..).load  to "document.getElementById("something").innerHTML = '<object type="text/html" width="100%" height="100%" data="myPage.jsp?id=0" ></object>'; "  it works without problems ! ..... do u know why ?

**Comment by tabalinas** [comment]
Glad that you figured it out.
I'm afraid, there is not enough context to answer your followup question.
