### ISSUE TITLE
Calling previous column's value with CellRenderer

### ISSUE THREAD

**Issue by tburd** [tabalinas/jsgrid#858]
Hey guys!
Thank you so much for such a nice tool.

I have been implementing it in a personal project with excitement.
Although I was not able to figure this out.
When rendering the cells of a certain column, I would like to use the value of the last column as reference for calculation.

Example:
__________
| 5 | 8 | 4 |
| 5 | 6 | 7 |   ==> When rendering 3rd column:  if( 2nd_column.value < 3rd_column.value) value = 3rd_column.value / 2;

```js
fields: [
                    { name: "id", type: "number", align:"center" },
                    { name: "temperature", type: "number", align:"center",
                        itemTemplate: function(value){
                            return parseInt(value).toFixed(2);
                        }
                    },
                    { name: "average", type: "number", align:"center",
                        itemTemplate: function(value){
                            return parseInt(value).toFixed(2);
                        }
                    },
                    { name: "result", type: "number", align:"center", width:"30",
                        cellRenderer: function(value){
                            **if (2nd_column_???? < value )  value = value / 2;**

                            if (value<2) cc="bg-green";
                            if (value>=2) cc="bg-yellow";
                            if (value>=5) cc="bg-orange";
                            if (value>=10) cc="bg-red";

                            return '<td class="jsgrid-cell '+cc+'">' +value+ '</td>';
                        },

                    }
                ]
```

How can I implement this, considering my code above?
Or it there a better way to do that?

Best regards and thank you in advance!

**Comment by tabalinas** [comment]
Second parameter of `itemTemplate` is the data `item` (http://js-grid.com/docs/#fields), so you can take any other field values from it.

Instead of `cellRenderer` you can use `itemTemplate, just wrap output value in a div with your custom css class.
