### ISSUE TITLE
Calculating Total footer when updating a Row

### ISSUE THREAD

**Issue by hbarbosa437** [tabalinas/jsgrid#859]
Hi

I am using the following to update the total when a row is updated. However it Works with a new row but not when rh column Sum is updated

Could you please help me?

```js
var data = [{
  "Name": "Product",
  "Sum": 10
}, {
  "Name": "Another Product",
  "Sum": 20
}, {
  "Name": "Third Product",
  "Sum": 30
}];

$("#jsGrid").jsGrid({
  width: "100%",

  autoload: true,
  inserting: false,
  editing: true,

  controller: {
    loadData: function() {
      return data;
    }
  },

  onRefreshed: function(args) {
    var items = args.grid.option("data");
    var total = {
      Name: "Total",
      "Sum": 0,
      IsTotal: true
    };

    items.forEach(function(item) {
      total.Sum += item.Sum;
    });
    var $totalRow = $("<tr>").addClass("total-row");

    args.grid._renderCells($totalRow, total);

    args.grid._content.append($totalRow);

  },

  fields: [{
    name: "Name",
    title: "Product",
    type: "text",
    width: "60%",
    validate: "required"
  }, {
    name: "Sum",
    title: "Sum",
    type: "number",
    width: "30%",
    validate: "required"
  }, {
    type: "control",
    width: "10%",
    editButton: false,
    itemTemplate: function(_, item) {
      if (item.IsTotal)
        return "9999";
      return jsGrid.fields.control.prototype.itemTemplate.apply(this, arguments);
    }
  }]
});
```

**Comment by tabalinas** [comment]
Have you checked out this issue https://github.com/tabalinas/jsgrid/issues/224?

**Comment by hbarbosa437** [comment]
Yes I have. 

I Added the following
onItemUpdated: function (item) {
                // Força  o refrsh
                $("#jsGrid").jsGrid("refresh")
            },


but the label"Total" does not appear and the sum shows always 0

I am trying to integrate that with Dynamics CRM. All My code is 👍 


<!DOCTYPE html>

<html lang="en" xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta charset="utf-8" />
    <title>Demo</title>
    <script type="text/javascript" src="ClientGlobalContext.js.aspx"></script>


    <script src="../WebResources/hb_load_css"></script>
    
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:300,600,400' rel='stylesheet' type='text/css'>
    
    <script src="../WebResources/hb_XrmServiceToolkit.js"></script>
    <script src="../WebResources/hb_jquery1.8.3.js"></script>
    <script src="../WebResources/hb_json"></script>
    
     
   
    <script src="../WebResources/hb_jsgrid.core"></script>
    <script src="../WebResources/hb_jsgrid.load_indicator"></script>
    <script src="../WebResources/hb_jsgrid.load_strategies"></script>
    <script src="../WebResources/hb_jsgrid.sort_strategies.js"></script>
    <script src="../WebResources/hb_jsgrid.field.js"></script>
    <script src="../WebResources/hb_jsgrid.field.text"></script>
    <script src="../WebResources/hb_jsgrid.field.textarea"></script>
    <script src="../WebResources/hb_jsgrid.field.number"></script>
    <script src="../WebResources/hb_jsgrid.field.decimal"></script>
    <script src="../WebResources/hb_jsgrid.field.select"></script>
    <script src="../WebResources/hb_jsgrid.field.checkbox"></script>
    <script src="../WebResources/hb_jsgrid.validation"></script>
    <script src="../WebResources/hb_jsgrid.pt"></script>
    <script src="../WebResources/hb_icons"></script>
    <script src="../WebResources/hb_jsgrid.field.control"></script>

    <style>
        .rating {
            color: #F8CA03;
        }
    </style>

    <style>
        .pager-panel {
            padding: 10px;
            margin: 10px 0;
            background: #fcfcfc;
            border: 1px solid #e9e9e9;
            display: inline-block;
        }
    </style>

</head>
<body>
    <h1>Reservas</h1>
    <div id="jsGrid"></div>

    
    <script>
        LoadCSS("../WebResources/hb_demos");
        LoadCSS("../WebResources/hb_JSgrid");
        LoadCSS("../WebResources/hb_rheme");
        this.context = GetGlobalContext();
               
        var serverUrl = this.context.getClientUrl();
        
        query = "/hb_servicoencargoSet?$select=hb_Codigo,hb_DisponivelnasReservas,hb_ExclusivodeSocios,hb_IVAId,hb_name,hb_PrecodeVendacomIVA,hb_Precoeditvelpeloutilizador,hb_servicoencargoId";
        ODataURL = serverUrl + "/xrmservices/2011/OrganizationData.svc" + query;
        
        $(function() {

        $("#jsGrid").jsGrid({
            height: "auto",
            width: 1000,
            sorting: true,
            editing: true,
            paging: false,
            autoload: true,
            locale: "pt",
            controller: {
                loadData: function() {
                    var d = $.Deferred();

                    $.ajax({
                        
                        
                        url: ODataURL,
                        dataType: "json",
                        beforeSend: function (XMLHttpRequest) {
                            //tipo do retorno
                            XMLHttpRequest.setRequestHeader("Accept", "application/json");
                        },
                        success: function (data, textStatus, XmlHttpRequest) {
                            resultado = data.d.results[0];
                            //alert(resultado.hb_name);
                        },
                        error: function (XmlHttpRequest, textStatus, errorThrown) {

                                alert('Falha em:' + ODataURL);

                            }
                        
                    }).done(function(data) {

                       
                            //alert("here");
                            d.resolve(data.d.results);
                        
                       
                    });

                    return d.promise();
                }
            },

            onItemUpdated: function (item) {
                // Força  o refrsh
                var $totalRow = $("<tr>").addClass("total-row");
                $("#jsGrid").jsGrid("refresh")
            },


            onRefreshed: function (args) {
                

                var items = args.grid.option("data");
                var total = { Name: "Soma", "new_Total": 0, IsTotal: true };
               
                total.new_Total = 0;
                items.forEach(function (item) {
                    if (item.new_Quantidade != null) {
                        //alert((item.new_Quantidade * item.hb_PrecodeVendacomIVA.Value).toFixed(2));
                        total.new_Total += parseFloat((item.new_Quantidade * item.hb_PrecodeVendacomIVA.Value).toFixed(2))
                        //alert(total.t_total)
                    }
                    
                
                });

                
                var $totalRow = $("<tr>").addClass("total-row");
                alert(total.new_Total)
                args.grid._renderCells($totalRow, total);

                args.grid._content.append($totalRow);
               
            },

            fields: [
                { name: "hb_servicoencargoId", title: "Id", type: "text", width: 100, visible: false },
                { name: "hb_Codigo", title: "Código", type: "text", width: 100, editing: false },
                { name: "hb_name", title: "Descrição", type: "text", width: 200, editing: false },
                { name: "new_Quantidade", title: "Quantidade", type: "decimal", width: 100, editing: true,   validate: {
                               validator: "range",
                               message: function(value, item) {
                                       return "Quantidade deve estar enter 0 e 100. Quantidade introduzida \"" + value + "\" está fora da gama.";
                                    },
                                   param: [0, 100]
                  }
        },
                {name: "hb_PrecodeVendacomIVA.Value", title: "PVP", type: "decimal", width: 100, editing: true},
           
                { name: "hb_IVAId.Name", title: "IVA", type: "text", width: 100, editing: false, align: "right" },
                { name: "hb_Precoeditvelpeloutilizador", type: "checkbox", title: "Editável", editing: false , visible: false},
                {
                    name: "new_Total", title: "Preço Total", type: "decimal", width: 100, editing: false, itemTemplate: function (value, item) {
                       
                        if (item.new_Quantidade != null) {
                            return (item.new_Quantidade * item.hb_PrecodeVendacomIVA.Value).toFixed(2);
                                                    }
                        else {
                            return (0);
                        }
                    }
                },

                {
                    type: "control", width: 30, editButton: true, itemTemplate: function (_, item) {
                        
                        if (item.IsTotal)
                             return "";
                        return jsGrid.fields.control.prototype.itemTemplate.apply(this, arguments);
                        }
                    }
                
            ],

            

        });
       
        });
        </script>
    </body>
    </html>

**Comment by hbarbosa437** [comment]
![capturar](https://user-images.githubusercontent.com/30574266/28769505-bbc130ac-75d3-11e7-8d54-6ef175bad0e9.JPG)

**Comment by hbarbosa437** [comment]
[gridHB.txt](https://github.com/tabalinas/jsgrid/files/1186928/gridHB.txt)

**Comment by hbarbosa437** [comment]
I think I know where the problem is. 
When a Field is calculated it is not possible to calculate total? 

Thanks

**Comment by tabalinas** [comment]
> When a Field is calculated it is not possible to calculate total?

What do you mean?

**Comment by hbarbosa437** [comment]
Hi Tabalinas

 

The colum I want to calculate Total is a colum that is calculated in funtion of the 2 others columns. The total appears always  as 0.

 

If  the column is a input column the total is calculated

 

 

 

 

 

Com os nossos melhores cumprimentos,

Helena Barbosa

 

Parceiro PME CRM ONLINE FY16 H2 Norte

Visite-nos em www.hbarbosa.pt .    Conheça as nossas soluções  

 

De: Artem Tabalin [mailto:notifications@github.com] 
Enviada: 5 de agosto de 2017 22:54
Para: tabalinas/jsgrid <jsgrid@noreply.github.com>
Cc: hbarbosa437 <hbarbosa@hbarbosa.pt>; Author <author@noreply.github.com>
Assunto: Re: [tabalinas/jsgrid] Calculating Total footer when updating a Row (#859)

 

When a Field is calculated it is not possible to calculate total?

What do you mean?

**Comment by tabalinas** [comment]
Do you have a jsfiddle (or any other public resource) to reproduce the problem?

**Comment by trouble2** [comment]
I'm trying to do just the same....
I've got 1 column with miles, and another with miles * 027 
So I've got that working with: 
https://github.com/tabalinas/jsgrid/issues/63

But now, it also needs to update the total....
Can you do a loop through the column values or something?

**Comment by trouble2** [comment]
It would probably work after I click on the 'update' button, and the grid get's refreshed..
But I would like it to instantly update the total...
