### ISSUE TITLE
Button field - custom onClick

### ISSUE THREAD

**Issue by heiovsky** [tabalinas/jsgrid#861]
Hi,
I have a button field that I want to make custom onCick function to it

```js
        ButtonField.prototype = new jsGrid.Field({
            css: "date-field", // redefine general property 'css'
            align: "center", // redefine general property 'align'
            filtering: false,
            sorting: false,
            editing: false,
            label: "Button",
            onClick: function (idx) {
                console.log('hello'+idx);
            },
            itemTemplate: function (value, item) {
                var $customButton = $("<button>")
                        .text(this.label)
                        .click(function (e) {
                            alert("....." + item.id);
                            this.onClick(item.id);
                            e.stopPropagation();
                        });
                return $customButton;
            }
        });

        jsGrid.fields.button = ButtonField;
```

**Comment by tabalinas** [comment]
Ok, it looks good. What is your question?

**Comment by heiovsky** [comment]
ButtonField.prototype = new jsGrid.Field({
                    css: "date-field", // redefine general property 'css'
                    align: "center", // redefine general property 'align'
                    filtering: false,
                    sorting: false,
                    editing: false,
                    label: "Button",
                    onClick: $.noop,
                    itemTemplate: function (value, item) {
                        var self = this;
                        var $customButton = $("<button>")
                                .text(this.label)
                                .click(function (e) {
                                    self.onClick(item);
                                    e.stopPropagation();
                                });
                        return $customButton;
                    }
                });
                jsGrid.fields.button = ButtonField;

this works with addition of 'var self=this'

I have no question now, I think, I was a little braindead when I was writing this issue ;D
