### ISSUE TITLE
Clear Filter don't work on custom field

### ISSUE THREAD

**Issue by 5p1k3md** [tabalinas/jsgrid#865]
1. Bug Report:
    A) Expected Behavior: Click on "clear filter" button in controls should clear all filters and load unfiltered data.
    B) Actual Behavior: Built-in fields got cleared, but custom field doesn't.
    C) Steps to Reproduce: See [this fiddle](https://jsfiddle.net/vxec1kj7/).
    
Am i missing something?

**Comment by tabalinas** [comment]
No, it's a custom control implementation bug - `filterTemplate` redefines itself to a jQuery element instead of the original function.

Here is the fixed version:
https://jsfiddle.net/tabalinas/9j1f4aLn/2/

**Comment by 5p1k3md** [comment]
First of all, thanks for your help.
Unfortunately your fixed version throws an error, see [this updated fiddle](https://jsfiddle.net/vxec1kj7/1/).
Error message is saying "Uncaught TypeError: this.filterTemplate.val is not a function".

**Comment by 5p1k3md** [comment]
I got it to work.

See [this working fiddle](https://jsfiddle.net/vxec1kj7/2/) (i don't know why filtering isn't working in this fiddle but in my project it does.
