### ISSUE TITLE
Select change event to update text in same row

### ISSUE THREAD

**Issue by dagobertdebug** [tabalinas/jsgrid#869]
Category: Help Request/Question

Hi guys

I have a text field and a select field in a row.

Is it possible to insert a string into the text field on a dropdown change event depending on the selected value? 

I am testing with the code below which shows the alert on any change of the dropdown in the case of adding. It is not working for updating of rows yet.

```
onDataLoaded: function(args) {
  $( ":input" ).change(function() {
      alert( "Handler for .change() called." );
      });
  },
```

My final plan is to set a decimal field with a price depending on the selected value from the dropdown. The price comes from the database.

Any tips? Thanks for your help!

**Comment by tabalinas** [comment]
Redefine `editTemplate` (or `insertTemplate` of the field attaching `change` event handler so the it sets the text field.
