### ISSUE TITLE
Need help creating custom field using Chosen by harvest

### ISSUE THREAD

**Issue by muzafarhasan** [tabalinas/jsgrid#87]
i need help in creating custom field regarding Chosen by harvest
here is the link to to the plugin http://harvesthq.github.io/chosen/
if you could point to some direction...

**Comment by tabalinas** [comment]
Have you seen this ticket? https://github.com/tabalinas/jsgrid/issues/72
What if you try to do it the similar way?
Don't hesitate to ask for help if you will have troubles with it (better provide a jsfiddle to show the problem)

**Comment by ahmed610** [comment]
![image](https://cloud.githubusercontent.com/assets/23277376/20086842/7b880878-a584-11e6-9239-8d4d04da35a5.png)

![image](https://cloud.githubusercontent.com/assets/23277376/20086861/a21e9204-a584-11e6-945f-20933ec34f92.png)

in the second screenshot as noticed I have to scroll to get the drop down list
