### ISSUE TITLE
Reload select filter options after insert

### ISSUE THREAD

**Issue by Hunter85** [tabalinas/jsgrid#871]
Once a row is inserted I want to add the newly create value/option into the select for the filter.  Please see jsfiddle for example. 

http://jsfiddle.net/jkhowell/ovbcdne8/7/

Thanks,
Josh

----
FYI - carried over from issue #853
----

**Comment by tabalinas** [comment]
You need to add item to the select items:

onItemInserted: function(args) {
     db.effDates.push({ID: args.item.EFF_DATE, NAME: args.item.EFF_DATE});
     this.fieldOption("EFF_DATE", "items", db.effDates);
}

Here is the fixed fiddle http://jsfiddle.net/2orofntb/
