### ISSUE TITLE
insert/update/delete feature request

### ISSUE THREAD

**Issue by edwardsmarkf** [tabalinas/jsgrid#874]
hello - 

is there any way to suppress the default **controller: insertItem** from happening, by including a final optional boolean parameter?

there are many times when i want to do a `$("#grid").jsGrid("insertItem"`, but we do not want the 
**controller: insertItem** to execute.

i am thinking about something like this:

http://js-grid.com/docs/#insertitemitem-promise
```
// insert item
$("#grid").jsGrid("insertItem", { Name: "John", Age: 25, Country: 2 }).done(function() {
    console.log("insertion completed");
},  false  );     // this 'false' boolean would suppress the "controller: insertItem" from executing.
```

**Comment by tabalinas** [comment]
`controller.insertItem` is in your hands. You can define any logic inside that will suppress it by particular condition.
