### ISSUE TITLE
Disable Filters Input Textbox

### ISSUE THREAD

**Issue by l1salvatore** [tabalinas/jsgrid#875]
Report type 3
 Is there some way to delete some filter input? I want to filter only by specific columns. 

Thanks in advance!

Lucas

**Comment by heiovsky** [comment]
http://js-grid.com/docs/#fields

**Comment by tabalinas** [comment]
Set `filtering: false` for fields not participating in filtering.

**Comment by krpriyesh1110** [comment]
filtering: false, is not working for a text type field. It is working only for select type field. #tabalinas please suggest..
