### ISSUE TITLE
Custom field "Datetime" editing: false don't work as expected

### ISSUE THREAD

**Issue by 5p1k3md** [tabalinas/jsgrid#876]
1. Bug Reports:
    A)Expected Behavior: Following [this example](http://jsfiddle.net/doaw2zgs/120/) i try to disable editing and expect, that edit template is not shown in edit mode.
    B) Actual Behavior: The edit template is still showing up, but the value don't get updated on save.
    C) See [this fiddle](http://jsfiddle.net/doaw2zgs/121/).

**Comment by heiovsky** [comment]
Its not bug, it works as is implemented

**Comment by 5p1k3md** [comment]
Hello and thank you for the fast answer.
If it's not a bug, is it possible to make it work as i expect it to do?
I just tested it with an other custom field with jquery autocomplete and the behavior is the same.
I hoped that custom field can behave like the integrated ones.

**Comment by heiovsky** [comment]
change this
           

           insertTemplate: function(value) {
                return this._insertPicker = $("<input>").datepicker({ defaultDate: new Date() });
           },
          editTemplate: function(value) {
             return this._editPicker = $("<input>").datepicker().datepicker("setDate", new Date(value));
          },

to this

      insertTemplate: function(value) {
           if (!this.inserting)
                return "";
        return this._insertPicker = $("<input>").datepicker({ defaultDate: new Date() });
      },
    
      editTemplate: function(value) {
               if (!this.inserting)
                  return this.itemTemplate.apply(this, arguments);
        return this._editPicker = $("<input>").datepicker().datepicker("setDate", new Date(value));
      },

**Comment by 5p1k3md** [comment]
Works like a charm.
Thank you.
