### ISSUE TITLE
How to assign items to a property on a select box?

### ISSUE THREAD

**Issue by ragerory** [tabalinas/jsgrid#878]
I have a model that contains Records. Each Record has an array assigned to it. I'm going over the documentation but all the "items" properties seem to be assigned to js variables. How can I access the property directly like I would with "name"? I have a lot of js-grid components on the application, but this is the first one that needs this type of functionality and I can't seem to get it to work the way I'm wanting it to.

Say my model is 

`List<Record> Records { get; set; } `

and Record looks like this...

```
string RecordName { get; set; }
List<Item> RecordItems { get; set; }
```

I'm looking to access RecordItems somehow. Something similar to this -

`name: "RecordName", type: "select", items: "RecordItems", etc...`

I tried multiple variations but cannot seem to get it correctly. I can add items to the top level but that list changes for each Record...

**Comment by heiovsky** [comment]
Reproduce your case on jsfiddle


17.08.2017 18:52 "Rory Thompson" <notifications@github.com> napisał(a):

**Comment by ragerory** [comment]
I can't with dynamic data... What part of the problem isn't clear? I can clarify where I can.

Instead of having a js array for "items", it is a dynamic list that changes per each record. So each row would have a dropdown with different values in the same column.
