### ISSUE TITLE
Row values revert after calling cancelEdit

### ISSUE THREAD

**Issue by gskramer** [tabalinas/jsgrid#879]
Hello - In my jsGrid controller code, the updateItem() method has some custom code to test the row values against other values in the grid - this is to prevent duplication of certain fields. If a duplication is found, it displays an error, then calls 'cancelEdit' to revert the row to its original values. That works fine: The cancelEdit call puts the original values back into the row. However, when the code exits the controller, the *edited* values get put back into the row - i.e., the *wrong* values. How do I prevent it from doing this? Many thanks for your help! Code sample follows (for simplicity, I've left out all controller methods except for updateItem): (see additional notes below this sample)

```js
    var controller = {
        updateItem: function(item) {
           // Before submitting to server, test for uniqueness of Part/Warehouse vs other rows
            var grid = $("#gridLD").jsGrid("option", "data");
            var thisRowId = item.id;
            for (var row in grid) {
                if (grid[row].id = thisRowId) {
                    if (grid[row].PART_ID == item.PART_ID && grid[row].WHSE_ID == item.WHSE_ID) {
                        alert('There is already a record with the same Part and Warehouse.');
                        $("#gridLD").jsGrid("cancelEdit");
                           // Correctly reverts row to previous values, but on exit from controller, the incorrect
                           // values are put back in.
                        window.idToCancel = thisRowId;
                           // Additional test to cancel edit after the fact in onItemUpdated()
                        return;
                    }
                }
            }
			// (send update to server here, if data is ok)
        }
    };
```
When the above didn't work, I tried ALSO canceling in the onItemUpdated method, based on the flag I set in the above code:
```js
                onItemUpdated: function(args) {
                    // cancel editing of the row if matches 'cancel update id' set in updateItem() method
                    if(args.item.id == window.idToCancel) {
                        args.cancel = true;
                    }
                }
```
However, this still doesn't work: The row remains with the incorrect data in it.

**Comment by gskramer** [comment]
Thanks so much for the quick response! Yes, that works. It appears that this prevents updateItem() from being called:
    args.cancel = true; 
and this reverts the row to its previous values:
    $("#gridLD").jsGrid("cancelEdit");

If I can ask a follow-up question: Is it possible to invoke jsGrid("cancelEdit") after updateItem() has been called? My updateItem() code sends the row update to the server, and it would be good to be able to revert the row to old values if the server code fails, in the Ajax callback. Or should I put all of that logic in the onItemUpdating  code?

**Comment by heiovsky** [comment]
Just return old unedited item from server and it will work


18.08.2017 21:01 "gskramer" <notifications@github.com> napisał(a):

**Comment by tabalinas** [comment]
@heiovsky, thank you for the answers!
