### ISSUE TITLE
onItemUpdated doesn't return the updated row but the updating one

### ISSUE THREAD

**Issue by julmarci** [tabalinas/jsgrid#88]
I was trying to change the row after updating using the onItemUpdated callback and was impossible. Then I saw this in the source code:

this._callEventHandler(this.onItemUpdated, {
                    row: **$updatingRow**,
                    item: updatedItem,
                    itemIndex: updatingItemIndex,
                    previousItem: previousItem
                });

I guess that $updatingRow means that is not returning the updated row.

**Comment by tabalinas** [comment]
Looks like a bug. Thank you for pointing this out!
