### ISSUE TITLE
Change paging - add option to not show page numbers

### ISSUE THREAD

**Issue by HerrimanCoder** [tabalinas/jsgrid#880]
Is there any way to have paging without page numbers? It seems very cluttery when I have many pages of data. What I would love is this:

First | Previous | Next | Last

There is no need to go to a specific page.

And even better than that would be icons rather than text links. Is something like this already supported? If so, how is it done? If not, could it be added? It would be very awesome.

Thank you.

**Comment by heiovsky** [comment]
http://js-grid.com/docs/

**Comment by HerrimanCoder** [comment]
Got it, sorry, I should have read the docs more thoroughly. But how can I replace those links with icons?

**Comment by HerrimanCoder** [comment]
I solved this with:

pagePrevText: "<",
pageNextText: ">",
pageFirstText: "<<",
pageLastText: ">>",
