### ISSUE TITLE
Disable certain options in select

### ISSUE THREAD

**Issue by ragerory** [tabalinas/jsgrid#881]
I have a select in my grid. Is it possible to disable certain options in the select when I bind it?

**Comment by heiovsky** [comment]
I using select2 plugin with jsgrid, adding disabled='disabled' to select
item do the trick

21.08.2017 21:03 "Rory Thompson" <notifications@github.com> napisał(a):

**Comment by ragerory** [comment]
Just adding the below works in the itemTemplate

```
            if (item.Disabled) {
                $option.attr("disabled", "disabled");
            }
```
