### ISSUE TITLE
Help Request. 

### ISSUE THREAD

**Issue by UjjayiniD** [tabalinas/jsgrid#884]
I have a link on a grid cell. On clicking on it, I need to pass the value of one of the fields in the same row, so that a modal can be viewed accordingly. Each row has a different modal depending on the value of the field. I can call the modal but passing the value as parameter is not achieved. Can you suggest anything? Thanks.

**Comment by 5p1k3md** [comment]
If the only problem is to get the value you can use the rowclick function:

```
$("#jsGrid").jsGrid({
       ...
        
        rowClick: function(e) {
        	clickedRow = e.item;
                var value = clickedRow.value;
        },
 
        fields: [...]
    });
```

**Comment by tabalinas** [comment]
@UjjayiniD, `itemTemplate(value, item)` accepts item with all fields, so you can access any field and pass to the link click handler.
Is it what you are trying to achieve?
