### ISSUE TITLE
filtering column with select

### ISSUE THREAD

**Issue by labregowski** [tabalinas/jsgrid#885]
In a column with a "select" that has two options, YES and NO, Is there a fast track way to instruct the filter to show elements that have both "YES" and "NO" in this column?
Thanks

**Comment by richraid21** [comment]
Could you please provide a more detailed description? I'm not sure I understand the problem.

**Comment by tabalinas** [comment]
@labregowski, as filtering is on your side, you can add a third option to the select (for instance "ALL") and show all items when it's selected.
