### ISSUE TITLE
Fire click event on new row's button

### ISSUE THREAD

**Issue by mgyatso** [tabalinas/jsgrid#886]
After creating a new row I would like to fire a click event on that new row's button. I imagine adding this call to the 'onItemInserted' callback is the proper way to accomplish this. 

For me, the following code does not work and I'm sure I'm missing something.

```
onItemInserted: function(item) {
     var $row = $("#my_grid").jsGrid("rowByItem", item);
     $($row + ' .toggle-button').click();
 }...
```
Any assistance would be appreciated.

**Comment by richraid21** [comment]
Why not just fire the function associated with the button? Rather than attempt to fire the click?

**Comment by tabalinas** [comment]
@mgyatso, I guess you meant:

```js
$row.find('.toggle-button').click();
```

instead of `$($row + ' .toggle-button')`.
