### ISSUE TITLE
number fields

### ISSUE THREAD

**Issue by sripathi123** [tabalinas/jsgrid#89]
hi

i have a number field in grid that accepting String also how to restrict to numbers only, and i seen that 
ticket no  #76 that's not working for me can u plz send the working code. i don't have much experience in front-end.

**Comment by tabalinas** [comment]
#76 does answer the question how to subscribe to event in the edit field.
See this fiddle to know how to prevent typing letters http://jsfiddle.net/lesson8/HkEuf/1/
If you will have problems with it, provide a fiddle with you tries.

**Comment by sripathi123** [comment]
thank you very much for fast reply,

this fiddle for common html input fields but i need to integrate it with grid input types, am unable to capture key-press event for grid input types, plz help me.

**Comment by tabalinas** [comment]
To integrate it with jsGrid you need to redefine `editTemplate` or `insertTemplate` just as it's done in #76.
Change the following fiddle http://jsfiddle.net/tabalinas/zzzfmpgt/ to demonstrate how you try to do it and the problem you faced with.

**Comment by sripathi123** [comment]
this is the fiddle, https://jsfiddle.net/vekomy/zzzfmpgt/8/  Actually am unable understand Template concepts, remining every thing is fine. deletion operations, rowRendering, cutomViews, every thing is fine.

**Comment by tabalinas** [comment]
The problem in your fiddle is that `inserting` for the grid is turned off J
Add `inserting: true` to the grid config.

**Comment by sripathi123** [comment]
can u plz send me the currect working fiddle.

**Comment by tabalinas** [comment]
This is your fixed fiddle http://jsfiddle.net/tabalinas/zzzfmpgt/9/ (just added `inserting: true`). Here you got alert on keypress in Address field.

**Comment by sripathi123** [comment]
Thank u very much for spending your valuable time for me, but still i didn't get  any alert in this fiddle, 
am using latest version of chrome browser, is there any browser capability required for this, and alerts also not blocked in my browser.

**Comment by tabalinas** [comment]
I guess, you try it again in filter row. You should click the plus icon to switch to insertion and then type something in Address input.

**Comment by sripathi123** [comment]
yes your  right its working fine, but my requirment is i need that event while editing exiting data, not for new entry, is this possible? 

any way great work Tabalinas thank you very much.

**Comment by tabalinas** [comment]
Why not? Just do the similar code for the editTemplate (as you did for insertTemplate).
