### ISSUE TITLE
get all row items from multiple pages using jsgrid

### ISSUE THREAD

**Issue by Nagavali** [tabalinas/jsgrid#890]
When we have pagination concept in jsgrid, present we are getting all rows of current page only by using below code:  

var items = $.map($gridData.find("tr"), function(row) {
                return $(row).data("JSGridItem");
 });
 console && console.log("Reordered items", items);

But when we have pagination concept I need all rows from all pages. How to get it.

**Comment by heiovsky** [comment]
Do you want sorting/filtering client side?

**Comment by Nagavali** [comment]
I want records reordering.. For saving records reordered in DB by using ID column I need all rows ID values. Currently I am getting current page rows only. when we have multiple pages I need all rows.

**Comment by heiovsky** [comment]
Why you reordering records in grid then saving it to DB?

Explain your case, becouse I dont get it

**Comment by Nagavali** [comment]
We have requirement for rows reordering. For this jsgrid supports to move records up and down for reordering. Here is the example site for rows reordering: http://js-grid.com/demos/ 
Once I move any record up OR down in any of the one page, I need to save the entire order in DB.

**Comment by Nagavali** [comment]
Once user moves the record up or down after sometime navigate to same page to see that.. that will be in same order which he moved.

**Comment by heiovsky** [comment]
So you just need a column 'order' in your table which will be your ID(primaryKEY) at start
and you just need to edit 2 items and swap thier 'order' values

**Comment by Nagavali** [comment]
Ya I need all rows from all pages (when we have pagination), so that I will get id value from that row. It will be very easy to save the order in DB in the same sequence. Present I am getting only current page rows only. But I need all pages rows.

**Comment by heiovsky** [comment]
Maybe just get all data you from other endpoint and work with it
var data= getJSON('my/app/endpoint/alldata/');

getJSON is function that makes simple ajax request

**Comment by Nagavali** [comment]
I need to get all rows items only from JSGrid. I am getting currentpage row items like below:
 var items = $.map($gridData.find("tr"), function(row) {
                            return $(row).data("JSGridItem");
                        });   
I kept Id as hidden column in JSGrid. So to retrieve Id I am using code like:
var items = $.map($gridData.find("tr"), function(row) {
                            return $(row).data("JSGridItem").Id;
                        });  

But I need all pages row items. That is the issue.

**Comment by tabalinas** [comment]
@Nagavali, you can get all grid items reading `data` option of the grid:

```js
var items = $("#grid").jsGrid("option", "data");
```

This is the case if you don't load data by pages, in which case obviously grid doesn't have all items loaded (only active page).
