### ISSUE TITLE
Can't reuse the function

### ISSUE THREAD

**Issue by stevehn** [tabalinas/jsgrid#891]
So I wrapped a function around the jsGrid Data Manipulation example  and had it loads based onChange event.  It works the first try but  failed the second event change.  Everything is wrapped inside a function  so it should be reinitialized for a second time around.  Is there  something in memory that I have to purge?  http://jsfiddle.net/stevehn/ntjnnh4y/

**Comment by tabalinas** [comment]
I commented on SO issue (https://stackoverflow.com/questions/45847411/jsgrid-function-call-issue#comment79014342_45847411):

> When jsGrid is initialized for the second time it doesn't create new grid but just triggers massive option change. The final intension of your example is not clear. If you want to have several grids - create several divs and just show div associated with select item. If you don't want to overload page with several grids, init them on show even lazily.
