### ISSUE TITLE
Insert custom headers into grid.

### ISSUE THREAD

**Issue by bluenose1970** [tabalinas/jsgrid#892]
Is it possible to insert custom rows (headers basically) into a grid, example below is grouped by country which produces the headers.

![screenshot](https://user-images.githubusercontent.com/25171000/29714940-1fc34e3c-899d-11e7-986b-cd98989691c2.png)

I know it is possible with multiple grids to achieve this but was curious if it was possible with just 1 grid?

Thanks

**Comment by tabalinas** [comment]
Check out this issue taking about grouping https://github.com/tabalinas/jsgrid/issues/223

**Comment by trouble2** [comment]
The issue under #223 talks about subgrids, I don't think that is a good solution.
When I look at other grid solutions you can simply add it to the options like:
jsGrid({
...
grouping: true,
groupingview: {
     groupfield: ["name"],
     grouptext: ["<strong>{0}</strong>"].
     groupcollapse: false
     ...
}
...
})
