### ISSUE TITLE
Help Request: process like a 'normal' POST

### ISSUE THREAD

**Issue by gonzalobrandan** [tabalinas/jsgrid#896]
Hi,

I'm having trouble to figure out how to process the values from the grid with a normal POST with a PHP backend, the grid it's a part of a form that contains more data (figure out like an invoice or a delivery note) but I send the data all together to the PHP controller.
Now, I parse the data ( reading from $("#jsGrid").jsGrid("option", "data") ) on a hidden field before the form is submitted but it's not very "elegant" altough it's working, is there a more efficient solution?

Thank you.

**Comment by richraid21** [comment]
It would be helpful if you posted your code. That way others can see what you have tried and attempt to build on it or point out any errors.

**Comment by gonzalobrandan** [comment]
After I insert or update the items in the grid, I do the following

var AUX = $("#jsGrid").jsGrid("option", "data"); //to get all the items from the grid
var AUX2 = JSON.stringify(AUX);
$("#txtGrid").val(AUX2);

Where txtGrid it's a textarea that is hidden.

Thanks!

**Comment by tabalinas** [comment]
I'm not sure it's a jsgrid-related question. It's up to you how you post data to the backend.
It can be done the way you described. But more usual way would be to define grid controller. (http://js-grid.com/docs/#grid-controller).
