### ISSUE TITLE
Multiple jsGrids and Finish Delete Event

### ISSUE THREAD

**Issue by michaeldeongreen** [tabalinas/jsgrid#899]
I don't believe that what I describe below is a bug, it is akward functionality and maybe a change can be implemented to make the implementation more intuitive.

1) When I use: "jsGrid.loadStrategies.DirectLoadingStrategy.prototype.finishDelete" on 1 jsGrid (let's call it jsGridA), I expect this event to only fire on the jsGrid that the event is setup for.

2) I have about 5 jsGrids on a Screen and whenever I delete an item from any jsGrid, jsGridA's finishDelete Event is always called.

3) The finishDelete Event for jsGridA should only fire when I delete an item from jsGridA.

Here is the original code:
```
 jsGrid.loadStrategies.DirectLoadingStrategy.prototype.finishDelete = function (deletedItem, deletedItemIndex) {
            var grid = this._grid;
            grid.option("data").splice(deletedItemIndex, 1);
            var $row = grid.rowByItem(deletedItem);
            $row.fadeOut({
                done: function () {
                    $row.remove();
                       self.parentViewModel.contract().supplierRequests([]);
                       that.supplierRequestChanged();
                }
            });
        };
```

Here is the workaround I implemented:

```
 jsGrid.loadStrategies.DirectLoadingStrategy.prototype.finishDelete = function (deletedItem, deletedItemIndex) {
            var grid = this._grid;
            grid.option("data").splice(deletedItemIndex, 1);
            var $row = grid.rowByItem(deletedItem);
            $row.fadeOut({
                done: function () {
                    $row.remove();
                    var gridId = grid._container[0].id; //<----checking to see what jsGrid fired the finishDelete Event by the DIV container id
                    if (gridId == 'selectedSupplierRequestsGrid') {
                        self.parentViewModel.contract().supplierRequests([]);
                        that.supplierRequestChanged();
                    }
                }
            });
        };
```

**Comment by tabalinas** [comment]
This is how `prototype` works in javascript. It's shared between all the instances. If you want to define custom load strategy for a single grid, then create new load strategy (see docs: http://js-grid.com/docs/#custom-loadstrategy) and set this strategy only for this grid.

Good article explaining how prototypes work in javascript - http://sporto.github.io/blog/2013/02/22/a-plain-english-guide-to-javascript-prototypes/
