### ISSUE TITLE
Column for object child

### ISSUE THREAD

**Issue by 5p1k3md** [tabalinas/jsgrid#901]
Help Request/Question:

A) Clearly state your problem:
I try to access a child of an object as field name.

B) Include your code
My attempt was : 
`{ name: "CompanyAmount.SubCompanyAmount", type: "number", title: "SubCompany" }
`    

But this doesn't work.
How does i have to do it?

**Comment by 5p1k3md** [comment]
I'm one step closer to solution.

I builded a custom field for the value.

This works if the object has only one child element.

In my case the object has X child elements.
So I tried to build a loop to create the fields, here is my code:

The loop:
```
//Genrate fields
for (var i = 1; i < data.Count + 1; i++) {
      GenerateAmountFields(i);
}
 ```
data.count is the number of childs.

The function:

```
//generate custom field for amounts
function GenerateAmountFields(i) {
     var AmountField = {};

     //field for amount
     AmountField["AmountField" + i] = function (config) {
          jsGrid.Field.call(this, config);
     };

     AmountField["AmountField" + i].prototype = new jsGrid.Field({

          //properties
          editing: false,

          //templates
          itemTemplate: function (value) {

               var amount = value(i).HirerAmount; 

               return amount;
          }
     });

     var ident = ["amount" + i];

     //define
     jsGrid.fields.ident = AmountField["AmountField" + i];

    }
```
Everything goes fine, field got created correct (i think), but it is not added to the grid fields.

Any advices?

**Comment by 5p1k3md** [comment]
I got it fixed on my own.
See [this working fiddle](https://jsfiddle.net/vxec1kj7/4/).

**Comment by vyasrohit1983** [comment]
Hello I have to bind the column dynamically in jsGrid, I have all the column name in json object all the column types are of check box type, kindly help me., How can I bind the column dynamically in jsGrid and set colum type as check box ...
