### ISSUE TITLE
Filter is not working .

### ISSUE THREAD

**Issue by HananAlasari** [tabalinas/jsgrid#902]
i have a problem  the filter jsGrid not working after implement the jsGrid any idea?

**Comment by heiovsky** [comment]
Flying Dutchman switched off filtering.

**Comment by HananAlasari** [comment]
i tried also to implement the jqGrid in a simple template html and  filtering doesn't work also i dont know what i'm missing.

**Comment by heiovsky** [comment]
just show jsGrid configuration

**Comment by tabalinas** [comment]
Please, checkout the following issue https://github.com/tabalinas/jsgrid/issues/32
