### ISSUE TITLE
How to get the last row of grid and make it bold

### ISSUE THREAD

**Issue by 5p1k3md** [tabalinas/jsgrid#903]
Question:

A) Clearly state your problem

I would like to add the following style to the last row (and column if possible).

B) Include your code

`style="font-weight:bold;"`

**Comment by heiovsky** [comment]
add this to jsgrid css file
.jsgrid-body > tr:last-child { font-weight:bold; }

**Comment by 5p1k3md** [comment]
Unfortunately this didn't do the trick for me.
In addition i don't want to do this for all grids in the project, but only for one specific.

**Comment by 5p1k3md** [comment]
See this [fiddle ](https://jsfiddle.net/vxec1kj7/5/) please.
Did i make a mistake?

**Comment by heiovsky** [comment]
I made a mistake
see this working:
https://jsfiddle.net/vxec1kj7/6/

**Comment by tabalinas** [comment]
@heiovsky, thank you for the answer and working fiddle!
