### ISSUE TITLE
Saving Changes

### ISSUE THREAD

**Issue by rennerund** [tabalinas/jsgrid#904]
Hi,

i'n new in programming and tried to implement jsgrid.
It works good , but the script does not change any changes or new data into db.js?
On reload of the page all changes are gone?

Thank you for your support.

BR
Rene

**Comment by uniquejava** [comment]
What's your `db.js` used for?  
What do you mean by `on reload`? Call the `loadData` API or refresh the whole page, have you verified that your data is persistent into your database.

Without any context, It's hard to answer your question.

**Comment by tabalinas** [comment]
@uniquejava asked exactly right questions.
jsgrid is a client-script. To have new data after page refresh you have to persist them in the storage on the server-side. The easiest is a REST service on the backend serving data for the grid and handling CRUD operations. jsGrid allows to define grid [controller](http://js-grid.com/docs/#grid-controller) to work with this backend service.
