### ISSUE TITLE
Generating fields from C# controller (Help Wanted)

### ISSUE THREAD

**Issue by nyihtway** [tabalinas/jsgrid#905]
Hi,

I'm using JSGrid in my ASP.Net web application. I'm trying to pass the fields from the Controller class (via ViewBag). My code works well for normal fields. But for the fields with headerTemplate and itemTemplate, I can't figure out how to do it. Helps will be much appreciated. following is my sample code in C#. 

	public class HomeController : Controller
    {
		public ActionResult Index()
        {
            List<GridColumn> columns = new List<GridColumn>();
            columns.Add(new GridColumn() { name = "Name", type = "text", width = 150 });
            columns.Add(new GridColumn() { name = "Age", type = "text", width = 50 });
            columns.Add(new GridColumn() { name = "Address", type = "text", width = 200 });
            ViewBag.columns = JsonConvert.SerializeObject(columns);

            return View();
        }
	}

**Comment by 5p1k3md** [comment]
Regarding to my issue [#901](https://github.com/tabalinas/jsgrid/issues/901) you have to do the following:

Pass the itemTemplate with the desired function and generate a new function for this from js side.

Example:
```
public class HomeController : Controller
{
	public ActionResult Index()
    {
        List<GridColumn> columns = new List<GridColumn>();
        columns.Add(new GridColumn() { name = "Name", type = "text", width = 150, itemTemplate = "return value[" + i + "].SubCompanyAmount" });
        ViewBag.columns = JsonConvert.SerializeObject(columns);

        return View();
    }
}
```
On JS-side:
```
 for (i = 0; i < 1; i++) {
    var field = {};

    field.itemTemplate = new Function("value", field.itemTemplate)

    fields.push(field);
  }
```
Grid config:

```
 $("#jsGrid").jsGrid({
...
    fields: fields,
...
  });
```

**Comment by nyihtway** [comment]
Great! it works.

**Comment by tabalinas** [comment]
@5p1k3md, thanks for the answer!
