### ISSUE TITLE
[Question] How to style input filter dropdown

### ISSUE THREAD

**Issue by erndev** [tabalinas/jsgrid#907]
I've been reading the docs and i haven't found a proper way to change the filter dropdown class.
Is there any way to do it? 

I've seen that we can create a custom filter field via prototype, but it seems too much just to change the combo's class.

right now i've solved it via jquery, iterating through the existing <select> controls, and changing the class. But does not seem to be very nice way.

thanks

**Comment by tabalinas** [comment]
You `filtercss` option of the [field config](http://js-grid.com/docs/#fields) to set custom css class of the filtering field. If you want to set styles for the `select` use usual css rule like `.my-custom-cls select`.
