### ISSUE TITLE
data is null then message not found  is not working tabalinas/js-grid

### ISSUE THREAD

**Issue by mayankvadiya** [tabalinas/jsgrid#908]
I want to display message "Not Found" when my ajax request getting NULL response. 
What I had tried is below:
```
loadData: function() {
                    var d = $.Deferred();
                        $.get('web-service/web/master/display',  {
                            inactive: active,val:inputVal
                        }, function(data, textStatus, xhr) {
                            if (data.status==200) {
                                console.log("item data",data)
                               d.resolve(data.data)
                            }else{
                               d.resolve()
                            }
                        });
                        return d.promise()
                }
```

**Comment by heiovsky** [comment]
Check if data returned from ajax is empty and return {data:[],itemsCount:0}


12.09.2017 16:15 "mayankvadiya" <notifications@github.com> napisał(a):

**Comment by heiovsky** [comment]
loadData: function() {
                    var d = $.Deferred();
                        $.get('web-service/web/master/display',  {
                            inactive: active,val:inputVal
                        }, function(data, textStatus, xhr) {
                            if (data.status==200) {
                                console.log("item data",data)
                               d.resolve(data.data)
                            }else{
                               d.resolve({data:[],itemsCount:0})
                            }
                        });
                        return d.promise()
                }

**Comment by mayankvadiya** [comment]
Thanks @heiovsky , for the great answer.
Here I have also find one another method is like below
`$(".jsgrid").jsGrid('option', 'data', []); `
