### ISSUE TITLE
How to clear jsgrid and display `No Record` message.

### ISSUE THREAD

**Issue by chiragsatapara** [tabalinas/jsgrid#909]
How to clear jsgrid , i want to clear jsgrid on button click and want to display `No record found` , message into the grid.

**Comment by heiovsky** [comment]
One simple question. Is documentation pain for you? 
Turbo jsGrid tutorial by me:
1) turn on thinking
2) if you need something -> go docs and read it carefully
3) no answer in docs? -> check github existing issues
4) still no answer?turn on thinking again, smoke a cigarette
5) no answer? open issue

Solution:
http://js-grid.com/docs/#optionoptionname-optionvalue
http://jsfiddle.net/n982uvx1/122/

**Comment by chiragsatapara** [comment]
@heiovsky thanks for your answer , it is very helpful to me.

actually i am trying to pass data in render like this : render(data); and data=[]; but jsgrid not refreshing the data , i tried everything , spend one day for this  and finally i generate the issue in github.

thank you so much for your helpful answer.
