### ISSUE TITLE
Bulk edit selected rows with given values

### ISSUE THREAD

**Issue by priyarathi** [tabalinas/jsgrid#910]
Hi, 

I have country, state and city fields in my JS Grid along with a checkbox column. 
I have selected in destination country, State, City cascading drop downs on top of my form.
I want to select muliple js grid rows and click on update button. 
As a result, for all checked rows - country, state, city columns should be updated with what I have selected in destination dropdowns at the start of my form.

Is it possible with Batch Update?

Thanks,
Priya

**Comment by jreast** [comment]
I'd recommend doing the edit server side and refreshing the grid. You can do exactly the same as the Batch Delete demo http://js-grid.com/demos/ but obviously the deleteClientsFromDb function would be an ajax call to your server with a list of IDs from selectedItems, and the values from your dropdowns. In the success callback either send the updated grid data back, or trigger a loadData on the grid to re-fetch.

**Comment by priyarathi** [comment]
Thanks! I will try this solution!
