### ISSUE TITLE
how resize cell width and height

### ISSUE THREAD

**Issue by mdemori** [tabalinas/jsgrid#914]
Hello, 

i've a little problem, some of cells are wider and higher than desired, i try to resize all cells using "width" property of fields but the result is different from expected, same for height

![image](https://user-images.githubusercontent.com/2266315/30387762-e447ff86-98ad-11e7-96b1-382b519ea458.png)

currently my field setup is as below:

```
fields: [
 { name: "ordpos", title: "Pos.", type: "number", width: 3 },
 { name: "ordpos2", title: "Pos.<br /> ERP", type: "text", width: 3 }, 
]

```
but, even if i assigned 3 as width the real cell width is always greater than desired. There is way to remove padding and all margin inside the cell ? i try also to override css setting but with little success.
My Css is as below:

```
.jsgrid-cell{
  font-size:0.85em;
  padding:0.3em !important;
  line-height:1;
}

.jsgrid-header-cell{
  font-size:0.85em;
  padding:0.3em !important;
  line-height:1;
}
```

how can i solve this problem?

**Comment by jreast** [comment]
Check if you are setting the grid width to 100%, if so column widths will be ignored:
```
$("#jsGrid").jsGrid({
        width: "100%",
...
```

**Comment by tabalinas** [comment]
@mdemori, could you provide your grid config?
Having a jsfiddle reproducing the issue would be perfect to identify the culprit.

**Comment by tabalinas** [comment]
No answer
