### ISSUE TITLE
Fields with "." (period) in the name break grid

### ISSUE THREAD

**Issue by jwtc** [tabalinas/jsgrid#916]
Bug Report

When using a static data array, if key names include "." (i.e., ASCII 46, "full stop"), then the value for that field is not displayed in the grid.

Expected Behavior:
```
var counts = [{"Grade Level": 9, "GPA 4.0": 23}];
$("#target").jsGrid({
  data: counts,
  fields: [{ name: "Grade Level",   type: "number"}, { name: "GPA 4.0", type: "number"}]
});

Grade Level | GPA 4.0
----------------------
|         9 |     23 |
----------------------
```

Actual Behavior
```
var counts = [{"Grade Level": 9, "GPA 4.0": 23}];
$("#target").jsGrid({
  data: counts,
  fields: [{ name: "Grade Level",   type: "number"}, { name: "GPA 4.0", type: "number"}]
});

Grade Level | GPA 4.0
----------------------
|         9 |        |
----------------------
```
Steps to reproduce:
[Fiddle](http://jsfiddle.net/Jefw/Lf7LngL6/)

**Comment by heiovsky** [comment]
First. Go to docs and read it then think what a sh*t issue you had written.
Who the f*ck uses spaces or dots in column names. Go try using spaces and dots in variable/column name with any database,programming lang -> Result: errorrrrrrrrrrrrrrrrrrrrrr
For column name you have magic property called 'title'. Property 'name' is used for dealing with JS array and JSON

**Comment by jwtc** [comment]
@heiovsky - your swearing and insulting makes it difficult to assume no malice, but to your points:

I have read the documentation.  It does not address this issue.  Unless I have missed it, there are no mentions of characters that are unsafe for use in key strings, or any other configuration area.  If I am wrong about this, please point me to the specific area I've missed and accept my apologies.

String literals are valid property name in JS, and may indeed contain spaces and dots, and all sorts of other unusual things beside.  Also, data doesn't always come from well-designed sources.  In my case, not that its any of your business, the offending data comes from a table alias in a programmatically generated query using a large and well established data dictionary.  (I.e, I cannot change it) which is replete with decimal points because it deals with demographic factors, ratios, and proportions.  In most cases, the decimal points convey important meaning.

Of course, I can translate these into a key name that will work within the constraints imposed by jsgrid, and map these to an appropriate label for use in the label property. In fact I have done so.  But absent intentional design to the contrary, this is a workaround, which by definition implies a bug.

In my view, the very best software comes from casting the widest net for boundary and obscure use cases, and making a considered decision about them.  If this is too rare a use case to be worth the trouble of fixing the bug, that's a question @tabalinas or other maintainers.  I make no value judgement either way.

Regards.

**Comment by uniquejava** [comment]
Hi, you can define a title property for the field definition, like this: `fields: [{ name: 'gradeLevel,   type: "number",  title: "Grade Level"}`

I've never seen any field name(used as key) has spaces or dot, also the dot notation is used for accessing nested object or array elements. I think you are in the wrong direction.

**Comment by tabalinas** [comment]
@jwtc, as @uniquejava said, dot `.` is used for nested objects. So grid tries to access `item["GPA 4"][0]`, which obviously doesn't exist.
I agree that this should be clearly stated in docs.
As for the bug report, no fix is required.
