### ISSUE TITLE
How to add a css class to the last row in jsGrid

### ISSUE THREAD

**Issue by Morehammered99** [tabalinas/jsgrid#917]
I want to add some styling to the last row in my grid. I wont know what the row number is as there could be any number of rows. How can I go about this? I've seen rowClass and rowRenderer but not a working example. Here is the code I have:

    var displayData = function (itemViewModelList) {
                    var fields = [
                            {
                                name: 'ConsultantName', type: 'text', width: 100, title: 'Consultant Name'
                            },
                            {
                                name: 'BranchName', type: 'text', width: 100, title: 'Branch Name', css: "red"
                            },
                            { name: 'NumberOfInvestments', type: 'text', title: 'Number Of Investments' },
                            {
                                name: 'ValueOfInvestments', type: 'money', width: 150, title: 'Value Of Investments',
                                itemTemplate: function (value) {
                                    return tisCommon.formatForMoney(value);
                                }
                            },
                            {
                                name: 'AverageValueOfInvestments', type: 'money', width: 150, title: 'Average Value Of Investments',
                                itemTemplate: function (value) {
                                    return tisCommon.formatForMoney(value);
                                }
                            },
                            {
                                name: 'Month', type: 'text', width: 100, title: 'Month',
                                itemTemplate: function (value) {
                                    return moment(value, 'M').format('MMMM');;
                                }
                            },
                    ];

                var options = {
                    inserting: false,
                    editing: false,
                    pageSize: 20,
                    fields: fields,
                    rowHeaders: false,
                    colHeaders: false,
                    
                    data: itemViewModelList,
                    controller: controller = {
                        loadData: function () {                        
                        },
                    },
                };
                $('#investment-grid').tisGrid('', options);
                
                if (itemViewModelList[0].ConsultantName != null) {
                    $("#investment-grid").jsGrid("fieldOption", "BranchName", "visible", false);
                } else {
                    $("#investment-grid").jsGrid("fieldOption", "ConsultantName", "visible", false);
                }
            };

My data being passed "itemViewModelList" is an array of objects

**Comment by heiovsky** [comment]
https://github.com/tabalinas/jsgrid/issues/903

**Comment by Morehammered99** [comment]
Thanks @heiovsky that would work, but that would also affect all grids. I have many grid in my system but only want this effect on 1 grid... any suggestions?

**Comment by heiovsky** [comment]
Add this in "style" tag on your page or prefix it with grid id

#jsgrid .jsgrid-table tbody ...

**Comment by tabalinas** [comment]
@heiovsky, thanks for the answer!
