### ISSUE TITLE
Add new row at the end

### ISSUE THREAD

**Issue by arijitchatterjee1** [tabalinas/jsgrid#918]
How can I show add new row at the end all the time ? Using it in an invoice design, and the new row should be visible all the time as the last item
please suggest

**Comment by jreast** [comment]
You might be able to bind to the onRefreshed event and grab a reference to the grid instance, and the insert row, and then append it to a tfoot element instead. You'll either need to create the tfoot inside the jsgrid-grid-body or you could create an extra jsgrid-table just for the insert row.

```
var insertRowMoved = false;

...

onRefreshed: function (args) {
    if (!insertRowMoved) {
        var insertRow = args.grid._insertRow;
        var gridBody = args.grid._bodyGrid;
        $( "<tfoot></tfoot>" ).appendTo(gridBody).append(insertRow);
    }
},
```

**Comment by tabalinas** [comment]
See also this workaround https://github.com/tabalinas/jsgrid/issues/224#issuecomment-195133516 (it uses the same approach as @jreast described above)
