### ISSUE TITLE
On one checkbox un-checked then another specific checkbox in the same row need to be disabled 

### ISSUE THREAD

**Issue by Nagavali** [tabalinas/jsgrid#919]
I have a requirement where I have two different checkbox columns in JSGrid. Assume check1 and check2 checkboxes.

If I checked check1 checkbox then check2 checkbox has to be enabled to allow change. 
If I unchecked check1 checkbox then check2 checkbox has to be disabled.

**Comment by subratasingharoy** [comment]
I have similar kind of requirement 
1. While inserting a row, on a checkbox checked, wanted to disable a number fields in JSGrid. 
2. Initially JSGrid Inserting, Editing & Deleting set false. Wanted to set Inserting, Editing & Deleting  value as true on a Button clicked.

Any quick help appreciated.

**Comment by jreast** [comment]
Have a look at how to use a custom insertTemplate to bind a change event to the checkbox and then manipulate other fields similar to the way dropdowns are handled in #71 with this fiddle http://jsfiddle.net/tabalinas/n982uvx1/13/

**Comment by Nagavali** [comment]
When I have multiple checkboxes in row then how to disable particular checkbox dynamically.

**Comment by Nagavali** [comment]
Hi All,
My requirement is I have two checkboxes Named as "Active" and "Testing". While doing row edit, if "Active" checkbox is not checked then I should not allow "Testing" checkbox to check, instead I have give alert saying Active Should be checked first. For this I am using the below code..

{name:"Testing", width:50,itemTemplate: function(value, item) {
                    return $("<input>").attr("type", "checkbox")  .on("change", function() {
                       item.Checked = $(this).is(":checked");
                       if(!item.Active && item.Checked) {
                         alert('Check Active First');
                         $(this).prop("checked", false);
                        }
                    });
                }
            }

Here the problem is Initially "item.Active" is retrieving only initial value at the time of row edit button. After I changed Active checkbox status and next checked Testing checkbox then here "item.Active" is not giving the updated Active checkbox value.

**Comment by tabalinas** [comment]
@Nagavali, could you reproduce it with a jsfiddle (you can fork the one from @jreast comment above)?
