### ISSUE TITLE
Dynamically set Inserting, Editing, Deleting value as true in JSGrid, when initially set the value as false

### ISSUE THREAD

**Issue by subratasingharoy** [tabalinas/jsgrid#920]
I have of requirement 
1. While inserting a row, on a checkbox checked, wanted to disable a number fields in JSGrid. 
2. Initially JSGrid Inserting, Editing & Deleting set false. Wanted to set Inserting, Editing & Deleting  value as true on a Button clicked.

Any quick help appreciated.

**Comment by jreast** [comment]
1. Have a look at how to use a custom insertTemplate to bind a change event to the checkbox and then manipulate other fields similar to the way dropdowns are handled in #71 with this fiddle http://jsfiddle.net/tabalinas/n982uvx1/13/
2. See the Custom View example here http://js-grid.com/demos/

**Comment by tabalinas** [comment]
@subratasingharoy, did you manage to meet your requirements?
