### ISSUE TITLE
How to list all option on edit after filter

### ISSUE THREAD

**Issue by Hunter85** [tabalinas/jsgrid#922]
Hello,

I am looking for some advise on how to list ALL options in a select when row is being edited AFTER filtering.  Currently when I filter on one column I filter the options of the other columns.  After a filter, I edit a row which in return only shows the filtered options.  I am wanting to list all options when editing due to the fact that the user is wanting to change the value to options outside what is filtered.  
Please use the jsfiddle link below and follow the example below.
Notice the TYPE column has D and O as options.  
Filter STATE to IA.   
Click pencil to edit this one row.
Click TYPE select.  D is the only option.  

Here I am wanting to have the ability to change to any(D,O) options.  I understand the "custom" filter is causing this.  Please let me know what I can do to make this possible

JSFiddle link below will help understand.
http://jsfiddle.net/jkhowell/yef3xwh4/23/

**Comment by tabalinas** [comment]
You have to redefine `editTemplate` of the `TYPE` field (since you want it to work differently.
To avoid rendering `select` yourself use the following trick:

```js
editTemplate: function(value) {
    var originalItems = this.items;
    this.items = types;
    var $result = this.editControl = this._createSelect();
    this.items = originalItems;
                    
    (value !== undefined) && $result.val(value);
                    
    return $result;
} 
```

Here is the working fiddle http://jsfiddle.net/tabalinas/yef3xwh4/25/

**Comment by bvasnake** [comment]
Hi,
how i can implement this technology [`http://jsfiddle.net/tabalinas/yef3xwh4/25/`](http://jsfiddle.net/tabalinas/yef3xwh4/25/)  using data bases
