### ISSUE TITLE
Custom sorter issue

### ISSUE THREAD

**Issue by yleshchuk** [tabalinas/jsgrid#925]
Hello,

First of all, thank you for this amazing grid, I use it all the time.

I'm implementing multi column sort and looks like there is an issue with jsGrid("option", "data") when using custom sorter.

There is fiddle to reproduce the issue: https://jsfiddle.net/yleshchuk/cbv88kya/
Reproducible only in Chrome, Firefox works fine.

As you can see when I use $("#jsGrid").jsGrid("option", "data"), it returns invalid list of items with duplicated item instead some valid item.

I know, this can be fixed by using external array with items, but I'm filing grid dynamically and one more place to sync items does not sound as good solution.

**Comment by tabalinas** [comment]
That looks bizarre indeed. Actually `$("#jsGrid").jsGrid("option", "data")` just returns the reference to the arrays passed from `loadData`. 

In this fiddle we see, that this happens even w/o jsgrid:
https://jsfiddle.net/tabalinas/08sy8z5q/

Any thoughts?

**Comment by tabalinas** [comment]
No answer.
