### ISSUE TITLE
onItemInserting fires after submitting

### ISSUE THREAD

**Issue by ragerory** [tabalinas/jsgrid#926]
I'm trying to dynamically show a column only for the insert row template called comments. When I place this in onItemInserting, it **only** shows after I click the insert button + on the row, and then it goes away after it's inserted. I'm trying to have this column be shown on the insert row when I display the insert row. How can I have this column be shown when I actually click the big + when showing the insert row?

```
    onItemInserting: function (args) { // this doesn't get fired when the insert row is shown
        edit = false;
        $('#mrcGrid').jsGrid('fieldOption', 'Comments', 'visible', 'true');
    },
    onItemInserted: function(args) {
        $('#mrcGrid').jsGrid('fieldOption', 'Comments', 'visible', false);
    },
```

**Comment by tabalinas** [comment]
Then you can put this in `onOptionChanged` callback http://js-grid.com/docs/#onoptionchanged.
Show this field when `inserting` option is set to `true` and hide otherwise.
