### ISSUE TITLE
Help with custom fields

### ISSUE THREAD

**Issue by fredericoregateiro** [tabalinas/jsgrid#927]
I'm creating some custom fields to use with jsGrid, and i cannot get the filter to work properly.

The code i'm creating:
[decimal field](https://codepen.io/regateiro/pen/wrgNzM)
[bootstrap - datetimepicker](https://codepen.io/regateiro/pen/qPRpPp)

Can anyone help me?

Thanks

**Comment by tabalinas** [comment]
Please checkout this example showing how to implement filter for datetime: https://github.com/tabalinas/jsgrid/issues/60#issuecomment-119648998
It should be similar for datetimepicker.
For decimal it's also similar: having two fields for decimal range.
