### ISSUE TITLE
Two connected select fields 

### ISSUE THREAD

**Issue by ToherIman** [tabalinas/jsgrid#929]
I need to make items of one select field depend on value of other select field. 
So it is possible to choose from smaller list. 
For example:
items1: [a, b, c]; items2: [1,2,3]
if (a) { 1,2 }
if (b) {3}
if (c) {1,2,3}
Read all related issues and posts. If there is solution, please help.

**Comment by jreast** [comment]
See @tabalinas answer to #46 and the jsfiddle http://jsfiddle.net/tabalinas/n982uvx1/

**Comment by ToherIman** [comment]
Thank you for answer. But this solution is for filtering data, not options itself. And it's not very lightweight. I have huge table, and this window db cause. I managed to do something like this but it's too many options and it not works fast. So I just added check before submit.

**Comment by tabalinas** [comment]
@ToherIman, have you tried to figure out where is the bottle neck? I doubt it's array filtering itself.
