### ISSUE TITLE
hiding certain rows from the entire table

### ISSUE THREAD

**Issue by lnyuan** [tabalinas/jsgrid#930]
Hi,

I want to be able to hide certain rows depending on the value of a certain column. Currently, I am able to do this, however, it only works on the first page. Further, if I move to a different page and then back to the first page, the initially hidden rows show up again. 

I have included the following code in loadData:
```js
$('#jsGrid tr td:nth-last-child(2)').each(function(){
      if ($(this).text() == "Archive" ){
          $(this).closest('#jsGrid tr').hide();
      }
});
```
I saw on other posts that I could access all the rows by using $("#jsGrid").jsGrid("option", "data");, but I'm a little unclear as to how to get the corresponding row in the grid. I tried the following as well:
```js
var allRows = $("#jsGrid").jsGrid("option", "data"); 
$.each(allRows, function(index,value){
     if(value["columnname"]=="Archive"){ 
          //hide
     }
});
```
Is there anyway to access all the rows in grid and hide them regardless of which page the user is on? For Datatables, users can use .fnGetNodes() to do this but I can't seem to find the equivalent to jsGrid. 

Thanks!

**Comment by tabalinas** [comment]
First, you could use `rowClass` http://js-grid.com/docs/#rowclass and add a hiding class by condition.

As of your initial approach, you could put this logic to `onRefreshed` so that it will be applied right after grid items refreshed.
