### ISSUE TITLE
How to get the selected value of a cell?

### ISSUE THREAD

**Issue by thilankascentic** [tabalinas/jsgrid#934]
Hi,
In my grid, there is a drop-down column, so I want to change a value of another cell (same row) according to selection of drop-down cell.
I checked the documentation but I could not able to find the method/event that using to get the value of dropdown item change,

and how to change another cell's value within that.

if anyone can help me with that would be very much appreciate.
Thanks

**Comment by thilankascentic** [comment]
any helpwould be appreciate

**Comment by thilankascentic** [comment]
Hi @tabalinas 
I've implemented both onItemUpdating and onItemUpdated functions but those are not executing when changing a cell value,
In my grid, I dont have a separate column for update, i want to update other column's value when switching to cell, hence I need to get the value on cell click,

a little help please?

**Comment by tabalinas** [comment]
@thilankascentic, are you talking about something related to https://github.com/tabalinas/jsgrid/issues/929#issuecomment-333538846?
