### ISSUE TITLE
refresh only column

### ISSUE THREAD

**Issue by fdourado** [tabalinas/jsgrid#935]
Hi, 

I have a grid with 3 input text box per row, but when i put any value in any textbox i must calculate total price and refresh at this column total

Why can you use refresh grid? because i lost focus from cursor and cant use tab key which reduces navigability, because that i must just refresh total column, this is my code:

  $("#dvPedido").jsGrid({
        height: "250px",
        width: "100%",
        autoload: true,
        autoload: true,
        sorting: true,
        fields: [
            { name: "strCodigo", title: "Codigo", type: "text", width: 20, align: "center" },
            { name: "strDescricao", title: "Produto", editing: false, width: 60, type: "text" },
            { name: "strPrecoDesconto", title: "Valor", type: "text", width: 5, align: "center" },
            {
                headerTemplate: "Venda",
                itemTemplate: function (e, item) {
                    return $("<input>").attr("type", "textbox").css("width", "35px")
                          CalculaTotalItem(item);
                          $("#dvPedido").jsGrid("refresh");
                      })
                },
                align: "center",
                width: 10
            },
            {
                headerTemplate: "Bonif",
                itemTemplate: function (e, item) {
                        return $("<input>").attr("type", "textbox").css("width", "35px").val(item.intBonif).
                              CalculaTotalItem(item);
                              $("#dvPedido").jsGrid("refresh");
                          });
                    }
                },
            },
            {
                headerTemplate: "Troca",
                itemTemplate: function (e, item) {
                    if (item.strCodigo == "") {
                        return }
                    return $("<input>").attr("type", "textbox").css("width", "35px")
                          .val(item.intTroca).on("change", function (e) {
                              CalculaTotalItem(item);
                              $("#dvPedido").jsGrid("refresh");
                          });
                },
                align: "center",
                width: 10
            },
            { name: "strTotal", title: "Total", type: "text", width: 20, align: "center" },
            {
                headerTemplate: "",
                itemTemplate: function (value, item) {
                    var $result = jsGrid.fields.control.prototype.itemTemplate.apply(this, arguments);
                    var $customButton = $("<button>")
                       .addClass("btnRemove");
                    return $result.add($customButton);
                },
                align: "center",
                width: 5,
            }
        ],
        data: gridProdutos
    });

**Comment by tabalinas** [comment]
if you don't want to call `refresh` you have to change the value manually, for instance on `change` event of the field.

PS GitHub support markedown, please paste your code as code, not as plain text.
