### ISSUE TITLE
create subgrid when click arrow

### ISSUE THREAD

**Issue by amin750** [tabalinas/jsgrid#937]
I want a subgrid like the picture below, which is the arrow in the left column and open subgrid when click it
![capture](https://user-images.githubusercontent.com/19873094/31338287-6f84ff6a-ad0b-11e7-9d1f-a94a06f6a16b.JPG)

**Comment by tabalinas** [comment]
This is the basic example showing the main idea: http://jsfiddle.net/tabalinas/vc1wm99n/
This one is closer to your case: http://jsfiddle.net/9ftwLsmf/. The arrow on the left should be added to the main grid row.

**Comment by onsac** [comment]
Hello Amin750,

You can share your code? I need the same solution.

Best regards,

Ronaldo

**Comment by gokulakrishnan4750** [comment]
Hi, 
i need the code for same as shown in above

pls help me asap.
