### ISSUE TITLE
Maximum row reach?

### ISSUE THREAD

**Issue by gattidaniel** [tabalinas/jsgrid#939]
I am having a problem. While, not many rows works ok, when I have many of them it doesn't work, showing the no data message. 

I am calling the json with the load data method of controller
```js
 controller: {
            loadData: function (filter) {
                return $.ajax({
                    type: "GET",
                    url: urlLoadData,
                    data: filter,
                    dataType: "json"
                });
            },
        },
```

The json in both cases is ok. Is any limit on characters length? (it has 1265496 characters)

Thanks

**Comment by tabalinas** [comment]
Probably this is just to much for the browser to render. Virtual scrolling is not supported out-of-box.
I suggest you considering loading data by pages, loading huge amount of data to the client at once is not the best design anyway, for instance what's going to happen on mobile...
