### ISSUE TITLE
Can't filter with static data

### ISSUE THREAD

**Issue by Alonzzzo2** [tabalinas/jsgrid#94]
When I try to work with static data and not with the controller, after I enter a value to one of the int fields and press enter, I can see the this.data is undefined...
I took a look at the demos - static data, and didn't understand what I'm doing wrong...
Here's my js code which runs on page load:

```javascript
function jsgridStart(taskID)
{
    $.getJSON("/Jobs/JobsData/" + taskID, function (data) {
        jsGridData = data;
        $("#jsgrid").jsGrid({
            height: "610px",
            width: "100%",

            filtering: true,
            sorting: true,
            paging: true,

            pageSize: 500,
            pageButtonCount: 5,
            autoload: false,
            data: jsGridData, // an array of data
            fields: [
                { name: "DeviceID", title: "Device ID", type: "text", width: 150 },
                { name: "RunResult", title: "Run Result", type: "number", width: 50 },
                { name: "JobResult", title: "Job Result", type: "number", width: 200 },
                { name: "JobResultValue", title: "Job Result Value", type: "number" },
                { name: "ExtendedResult", title: "Extended Result", type: "text" },
                { name: "Comments", title: "Comments", type: "text" },
                { name: "TimeOfRun", title: "Time Of Run", type: "text" }
            ]
        });
    });       
}
```

Hope this is the right way to ask for this kind of help. if not, can you please tell me how?
Thanks you very much!

**Comment by tabalinas** [comment]
I've reproduced the issue. Thank you for the report.
Anyway, filtering is completely developer responsibility  (read about that in the ticket https://github.com/tabalinas/jsgrid/issues/32). That's why your filtering won't work without controller  anyway.
