### ISSUE TITLE
How to Open grid at specified item?

### ISSUE THREAD

**Issue by RebeccaArt** [tabalinas/jsgrid#940]
Help Request
I would like to be able to load the grid as part of a PHP file and initialise it to open at a specific item on load. Is there a simple way to do this?

**Comment by tabalinas** [comment]
I assume you have paging enabled. In this case, knowing the ordering, you can calculate the page index of the item. Specify `pageIndex` in grid config, so it will be rendered on the particular page, so the item is going to be displayed.
