### ISSUE TITLE
How to add new line or br each press Enter in jsGrid Input ?

### ISSUE THREAD

**Issue by Kyodo-samurai** [tabalinas/jsgrid#943]
##
  ##![jsgrid-help](https://user-images.githubusercontent.com/2525537/31814840-05a9e350-b5b5-11e7-9f8d-17d5401ea53e.gif)
 Hi,

In my Grid, i need to add new line to Grid input

this is image to show clear my problem http://ibb.co/iHdbmR

Anyone can help me
Thanks!

**Comment by tabalinas** [comment]
Looks like you want to use `textarea` field instead of `text` field
