### ISSUE TITLE
filterRowRenderer example

### ISSUE THREAD

**Issue by jdelate** [tabalinas/jsgrid#946]
Are there any examples of implementing a filterRowRenderer?

I keep getting "Uncaught TypeError: Cannot read property 'val' of undefined.

I have multiple nested/grouped grids and would like to filter on children and child properties.

**Comment by tabalinas** [comment]
Could you provide more details? 
Where exactly do you get this error?
Having access to a public resource (jsfiddle or alike) demonstrating the issue would be helpful.

**Comment by anki7scorp** [comment]
@tabalinas Could you please provide an example link or reference link for your statement?
