### ISSUE TITLE
Changing Grid behaviour: multiple checkboxes, no double click and submit changes one time

### ISSUE THREAD

**Issue by raptus84** [tabalinas/jsgrid#947]
Hi,
I'm facing problems changing grid behavior this way: I have rows with some checkbox columns and I need to save the updated rows only one time with a submit button I added right below the grid. 
No double clicking for editing checkboxes. I disabled editing and grid buttons, I changed itemTemplate like this following your examples:
```js
var itemTemp = function(value, item) { 
		  if(value) {
			 selectedItems.push(item);
			 selectedItems = $.unique(selectedItems);  
			  }
        	    return $("<input>").attr("type", "checkbox") .prop("checked",value)
                .on("click", function () { 
                })
                .on("change", function () {
                	$(this).is(":checked") ? selectItem(item) : unselectItem(item);
                });
                }
```

How can I retrieve the updated item value to update the array? The logic is the same of batch delete example, the difference is that I have multiple checkbox columns that represent row data and the JSON row item value should change when I check a box to allow the selectedItems array to be updated (and finally to be submited in the end using the button).
If I try to log the row item when I click it, it logs always the old value, no way to get the updated item (graphically they are checked).
Thank you for any help.
Regards

**Comment by raptus84** [comment]
I'm solving it using this example [link jsFiddle](https://jsfiddle.net/sachin4dotnet/4u6xp3t3/96/), thank you sachin4dotnet, it works like a charm, I have only to fix validations, it's a bit difficult restoring previous rows when updating goes wrong.

**Comment by tabalinas** [comment]
Glad that figured it out!
