### ISSUE TITLE
How set itemTemplate based on other field

### ISSUE THREAD

**Issue by SabinaSc** [tabalinas/jsgrid#948]
Hi,
how can I handle itemTemplate of a field based on other field values?

Actually I have:
```js
    {
         name: "RejectOrder", 
                    itemTemplate: function (value, item) {
                        var $i1 = $("<i>").addClass("fa fa-times iconGrid").prop('aria-hidden', 'true').prop('title', 'Reject order').click(function (e) {
                            item.Operation = "reject";
                            alert(item.StoreOrder);
                            Solution.Common.showModal("Reject Order", ...
```
In other words I dinamically add a link that open a modal popup... now I need to disable the link if field "Accept", that is a bool value, is true... could you help me?

Thanks

**Comment by tabalinas** [comment]
in `itemTemplate` you get `item` with all the fields. So you can add any condition to the renderer depending on different item fields.
