### ISSUE TITLE
Don't clear some fields on insert, and allow enter to edit/insert

### ISSUE THREAD

**Issue by laptopdude90** [tabalinas/jsgrid#949]
A user may want to bulk enter data. In that case, a few of the fields will likely remain the same(Such as the date). I'd like for fields of my choosing to remain populated with the previous data, even when it's inserted.

I'd like to be able to press enter to either insert or confirm an edit. I'd also love for the escape button to cancel the edit. I've seen some examples posted around but they seem outdated now and don't work.

Finally, I'd like for tab behaviour to be slightly different. I'd like for it to loop around the currently selected row(Rather than the entire page) and, if possible, ignore the control buttons entirely.

Could you give me a few pointers on how to do what I want?

**Comment by tabalinas** [comment]
Clearing insertrow data after insert is the behavior of the `control` field (https://github.com/tabalinas/jsgrid/blob/master/src/fields/jsgrid.field.control.js#L183). You can redefine it on the `control` field of your grid.

Better keyboard support is reported in this issue https://github.com/tabalinas/jsgrid/issues/773
There you can find a suggestion on how to implement it now.
