### ISSUE TITLE
Stop new item from inserting

### ISSUE THREAD

**Issue by Rahphaella** [tabalinas/jsgrid#95]
For insertItem(item): Promise|insertedItem,
If no item is returned, inserting item will be used as inserted item.

In my case, validation is added to insertItem(item) function, thus, if the validation fail, no ajax was send to insert data into the database. Yet, new row is still added to the table without fail, how do i disable the new insertion?

**Comment by tabalinas** [comment]
Please, check out this ticket https://github.com/tabalinas/jsgrid/issues/54
For the insert you should redefine `finishInsert`method.
