### ISSUE TITLE
onItemUpdating previousItem not correct when using rowClick function

### ISSUE THREAD

**Issue by brighty99** [tabalinas/jsgrid#950]
When implementing onItemUpdating, expect args.previousItem to contain original item data.

If rowClick is implemented, args.previousItem in onItemUpdating contains updated data, not the original.  If I remove rowClick function and revert to in-place update, args.previousItem has expected original item data.

**Comment by tabalinas** [comment]
Could you provide an example in jsfiddle (or any other online editor) reproducing the issue?
