### ISSUE TITLE
Update select2 dropdown list values on the basis of filtered data

### ISSUE THREAD

**Issue by namdeok** [tabalinas/jsgrid#953]
Hi @tabalinas  i have a requirement where i have to update the select dropdowns(using select2) of columns on filtering .
Whenever the data is filtered at that time each filter dropdown list should have filtered result values inside it.
Here is the jsfilddle link - http://jsfiddle.net/9sxcsurk/2/
Example - If user enter 29 in Age it return 2 rows..So the Country dropdown should only have 'China,Russia'.
I have asked this question StackOverflow too..but no response - [https://stackoverflow.com/questions/47257765/update-select-dropdown-list-on-filtering-js-grid-data](url)

So in my case i'll have multiple dropdowns ,so on each filtering data dropdown list item should get updated.

**Comment by tabalinas** [comment]
Looks somehow related to dependent selects case, did you checkout this issue https://github.com/tabalinas/jsgrid/issues/106?

**Comment by namdeok** [comment]
Hi @tabalinas  firstly i would like to say this is one of the good component i have come across.
 
No it is not dependency issue.I want to update all the dropdowns list according to the data in the grid.There can be multiple dropdowns each are independent .When we select any value and filter the data so then all the dropdown list should be update as per the filtered data in the grid.

**Comment by tabalinas** [comment]
What I meant is that the handling could be similar to `$filterControl.on("change"` in this example: http://jsfiddle.net/tabalinas/n982uvx1/.
The difference is that you use `onDataLoaded` (http://js-grid.com/docs/#ondataloaded) and it's `args.data` argument to get items for selects. There you can get all select fields and replace their `items`.

**Comment by namdeok** [comment]
Thanks for the help.I'll try it out.

**Comment by devlencer** [comment]
@namdeok , i was working on the same this . hope my below code helps you. i got select 2 working with JS-Grid
`  <script type="text/javascript">
      $(function(){
        $("#destinations").select2({
           });

        $('#destinations').on('change', function() {
      	 var destid = $(this).val();
    	 $.ajax({  
         	data: {'destid':destid},
            type: "GET", 
            async: false,                	
            url:'getRatesFromRateSheet',
            dataType: 'json',
            complete : function(results) {
            	loadGrid(results.responseJSON);
            },
            fail: function( jqXHR, textStatus, errorThrown ) {
                console.log( 'Could not get posts, server response: ' + textStatus + ': ' + errorThrown );
            }           
         });         
        })    
       });

      function loadGrid(data){
    	  var tre = $("#jsGrid").jsGrid({
  	        width: "100%",
  	        height: "400px",
  	        filtering: true,
  	        inserting: true,
  	        editing: true,
  	        sorting: true,
  	        paging: true,
  	        autoload: true,
  	        dataType : "json",
  	        pageSize: 15,
            pageButtonCount: 5,
            deleteConfirm: "Do you really want to delete the rate ?",
            data: data,
            controller: {
                data:data,
                loadData: function (filter) {
                    return $.grep(this.data, function (item) {                    	
                        return (!filter.dialCode || item.dialCode.indexOf(filter.dialCode)  > -1)
                            && (!filter.dialingCodeDescription || item.dialingCodeDescription.indexOf(filter.dialingCodeDescription)  > -1);
                    });
                },          
            },
  	        fields: [
  	            { name: "dialCode", title: "Dial Code" ,type: "text", width: 50 },
  	            { name: "dialingCodeDescription", title: "Dial Code Description" ,type: "text", width: 150 },
  	            { name: "effectiveDate", type: "text", title: "Effective Date", sorting: false },
  	            { name: "price", title: "Price" ,type: "number", width: 50 },
  	            { name: "isGeo", type: "checkbox", title: "Is Selected", sorting: false },
  	            { name: "service", type: "text", title: "Service type", sorting: false }, 	           
  	            { type: "control" }
  	        ]
  	    });
    console.log("Dta"+tre)
  	    }
</script>`

**Comment by tabalinas** [comment]
@devlencer, thanks for sharing!
