### ISSUE TITLE
Two fields in one cell

### ISSUE THREAD

**Issue by baks92** [tabalinas/jsgrid#954]
Hello. I have a simple question regarding the row editing. Is it possible to add more than one input in one cell in the grid? Like so:
![untitled](https://user-images.githubusercontent.com/33693484/32841469-a9125620-ca1a-11e7-8d31-2219f338b523.png)

**Comment by tabalinas** [comment]
Yes, `editTemplate` returns jQuery object, so it could be as many elements as you need.
