### ISSUE TITLE
Real time data updates

### ISSUE THREAD

**Issue by yck1719** [tabalinas/jsgrid#956]
Hi,

I am new to use jsgrid and have a question, I am developing a website that uses websocket to get data from a server and have to present that data in a grid. That data can gets updated throughout the day so I need to refresh the grid whenever new data comes in (without the need for user to refresh manually). Is it possible to do that through the controller:loadData method or is there any other ways to achieve that?

Thanks,
Yuet

**Comment by tabalinas** [comment]
You can set grid option `data` directly each time data coming from the server:

`$("#grid").jsGrid("option", "data", newItems)`
