### ISSUE TITLE
row click except one field

### ISSUE THREAD

**Issue by vahidhiv** [tabalinas/jsgrid#96]
Hi. I want my row when clicked doing some function, but i want another field of row doing something else when clicked. Is It possible?
Consider the exception field as button.
Thanks for your attention.

**Comment by tabalinas** [comment]
If you would put the button into the field, you could just `return false` from the click handler

```javascript
$("<button>").click(function() {
    // some action
    return false;
});​
```

If you wish to handle the click on the entire table cell, you could redefine `rowClick` in grid config:

```javascript
rowClick: function(args) {
    var $target = $(args.event.target);

    if($target.closest(".your-field-css-class").length) {
       // handle cell click
    }

    // otherwise handle row click
    if(this.editing) {
        this.editItem($target.closest("tr"));
    }
},
```

**Comment by vahidhiv** [comment]
Yes, returning false on click works, Thank you very much for your support.

**Comment by tabalinas** [comment]
You are welcome!

**Comment by pedrolarap** [comment]
Hi, I'm new with this library. Where exactly should I put the code?

**Comment by vahidhiv** [comment]
> Hi, I'm new with this library. Where exactly should I put the code?

which one?
If you mean click function of row, it is a field when you initialize grid.
If you mean the button or some element inside row, you must define click event for that element.

**Comment by pedrolarap** [comment]
> > Hola, soy nuevo con esta biblioteca. ¿Dónde exactamente debo poner el código?
> 
> ¿cúal? 
> Si quiere decir hacer clic en la función de la fila, es una variable cuando inicializa la cuadrícula. 
> Si se refiere al botón o algún elemento dentro de la fila, debe definir un evento de clic para ese elemento.

I put the event, but it does not work ``{ name: "CodigoCurriculo", type:"text", visible:false},
				 	            { name: "Nombre", type:"text",title: "Curriculo",},
								{ name: "Autor", type:"text",rowClick: function(args) {
									alert("Hola")
								}},
								{ name: "Temas", type: "select", items: TemasSelect },

**Comment by pedrolarap** [comment]
> > Hi, I'm new with this library. Where exactly should I put the code?
> 
> which one?
> If you mean click function of row, it is a variable when you initialize grid.
> If you mean the button or some element inside row, you must define click event for that element.

I put the event, but it does not work ``{ name: "CodigoCurriculo", type:"text", visible:false},
{ name: "Nombre", type:"text",title: "Curriculo",},
{ name: "Autor", type:"text",rowClick: function(args) {
alert("Hola")
}},
{ name: "Temas", type: "select", items: TemasSelect },

**Comment by vahidhiv** [comment]
This is a sample, i wish it could help.

container.jsGrid({
        inserting: false,
        editing: false,
        sorting: false,
        paging: false,
        data: data,

        fields: [
            {name: "instrumentID", itemTemplate: function (value, item) {
                    return  value;
                }
            },
        ],
        rowClick: function (args) {
            selectShare(args.item.instrumentID);
        }
    });

**Comment by pedrolarap** [comment]
> Esta es una muestra, ojalá pudiera ayudar.
> 
> ```
> container.jsGrid({
>         inserting: false,
>         editing: false,
>         sorting: false,
>         paging: false,
>         data: data,
> 
>         fields: [
>             {name: "instrumentID", itemTemplate: function (value, item) {
>                     return  value;
>                 }
>             },
>         ],
>         rowClick: function (args) {
>             selectShare(args.item.instrumentID);
>         }
>     });
> ```
thanks for your reply. It has helped me a lot. I only have one concern: the code that you have placed works for me to place the event in the whole row. I want to add the event to only one field.
