### ISSUE TITLE
Apply filter while typing in the filtering box for text field and number field.

### ISSUE THREAD

**Issue by Jasvinder15s** [tabalinas/jsgrid#960]
Feature Request / Help Request

Hi, @tabalinas I have tried searching for this and found the solution for it #487 but my requirement does not match it.
We need:-
1. Filter number while typing without hitting enter.
2. Filter text neglecting uppercase and lowercase characters.
i.e to filter without considering the case of the text entered.
 
http://jsfiddle.net/singh_jasvinder/xk402uhg/8/

Thanks.

**Comment by tabalinas** [comment]
You are almost there with your example. All you need is to tweak your filtering function a bit.
`===` is used for Number, while filter value is a string, so it doesn't work.
For case insensitive search use `.toLowerCase()`.
Here is the corrected fiddle:
http://jsfiddle.net/tabalinas/p4xbh260/

**Comment by Jasvinder15s** [comment]
Hi, Thank you for the solution!
