### ISSUE TITLE
Combined Filterfield for 2 Columns

### ISSUE THREAD

**Issue by 5p1k3md** [tabalinas/jsgrid#961]
Help Request/Question:
A) Clearly state your problem
What i want to achieve is a filterfield, which strechs over 2 columns, but the 2 columns should still have there own titles.
On filtering the value of the filterfield should be applied to both columns as filtervalue.

**Comment by tabalinas** [comment]
Redefine `filterRowRenderer` so it renders filter row the way you need.
One gotcha is that in this case you have to define `filterValue` for each field (except `control` field).
Looks at this simplest example:
https://jsfiddle.net/tabalinas/r6kg5m51/
