### ISSUE TITLE
multiselect column value is not showing after saving data and reloading grid.

### ISSUE THREAD

**Issue by h-patel** [tabalinas/jsgrid#963]
Created a multiselection column. When i load the grid i am returning comma separated value which is showing properly. when i try to do edit the selection and then save it. saving working properly getting the changed value during save. after getting getting success response from save doing $("#jsGrid").jsGrid("loadData");. grid is loading but the row is showing the older value. if i refresh the page then its showing the changed value from properly. 
Am i missing anything?

Hrushikesh

**Comment by tabalinas** [comment]
Seems to be related to this bug https://github.com/tabalinas/jsgrid/issues/962.

If you could send the updated item from the updating endpoint to the client and return it from `controller.updateItem` the grid will use this new item (instead of old updated item). This should solve the issue.
