### ISSUE TITLE
Unable to override _createGridButton

### ISSUE THREAD

**Issue by MikeHofer** [tabalinas/jsgrid#964]
I'm trying to override `_createGridButton`, as suggested [here](https://github.com/tabalinas/jsgrid/issues/600). I need to be able to do this so that I can replace the `<input>` control with either an `<i>` or a `<span>`, and apply FontAwesome classes to it so that the site is thematically consistent with the rest of our in-house sites. (FontAwesome classes don't work on `<input>` elements.)

In my JavaScript, I've included the following, lifted directly from the source code provided in the link above:

```js
    jsGrid.ControlField.prototype._createGridButton = function (cls, tooltip, clickHandler)
    {
        var grid = this._grid;
        
        return $("<input>").addClass(this.buttonClass)
            .addClass(cls)
            .attr({
                type: "button",
                title: tooltip
            })
            .on("click", function (e)
            {
                clickHandler(grid, e);
            });
    };
```

The problem is that the rendered markup contains no input controls whatsoever. I can set a break point in the function and see that it is hit, but no `<input>` control is rendered. The result is an empty table cell (in both the header, where the insert button should appear, and in the row, where the edit button should appear).

What am I doing wrong? This code is directly from the js-grid source code. I was going to modify it after I could prove that it worked, but I'm not even getting any markup from it. Can anyone please shed some light on this?

**Comment by tabalinas** [comment]
Could you provide a jsfiddle reproducing the issue?
