### ISSUE TITLE
Pagination AJAX loading

### ISSUE THREAD

**Issue by s-karthic** [tabalinas/jsgrid#965]
Hi,
I have 816 data.
I set the page size as 10.
I bind 816 data in a single api call.. It tooks so long time to bind the data and display it in UI.
So I planned to change it. Like Pagination sets first for 816 data. After clicking several page i want to call the data.
For eg.,
|-----------------------------|
|     1            SampleText     |
|     2            SampleText     |
|     3            SampleText     |
|     4            SampleText     |
|     5            SampleText     |
|     6            SampleText     |
|     7            SampleText     |
|     8            SampleText     |
|     9            SampleText     |
|    10            SampleText     |
|-----------------------------|

Pages:  1   2   3   4   .....   Last   1 of 82

When I load the grid Only 10 data have to be upload. After i click the page number "2", the call have to go for api and get another 10 data and append into the grid.. Like wise it goes on..

Now for the first call I binds all (816) data.. I don't like this method. Please guide me...

**Comment by tabalinas** [comment]
Enable loading data by pages with `pageLoading: true` (http://js-grid.com/docs/#pageloading-default-false). 

Find more details in this answer: https://stackoverflow.com/a/38995647/1140893

**Comment by s-karthic** [comment]
thank you. its working
