### ISSUE TITLE
How to use the built-in min validator

### ISSUE THREAD

**Issue by 5p1k3md** [tabalinas/jsgrid#967]
Hello,

i test for about an hour now to get the min validator working for a number input.
what the right way to use it?
does it also limit the input for the filter field?

**Comment by tabalinas** [comment]
`min` validator can be used as any other build-in validator, the min value should be specified in `param` field http://js-grid.com/docs/#built-in-validators

```
validate: {
    validator: "min",
    message: "The value should be greater than 20",
    param: 20
}
```

No, it's not applied to the filter.
