### ISSUE TITLE
How to import excel data in js grid?

### ISSUE THREAD

**Issue by Jasvinder15s** [tabalinas/jsgrid#968]
How to import excel data in jsgrid?

**Comment by tabalinas** [comment]
You have to read data from the excel file, checkout https://stackoverflow.com/questions/8238407/how-to-parse-excel-file-in-javascript-html5 or any other explanation.
Then it's easy to feed json to the grid.

**Comment by Jasvinder15s** [comment]
Thank you so much. You're awesome!!
