### ISSUE TITLE
Callbacks example

### ISSUE THREAD

**Issue by mese79** [tabalinas/jsgrid#97]
Hi
I can't figure out how to use callbacks like ```onDataLoaded``` or ```onOptionChanged```. i've tried like:
```
grid.onDataLoaded = function(grid, data) {
    console.log(data);
}
```
with no message or error in console.
Could you give me an example, please?

By the way thanks you for great job!

**Comment by tabalinas** [comment]
Hi,

I guess, the problem is callbacks accept a single argument with the format of `{ grid, data }`.
In your case it will be: 

```javascript
grid.onDataLoaded = function(args) {
    console.log(args.data);
}
```
