### ISSUE TITLE
How to load dynamically particular fields data depending on other selected value

### ISSUE THREAD

**Issue by maqsoodgul** [tabalinas/jsgrid#973]
Hello,
I wanted a similar feature like the one explained in http://jsfiddle.net/tabalinas/n982uvx1/ however, in my case a user can select any of dropbox/combobox (there will be 3 in my case) and initially if none of dropbox has value it should fill the combobox with all the values returned by functionX. and once the user selected the value the remaining combobox should return only values  related to the selected values.

for example: 

combo1= list of countries
combo2=list of states
combo3=list of countries

so if user select combo3 first time it should return all the values that functionX return and fill it with. let say user select cityX than after selection combo1 & combo2 must be filled accordingly eg combo1=>CountryZ & combo2=>statesY. I have already functionX which returns the data depending upon selected value & comboboxid. Please note that the selection of combobox can be in any order.

function functionX(arr, comboID)
{

var valueList=getList(comboID,arr) // arr will be array containing selected values else empty array
.
.
return value

}

i hope you understand the problem and can guide me.

**Comment by tabalinas** [comment]
Did you try to modify this fiddle so that items loaded asynchronously?

**Comment by maqsoodgul** [comment]
did it with custom control thanks

**Comment by joesalloum** [comment]
@maqsoodgul i have same problem can you help me ? how did you write the custom control please i need help

**Comment by maqsoodgul** [comment]
Hello @joesalloum I followed this tutorial [Custom field](http://js-grid.com/docs/#custom-field) also find below my code i am not sure whether this will help or not 
`
$(function () {
    var customfieldmultiselectlookupcontrol = function (config) {
        this.id = config.id;
        this.scolnew = config.scolnew;
        this.curIndex = config.curIndex;
        this.header = config.header;
        this.outputvalue = null;

        jsGrid.Field.call(this, config);
    };

    customfieldmultiselectlookupcontrol.prototype = new jsGrid.Field({
        sorter: function (value1, value2) {
            return value1.id - value2.id;
        },

        itemTemplate: function (value) {
            return value.displayValue;
        },

        insertTemplate: function (value) {
            var curIndex = this.curIndex;
            var curHeader = this.header;
            var scolnew = this.scolnew;
            var parent = this;

            parent.outputvalue = {propid: curHeader.cells[curIndex].id, id: -1, displayValue: " - leer -"};
            scolnew[curIndex] = {propid: curHeader.cells[curIndex].id, id: -1, displayValue: " - leer -"};

            var getComboboxValueList = function (id, scol) {
                var result = [];
                var d = new $.Deferred();
               MyCallbackFunction(
                        function (listData) {
                            if (listData !== null && typeof (listData) !== 'undefined') {
                                result.push({value: -1, label: " - leer -"});
                                for (var i = 0; i < listData.length; i++) {
                                    var temp = {};
                                    temp['value'] = listData[i].id;
                                    temp['label'] = listData[i].displayValue;
                                    result.push(temp);
                                }
                                d.resolve(result);
                            }
                        },
                        getErrorCallback());
                return d.promise();
            }

            var input = $("<input readonly>")
                    .val(" - -")
                    .addClass("custom-combobox-input ui-widget ui-widget-content ui-state-default ui-corner-left")
                    .autocomplete({
                        delay: 0,
                        minLength: 0,
                        source: function (request, response) {
                            var b = [];
                            var x = 0;
                            for (var i = 0; i < scolnew.length; i++) {
                                if (scolnew[i] !== null && typeof (scolnew[i]) !== 'undefined') {
                                    b[x++] = scolnew[i];
                                }
                            }
                            getComboboxValueList(a, b).done(function (value) {
                                response(value);
                            });
                        },
                        select: function (event, ui) {
                            parent.outputvalue = {propid: curHeader.cells[curIndex].id, id: ui.item.value, displayValue: ui.item.label};
                            scolnew[curIndex] = {propid: curHeader.cells[curIndex].id, id: ui.item.value, displayValue: ui.item.label};
                            event.preventDefault();
                            input.val(ui.item.label);
                        }
                    })
                    .tooltip({
                        classes: {
                            "ui-tooltip": "ui-state-highlight"
                        }
                    }).on("focus", function () {
                $(this).autocomplete("search", "");
            });

            return this._insertPicker = input;
        },

        editTemplate: function (value) {
            var curIndex = this.curIndex;
            var curHeader = this.header;
            var scolnew = this.scolnew;
            var parent = this;

            parent.outputvalue = value;
            scolnew[curIndex] = value;

            var getComboboxValueList = function (id, scol) {
                var result = [];
                var d = new $.Deferred();
                MFFramework.getValueListData(id, scol,
                        function (listData) {
                            if (listData !== null && typeof (listData) !== 'undefined') {
                                result.push({value: -1, label: " -  -"});
                                for (var i = 0; i < listData.length; i++) {
                                    var temp = {};
                                    temp['value'] = listData[i].id;
                                    temp['label'] = listData[i].displayValue;
                                    result.push(temp);
                                }
                                d.resolve(result);
                            }
                        },
                        getErrorCallback());
                return d.promise();
            }

            var input = $("<input readonly>")
                    .val(value.displayValue)
                    .addClass("custom-combobox-input ui-widget ui-widget-content ui-state-default ui-corner-left")
                    .autocomplete({
                        delay: 0,
                        minLength: 0,
                        source: function (request, response) {
                            var scol = [];
                            var x = 0;
                            for (var i = 0; i < scolnew.length; i++) {
                                if (scolnew[i] !== null && typeof (scolnew[i]) !== 'undefined') {
                                    scol[x++] = scolnew[i];
                                }
                            }
                            getComboboxValueList(curHeader.cells[curIndex].id, scol).done(function (value) {
                                response(value);
                            });
                        },
                        select: function (event, ui) {
                            parent.outputvalue = {propid: curHeader.cells[curIndex].id, id: ui.item.value, displayValue: ui.item.label};
                            scolnew[curIndex] = {propid: curHeader.cells[curIndex].id, id: ui.item.value, displayValue: ui.item.label};
                            event.preventDefault();
                            input.val(ui.item.label);
                        }
                    })
                    .tooltip({
                        classes: {
                            "ui-tooltip": "ui-state-highlight"
                        }
                    }).on("focus", function () {
                $(this).autocomplete("search", "");
            });

            return this._editPicker = input;
        },

        insertValue: function () {
            return this.outputvalue;
        },

        editValue: function () {
            return this.outputvalue;
        }
    });

    jsGrid.fields.customfieldmultiselectlookupcontrol = customfieldmultiselectlookupcontrol;

   
});
`
