### ISSUE TITLE
checkbox and editing

### ISSUE THREAD

**Issue by caldera500** [tabalinas/jsgrid#975]
I am using the code from the 'Batch Delete Demo', which works great as it is. The issue is that if I enable editing I have to click twice to check the checkbox. It also adds the selected item twice to the 'selectedItems' array. The demo has editing disabled. I tried to set 'editing : false' for the checkbox field but the issue remains. 
is there a better way to all fields but the checkbox field editable?

Thanks!

**Comment by tabalinas** [comment]
Please checkout this issue https://github.com/tabalinas/jsgrid/issues/959
