### ISSUE TITLE
Need code for JS-Grid Custom Inline editable grid with final update instead of each row update

### ISSUE THREAD

**Issue by TamilselvnJames** [tabalinas/jsgrid#977]
[JSGrid.zip](https://github.com/tabalinas/jsgrid/files/1566875/JSGrid.zip)
Rightnow I'm having a sample code to have consolidate edit(which will edit entire grid into editable mode) and consolidate update. 
I want to customize with consolidate update only. If I click the row it will keep the dirty flag over the row and if I submit the consolidate button I want to update get the all dirty rows are modified in dom.

**Comment by tabalinas** [comment]
The general idea sounds correct. Did you face with any specific issue that you are not able to resolve?

**Comment by TamilselvnJames** [comment]
I have completed the necessary requirement. Thanks for your support.

<!DOCTYPE html>
<html>
<head>
    <title></title>
    <meta charset="utf-8" />
    <script type="text/javascript" src="JS/jquery-2.2.4.min.js"></script>
    <link type="text/css" rel="stylesheet" href="JS/jsgrid.min.css" />
    <link type="text/css" rel="stylesheet" href="JS/jsgrid-theme.min.css" />
    <script type="text/javascript" src="JS/jsgrid.min.js"></script>
    <style>
        .hide {
            display: none;
        }

        /*.jsgrid-pager-container {
            display: block !important;
        }*/
    </style>
    <script type="text/javascript">
        
        $(function () {
            var JSGRID_EDIT_ROW_DATA_KEY = "JSGridEditRow";
            var JSGRID_ROW_DATA_KEY = "JSGridItem";
            var editRowClass = "jsgrid-edit-row";

            var clients = [
                { "Name": "Otto Clay", "Age": 25, "Address": "", "Country": 1, "Address Data": "Ap #897-1459 Quam Avenue", "isDirty": "No" },
              { "Name": "Connor Johnston", "Age": 45, "Address": "", "Country": 2, "Address Data": "Ap #370-4647 Dis Av.", "isDirty": "No" },
              { "Name": "Lacey Hess", "Age": 29, "Address": "", "Country": 2, "Address Data": "37 Oak St, Melbourne", "isDirty": "No" },
              { "Name": "Tamil", "Age": 29, "Address": "", "Country": 1, "Address Data": "test", "isDirty": "No" },
              { "Name": "james", "Age": 29, "Address": "", "Country": 1, "Address Data": "test test", "isDirty": "No" }
            ];

            var countries = [
                { Name: "", Id: 0 },
              { Name: "United States", Id: 1 },
              { Name: "Canada", Id: 2 },
              { Name: "United Kingdom", Id: 3 },
              { Name: "Australia", Id: 4 }
            ];

            //$('div').filter(function () {
            //    return $(this).attr('data-name') === 'content1';
            //}).append('<div id="jsGrid"></div>');
            //$('#content1').append('<div id="jsGrid"></div>');
            // or
            //$('<div>hello</div>').appendTo('#parent');

            var $grid = $("#jsGrid");

            $("#jsGrid").jsGrid({
                width: "100%",
                height: "300px",

                inserting: true,
                editing: true,
                sorting: true,
                paging: true,
                pageSize: 2,
                editFields_forBatch: [],
                _editingRows_forBatch: [],

                data: clients,
                //openPage: function (pageIndex) {

                //    //if (this._editingRow) {
                //    //    this.updateItem();
                //    //}

                //    var indexFrom = this._loadStrategy.firstDisplayIndex();
                //    var indexTo = this._loadStrategy.lastDisplayIndex();
                //    $("#hdnIndexFrom").val(indexFrom);
                //    $("#hdnIndexTo").val(indexTo);
                //    var i = 0;
                //    for (var itemIndex = indexFrom; itemIndex < indexTo; itemIndex++) {
                //        var item = this.data[itemIndex];
                //        var frameName = '#iFrameComponentCheck' + i;
                //        var compId = item['Address Data'];
                //        //$(frameName).attr('src', '../../../editmaincomponent?id=' + compId);
                //        //$(frameName).contents().find('#cu_materialnumber').val(meterialNo);
                //        //$("#iFrameComponentCheck").contents().find('select[name^=cu_recommendation] option[value='+actionTaken+']').attr("selected","selected");
                //        i++;
                //    }

                //    //if (document.readyState == "complete") {

                //    //    var flag = true;
                //    //    var indexFrom = $('#hdnIndexFrom').val();
                //    //    var indexTo = $('#hdnIndexTo').val();
                //    //    var component = $("#jsGrid").jsGrid("option", "data");
                //    //    component.forEach(function (item) {
                //    //        if (item.isDirty == "Yes") {
                //    //            var materialNo = item['Address Data'];
                //    //            //var materialNo = component['New material number'];
                //    //            var actionTaken = item['Country'];
                //    //            if (actionTaken == 2) {
                //    //                if ((materialNo.indexOf("HZTL") == 0 || materialNo.indexOf("HTLT") == 0 || (materialNo.indexOf("NB") == 0 && materialNo.indexOf("P") >= 1) || materialNo.indexOf("NBT") == 0
                //    //                          || materialNo.indexOf("TL") == 0 || materialNo.indexOf("TLT") == 0 || materialNo.indexOf("GON") == 0) && (materialNo.length == 15)) {
                //    //                    flag = true;
                //    //                }
                //    //                else {
                //    //                    $('#divAlert').show();
                //    //                    $("#spnErrorText").html('Please provide valid Material Number.');
                //    //                    document.location.href = '#top';
                //    //                    flag = false;
                //    //                }

                //    //            }
                //    //            else {
                //    //                flag = true;
                //    //            }
                //    //        }
                //    //    });


                //    //    if (!flag)
                //    //        return false;

                //    //    alert(JSON.stringify(component));
                //    //    for (var i = 0; i < component.length; i++) {
                //    //        var obj = component[i]['Address Data'];
                //    //        //alert(obj.Age)
                //    //    }
                //    //}

                //},

                fields: [
                  { name: "Name", type: "text", width: 150, validate: "required" },
                  { name: "Age", type: "number", width: 50 },
                  {
                      name: "Address", type: "text", width: 200,
                      editTemplate: function (value, item) {
                          var grid = this._grid;
                          var $editControl = jsGrid.fields.text.prototype.editTemplate.call(this, value);
                          item.isDirty = "Yes";
                          $(".jsgrid-pager *").prop('disabled', true);
                          if (!this.editing)
                              return this.itemTemplate(value);
                          var $result = this.editControl = this._createTextBox().prop({ disabled: true });
                          if (item.Country == 2) {
                              grid.fields[2].editControl[0].disabled = false;
                              if (item.Address == "") {
                                  grid.fields[2].editControl[0].value = item['Address Data'];
                                  item.Address = item['Address Data'];
                              }
                              else
                                  grid.fields[2].editControl[0].value = item.Address;
                          }
                          return $result;
                      }
                  },
                  {
                      name: "Country", type: "select", items: countries, valueField: "Id", textField: "Name"
                      , editTemplate: function (value, item) {
                          var $editControl = jsGrid.fields.select.prototype.editTemplate.call(this, value);
                          var grid = this._grid;
                          if (value == 2) {
                              //grid.fields[2].editControl[0].disabled = false;
                              //grid.fields[2].editControl[0].value = grid.fields[5]._value;
                          }


                          $editControl.change(function () {
                              var selectedValue = $(this).val();
                              if (selectedValue == 2) {
                                  grid.fields[2].editControl[0].disabled = false;
                                  grid.fields[2].editControl[0].value = grid.fields[5]._value;
                                  grid.fields[4]._value = "Yes";

                              }


                          });

                          return $editControl;
                      }
                      //, updateItem: function (item, editedItem) {
                      //    var $row = item ? this.rowByItem(item) : this._editingRow;
                      //    },
                  },
                  { name: "isDirty", css: "hide", width: 0 },
                  { name: "Address Data", width: 0, css: "hide" }
                ],


                updateItems_forBatch: function (item) {
                    if (this._editingRow)
                        this.updateItem();

                    return;
                },
                _finishUpdate: function ($updatingRow, updatedItem, updatedItemIndex) {
                    if (this._editingRow) this.cancelEdit();
                    else this.cancelEdit_forBatch_row($updatingRow);
                    this.data[updatedItemIndex] = updatedItem;

                    var $updatedRow = this._createRow(updatedItem, updatedItemIndex);
                    $updatingRow.replaceWith($updatedRow);
                    return $updatedRow;
                },

                cancelEdit_forBatch_row: function (updatedRow) {
                    if (!updatedRow)
                        return;
                    updatedRow.prev("tr." + this.editRowClass).remove();
                    updatedRow.show();
                },
                cancelEdit_forBatch: function (rowItems) {
                    for (var i = 0; i < rowItems.length; i++) {
                        var $row = this.rowByItem(rowItems[i]);
                        if ($row.length) {
                            this.cancelEdit_forBatch_row($row);
                        }
                    }
                },
                pagingwiseUpdate: function (rowItems) {

                    for (var i = 0; i < this.data.length; i++) {
                        if (this.data[i]['isDirty'] == "Yes") {
                            this.data[i]['isDirty'] = "No";
                            this.data[i]['Address Data'] = this.data[i].Address;
                        }
                    }
                },
                rowClick: function (args) {
                    var $row = $(args.event.target).closest("tr");
                    if (this._editingRow) {
                        this.updateItem().done($.proxy(function () {
                            //this._editingRows_forBatch.push($row);
                            this.editing && this.editItem($row);
                        }, this));
                        return;
                    }
                    this.editing && this.editItem($row);
                },
                //onItemUpdating: function (args) {
                //    if (args.item.Address != args.previousItem.Address) {
                //        args.item.isDirty = "Yes";
                //        $(".jsgrid-pager *").attr('disabled', true);
                //    }
                //},
            });


            $("#content1").on('click', '#btnBatchSave1', function () {
                var mainComponentItem = $grid.jsGrid("updateItems_forBatch");
                var flag = false;
                var indexFrom = $('#hdnIndexFrom').val();
                var indexTo = $('#hdnIndexTo').val();
                var component = $grid.jsGrid("option", "data");
                for (var i = indexFrom; i < indexTo; i++) {
                    if (component[i]['isDirty'] == "Yes") {
                        var materialNo = component[i]['Address Data'];
                        //var materialNo = component['New material number'];
                        var actionTaken = component[i]['Country'];
                        if (actionTaken == 2) {
                            if ((materialNo.indexOf("HZTL") == 0 || materialNo.indexOf("HTLT") == 0 || (materialNo.indexOf("NB") == 0 && materialNo.indexOf("P") >= 1) || materialNo.indexOf("NBT") == 0
                                      || materialNo.indexOf("TL") == 0 || materialNo.indexOf("TLT") == 0 || materialNo.indexOf("GON") == 0) && (materialNo.length == 15)) {
                                flag = true;
                            }
                            else {
                                $('#divAlert').show();
                                $("#spnErrorText").html('Please provide valid Material Number.');
                                document.location.href = '#top';
                                flag = false;
                                break;
                            }

                        }
                        else {
                            flag = true;
                        }
                    }

                    $grid.jsGrid("pagingwiseUpdate", component);
                    $(".jsgrid-pager *").removeAttr('disabled');
                }

                if (!flag)
                    return false;

                alert(JSON.stringify(component));
                for (var i = 0; i < component.length; i++) {
                    var obj = component[i]['Address Data'];
                    //alert(obj.Age)
                }
                if ($grid.jsGrid("updateItems_forBatch")) {
                    //$grid.jsGrid("fieldOption", 4, "visible", true);
                    ////$('#btnBatchSave1').prop('disabled', true);
                    //$('#btnBatchCancel1').prop('disabled', true);
                    //$('#btnBatchEdit1').prop('disabled', false);
                }
            });
            $("#content1").on('click', '#btnBatchCancel1', function () {
                var rows = $grid.jsGrid("option", "data");
                $grid.jsGrid("cancelEdit_forBatch", rows);
                $grid.jsGrid("fieldOption", 4, "visible", true);
                //$('#btnBatchSave1').prop('disabled', true);
                $('#btnBatchCancel1').prop('disabled', true);
                $('#btnBatchEdit1').prop('disabled', false);
            });

            $("#pager").on("change", function () {
                var page = parseInt($(this).val(), 10);
                $("#jsGrid").jsGrid("openPage", page);
            });


            $(document).ready(function () {
                var component = $grid.jsGrid("openPage", 1);
            });





        });

        function loadFrame(arr, i, url, meterialNo) {
            alert(url + ' ' + meterialNo);
            $('#iFrameComponentCheck').once('load', function () {
                if (i < arr.length) { loadFrame(arr, i++); }
            });
            $("#iFrameComponentCheck").contents().find('#cu_materialnumber').val(meterialNo);
            $("#iFrameComponentCheck").attr("src", url);
        };

        function validateTextBox() {
            if ((value.startsWith("HZTL") || value.startsWith("hztl") || value.startsWith("HTLT") || value.startsWith("htlt") || ((value.startsWith("NB") || value.startsWith("nb")) && value.IndexOf("P") >= 1) || value.startsWith("NBT") || value.startsWith("nbt") || value.startsWith("TL") || value.startsWith("tl") || value.startsWith("TLT") || value.startsWith("tlt") || value.startsWith("GON") || value.startsWith("gon")) && (value.length == 15)) {
                alert('ok');
            }
            var value = document.getElementById("txtInput").value;
            //if (textBoxName.toUpperCase.startsWith('HTLT'))

        }

    </script>


</head>
<body>
    <div id="content1">
        
        <button type="button" id="btnBatchSave1">Save</button>
        <button type="button" id="btnBatchCancel1">Cancel</button>
    </div>

    <div id="jsGrid"></div>
    <iframe id="iFrameComponentCheck0" height="500px" width="500px"></iframe>
    <iframe id="iFrameComponentCheck1" height="500px" width="500px"></iframe>
    <iframe id="iFrameComponentCheck2" height="500px" width="500px"></iframe>
    <iframe id="iFrameComponentCheck3" height="500px" width="500px"></iframe>
    <iframe id="iFrameComponentCheck4" height="500px" width="500px"></iframe>
    <input type="hidden" id="hdnIndexFrom" value="" />
    <input type="hidden" id="hdnIndexTo" value="" />

    <div>
        <span>Enter the text</span>
        <span><input type="text" id="txtInput" width="300" /></span>
        <span><input type="button" id="btnInput" onclick="validateTextBox();" name="Submit" /></span>
    </div>
</body>

</html>
