### ISSUE TITLE
Custom Confirm Dialog on delete Item

### ISSUE THREAD

**Issue by LeonidSegment** [tabalinas/jsgrid#981]
How I can change the default browser confirm dialog on delete item in the grid, to some custom, like  alertifyjs (https://alertifyjs.org/)

**Comment by margolisj** [comment]
See the deleteConfirm function under configuration:
http://js-grid.com/docs/#deleteconfirm-default-are-you-sure

**Comment by LeonidSegment** [comment]
The function returning string message to display.
I want to change the browser default confirm dialog to custom dialog and this function (deleteConfirm)
not the solution

**Comment by margolisj** [comment]
Sorry. Pull up the source and check out the deleteItem function. You could probably replace this line with what you want:
https://github.com/tabalinas/jsgrid/blob/master/src/jsgrid.core.js#L1523

**Comment by tabalinas** [comment]
Please checkout the following enhancement issue https://github.com/tabalinas/jsgrid/issues/323
