### ISSUE TITLE
Help/Problem: Filter Bar Not Functioning

### ISSUE THREAD

**Issue by margolisj** [tabalinas/jsgrid#982]
See this fiddle: https://jsfiddle.net/margolisj/2hbLq5gs/
Fixed the fiddle.

Basically, the filter bar doesn't seem to be doing anything for me. I don't think I did anything crazy here and its practically the same as the demo. Any help would be greatly appreciated. Thanks.

**Comment by tabalinas** [comment]
Please checkout the following issue https://github.com/tabalinas/jsgrid/issues/32
