### ISSUE TITLE
Custom sorting: natural sort?

### ISSUE THREAD

**Issue by inferno-cc** [tabalinas/jsgrid#984]
Hi,

JSGrid doesn't support natural sorting out of the box, am I right?

So, I need to add my own custom sorter for this?
Maybe somebody already has something like this and wants to share the experience? :)

Thx!

**Comment by inferno-cc** [comment]
Maybe it is possible to integrate this one (https://github.com/Bill4Time/javascript-natural-sort) to jsgrid? :)

**Comment by tabalinas** [comment]
There are a bunch of built-in sorting strategies. You can register your custom sorting methods if you wish.
Please checkout docs about sorting http://js-grid.com/docs/#sorting-strategies.
