### ISSUE TITLE
Custom edit template

### ISSUE THREAD

**Issue by inferno-cc** [tabalinas/jsgrid#985]
Hi,

I'm trying to add some custom editTemplate for the select items...
I like to use selectize.js.... but every time I trying to make some working code, it doesn't do anything 

So for example if I just initialize the selectize function on some select classess / id's, it doesn't work. (I'm able to change the default edit select/option class/id...)

I think it's because of every item of jsgrid is a dynamic jquery object? And the selectize 'plugin' just doesn't know about it?

I'm not a professional on javascript, so I don't know exactly that's the problem..

Maybe somebody any experience with making custom editTemplate for the select items with some javascript plugins? (I have already searched and found something about the combination jsgrid+select2, but the manner of work looks not to work with selectize.js :/)

Thx!

**Comment by tabalinas** [comment]
Please provide a jsfiddle reproducing the issue.

**Comment by margolisj** [comment]
If you're looking for a good example on jsgrid custom fields look up the datetime or autocomplete examples. 

I happened to have the datetime example handy: https://github.com/tabalinas/jsgrid/issues/60
