### ISSUE TITLE
Indeterminate state of checkbox

### ISSUE THREAD

**Issue by maqsoodgul** [tabalinas/jsgrid#986]
3. Help Request/Question:

I need to add the functionality of indeterminate state for checkbox i.e if the value is "" i.e empty string the status of checkbox should be indeterminate. I know you mentioned in one of your about the indeterminate state but i am not able to find how to do it.

**Comment by tabalinas** [comment]
I guess here is the solution you found https://stackoverflow.com/a/48095095/1140893

**Comment by tabalinas** [comment]
`indeterminate` state is supported only for filters out-of-box.
