### ISSUE TITLE
jsgrid -  how to filter on read-only columns

### ISSUE THREAD

**Issue by ynteoh** [tabalinas/jsgrid#988]
I am using jsgrid, may I know how to filter on read-only columns?

**Comment by ynteoh** [comment]
I do not allow to perform the filter after changing the field to "type not defined" or set to readOnly: true.
Could anyone advise how to filter on read-only field or field without type?

**Comment by ynteoh** [comment]
I found the solution. Thanks.

**Comment by sharepointmike** [comment]
@ynteoh Can you share the solution?
