### ISSUE TITLE
Unable to reload grid without data

### ISSUE THREAD

**Issue by harissg** [tabalinas/jsgrid#989]
Hi, 

First of all, this is a great tool - very easy to use and good documentation.

I have a issue - I have tried to research around for a solution but cannot seem to get anywhere.

I have a grid - that loads data fine. 

I would now like to "reset" the grid - as in remove the data from it as to its initialised state.

Here is a jsfiddle I found - that achieves the behaviour I am after, however this solution - although should work but does not work for me. I have also looked at #763 and #664

http://jsfiddle.net/tabalinas/gmdbuzbe/

I reset the datasource as:

`this.products = []` 

However - previous data still appears in the grid.

Summary

I would like the grid to "reload" without any data.

My code:
```js
jsgrid['jsGrid']({
            width: '1000px',
            height: '200px',
            inserting: false,
            editing: true,
            paging: false,
            data: this.products,
            fields: this.gridFields,
            loadData: () => {
                return this.products;
            },
            onItemDeleted: (args: any) => {

            },
            onItemUpdating: (args: any) => {
                
            }
        });

    cancel() {
        this.products = [];
        $('#jsgrid')['jsGrid']('refresh');
    }
```
Thanks

**Comment by tabalinas** [comment]
First you shouldn't mix static data scenario (using `data` config option) and `loadData` scenario.
Second, `loadData` should be inside a `controller`.
Third, you need to call `loadData` or `search` to actually reload data, `refresh` just repaints the grid.

**Comment by harissg** [comment]
thanks, that has helped me.
