### ISSUE TITLE
Get custom date time picker value in post method

### ISSUE THREAD

**Issue by SaadManai** [tabalinas/jsgrid#993]
[include.docx](https://github.com/tabalinas/jsgrid/files/1608797/include.docx)

Hello guys. I need some help with jsGrid.

I used the custom bootstrap datetime picker that has been mentioned in other issues on this forum. I have got it to successfully work in my project. I just have one question. I would like to insert a row from my grid into a mysql database. For that I have written down the function and everything. I just need to know that in the post method, how do i get date and time as a string. I tried it using req.body.deadline, deadline is the date and time column in the grid but req.body.deadline comes up empty.

I would really appreciate the help. Thank you.

**Comment by tabalinas** [comment]
json doesn't support standard representation for dates. 
You should receive it as a string and parse it on the server-side.

**Comment by SaadManai** [comment]
Can you give me a sample of how to receive it? That is what I've been trying to do but I'm stuck. Thanks

**Comment by SaadManai** [comment]
I have fixed the issue. Thank you for your help
