### ISSUE TITLE
Cross-site Scripting (XSS) when inserting / updating a row

### ISSUE THREAD

**Issue by incyclum** [tabalinas/jsgrid#994]
Writing <script>alert('XSS');</script> in a text cell and saving executes it. Works every time when the row is shown (displaying data after page reload, sorting up/down or page switching).

**Comment by incyclum** [comment]
Related to #481

**Comment by abhimishra18** [comment]
I have added validator to check for < or > symbol and it works. you may change regex to check other symbols
{ 
            				  		    validator: "pattern",
            							message: function(value, item) {
                							return 'your error message';
            							},
            							param: "^[^<>]*$"            						              						
            						}

**Comment by tabalinas** [comment]
Duplicate of #481
