### ISSUE TITLE
jsGrid does not completely respect a field's "editing" configuration value

### ISSUE THREAD

**Issue by davehayes** [tabalinas/jsgrid#995]
This is a feature request and a suggested workaround until the feature actually exists.

Consider editing a row. Each field (column) appears to have a customizable `editing` boolean which tells jsGrid whether to allow editing of that column within that row.

However, looking in `_createEditRow()` I see that this function doesn't care whether `editing` is set in the field's config or not. Regardless of the setting of `editing`, the `editTemplate()` for the field is inserted anyway even though the value of the control will not be used. What appears to the user is an editing control, in spite of setting `editing` to `false`. I do realize that the resulting control's value will not be used to change the content of that column, but I feel this behavior is really confusing to users (and some developers).

Thus, my feature request is that the `itemTemplate()` be used instead of the `editTemplate()` in `_createEditRow()` if `editing` is set to `false`.

At the moment, I can work around this by setting the `editTemplate` property of the config to this:

```javascript
function(value,item) {
        return Object.getPrototypeOf(this).itemTemplate.call(this, value, item);
};
```

along with setting the `editing` property of the same field to `false`. So this isn't a showstopper by any means, but I suspect the change is really small and easy.

**Comment by tabalinas** [comment]
The original idea was to allow field handling of `editing` field. That what happens in every built-in field implementation. What if you wish to have some third representation for non-editable field (and not show itemTemplate)? 
I agree that your proposal makes total sense, but it means less flexibility.
Currently, implementing this would cause a huge breaking change, so we can't afford it.
